### ISSUE TITLE
Any way to select specific books?

### ISSUE THREAD

**Issue by webwizz2003** [rmcrackan/Libation#1]
Can you select specific books?  Am I missing something?  It looks like you have to back up all the books in your library at once.  It would be nice to be able to select the books you want to back up.

Thanks for making this.  It's coming along nicely.

**Comment by rmcrackan** [comment]
Thanks for taking a look. I've got good news and bad news. You didn't miss anything, I just hadn't created that feature yet. I love the idea though so I created it today.

Now for the bad news: something about the latest Microsoft update (Visual Studio 16.4, Core 3.1) broke publishing. Ironically, this upgrade was supposed to be a *more* stable version of Core. I'm keeping an eye on an online thread where someone is already addressing this with them.

As soon as I can publish, this feature will be available in [v3.1-beta.9](https://github.com/rmcrackan/Libation/releases/tag/v3.1-beta.9). Or if you're comfortable with code, you can download it and run locally to get this feature immediately.
