### ISSUE TITLE
Activationbytes Lib

### ISSUE THREAD

**Issue by JKamsker** [rmcrackan/Libation#10]
I've created a free service which resolves the activation bytes of any hash possible.
It's netstandard 2.0 so it should be compatible.

Nuget package: https://www.nuget.org/packages/Aax.Activation.ApiClient/1.0.0
How to use: https://github.com/JKamsker/OSAC/blob/master/OSAC/MainWindow.xaml.cs#L172

If you won't incorperate the service into the program, you could hint the user at the free webservice: https://audible-tools.github.io/

Please note, that neither the webservice nor the webapi are guaranteed to be online 100%, so this feature should be optional and all values should be cached.

**Comment by rmcrackan** [comment]
Libation handles this locally in a similar manner so I don't intend to switch. However, I love that you're providing other free options to people. I host the AudiobookHub resource page for tools like ours. I added your links under 'drm removal': https://github.com/rmcrackan/AudiobookHub

Thanks for adding to the toolset for people who want to use their books their own way. I'm a big fan of all such efforts, esp other solo developers.

**Comment by mkb79** [comment]
Hi,

[here](https://github.com/mkb79/Audible/blob/master/examples/get_activation_bytes.py) you can find a script for python to retrieve activation bytes by authenticating to audible. 

Greets

**Comment by rmcrackan** [comment]
> [here](https://github.com/mkb79/Audible/blob/master/examples/get_activation_bytes.py) you can find a script for python to retrieve activation bytes by authenticating to audible.

I do a rainbow lookup. It's technical and time consuming and works locally. You cut the gordian knot entirely -- I love it!
