### ISSUE TITLE
Scan Library take much longer than it used to.

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#100]
As the title says, something about library scanning is taking much longer than it used to
Downloading the library content through the Api is as fast as it ever was, but after download, CPU usage goes to 100% on one core and hangs for about 5-10 seconds.

**Comment by rmcrackan** [comment]
I saw that once earlier today too and now I can't reproduce it. Does it happen for you every time?

**Comment by Mbucari** [comment]
I repeatedly get 5 seconds, and it looks like the DB calls are the culprit.

![image](https://user-images.githubusercontent.com/37587114/131944235-3e566a83-4cb5-4f7b-955c-4d87700e0c09.png)

**Comment by rmcrackan** [comment]
I have one change ready. Much more could be done with this area but I think I'm proving how bad I am with EF. I'll release mine along with your mp3 fix when it's ready.

**Comment by Mbucari** [comment]
Still working on this... Do you know if you can specify a configuration to build with rohith/publish-nuget@v2?  It's overriding my csproj config.

**Comment by rmcrackan** [comment]
The yml at the bottom of this page specifies config in the build step and use rohith/publish-nuget@v2 to publish to nuget

**Comment by Mbucari** [comment]
OMG. So after HOURS of fiddling with this, I discovered a bug in nuget! It doesn't like the version number 1.0.4. Jesus...

**Comment by rmcrackan** [comment]
> It doesn't like the version number 1.0.4

Now *that's* a weird one

**Comment by Mbucari** [comment]
Correction, version # 0.1.4 causes the bug.

Version 0.1.8 is posted and working.

Handling those native libraries properly proved impossible, so I embedded them as a resource. It works and I no longer care.

Also, the rohith/publish-nuget action builds the project and builds the nuget package with the "Release" configuration override.  There's no way to choose a different build configuration. So I forked that project and added BUILD_CONFIGURATION and BUILD_PLATFORM options.

https://github.com/Mbucari/publish-nuget

If you want to use it, just replace  ```rohith/publish-nuget@v2``` with ```Mbucari/publish-nuget@master```

**Comment by rmcrackan** [comment]
Thanks! New ver released with this

**Comment by rmcrackan** [comment]
I can't figure out the 0.1.4 thing but I see what you mean about him having hardcoded 'release'. That's a reasonable default but it shouldn't be hardcoded.

**Comment by Mbucari** [comment]
> 
> 
> I can't figure out the 0.1.4 thing 

When I was making nuget packages with version 0.1.4, they would build without error but would fail to import into a project.
