### ISSUE TITLE
Libation not starting of freezing/not responding right after start

### ISSUE THREAD

**Issue by Skinopolus** [rmcrackan/Libation#1003]
[_Log202410.zip](https://github.com/user-attachments/files/17359367/_Log202410.zip)

**Comment by rmcrackan** [comment]
Thank you very much for your log file. I believe your account settings file may be corrupted. In the same folder where the log lives, delete the file `AccountsSettings.json`. Restart Libation and re-add your account(s) under settings. You'll be prompted to login again on your next scan.

**Comment by Skinopolus** [comment]
Thank you so much for the quick reply and fix!
