### ISSUE TITLE
Download & Decrypt: Decrypt Failed

### ISSUE THREAD

**Issue by RooterPwnage** [rmcrackan/Libation#1010]
**Describe the bug**
I have 70+ AudioBooks with most of them downloading successfully, however, 6 of them will not download & decrypt.

**To Reproduce**

1. Go to 'Visible Books'
2. Click on 'Liberate'
3. Click on 'Queue Log'

**Expected behavior**
Books to download & be decrypted

**Platform**
Windows 11, Libation 11.1.0.1

**Queue Log (within app)**
10/16/2024 5:11 PM	Download & Decrypt Step, Begin: [B089DK8589] Dark NLP: The Beginner’s Guide to the Essential of Neuro Linguistic Programming. The Secrets on How to Use Dark Psychology, Influence, Persuasion and Manipulation. Body Language to Analyze People.
10/16/2024 5:11 PM	Download & Decrypt Step, Completed: [B089DK8589] Dark NLP: The Beginner’s Guide to the Essential of Neuro Linguistic Programming. The Secrets on How to Use Dark Psychology, Influence, Persuasion and Manipulation. Body Language to Analyze People.
10/16/2024 5:11 PM	Download & Decrypt:  Decrypt failed
10/16/2024 5:11 PM	ERROR. All books have not been processed. Most recent book: processing failed
10/16/2024 5:11 PM	Download & Decrypt Step, Begin: [B08XWNDBLZ] Dark Psychology and Manipulation: Discover 40 Covert Emotional Manipulation Techniques, Mind Control, Brainwashing. Learn How to Analyze People, NLP Secret and Science of Persuasion to Influence Anyone
10/16/2024 5:11 PM	Download & Decrypt Step, Completed: [B08XWNDBLZ] Dark Psychology and Manipulation: Discover 40 Covert Emotional Manipulation Techniques, Mind Control, Brainwashing. Learn How to Analyze People, NLP Secret and Science of Persuasion to Influence Anyone
10/16/2024 5:11 PM	Download & Decrypt:  Decrypt failed
10/16/2024 5:11 PM	ERROR. All books have not been processed. Most recent book: processing failed
10/16/2024 5:11 PM	Download & Decrypt Step, Begin: [198264107X] Unf*ck Your Intimacy: Using Science for Better Relationships, Sex, and Dating
10/16/2024 5:12 PM	Download & Decrypt Step, Completed: [198264107X] Unf*ck Your Intimacy: Using Science for Better Relationships, Sex, and Dating
10/16/2024 5:12 PM	Download & Decrypt:  Decrypt failed
10/16/2024 5:12 PM	ERROR. All books have not been processed. Most recent book: processing failed
10/16/2024 5:12 PM	Download & Decrypt Step, Begin: [1250245788] Radical Candor: Fully Revised & Updated Edition: Be a Kick-Ass Boss Without Losing Your Humanity
10/16/2024 5:12 PM	Download & Decrypt Step, Completed: [1250245788] Radical Candor: Fully Revised & Updated Edition: Be a Kick-Ass Boss Without Losing Your Humanity
10/16/2024 5:12 PM	Download & Decrypt:  Decrypt failed
10/16/2024 5:12 PM	ERROR. All books have not been processed. Most recent book: processing failed
10/16/2024 5:12 PM	Download & Decrypt Step, Begin: [1400222729] The 360 Degree Leader: Developing Your Influence from Anywhere in the Organization
10/16/2024 5:12 PM	Download & Decrypt Step, Completed: [1400222729] The 360 Degree Leader: Developing Your Influence from Anywhere in the Organization
10/16/2024 5:12 PM	Download & Decrypt:  Decrypt failed
10/16/2024 5:12 PM	ERROR. All books have not been processed. Most recent book: processing failed
10/16/2024 5:12 PM	Download & Decrypt Step, Begin: [1982647965] The Entrepreneur Roller Coaster: Why Now Is the Time to #JointheRide
10/16/2024 5:12 PM	Download & Decrypt Step, Completed: [1982647965] The Entrepreneur Roller Coaster: Why Now Is the Time to #JointheRide
10/16/2024 5:12 PM	Download & Decrypt:  Decrypt failed
10/16/2024 5:12 PM	ERROR. All books have not been processed. Most recent book: processing failed

**Comment by rmcrackan** [comment]
Thank you for your log file. I see a few possibilities, in order of likelihood:

* Some of these books has an outrageously long. (Example: `Z:\Books\Libation\LibationTemp\DecryptInProgress\The Entrepreneur Roller Coaster- Why Now Is the Time to #JointheRide [1982647965] - 20 - Chapter 2- Secure Your Shoulder Harness- You Will Be Thrashed About (Severely at Times)- Embrace Your Freaky Nature- Five Strategies- 1. Stop Being Likable.m4b`) Maybe try a different options in Settings > Download/Decrypt tab > Custom file naming
* For Plus titles, make sure they're still in your library -- either on the website or if you can access them via the official app
* Is the Z drive accessible? Or might it have become disconnected sometime during download?

**Comment by RooterPwnage** [comment]
Changing the audio file custom file naming for the audio files, within the app, from :
<title> [<id>] - <ch# 0> - <ch title>

to:
<title short> - <ch# 0> - <ch title>

seems to have fixed the issue.

Z: is my NAS, it was fully connected and never disconnected (that I recall).

I'm fairly new to bug reporting with GH, and so I'll let you close it or file it however you'd like.  But the issue is resolved.  Thank you!

**Comment by rmcrackan** [comment]
Thanks for following up. I'm glad this worked for you
