### ISSUE TITLE
Cannot download audiobook files - processing failed

### ISSUE THREAD

**Issue by dainaar** [rmcrackan/Libation#1020]
**Describe the bug**
Library is imported, but audiobook files will not download. Each attempt fails with error: "processing failed"

**To Reproduce**
1. Go to menu bar
2. Click on import
3. Scroll down to Scan Library
4. Libation attempts to download files
5. See error

**Expected behavior**
Files downloaded ready for converting

**Screenshots**
<img width="1072" alt="Screenshot 2024-10-25 at 13 49 57" src="https://github.com/user-attachments/assets/d82c491b-32e3-4a41-be8a-caec55ce9256">

**Platform**
Mac 14.6.1

**Log Files**
[_Log202410.log](https://github.com/user-attachments/files/17522283/_Log202410.log)

**Comment by rmcrackan** [comment]
Thank you for the log. I'm so sorry about this bug. The audio converter (m4b => mp3) seems to have a bug for mac. I'll include a reference to this ticket with the existing issues. I'll close this one so there's 1 central place to track.

**Comment by rmcrackan** [comment]
Please try this pre-release and let me know if it helps your issue : https://github.com/rmcrackan/Libation/releases/tag/v11.5.2

**Comment by dainaar** [comment]
It's working perfectly, thank you!

**Comment by rmcrackan** [comment]
@dainaar Thanks for the update. I'm glad it's working again.

@Mbucari Success! Thanks again.
