### ISSUE TITLE
Unexpected Error- Unable to load my books

### ISSUE THREAD

**Issue by Bado284** [rmcrackan/Libation#1024]
Hello I used Libation without a problem for months now, but today I got this error. Personally I am not a techsavy guy when it comes to these stuff so I am completely lost.

**The ERROR:**

SQLite Error 14: 'unable to open database file'.

   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReader(RelationalCommandParameterObject parameterObject)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.InitializeReader(Enumerator enumerator)
   at Microsoft.EntityFrameworkCore.Storage.NonRetryingExecutionStrategy.Execute[TState,TResult](TState state, Func`3 operation, Func`3 verifySucceeded)
   at Microsoft.EntityFrameworkCore.Query.Internal.SingleQueryingEnumerable`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToList()
   at ApplicationServices.DbContexts.GetLibrary_Flat_NoTracking(Boolean includeParents) in D:\a\Libation\Libation\Source\ApplicationServices\DbContexts.cs:line 18
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LibationWinForms.Program.<>c__DisplayClass1_0.<<Main>b__0>d.MoveNext() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 88
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Object, IntPtr*)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)

**The Log files:**
[_Log202403.zip](https://github.com/user-attachments/files/17534022/_Log202403.zip)
[_Log202405.zip](https://github.com/user-attachments/files/17534023/_Log202405.zip)
[_Log202406.zip](https://github.com/user-attachments/files/17534024/_Log202406.zip)
[_Log202408.zip](https://github.com/user-attachments/files/17534025/_Log202408.zip)
[_Log202409.zip](https://github.com/user-attachments/files/17534026/_Log202409.zip)
[_Log202410.zip](https://github.com/user-attachments/files/17534027/_Log202410.zip)
[_Log202410_001.zip](https://github.com/user-attachments/files/17534028/_Log202410_001.zip)

I am on Windows 10

**Comment by rmcrackan** [comment]
Thank you very much for your logs. Can you attach a list (or screenshot) of all files that are in the folder with your log files?

**Comment by Bado284** [comment]
Okay I have to say after I wrote this msg I deleted everything and tried to a fresh install. It still gave me the same error. So now I will attach the new log+ requested screenshot
[_Log202410.zip](https://github.com/user-attachments/files/17535698/_Log202410.zip)
![Ekran görüntüsü 2024-10-28 020830](https://github.com/user-attachments/assets/b722fed8-64e1-4ca7-b375-916f689b1a2f)

**Comment by rmcrackan** [comment]
When you deleted everything, does that include the file `LibationContext`? This is the database file that the log is saying it can't open.

**Comment by Bado284** [comment]
yes I  did delete it but right after it I also did a fresh install, so if the old one was corrupted the new one should be okay to replace it. But it sadly still did not work. And it is still giving me the same error. Maybe if you can send that specific file alone to me,  I can replace it  with what i have and that can maybe fix it ?

**Comment by rmcrackan** [comment]
The database file is freshly created by Libation. If it's repeatedly getting file access errors, there must be something else at play here. `C:\Users\PC\Libation` looks like a really standard user folder. Are you logged into windows as this "PC" user?

**Comment by Bado284** [comment]
Yes, there is only 1 user on this windows and it is "PC"

**Comment by rmcrackan** [comment]
So here's the problem -- if you've already deleted that database file, and it recreated it again in a way that isn't readable, then I'm not sure where to go from here. It can't be a permissions issue with that folder because Libation writes to the other files fine, including the log. You're using the most tested version of Libation and I've never seen this before. Maybe try deleting it again and grabbing one of the more recent pre-releases -- https://github.com/rmcrackan/Libation/releases . We can see if the latest pre-release creates the database in a usable way.

**Comment by Bado284** [comment]
man this honestly sucks.. nothing I can do works it is so frustrating. I deleted it again and tried the pre-release still did not work. At this point I am questioning my deleting skills. You basically delete the Folder you unziped and also the folder  with log files one. ANd that should be it. But after deleting them and re-downloading and opening the .exe still it gives me the same error. From the last time I used my pc I changed nothing out of no where it started to not work. The only thing that I can think of somehow a Windows update messed up with this, but that I cant wrap my head around.

**Comment by rmcrackan** [comment]
We're obviously missing something.

* Are you running a 64-bit operating system?
* The log contains some errors about not being able to load a few resources. These are usually harmless so I largely ignore them. Maybe they aren't harmless this time. They all relate to Turkey so I assume that's your PC's locale. That shouldn't be a problem but Turkey is notorious for all of this tiny things it does differently which can cause unexpected programming problems so I can't discount that as a possibility.
* A newer pre-release version of Libation might help but it sounds like you tried that already.
* You could try Windows Chardonnay instead of Classic. This shouldn't make a difference, but then again, none of this *should* be happening.

**Comment by Bado284** [comment]
Sorry for the late reaponse. Yes  I am  running 64 bit, and yes I am from Turkey. I also did tried pre release and the chardonay version sadly both did not work.

If you think its network routing related i can try to use a vpn? 

I also use my pc in Turkish, i  will change the language to english and try to run it again ( i know this sounds weird but couple of months ago a game called Black Myth Wukong was released and I was experincing bugs just because the language of my PC was set to Turkish once I canged that to english everything was fixed)

I will report you back my findings if I get a positive result.

**Comment by Bado284** [comment]
Hey man, its me again I solved the problem.. It was just an easyfix that didnt came to my mind because it was just too easy. So.... All I had to was "run as adminastrator" xD I know it is so dumb of me to not think of it but hey at least we know the fix now :D
