### ISSUE TITLE
Skip tag a book - How to mark a book not to be downloaded

### ISSUE THREAD

**Issue by fsafq41** [rmcrackan/Libation#1025]
So far, I couldn't find such functionality in the app or in the enhancement request list.

In my library, I have a number of books I have already read and therefore I am not interested in downloading.
Is there a way to clearly tag/mark these books so Libation does not download them.

**Comment by rmcrackan** [comment]
Sure. Just right-click and change its status to ‘downloaded’. This status is how Libation knows whether to download a book.

**Comment by CLHatch** [comment]
> Sure. Just right-click and change its status to ‘downloaded’. This status is how Libation knows whether to download a book.

It might be worth it to be able to set an "ignore" flag, instead of "lying" to the system and saying it's been downloaded?  I know there's the trash bin, but that removes it from view completely.

**Comment by fsafq41** [comment]
Yes I know about this and in fact this is  exactly how I am doing it to skip books I don’t want to download.
But of course I can’t differentiate books that are really downloaded vs skipped. Hence my question.

**Comment by CLHatch** [comment]
> Yes I know about this and in fact this is exactly how I am doing it to skip books I don’t want to download. But of course I can’t differentiate books that are really downloaded vs skipped. Hence my question.

You may not be aware of the "trash bin".  If you right-click on a book, you can select "Remove from library".  This isn't a permenant delete, it places it in a "trash bin", and it can be restored later if you want.  But as I mentioned, this actually removes the book from the list, you can only see it in the trash bin.

**Comment by rmcrackan** [comment]
Thanks for the clarification. I think I understand now. You could use the trash bin as @CLHatch mentioned. Also, you can use tags. In each book's row, the right-most column lets you click to add tags. You could do something like using `skipped`, search for `-[skipped]` and use this as your default search.
