### ISSUE TITLE
crashing app

### ISSUE THREAD

**Issue by rigelnika** [rmcrackan/Libation#1027]
**Describe the bug**
crashing app

**To Reproduce**
opened app several times and same result

**Expected behavior**

**Screenshots**

**Platform**

Windows 7

**Log Files**
Attach your Libation log file here.
[_Log202410_001.zip](https://github.com/user-attachments/files/17576668/_Log202410_001.zip)

**Comment by rmcrackan** [comment]
Thank you for the log. Your hard drive might be full: `database or disk is full`
Please move some books off and try again.
