### ISSUE TITLE
feat: libby support

### ISSUE THREAD

**Issue by csells** [rmcrackan/Libation#1031]
**Is your feature request related to a problem? Please describe.**
Your app works great for Audible! Can you make it work just as well for [Libby](https://libbyapp.com/), too?

**Comment by rmcrackan** [comment]
I am in full support of someone doing this! Unfortunately, it will not be me. There is simply too much work for the small payoff. Audible and their drm is 2/3 of the audiobook market. Everyone else is a tiny sliver. Sorry, it’s just not worth the effort me.
