### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by Crysthera** [rmcrackan/Libation#1032]
[_Log202411.zip](https://github.com/user-attachments/files/17608721/_Log202411.zip)
**Describe the bug**
I have previously downloaded my library. After purchasing a new book on Audible, I opened Libation and clicked Import > Scan Library.  The pop up error says "Error importing library. Please try again. If this still happens after 2 or 3 tries, stop and contact a" and the rest of the error message is cut off with no apparent way to resize the window or get the rest of the error.

I tried restarting the application and manually downloading a few times with the same error.

**To Reproduce**

1. Go to Import > Scan Library
2. See error

**Expected behavior**
This is my second time using the application.  The auto download either didn't work or was scheduled at some cadence I couldn't look up, so I expected manually downloading to retrieve the new book.

**Screenshots**
I attached the log files.

**Platform**
Windows 10 home
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

Thank you!

**Comment by rmcrackan** [comment]
Thank you for your log file. This is head-scratcher. The error implies your computer can't write to a zip file. But this only zip file is this log file itself -- which it wrote to. First thing to try is delete all Libation log files and restart Libation. If that doesn't work, please try a more recent pre-release version and see if it works -- https://github.com/rmcrackan/Libation/releases

**Comment by Crysthera** [comment]
Huh.  I shift deleted all the log files in C:\Users\<username>\Libation, as well as LibraryScans.zip, rebooted the application, and it immediately started downloading my new book!

Thanks so much!!

**Comment by rmcrackan** [comment]
Thank you for your update. This bug had me completely flummoxed.
