### ISSUE TITLE
Add support for <if audible subtitle>

### ISSUE THREAD

**Issue by filviu** [rmcrackan/Libation#1033]
Hi, first of all apologies for (ab)using the Issues for what is half question half feature request.

I'm trying to understand how to setup so I don't get extra separators when the <audible subtitle> tag is missing. I read NamingTemplate.md but either I'm thick or this is not yet supported.

Explanation:

My naming template looks like:

`<year> - <audible title> - <audible subtitle> {<first narrator>}`

This works fine but books that have no subtitle get folder names that look like `2024 - Boook Title -  {Narrator}` 

Is there anyway to only add the second `-` and a space after only if the subtitle actually exists?

Thanks !

**Comment by filviu** [comment]
I just realized I can use <title> instead of both and the character replacement to replace `:` with ` -`

**Comment by rmcrackan** [comment]
👍 I'm glad you figured it out. Thanks for the follow-up
