### ISSUE TITLE
docker: Error when using SLEEP_TIME - "integer expression expected"

### ISSUE THREAD

**Issue by charltonstanley** [rmcrackan/Libation#1048]
**Describe the bug**
SLEEP_TIME no longer works. It seems there is an issue with the latest version of libation.sh

**To Reproduce**

1. Set the `SLEEP_TIME` docker variable to `10m`
2. launch the container
3. error is returned at the end of the run

```
libation.sh line 164 [: 10m: integer expression expected
```

I believe it to be related to this section of code:
https://github.com/rmcrackan/Libation/blob/ed87ded77afa9684e7aec34608e57eab15405ba2/Docker/liberate.sh#L159-L169

I'm not really a bash scripter but I believe `-eq` should be `==` on line 164.  I believe the same is true for other places in the file where the same variable `SLEEP_TIME` is being compared against `-1`.

I reverted to pre-release 11.5.1 to get back up and running.

Thanks!

**Comment by rmcrackan** [comment]
Thank you for catching this. Would you mind checking if this fix worked -- https://github.com/rmcrackan/Libation/releases/tag/v11.5.5

**Comment by charltonstanley** [comment]
@rmcrackan checked it out over the weekend and it works great! Thanks for the quick fix!
