### ISSUE TITLE
Able to download all but 2 titles in my library

### ISSUE THREAD

**Issue by nikguhl89** [rmcrackan/Libation#1051]
My main audible account is downloading all books except for 2. Both books can be downloaded in the audible app, but do not import into Libation. I do not receive an error, they just don't import. Any help would be greatly appreciated.

**Comment by rmcrackan** [comment]
I'd be happy to look into this. Please attach your latest log file to this ticket. To find it: in Libation > Settings, near the bottom is a button for "Open log folder"

**Comment by nikguhl89** [comment]
[](url)
[_Log202411.zip](https://github.com/user-attachments/files/17836189/_Log202411.zip)
this if for nik.guhl89@gmail.com account the 2 books names are hardboiled horror and demons of king solomon

Thank you

**Comment by rmcrackan** [comment]
Are these owned books, or borrowed via the plus catalog?

**Comment by nikguhl89** [comment]
Yes they are both owned books

**Comment by rmcrackan** [comment]
In the 'stop light' column in the grid, do these books have the red stop light? Or a special error icon? If a special error, right-click and set status to 'not downloaded'. If it's already a red stop light ... I'm not sure. This hasn't really happened before. Are these books actually part of another account which isn't currently logged into Libation?

Barring other ideas, the best idea I have is: give it a day or 2 and try again then send me the new log. Some audible issues resolve themselves in that period of time. I can only guess that when these things happen, their official app knows fallback paths which I can't replicate. Unfortunately I'm also leaving town for a week starting in a few days so I'll be unable to check the new logs for a while.

**Comment by nikguhl89** [comment]
So I just looked into this again and checked my trash and I had actually
removed the books from what was showing when I first signed in with the
account. I am so sorry for bothering you with all of this and thank you so
much for all of your help.

**Comment by rmcrackan** [comment]
Oh man this is such a relief. I truly could not imagine what I was missing. Thank you for following up. And it was no trouble at all :)
