### ISSUE TITLE
User ID change breaks automation

### ISSUE THREAD

**Issue by jacoknapp** [rmcrackan/Libation#1055]
With the recent docker uid changes not honoring the pid and gid set in the environment variables, it breaks any automation that this may be linked to. By setting this change in output file permissions, it ends up dictating the way that the media folders have to be configured permissions wise, which means either more automation to solve moving around the files, or having to retool the entire permissions folder structure for every app that might be dependent on it. 

That said, this is awesome work in general, and generally speaking the app is rock solid! Thank you so much for the work that you've done so far!

**Comment by rmcrackan** [comment]
@pixil98 -- any ideas?

**Comment by jacoknapp** [comment]
Quick update, as a workaround I have a scheduled a GitHub action nightly that rebuilds the docker container on my local gitea instance and switching the user to the one I want. I just pop the newest release off of the GitHub api, and use that tag as my base.

**Comment by pixil98** [comment]
@jacoknapp can you tell me more about your setup? The previous builds shouldn't have been respecting any wishes to run as a non-root user or group. You should now be able to specify the user/group to run as without needing to rebuild the image. For instance, in docker compose, you could set `user: "<UID>:<GID>"` .
