### ISSUE TITLE
Closes/Crashes(?) After Any Save/Close Action

### ISSUE THREAD

**Issue by HikariNoKitsune** [rmcrackan/Libation#1065]
**Describe the bug**
Every time you click "Save", "Close", etc on any window (Account, Settings, etc), the entire application closes (or crashes maybe?). Nothing in the Log zip seems to state any reason for a close.

**To Reproduce**
Open up settings. Click Save. 

1. Go to 'Settings'
2. Click on 'Save'
3. Application closes.

**Expected behavior**
The "Settings" window closes, but main application stays open.

**Platform**
Windows 11
Using Libation.11.6.1-windows-chardonnay

**Log Files**
[_Log202412.zip](https://github.com/user-attachments/files/18012263/_Log202412.zip)

**Comment by rmcrackan** [comment]
Thank you for the log file. This is super weird. Does this happen with the classic version also?

**Comment by HikariNoKitsune** [comment]
I've never tried the classic version. It also was doing this when I was trying to get my account set up for it as well. But I was able to bypass that by grabbing the account settings from my backup. (This is a fresh install of Windows 11, and I had backed up the previous install thankfully, so was able to grab the account settings from it)

**Comment by rmcrackan** [comment]
Nice. Does the Classic version also crash?

**Comment by HikariNoKitsune** [comment]
Sorry am at work (remoting to my desktop at home atm to use libation lol). I'll give Classic a go here in a few minutes :D

**Comment by rmcrackan** [comment]
@CLHatch , @cbordeman , @wtanksleyjr , @Mbucari -- hey frequent users. Is someone willing to see if the latest pre-release of Chardonnay works for you?

**Comment by slavakurilyak** [comment]
v11.6.1 is crashing on my Apple M1 running on macOS Sequoia 15.2 Beta

**Comment by rmcrackan** [comment]
Thanks for checking. 11.6 upgraded several major components that I have no control over. This is going to be a nightmare to debug. I guess the next major release won't be out for even longer now :(

**Comment by HikariNoKitsune** [comment]
I'm so sorry D: Not really sure what to say other than that... I know it isn't particularly my fault that this is happening to the application, but being the 'bearer of bad news' still feels bad. I'll be rooting for all of you, and will try to be around if any sort of testing or anything is wanted/needed. I'm not the most responsive unless I get a notification from an email about a reply, but I'll try to check up on this just in case :D

**Comment by CLHatch** [comment]
> > @CLHatch , @cbordeman , @wtanksleyjr , @Mbucari -- hey frequent users. Is someone willing to see if the latest pre-release of Chardonnay works for you?
> 
> I think i might actually be on the latest Chardonnay version. But it sounds like it's only crashing when hitting "close" or "save" from account, settings, etc, which I haven't had to do in a while. I'll check later tonight and let you know.

Appears I was actually on 11.5.5.  Updated to 11.6.1, and can confirm the crash here as well (Windows Chardonnay).  I see that @Mbucari has a fix, so I'll try that when it gets released.

**Comment by cbordeman** [comment]
@CLHatch What fix did @Mbucari have?  I don't see it.

**Comment by CLHatch** [comment]
> @CLHatch What fix did @Mbucari have? I don't see it.

https://github.com/rmcrackan/Libation/pull/1066

**Comment by rmcrackan** [comment]
Thank you again @Mbucari !!

Can y'all please see if Chardonnay is fixed for you in this pre-release -- https://github.com/rmcrackan/Libation/releases/tag/v11.6.2

**Comment by CLHatch** [comment]
> Thank you again @Mbucari !!
> 
> Can y'all please see if Chardonnay is fixed for you in this pre-release -- https://github.com/rmcrackan/Libation/releases/tag/v11.6.2

Appears to have fixed it for me.  Running Windows 11.

**Comment by rmcrackan** [comment]
Thanks all for your help. I'm going to call this a success.
