### ISSUE TITLE
Docker build_and_push release step failing for .net9

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#1067]
@charltonstanley , @pixil98 , @jwillikers , @aaron

Can any of you fine docker folks tell why this step always fails since the .net upgrade: Docker build_and_push

**Comment by pixil98** [comment]
The Dockerfile is still using version 8 of the sdk and runtime images. I'll submit a PR to fix it shortly.

**Comment by rmcrackan** [comment]
Thank you so much! Your fix is in -- https://github.com/rmcrackan/Libation/releases/tag/v11.6.3
