### ISSUE TITLE
Login with Amazon account

### ISSUE THREAD

**Issue by greencardamom** [rmcrackan/Libation#1069]
Audible has two methods of login.

Old school: before Audible was purchased by Amazon, there is a login ID (not an email address) and password.

New school: after Audible was purchases by Amazon, it is your Amazon credentials ie. email address and Amazon password.

Audible supports both methods of login. I am "Old School" and the Libation login process is not working for Old School users.

**Comment by rmcrackan** [comment]
When you select your region, look at the bottom of the list. There are "pre-amazon" regions for old school username logins.

**Comment by greencardamom** [comment]
Got it, thank you!
