### ISSUE TITLE
Feature Request - make a mobile version (android/ios)

### ISSUE THREAD

**Issue by jhicken** [rmcrackan/Libation#107]
I know this is totally a hobby project. But I thought I would see what your thoughts are on this. I know for me... I just really dislike the audible app. So I use this to dump my books into a format that a different reader can use. And then I have to copy them back to my mobile device. It would be really cool to have this app running on my mobile device so that I could just do everything on there. Instead of jumping back and forth between devices. 

Thoughts?

**Comment by rmcrackan** [comment]
Supporting various platforms are among the top requests. However I have neither the time nor experience to pull this off. I've done my best to keep the guts platform-agnostic though so if someone wants to contribute and integrate a x-platform UI, it will be possible.

For now though: sorry; no such plans.
