### ISSUE TITLE
Processiong failed. Error: Invalid Argument

### ISSUE THREAD

**Issue by tomnmillie** [rmcrackan/Libation#1083]
**Describe the bug**
Some books do not download, but finish with an invalid argument error for a location other books successfully used.

**To Reproduce**

1. Click on book to add to queue
2. Queue entry shows error after 99% completion
3. Click Queue Log tab
4. Scroll to see cause

**Expected behavior**
Expect book to successfully process like most of the other books.

**Screenshots**
![image](https://github.com/user-attachments/assets/2fd12e09-b37c-476b-925e-30e18e662473)

**Platform**

Linux Mint 21.3

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach the log file?

**Comment by tomnmillie** [comment]
> Sorry about this. Can you attach the log file?

Is that the _LogFoo.zip file in the main dir where the library is?

**Comment by rmcrackan** [comment]
Yep. Please drag/drop the latest one into this ticket.

**Comment by tomnmillie** [comment]
[_Log202412.zip](https://github.com/user-attachments/files/18185937/_Log202412.zip)

**Comment by tomnmillie** [comment]
aye, it was the colon. thanks for the help. thanks for the work. thanks for the software.

**Comment by rmcrackan** [comment]
:) you're welcome. Merry Christmas!
