### ISSUE TITLE
Libation naming books wrong

### ISSUE THREAD

**Issue by johnlescault** [rmcrackan/Libation#1085]
**Describe the bug**
I am running Libation on multiple computers due to having multiple accounts. (trying to download faster). On one of them, the books get named like `BEORYG~H` or `B42LPC~O` as examples. (the folder and the M4B/JPG are named that)

I am using the following formatting: `<if series-><series>/Book <series#> - <-if series><title> [<id>]`

**To Reproduce**
Unfortunately I don't know how. It is only occuring on one computer

**Platform**
Linux - Kubuntu 22.04

**Log Files**
Where are they located?

**Comment by rmcrackan** [comment]
Libation allows as many accounts on as you'd like. You're of course welcome to keep running on multiple computers if that's your jam.

The template you specified: is that for 'how to format the folders' or 'how to format the audio files'?

RE log file location: when you open Libation > Settings, on the first tab there's a button toward the bottom: `Open log folder`. Please attach the latest to this ticket.

**Comment by johnlescault** [comment]
Sorry for the delay in response, Holiday time is busy!

[_Log202412.zip](https://github.com/user-attachments/files/18268337/_Log202412.zip)

![image](https://github.com/user-attachments/assets/095f1dac-9c89-4c21-bfca-c44966b50dd8)

![image](https://github.com/user-attachments/assets/075afef4-26bd-4cef-ad8d-b3a3781215cb)

**Comment by CLHatch** [comment]
> Sorry for the delay in response, Holiday time is busy!
> 
> [_Log202412.zip](https://github.com/user-attachments/files/18268337/_Log202412.zip)
> 
> ![image](https://private-user-images.githubusercontent.com/17369501/399135271-095f1dac-9c89-4c21-bfca-c44966b50dd8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NTQxMDMsIm5iZiI6MTczNTQ1MzgwMywicGF0aCI6Ii8xNzM2OTUwMS8zOTkxMzUyNzEtMDk1ZjFkYWMtOWM4OS00YzIxLWJmY2EtYzQ0OTY2YjUwZGQ4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDA2MzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVlM2JjOWVlZjcxZjRlMjIyNzFmMGYzZGZmNTgwZDU0MzljM2VlNTZmMDRiMDBmMTUwY2M4ODdjM2Q0NjY2Y2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.EUmF4afmuc1A-VeVk6bWHu7QqwJU0DR1SxsREfuFEYQ)
> 
> ![image](https://private-user-images.githubusercontent.com/17369501/399135298-075afef4-26bd-4cef-ad8d-b3a3781215cb.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU0NTQxMDMsIm5iZiI6MTczNTQ1MzgwMywicGF0aCI6Ii8xNzM2OTUwMS8zOTkxMzUyOTgtMDc1YWZlZjQtMjZiZC00Y2VmLWFkOGQtYjNhMzc4MTIxNWNiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI5VDA2MzAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlMGVhYmFhZjNhZjk5ZGQyMzVkZTI0MzM3NThjZjkxOGZlYjViYmJhMmYwOTc0Nzg5NjIyMjhiM2E3NjUxMDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.sJgggm6uFyFsQ5w4oY0hAvJVWJmrGYLIvQT2ayOpsHU)

This might just be a shot in the dark, but to me it looks like all the one's it's naming them wrong have a ":" in the title of the book.  And the way it's naming them wrong is the way Windows often handles long filenames.  So I'm guessing you are running Libation in Linux, storing to a Windows share?

Have you set up the illegal character replacement options to handle ":" in filenames?

![image](https://github.com/user-attachments/assets/78ef8c19-9f70-41a7-b6f4-84924b59cce1)

I personally have mine replace `:` with `꞉`, which is a Unicode equiv character that Windows can use.

Also, if it helps any, this is my naming pattern that lets you place books from multiple accounts into their own folders:

Folder:
`<if podcast->Podcasts\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[000.##]> - <-if series>(<pub date>) - <series> - <title> [<id>]<-if podcast><!if podcast->AudioBooks\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<year>) - <title> [<id>]<-if podcast>`

File:
`<audible title> [<id>]`

An example book with that format gets stored on my system as:
`C:\Users\CLHat\Libation\Books\AudioBooks\Audible\Chris\Anne McCaffrey; Elizabeth Moon\Planet Pirates Series\01 - (2020) - Sassinak꞉ The Planet Pirates Series, Book 1 [1094164399]\Sassinak [1094164399].m4b`

**Comment by johnlescault** [comment]
I am testing on two Ubuntu machines. One it works perfectly, the other one outputs this. I did not do any special character on the one that works - so I guess I would ask why it only fails on one machine?

Here are the full names (and folders of the badly named files, which it seems like you may be right.

GIMG59~D
George Carlin Reads to You: An Audio Collection Including Grammy Winners 'Braindroppings' and 'Napalm & Silly Putty' [B0711BV688]/George Carlin Reads to You: An Audio Collection Including Grammy Winners 'Braindroppings' and 'Napalm & Silly Putty' [B0711BV688].m4b

IU8WBS~1
It Never Ends: A Memoir with Nice Memories! [B08ZV9QBG1]/It Never Ends: A Memoir with Nice Memories! [B08ZV9QBG1].m4b"}

BD8GKX~F
Anty Boisjoly Mysteries/Book 2 - The Case of the Ghost of Christmas Morning: The Anty Boisjoly Mysteries, Book 2 [B09VKFV9DD]/The Case of the Ghost of Christmas Morning: The Anty Boisjoly Mysteries, Book 2 [B09VKFV9DD].m4b

**Comment by CLHatch** [comment]
> I am testing on two Ubuntu machines. One it works perfectly, the other one outputs this. I did not do any special character on the one that works - so I guess I would ask why it only fails on one machine?
> 
> Here are the full names (and folders of the badly named files, which it seems like you may be right.
> 
> GIMG59~D George Carlin Reads to You: An Audio Collection Including Grammy Winners 'Braindroppings' and 'Napalm & Silly Putty' [B0711BV688]/George Carlin Reads to You: An Audio Collection Including Grammy Winners 'Braindroppings' and 'Napalm & Silly Putty' [B0711BV688].m4b
> 
> IU8WBS~1 It Never Ends: A Memoir with Nice Memories! [B08ZV9QBG1]/It Never Ends: A Memoir with Nice Memories! [B08ZV9QBG1].m4b"}
> 
> BD8GKX~F Anty Boisjoly Mysteries/Book 2 - The Case of the Ghost of Christmas Morning: The Anty Boisjoly Mysteries, Book 2 [B09VKFV9DD]/The Case of the Ghost of Christmas Morning: The Anty Boisjoly Mysteries, Book 2 [B09VKFV9DD].m4b

My guess would be maybe the file system on the machine might be the difference?  Perhaps the other two systems are able to store `:` without conversion.

**Comment by johnlescault** [comment]
Hmm.. thanks for these replies, however respectfully I am not convinced. I ran the following: 

```
for char in '?' '*' ':' '<' '>' '|' '"' '/' '\0'; do
    touch "test${char}file" 2>/dev/null
    if [ $? -ne 0 ]; then
        echo "Character '${char}' is not allowed."
    fi
done
```

and only the / returned as a bad character. The : was accepted. 

I'm struggling with this one, one is running 22.1 (bad naming), the other is 24.04 so I can't see this creating many issues. It is accepting the filename afterall during the script.

Any other ideas by chance? I try to keep Libarate setting changes to minimum to make it easy to re-set up and resync. I'd hate for one machine to start saving things differently

**Comment by CLHatch** [comment]
> Hmm.. thanks for these replies, however respectfully I am not convinced. I ran the following:
> 
> ```
> for char in '?' '*' ':' '<' '>' '|' '"' '/' '\0'; do
>     touch "test${char}file" 2>/dev/null
>     if [ $? -ne 0 ]; then
>         echo "Character '${char}' is not allowed."
>     fi
> done
> ```
> 
> and only the / returned as a bad character. The : was accepted.
> 
> I'm struggling with this one, one is running 22.1 (bad naming), the other is 24.04 so I can't see this creating many issues. It is accepting the filename afterall during the script.
> 
> Any other ideas by chance? I try to keep Libarate setting changes to minimum to make it easy to re-set up and resync. I'd hate for one machine to start saving things differently

I could well be wrong, but what I think is happening is that it is storing the `:` "correctly", but it's doing it by making the modified name you are seeing.  Perhaps that 12TB drive is formatted as exFAT, which I believe doesn't support `:` directly.  I would just try going into the illegal character replacement table, and try having it replace `:` with `꞉` (you can copy/paste that second one into the table), and see if it then names them right.  If it does, then do the same on your other system, and the naming between the two systems will match.
`

**Comment by johnlescault** [comment]
That drive is ext4. I did try as you recommended (which was odd because the colon you gave me pasted as a ? on my machine).

That script I said that I tested with, when looking at those files on my "normal" machine, they are all "shortened filenames" as well (all of them!). I also noticed when looking at the folder on the "bad" machine, all the filenames are OK!

Both machines are set to en_CA.UTF-8 but I'm confident it is something on the one machine that is wrong now. Other than the en_CA.UTF8 locale, i'm not sure what else to look at though. Any ideas?

**Comment by CLHatch** [comment]
> That drive is ext4. I did try as you recommended (which was odd because the colon you gave me pasted as a ? on my machine).
> 
> That script I said that I tested with, when looking at those files on my "normal" machine, they are all "shortened filenames" as well (all of them!). I also noticed when looking at the folder on the "bad" machine, all the filenames are OK!
> 
> Both machines are set to en_CA.UTF-8 but I'm confident it is something on the one machine that is wrong now. Other than the en_CA.UTF8 locale, i'm not sure what else to look at though. Any ideas?

That is odd.  I'm not a Linux expert at all, but you did mention there is a difference in OS versions there.  Are you able to update 22.1 to 24.04?  Maybe something that was fixed in a more recent kernel is breaking the naming in the older system.

**Comment by johnlescault** [comment]
Yes that is what I'm going to do. I was due for a full reformat anyhow. Thank you for your help.

As I am convinced the issue is on my side and not Libation I will close this ticket! Thanks for the help!
