### ISSUE TITLE
Can't Enter Password

### ISSUE THREAD

**Issue by GermaricanMix** [rmcrackan/Libation#1088]
I just downloaded and installed the latest Libation version. I can enter my location and account email, but then nothing happens. From the tutorial I'm watching a window should pop up where I can enter my password, but it doesn't.  Would apprecite any help!

**To Reproduce**
Not sure but these are the steps I took
downloaded Libation.11.1.0-windows-chardonnay
installed
changed book location to different drive
changed download settings  to convert to mp3
went to account and entered US for location
entered email
clicked save
nothing happens beyond that

**Expected behavior**
window should pop up to enter password and connec to audible account

**Platform**
Laptop
Windows 11

**Log Files**
Not sure how to get this

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach your log file and I'll take a look. In settings, there's a button to open the log file's folder.

**Comment by wtanksleyjr** [comment]
The window only pops up once you click Liberate, try that.

**Comment by GermaricanMix** [comment]
> Sorry about this. Can you attach your log file and I'll take a look. In settings, there's a button to open the log file's folder.

is this what you're looking for?
[_Log202412.log](https://github.com/user-attachments/files/18215088/_Log202412.log)

**Comment by rmcrackan** [comment]
Like @wtanksleyjr said, try a Liberate. If that doesn't work, upload the new log and I'll see if it reveals anything.

**Comment by GermaricanMix** [comment]
> Like @wtanksleyjr said, try a Liberate. If that doesn't work, upload the new log and I'll see if it reveals anything.

Do you mean the 'Liberate' drop down between import and export? It says all books have been liberated. 

If you mean in the 'accounts' window - I don't see a Liberate option, just 'save' which I've been clicking

uploading a screen grab:

![Liberate01](https://github.com/user-attachments/assets/a1746be8-0aad-4be5-b559-e0e9251e6954)

**Comment by rmcrackan** [comment]
Sorry, I should have been more clear: not on that window. After you save and close that, look at the top bar: Import, Liberate, Export, ...

**Comment by rmcrackan** [comment]
Do'h, sorry -- do a scan first. It's under Import.

**Comment by GermaricanMix** [comment]
> Do'h, sorry -- do a scan first. It's under Import.

It worked! Thank you so much for your quick and thorough help!

**Comment by rmcrackan** [comment]
You're welcome. Merry Christmas!
