### ISSUE TITLE
Delete multiple titles from library at a time. Or use delete button to delete highlighted selections.

### ISSUE THREAD

**Issue by orthadoxtesla** [rmcrackan/Libation#1089]
As the title suggests it would be great to be able to delete a large amount of books from the library. I share a library with my mother and I don't particularly want to see the large quantity of what I will nicely call romantic fiction. If it's possible to be able to highlight and remove multiple titles from the library at once more quickly it would be helpful. No rush. Thank you for this awesome service. You're all hero's

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a new 'Themes' menu item under Settings to allow users to switch between light and dark themes. This addresses the feature request for theme customization.

You can review changes in this commit: https://github.com/wwqwq2313/rmcrackan-Libation-1089/commit/7e7242514b0d9c60c0e64bef01d820a1cb48bd6d.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by orthadoxtesla** [comment]
Never mind. I've seen the option now to delete multiple things at once
