### ISSUE TITLE
Recoving an item after clicking "Remove from Library"

### ISSUE THREAD

**Issue by GoAndDo2** [rmcrackan/Libation#1090]
**Is your feature request related to a problem? Please describe.**
I was having some glitches and running slow because of so many books in my library. I couldn't find a way to remove the books from the list that I was done with (similar to Clear Finished in the Queue), so I did "Remove books from all accounts" (because I didn't want to click over 1,000 books individually =). I ran the process again to get the last few books I'd obtained in Audible, and I right-clicked and chose "Remove from Library" on one after it was done, and it not only removed it from the list, but seems to have removed the folder with the book from my hard drive.

**Describe the solution you'd like**
The problem is not so much that the folder has been removed, but now when I scan my Audible library, it is not showing the book I removed. I assume it's because it was already downloaded, but since I deleted it, now I can't find a way to redownload it. Along those lines, none of the books I'd previously downloaded and then did "Remove books from all accounts" will show up in my list again when I click Import and Scan.
The best solution I can think of that might have the least impact on everything else is to make an option where you can search for a specific file in someone's Audible library, and then have that file downloaded.

**Describe alternatives you've considered**
I haven't thought of anything else... well, maybe a history of what's been removed and have an option to undo that action?

**Additional context**
Nothing that I can think of, except that you guys are rock stars, and thank you!!!

**Comment by rmcrackan** [comment]
Sorry for the confusion. Go to Settings > Trash bin

**Comment by GoAndDo2** [comment]
Brilliant! Thank you so much, that is what I needed. 
Side note - since I missed that I may have missed this, too, but is there a way to search for a title in the Trash bin, or to sort the titles by name?

**Comment by rmcrackan** [comment]
No, sorry, the trash bin is pretty basic.
