### ISSUE TITLE
Missing books

### ISSUE THREAD

**Issue by GoAndDo2** [rmcrackan/Libation#1091]
**Describe the bug**
Libation has successfully downloaded over 1,000 books for me. Recently I purchased some books and just a few of them are not showing up when I do an Import and Scan in Libation. I got some more books today and they are found and downloaded just fine, but I can't figure a way to get those few from a week or so ago to be found when I scan my library.

**To Reproduce**
In libation I just click Import and Scan Library of Some Accounts (because I have some old accounts that I don't want to scan every time). 
It scans for a bit, then stops and no books are added to Libation.

**Expected behavior**
Any new books I added since the last scan used to show up, and that happened today with the most recent books I got, but those few books that were part of the purchase a week or two ago still don't show up when scanned.
If there were a way to search my Audible library for just one file, I don't know if that would be a workaround or a troubleshooting step, but I already mentioned that in a software request =)

**Platform**

WIndows 11

**Log Files**

I hope this is the file you want!
THANK YOU, and have a nice day!

[000003.log](https://github.com/user-attachments/files/18219806/000003.log)

**Comment by rmcrackan** [comment]
Is this related to the other ticket #1090 ?

**Comment by GoAndDo2** [comment]
Hello, and thank you for asking.
This is not related to ticket 1090. That had to do with books that Libation had downloaded from Audible, then I removed from the list in Libation, after which I could not find a way to have them show up when scanning my Audible library, or to somehow re-download them from Audible. Thank you for your answer on that!
In this situation, I purchased some books from Audible and they never showed up in Libation when doing an Import | Scan Library. So they have never been downloaded from Audible. It's odd because this hasn't happened with hundreds of books in the past, and with a dozen or so books I have added in Audible since getting the books in question, but this small groups of a half dozen or so books that I added maybe a couple of weeks ago, I have never been able to get them into Libation.
Thank you so much for any ideas or suggestions you have on this.

**Comment by rmcrackan** [comment]
Off the top of my head:

* either you bought them on a different audible account, in which case you just need to add that account in Libation.
* Or there was a error during the scan. Please do another scan, then go to Settings and click the 'open log folder' button. Attach the latest log file to this ticket. Maybe it'll have clues. By doing another scan first, we can log the most up-to-date error details.

**Comment by GoAndDo2** [comment]
Holy cow you're fast! Thank you!
- Good point. These are on the same account, obtained from the same group of credits and showing up in the Library alongside the other books that are downloading.
- I have done a number of scans, including: Auto Scan, from All Accounts, and from Some Accounts.
I just started Libation fresh and did an Import | Scan Library of Some Accounts so I could choose the account whose library these books are showing up in, and am attaching the log file from immediately after that scan was run.
Thanks again, I hope this helps.
[_Log202412_006.zip](https://github.com/user-attachments/files/18230693/_Log202412_006.zip)

**Comment by rmcrackan** [comment]
Thanks for the new log. No recent errors. In fact, this is about the most normal log I can imagine. You're on the most stable version of Libation. There was some scan error 2 days ago but nothing today. We've established that the books are from an account being scanned by Libation, and that they're purchases (as opposed to free "Plus" titles).

* Is there a filter at the top of Libation keeping them from showing up?
* Did they already get scanned then accidentally removed? If so, they'll show up under Settings > Trash Bin
* Are they accessible from the official phone app?

Please tell me more about the books which aren't showing up. You've done great troubleshooting. I'm starting to run out of ideas. This has gotten wacky.

**Comment by GoAndDo2** [comment]
"We've established that the books are from an account being scanned by Libation, and that they're purchases (as opposed to free "Plus" titles)."
-> To be thorough, I just added a podcast and a free "Plus" book title, and those are showing up in Libation scans as well.

"Is there a filter at the top of Libation keeping them from showing up?"
-> The filter field is clear. Under the Quick Filters menu the 1st Quick Filter option is not checked, and under Edit there are no filters at all.

"Did they already get scanned then accidentally removed? If so, they'll show up under Settings > Trash Bin"
-> I wondered about that. Since I never saw these books in the Scan results, I didn't think they could be in the Trash bin, but started looking through it just to be sure. Since there are well over 1,000 titles in there I decided it might be faster to Restore them all so I could Sort them and search by title.
And you know what? They are there. I was **100%** sure I never saw them show up in the scan results. And they haven't been downloaded yet. So I don't know what happened. Just goes to show that no matter how right someone thinks they are, they might still be a moron =) 

1. THANK YOU for your patience and help with this.
2. You're an excellent troubleshooter!!
3. I didn't realize there is a phone app. I will check that out as well, thank you.
4. It would be nice to be able to remove or hide the books in the scan results list that have already been downloaded. Because I have so many, it downloads one book then freezes. I start it back up and do the next one, but I imagine all those downloaded books might be weighing down the list. I'll see if filters or something can help with that - not your problem.
5. I'm going to go figure out how to do GitHub contributions. Thank you again for everything!

**Comment by rmcrackan** [comment]
> I didn't realize there is a phone app. I will check that out as well, thank you.

There's no Libation phone app -- I meant: did the problem books show up in audible's actual phone app. Obviously moot now but I wanted to reply and clarify that I don't have my own phone app.

> I'm going to go figure out how to do contributions. Thank you again for everything!

Much thanks for your generous tip. And you're very welcome. I'm glad we got it figured out. Merry Christmas!
