### ISSUE TITLE
Sepecific audiobook not added to Libation with Library Scan

### ISSUE THREAD

**Issue by nazofukuro** [rmcrackan/Libation#1095]
**Describe the bug**
I recently noticed that one book in a series was not added to Libation. I tried removing it from my Audible library and adding it again, but it was still not found with a library scan. In the same series, the books before and after get scanned successfully.

Notes: 
I have used Libation for 1000+ books and it worked fine for them (thank you for all the work you do!).
This is a book from audible.co.jp so it might be difficult for you to test.

**To Reproduce**

1. Go to the audible.co.jp page of [[4巻] リビルドワールドIV 現世界と旧世界の闘争](https://www.audible.co.jp/pd/4%E5%B7%BB-%E3%83%AA%E3%83%93%E3%83%AB%E3%83%89%E3%83%AF%E3%83%BC%E3%83%AB%E3%83%89IV-%E7%8F%BE%E4%B8%96%E7%95%8C%E3%81%A8%E6%97%A7%E4%B8%96%E7%95%8C%E3%81%AE%E9%97%98%E4%BA%89-%E3%82%AA%E3%83%BC%E3%83%87%E3%82%A3%E3%82%AA%E3%83%96%E3%83%83%E3%82%AF/B0CQJPNTNY)
2. Add it to your library 
3. Scan Library in Libation

**Expected behavior**
The book is added to the Libation Library

**Screenshots**
![Screenshot Added books](https://github.com/user-attachments/assets/2bbee5d6-e8ed-462f-9e32-5b7a733753f8)

![Screenshot Libation Library](https://github.com/user-attachments/assets/519c24ce-1bc3-486b-980d-a89ff08970d0)

**Platform**
Windows 11

**Log Files**
[_Log202412.zip](https://github.com/user-attachments/files/18246471/_Log202412.zip)

**Comment by rmcrackan** [comment]
Did it accidentally get removed in Libation? If so, it would be in Settings > Trash bin

**Comment by nazofukuro** [comment]
Yes, I found it in the Libation Trash bin, no idea how it got there. Pressing delete on my keyboard doesn't seem to put files into the Trash bin, so I'm not sure if I just randomly clicked at some point in an unfortunate way.

Anyway, thanks a lot, and have a great holiday season!

**Comment by rmcrackan** [comment]
Thanks for following up. Happy New Year!
