### ISSUE TITLE
Libation has encountered an unexpected error. Could not deserialize json:

### ISSUE THREAD

**Issue by kcbutler1015** [rmcrackan/Libation#1096]
I get this error message when Libation opens up. I cannot do anything else within the application. 

![image](https://github.com/user-attachments/assets/09e97fd9-6f94-4081-82fe-240ed5c6d726)

[_Log202412.zip](https://github.com/user-attachments/files/18255703/_Log202412.zip)

**Comment by rmcrackan** [comment]
I believe your accounts settings file got corrupted. In the same folder where your log file is, rename or delete `AccountsSettings.json`, restart Libation, then under Settings > Accounts, re-add your account. On next scan it will make you log in again, but no books or progress will be lost.
