### ISSUE TITLE
missing book in lbrary

### ISSUE THREAD

**Issue by Kentheprofile** [rmcrackan/Libation#1099]
I am missing a book I had before can get it back even thought I can see it on audible.com
I have no log to show but it does say 1 book unavailable. wont show even if o scan my library multiple times.

**Comment by rmcrackan** [comment]
Is it in the trash bin? Go to Libation > Settings > Trash Bin

**Comment by Kentheprofile** [comment]
yep thank you all set

**Comment by rmcrackan** [comment]
Great. Thank you for following up. Happy new year!
