### ISSUE TITLE
Trying to workaround "Wall Street Journal" Audible misfeature

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#111]
Summary: can we either not stop all conversions when a problem is hit, OR can we make a way to exclude all of the titles in a given search result?

Audible used to offer a daily subscription to some newspaper summaries (WSJ, NYT, and one other). In a fit of completely unjustified optimism I subscribed to the Wall Street Journal. Big, big mistake. It's impossible to unsubscribe and impossible to ever remove any of the issues from one's library. Even the extremely old ones which have been removed and produce nothing but an error when downloaded.

So ... since Libation now attempts to download episodes (yay!) and therefore stops trying to do anything as soon as it hits the first episode of the WSJ, I can no longer liberate anything automatically (awwwww).

I'm going to try to work with Audible to get them removed, but thousands of people have reported no success.

Meanwhile, what can I do?

1. I know I can still liberate by hand. That's fine for new books, but I kind of want to get my older episodes.
2. I suppose I COULD click "Ignore" on hundreds of WSJ episodes. Please no. :)
3. Maybe could we provide an option to automatically "Retry" when an error is hit? It's the least destructive/permanent of the options that would allow the liberation to happen in spite of the annoyingness.
4. Maybe there's a way to bulk-select and ignore/etc items using the filters?

That's what occurs to me. I know I'm going to have a NEW problem tomorrow morning when I get a new episode I won't want to download, but maybe I deserve it for being so _optimistic_.

**Comment by rmcrackan** [comment]
I'll think about the issue this weekend. For now: the CLI just skips problem titles and retries them again on the next attempt.

**Comment by rmcrackan** [comment]
Setting added in [v5.7.1](https://github.com/rmcrackan/Libation/releases/latest)

I thought about allowing for blacklisting feeds like WSJ which audible can't figure out how to unsubscribe. Then I looked up audible's market value. The entire Libation project is already compensating for audible's fuck ups/belligerence. A solo hobbyist doing it (mostly) sober in my spare time vs a multi-billion dollar company which is more of less owned by the richest man on the planet. Some features are hard to morally justify.
