### ISSUE TITLE
US library import failing (AU is OK)

### ISSUE THREAD

**Issue by flysalad** [rmcrackan/Libation#112]
Hi,

I'm trying to import my Audible US library and it's failing. Looking at the log it appears to be one book causing the problem. I can confirm that import is working on my much smaller AU (Australian) library - US log attached. I'm pretty sure it worked OK in v5.5.9 but I've not been able to update my library since and v5.5.9 is no longer working either. I've tried deleting all contents from the user directory and then re-adding my accounts.

Thanks for this great software!

[_Log202109.log](https://github.com/rmcrackan/Libation/files/7151350/_Log202109.log)

**Comment by rmcrackan** [comment]
Sorry about that. Hopefully fixed in latest: https://github.com/rmcrackan/Libation/releases/latest
