### ISSUE TITLE
Libation 5.7.1 seems to silently crash on startup

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#113]
I was previously using 5.6.7 and saw there was an update so I unzipped 5.7.1 to its own directory. After running Libation.exe in the 5.7.1 directory nothing seems to happen - I'm guessing it's crashing but there's no UI or anything displaying any error.

I'm not seeing any modified logs in the users\Libation directory that might contain crash data, either.

**Comment by Mulchman** [comment]
Investigating from the source, I appear to be hitting an exception -

`System.IO.FileLoadException
  HResult=0x80131040
  Message=Could not load file or assembly 'System.Drawing.Common, Version=5.0.0.2, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The located assembly's manifest definition does not match the assembly reference. (0x80131040)
  Source=<Cannot evaluate the exception source>
  StackTrace:
<Cannot evaluate the exception stack trace>

  This exception was originally thrown at this call stack:
    [External Code]
    LibationWinForms.Program.Main() in Program.cs`

**Comment by Mulchman** [comment]
It almost seems like there's a race condition happening. Sometimes the app works and sometimes I'm hit w/ the exception about System.Drawing.Common.dll missing.

**Comment by rmcrackan** [comment]
I'll release a new build later today.

This was introduced with the new CLI. To easily deploy, they share an output build dir. I thought I'd fixed this but apparently I just hadn't noticed it happening again.

**Comment by Mulchman** [comment]
![CompilationRace](https://user-images.githubusercontent.com/11757993/133097865-3fd8e5aa-1999-4613-9f54-db85e9b55c7e.gif)

**Comment by rmcrackan** [comment]
I can't follow what's going on in this gif. Please describe

**Comment by Mulchman** [comment]
Just showing that after some rebuilds it'll crash and after others it won't. Libation is off the screen so you can't see when it opens or when I close it.  Here's what's happening in the video, though:

- Rebuild, run, no exception.
- Rebuild, run, no exception.
- Rebuild, run, exception.
- Rebuild, run, no exception.
- Rebuild, run, no exception.
- Rebuild, run, exception.
- I type "what the fuck"
- Gif loops

**Comment by Mulchman** [comment]
I appreciate the response and really appreciate the tool. I threw some money your way early on and maybe it's time to throw some more. I despise using the Audible player and would hate to go back to it!

**Comment by rmcrackan** [comment]
Heads up -- I'm emailing you a quick question to your email that paypal showed me (p...r@gmail.com) for a discussion I don't want to make public

**Comment by rmcrackan** [comment]
It looks like even re-releasing didn't fix it. See #114 

Either later today or early tomorrow I'll pull the CLI out of the releases until I figure out a new way to deploy it

**Comment by rmcrackan** [comment]
In [the latest release: v5.7.4](https://github.com/rmcrackan/Libation/releases/tag/v5.7.4) I figured out a new way to repackage which still includes Libation.exe and LibationCLI.exe in the same folder so they can share settings, db, etc. Per the release notes, since this issue was intermittent across users, I can't be 100% sure it's fixed. Please let me know if either program does not run for you.

**Comment by Mulchman** [comment]
Libation 5.7.4 starts up for me!
