### ISSUE TITLE
LOG IN ISSUES. Please report all log in problems here

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#118]
# If you have login issues, please comment here with description and attached log files.

I thank everyone for your patience. I know how frustrating it is for software not to work and I'm doing my best to fix it. I'm sorry that I don't know more.

There's something weird affecting a small number of user log ins. I've been playing cat and mouse with audible/amazon for nearly a year and there's some tiny detail I must be missing. I'm continuing to hunt for an answer. At present I have no time frame for a fix since I can't tell what's wrong. These issues don't happen to me which makes them very hard to debug.

Libation's logging continues to improve. The best way you can help is to post here with details of what you did and what went wrong along with log files.

There are currently several open issues related to login ( #108 #109 #117 ). I'm going to close those and link them here so there's a central place to track them. Please add new progress here.

**Comment by rmcrackan** [comment]
New login method available which should fix all current log in issues. See latest release [v6.0.1](https://github.com/rmcrackan/Libation/releases/tag/v6.0.1). Thank you all for your patience while I worked to fix these.

**Comment by kfbest** [comment]
Just experienced this tonight with 6.0.2. CAPTCHA didn't work, but I was able to use browser to log in.

**Comment by kfbest** [comment]
> Just experienced this tonight with 6.0.2. CAPTCHA didn't work, but I was able to use browser to log in.
> [Log202109.log](https://github.com/rmcrackan/Libation/files/7214786/Log202109.log)

Realized I had a typo in my email address (.som instead of .com). Now I get the 2FA prompt instead of the CAPTCHA prompt and am able to log in.

**Comment by CharlieRussel** [comment]
@rmcrackan -- Bless you for the web login fix. I was never able to reliably use the original login, but the web login has worked, and worked again today after I had to change my Amazon password. 👍

**Comment by rmcrackan** [comment]
@CharlieRussel Fantastic! Man has reverse engineering this login stuff been hard. fwiw: I also fixed a bug this week for pre-audible uk accounts. They now work in app and in browser.

**Comment by rmcrackan** [comment]
@CharlieRussel Wow! Thank you so much for your generosity. That's very kind of you.
