### ISSUE TITLE
capchas are too hard

### ISSUE THREAD

**Issue by webwizz2003** [rmcrackan/Libation#12]
I am not able to get passed the capcha on the new version.  It may help to decrease difficulty or make the box larger.  I pinky swear I am not a bot. ;)

**Comment by rmcrackan** [comment]
Sorry, I'd get rid of them altogether if I could. They're sent as-is from amazon/audible.

If you had success with a previous version of Libation you could use advanced settings to point your previous 'libation files' folder then restart the program. This would pick up your previously saved login.
