### ISSUE TITLE
Unable to launch app

### ISSUE THREAD

**Issue by docbha** [rmcrackan/Libation#121]
Hi I have downloaded the latest version but the app does not launch when I click on libation. Have tried numerous times. I am working on windows 10. Thanks a lot for your help.

**Comment by rmcrackan** [comment]
That's not good. I created a new release. Let's see if this fixes it: [v6.0.3](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by docbha** [comment]
Hi Thanks i downloaded the new relaese but this also does not launch. Should i delete all the old files. I am launching it by clicking on libation app icon, hope I am doing it correctly.

**Comment by rmcrackan** [comment]
Everything you're doing sounds correct. What happens if you try to launch it from a command prompt?

**Comment by docbha** [comment]
Hi sorry I am not so good with IT stuff so could you guide me how to use command prompt. Thanks

**Comment by docbha** [comment]
Even the older versions downloaded are not launching now even after restarting my laptop.

**Comment by rmcrackan** [comment]
That's illuminating. Either your anti-virus (or windows defender or similar) stopped trusting Libation or else there's something wrong with my files.

Let's try this. Find your Libation files. They're probably in C:\Users\[username]\Libation. Inside this folder are 3 other folders (DownloadsFinal, Images, SearchEngine). You can leave these folders alone.

* There are also 5-10 files. Back up all those files somewhere.
* After backing up -- seriously, back them up in case this goes wrong -- delete "LibationContext.db"
* Start Libation

If it doesn't even start here, then we've got even bigger problems. Now to restore the data we just deleted:

* Import your library
* When that's complete, close Libation
* Rename the file "FileLocations.json" to "FilePaths.json" (or if you can't see file extensions, rename "FileLocations" to "FilePaths")
* Restart Libation

Give it a minute or 2 to run. If everything goes well, the following will all be true. If not, let me know what's wrong and we'll dig deeper:

* Libation will run
* your data looks just like it did before
* FilePaths.json is gone
* FileLocations.json is back

**Comment by docbha** [comment]
Thanks a lot, will try this.

**Comment by docbha** [comment]
The file settings.json is empty
There is another file accountsseetings.json which has details of all accounts.

**Comment by docbha** [comment]
the file appsettings.json in my downloaded libation folder has the following
{
  "LibationFiles": "C:\\Users\\user\\Libation"
}

**Comment by rmcrackan** [comment]
Any recent log entries?

If you rename that Users\\user\\Libation folder to Libation_backup then restart Libation, does it create a new "Libation" folder?

**Comment by kfbest** [comment]
Having similar issue. v6.0.2 and v6.0.3 not launching after crashing. Even after reboot, won't launch.

Deleted .db file, 6.0.2 opens and has "newer version" popup. v6.0.3 does NOT open. Deleted .db file again and still does not open. 

[Log202109.log](https://github.com/rmcrackan/Libation/files/7214809/Log202109.log)

**Comment by docbha** [comment]
> 
> 
> Any recent log entries?
> 
> If you rename that Users\user\Libation folder to Libation_backup then restart Libation, does it create a new "Libation" folder?

Hi it opened now with new created libation folder but all my old data is missing

**Comment by rmcrackan** [comment]
> Hi it opened now with new created libation folder but all my old data is missing

Cool, Libation isn't being blocked by windows or anti-virus. Now let's restore your data.

Close Libation. Copy these files from the 'Libation_backup' folder to the new 'Libation' folder: AccountsSettings.json , BookTags.json , QuickFilters.json , Settings.json . Start Libation. Import/scan your library.

You should now have everything back except for the downloaded/liberated statuses. Close Libation. This part is a little funky:

delete Libation\\FileLocations.json  
copy Libation_backup\\FileLocations.json => Libation\\FileLocations.json  
rename Libation\\FileLocations.json => Libation\\FilePaths.json  
Restart Libation. It will take a minute or 2 to process this file. (When it's done, Libation\\FilePaths.json will be gone and FileLocations.json will be back). Do 1 more library scan, and aside from being frustrated will all of my steps, you should be back to where you were yesterday.

**Comment by rmcrackan** [comment]
@kfbest -- what happens if you rename that Users\user\Libation folder to Libation_backup then restart Libation, does it create a new "Libation" folder?

**Comment by docbha** [comment]
> 
> 
> **Edit: the below is for @docbha**
> 
> > Hi it opened now with new created libation folder but all my old data is missing
> 
> Cool, Libation isn't being blocked by windows or anti-virus. Now let's restore your data.
> 
> Close Libation. Copy these files from the 'Libation_backup' folder to the new 'Libation' folder: AccountsSettings.json , BookTags.json , QuickFilters.json , Settings.json . Start Libation. Import/scan your library.
> 
> You should now have everything back except for the downloaded/liberated statuses. Close Libation. This part is a little funky:
> 
> delete Libation\FileLocations.json
> copy Libation_backup\FileLocations.json => Libation\FileLocations.json
> rename Libation\FileLocations.json => Libation\FilePaths.json
> Restart Libation. It will take a minute or 2 to process this file. (When it's done, Libation\FilePaths.json will be gone and FileLocations.json will be back). Do 1 more library scan, and aside from being frustrated will all of my steps, you should be back to where you were yesterday.

Hi as soon as i copy the files, libation stops opening. Tried it two times. Thanks so much for your help.

**Comment by rmcrackan** [comment]
> Hi as soon as i copy the files, libation stops opening. Tried it two times. Thanks so much for your help.

Very strange but I'm glad we're narrowing down the issue. I'm glad you have the files backed up in Libation_backup. That will help a lot.

In \\Libation folder, get rid of the files you added. Libation should start again. Close it, add one of those files from Libation_backup. Re-open. Close again. Etc. Let's figure out which file is causing our bug.

**Comment by docbha** [comment]
Sure will try this, thanks

**Comment by docbha** [comment]
It is seetings.json file causing issues, it is actually empty in the back up folder.

**Comment by rmcrackan** [comment]
That's super weird. I don't think I've touched code relating to that file in quite a while. If you follow the previous steps for everything other than Settings, does it work again? incl the appropriate stoplights being green

**Comment by rmcrackan** [comment]
@docbha and @kfbest 

I just released [v6.0.4](https://github.com/rmcrackan/Libation/releases/latest) which has better error messages to handle the limbo between when the app launches and when proper logging can start.

@kfbest 

Open your Settings.json in notepad and see if it is also blank.

**Comment by docbha** [comment]
> 
> 
> That's super weird. I don't think I've touched code relating to that file in quite a while. If you follow the previous steps for everything other than Settings, does it work again? incl the appropriate stoplights being green

Hi it worked except for the green lights. Only 1-2 of my files show liberated. This is the error i get and both the filelocation and filepath files remain.

[error.docx](https://github.com/rmcrackan/Libation/files/7218086/error.docx)

**Comment by rmcrackan** [comment]
Does that error happen every time? After we fix this, I have hope that we can fix the stoplights also

**Comment by docbha** [comment]
Yes it happens everytime I open the app

**Comment by rmcrackan** [comment]
Damn. Try [v6.0.5](https://github.com/rmcrackan/Libation/releases/latest). Same error? Does the error also appear in the log file? If no error: do both the filelocation and filepath files still remain?

**Comment by docbha** [comment]
Hi i tried v6.05, no error but the green light is still not there and filelocation and filepath files remain.

**Comment by rmcrackan** [comment]
I could debug this a lot faster from my own computer. If you're comfortable with it, could you zip a few files and email them to me rather than post here? Do NOT include the AccountsSettings file. That's the one with the tokens (think: browser cookies) which allow access to your actual audible account(s)

I need these files: FileLocations , FilePaths , LibationContext . Highlight them in windows. To zip: right-click -> Send to --> Compressed (zipped) folder. (Or you can put them in a new folder and do the same right click on that new folder.) Email me that zip file. My email is on [this page](https://github.com/rmcrackan)

**Comment by docbha** [comment]
Thanks so much, emailed you the zipped files.

**Comment by rmcrackan** [comment]
Thank you for your patience. Here's the solution (finally!). Thank you so much for your help. It directly contributed to the improvements made in v6.0.6

* You should have 1 database file named LibationContext. If you have 3, then the 2 files with blank icons should be deleted
* download the latest version [v6.0.6](https://github.com/rmcrackan/Libation/releases/latest)
* Backup and delete your current FilePaths and FileLocations files
* Unzip the FilePaths file I emailed you: right-click => Extract All
* Put this newly unzipped FilePaths file into the \\Libation folder
* Launch the new Libation
* Let it run for 2-3 minutes

If everything went ok, the new FilePaths will be gone, there will be a new FileLocations file, and your stoplights will be fixed. In short: all will be back to normal.

**Comment by kfbest** [comment]
> @kfbest -- what happens if you rename that Users\user\Libation folder to Libation_backup then restart Libation, does it create a new "Libation" folder?

Renamed folder. 
6.0.3 - doesn't launch, doesn't create new folder
6.0.2 - does launch and asks about New User vs. Upgrade. 


> @kfbest
> Open your Settings.json in notepad and see if it is also blank.

Nope - it's populated. 

Just as an aside, does it matter where I put the program after unzipping it? 


Updated to 6.0.6 and got the attached error.  Note that the "click to open log files folder" link doesn't work. 


<img width="470" alt="Screen Shot 2021-09-23 at 6 14 49 PM" src="https://user-images.githubusercontent.com/6269235/134591167-be98ffaa-b072-4ab8-8d95-bbecc143c100.png">
[launch error.txt](https://github.com/rmcrackan/Libation/files/7221050/launch.error.txt)

**Comment by rmcrackan** [comment]
Ah, now the picture is becoming more clear. Libation doesn't care where the files are but apparently windows cares. Is this the same location you were running previous versions from? Does it help if you run it from somewhere else? Also, if you right click appsettings.json and choose properties, see if read-only is checked. Or if that downloaded-from-web box is checked.

**Comment by docbha** [comment]
> 
> 
> Thank you for your patience. Here's the solution (finally!). Thank you so much for your help. It directly contributed to the improvements made in v6.0.6
> 
>     * You should have 1 database file named LibationContext. If you have 3, then the 2 files with blank icons should be deleted
> 
>     * download the latest version [v6.0.6](https://github.com/rmcrackan/Libation/releases/latest)
> 
>     * Backup and delete your current FilePaths and FileLocations files
> 
>     * Unzip the FilePaths file I emailed you: right-click => Extract All
> 
>     * Put this newly unzipped FilePaths file into the \Libation folder
> 
>     * Launch the new Libation
> 
>     * Let it run for 2-3 minutes
> 
> 
> If everything went ok, the new FilePaths will be gone, there will be a new FileLocations file, and your stoplights will be fixed. In short: all will be back to normal.

Thanks again for your help. I did the steps. There was only one file of Libationcontext and also the filepaths file disappeared and was replaced by filelocations. But it shows only some of my books backed up, whereas  almost all my books were backed up. I am attaching the log, thanks
[Log202109_001.log](https://github.com/rmcrackan/Libation/files/7222802/Log202109_001.log)

**Comment by docbha** [comment]
I was earlier running the libation from E drive my external hard disk and now I am running from c drive, my storage for downloaded books is still E, would that be an issue ?

**Comment by rmcrackan** [comment]
I'm closing this issue because the actual bug is fixed. Either of you can still reply here and I'll see what I can do to help your individual situations.

@docbha I'm out of tricks. They can be manually changed to liberated one at a time with the buttons on the right of each row. Or you can tell me which books are/are not liberated and I can manually fix the database file you sent me then I can zip/email it back to you.

**Comment by docbha** [comment]
Thanks a lot for your help. I will manually do it, no problem. Again really apprecaite your support to get this issue solved.
