### ISSUE TITLE
Libation no longer generating .nfo files

### ISSUE THREAD

**Issue by Jamyn** [rmcrackan/Libation#129]
I'm not sure which version of Libation stopped generating .nfo files, but I think it worked fine in all 5.x versions and stopped working around the release of Libation 6.x.  Libation still correctly generates lossless .m4b and .cue files, but there are no logged steps for nfo file generation.

[log_snippet.txt](https://github.com/rmcrackan/Libation/files/7247738/log_snippet.txt)

**Comment by Mbucari** [comment]
See #126

**Comment by Mbucari** [comment]
@rmcrackan I think that .NFO files makes Libation feel warez-y.

**Comment by rmcrackan** [comment]
@Mbucari you’re not wrong
