### ISSUE TITLE
Request - Find existing downloads in folder

### ISSUE THREAD

**Issue by kealist** [rmcrackan/Libation#130]
For whatever reason, I have had to reconfigure the app multiple times to save to a particular directory, but assigning the directory does not scan or find the files that have been already downloaded.  I can manually go through each and mark it as downloaded, but it's a bit of a hassle.  It would be nice if there were at least a one time tool to check if the files exist.

**Comment by rmcrackan** [comment]
That sounds frustrating. Previous downloads should be saved in your database. Did something happen to delete that file?

**Comment by kealist** [comment]
I believe I was trying to re run an old download of it, and it acted like it was not setup.  So I had to reconfigure everything, so yes the database was probably deleted somehow.

**Comment by rmcrackan** [comment]
I added this feature request to my queue. I'll report back here when progress is made. No ETA

**Comment by rmcrackan** [comment]
I'm experimenting with tracking enhancements and feature requests using github issues instead of a local file.

# Scan for existing books

Scan folder ("Books" folder or custom folder) for already liberated books. Update database liberated status where new status is better than db status. Eg: if is newly found and db status is not-liberated or error, then update. If not found, do not overwrite db status. If it's easy, do PDFs also.

This will only work for files which retained audible id.s in the file or directory names. Nothing more extraordinary needs to be done than what can be seen in `migrate_to_v5_5_0_thread` and `BackgroundFileSystem`

**Comment by kealist** [comment]
@rmcrackan Which version of VS are  you using? 2017?  I opened in 2019 and it was trying to convert csproj files.  I was thinking about taking a look at this.   Any guidance at where (which project) this action should live?

**Comment by rmcrackan** [comment]
@kealist I'm currently on 2022 but most of the development was done in 2017 and 2019. As I said above, there are sections of code with hints about how I'd go about it if it were me.

The initial gui piece probably belongs in the Import menu. Then the user would choose to scan their standard books directory or a custom one of their choice. At the end, the UI should tell them what was found. That should really be it for the graphical portion.

The backend belongs in: LibraryCommands

**Comment by rmcrackan** [comment]
This should now be way easier with the 'visible books' menu and it's batch actions

**Comment by nogwater** [comment]
I don't know if this is the right place to post this.  I've been learning Libation today and messed up some of my local downloads.  I want to re-download them, but Libation thought they were all fine.  I ended up removing all books from my library (just the db, not all of my downloaded/liberated files).  Then, when I rescanned, they all showed up as not downloaded (duh).  If I click on the Liberate button, it just redownloads the books that are already downloaded (not what I want).  I ended up using the Visible Books menu to mark them all as downloaded.  Then I created a new menu item to check the downloads.  I don't know if this would help anyone else, but here's the change:

Add a new menu item:
![image](https://user-images.githubusercontent.com/350287/201550264-8b131193-e566-4a3f-9db7-c18cd2d13831.png)

Add a click handler with the following:
```
private void checkDownloadedToolStripMenuItem_Click(object sender, EventArgs e)
{
    var visibleLibraryBooks = productsDisplay.GetVisible();
    foreach (var libraryBook in visibleLibraryBooks)
    {
        if (libraryBook.Book.Audio_Exists())
        {
            var filePath = AudibleFileStorage.Audio.GetPath(libraryBook.Book.AudibleProductId);
            if (filePath == null)
            {
                libraryBook.Book.UserDefinedItem.BookStatus = LiberatedStatus.NotLiberated;
                LibraryCommands.UpdateUserDefinedItem(libraryBook.Book);
            }
        }
    }
}
```

I can then run this code to mark all of my deleted downloads as NotLiberated and then easily re-download them.  Something like the opposite of this may work for the original request (when first re-scanning a library from a clean db, find the already downloaded books).

This isn't meant to be a PR but maybe someone will find it to be useful.

**Comment by rmcrackan** [comment]
@nogwater Interesting idea. Is this right?

* In my OS, I delete book files that I want to re-download
* Click a new option in Libation. For each book we can't find, mark it as not downloaded

Sure, that's do-able. Thanks for your sample code. Can you put this into a new feature ticket?

What's really funny is -- back in the day I didn't track download status at all. That status was only determined by whether or not the file was present; what you describe was basically the enforced global behavior. It prevented people from moving their files though so I created that database flag. We've come full circle (in a good way).

**Comment by pixil98** [comment]
If this is added, please add it to the CLI as well. I'd like to be able to automate checking for missing books before downloading any new ones.

**Comment by nogwater** [comment]
@rmcrackan new enhancement request here https://github.com/rmcrackan/Libation/issues/396
