### ISSUE TITLE
Audible Plus

### ISSUE THREAD

**Issue by Mantene** [rmcrackan/Libation#14]
I know your latest version currently filters out Audible Plus books since the downloads do not work the same as other Audible books. If a way were found to resolve that issue, would it be possible to re-instate Audible Plus books in Libation?

**Comment by rmcrackan** [comment]
Since Audible Plus books work differently, they are omitted from Libation. Although this could change in the future there are currently no plans to include them in Libation

**Comment by rmcrackan** [comment]
This will actually be included in the next major version of Libation. Look for it in the next week or 2.

**Comment by Mantene** [comment]
Wow! I am speechless! I don’t know how you cracked this nut, but thanks! I will look for it in a few weeks!
