### ISSUE TITLE
Partial / Complete files in `%temp%\Libation` are not tidied / reused

### ISSUE THREAD

**Issue by attie** [rmcrackan/Libation#144]
While figuring out #143, I had a book download and decrypt, but then fail to move into its final position.

This file was left as `%temp%\Libation\DecryptInProgress\x.x.m4b`.

Upon re-running the download/decrypt, these files were ignored (not reused or removed), the book was re-downloaded, re-decrypted and the new files had a ` (1)` appended (e.g: `x.x (1).m4b`).

I don't imagine these files should be left behind during normal operation (but if an error or perhaps if a force-quit occurs?)...
Therefore, it might be nice to try handling these files - e.g: either verify for completeness (difficult) / delete on retry (easy) / delete on failure (not ideal) / etc...

**Comment by rmcrackan** [comment]
I'm experimenting with tracking enhancements and feature requests using github issues instead of a local file.

# Clean up old bad files

* On error: delete. Clean up after your own process when possible.
* Delete old bad files on start. This will catch places where the previous isn't possible.

**Comment by rmcrackan** [comment]
Added in [v7.2](https://github.com/rmcrackan/Libation/releases/tag/v7.2.0)
