### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by Tb3986** [rmcrackan/Libation#145]
Hello,
sometimes i get this error with some audiobook

https://i.postimg.cc/mgg8xQHw/Untitled.jpg

is there any workaround?

Thank you

**Comment by Tb3986** [comment]
Yes sure.

[Error.txt](https://github.com/rmcrackan/Libation/files/7446438/Error.txt)

**Comment by rmcrackan** [comment]
Thank you for the log. Can you delete all files from this directory, try again, and let me know the result? C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\Libation\\DecryptInProgress

**Comment by Tb3986** [comment]
Is already empty. When i start the download, i get 4bm and then error,
This is json file:

{
  "SaveFilePath": "C:\\Users\\Administrator\\AppData\\Local\\Temp\\2\\Libation\\DecryptInProgress\\How to accelerate. Introduzione all'accelerazionis [B09HQWKB4V].tmp",
  "Uri": "https://dze5l2jxnquy5.cloudfront.net/bk_asit_003329it/34217621/aax/2/bk_asit_003329it_lc_128_44100_2.aax?id=48e41142-9c66-471d-876b-9deb3b50f4bd&Expires=1635780508&Signature=pKRqKdjdImgqccThaAyDAbCagsl2AlQ1cyn2F5tpcRnA9A8QcX6woKP5cdUgAHC-4YgScp0HK1agAyQJYMbdM67537WsPwXVJ0X0avQeKeNDUC9EytQAMyJbcGAu6STDzJseGnFanOAD2Uf6jb2eNxNjkr1Wu~nvWeppU-0wspKylzXo6BJFtCL5lxiRP9bA3IBhwR03YnUOsi-3QpbltzxS9yZ-RwoeaWLZ7mmQ5eFCqbgqcuzzsXkhYuB~oOnNx12WwlnN2BUqGL4MiooPwREXEcayGAgL5pPd1cwqgUYT6qTbyTkEHvBMWOSUuhMBV0-hKXj0IY-ftiVHib6yLQ__&Key-Pair-Id=K13BOWPVA44D7",
  "CookieContainer": {
    "Cookies": [],
    "Uri": "https://dze5l2jxnquy5.cloudfront.net/",
    "Capacity": 300,
    "Count": 0,
    "MaxCookieSize": 4096,
    "PerDomainCapacity": 20
  },
  "RequestHeaders": {
    "User-Agent": "Audible/671 CFNetwork/1240.0.4 Darwin/20.6.0",
    "Range": "bytes=0-"
  },
  "WritePosition": 160763441,
  "ContentLength": 182575634,
  "IsCancelled": true
}

**Comment by rmcrackan** [comment]
Thanks to your log I was able to find and fixed the bug in [v6.3.4](https://github.com/rmcrackan/Libation/releases/latest)

Thank you again.
