### ISSUE TITLE
Malwarebytes Detects Ransomware

### ISSUE THREAD

**Issue by nsomniak6** [rmcrackan/Libation#146]
I was downloading and the program was stopped and then deleted by Malwarebytes with the message of "Malware.Ransom.Agent.Generic detected" Any idea what this might be?

**Comment by rmcrackan** [comment]
Sorry, I have no control over this. There was one other user who once had LIbation flagged by Norton. There was a way in Norton to whitelist programs. Hopefully Malwarebytes allows something similar.
