### ISSUE TITLE
Libation keeps crashing when I try to import!

### ISSUE THREAD

**Issue by Soopx** [rmcrackan/Libation#147]
I've managed to import and decrypt one relatively short book, but anything slightly longer crashes the application  I'm not sure where to find the log file, but if  requested I can supply it :)

**Comment by rmcrackan** [comment]
That's not good. Open Libation and go to Settings and click "Open log folder". Inside there will be files similar to "Log202111.log". Please attach those files to this issue.

**Comment by Soopx** [comment]
thanks for the quick response!  As soon as I found the logs, I managed to take a look and realised what the issue was - lack of diskspace for the temporary files.   It's chugging along nicely now, thankyou :)

**Comment by rmcrackan** [comment]
No problem. Glad it's all sorted out now
