### ISSUE TITLE
Bulk Actions

### ISSUE THREAD

**Issue by eragon921** [rmcrackan/Libation#148]
NOT CRITICAL - As I've been using Libation, I've found it would be nice to have the capability of performing actions on multiple titles at once. This could be downloading/liberating, tagging, rating, etc. Even if, at a base, it meant filtering and then executing against a filtered group that would work. I don't know if I'm one of a select few or not, but just a general feature request to add to your never-ending queue. 

Libation has been a godsend for my workflow regardless.

**Comment by rmcrackan** [comment]
So glad to hear how it's helped your workflow.

I'm not sure what you mean. Downloading already happens in bulk from the top menu. You can't apply rating from Libation; it just reads what's on audible. I hadn't considered tagging on more than one book at a time -- that could be something to look in to.

Can you give an example of a specific case/workflow? I get that you'd perform a filter -- then what?

**Comment by eragon921** [comment]
So the bulk download from the top only offers to download all books. It doesn’t let you select a subset for downloading. For example, I already have a large selecteion of my 2300 books downloaded and converted to InAudible or OpenAudible, but Libation can’t recognized them. If I want to only download titles from, say, the last 2 weeks I have to individually download them instead of filtering for DateAdded:{StartDate TO EndDate] and having the application have an option under Liberate to only liberate the filtered list. Another option would be something like a checkbox in the GUI to select books upon which to take action. 

 

For tagging either workflow would also work for me. We would then need a bulk editor for user-controlled metadata like tags. 

 

Seth Schumacher

**Comment by wtanksleyjr** [comment]
I agree, I've wanted this "only liberate the files I'm looking at now" operation. Another good one would be "mark all of the files I'm looking at as don't-try-to-liberate-me." The latter would become very important if (by chance) my installation got corrupted and the DB wasn't recoverable.

**Comment by rmcrackan** [comment]
Thanks for the clarifications. Let's think this through. Currently your GUI options for individual books are:

* left/stoplight button: liberate or go to file
* right button: see image and details, edit tags, edit book liberated status, edit pdf liberated status

These make no sense in batch/bulk: go to file, see image and details

These seem straight forward to create a batch function: liberate, edit tags, edit book liberated status

This one is tricky: edit pdf liberated status. I could examine selected books and see if they have pdfs: all, none, or some. "All" or "none" are easy to handle the same way as however I'd do it for book status. "Some" will take a bit more care behind the scenes but, yeah, that seems do-able also.

The CLI has no concept of filtering so trying to add in a 'batch action by filter' feature would be a massive undertaking. Once you introduce anything filter related in the CLI it opens the flood gates for other reasonable filter and ad hoc querying. Eg: if "setting liberate status to all" with a filter, surely we'd first want a "get list by filter" feature. or a "get details for book", "get details by filter" etc. I'd like to avoid this rabbit hole.

Is this what you had in mind? Did I miss anything?

**Comment by wtanksleyjr** [comment]
Speaking for myself, I wouldn't expect filtering to be available on the
CLI. If the GUI could bulk-mark books as liberated I'd use that instead
(then run the CLI).

(BTW, the CLI is awesome, I use it all the time.)

I wasn't thinking of the PDFs; honestly they don't matter as much to me
because they're small, the audio is what I really don't want to re-download
in cases like this.

-Wm

**Comment by eragon921** [comment]
I agree with WM. I’d much rather do my filtering and bulk editing in the GUI and then l’d run the CLI as needed. I don’t use the CLI as much since my needs are generally more basic. Ditto with the PDFs, not that important to me.

 

Seth

**Comment by rmcrackan** [comment]
Thanks again for the feedback.

I added this to my queue. I like to keep issues open for active work only, esp bugs. I'm going to close this issue and I've made a note in my queue to update this issue when progress is made. At that point you should receive an alert/email. No ETA.

**Comment by eragon921** [comment]
No worries! I’m just glad it’s on your roadmap. I have no rush. Looking forward to seeing it when you’re able.

 

Seth

**Comment by rmcrackan** [comment]
I'm experimenting with tracking enhancements and feature requests using github issues instead of a local file.

# Batch Actions

Allow some bulk/batch commands to apply only to visible/filtered books. See above.

**Comment by rmcrackan** [comment]
Available in [v7.5](https://github.com/rmcrackan/Libation/releases/latest). Look in the new menu for 'visible books'
