### ISSUE TITLE
Re-arrange book files to new filename settings

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#155]
The new custom filename settings are great, especially with the <if series> logic. But now I have 1240 directories that don't follow that logic. Manually moving and renaming is just more effort than I really want to do, and it seems wrong to delete them all and re-download with the new settings. Any chance of adding an option to rename/move files in the output directory to match the current custom settings? (Yes, I know this is likely non-trivial, but I figure if I don't ask, I don't get. )

**Comment by rmcrackan** [comment]
Sorry, you hit the nail on the head. It's not trivial and, although it'd take an annoyingly long time, you can create your new naming templates, back up and delete your database, and re-run the scan + liberation.
