### ISSUE TITLE
Request - Option to disable the popup on library scan.

### ISSUE THREAD

**Issue by L0garithmic** [rmcrackan/Libation#160]
Request - Option to disable the popup on library scan.
It's kinda annoying

**Comment by rmcrackan** [comment]
I need the database to not get altered during that process so this is how I achieve this. Suggestion?

**Comment by L0garithmic** [comment]
> I need the database to not get altered during that process so this is how I achieve this. Suggestion?

Oh no lol. I just mean the one that pops up at the end and says how many books found that we have to click OK to.

**Comment by rmcrackan** [comment]
Ah, now I get it. Would it be less annoying if it only popped up if > 0 ?

**Comment by L0garithmic** [comment]
> 

Just an option to turn it off entirely would be ideal. Not everyone is like me. But since I am refreshing quite a bit because of... reasons. It's just one more thing to click. 

Also on a 4k screen, it centers the notification on the screen, not the program so its like, click import on the left bottom of the screen, then drag mouse all the way to the center to click ok, to drag the mouse all the way back to the left to click the red street light

**Comment by L0garithmic** [comment]
Oh also. BOLD the text on the alternative login screen that says that an ERROR on Amazon is GOOD... lol. I spent more time then I should of getting mad at the error page before reading the wall of text lol

**Comment by rmcrackan** [comment]
> Just an option to turn it off entirely would be ideal

Added. Will be available in next version. Prob will release this later today

> it centers the notification on the screen

This one is out of my control -- Windows chooses where to put it. But that's moot since you'll soon have the setting.

> BOLD the text on the alternative login screen that says that an ERROR on Amazon is GOOD

I mean, it is in all caps. I'll add some bold tl;dr text also though.
