### ISSUE TITLE
Automatic Upgrade After Download of New Version?

### ISSUE THREAD

**Issue by nsomniak6** [rmcrackan/Libation#161]
I chose the "ok" option after the popup comes up to download the new version, it didn't actually download it so I was wondering if it is automated and I am unaware? I read the Readme file but it didn't really clear it up for me. I was also noticing the Hoopla option but have zero clue how to do that. Can you point me in the right direction to understand it better? Sorry for my ignorance, I am obviously VERY new at this so the learning curve is steep for me. 

Thanks in advance for any help you can give!

**Comment by rmcrackan** [comment]
When you opt to download an upgrade it says 'New version available @ [url] Download the zip file?' Then it asks you where you want to save it. The zip will be where ever you selected. (Maybe it's in your 'downloads' folder?) Unzip and run the new Libation.exe. If you originally did a default install, it will find your old settings and books. You can delete the old version of the program. Sorry that I don't yet have a good installer or updater.

The Hoopla file is a placeholder that I have not yet done anything with. I actually don't know if I ever will. Libation is an ever-evolving passion project where things get added as I find the time and/or have the whim.
