### ISSUE TITLE
Noob question, how to install from zip?

### ISSUE THREAD

**Issue by ryanbrownnetworking777** [rmcrackan/Libation#162]
So I have the zip and I'm probably missing something super obvious here...but how do I get it from the zip to a working program? I see the zip contains .dll files and the visual studio solution file so do I have to open it up in visual studio and build the application first? Is there a way to do this with vs code?

**Comment by CharlieRussel** [comment]
Extract the zip file to a folder (mine is D:\Libation) and run Libation.exe. There is no installer package. Then follow the instructions in the readme to establish your accounts and start using Libation to liberate your Audible books.

**Comment by rmcrackan** [comment]
@CharlieRussel Thank you!

**Comment by CharlieRussel** [comment]
@rmcrackan Might be worth adding a paragraph or two to the readme that covers this. Users tend to think they should have an installer package. There's no current need for one, until or unless you add direct upgrades, but we can help get folks over the hump.

**Comment by rmcrackan** [comment]
@CharlieRussel Not a bad idea. What do you recommend? Putting a few sentences at the top of getting started?

**Comment by CharlieRussel** [comment]
@rmcrackan Yes. Right after the download link, add something on the order of:

**Installation**:  To install Libation, extract the zip file to a folder, for example C:\Libation, and then run Libation.exe to begin the configuration process and configure your account(s).

**Comment by rmcrackan** [comment]
> Right after the download link

Sounds good, thanks. Added to https://github.com/rmcrackan/Libation#getting-started

**Comment by CharlieRussel** [comment]
Excellent.
