### ISSUE TITLE
First click on Liberated icon shows 'File not found: <temppath>'. Second click opens correct final path.

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#164]
I download my entire library. On a random entry, when I click the green stop light icon, it pops up with error:
File Not Found: <temp path from settings>\DecryptInProgress\<filename>.m4b

But if I click it again, then it correctly opens a file explorer window to where the files are.

**Comment by rmcrackan** [comment]
I noticed this a while ago and I've been putting it off and putting it off and putting it off for no good reason. It only took moments to fix. Thanks for the nudge. It will be fixed in the next version.
