### ISSUE TITLE
Add support for identifying if item is 'audiobook' or 'podcast'

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#165]
Currently, there is no distinction between book series and podcast series, and so a folder/file naming rule for <series> would affect both. Perhaps add a 'type' key to the database so items can be identified as 'audiobook' or 'podcast'.  This would then allow:
- Sorting / filtering of grid by items based on type
- Create folder/file naming rules that are distinct for audio books and podcasts.
For example:
Put podcasts only in subfolder based on series name and prefix subfolder name with "[PODCAST]" and put audiobooks only in subfolder based on author's name:
`<if audiobook-><first author>\<-if audiobook><if series-><if podcast->[PODCAST] <series>\<-if podcast><-if series><title short> [<id>]`

**Comment by rmcrackan** [comment]
There is such a key. You can see it when you export. The final column is Content Type which says whether it's an episode or a product. For filtering, if you click the "?" box to the left of the filter box, look at the bottom of the boolean column. The bottom 4 are synonyms so I don't have to remember which way I named it. 

All this is to say: I'm much better at implementing features than I am at documenting them or making them discoverable.

As for sorting, I'm tracking these ideas in #154 . Who knows if I'll ever get to them, but that's where they are for now.

I like the idea for a better scripting for book exports. It feels like extending the current paradigm would get unwieldy. In fact, I really dislike the current `if series` thing -- the code is an uncomfortable kludge. Off the top of my head, maybe a rules engine where each rule has a match expression and a filter string; the first which matches is what gets used. Eg:

Rule 1:

* Name: books in series
* Match on: `Product and Series`
* Filter: `<first author>\<series>\<title short> [<id>]`

Rule 2:

* Name: books not in a series
* Match on: `Product and not Series` // can also just use `Product` as long as this rule comes after the previous one
* Filter: `<first author>\<title short> [<id>]`

Rule 3:

* Name: my podcasts
* Match on: `Episode`
* Filter: `my podcast folder\<series>\<title short> [<id>]`

Here's the bad news [ and I know it probably seems like I just keep finding different ways to tell you no :( ] between the holidays and a probable new job, I have no idea when I could get around to this. I really like the idea though. I like it way better than `if series`

**Comment by badbob001** [comment]
I see that filtering is rather extensive and does expose much of the metadata missing from the grid. If you can limit download actions to only items visible in the current filter, then one can workaround the limited rules syntax by:

1. Filter to show certain items
2. Change folder/file rules
3. Trigger download of items in filter view
4. Repeat 1-3 for other items

Yeah, not very elegant. I do like your idea to create rule sets that combine naming rules with filtering rules; perhaps it's not worth it to add workaround features to only replace them later with something better.

**Comment by Kazaa3** [comment]
I'm also in favor of implementing a filter function for podcasts, as some podcast have hundreds of episodes, cluttering up the audiobook library.

Another improvement would be to display a complete podcast sorted by episodes bundled in one entry. E.g. one entry per season.

Im Moment exportiere ich die komplette Bibliothek auf zwei getretten Geräten, da die Podcasts die Bibliothek zerstören. Die Podcasts lade ich einzeln und merge Sie per Hand zu einem Hörbuch pro Podcast in dem alle Folgen enthalten sind.

Currently I export the entire library on two separate devices because the podcasts destroy the organization of the entire library. 
For this reason I load the podcasts into a separate library and then merge them by hand. In the end there is one audio book per podcast containing all episodes of a season.  Which I update when a podcast season is completed.

**Comment by rmcrackan** [comment]
@Kazaa3 

> filter function for podcasts

In the search/filter box, you can type `Podcast` or `IsPodcast` to see only podcasts. Similarly `-Podcast` will hide them all.

> Another improvement would be to display a complete podcast sorted by episodes bundled in one entry. E.g. one entry per season.

Agreed. This is part of the plans in #154

**Comment by rmcrackan** [comment]
All the podcast stuff has gotten a substantial overhaul lately so I'm closing this. The new multi-level filter rules is too complex compared to the benefits gained. You can still include a series folder in your template. If no series then it will be blank. And blank folders are ignored. That is: `C:\[blank]\whatever` just becomes `C:\whatever`
