### ISSUE TITLE
Capture rating and title of top review

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#166]
On audible website, when hovering the mouse over an audiobook, the pop-up info window shows the top review's rating and title, which I find very helpful since the aggregated ratings are too similar for most books. Please capture this top review's rating and title and show in the grid (can be in a new column or an addition to the existing column). Support sorting or filtering by this rating.

**Comment by rmcrackan** [comment]
I'm going to say no for now. However I really like the idea of a future features for more filter options and customizable headers.
