### ISSUE TITLE
Request - Center errors on top of main window

### ISSUE THREAD

**Issue by TipsyOne** [rmcrackan/Libation#168]
The current error dialogue box requires dismissal before any other window can be interacted with, but the dialogue is often hidden behind other windows.  

Usability would be improved if the error dialogue box centers itself on top of the main window whenever one of the windows is restored/maximized.

**Comment by rmcrackan** [comment]
Addressed in new version [v7.6](https://github.com/rmcrackan/Libation/releases/latest)
