### ISSUE TITLE
Request - Replace individual status windows with a queue docked in the main window

### ISSUE THREAD

**Issue by TipsyOne** [rmcrackan/Libation#169]
When manually starting a download a new window opens to display its status. If another is started its window gets stacked on top of the previous ones. This can cause a mess of windows if several are running at once.  

I would suggest creating a docked queue window that allows prioritizing active/upcoming downloads, and a toggle between simultaneous and sequential downloads.

**Comment by rmcrackan** [comment]
Addressed in new version [v7.6](https://github.com/rmcrackan/Libation/releases/latest)
