### ISSUE TITLE
Process stops on any failure, can't continue past failed book.

### ISSUE THREAD

**Issue by ApKNJ** [rmcrackan/Libation#17]
I'm not sure if there will be any further work done on this since Audible is apparently on the verge of making it obsolete, so let me take this opportunity to say thanks for this app, I wish I had found it sooner!
But just in case:
During a full library liberation, when Libation encounters a book it cannot download or cannot decrypt, the process stops, and there does not appear to be a way to prevent it from retrying the same failed book each time.   I am not clear if the bulk download process is supposed to process only filter-visible items, but in any case, it doesn't.

I found a workaround by manually creating a dummy folder with dummy files in the completed books folder, which apparently makes it think the book is already completed.

**Comment by rmcrackan** [comment]
That's a fine work around for now.

Thanks for the log file. It's pretty big, can you tell me which book was
giving you trouble?

RE audible making it obsolete: depends on what they do. If they actually
improve their service so all users can easily backup and organize their
titles, then I'll be the first one glad that I'm obsolete. If they're just
adding new encryption like with the aaxc files, that's just a cat and mouse
game and there are already some complex work arounds that will only get
easier as more programmers attack the problem. Your thanks is appreciated.
I hope there's a lot more life in projects like this, either mine or from
some other kindred spirit

**Comment by rmcrackan** [comment]
I think I found the issue. See if the latest version 4.1.0 fixes your problem: https://github.com/rmcrackan/Libation/releases/latest

**Comment by ApKNJ** [comment]
Hi,
I'm not sure how git hub's notification system works, so please reply to at
least let me know you received this.
I tried 4.1., but it throws an error immediately on trying to do a library
scan that says "Contact administrator."

There have been half a dozen or so books so far causing it to stop, with
different issues.
Some examples are

[B002V8MVY2]
 [2291080687]
[B002UZZ3KK]
[B003NTGE14]

**Comment by rmcrackan** [comment]
D'oh! Sorry, I rushed the previous release in my excitement of the bug fix. That crash is fixed in the latest version. Let me know if your original issue persists.

**Comment by ApKNJ** [comment]
Awesome, thanks!   I got all the way through my library (except for a dozen
or so items that failed with various errors but I will start another run to
a new folder later today just to test and compare.

**Comment by ApKNJ** [comment]
4.1.1 fails and stops on the same first book, with the same error as before:

12/3/2020 3:50:37 PM Download Step, Begin: [B002UZZ3KK] Golden Age of Radio
12/3/2020 3:50:37 PM Download Step, Completed: [B002UZZ3KK] Golden Age of
Radio
12/3/2020 3:50:37 PM ERROR: Value cannot be null. (Parameter 'source')
12/3/2020 3:50:37 PM DONE

Let me know if you'd like me to do any specific further tests.   I have no
personal need to export my library again, though  I am happy to help test.

**Comment by rmcrackan** [comment]
Can you post a link to your new log?

>

**Comment by ApKNJ** [comment]
Here you go.   Just to illustrate two of the several different errors I encountered across my library, this log contains the initial run, which failied on the first book, then another run, after creating a fake folder for that book, to capture a different error on the next book.
[Log202012.log](https://github.com/rmcrackan/Libation/files/5661401/Log202012.log)

**Comment by ApKNJ** [comment]
By the way, I see you're not completely anonymizing the logs.

**Comment by rmcrackan** [comment]
The latest version should give us better debug info in your next log file

https://github.com/rmcrackan/Libation/releases/latest

RE anonymizing: can you point to a specific place? I'll try to improve it

>

**Comment by ApKNJ** [comment]
New log attached, again showing the first two errors it stops on.
Search for "account" and you'll see where there is some info some folks might find sensitive.
(in fact I wouldn't mind if you deleted my logs from git hub when you were done.)
BTW, the folder in the zip this time was called win-x64 rather than libation 4.1.2, not sure if that was intentional or not.
[Log202012.log](https://github.com/rmcrackan/Libation/files/5666804/Log202012.log)

**Comment by rmcrackan** [comment]
Resolution: new temp feature added to bypass troublesome books, usually titles which were added to library 15+ years ago
