### ISSUE TITLE
Multiple action options for Libation icon (especially to play folder with external app)

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#170]
Currently, clicking the Libation icon in each row will either download the audiobook or open the folder of the downloaded book. How about adding an option to send the folder as a parameter to an app like a player? I think being able to play the item is an important missing element when treating Libation as an organizer than just a downloader. Another option is to open the audible page so one can read the reviews.

In settings, you can have:
Icon Action
Click: [_] download/open folder [_] Open audible page [_] Custom: <application path + parameters> <item folder path>
Shift+Click: [_] download/open folder [_] Open audible page [_] Custom: <application path + parameters> <item folder path>
Ctrl+Click: [_] download/open folder [_] Open audible page [_] Custom: <application path + parameters> <item folder path>
Alt+Click: [_] download/open folder [_] Open audible page [_] Custom: <application path + parameters> <item folder path>

On second thought, I hate features that are only accessible by key combos (hate VI and WordPerfect was tolerated). Would be nice to have those functions tied to text/icon/menu links.

**Comment by rmcrackan** [comment]
Thanks for the ideas. Sorry this has taken me literally half a year to get to.

> How about adding an option to send the folder as a parameter to an app like a player?

I'm not sure what you mean. Do you mean this?

* new setting for execution string. eg: `C:\foo\music_player.exe %1`
* new link, when clicked: execute command which will launch music_player with book's folder in the %1 parameter?

I like the idea in principle. To be useful though, I'm afraid of the hoops I'd have to jump through to support different player's inputs. I imagine most would need file path. Some would need folder path. Many users download with the option to split the book into chapters so those same questions but for multiple files.

> Would be nice to have those functions tied to text/icon/menu links

I'm skeptical that this would add much value. The grid isn't overly keyboard-friendly so you'd still have to click on the row, then you could use the keyboard to get to menus. It's not too different from just clicking on the button.

> open the audible page so one can read the reviews

Good idea. This big text is so I can find it easier later

# Feature request: Link to Audible's product page (remember to link to the correct region's website)

> Would be nice to have those functions tied to text/icon/menu links

I'm skeptical that this would add much value. The grid isn't overly keyboard-friendly so you'd still have to click on the row, then you could use the keyboard to get to menus. It's not too different from just clicking on the button.

**Comment by rmcrackan** [comment]
This link will be included in the next release
