### ISSUE TITLE
ATTENTION: please report login/register bugs HERE

### ISSUE THREAD

**Issue by Adramelech91** [rmcrackan/Libation#175]
Could not register

   at AudibleApi.Authorization.Authorize.RegisterAsync(AccessToken accessToken, IEnumerable`1 cookies)
   at AudibleApi.Authorization.IdentityMaintainer.RegisterAsync()
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity, IAuthorize authorize, ISystemDateTime systemDateTime)
   at AudibleApi.Authorization.IdentityMaintainer.CreateAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(IIdentity identity)
   at AudibleApi.EzApiCreator.createApiAsync(Identity inMemoryIdentity, String identityFilePath, String jsonPath)
   at AudibleApi.EzApiCreator.GetApiAsync(ILoginChoiceEager loginChoiceEager, Locale locale, String identityFilePath, String jsonPath)
   at AudibleUtilities.ApiExtended.CreateAsync(Account account, ILoginChoiceEager loginChoiceEager) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 30
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libatio
n\ApplicationServices\LibraryCommands.cs:line 136
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

[Log202112.log](https://github.com/rmcrackan/Libation/files/7770919/Log202112.log)

**Comment by rmcrackan** [comment]
Have you tried the alternate login?

**Comment by Adramelech91** [comment]
> 

Yep, same Error
I use Libation on Windows 10 and work well, this error is On Windows 11

**Comment by rmcrackan** [comment]
Daaaaaaamn. I don't have Windows 11 yet and I can't even imagine how they managed to F this up. Maybe try on a Win10 machine then move the AccountsSettings.json file onto your computer. Don't leave that on someone else's machine though -- it's what says you're logged in as you.

I'll keep this bug open but probably can't do much with it until after I upgrade to 11

**Comment by Adramelech91** [comment]
I install VM with Windows 10 and have same error... When I have Windows 10 Log File I Update it

**Comment by inSpades007** [comment]
I d/led Libation today on a Windows 7 PC and get the 'Could not register' error.  I've tried a few times including copy and pasting the url but it's a no go.  Hope the attached log helps.
[_Log202112.log](https://github.com/rmcrackan/Libation/files/7791131/_Log202112.log)

**Comment by rmcrackan** [comment]
Wow, this is not good. I just started a new job and I have no idea when I'll have time to do a deep dig into this. I hope audible didn't change something with the registration process that will break this for everyone!

**Comment by rmcrackan** [comment]
**UPDATE**

I suspect audible has changed something with their international logins

* Italy, India, and Canada are having login/registration errors
* Spain doesn't work at all
* US, UK, Germany so seem unaffected

I'll continue to look into this as my time allows.

**Comment by rmcrackan** [comment]
@mkb79 : Have you been experiencing new login errors? To recap: I suspect audible has changed something with their international logins

* Italy, India, and Canada are having login/registration errors
* Spain doesn't work at all
* US, UK, Germany so far seem unaffected

**Comment by mkb79** [comment]
@rmcrackan : I wish you a happy new year! I‘ve tried it myself to login and register to Audible India with my package. And it's run fine. Will test later again.

**Comment by rmcrackan** [comment]
@mkb79 Thanks! Happy new year to you too.

I cannot figure out what is going wrong. The basics of the code that is failing for the users above hasn’t changed in a very long time and it’s working fine for nearly all users.

**Comment by ekt-** [comment]
I'm having the same 'Could not register' error as the OP. I'm on Win10, Italy marketplace, no 2FA
I can run it in debug in visual studio if it could be of any help but I'm afraid that that response 400 Bad Request leaves little doubt as to where the problem lies. let me know if I can be of any help anyway

[Log202201.log](https://github.com/rmcrackan/Libation/files/7804344/Log202201.log)

**Comment by rmcrackan** [comment]
@ekt

> I can run it in debug in visual studio if it could be of any help but I'm afraid that that response 400 Bad Request leaves little doubt as to where the problem lies.

It's suggestive but unfortunately it's not 100% obvious. I've encountered at least 2 places where amazon returns 4xx codes on success pages.

Since the code for registration is in AudibleApi, if you want to debug it: clone Libation and AudibleApi. Add the AudibleApi project in Libation's solution. In Libation's AudibleUtilities, add a project reference to AudibleAPI. VS 2019 or 2022 should now debug straight into the AudibleApi code. RegisterAsync is in AudibleApi/Authorization/Authorize.cs

**Comment by mkb79** [comment]
@rmcrackan: You have changed the register url for pre-amazon accounts some weeks ago. Maybe you have changed this globally?

**Comment by Ibanez1981** [comment]
@rmcrackan Hi, same error here (italian account on Win 7 laptop) :-(

**Comment by ekt-** [comment]
@rmcrackan ok got it. I'll try and report back. 
btw: OpenAudible works fine and their last release is 30 days old. so I don't think the amazon service has changed

**Comment by mkb79** [comment]
@rmcrackan The issue is in this [commit](https://github.com/rmcrackan/AudibleApi/commit/13224be7de7871a5578492ab41655a1d2b508421). As far as I understood on your code you change the registration url globally. But the url should only be changed for pre-amazon accounts.

**Comment by rmcrackan** [comment]
Thank you everyone for your help and patience. Please try [v6.6.3](https://github.com/rmcrackan/Libation/releases/latest) and reply with whether or not it solves your problem.

@mkb79 : Thank you again! You are amazing as always :)

**Comment by mkb79** [comment]
@rmcrackan: I just gave the hint. You did the work! So you deserve the honor!

**Comment by ekt-** [comment]
@rmcrackan v6.6.3 works great

**Comment by inSpades007** [comment]
Confirmed v6.6.3 is working!  Awesome job guys.

**Comment by Ibanez1981** [comment]
COnfirm working even on win 7! Thanks a lot!

**Comment by trueciccioformaggio** [comment]
It works fine in Italy with Win10!
