### ISSUE TITLE
amazon spain library not available

### ISSUE THREAD

**Issue by brunomalone** [rmcrackan/Libation#176]
[_Log202112.log](https://github.com/rmcrackan/Libation/files/7781130/_Log202112.log)

**Comment by rmcrackan** [comment]
Sorry -- that's frustrating. Does the alternate login method work?

**Comment by brunomalone** [comment]
No, it doesn't, however the US library works perfectly for the same amazon user.

**Comment by brunomalone** [comment]
This is what i got with the alternate login metho
[Log202112.log](https://github.com/rmcrackan/Libation/files/7785833/Log202112.log)
d

**Comment by brunomalone** [comment]
Maybe it has something to do with this: Spanish marketplace is not available 

[img]https://i.imgur.com/P5FuVJU.png[/img]

**Comment by rmcrackan** [comment]
Weird. What region are you supposed to be a part of?

**Comment by rmcrackan** [comment]
Note: where you physically live is not necessarily the same as audible's region

**Comment by brunomalone** [comment]
> Weird. What region are you supposed to be a part of?
 
I don't know for sure, theoretically Spain (audible.es). I have 2 different libraries depending on whether I log into audible.com (no problem with this one) or audible.es, however audible.es is not available in audible app for windows, only using audible website or the app for android. So I thought it might be related to libation's inability to scan my library at audible.es. since libation works perfectly with audible.com, using the same username / password.

**Comment by rmcrackan** [comment]
Sorry, if it's not in the audible's official phone app, it might not work on Libation either :(

**Comment by rmcrackan** [comment]
Maybe I should remove Spain from the options since it doesn't appear to be fully supported in the official app. I'll look into this soon. In the meantime, I don't think there's anything else I can do

**Comment by rmcrackan** [comment]
There seem to be a lot of recent issues with not being able to log in. I suspect audible changed something on their end. I'm going to track them all together in #175
