### ISSUE TITLE
App doesn't work with audible usernames?

### ISSUE THREAD

**Issue by cniekel** [rmcrackan/Libation#178]
I tried to login using the username / password, that didn't work.
So I tried to use the "copy links" method, and I thought that worked, but I always got 0 books in my library. And chrome still wanted me to login, which was the hint.

So I have an audible.de account. The url I copy in the app brings me to `https://www.amazon.de/ap/signin?...`, and there I can only choose Email-adddress or telephone number.

If I go manually to audible.de, click on "Anmelden", I always have to go to the bottom "Mit Benutzernamen anmelden" (which means login with username), if I go there it asks me for the username and password (and there is a separate "Login with amazon account").

However, the openid signin doesn't allow for a 'switch to audible usernames' toggle. Is there a way to trigger the audible-username with openid signin flow? I did just put my audible username in the app.

Thanks!

**Comment by rmcrackan** [comment]
What happened when you log in inside the app using "pre-amazon - germany"?

**Comment by cniekel** [comment]
I didn't see that option before! It worked, I now have all my books in the library!

Thanks for the quick reply!
