### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by planetajay** [rmcrackan/Libation#180]
[Log202112.log](https://github.com/rmcrackan/Libation/files/7794568/Log202112.log)

**Comment by rmcrackan** [comment]
No error was written tot he log. What did you see on screen?

**Comment by planetajay** [comment]
It wasn't logging into my A/c at all just throwing up errors

**Comment by rmcrackan** [comment]
Sorry, I wasn't clear enough. The log file you attached does not show any errors in it. Can you describe what you saw?

**Comment by rmcrackan** [comment]
I fixed some login bugs in the latest version [v6.6.3](https://github.com/rmcrackan/Libation/releases/latest). If this does not fix your bug, please reply and I'll re-open this issue.
