### ISSUE TITLE
Missing cover art in newly liberated audiobooks?

### ISSUE THREAD

**Issue by GH-Timmy** [rmcrackan/Libation#181]
I recently liberated my library and all books arrived in the program with cover art. The past couple of months, all of the books show the art on the download screen, but once complete, the cover art does not show on the main screen. I don't see a way to force the cover art to display. I even tried downloading again, but still no art on the main screen.

**Comment by rmcrackan** [comment]
Can you share a screen shot? What audible region is this happening for?

**Comment by GH-Timmy** [comment]
US Region. See attached
![LibationCapture1](https://user-images.githubusercontent.com/97370271/148703796-be02c7bf-6c05-4a4d-a3b5-9e162bbee465.JPG)
.

**Comment by rmcrackan** [comment]
Thanks for the screenshot.

This is very strange. I stopped Libation, renamed by images folder (so I'd have a back up), and restarted Libation. The first time it stalled out after a few hundred covers. So I restarted it and it did all the rest.

What happens for you if you do likewise?

**Comment by GH-Timmy** [comment]
Can you advise me on where the images folder is located? I've looked in the Libation directory and sub-folders and don't see an images folder.

**Comment by rmcrackan** [comment]
Sorry for skipping that part. Go to Libation settings and click the button to take you to the logs. That folder has all of your settings including the folder of downloaded images.

**Comment by GH-Timmy** [comment]
I made a backup of the Images folder which had 507 files. Then I started Libation which created a new Images folder. This time, only 494 files loaded. Several more books now don't have cover art. I restarted Libation several times just to make sure.

**Comment by rmcrackan** [comment]
Strange that it will do a some but not all. You'd think this would be all or nothing. Can you attach the log?

**Comment by GH-Timmy** [comment]
See attached for January's log file. Let me know if you want any earlier ones.

[Log202201.log](https://github.com/rmcrackan/Libation/files/7850349/Log202201.log)

**Comment by rmcrackan** [comment]
Thank you for the log. No need for previous logs. The latest one will include stuff discussed in this thread.

No errors were logged. Is there any possibility that you could run Libation while connected to a different wifi network? Normally I would assume this is a regular bug. It's the fact that it works a little then stops -- that's what has me suspecting something else.

**Comment by GH-Timmy** [comment]
I'm hardwired directly to the router. No WiFi capabilities on this desktop PC.

**Comment by rmcrackan** [comment]
Sorry: I shouldn't have said wifi. I really just meant a different network. As in: is audible causing an issue based on your IP? I'd be curious to see how Libation acted when you were on a different IP

**Comment by GH-Timmy** [comment]
I used a VPN connection which changed my IP address. Then, I repeated the test of deleting the Images folder. Same result. I never get past 494 image when I have 521 books (give or take a couple).

**Comment by rmcrackan** [comment]
Can you zip and and [email me](https://github.com/rmcrackan) your database file? I'd like to see how it acts on my computer. The database file contains your books but no access to your account.

**Comment by GH-Timmy** [comment]
Not at my house at the moment. Would you provide details on where the db file is located? I'll send when I get home.

**Comment by rmcrackan** [comment]
Thanks for the database! This is now fixed in [v6.6.5](https://github.com/rmcrackan/Libation/releases/latest). After you run this version for the first time, do a new import/scan. It's possible there are a few with no covers but it shouldn't be NEARLY as many.
