### ISSUE TITLE
Error while importing 

### ISSUE THREAD

**Issue by samrutur2** [rmcrackan/Libation#184]
Getting this error while importing books from audible.co.au. Not sure whether it is related to AU account, since I was able to import books from another AU account of mine
[Log202201.log](https://github.com/rmcrackan/Libation/files/7844630/Log202201.log)
.

**Comment by rmcrackan** [comment]
Thank you for the error log. The latest release [v6.6.4](https://github.com/rmcrackan/Libation/releases/latest) should fix your issue

**Comment by samrutur2** [comment]
Thanks! That was fast!
