### ISSUE TITLE
Support to download as .aax without modification

### ISSUE THREAD

**Issue by oucil** [rmcrackan/Libation#185]
Hey there, first, thanks for your work on this, it's greatly appreciated!

Till now, I've been using the Windows 10 app to download the audiobooks in AAX format to my PC, then I use "[AAX Audio Converter](https://github.com/audiamus/AaxAudioConverter)" to convert to MP4, strip DRM, etc. so I can use my preferred media programs (Plex / Chronical / Prologue).  

My wife and I share a single Audible account as Canada doesn't support "Family" members with their own libraries/listening positions on the same account, and now that the kids are into audiobooks, and are listing to a lot of the Plus catalogue, which can't be download in the windows 10 app, it means they can't listen to the same book at the same time.... enter Libation!

AAX Audio Converter allows me to break the AAX files into individual chapter files which I prefer, but it will only work with AAX files and yours outputs MP4 files so I was wondering how much work it would be to add a checkbox to allow me to download just the raw AAX files in your app without any extra work being done to them?

Again, much appreciated!
Cheers,
Kevin.

**Comment by rmcrackan** [comment]
Libation will also break them into chapter. Settings > "Download/Decrypt" tab > "Split my books in to multiple files by chapter"

**Comment by oucil** [comment]
Oh, jeez, I thought I read through all the settings, my bad!  Thanks for that!

**Comment by rmcrackan** [comment]
No worries. Glad to help.
