### ISSUE TITLE
FEATURE REQUEST: Ability to set tag naming paterns the same way I can set file/folder patterns

### ISSUE THREAD

**Issue by oucil** [rmcrackan/Libation#186]
It's great that I can use variables for the file naming conventions, but it'd be really nice to be able to set patterns for the actual meta tagging as well.  For instance, right now, all tracks are using the book title even when there is a specific chapter name available.  Also, the track numbers aren't set at all.  

At the moment I can sort of use Mp3Tag to bulk update the files and tags, but even then, books that are in a series and include book numbers, or that have a secondary title are different than books without so I can't do a full bulk change to all at once, I have to update each book individually.

Lastly, it would be great if we could set the Audible ID to be stored in a tag, i.e. "Comment", rather than the file name.

Thanks!

**Comment by cadric** [comment]
I was just about to open a feature request on something like this, but instead I will comment here :)

Tags I would like to see used are:
Title, Artist, Album Artist, Album, Discnumber, Year, Genre, Publisher, Comment, and Track

You are allready doing many of the things I list below, but some tags are still missing. 
Also it seems the tags allready have the correct chapter "title" and track numbers are set correctly in tags.
The tags I see missing or wrong is: 

- Album Artist - Should be blank as the writers name is allready in Artist
- Narrator - (See *1) Should be the name of the narrator
- Album - Should only be the title of the audiobook and not include series title  or book number
- Series - A tag for the series. (See *2) below
- Discnumber - Book number
- Publisher - Which recording studio made the audiobook


Using tags I would like to tag a book like [Apocalypse: Generic System](https://www.audible.com/pd/Apocalypse-Generic-System-Audiobook/1039404472) as this.

```
M4B Tag                         Audible "book info"                 Audible "tag"
Title                           Chapter 1: May Cause Drowsiness   - Chapter name or number
Artist                          Macronomicon                      - By:
Narrator                        Steve Campbell                    - Narrated by:
Album                           Apocalypse: Generic System        - Book title
*2                              Systems of the Apocalypse         - Series:   
Discnumber                      1                                 - Series:, book number
Year                            2021                              - Release date:
Genre                           Science Fiction                   - Audible category
Publisher                       Podium Audio                      - Publisher
Comment                         Asin: 1039404472                  - Product_ID/ASIN
Track                           Chaper Number                     - Chapter numbers should be set in track
```
*1 There is support for a [narrator](https://help.mp3tag.de/main_tags.html) tag in mp4
*2 I am unsure what tag should be used for the series name. Maybe its correct to just put it with the album name as it currently is.

I have no idea if you can pull and set the tags like that, but it would be great if we could get better tags then you allready have. And thanks for all the work you are doing.
[Screenshot](https://cdn.discordapp.com/attachments/716631234398257215/942489849393479812/unknown.png)

**Comment by turfutils** [comment]
Came here to ask just the same thing but you already asked, thankyou! 

This would be very helpful when using players like VLC to listen to a book split by chapters because now every chapter is called the name of the book and it's hard to know if every chapter is in order.

It doesn't have to be settable exactly like the filename, just a "ch05" for chapter 5 in the name tag would do wonders.

**Comment by Mbucari** [comment]
Both mp3 and mp4 support metadata tags for track number. When converting to multi-part MP3 files, libation does set the track number in the metadata tags. However, I have not yet added the track tag for mp4 files, but I'll do that soon.

Would having the track number in the metadata tags solve your problem, or would you still want The track number in the title tag as well?

**Comment by turfutils** [comment]
That sounds great!

The track number helps the current problem for us at least but some players do not display this number in lists so it would still be nice with the possibility of adding a chapter number in the name tag.

**Comment by oucil** [comment]
Track number is definitely a good start, but if you are going to bother setting the chapter tag, you may as well use the chapter title supplied by Audible, many books have named chapters, not simply numbered chapters.

**Comment by oucil** [comment]
@wtanksleyjr that's why I specified in my original feature request the ability to use the same variables used elsewhere in the app so that users can specify based on their own preferences.

**Comment by rmcrackan** [comment]
Added to [version 8.0.3](https://github.com/rmcrackan/Libation/releases/latest)
