### ISSUE TITLE
Feature Request: Allow saving the original aax

### ISSUE THREAD

**Issue by TomboAhi** [rmcrackan/Libation#187]
I would like an option to  download and save the original encrypted .aax file, as is, without any decryption or conversion.

**Comment by rmcrackan** [comment]
Interesting. Can I ask what advantage this has over the decrypted .m4b file? The decrypted m4b file is the same audio quality, only without the drm.

**Comment by TomboAhi** [comment]
Downloading a book is significantly faster than decrypting it. So having the option to not decrypt will allow for the download of a large library as well as keeping the library in sync with your local copy would be significantly faster because the added process of decryption is not taking place. 

It would also affords the flexibility to decrypt the books independently, as needed in the format needed at the time. It will always be there as the aax and if I want book A as an M4b for an audiobook player but then want another book as MP3 for use in the car, I can only do what I need when I need.

**Comment by Kazaa3** [comment]
I would like to add that depending on the country laws of the user, the legal classification of the backup could be different. A simple backup is legal almost everywhere in the world. The .m4b conversion could possibly mean circumventing an effective copy protection measure, so the situation is less clear (although of course it's sad that we live in a world where an honest buyer may have to worry about such things). But saving the original Audible files could give a user this security. 

Btw: An extension of this feature could be a post batch conversion of the original files as well as a NAS storage path for the archive that is syncronized around by newly added files.

**Comment by wtanksleyjr** [comment]
I remember asking for the app to preserve AAX files. This was back when the
app used to download them --- it doesn't anymore.

Aside from that: I'm not sure where you heard that. Downloading a book is
vastly slower than decrypting it. Decrypting is extremely simple and
straightforward, a matter of memory access only, while downloading requires
network access. I think you might be thinking of the old rainbow-table hash
attack that older tools like OpenAudible use; this application doesn't use
any attack, it simply uses Audible's API to get the files and the proper
decryption key.

You might be right that the legal classification could be different, I'm
not a lawyer and even lawyers have to be specialists to do that kind of
thing. I know it's no different in the US code -- so long as the software
CAN decrypt the files it's a circumvention device, even if it doesn't
actually DO the decryption. It's notable, therefore, for the sake of laws
that concern themselves with this, that downloading the AAX files is
officially supported by their own public website for the purpose of loading
them into iTunes. I would suggest, though, that what you want if you're
trying to be safe is probably to stick with what's on their public website
and not to use an app like this.

-Wm

**Comment by TomboAhi** [comment]
>Decrypting is extremely simple and straightforward, a matter of memory access only, 
>while downloading requires network access.

Really? So you are saying that this application doesn't use network access to get the files to decrypt? So I assume the encrypted aax just magically materializes for the application to decrypt/convert?

Download vs Download & Decrypt/Convert -- hmm!

**Comment by rmcrackan** [comment]
At the moment, all enhancements are being put on the back burner for a bit. I started a new job recently so only bugs are getting immediate attention.

For now, I hope this will help alleviate your concerns from above:

> Downloading a book is significantly faster than decrypting it.

I disagree. Download+decrypt is slower than *just* download or *just* decrypt. However, the decrypt step is extremely fast. Download and Decrypt used to be separate steps, with aax existing on the hard drive in the mean time. The better decryption library that I've been using for the last year combines download+decrypt and is vastly faster than the old way. By decrypting at the same time as it downloads instead of in 2 separate passes, it's very nearly as fast as just the download alone.

> It would also affords the flexibility to decrypt the books independently, as needed in the format needed at the time. It will always be there as the aax and if I want one book as an M4b for an audiobook player but then want another book as MP3 for use in the car, I can decrypt/convert them as what I need when I need.

The m4b files that Libation creates are just the decrypted aax/aaxc files. Converting aax => mp3 is the same as converting aax => mb4 => mp3, except that the initial step has already been done for you.

**Comment by wtanksleyjr** [comment]
TomboAhi ***@***.***> wrote:

> Decrypting is extremely simple and straightforward, a matter of memory
> access only,
> while downloading requires network access.
>
> Really? So you are saying that this application doesn't use network access
> to get the files to decrypt? So I assume the encrypted aax just magically
> materializes for the application to decrypt/convert?
>
Tombo, my point is that downloading and then skipping decryption doesn't
save any real time, and won't protect you from legal trouble if your local
laws prohibit circumvention of copyright anti-infringement measures.
There's therefore absolutely no reason to skip decryption without also
skipping the download.

-Wm

**Comment by Mbucari** [comment]
I've made some improvements too AAX clean recently, and now downloading a decrypting truly is just as fast as downloading, provided your machine has at least two cpu cores.

**Comment by rmcrackan** [comment]
@Mbucari thanks again sir. I'm making some performance enhancements to the UI also. Between your changes and mine, Libation is getting really speedy!

Now if only I can remember how to just download aax files. I figured out why some people want this feature.

* 1 reason is because they want to back them up raw because they think Libation messes with them somehow. That just takes a little education in how Libation works. And is further evidence that my documentation is lacking.
* The other reason sounds legit: evidently on android you can drop aax/aaxc files onto the device somewhere and have them recognized by the audible app.

**Comment by Mbucari** [comment]
Gotcha.  Anyway, ours is not to reason why. Ours is to implement features if we feel like it, when we get around to it!

Re saving the aax file, Libation simultaneously downloads the aax to a temp file and feeds it to the decrypter via NetworkFileStream.  The reason for that was to allow resuming of interrupted downloads for users with shaky internet.  The temp file is deleted in AaxDecrypter.AudiobookDownloadBase.Step_Cleanup().

As for performance,  simultaneously writing two files (temp file and decrypted file) in an I/O bound routine is going to slow things down. Most people are network limited, so they won't see the issue. I'm not one of those people!

**Comment by Mbucari** [comment]
Actually, I just noticed that Libation is no longer making use of the temp files for resumable downloads.  If a .tmp or .json file already exist,  Libation ignores them and starts a new files with a (n+1) suffix.  Is that intentional?

**Comment by rmcrackan** [comment]
@Mbucari not intentional at all. I have no memory of having touched that. I would very much prefer the ability to resume.

**Comment by rmcrackan** [comment]
@Mbucari These are the weeds with which you are most familiar. How difficult would it be to enable 'resume' and also provide a setting for 'save original aax file', default: false?

**Comment by Mbucari** [comment]
Not too difficult I think.  Let me look at it before you accept my PR.

**Comment by rmcrackan** [comment]
Lol, sorry. I did that before seeing this note. No worries. Change whatever you need to in that space. I trust you.

**Comment by rmcrackan** [comment]
Added in [v7.2](https://github.com/rmcrackan/Libation/releases/tag/v7.2.0)!
