### ISSUE TITLE
Feature request: Import/Export auth file to Libation

### ISSUE THREAD

**Issue by mkb79** [rmcrackan/Libation#189]
@rmcrackan 
Hello. My app audible-cli stores the auth files in the dir `C:\Users\<user>\AppData\Local\audible` in Windows. Is it possible to add a function into Libation to import these files? Would it also be possible to export credentials from Libation as an auth file to the directory above?

**Comment by rmcrackan** [comment]
I started a new job recently so I'm not adding features at the moment; only addressing bugs. However, it's just json. I'll be glad to detail it for you and I'm happy to answer questions:

In `Libation.exe`'s folder, `appsettings.json` says where to find the directory where settings and persistence live. To see this dir from the UI:

* launch Libation
* Settings menu > Settings...
* Click "Open log folder"

Account-specific settings and tokens are in `AccountsSettings.json`. Here's an annotated sample with valid values (except for `<<<REDACTED>>>` parts):

```

{
// any number of account objects can be in this json array
  "Accounts": [
    {
// account name. usually email
      "AccountId": "fake-us@gmail.com",
// user editable. default is the account id without "@" and domain
      "AccountName": "fake-us",
// setting. when you choose to scan 'some' accounts, this setting says
// whether to include this account to by default
      "LibraryScan": true,
// I think this no longer applies
      "DecryptKey": "",
      "IdentityTokens": {
// you can see the locale name options here:
// https://github.com/rmcrackan/AudibleApi/blob/master/AudibleApi/Localization.cs
        "LocaleName": "us",
        "ExistingAccessToken": {
          "TokenValue": "Atna|Ew<<<REDACTED>>>vg",
          "Expires": "2022-01-19T22:33:26.7167657Z"
        },
        "PrivateKey": {
          "Value": "-----BEGIN RSA PRIVATE KEY-----\nMI|Ew<<<REDACTED>>>RE\n-----END RSA PRIVATE KEY-----\n"
        },
        "AdpToken": {
          "Value": "{enc:w4|Ew<<<REDACTED>>>==}"
        },
        "RefreshToken": {
          "Value": "Atnr|Ew|Ew<<<REDACTED>>>BA"
        },
        "Cookies": [
          {
            "Key": "session-id",
            "Value": "14|Ew<<<REDACTED>>>43"
          },
          {
            "Key": "session-id-time",
            "Value": "22|Ew<<<REDACTED>>>1l"
          },
          {
            "Key": "i18n-prefs",
            "Value": "USD"
          },
          {
            "Key": "skin",
            "Value": "noskin"
          },
          {
            "Key": "ubid-main",
            "Value": "13|Ew<<<REDACTED>>>32"
          },
          {
            "Key": "session-token",
            "Value": "\"iK|Ew<<<REDACTED>>>w=\""
          },
          {
            "Key": "lc-main",
            "Value": "en-US"
          },
          {
            "Key": "sid",
            "Value": "\"bG|Ew<<<REDACTED>>>M=\""
          },
          {
            "Key": "x-main",
            "Value": "\"Ub|Ew<<<REDACTED>>>tH\""
          },
          {
            "Key": "at-main",
            "Value": "Atza|Iw|Ew<<<REDACTED>>>vQ"
          },
          {
            "Key": "sess-at-main",
            "Value": "\"mg|Ew<<<REDACTED>>>g=\""
          }
        ],
        "DeviceSerialNumber": "RJ|Ew<<<REDACTED>>>IO",
        "DeviceType": "A2|Ew<<<REDACTED>>>VM",
        "AmazonAccountId": "amzn1.account.AG|Ew<<<REDACTED>>>UQ",
        "DeviceName": null,
        "StoreAuthenticationCookie": null
      },
// user name as it appears in log files
//   first letter, "[...]", and last letter of each group
// It saves time to cache this here so I don't have to recalculate
// it for every log call where username is relevant
      "MaskedLogEntry": "AccountId=f[...]s@g[...]l.c[...]m|AccountName=f[...]s|Locale=us"
    }
// for multiple accounts
    , {
      "AccountId": "example@gmail.com",
etc...
    }
  ]
}

```

**Comment by Mbucari** [comment]
I looked at doing this.  Libation's Account structure and @mkb79's auth (m_auth) file are almost 1:1 compatible. But there are a couple of small discrepancies that could cause problems.

Libation's Account file stores the user's id (email address), but m_auth doesn't.
m_auth tracks the user's name, account_pool, and home_region, but Libation doesn't.

@rmcrackan & @mkb79, you two understand this system far better than I do. Will these fields cause problems if they are blank?

**Comment by rmcrackan** [comment]
Libation needs email for login and for keeping track of which book came from which account so it can avoid insert collisions if the book is in 2 accounts of the same region. Something else could be used for the 2nd part but it would have to be unique.

Libation's account file tracks region. I'm not sure if this is the same as m_auth's home_region

**Comment by mkb79** [comment]
I'm storing the `user_id` in `customer_info` which is unique to identify a user/account.

**Comment by mkb79** [comment]
But the email and user_id can be request by the `https://api.amazon.{domain}/user/profile` or `https://api.audible.{domain}/user/profile`. So this data can be completed.

**Comment by Mbucari** [comment]
https://api.amazon.com/ has been down for me all morning. Are either of you able to access that domain?

**Comment by mkb79** [comment]
> https://api.amazon.com/ has been down for me all morning. Are either of you able to access that domain?

us and de running fine for me!

**Comment by Mbucari** [comment]
I cannot get this to work.  I [copied your code exactly](https://github.com/mkb79/Audible/blob/a367ec497eb2ef464beeb5024b9918f677a5a5b0/src/audible/auth.py#L128), but I keep getting `invalid_token` error. 

Does your implementation work? It doesn't look like [user_name](https://github.com/mkb79/Audible/blob/a367ec497eb2ef464beeb5024b9918f677a5a5b0/src/audible/client.py#L138) is used anywhere.

**Comment by mkb79** [comment]
@Mbucari 
Yes, my implementation works. I tried it yesterday successfully. Have you refreshed your access token?

**Comment by mkb79** [comment]
An access token is only valid for 60 minutes. Then you have to refresh your token.

**Comment by Mbucari** [comment]
Success! I've implemented import/export from/to audible-cli. I have a couple of other features I'm working on for an upcoming release, so this feature won't be available until Libation 8 is released in about 1 week.

**Comment by rmcrackan** [comment]
@Mbucari fantastic. Should I close this issue now? or would you prefer me to wait until you fully integrate?

**Comment by Mbucari** [comment]
Let's leave it open until it's been released.

**Comment by rmcrackan** [comment]
@mkb79 : available in [version 8](https://github.com/rmcrackan/Libation/releases/latest)

Thanks @Mbucari !!
