### ISSUE TITLE
Entering new account results in confusing demand for "local name".

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#19]
When adding a new account but failing to enter a locale name, then clicking "Submit", the system currently pops up an error dialog insisting that all accounts must be given a "local name". That tiny, tiny misspelling ("locale" vs. "local") resulted in me wasting 5 minutes trying to find a "local name" field (and trying to find whether I'd done something else wrong).

Ha ha, my bad ... but still a typo that could be fixed :) .

**Comment by rmcrackan** [comment]
D'oh! Thanks for finding my typo. That 'e' will be included in all future releases :)

I've now changed it to: Please select a locale (i.e.: country or region) for all accounts
