### ISSUE TITLE
Using converter on any m4b files

### ISSUE THREAD

**Issue by inSpades007** [rmcrackan/Libation#190]
I've loved the program and have other m4b files that I'd like to convert to mp3.  A couple of programs I've used more than doubles the original file size after converting to mp3 but Libation is able to shrink the converted mp3 files which I prefer.

Would you be able to make it possible to use Libation to convert other m4b files?

I've tried everything I can think of to fool the program in to converting but it only spits out a tiny 50k file.

**Comment by rmcrackan** [comment]
I'm on the fence regarding whether I'll add general purpose tools like this. Right now I'm focused on audible-centric conversion and organization. For now I'd recommend looking into some of [these](https://github.com/rmcrackan/AudiobookHub#backup-decrypt-convert-organize).

**Comment by CharlieRussel** [comment]
I would certainly appreciate it. Currently I use dbPowerAmp, which is an excellent program, but a bit of overkill for as rarely as I need it, and it's really more focused on music instead of audio books. So it knows zip about chapters, for example.

**Comment by jonjbm** [comment]
Can I ask why you guys would want MP3 over M4B? Is there a platform out there in the present day that can't play AAC (the codec M4B uses)? Just so you know, AAC is higher quality than MP3 at the exact same bitrate. If you transcode a 128kbps M4B to 128kbps MP3, you have inevitably degraded the quality. Unless you're using a very, very old platform that can't handle AAC, I don't see the reason for transcoding.

**Comment by inSpades007** [comment]
I just find it the most convenient format whether I'm on a computer or phone.  I find that not all the programs/apps I use recognize other formats.  So having everything as an mp3 gives me fewer headaches.

**Comment by flysalad** [comment]
I use fre:ac from freac.org to convert M4B into either a single MP3 or individual chapter MP3's. Lots of options and better than cluttering up Libation with unneeded functionality. I also have a lot of devices that don't do anything other than MP3. InAudible also does a good job of conversion of M4B to MP3 if you have that.
