### ISSUE TITLE
Maxium Title Length

### ISSUE THREAD

**Issue by tormaid** [rmcrackan/Libation#192]
I noticed one of the books I downloaded recently from Audible JP had the title slightly truncated, both in the file name and the .cue sheet. Is there some technical reason for this?

Full Title:
[13巻] 本好きの下剋上～司書になるためには手段を選んでいられません～第四部「貴族院の自称図書委員1」
Truncated:
[13巻] 本好きの下剋上～司書になるためには手段を選んでいられません～第四部「貴族院の自称図書委員

**Comment by bydioeds** [comment]
Any fix for this?

**Comment by rmcrackan** [comment]
> Any fix for this?

The original user opened this issue then closed it them self on the same day so it never hit my radar at all. Is this only an issue in JP?

**Comment by tormaid** [comment]
Yeah, I'm sorry. I saw [this](https://github.com/rmcrackan/Libation/issues/183) issue and figured this was the result of the same internal 50 character string limit.
