### ISSUE TITLE
Not getting any .nfo files

### ISSUE THREAD

**Issue by jonjbm** [rmcrackan/Libation#193]
In your README, it says when we download + decrypt a book we're supposed to get (in addition to the m4b and cue file) an nfo file which has "some general info about the book and includes some technical stats about the audiofile."

I haven't been getting any nfo files. I'd really like to be able to, especially technical info about the audio -- source/output formats, sample rates, channels, bitrates, whether or not the output is lossless and in the original audio, etc.

**Comment by rmcrackan** [comment]
tl;dr: sorry, no longer available

This is my fault -- I forgot to remove that line from the readme. With each new decrypt option that was added, the code for nfo files became increasingly cumbersome to maintain. About a year ago I decided that they'd outgrown their original intent. Most of this info is available via the export menu. Sorry, this is mostly book metadata, not file metadata. Decrypting to m4b is lossless -- aax/aaxc files are just encrypted m4b files. Obviously mp3 is lossy.
