### ISSUE TITLE
Error Importing Library: Sequence contains more than one matching element

### ISSUE THREAD

**Issue by rickwilliams08** [rmcrackan/Libation#194]
I was able to import my library about a month ago, and then had not run it since. Purchased some new books so I went to go run it again and I ran into an error importing the library.
I have tried removing the books from the library in Libation, deleting and re-adding my account, changing where the books are saved, closed out and restarted the program between each of these and each time resulted in the same error. I'm running the latest version 6.6.5

[Log202202.log](https://github.com/rmcrackan/Libation/files/7991815/Log202202.log)

**Comment by rmcrackan** [comment]
Thank you for the log file. Fixed in [v6.6.6](https://github.com/rmcrackan/Libation/releases/latest)

Damn, I was hoping to use release 6.6.6 for something about horror books, or maybe release it on Halloween :) Ah well. Thanks to your logs I found the bug. Sorry for the trouble.
