### ISSUE TITLE
Error when trying to sync library

### ISSUE THREAD

**Issue by jrgensol** [rmcrackan/Libation#195]
[_Log202202.log](https://github.com/rmcrackan/Libation/files/8007429/_Log202202.log)

**Comment by rmcrackan** [comment]
Thank you for the log. This appears to be a login issue. Sometimes it works if you try again the next day. If not, on that first box which asks for password: click the bottom link "Or click here" and it will guide you through logging in with the browser.

Please let me know if either of these works for you.

**Comment by jrgensol** [comment]
logging in with browser worked. Thanks
