### ISSUE TITLE
Feature Request: Export Description

### ISSUE THREAD

**Issue by macr0dev** [rmcrackan/Libation#197]
It would be great for leading the information into other programs such as booksonic, if it were possible to export the description into a text file.  I see that it already loads it in the app.  For reference, booksonic uses desc.txt and loads that automatically.  I'd gladly accept any file name that is most common and script to rename it myself on the fly.  Or a flag that asks for the name of the output file in the CLI.  
  
Alternative solution might be to include the description in the existing library export.  I wouldn't mind writing a script to do exporting from there.  That might make it a simpler solution to implement from your side.

Thanks!  Love the app.

**Comment by rmcrackan** [comment]
Have you looked at the export options? You can export all the metadata, incl. description, into csv or json (also excel but that's harder to use in scripts). These exports are also available in the [CLI](https://github.com/rmcrackan/Libation#command-line-interface) which is much more script-friendly than the main gui.

**Comment by macr0dev** [comment]
I've done the exports from the CLI as well as from the gui, in all three formats (json, csv, excel) and the description seems to be the only thing actually missing from what is visible in the app.  Am I missing a flag that makes it included?  I all seemed pretty straightforward.  
  
I just kind of assumed you'd left it out to avoid have to escape or replace all the special characters that get thrown in there...  :)

**Comment by rmcrackan** [comment]
Huh! Would you look at that. Maybe past-me didn't think anyone would find that huge text column of word vomit useful. Maybe past-me was just lazy. I really have no good answer about why I omitted that. It's now included in [the latest release: v6.6.7](https://github.com/rmcrackan/Libation/releases/latest). Thanks for the heads-up.

**Comment by macr0dev** [comment]
Awesome. Thanks for the quick update!  I'm working on a powershell script to parse the json library file and create the individual files I need.  I'm happy to share it when I'm done.  In case anyone else finds it useful.
