### ISSUE TITLE
Reported timeout

### ISSUE THREAD

**Issue by grranimals** [rmcrackan/Libation#199]
Hello, I've been using Libation with no issue (it's great!), but yesterday I started getting an error when I tried to rescan the library for import. It says the request is canceled due to a timeout, but when I go directly to Audible to try to download with their interface, there doesn't seem to be a timeout, it starts downloading immediately. I c&p'd the error message I got below. Please let me know if there is anything else I can try to resolve the issue. Thanks for your help.

> The request was canceled due to the configured HttpClient.Timeout of 30 seconds elapsing.
> 
>    at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client)
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client)
>    at AudibleApi.Api.getLibraryAsync(String parameters)
>    at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions)
>    at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups)
>    at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 131
>    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>    at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>    at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
>    at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
>    at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
>    at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

**Comment by rmcrackan** [comment]
Sorry to hear that. I've actually never had this time out on me. I'll be glad to take a look. Can you do this again and attach the log file to this issue? To find the log file, Libation > Settings > click Open log folder

**Comment by grranimals** [comment]
Yes, here it is, thank you!

[Log202202.log](https://github.com/rmcrackan/Libation/files/8119238/Log202202.log)

**Comment by rmcrackan** [comment]
Hmm. You mentioned you could d/l from their webpage so it's not an IP problem. since that works, I'll assume you can also download to your phone using the same wi-fi network. Have you recently logged in to a new device for that account? There are a limited number of active slots available. Maybe it kicked Libation out. Then again, that would probably be a more direct failure, not a timeout.

Maybe a fresh set of login tokens will help. Let's try this: in Libation, go to Settings > Accounts. Click `X` to delete that account. Click Save. Go through the steps to re-add the account. Scan. It will force you to log in again. Let me know if that scan is successful. If not, let's look at the new log file.

**Comment by grranimals** [comment]
Gave it a shot but it is still reporting the same issue. Here is the new log file:

[Log202202.log](https://github.com/rmcrackan/Libation/files/8120313/Log202202.log)

I actually don't have Audible on my phone but I could download the app just to give it a shot if it would be helpful. I don't think I've recently logged into a new device with the account, and even logged out of the browser version before trying Libation again this time around.

**Comment by rmcrackan** [comment]
What's interesting is that it let you log in again; so it's obviously actively communicating you.

A few things to try:

* With Libation closed, delete everything in this temp folder: C:\\Users\\paige\\AppData\\Local\\Temp\\Libation (to open: press the windows key, paste this, and hit enter)
* You're a few versions behind the [latest version](https://github.com/rmcrackan/Libation/releases/latest) of Libation. I recommend upgrading
* Can another non-browser device (like a phone) download a book using the same wi-fi network
* Can Libation on this laptop work when on a different wifi network?
* This is stretching since it used to work: check to see if a firewall or anti virus is blocking it
* Change the Libation setting for logging to Debug and try again. This will create a more detailed log.

If none of this works, I can create a temporary custom version for you with a really huge timeout and we'll see if that makes a difference.

**Comment by grranimals** [comment]
Thanks for all your help so far! Unfortunately the problem is persisting but here is what I have tried:

- Deleted everything in the temp folder
- Updated to latest version
- I tried the Audible app and it will let me download on the same wi-fi
- I checked my antivirus and as far as I can tell it's not flagging Libation
- I attached the debug log

I did try to use Libation on a "different" network, but it's actually kind of the same network--a "guest" network, still hosted by my same ISP on our network. It didn't work. I am on satellite internet so sometimes there is a latency issue, although I will say that Audible typically has the lowest lag (among things like Netflix, Youtube, etc). Usually this lag is just in the start up of something and once a stream is established it poses no problems. Not sure if that could be affecting it, although like I say, it can download from the app. I'm planning on taking my laptop somewhere else tomorrow and trying to stream from a network that is actually different.

Also something interesting I noticed, not sure if this will be helpful in the slightest... I moved everything in the "Images" folder (C:\Users\paige\Libation\Images) to a different location on my computer. At first when I had Libation open, all of the cover images were missing. After I tried to import my library, they reappeared, and checking the timestamps on them confirmed that they had just been re-downloaded. So it's definitely making a connection and transferring content...just not importing the library. I also tried removing some books from my library to see if that would help by lightening the load or something but hasn't seemed to help so far.


[Log202202.log](https://github.com/rmcrackan/Libation/files/8121630/Log202202.log)

**Comment by rmcrackan** [comment]
Good idea about the images. That proves Libation is definitely communicating with audible. With the successful login, we know it's even communicating on the trickiest part of the communication. Agree that your guest network is going to likely have the same limitations because it's the same connection to your ISP.

I threw together a test with a 10 minute timeout. This is not a permanent solution; it will tell us though if the timeout is really the problem.

* Find where Libation.exe lives. It will be surrounded by tons of files, mostly .dll files
* Just in case, backup/rename AudibleApi.dll
* Download this: [AudibleApi.zip](https://github.com/rmcrackan/Libation/files/8125087/AudibleApi.zip)
* Unzip it
* Move those 2 unzipped files into Libation's folder. It will overwrite AudibleApi.dll
* Run your test again and let me know the result

**Comment by wtanksleyjr** [comment]
I work for ViaSat. Aside from latency, terminals automatically force the
TCP connection into a kind of strange streaming mode where mis-sent packets
can sometimes not be re-sent. That last might be a problem, since with a
large download you actually might lose a whole packet at some point.

If the Audible application works and we don't, there might be some extra
packet-by-packet error recovery they're doing and we're not.

-Wm

**Comment by grranimals** [comment]
Thanks for working with me so extensively on this. I wonder if it might be something along the lines of what wtanksleyjr brought up. I put the files in the program and tried again to import the library, and I think we might be able to rule out an actual timeout, because it came back with the same "timeout" error...even faster than usual, this time I think it was under a minute even, so it definitely did not attempt to import for the stated 10 minutes.

[Log202202.log](https://github.com/rmcrackan/Libation/files/8129435/Log202202.log)

Unfortunately I forgot to bring my laptop with me to test on another network but I should get another chance at that tomorrow so that's still something I'm planning on trying.

Thanks again for all your help.

**Comment by rmcrackan** [comment]
Thanks for the new log. Interesting -- I went back through all logs here. It was exactly 90 seconds each time, regardless of whether the timeout was supposed to be 30 seconds or 10 minutes. I'm pouring through code and documentation and I can't find this default anywhere. I'm very curious to know how your this works on a different network.

**Comment by rmcrackan** [comment]
Could you try doing this with Logging Level set to Debug? Maybe those more detailed logs can help.

**Comment by grranimals** [comment]
Okay, I did as you suggested, and when I hit import, it immediately gave me an error, and it was a new one!

> The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.

   at System.Convert.FromBase64CharPtr(Char* inputPtr, Int32 inputLength)
   at System.Convert.FromBase64String(String s)
   at AudibleApi.Cryptography.CreateRsaProviderFromPrivateKey(String privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 104
   at AudibleApi.Cryptography.signSha256(String private_key, String dataString) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 88
   at AudibleApi.Cryptography.CalculateSignature(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 74
   at AudibleApi.Cryptography.SignRequest(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 45
   at AudibleApi.Api.signRequestAsync(HttpRequestMessage request) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 75
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 68
   at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 62
   at AudibleApi.Api.getLibraryAsync(String parameters) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 226
   at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 206
   at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 307
   at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 131
   at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
   at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
   at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34


Do you think completely uninstalling and reinstalling would help?

**Comment by rmcrackan** [comment]
> it immediately gave me an error, and it was a new one! ... not a valid Base-64

D'oh. I did not think through my suggestion far enough. By just corrupting those, we couldn't even get far enough to test it. Instead we need them to be valid format but the wrong values. Let's kill the altered file and create a new test file from the original backed-up one. Instead of *deleting* characters for tokens and keys, *replace* a few characters in the middle with Z so the total length doesn't change. We should probably also only change one token/key between each test.

> Do you think completely uninstalling and reinstalling would help?

You're welcome to try but I don't have a lot of hope. Since it worked on a different network, a re-install will probably behave the same way. I suppose you could try removing the AccountsSettings.json file. You deleted and re-added your account a week ago though which should be essentially the same thing.

* That computer worked on another network: it's not the computer (firewall, anti-virus) blocking it. And Libation is confirmed to work on your computer.
* The app on your phone worked on your home network: it's not an IP block. Also Libation can download books and images.
* You deleted the account and re-added it. This deleted old cookies, keys, tokens, or serial number: they aren't the problem.

I have to admit: I can't think of what else it could be :(

**Comment by grranimals** [comment]
Apologies again for the delay. I changed each one and ran it separately as suggested.

Results of replacing some characters in "Token Value": Same problem as usual--reported timeout after some time.

Results of replacing some characters in "Private Key": new error thrown, see below
> A device attached to the system is not functioning.
> 
>    at Internal.NativeCrypto.CapiHelper.SignValue(SafeProvHandle hProv, SafeKeyHandle hKey, Int32 keyNumber, Int32 calgKey, Int32 calgHash, Byte[] hash)
>    at System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, Int32 calgHash)
>    at System.Security.Cryptography.RSACryptoServiceProvider.SignHash(Byte[] rgbHash, String str)
>    at AudibleApi.Cryptography.signSha256(String private_key, String dataString) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 92
>    at AudibleApi.Cryptography.CalculateSignature(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 74
>    at AudibleApi.Cryptography.SignRequest(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 45
>    at AudibleApi.Api.signRequestAsync(HttpRequestMessage request) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 75
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 68
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 62
>    at AudibleApi.Api.getLibraryAsync(String parameters) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 226
>    at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 206
>    at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 307
>    at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 131
>    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>    at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>    at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
>    at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
>    at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
>    at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

Results of replacing some characters in "ADPToken": new error thrown, see below
> Request could not be authenticated
> 
>    at AudibleApi.RestMessageValidator.ThrowStrongExceptionsIfInvalid(String message, Uri requestUri) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\RestMessageValidator.cs:line 27
>    at AudibleApi.ApiMessageHandler.ProcessResponse(HttpResponseMessage response, CancellationToken cancellationToken) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\ApiMessageHandler.cs:line 73
>    at System.Net.Http.MessageProcessingHandler.<>c.<SendAsync>b__5_0(Task`1 task, Object state)
> --- End of stack trace from previous location ---
>    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 70
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 62
>    at AudibleApi.Api.getLibraryAsync(String parameters) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 226
>    at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 206
>    at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 307
>    at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 131
>    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>    at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>    at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
>    at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
>    at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
>    at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

Results of replacing some characters in "RefreshToken": new error thrown... at first it asked me for my password again and had me do a couple captchas, then returned an error, seen below

> 
> Bad Data.
> 
>    at Internal.NativeCrypto.CapiHelper.ToKeyBlob(RSAParameters rsaParameters)
>    at System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(RSAParameters parameters)
>    at AudibleApi.Cryptography.CreateRsaProviderFromPrivateKey(String privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 122
>    at AudibleApi.Cryptography.signSha256(String private_key, String dataString) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 88
>    at AudibleApi.Cryptography.CalculateSignature(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 74
>    at AudibleApi.Cryptography.SignRequest(HttpRequestMessage request, DateTime dateTime, AdpToken adpToken, PrivateKey privateKey) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Cryptography.cs:line 45
>    at AudibleApi.Api.signRequestAsync(HttpRequestMessage request) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 75
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(HttpRequestMessage request, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 68
>    at AudibleApi.Api.AdHocAuthenticatedGetAsync(String requestUri, IHttpClientActions client) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api [partial].cs:line 62
>    at AudibleApi.Api.getLibraryAsync(String parameters) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 226
>    at AudibleApi.Api.GetLibraryAsync(LibraryOptions libraryOptions) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 206
>    at AudibleApi.Api.GetAllLibraryItemsAsync(ResponseGroupOptions responseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\AudibleApi\AudibleApi\Api.Library.cs:line 307
>    at AudibleUtilities.ApiExtended.getItemsAsync(ResponseGroupOptions responseGroups, Boolean importEpisodes) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\AudibleUtilities\ApiExtended.cs:line 131
>    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
>    at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
>    at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 159
>    at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, ResponseGroupOptions libraryResponseGroups) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 143
>    at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\ApplicationServices\LibraryCommands.cs:line 86
>    at LibationWinForms.Dialogs.IndexLibraryDialog.IndexLibraryDialog_Shown(Object sender, EventArgs e) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\LibationWinForms\Dialogs\IndexLibraryDialog.cs:line 34

Results of replacing some characters in "Cookies"-->"Key" "session-id" section: same old timeout error

Results of replacing some characters in "Cookies"-->"Key" "ubid-main" section: same old timeout error

Results of replacing some characters in "Cookies"-->"Key" "x-main" section: same old timeout error

Results of replacing some characters in "Cookies"-->"Key" "at-main" section: same old timeout error

Results of replacing some characters in "Cookies"-->"Key" "sess-at-main" section: same old timeout error

Results of replacing some characters in "StoreAuthenticationCookie" section: same old timeout error


Hopefully this is of some use to you. Let me know if you have any questions or if I missed something. I did download the newest version after running these test and it is also the same timeout error with that.

**Comment by rmcrackan** [comment]
Thanks! I added some better error handling in that new version (6.6.9), esp thinking about this issue. Can you attach the error log?

* Private Key: looks like we can't just change things here ad hoc. The request never left our side at all
* ADPToken: Same old error. I'd like to see the v6.6.9 error log on it though
* RefreshToken: Interesting. It got to amazon and they saw something was bad which is why they asked for your pw. This confirms again that they aren't just blocking you
* Cookies: Same old error. I'd like to see the v6.6.9 error log on it though

You could close Libation and delete the AccountSettings.json file . This would force you re-enter your login but I have no faith at this point that it would make any difference. I'm holding out hope that the better error logging yields something.

**Comment by grranimals** [comment]
I tried deleting the AccountSettings.json file and you're right--no dice.

I'm attaching the log with the ADPToken and all the Cookies rerun with the log set to "error." I tried to run them all back to back on the same log? Hopefully that worked out okay, let me know.

[Log202203.log](https://github.com/rmcrackan/Libation/files/8191866/Log202203.log)

**Comment by rmcrackan** [comment]
Yay, the new log is more illuminating. (Although the entries are strangely crammed together. That's a minor battle for another day though.) Like we did before:

* Find where Libation.exe lives
* backup/rename AudibleApi.dll
* Download this: [AudibleApi.zip](https://github.com/rmcrackan/Libation/files/8191892/AudibleApi.zip)
* Unzip it
* Move those 2 unzipped files into Libation's folder. It will overwrite AudibleApi.dll
* Try to scan again and let me know the result

These new files are for debugging only. They are not final files. Please back up the real one first.

**Comment by grranimals** [comment]
Well well well! I was able to import the library! I don't have an error log to attach since it didn't throw one at me this time. Let me know if you want me to run it again with any other logs.

**Comment by rmcrackan** [comment]
W00H00!! That was BRUTAL. You've been fantastic.

One last request: please stop Libation, delete your log file, restore AudibleApi.dll, run a new scan, and reply with that new error log. Then you can go back to using the new debug files until I create a real fix.

**Comment by grranimals** [comment]
Sure thing, here it is!
[Log202203.log](https://github.com/rmcrackan/Libation/files/8191960/Log202203.log)

I know, I could hardly believe it when it scanned successfully and I was so excited and happy! Thank you so much for sticking with me in trying to solve it, I appreciate it SO much. Please let me know if there's anything else you need.

**Comment by rmcrackan** [comment]
Please try this and let me know whether or not it works. Thank you again for all of your help: [v6.7.0](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by grranimals** [comment]
That's an affirmative! All is good in my Libation. :) Thank you!!!
