### ISSUE TITLE
File tag genre is "Audiobook" should be from Category

### ISSUE THREAD

**Issue by littleblackdog77** [rmcrackan/Libation#202]
Hi,

The tag for the genre field on the audio files is "Audiobook" when it should be whatever is in the category field in libation ie "Literature & Fiction" or "Science Fiction & Fantasy > Fantasy"

Any chance on changing this?

**Comment by rmcrackan** [comment]
@Mbucari: is it true that AAXClean just uses whatever metatags audible already uses?

**Comment by Mbucari** [comment]
My mistake, it only supports adding new tags and changing the cover art tag using AaxFile.AppleTags.  I can add setters for the AppleTags properties if you like. Which tags do you need to be able to edit?

**Comment by rmcrackan** [comment]
Looks like just genre for now. I don't want to get into every possible metadata field

**Comment by rmcrackan** [comment]
@Mbucari  Looks like just genre for now. I don't want to get into every possible metadata field

**Comment by rmcrackan** [comment]
@littleblackdog77 fyi -- I'm marking this as an "enhancement" instead of "bug" because Libation is correctly retaining the metadata that audible provides

**Comment by littleblackdog77** [comment]
> @littleblackdog77 fyi -- I'm marking this as an "enhancement" instead of "bug" because Libation is correctly retaining the metadata that audible provides

Thank you! There are some audiobook programs that automatically categorize books based on the genre field when the library is scanned (Audiobook Suite) for example, so it would be handy to have :)

Thanks again!

**Comment by littleblackdog77** [comment]
OK I'm not sure that I understand. Libation correctly displays the genre but then writes "Audiobook" in the genre metadata?
![lib](https://user-images.githubusercontent.com/26426154/158105771-00485421-b153-4956-a510-eca3a890c356.png)

**Comment by rmcrackan** [comment]
@littleblackdog77  Ah the joys of software. Audible has metadata (eg: genre) inside the book files themselves. This is what is displayed when you play a book, esp book title, author, narrator, and chapter titles. They also a separate source of data (well call that their API) for everything else. This is what you see anywhere else on their site or in the app. Audible doesn't want to have to read each file to, for example, show you all the books in your library -- so it uses that other data source. To make matters even more fun: in audible's own software, there's nothing stopping them from mixing these 2 and showing it to the user as though they were from the same place.

Libation uses AAXClean (made by @Mbucari ) to handle the file download and decrypt. Everything inside the file comes from there. During that process, he retains all of the file's metadata as is. When he has time, he'll add the ability for me to update the genre tag.

Libation uses that other data source (the API) for the grid, search engine, and the *naming* of files. From a programmer's point of view, what's inside the files is completely separate from the name and location of the file.

Hypothetically, if audible got really sloppy, audible could put different info in the API and inside the file. In that case the info in my grid might not match the file's metadata at all. Then I'd have a slew of what look like *my* bugs. The genre discrepancy that you found is a tiny specific case of this exact problem.

**Comment by Mbucari** [comment]
OK, I finally got around to doing this. All AppleTag properties are setable.  Just make sure you make all changes BEFORE converting or they won't be written to the output file.

**Comment by littleblackdog77** [comment]
Hi,

I grabbed the latest version. Made sure the fix tags checkbox was ticked.

I might be doing something wrong but it doesn't seem to work for me. I
grabbed a new book and it still comes out with genre = audiobook.

Cheers,
Michael.

**Comment by rmcrackan** [comment]
@littleblackdog77 yeah, that kind of thing happens when an idiot updates the code. I put the new fix in place without removing the old code. Which means that effectively nothing changed. Mea culpa. Try [this version](https://github.com/rmcrackan/Libation/releases/latest) and let me know if the problem persists.

**Comment by littleblackdog77** [comment]
Hey, yeah I've done similar before too. It works fine now. Many thanks for
adding this feature!
