### ISSUE TITLE
Books not displayed

### ISSUE THREAD

**Issue by kfbest** [rmcrackan/Libation#203]
Similar to https://github.com/rmcrackan/Libation/issues/198, except I haven't done any deleting and haven't gotten any errors. 

When I open Libation, doesn't show any books. Have upgraded to latest version, rescanned library, rebooted. Nothing displaying. But I can download new books (Liberate All) and it does update the count of remaining books to be downloaded down in the status bar.

**Comment by rmcrackan** [comment]
Sounds like something is going wrong with the filters and/or search engine

Filter:

Clear the filter box and hit enter. If your books come back then something was probably added in there wrong. You can edit filters under Quick Filters. It also has a checkbox to "Start Libation with 1st filter"

If that wasn't the problem, let's reset the search engine:

* Open the folder with the log file (Settings > "Open log folder" button)
* Close Libation
* Delete folder "SearchEngine"
* Restart Libation
* Do a new import > scan

Let me know if either of these fixes it.

**Comment by kfbest** [comment]
That worked! Thanks!

**Comment by rmcrackan** [comment]
Awesome! Thanks for the feedback.

Enjoy!
