### ISSUE TITLE
Crashes after downloading ~5 books

### ISSUE THREAD

**Issue by TsaraVandercross** [rmcrackan/Libation#205]
Trying to download my library of about 350 books.  Every 3-5 books, Libation crashes.

I have the setting set to skip a book if it errors and keep downloading.  I have the checkbox marked for "Keep Going".  I have downloaded the newest version downloaded.

Not sure what might be happening here.

**Comment by rmcrackan** [comment]
That's really not good. Can you attach the log file here? If you go into settings, there's a button which will open the folder containing the log file

**Comment by TsaraVandercross** [comment]
[_Log202203.log](https://github.com/rmcrackan/Libation/files/8182230/_Log202203.log)

Let me know if you need anything else!  I grabbed this log while it's running the next chunk.

**Comment by rmcrackan** [comment]
Thanks for the log. Weird. There's not a single error in here. When you say it "crashes", what specifically happens?

**Comment by TsaraVandercross** [comment]
Every window closes and the process manager no longer sees it running.

**Comment by rmcrackan** [comment]
Damn. Yup, that's a crash for sure. The previous log that you posted showed you 1 version behind. (v6.6.8 instead of v6.6.9). Does anything change if you use v6.6.9?

**Comment by rmcrackan** [comment]
Also, what version of windows are you running? Are you running low on any physical resources? eg: disk is almost full, ram or cpu is running close to max

**Comment by TsaraVandercross** [comment]
That is really odd about the log being 1 version behind.  I literally downloaded 6.6.9 before starting the downloads.

Windows 11.  Lots of disc space available.  (3 TB still free)

Everything seems to be ok, resource-wise.

The killer part is, now that I have started the ticket with you, it hasn't crashed again.  On book 12 or so.  I will let it run over night and if it crashes again, see if I can get you a new log file.

**Comment by rmcrackan** [comment]
RE version: that's odd. Did you unzip and run what's inside?

I'm glad you're issue seems to have gone away. (Well, I'm glad for you, I'm rather nervous about what a bug like that means for me.) I'm going to close this issue. If you have more crashes, reply here -- I'll see it and will re-open the issue.
