### ISSUE TITLE
Converting to .MP3 results in differing durations

### ISSUE THREAD

**Issue by DepressMode** [rmcrackan/Libation#206]
I was able to successfully import and download my library as .M4B files. I then converted the entire library to .MP3. When it was finished and I was checking it over, I noticed the durations of each converted book seemed to randomly differ from the source file. For example, one .M4B file was originally 18 hours, 13 minutes. After conversion, it was 19 hours, 6 minutes. That's a +4.5% gain in length. Another was originally 3 hours, 11 minutes, and came out 3 hours, 2 minutes (-4.7%). Another was 9 hours, 8 minutes and then 9 hours 51 minutes (+7.8%).

There was something that might be a clue as to the issue, though (or maybe a clue as to where _not_ to look); when I was converting my library to .MP3, I ran into an error on the very last book, but was able to get around the issue by redownloading the book individually with the "Download my books as .MP3 files" setting enabled. I noticed that when done this way, the resulting .MP3 was the exact same length as the original .M4B (and .AAX as well), so maybe there's something wrong with the long-running full library conversion process, but perhaps not in the individual aspect. The downloaded .M4B files are the same length as their .AAX originals to start with, so I don't think there's any issue there. 

I'd guess it's just a slight speeding or slowing of the original files, which isn't really a huge issue in single-digit amounts like this, but certainly not ideal. I have this slight paranoia that shorter .MP3s have been truncated in some way, though. I can paste in both file versions of a given book if that's helpful.

Windows 10
Libation v6.8.8

Thanks

**Comment by rmcrackan** [comment]
@DepressMode  Thanks for the heads up. I use another library for the mp3 conversions. I'll include the owner here in case he has time to look at it

@Mbucari It looks like there might be a slight discrepancy in final length when converting from m4b => mp3 in `AAXClean.Mp4File.ConvertToMp3`. Details in Libation issue https://github.com/rmcrackan/Libation/issues/206

**Comment by Mbucari** [comment]
I'll check this out sometime this week. It may not be an issue anymore now that I upgraded the AAC decoder.

**Comment by Mbucari** [comment]
OK, I tested this on _one_ book with the new AAXClean.Codecs, and the output mp3s are byte-for-byte identical.

Here's some code to run tests on other books.

```C#
static bool Mp3ConversionsSame(AaxFile aax)
{
  var m4b = new MemoryStream();
  aax.ConvertToMp4a(m4b);
  m4b = new MemoryStream(m4b.ToArray());
  
  var mp4a = new Mp4File(m4b);
  
  var mp3Direct = new MemoryStream();
  var mp3Indirect = new MemoryStream();
  
  aax.ConvertToMp3(mp3Direct);
  mp4a.ConvertToMp3(mp3Indirect);
  
  var mp3DirectBts = mp3Direct.ToArray();
  var mp3IndirectBts = mp3Indirect.ToArray();
  
  if (mp3DirectBts.Length != mp3IndirectBts.Length)
    return false;
  
  for (int i = 0; i< mp3DirectBts.Length; i++)
  {
    if (mp3DirectBts[i] != mp3IndirectBts[i])
    return false;
  }
  
  return true;
}
```

**Comment by rmcrackan** [comment]
@Mbucari Very nice. That's hardcore. I would have just done a hash. Much thanks!

**Comment by rmcrackan** [comment]
@Mbucari lol, no worries. Also, with hashing you couldn't surgically find where differences were. Even a stray \\0 in a metatag would blow up your hash. Hashing is only easy when you know for sure it's identical.

As for unit tests: if there were a tiny obscure aaxc file somewhere online, then your test could download it each time. Set those to only run locally so you don't run afoul of githubs actions. Maybe someone has already hosted one in github. You just need a sample somewhere with plausible deniability.
