### ISSUE TITLE
Unable to scan/import titles

### ISSUE THREAD

**Issue by imno007** [rmcrackan/Libation#208]
[_Log202203.log](https://github.com/rmcrackan/Libation/files/8210252/_Log202203.log)

**Comment by rmcrackan** [comment]
Thank you for the logs. That's a strange error. Let's try this:

* Settings > Accounts
* Click `X` to delete that account
* Click `Save`
* Settings > Accounts and re-add the account
* Try again to scan

If it still doesn't work, reply with your new log and we'll try something else.

**Comment by imno007** [comment]
Hello, thanks for the reply. I had done that a few times, as well as deleting the program multiple times and installing other versions, and deleting everything I could find in the registry. This only started happening after I installed the latest version today, so I thought at first that going back to the older version might fix things, but it did not.

BUT... for whatever reason, things seem like they might be okay right now. I just started it up again and was able to scan and import to an account. Time seems to have corrected whatever the issue was. So I'll keep my fingers crossed. If the problem resurfaces, I'll get back to you. Thank you again.

________________________________

**Comment by rmcrackan** [comment]
How strange. I'll close this issue. If you see this again you can reply here and I'll re-open it. Glad it's working for you.

In case you're interested for later: the only files Libation uses are the ones that are in the zip and the stuff in that folder where the log file lives. This is why there's no installer/uninstaller -- installing is just unzipping and uninstalling is deleting 2 folders. I believe in creating as little footprint on your computer as possible including not touching the registry. (Oh yeah, and I use a temp folder while downloads are in progress)

**Comment by imno007** [comment]
Right, I didn't actually mean I installed or uninstalled it, I was simply talking about deleting the previous files and replacing them. Just habit. And I use a registry manager that found a bunch of files, but truth be told, I didn't go through them to see where they were all located, I just deleted them all, so yeah, they probably weren't actually in the registry. 😉

Thanks again for the replies - and the program! It's especially helpful now that Audible has eliminated the high-quality bitrate downloads via browser and their own programs.
________________________________
