### ISSUE TITLE
Can liberate PDFs to Dropbox, but error on all audiobooks

### ISSUE THREAD

**Issue by EddisFargo** [rmcrackan/Libation#209]
[_Log202203.log](https://github.com/rmcrackan/Libation/files/8238266/_Log202203.log)

Hope I'm doing this right! I think most of the errors are the same thing over and over again as I clicked "Retry" a few times before giving up.

**Comment by rmcrackan** [comment]
Thanks for the log. It looks like a file is missing: AaxDecrypter.dll. Maybe it got deleted by accident. I'd recommend downloading the zip again.

Let me know whether this fixes your issue

**Comment by EddisFargo** [comment]
They're downloading now!!! Haha I wonder how that file got deleted. Oh well! Thanks so much!!

**Comment by rmcrackan** [comment]
Awesome, I love an easy fix :) Glad it's working
