### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by User2k10** [rmcrackan/Libation#21]
I am having the same problem. After getting the password, catcha and approval prompt successfully approving the login on my iphone, i get an error dialog that says "Error import library". I have tried 2 times, including after having restarted the application and get the same thing.

UK locale, 4.1.8 Libation downloaded today.

Log has the same 404 error as previously reported.

Thanks!

**Comment by rmcrackan** [comment]
Thanks for letting me know. I'm closing this issue so I don't have the progress spread out in several places. I'll address it in #20 . If you have any other info, please include it there.

**Comment by rmcrackan** [comment]
Correction: #16
