### ISSUE TITLE
Feature request: support accounts with over 10,000 titles

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#214]
Standard get-library maxes out at 10,000 paginated titles. Support over 10,000 titles by using continuation tokens, per @mkb79 's [notes](https://github.com/rmcrackan/Libation/issues/210#issuecomment-1073075865)

**Comment by Mbucari** [comment]
Shouldn't this be closed with 7.10?

**Comment by rmcrackan** [comment]
Yup. Good call
