### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by Luckyshot11** [rmcrackan/Libation#215]
[_Log202202.log](https://github.com/rmcrackan/Libation/files/8310480/_Log202202.log)
[_Log202203.log](https://github.com/rmcrackan/Libation/files/8310481/_Log202203.log)
This happens every time I start it up now, through three new versions.

**Comment by rmcrackan** [comment]
Thanks for the logs. It seems like these logs are from version v6.6.8. Can you upgrade to latest [v6.7.2](https://github.com/rmcrackan/Libation/releases/latest) and try again? It probably won't fix your issue but there's much better error logging in the more recent versions. My hope is the better logs will allow me to pin-point the issue.

**Comment by Luckyshot11** [comment]
It's given me the same issue with 6.6.8, 6.7.0 and 6.7.2, but I understand
the logging issue, so I will run it again tonight (working all weekend) and
post the updated logs. Thanks!

**Comment by rmcrackan** [comment]
I apologize for the headache. Thanks for being willing to re-run them for me. I don't expect the error to change; there's something very real going wrong here. I think the recent improvements to logging will help find the problem.

**Comment by Luckyshot11** [comment]
[Log202203.log](https://github.com/rmcrackan/Libation/files/8314936/Log202203.log)
[Log202203_001.log](https://github.com/rmcrackan/Libation/files/8314937/Log202203_001.log)
[Log202203_002.log](https://github.com/rmcrackan/Libation/files/8314938/Log202203_002.log)

**Comment by rmcrackan** [comment]
It looks like these are all titles which are no longer associated with your audible account. For the The Making of a Massacre podcast, did you unfollow it? Or do you no longer have an active membership? For the other books (Star Runner, Revenger, King of Ashes...), were they returned?

If you no longer own these books and want them removed from Libation, the easiest way to get rid of them is Import > Remove Library Books. This will get your latest book list from audible and compare it to what Libation knows. Books that are no longer in your audible library will be at the top of the list and will be checked. You can click the button to remove clicked items.

**Comment by rmcrackan** [comment]
My guess is that there are specific titles (like the ones mentioned above) which are no longer in the account. When they fail, they're keeping your good titles from processing correctly. I recommend these steps:

* do the 'remove library books' that I mentioned previously
* go to settings > Download/Decrypt tab. In the upper right "When liberating books...", select "Permanently ignore book". This should allow you to get through all of your titles
* Liberate as normal

Let me know if this does not work

**Comment by wtanksleyjr** [comment]
You might want to take notes on which specific books are marked, and
hand-check whether they are still in your Audible library. I've heard
stories of paid-for books vanishing from people's libraries by Audible's
mistakes, and people can complain about it and get a credit. (OTOH there
are other possible reasons too, so be careful.)
