### ISSUE TITLE
Feature request: Ability to select a few audiobooks to queue up to download, rather than just one or all

### ISSUE THREAD

**Issue by chippy** [rmcrackan/Libation#217]
As far as I can tell, you currently have the option to download books one at a time, or to download all of them in one hit. It would be nice to be able to select a few, and then leave those running in a queue.

**Comment by rmcrackan** [comment]
Good idea. This request looks close enough to #148 that I'm going to close this issue and track requests there.

**Comment by chippy** [comment]
> 

Ah, didn't spot that one! Thanks.
