### ISSUE TITLE
Libation failed to move Audiobook

### ISSUE THREAD

**Issue by HedaConHeda** [rmcrackan/Libation#218]
I have an issue where the decrypted audibook doesn't get moved the to destination, resulting in an error.

I am using the following naming format in Libation.
Folder: `<first author><if series->\<series><-if series>\<if series-><series#> - <-if series><title short>`
File: `<title short>`

The resulted Folder structure gets created: `Random Author\Play & Time\1 - It Begins`
The filename of the decrypted audiobook in the temp folder: `It Begins....m4b`

I am pretty sure the issue is that Libation tries to name the folder `1 - It Begins...` as well, but this isn't allowed in Windows thus the dots get stripped. When Libation tries to move the file to the folder it's looking for `1 - It Begins...` which indeed doesn't exist resulting in an error.

**Comment by rmcrackan** [comment]
Wow, it's been so long since someone has found a legit bug and not just a login issue that I genuinely thought I'd misread this at first. Thanks!!

I don't have any titles to test this with. I put my best guess at a fix into [v6.7.3](https://github.com/rmcrackan/Libation/releases/latest). Let me know whether this fixes it for you.

**Comment by HedaConHeda** [comment]
Okay downloaded v6.7.3 and it did move the file to the folder this time.

Thanks for the quick response and fix!

**Comment by CharlieRussel** [comment]
> Wow, it's been so long since someone has found a legit bug and not just a login issue that I genuinely thought I'd misread this at first. Thanks!!
> 
> I don't have any titles to test this with. I put my best guess at a fix into [v6.7.3](https://github.com/rmcrackan/Libation/releases/latest). Let me know whether this fixes it for you.

And after you put in the URL login workaround, I haven't had any issues with logins at all. Even after I messed up my installation on one machine and had to start over. (Regedit can be a lifesaver, but it can also get one in trouble! Sigh.) Thanks, again, for this great program.

**Comment by rmcrackan** [comment]
@CharlieRussel You're welcome :)
