### ISSUE TITLE
App Crash

### ISSUE THREAD

**Issue by Amedhas** [rmcrackan/Libation#221]
Hi, 

I may have misclicked somewhere on the application and the screen as I am very new to it and resulted in crashing the whole application on my system.

Please assist. I am attaching the Error log as suggested by the app.
[Log202204.log](https://github.com/rmcrackan/Libation/files/8417361/Log202204.log)

**Comment by rmcrackan** [comment]
Ouch. It appears you ran out of disk space. Fortunately, after books are downloaded, you can move them wherever you want and Libation will remember which have already been downloaded.
