### ISSUE TITLE
Library "looks" empty

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#228]
Libation shows no library entries (lower left has "Visible: 0", but my library is somehow still there (right side shows: BACKUPS: No progress: 1405 In process: 0 Fully backed up: 1814". If I try to do a library import, it gets an error. But if I kick off a "Being Book and PDF backup", it'll continue downloading my library. But I just can't see any entries in the interface. I don't want to re-download my library again, which this is actually my second attempt since somehow Libation previously lost the library after an upgrade.
[Log202204.log](https://github.com/rmcrackan/Libation/files/8461135/Log202204.log)
.

**Comment by rmcrackan** [comment]
Does it help if you do another scan?

**Comment by rmcrackan** [comment]
Thanks again for the logs.

In the same folder as your log file is `BookTags.json`. I think it got corrupted somehow. Try: stop Libation, delete `BookTags.json`, restart Libation, scan. That should fix it.

I'll add code today to look for this issue.

**Comment by rmcrackan** [comment]
Fixed in [v6.7.6](https://github.com/rmcrackan/Libation/releases/latest)

If this is still a problem, comment here; I'll see your post then I'll re-open the issue. When I mention an issue number in my bug fixes, github "helpfully" automatically closes the issue.

**Comment by badbob001** [comment]
That was it! Thanks. Could the issue be due to my upgrade method? I had been upgrading Libation by copying the new files over the old ones (with it not running of course) and afterwards, it would always prompt me to point it to my config location, which I have set to be a subfolder of the libation app folder. But mostly it got corrupted due to the app crashing or my system crashing.

**Comment by rmcrackan** [comment]
That shouldn't be a problem. Who knows why corrupt files happen.

By the way, if you use the new files but use your old `appsettings.json` file, it will find your settings and database automatically. Sorry my upgrade is garbage. It's on the long list of things to fix one day.
