### ISSUE TITLE
Feature Request: Actions on Filtered Titles

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#229]
It would be really helpful to be able to perform a set of actions (such as removing very old, free episodes of Car Talk that will never be listened to ever again) based on the results of a Filter. When you're dealing with several thousand books across 4 different Audible accounts in 3 different countries, it's more than a little painful to have to click one at a time. But I can filter down to just the ones I want to act on, but that filter doesn't hold when I want to, for example, remove the episodes.

**Comment by rmcrackan** [comment]
For feature reference: similar to #148 . Different though since that enhancement is for the main grid and this enhancement is for the delete-books grid.

**Comment by CharlieRussel** [comment]
Perhaps enabling filtering to affect any grid?  Or tie all actions back to one grid (the main grid), rather than having a separate delete grid.

And while I’m at it, how well does that filer option handle regex?

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by rmcrackan** [comment]
> And while I’m at it, how well does that filer option handle regex?

It doesn't. It uses the [Lucene query syntax](https://www.lucenetutorial.com/lucene-query-syntax.html) -- [another reference](https://lucene.apache.org/core/2_9_4/queryparsersyntax.html). Additionally I implemented tags which you can search like `[this]` and also the special search words that you see when you press the `?` button.

For example, part of my default filter is `-[hidden] -episode -IsRated -[kids]`. It hides books tagged as hidden, episodes, books I've rated, and books I've tagged as just for my kids. There are also *logical* operators. `(-[hidden] -episode -IsRated -[kids]) OR [maybe]` will filter as previous but will also include books with maybe tag, even if it's a kids book.

**Comment by CharlieRussel** [comment]
Ah. Yet Another Query Syntax. ;)

OK, explains why things didn’t behave as I’d hoped. But I can deal.

**Comment by rmcrackan** [comment]
> Yet Another Query Syntax

Yeah. I didn't choose the syntax per se. I chose the easy to integrate full search engine which comes with a syntax which supports ranges, quotes, and full complex logic with parentheses, and/or/not, wildcards, and even proximity. The language is itself clunky but it's powerful out of the box and really performant at any scale.

**Comment by rmcrackan** [comment]
Available in [v7.5](https://github.com/rmcrackan/Libation/releases/latest). This is available in the main grid, not delete grid. Look in the new menu for 'visible books'
