### ISSUE TITLE
Problem with Podcast & Other "issue"

### ISSUE THREAD

**Issue by Tb3986** [rmcrackan/Libation#230]
Hello,
**First Problem**
Importing a podcast, libation will download all episodes on different folder
Here the podcast: 10 episodes
https://www.audible.it/pd/Podcast-micidiali-Podcast/B09MFZ6TB3?qid=1649832133&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=67f8f22b-aed1-45a6-a456-d09beff03315&pf_rd_r=07EJGYWF7NAE12R03W06

Here after download:
https://i.postimg.cc/QMbS1DfN/Untitled.png

Is that possible to download in the same folder all episodes? Otherwise i have to copy and paste and would be pretty boring.

**Second Problem:**
Transcoding m4b to mp3, bitrate is not the same. With movavi video converter or pazera i get 128 kb/s as a source, with libation around 70 and converting required a lot of time. Using the original one, conversion would be pretty fast and not slow

**Tips**
Auto download? :D Please add a button to download automatically all new audible and not clicking one by one.

Thank you

**Comment by rmcrackan** [comment]
Thanks for reaching out:

> First Problem ... all episodes on different folder

You can customize how files are saved here:

* Settings
* Download/Decrypt tab
* "How to format the folders in which files will be saved"
* Edit

`<series>` might help

> Second Problem ... bitrate is not the same

Libation's main feature is removing the DRM; the mp3 transcoder is just a convenience. For more control over it, I recommend finding a more specialized solution. I'll let the author of this feature know though.

@Mbucari -- fyi: a user has found that AAXClean's m4b to mp3 encoder is not retaining the same bitrate

> Auto download?

These files can be big and numerous. I think downloading without user intervention is a recipe for disaster.

> Please add a button to download automatically all new audible and not clicking one by one.

Oh heavens, I'm so sorry. You don't have to click them one by one. Go to Liberate, Begin Backups. This will go through your entire library 1 book at a time and download each one that hasn't already been downloaded.

**Comment by Mbucari** [comment]
re bitrate, aaxclean uses the following lame config:

If stero, downsample to mono.  All aax books I've tested just duplicate left-right channels, so stereo is redundant.
Encode with average bitrate = aax's average bitrate.  If donwsampling to mono, divide by 2.

**Comment by rmcrackan** [comment]
@Mbucari I like this in general. Great way to save space. However Audible has started releasing some titles as [3D audio](https://www.audible.com/ep/3d-audio) which is, as far as I can tell, their BS marketing term for stereo.

**Comment by Mbucari** [comment]
In that case, you can use the ConvertToMp3 overload that accepts a NAudio.Lame.LameConfig object.

**Comment by wtanksleyjr** [comment]
Does the 3D audio appear in their aax files, or only in aaxc, though?

**Comment by rmcrackan** [comment]
@wtanksleyjr They're all really new so I'd assume aaxc. I haven't verified though.

**Comment by Mbucari** [comment]
Here's what I use as default:
```C#
double channelDown = mp4File.AudioChannels == 1 ? 1 : 0.5;
var lameConfig = new NAudio.Lame.LameConfig
{
  ABRRateKbps = (int)(mp4File.AverageBitrate * channelDown / 1024),
  Mode = NAudio.Lame.MPEGMode.Mono,
  VBR = NAudio.Lame.VBRMode.ABR,
};
```
If you want stereo, then do something like:

```C#
var lameConfig = new NAudio.Lame.LameConfig
{
  ABRRateKbps = (int)(mp4File.AverageBitrate / 1024),
  VBR = NAudio.Lame.VBRMode.ABR,
};
```
If you don't specify mode it uses the input's mode.

**Comment by Mbucari** [comment]
FYI, stereo encoding is MUCH slower than mono.  If you want to allow stereo encoding I suggest you make it optional.

**Comment by rmcrackan** [comment]
@Mbucari that's solid advice, thank you. I think for now I'm going to leave it as is.
