### ISSUE TITLE
How does Libation respond to duplicates? 

### ISSUE THREAD

**Issue by Zachman1** [rmcrackan/Libation#232]
Would libation overwrite a currently existing book if you had it in your library twice? 

A book could be a duplicate from owning it in 2 seperate marketplaces, or from audible taking it down for sale and putting it up again and a user buying both.

**Comment by rmcrackan** [comment]
Each audible title has a unique id. You can see this 8-10 character id in the url. Eg: https://www.audible.com/pd/Project-Hail-Mary-Audiobook/B08G9PRS1 -- the id for Project Hail Mary in the US marketplace is B08G9PRS1. When the scanner finds this id and it's not in Libation's database, it gets added. If you have 2 accounts with the same book, it's added the first time and ignored on 2nd encounter. If the same book has different ids in the US and UK marketplaces and you have them both, then both will be added to your database. It's all about that id.
