### ISSUE TITLE
Folder support for Audiobookshelf 

### ISSUE THREAD

**Issue by Zachman1** [rmcrackan/Libation#236]
I am trying to integrate audiobookshelf into my audiobook flow and am trying to figure out the best process to import books from libation to audiobookshelf. 

https://www.audiobookshelf.org/docs

Does Libation support the directory structure as described in the above link? I took a look in the download/decrypt tag section but it appears that it currently only supports a single level of folders. If not, would it be possible to add support for a file structure like this?

Thanks for the help.

**Comment by CharlieRussel** [comment]
No, you can have multiple levels. So, for example, I have: <first author>\<if series-><series>\<-if series>\<if series->#<series#>-<-if series><title short>. This yields: 

D:\AudibleBooks\Ben Aaronovitch\Rivers of London Series\#9-Amongst Our Weapons

Where D:\AudibleBooks is my base folder, Ben Aaronovitch is the author the the Rivers of London series, and Amongst Our Weapons is the 9th book in the series.

**Comment by rmcrackan** [comment]
Sorry it's a little clunky. The FOLDER template allows levels and subfolders. Just use `\`. The FILE template does not.

**Comment by Zachman1** [comment]
That's great! Thanks.

Is there a way to get it to force rename to a new naming convention I select, previously downloaded and named titles?

**Comment by CharlieRussel** [comment]
No, short of deleting the book and re-scanning. :(

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by rmcrackan** [comment]
We can turn this issue into a feature request for that, but honestly this will be way easier: go into you Log folder. Delete your database `LibationContext.db`. Re-scan. Re-download.

The database only has 2 things in it (all other info is stored in other files): info downloaded from audible, and which files have been downloaded. Deleting the database is effectively resetting all files to 'not downloaded'.

**Comment by Zachman1** [comment]
Thanks that is what I did. Itll definetely take a bit though. 

It wouldnt be a bad feature to have, but I have no idea how much work would go into it so I think this will suffice for now.

**Comment by rmcrackan** [comment]
@Zachman1 stuff like this takes so much longer than you might imagine. I know it sounds stupid, but the base feature takes less than 20% of the time. The rest is testing, UI, and far too many "what if". If I even had a 2nd person working with me, this would be a different matter. For now, making this production-ready for a few people means time I'm not spending on something else that's for (hopefully) more users.

Hopefully, you can run the new backups over-night and it'll do what you need.
