### ISSUE TITLE
Unable to log in with username Audible account

### ISSUE THREAD

**Issue by Jimmni** [rmcrackan/Libation#237]
I made my US Audible account way back in the early 2000s, when Audible was US-only, and it is one that logs in using a username, not an email. Attempting to log in using the standard username/password option yields a loop of captchas until it gives up. Clicking the option to log in via a web browser worked fine for my UK account, but my US account isn't linked to any Amazon account, so I can't just log in using my Amazon account. I made it before Amazon owned Audible, and my only Amazon account was automatically converted from a US account to a UK one many many years ago.

Is there any way for my use use Libation with this old non-Amazon linked account? Thanks!

**Comment by Jimmni** [comment]
I ended up making a US Amazon account and beginning the merging process. It had me sign in with both my Audible and Amazon account, and then when it asked me to enter my credit card details to confirm the merge I just... didn't (there are only so many times Amazon need my card details...). I then tried the Amazon link provided by Libation again and was able to log in successfully.

**Comment by rmcrackan** [comment]
The region dropdown has options for 'pre-audible'. Let me know if those work for you.

**Comment by Jimmni** [comment]
Ah, I didn't spot that! I ended up making a US Amazon account and merging them. Annoyed at myself now for not looking more carefully!
