### ISSUE TITLE
CUE file format seems incorrect (for VLC, anyway)

### ISSUE THREAD

**Issue by thepuss** [rmcrackan/Libation#24]
Probably shows how many people do NOT use these any more!

I believe the first line (FILE) is incorrectly formed. 
Example:
My audio file is generated as:          A Bespoke Murder [B00CJD98K4].m4b
My CUE file is generated as:            A Bespoke Murder [B00CJD98K4][m4b].cue
My NFO file is generated as:           A Bespoke Murder [B00CJD98K4][m4b].nfo

(I have no issue with the NFO file here)

In the CUE file as generated, Line #1:   FILE "[B00CJD98K4].m4b" MP4
1> "MP4" is not a valid CUE "FILE" option.
2> Filename does not match filename as generated

So...  as generated:                          FILE "[B00CJD98K4].m4b" MP4
What I changed to get it to work:   FILE "A Bespoke Murder [B00CJD98K4].m4b" MP3

Also I think the CUE file may need to have the same filename as the Audio file:
Audio file named as produced:  A Bespoke Murder [B00CJD98K4].m4b
Cue file named as produced:     A Bespoke Murder [B00CJD98K4][m4b].cue

I renamed the CUE file to:          A Bespoke Murder [B00CJD98K4].cue

Then it all worked beautifully. A great product that basically does what I'm looking for.
Many thanks!

I am using Libation: v4.2.3 downloaded on 10th April 2021
                  VLC: v3.0.12 Vetinari

**Comment by rmcrackan** [comment]
Thanks for that info. In the [latest release](https://github.com/rmcrackan/Libation/releases/tag/v4.2.4) I changed it to MP3 and made sure the internal filename matches the audio file. I didn't change the cue's filename though. Let's see if this works

Thank you again

**Comment by thepuss** [comment]
Many thanks! It does seem to work now...
Unfortunately, VLC has a bug in its handling of CUE file data, so it
doesn't display index times and titles correctly, but the playlist,
chapters are now at least playable from the CUE file.

(VLC Error: https://code.videolan.org/videolan/vlc/-/issues/14134 )

**Comment by rmcrackan** [comment]
Glad it's at least better now. Much thanks for the kind donation!
