### ISSUE TITLE
Feature: allow selecting "Liberate" while an background sync is in progress

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#241]
It would be nice to be able to open the program, start a liberation, and walk away. In support of that, would it be possible to have the Liberate action queue a liberation to begin after the active sync?

Of course this is already possible from the command line, and is how I do that now.

**Comment by rmcrackan** [comment]
Doing a scan followed immediately by downloading/decrypt is logistically simple. The UI is the question. Do you imagine another menu item? A new setting? I don't want to clutter it with more and more options. Likewise, when you add more menu items, the terse names can be confusing and run the risk of people picking the wrong one. Or simply mis-clicking on something that didn't used to be there. Ideas?

Once we figure this out, you won't need to start a scan if you don't want to. Just enable the new autoscan and all you'll have to do is launch the app and walk away.

**Comment by wtanksleyjr** [comment]
Let me dump some UI ideas.

First: what if the scan itself was a line-item in the new to-be-processed list, and included a checkbox on it that would enable "automatically liberate newly discovered books"? Naturally would also need a settings to pick what the default is, some people want to liberate everything and some don't.

Second: what if we got rid of all the separate menus ("Scan", "Liberate", "Export"), and just used a single "Go" button that popped up a dialogue including that kind of choices (whether to scan first, which accounts, whether to liberate every found item, where to put exported data, etc).

**Comment by rmcrackan** [comment]
Added to v7.9. I got lazy and just made yet another setting: 'Auto download episodes after scanning' setting is on the 'Import Library' tab
