### ISSUE TITLE
Downloaded Zip and Exported, but the exe file is not located anywhere? 

### ISSUE THREAD

**Issue by JuanTaco666** [rmcrackan/Libation#246]
Hello,
This software seems like exactly what I'm looking for but I cant seem to find the .exe file to get the installation process started? Am I just being stupid or is there something else wrong.

**Comment by JuanTaco666** [comment]
Turns out I am dumb, wrong download lol

**Comment by rmcrackan** [comment]
Lol, no worries. I'm glad you found it :)
