### ISSUE TITLE
Documentation On How To Update

### ISSUE THREAD

**Issue by freddyyeddy** [rmcrackan/Libation#25]
Right now it seems i have to start from scratch for each new version. Which at this point is getting tiring. Thank you for the assistance.

**Comment by rmcrackan** [comment]
I apologize for my crap documentation. At the very, very end of Libation's [main page](https://github.com/rmcrackan/Libation#advanced) it (poorly) mentions the setting you want.

* Settings > Basic Settings : The top box is the location where your books live. You can point it anywhere you want. Alternatively if you already downloaded them, you can go to your previous folder and drag+drop them to the current "books" folder. Libation will automatically recognize them in the new location.
* Settings > Advanced Settings : this one can be confusing but it makes my life a lot easier. I really enjoy having certain things in certain places on my computer -- imagine that, a nit-picky programmer. My audible audiobook files are in 'C:\Dropbox\whatever\audiobooks\audible' and Libation configuration files are in 'C:\Dropbox\whatever\settings\MyLibationFiles' . Inside Libation. I go to Settings > Advanced Settings and aim the Libation Files location to 'C:\Dropbox\whatever\audiobooks\MyLibationFiles' and I'm immediately up and running again

Advanced settings says: this is where my real settings are location  
Basic settings says: here is where to look for my liberated books, and a few misc configuration options

So when you get a new version of Libation, your 1 step is to point to your advanced Libation File location and everything will work again. It'll remember your old settings, library, logged in accounts, tags ... everything

Sorry for any frustration up to this point. Please let me know if you have any specific suggestions on making Libation more intuitive and/or making the documentation better.

Thanks for reaching out
