### ISSUE TITLE
Download Stuck

### ISSUE THREAD

**Issue by Tb3986** [rmcrackan/Libation#251]
Hello,
i would like to report a bug very annoying. Download is stuck and don't won't to move all files from temp folder to the final one.

![Untitled](https://user-images.githubusercontent.com/45364981/169017405-0fed09f4-d0c2-4dab-aa16-599353741299.png)

With the new update, 3 downloads, 3 stucks.

Here the log

https://we.tl/t-H5OKsApPez

Regards

EDIT:
Tried to use another temp folder and final folder, same issue.

**Comment by rmcrackan** [comment]
@Tb3986 Be happy to look into this. That site isn't letting me download your log file. Can you attach it here on github directly? You can drag/drop it into the text box.

@Mbucari Ya know those lack of bug reports we were talking about... :worried:

**Comment by Tb3986** [comment]
[Log202205_001.log](https://github.com/rmcrackan/Libation/files/8716152/Log202205_001.log)

Done

**Comment by Tb3986** [comment]
> @Tb3986 Can you please change your logging level to "Verbose", retry the same book, and post those logs?

[Log202205.log](https://github.com/rmcrackan/Libation/files/8718110/Log202205.log)

**Comment by Mbucari** [comment]
Fixed in #252

**Comment by rmcrackan** [comment]
Fixed in latest version [v7.6.2](https://github.com/rmcrackan/Libation/releases/latest)
