### ISSUE TITLE
can't make the in-place upgrade actually run

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#259]
I can't make the in-place upgrade actually run, apart from downloading the file and putting it who-knows-where.

The in-place upgrade asks me if I want to download the upgrade, then tells me it'll do the upgrade next time I restart. So I let the download finish, the progress bar on the download vanishes, and I quit Libation and start it up again -- and all it does is repeat the same "do you want to download the upgrade" again.

Is there something I'm supposed to do aside from just closing Libation to make the upgrade happen? Any chance the upgrade download might check to see whether there's something already downloaded and just use it, instead of repeating the whole download?

**Comment by rmcrackan** [comment]
These steps worked for me. Where do ours differ? I can add clarity inside the program

* I downloaded an old version from github -- v7.8.1
* Unzip
* Run Libation.exe
* go through the 'returning user' setup
* Libation started and the 'update available' box pops up
* Verify version in Libation \> Settings \> About. Running Libation version 7.8.1.2
* Back to the update available box: Would you like to update: click Yes
* Progress bar then "waiting for application to exit"
* X out of the main Libation UI (not the "waiting for application to exit" box)
* installing update progress bar
* Libation restarts. Settings \> About v7.9.0.2
* No update available box this time

**Comment by wtanksleyjr** [comment]
OK, one big difference: no "waiting for application to exit" box. As soon
as the downloading app progress bar fills, that window just vanishes, I
didn't even guess it wasn't supposed to.

Are there logs for it I should get to you?

-Wm

**Comment by rmcrackan** [comment]
No logs since I'm using a 3rd party tool for this. After the window vanishes, could the 'waiting for exit' box be behind the main program?

**Comment by wtanksleyjr** [comment]
I just MIGHT have figured it out.

What happens is that the installer has to get admin permissions (which my
account has), but sometimes for some reason Windows backgrounds the request
for that.

This time as soon as the download finished my screen switched correctly to
asking for admin perms, so it worked fine. My guess is that when I tried
before Windows just hid the permissions request ... not sure why. Maybe it
has a timeout, in which case I'll try to make it happen again so we can
know for sure.

For now, I'd say this is resolved. I'll make a new bug, or reopen this one,
next time I do an upgrade.

-Wm

**Comment by rmcrackan** [comment]
Cool. Glad it's not a total mystery anymore. Good luck
