### ISSUE TITLE
Chapter titles not included in M4B

### ISSUE THREAD

**Issue by oswallt** [rmcrackan/Libation#261]
The chapters are just listed as Chapter 1, Chapter 2, etc.  I've tried previous versions and it's not working there either, so I don't believe it's related to [this issue.](https://github.com/rmcrackan/Libation/issues/234)

**Comment by oswallt** [comment]
It looks like a jumped the gun.  I downloaded 3 different books that all have chapter titles in the kindle version, but I've downloaded them in the audible app now and they all show chapter numbers without titles.  It was just a coincidence that I got  3 different books like that in a row.  My apologies.

**Comment by rmcrackan** [comment]
No worries. Glad it's working again.
