### ISSUE TITLE
263 post mortem

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#265]
Let's discuss this after #263 is fully resolved

1) what's the right solution?
2) are there implications of rolling that back the SERIES_ hack? Esp how it will affect this user in particular?
3) what went wrong?
3A) I think the short version is: audible changed something weird and unpredictable. The nature of reverse engineering is being reactionary. What could we do differently? probably nothing
3B) exceptions weren't handled correctly. I'll address the exceptions part soon
3C) a user was left in a bad state. Is there a way to help a user out of a bad state? does Libation need to deploy with a helper app? Like: something where we say: open LibationOhShit.exe and paste in `rollback to v7.0` or `update Books set brain=false where foo=bar`

**Comment by Mbucari** [comment]
1. I want to add Parents to the library. I do not want to alter their Asins.  I think ContentType should have a new enum field: ContentType.SeriesParent, and only Items with RelationshipToProduct.Parent should be assigned that enum value. 
This leaves the problem of the special case where a parent is also its own child. I'd be inclined to add the item twice, once as ContentType.SeriesParent and once as ContentType.Episode, but the DB implementation prevents duplicate ASINS. Is that an insurmountable problem? I remember a while back you said ASINs are not PKs, so maybe we can have dups.

2. I tested this bu removing the "SERIES_" prepend, and the effect is that those items remain in the db but don't affect anything. There is a duplication problem which I hadn't notice before (doh!) that happens if the db was upserted once with [ASIN] and once with SERIES_[ASIN]. That can be fixed with Remove Books Dialog. But nothing breaks.

3. The problem was 3-fold.

First, Audible has a poor system for indexing podcasts.  For most podcasts, there is a parent ASIN which is retrieved from the library api endpoint, and children ASINs that are retrieved from the catalog api endpoint.  What they SHOULD have done for podcasts with only 1 episode is to make 2 separate ASINs: 1 for the series and 1 for the episode.  What they ACTUALLY did was make 1 ASIN for that episode, and no ASIN for a containing series.

Second, whem the importer found an episode type that had no children, it just added the book to the library with no Series information.  This was a bad idea because, even though it wasn't linked to any other ASINs, it is a series **type** that should have a series identifier.

Third, when I made the new ProductsGrid I relied on a (now proven wrong) assumption that any ContentType.Episode book would have at least 1 SeriesBook.  That didn't happen because of the choice made in "Second" above.

**Comment by Mbucari** [comment]
Re No.1

To do hierarchical episodes correctly, Book needs to have more information about episodes than just ContentType.Episode.  Something like Item has with RelationshipToProduct "child" or "parent"

Maybe something like:

```C#
[Flags]
enum EpisideHierarchy
{
	Parent,
	Child
}

class Book
{
	public EpisideHierarchy? EpisideHierarchy {get;}
}

```
For non-episode products:
```C#
Book.EpisideHierarchy = null;
```
For episode parents:
```C#
Book.EpisideHierarchy = EpisideHierarchy.Parent;
```

For episode children:
```C#
Book.EpisideHierarchy = EpisideHierarchy.Child;
```

For cases an episode has no parent (or is it's own parent, depending on how you look at it):

```C#
Book.EpisideHierarchy = EpisideHierarchy.Parent | EpisideHierarchy.Child;
```

**Comment by rmcrackan** [comment]
1) Parents aren't books. What's the advantage of adding them to that table?

lol, I wrote out the following before I read your 2nd post (great minds think alike). I'm leaving it here because if I pulled the binary comment out of context it would make no sense:

> Assuming we want to though, for parent that is its own child: this sounds like 1 db entry with `ContentType = ContentType.Parent | ContentType.Child` and we change ContentType to a flag type enum. By pure luck, we're only using binary friendly numbers so far (0, 1, 2) so we can do this with no data migration needed. Since flags aren't typical, maybe change ContentType to internal and expose it through properties like `public ContentType IsChild => this.ContentType & ContentType.Child == ContentType.Child` etc. which hide the implementation details.

2) sounds like you've got that under control

3)

A. Good breakdown. This is just the annoyance of reverse engineering; not our fault

B. The app crashing without log info was bad. I addressed global error handing [here](https://github.com/rmcrackan/Libation/commit/114925ebcedd175a992217b94080740de2d6cc63). Errors in events and async code will get logged, UI displayed, and not crash the app. Errors in threads will get logged, UI displayed, and will crash the app. I feel stupid for not having implemented global error handling literally years ago.

C.

> You can't un-migrate the db

Sure you can. That's why migrations have and [up and down](https://github.com/rmcrackan/Libation/blob/master/Source/DataLayer/Migrations/20220510175257_AddPictureIDLargeMigration.cs#L18). That was just an example though. Sorry, I was too specific. I was really exploring the idea of creating an app to deploy along side Libation that could help us with debugging. Like if we needed them to run a sql query. Imagine telling that user last night: run `delete from Books where asin like 'SERIES_%'` or delete your database, do a new import and `update Books set liberated = 'downloaded'; update books set pdfliberated = 'downloaded' where pdfliberated is null` and the tool could do an automatic backup before they ran their queries. Or it could run the LibationCli ... which I guess they already can by virtue of Window's cmd ... This might not actually be useful compared to the effort required, that's why I wanted to get your take on it.

**Comment by Mbucari** [comment]
1. Parents aren't books, but they contain info about the series as a whole that isn't available from any single episode.  Of particular interest to me is the cover art, series description, and ratings.  With the addition of series grouping, this info is now useful to populate the SeriesEntry in the ProductsGrid.

2. Yeah, I like it. And very lucky on the existing enum values

3. If you roll back to a version of Libation pre-migration, it won't have later migration code in it so it'll just crash. But I really like the idea of cli queries.  That could be really useful in general for fixing databases and assist in debugging user's issues. 

4. I'm leaving town this evening and won't return until next weekend, so I won't be working on any of this in the meantime.  But if something else breaks, please feel free to email me if you have any questions.  I will probably not be checking in with github notifications, though.

**Comment by Mbucari** [comment]
Actually we don't even need to give ContentType a Flags attribute (which is good for safety).

```C#
enum ContentType
{
  None,
  Product,
  Episode,
  Parent = 4,
  ParentEpisode = 6
}

Book.ContentType = ContentType.Parent | ContentType.Episode;

Console.WriteLine($"Content type is {Book.ContentType}");

//Content type is ParentEpisode
```

**Comment by rmcrackan** [comment]
> I'm leaving town

Thanks for the heads up. This is just brainstorming that can resume whenever.

> ContentType

A few things I don't understand. This is flags without the attribute. Are you saying not using that attrib is safer? RE Episode vs Child: right now they're one and the same. What's the distinction? Regardless of the specifics, once we overload this field, we'll want to hide the impl. details and give more obvious public properties.

**Comment by Mbucari** [comment]
I've put together a solution on my end, but I'm having trouble with EF. If I make the ContentType property private and add the Column attribute, the column is added to the DB but the value isn't stored. I found [this answer about storing non-public properties](https://stackoverflow.com/a/21686896/3335599), but that it looks like a lot more messing around than I feel comfortable doing. Can you do the work required to store private properties, or do you just want to keep it public?

**Comment by Mbucari** [comment]
> RE Episode vs Child: right now they're one and the same.

I decided on the following:

```C#
[Flags]
public enum ContentType 
{ 
 Unknown = 0,
 Product = 1,
 Episode = 2,
 SeriesParent = 4,
 Series = Episode | SeriesParent
}
[NotMapped]
public bool IsSerial => IsSeriesEpisode || IsSeriesParent;
[NotMapped]
public bool IsSeriesEpisode => ContentType.HasFlag(ContentType.Episode);
[NotMapped]
public bool IsSeriesParent => ContentType.HasFlag(ContentType.SeriesParent);

```

**Comment by rmcrackan** [comment]
No problem. It'll take me a while to get to though. I've been out of town for several days and my backlog is formidable

**Comment by rmcrackan** [comment]
It looks like the last of these unaddressed items are in your new in-progress PR so we can continue this conversation there.

I've had a million things to do since getting back in town so I don't recall if I already told you: I added the beginnings of a new debug tool. "Hangover" will be deployed with all future versions of Libation. Currently the only tool is to run ad hoc sql. There's also an unused tab just to make the pattern clear for how to add more tabs.

**Comment by Mbucari** [comment]
> we can continue this conversation there.

Agreed. I hate having the same convo across multiple threads.

> I added the beginnings of a new debug tool. "Hangover"

I did see that. I haven't messed around with it yet, but it looks like it may be very useful.  My sql skills are pretty terrible though XD
