### ISSUE TITLE
Application Crash

### ISSUE THREAD

**Issue by jmpatel90** [rmcrackan/Libation#279]
[_Log202206.log](https://github.com/rmcrackan/Libation/files/8943743/_Log202206.log)

**Comment by Mbucari** [comment]
Looks like the Audible server is down for you.  You got audible's "Whoops! Looks like something went wrong." message.

**Comment by jmpatel90** [comment]
Thanks! Just started using Libation and wasn't sure. It keeps crashing periodically while backing up, but works fine again for a bit when I restart it.
