### ISSUE TITLE
Books now dowloading into folder <first author>

### ISSUE THREAD

**Issue by EddCase** [rmcrackan/Libation#281]
Version 8.0.3

Directory Naming set to

`<first author>\<if series-><series><-if series>`

Was working fine in previous version

Expected behaviour eg Wandering Inn Book 1 by pirateaba - 

`c:\books\pirateaba\The Wandering Inn\Wandering Inn.m4b`

now getting 

`c:\books\<first author>\The Wandering Inn\Wandering Inn.m4b`

Titles now are getting downloaded to a folder `<first author>` Rather than the First Authors Name

**Comment by rmcrackan** [comment]
Sorry about that! Fixed in [version 8.1](https://github.com/rmcrackan/Libation/releases/latest)
