### ISSUE TITLE
Books still being downloaded into <author> or <first author> folders

### ISSUE THREAD

**Issue by EddCase** [rmcrackan/Libation#283]
V8.1.0.2
Folder sorting structure set as 

`<first author>\<if series-><series><-if series>`
also tried
`<author>\<if series-><series><-if series>`

Issue not effecting all book downloads

example of books effected

Artemis - Andy Weir
Always looking up: The Adventures of an incurable Optimist - Michael J. Fox
Catching Fire: Hunger Games Trilogy, Book 2: Hunger Games, Book 2 - Suzanne Collins
Go the F--k to Sleep - Adam Mansbach
The Graveyard Book - Neil Gaiman

**Comment by rmcrackan** [comment]
Fixed in [version 8.1.1](https://github.com/rmcrackan/Libation/releases/latest). Thank you for your patience
