### ISSUE TITLE
Couple of bugs related to the old news digests. May also affect podcasts in general.

### ISSUE THREAD

**Issue by atylmo** [rmcrackan/Libation#288]
I know they don't do news digests any more, but I thought maybe these issues could affect something else so I'm reporting them.

The first is that I had the NYT Digest for ten years, but Libation only shows the last two years' worth of content. I can see all of the episodes I have on Audible's site. Episodes from mid-April 2019 and up are still available on Audible to the public, but Libation only shows me the ones from and after early January 2020.

The second is that I briefly had the WSJ Digest and Weekend Digest in 2011, but Libation is also only showing the last two years of episodes and lists episodes I don't own (for the Weekend Digests, it goes back to 2013 but perhaps that's due to being published weekly instead of daily). When I try to download one, the log says I don't have the rights to it. That makes sense, because I unsubscribed, but Libation is showing that I own them. Audible's site only shows the episodes I originally had.

I thought some of these things might transfer over to other podcast episodes too. Some kind of episode cap? Libation says I have 498 NYT episodes and 689 WSJ episodes between both editions. For NYT I should have several thousand. For WSJ I should have two.

To be honest it could just be my account, though.

**Comment by rmcrackan** [comment]
Since this is exclusively these news periodicals which they've also discontinued, I'm going to assume it's only them. If you find anything else though reply here and I'll re-open the issue for investigation.

**Comment by atylmo** [comment]
Okay, will do. Sorry for the trouble. I believe it's my account because the purchase dates seem odd. The reason I have so many is once I unsubscribed from Audible the first time they kept sending them and I never fixed it.
