### ISSUE TITLE
Determine where libation thinks a downloaded file should be

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#291]
I have some books and podcasts that are no longer downloadable from audible but I did download them previously with Libation. Or I have books that were downloaded previously based on a different folder-path setting. For various reasons, I had to recreate my libation library and so those books/podcasts are showing as red. I can manually set the item as 'downloaded' to turn the light to green, but when clicking the traffic light, it gives error 'file not found'. 

What can I do to sync up the actual location of the files with where libation thinks they are? I figured it would be easier to move the files but it's unclear where libation is expecting them to be. The log doesn't seem to show where it tried to look. The Export PDF also doesn't show any path information.

**Comment by Mbucari** [comment]
@rmcrackan 
AAX files, and consequently m4b files, contain the ASINs in metadata. Scanning those files to identify books by their metadata tags would be a slower process, but it's certainly within the realm of possibility. Unfortunately, all bets are off for MP3s.

**Comment by rmcrackan** [comment]
> The initial click is slow in opening the folder window. But later clicks is faster. So I guess it stores the found location in the database?

Yup!
