### ISSUE TITLE
Library Backup Halted: Licenses Denied

### ISSUE THREAD

**Issue by tormaid** [rmcrackan/Libation#297]
About 1/4 of the way though my library's backup on a new machine using version 8.1.3 I started getting the error "Content License denied for asin:[Book ID]" on every remaining not-backed-up title. I checked on the website and I can still stream these titles though the browser so I should still have that license. This is on Audible Japan.

**Comment by Mbucari** [comment]
Please post your log file.

**Comment by tormaid** [comment]
Sorry, here you go:

[Log202206.log](https://github.com/rmcrackan/Libation/files/8979054/Log202206.log)

**Comment by tormaid** [comment]
Okay, so individual titles have started to download successfully again (including ones that errored out a couple hours ago). My guess is I hit the system with too many requests in a short period of time.

**Comment by Mbucari** [comment]
I'm so glad it's working again, because I had absolutely no idea what was wrong!

**Comment by tormaid** [comment]
Okay, well I'll stick to doing incremental backups for now. Thank you for your time!

**Comment by Mbucari** [comment]
How many books were you downloading?  I've batch downloaded as many as 300 books with little or no pausing, and I've never been denied a license.

**Comment by tormaid** [comment]
It stopped at ~125/450 titles

**Comment by mcrc7** [comment]
I am having this same issue how can I solve it.
