### ISSUE TITLE
Libation failing with "Plus Catalogue" audiobooks

### ISSUE THREAD

**Issue by richard-etchells-jones** [rmcrackan/Libation#298]
Audiobooks which have been purchased are downloading successfully. However, any added to the library via "Plus Catalogue" are showing the following error:

Content License denied for asin: [B00D8HU1V0]

   at AudibleApi.Api.GetDownloadLicenseAsync(String asin, DownloadQuality quality)
   at AudibleApi.Api.GetPdfDownloadLinkAsync(String asin)
   at FileLiberator.DownloadPdf.downloadPdfAsync(LibraryBook libraryBook, String proposedDownloadFilePath) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadPdf.cs:line 61
   at FileLiberator.DownloadPdf.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadPdf.cs:line 30
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\Processable.cs:line 58
   at LibationWinForms.ProcessQueue.ProcessBook.Processable_Completed(Object sender, LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationWinForms\ProcessQueue\ProcessBook.cs:line 290
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)

[_Log202206.log](https://github.com/rmcrackan/Libation/files/8984056/_Log202206.log)

**Comment by rmcrackan** [comment]
Those great courses in plus are usually for a limited time and you must have an active audible account. Off the top of my head, my guess is that either audible removed it from the plus catalog or your account has been canceled. See if "Emperors of Rome" is still available on your phone app.

If you download it while it's still in plus, the files stay on your computer. Once audible removes it, there's nothing we can do.

**Comment by richard-etchells-jones** [comment]
Thank you the quick response. In response to the points you raised:

- The Audible account is still active.
- The Plus Catogue item is still available to be added to the library,
where it can be played as normal.

These items could be downloaded as of Thursday 23rd, but this functionality
ceased on Friday 24th. I have since reinstalled Libation, removed and
readded the Plus Catalogue items to the library, and the problem remains.

I can only assume that something has changed on Audible's side. The
application is still excellent for purchased items, and hopefully this
functional will return.

**Comment by rmcrackan** [comment]
Do all Plus titles fail for you now?

Let's try this.

* In audible remove that Emperors of Rome book from your account.
* Open Libation. If you have a lot of books, you might want to search for `rome` to make it easier to find for the next part
* Go to Import \> Remove Library Books. This will show you a new checkbox column
* Check this Rome book. Click the Remove button. Then click the Done Removing Books button
* Go back to audible and re-add your Plus book
* In Libation do a new scan and download

If you're still getting that error, please post your new log here.

I apologize that this is a lot of steps. For that matter I'm sorry it's not working in the first place. I'm not sure what changed. Hopefully with your help we can fix this quickly.

**Comment by Mbucari** [comment]
@richard-etchells-jones 
Are you able to download this book onto your smartphone in the Audible app?

**Comment by richard-etchells-jones** [comment]
Thank you once again for the quick response and ideas.

I followed your instructions and the Plus Catalogue audiobooks are
downloading again. I have tested this with multiple examples.

To answer the other questions you asked:

- Yes, it was with all Plus Catalogue items, not merely Emperors of Rome.
- Yes, I was able to download the item via the android app.

Once again, thank you for the help. Hopefully, the problem will not arise
again. I have also attached the Log file as requested, perhaps it may give
you some idea why the problem occurred and how it was effectively rectified.

Many thanks.

**Comment by rmcrackan** [comment]
Oof. This is going to be a rough one if audible fundamentally changed how plus is handled in the UK site.

@mkb79 -- have you noticed a change to the UK plus catalog? Libation has a user who suddenly can't access it with our library but they verified it does work on the app. They're getting a license denied error.

**Comment by Mbucari** [comment]
This is the same issue as #297, which was Japan, and as https://github.com/mkb79/audible-cli/issues/103, which was Canada.

It's like they're moving region by region and doing something to the system which temporarily breaks Audible Plus downloads.

**Comment by mkb79** [comment]
@rmcrackan @Mbucari 
I have now signed up for a monthly subscription to Audible Plus at Audible UK.

I tried some Audible Plus titles. I was able to download them all without any problems. 

A license request currently looks like:

```http
POST /1.0/content/B016YTJ4DY/licenserequest HTTP/1.1
Host: api.audible.co.uk
X-ADP-SW: 37400811
Content-Type: application/json
Accept: application/json
X-ADP-Transport: WIFI
x-adp-signature: ...==:2022-06-26T19:00:00+02:00
X-ADP-LTO: 120
Accept-Language: de-DE
X-Device-Type-Id: A2CZJZGLK2JJVM
device_idiom: phone
Content-Length: 165
User-Agent: Audible, iPhone, 3.74 (811), iPhone 12 Pro Max (iPhone13,4), 238 GB, iOS, 15.5, Wifi
x-adp-alg: SHA256withRSA:1.0
Accept-Encoding: gzip, deflate, br
X-Amzn-RequestId: ...
X-ADP-Country: DE
x-adp-token: {...}{key:...==}{iv:...==}{name:...}{serial:Mg==}
Connection: keep-alive

json body: {
  "supported_drm_types" : [
    "Mpeg",
    "Adrm"
  ],
  "quality" : "High",
  "consumption_type" : "Download",
  "response_groups" : "last_position_heard,pdf_url,content_reference,chapter_info"
}
```

And the response

```http
HTTP/1.1 200 OK 
Server: Server
Date: Sun, 26 Jun 2022 17:00:00 GMT
Content-Type: application/json
Content-Length: 3625
Connection: keep-alive
x-amz-rid: ...
x-amzn-RequestId: The same id as in the request
X-Amz-Date: Sun, 26 Jun 2022 17:00:00 GMT
Vary: Content-Type,Accept-Encoding,X-Amzn-CDN-Cache,X-Amzn-AX-Treatment,User-Agent
Permissions-Policy: interest-cohort=()

content: {
  "content_license": {
    "acr": "CR!...",
    "allowed_users": ["amzn1.account...."],
    "asin": "B016YTJ4DY",
    "content_metadata": {
      "chapter_info": {
        "brandIntroDurationMs": 1533,
        "brandOutroDurationMs": 3204,
        "chapters": [{
          "length_ms": 25867,
          "start_offset_ms": 0,
          "start_offset_sec": 0,
          "title": "Opening Credits"
        }, {
          "length_ms": 3657654,
          "start_offset_ms": 25867,
          "start_offset_sec": 26,
          "title": "I"
        }, {
          "length_ms": 1691333,
          "start_offset_ms": 3683521,
          "start_offset_sec": 3684,
          "title": "II"
        }, {
          "length_ms": 1175478,
          "start_offset_ms": 5374854,
          "start_offset_sec": 5375,
          "title": "III"
        }, {
          "length_ms": 1747490,
          "start_offset_ms": 6550332,
          "start_offset_sec": 6550,
          "title": "IV"
        }, {
          "length_ms": 3306472,
          "start_offset_ms": 8297822,
          "start_offset_sec": 8298,
          "title": "V"
        }, {
          "length_ms": 1387460,
          "start_offset_ms": 11604294,
          "start_offset_sec": 11604,
          "title": "VI"
        }, {
          "length_ms": 2823964,
          "start_offset_ms": 12991754,
          "start_offset_sec": 12992,
          "title": "VII"
        }, {
          "length_ms": 2420355,
          "start_offset_ms": 15815718,
          "start_offset_sec": 15816,
          "title": "VIII"
        }, {
          "length_ms": 2349491,
          "start_offset_ms": 18236073,
          "start_offset_sec": 18236,
          "title": "IX"
        }, {
          "length_ms": 2564359,
          "start_offset_ms": 20585564,
          "start_offset_sec": 20586,
          "title": "X"
        }, {
          "length_ms": 3019105,
          "start_offset_ms": 23149923,
          "start_offset_sec": 23150,
          "title": "XI"
        }, {
          "length_ms": 2114781,
          "start_offset_ms": 26169028,
          "start_offset_sec": 26169,
          "title": "XII"
        }, {
          "length_ms": 2400618,
          "start_offset_ms": 28283809,
          "start_offset_sec": 28284,
          "title": "XIII"
        }, {
          "length_ms": 4620864,
          "start_offset_ms": 30684427,
          "start_offset_sec": 30684,
          "title": "XIV"
        }],
        "is_accurate": true,
        "runtime_length_ms": 35305291,
        "runtime_length_sec": 35305
      },
      "content_reference": {
        "acr": "CR!...",
        "asin": "B016YTJ4DY",
        "content_format": "AAX_22_64",
        "content_size_in_bytes": 285501951,
        "file_version": "3",
        "marketplace": "A2I9A3Q2GNFNGQ",
        "sku": "BK_ADBL_022928",
        "tempo": "1.0",
        "version": "244475"
      },
      "content_url": {
        "offline_url": "https://dze5l2jxnquy5.cloudfront.net/..."
      },
      "last_position_heard": {
        "status": "DoesNotExist"
      }
    },
    "drm_type": "Adrm",
    "license_id": "...",
    "license_response": "...",
    "message": "Customer [...] has rights to asin [B016YTJ4DY] for AYCL",
    "refresh_date": "2022-07-15T21:00:00Z",
    "removal_date": "2022-08-24T21:00:00Z",
    "request_id": "The same as in the requesr headers",
    "requires_ad_supported_playback": false,
    "status_code": "Granted",
    "voucher_id": "cdn:..."
  },
  "response_groups": ["always-returned", "last_position_heard", "pdf_url", "chapter_info", "content_reference"]
  }
```

**Comment by mkb79** [comment]
@rmcrackan @Mbucari 
The request are made by the original iOS App

**Comment by mkb79** [comment]
The licenserequest response content contains a refresh date and a removal date. These seams to be new.

**Comment by Mbucari** [comment]
Refresh_date and removal_date have been part of .com content licenses since at least June 30, 2021, because I generated this class on that date: https://github.com/rmcrackan/AudibleApi/blob/a48290af990921de1ac27a6f4c22b6ae261aa420/AudibleApiDTOs/ContentLicenseDtoV10.cs

**Comment by rmcrackan** [comment]
What I'm hearing is: this might be something specific to this user's account. We need a debug/verbose option to export the full library jsons. If it's the user and not a new issue with audible uk, I'm not sure of any other way to debug this user

**Comment by Mbucari** [comment]
@rmcrackan I think you can close this one. @richard-etchells-jones 's problem seems to have resolved itself.

**Comment by richard-etchells-jones** [comment]
Yes, thank you for your assistance. The problem seems to have been
temporary, one that others have experienced on occasion.

I am unfamiliar with the processes on GitHub, is there something I need to
do in order to close the query?

Many thanks

**Comment by rmcrackan** [comment]
Thanks for the heads up. Sorry this happened but I'm glad it resolved itself.
