### ISSUE TITLE
Doesn't work with Audible Australia

### ISSUE THREAD

**Issue by Pirateguybrush** [rmcrackan/Libation#3]
No option for Australian region in setup.

**Comment by rmcrackan** [comment]
I have no access to the Australia site but I can make some educated guesses for how to make it work.

The one piece of information I can't find via google is Audible Australia's Marketplace Id. Each audible region has its own ID. Can you go to audible.com.au, inspect, and search for marketplaceid . Hopefully you'll find either MarketplaceId or ObfuscatedMarketplaceId followed by a ~13 character capitalized piece of text that you can report back to me.

**Comment by rmcrackan** [comment]
I think I figured it out. Try the latest version: v3.1.8
