### ISSUE TITLE
One specific podcast refuses to work. Any and all others work flawlessly

### ISSUE THREAD

**Issue by ilicity** [rmcrackan/Libation#302]
All it tells me is that theres an error while trying to process

I've tried removing it and readding it to libation, unfollowed and then refollowed it in audible. I dont know why this particular podcast is giving me so many issues. It is every single episode. log attached.
Every other audiobook and podcast works flawlessly. i also cleared the temp folder and that did not seem to help.

[Log202206_010.log](https://github.com/rmcrackan/Libation/files/8990538/Log202206_010.log)
[Audible Link](https://www.audible.com/pd/Unsolved-Mysteries-Podcast/B08K54KKGZ) 

Curious what you say about this one considering my last log i submitted was.... _Special_ haha

**Comment by ilicity** [comment]
> Thanks for the log and link. I just subscribed and was able to download all 52 episodes. The error in your log appears to be network issues. Can you try again later today and see if it still happens?

I didn't even think of a network issue because it was only this podcast was having this issue. That kinda dumbfounds me.
But regardless, thank you kind sir for the quick response!

**Comment by rmcrackan** [comment]
Since network looks like the culprit, I'm going to close this issue. If it's still a problem later, put your new logs here and I can re-open the issue again, no problem.
