### ISSUE TITLE
Feature Request: Add last name first format option for author names in filepaths

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#303]
I know this has to be parsed/guessed bc audible doesn't provide first and last names but even an 80/20 solution would be great.

**Comment by rmcrackan** [comment]
Sorry. I've done name parsing before "O, that way madness lies". Audible makes an impossible task even harder because they love to shove stuff in the name like "Bob Smith Intro"

**Comment by rmcrackan** [comment]
Github does not make it easy to find closed items! I knew this ticket existed and have been searching for forever to find it.

Great news, we reconsidered this request and decided to go for it. It's available in the current version. Full list of options are here:

https://github.com/rmcrackan/Libation/blob/master/Documentation/NamingTemplates.md#name-list-formatters
