### ISSUE TITLE
Preserving data only available in AAX tags

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#31]
Some of the data I currently use in my collection of scripts is available only in the AAX files, and apparently cannot be copied into M4B tags -- but would be very nice to have in the spreadsheet of data.

Can we make a way to copy them out of the AAX/AAXC files before deletion?

From Mutagen, the following tags would be useful:
> -- original/william/BK_BBCW_000383.aax
> - MPEG-4 audio (AAVD), 43760.84 seconds, 0 bps (audio/mp4)
> GUID=A1O2WKOOUNQRWZ
> prID=BK_BBCW_000383
> rldt=01-JAN-2004
> ©nrt=Robert Powell
> ©pub=Audible Studios

Oh, also `©des`, which I didn't include because it's the long-form description.

**Comment by wtanksleyjr** [comment]
> What all data/metadata/tag/etc would you like to see retrieved?

See the list I gave above -- those are not included in M4B but are in AAX according to mutagen-inspect.

My current manual workflow is to just save the output of mutagen-inspect alongside the M4B, but I'm looking at adopting Libation because of astounding coolness :) .

> Also, do you have a preferred format? xml? json? ...

Given the choice JSON because XML is a PITA, but it's not a big deal. Most of those tags (except the long-form comment) would export fine in the spreadsheet you allow the user to request, which is also fine.

> Are the user for whom the "RetainAaxFiles" setting was added?

I don't remember asking for that, but it's conceivable I might have. You might say I'm the opposite -- I'd like to discard the files after draining every drop of useful content from them ;) . Saving the non-encrypted AAX files is one way of preserving their metadata, but it's pretty wasteful of space once the conversion's done, unless the conversion can fail without us detecting it (I hate it when that happens, and I have had it happen once in my own workflow, not Libation).

**Comment by Mbucari** [comment]
So here are the properties I'm commonly finding finding in the aaxc files. The forthcoming changes will include all these fields. in the m4b file. So far I haven't found a GUID tag in any of the files I've looked at.
{
   "©nam":[
      "Ready Player Two: A Novel (Unabridged)"
   ],
   "©ART":[
      "Ernest Cline"
   ],
   "aART":[
      "Ernest Cline"
   ],
   "©alb":[
      "Ready Player Two: A Novel (Unabridged)"
   ],
   "©gen":[
      "Audiobook"
   ],
   "prID":[
      "BK_RAND_008396DE"
   ],
   "©cmt":[
      "The highly anticipated sequel to the beloved worldwide best seller Ready Player One, the near-future adventure that inspired the blockbuster Steven Spielberg film...."
   ],
   "©des":[
      "The highly anticipated sequel to the beloved worldwide best seller Ready Player One, the near-future adventure that inspired the blockbuster Steven Spielberg film. \nAn unexpected quest. Two worlds at stake. Are you ready? \nDays after winning OASIS founder James Halliday’s contest, Wade Watts makes a discovery that changes everything.\\xa0\nHidden within Halliday’s vaults, waiting for his heir to find, lies a technological advancement that will once again change the world and make the OASIS 1,000 times more wondrous - and addictive - than even Wade dreamed possible.\nWith it comes a new riddle, and a new quest - a last Easter egg from Halliday, hinting at a mysterious prize.\nAnd an unexpected, impossibly powerful, and dangerous new rival awaits, one who’ll kill millions to get what he wants.\nWade’s life and the future of the OASIS are again at stake, but this time the fate of humanity also hangs in the balance.\nLovingly nostalgic and wildly original as only Ernest Cline could conceive it, Ready Player Two takes us on another imaginative, fun, action-packed adventure through his beloved virtual universe, and jolts us thrillingly into the future once again."
   ],
   "cprt":[
      "&#169;2020 Ernest Cline\t;(P)2020 Random House Audio"
   ],
   "©pub":[
      "Random House Audio"
   ],
   "©day":[
      "2020"
   ],
   "©nrt":[
      "Wil Wheaton"
   ],
   "CDEK":[
      "0593396960"
   ],
   "CDET":[
      "ADBL"
   ],
   "VERS":[
      "20056321"
   ],
   "AACR":[
      "CR!Y5N6MYZ7C93XZ1WAZGN67RS3ZP6S"
   ],
   "@sti":[
      "Ready Player Two: A Novel (Unabridged)"
   ],
   "rldt":[
      "24-Nov-2020"
   ],
   "covr":[
      MP4Cover()
   ]
}

**Comment by wtanksleyjr** [comment]
OK, so they're a little different from AAX, that's fair. In my experience files with the same `prID` don't have different contents, so I generally trust it as a UID. Definitely knowing the narrator, author, publisher, release date, and long description is very important, along with title and subtitle (this book doesn't have a subtitle, so that's hard to tell, but for ones that have one, one of those will contain only the main title, while the other will contain both together). I wish they tracked series, but well, they don't -- although usually either the title or subtitle will contain the series information.

**Comment by Mbucari** [comment]
Can you give me an example of a book that has a subtitle?

Also, we _could_ add the series name as a tag. QuickTime tags support custom tag IDs. We could add a "sern" tag (which as far as I can tell isn't already a standard ID) with series name info. It would really just com down to what @wtanksleyjr is comfortable with.

**Comment by rmcrackan** [comment]
I case it's useful, most of the info which Libation stores can be exported into excel, csv, and json. See if one of those exports has some of what you're looking for.

**Comment by wtanksleyjr** [comment]
Almost every book in my collection has a subtitle. Some don't, like the one you chose -- I'm a little surprised to find you don't have any, they're so common...

mutagen tells me one of my m4b files has this:

©alb=The Adventure of English (Unabridged)
©nam=The Adventure of English: The Biography of a Language (Unabridged)

That's a typical subtitle; you can see Audible doesn't have a separate tag for the subtitle, so both tags are best preserved. MP3s almost always have separate tags. (And what is it with putting "(Unabridged)" everywhere -- including, literally, in most abridged books.)

I would love preserving the series info (and anything else Libation uniquely gets) in tags, but I actually agree that the csv/json reports will be adequate for that. My real goal here is to make sure I can run Libation and not lose info versus my current workflow, it's not really a big deal if the info's saved in tags vs in a report, so long as it's easy to connect the line items in the report to the files.

**Comment by rmcrackan** [comment]
I'm going to close this issue. Even though the fix isn't yet live, the following is in the code and it will be available on the next major release:

1) great efforts have been made to preserve all metadata. Between this and the export reports, I think you'll be happy. If I'm wrong, hit me up on here again and we can dig deeper

2) A new setting has been added to Settings > Basic Settings: "Download chapter titles from Audible". When enabled, Libation attempts to preserve all metadata we know to look for and it fixes things like chapter titles and times. When disabled, the output audio file is just a raw decrypt. In this case we don't try to fix these little things and all metadata is untouched.

**Comment by wtanksleyjr** [comment]
Sotto voce comment: do you want me to document "positive case" tests I'm running on 5.0.0? I could make a single issue for all of the "I'm happy with this" comments, for example.

**Comment by rmcrackan** [comment]
Sure, that would be helpful. Thanks

**Comment by BluebonnetSK** [comment]
Suggestion:  The audiobook tagging, naming, and workflow by seanap has become pretty popular.  Would you be willing to map the above tags scraped from the AAX into similar tags as the ones we create using mp3tag for existing files?  See his documentation here:  https://github.com/seanap/Audible.com-Search-by-Album , which uses data scraped from the audible website.  

This would make it so much simpler for mixed-origin libraries (those converted with Libation and those coming from other sources) to be consistent.

**Comment by rmcrackan** [comment]
> into similar tags as the ones we create using mp3tag

I'm not sure I understand what the request is. In practical terms: what would this look like? how would it be used?

**Comment by BluebonnetSK** [comment]
Sorry if I wasn't clear.  I would like to have the tags embedded into the m4b file with the mapping shown on the above link.  These tags are very useful when using Plex for managing an audiobook library, and dedicated abook players like Prologue and Bookcamp can use them.

**Comment by rmcrackan** [comment]
> The idea here is that for books I have bought from Audible and convert with Libation would not need tags scraped from the Audible website (via mp3tag) if these were already in the original AAX and could be embeded during the conversion.

Thanks, now I understand. I'm not opposed to doing this but it would be a new feature and pretty far down on my list of priorities. In the short term you can open a new issue here with any fields that we don't already export. From there maybe we can incrementally work together on the path of: get books, get all correct metadata, write a small program to automate a tool (like ffmpeg) to combine these.

**Comment by wtanksleyjr** [comment]
BlueBonnetSK, It might help to take a look at the "export library" menu
item, and consider the data in there. It's definitely VASTLY better than
what's in the tags, although currently it's not complete (it doesn't have
subtitles at all, nor productID; the "AudibleProductID" it has as a key is
actually not a standard tag, so exiftool can't see it at all). Right now
I'm not doing any retagging, but I might lay out a plan for that, the data
is SO much better than what Audible sends in the actual tags.

This should probably be developed into a plan that can be its own issue.
