### ISSUE TITLE
Podcast

### ISSUE THREAD

**Issue by Lagunabel** [rmcrackan/Libation#310]
How can I add Podcast on Libation?

![0](https://user-images.githubusercontent.com/92586781/178233127-7b088f70-bd92-4b58-af7d-7f065f17f1e8.jpg)

 👇 
 
![1](https://user-images.githubusercontent.com/92586781/178233352-ef75126e-ef7c-4b5f-8581-21bd6fa0a008.jpg)

**Comment by rmcrackan** [comment]
Thanks for these screenshots. Open settings and go to the "Import library" tab. There are 2 settings related to podcasts. One will let you see podcasts in your grid but won't download the episodes. The other setting will also allow you download them. After you've verified that these are checked, they should appear on the next scan. On that "Import" menu, you can do a manual scan or turn on auto scanning which will run a new scan every 5 minutes.

**Comment by Lagunabel** [comment]
Thank You!!! 🤩🤩🤩

**Comment by rmcrackan** [comment]
:smile: You're welcome.

Sorry for the confusion -- the whole podcast thing can be very confusing. Users feel strongly in different ways so we created these options. Some people want podcasts with everything else they own and other people don't want podcasts that they listen to only once to be mixed in with books that they want to keep forever. And a small number of people want to see their podcasts but not download them. Like I said, it can get confusing.
