### ISSUE TITLE
Libation not unlocking some books

### ISSUE THREAD

**Issue by OrdinaryGlitter** [rmcrackan/Libation#311]
I have bought several newer books on audible and when I run libation, it won't work.  For example, I own Dungeon crawler Carl.  It will not allow me to convert it.   One side note,  I went to the audible website, and I noticed that my newer purchases, do not have a download button.  Could that be the problem?
C

**Comment by Mbucari** [comment]
Are you able to download them from the Audible mobile app?

Would you mind placing the links to those books here please? And for good measure, can you please attach your log file?

**Comment by rmcrackan** [comment]
Hmm. Possibly. I just purchased a book today and it has a download button so it's unlikely that audible changed something recently across the board. Did anything else change in your account lately?

**Comment by rmcrackan** [comment]
Since this thread has fizzled out, I'm going to close it. If you have any updates I'm more than happy to reopen it. Just reply to this email.
