### ISSUE TITLE
Version 8.2 - Fresh Install Won't Run

### ISSUE THREAD

**Issue by TsaraVandercross** [rmcrackan/Libation#314]
Saw you updated on Reddit.  Took out my old installation.  Downloaded.  Try running the exe and it never actually runs.  Never even shows up in task manager.

**Comment by Mbucari** [comment]
Please attach you log file

**Comment by TsaraVandercross** [comment]
I would love to!  It isn't creating one at all.

**Comment by Mbucari** [comment]
If you're using default locations, the log files should be in C:\users\[your account]\Libation

**Comment by TsaraVandercross** [comment]
Folder is empty.  Tried running the program again just to make sure...still empty

**Comment by TsaraVandercross** [comment]
![image](https://user-images.githubusercontent.com/100886959/179629109-5828e398-baf5-43e0-8977-5c9aafe8600f.png)

**Comment by Mbucari** [comment]
Were you running Libation on your machine before now? If so, which version, and have you tried downgrading to that version and trying again?

**Comment by TsaraVandercross** [comment]
I had version 7.7.1 previously.  Let me re-install that and I'll let you know if that works.

**Comment by TsaraVandercross** [comment]
7.7.1 runs successfully.  When I do 8.2 again, want me to put it to a new folder or overwrite the files in the old one?

**Comment by TsaraVandercross** [comment]
I let 7.7.1 auto update me.  I appear to be running 8.2.0.1 now and it's actually running.  I guess we can call this closed?  Just really weird that a fresh install wasn't working for me.

**Comment by rmcrackan** [comment]
Thank you for keeping us updated. That is definitely not ok. Please let me know if it happens again

**Comment by rmcrackan** [comment]
@TsaraVandercross - Thank you so much for the bug report above. I think I found the issue. Could you do me a favor and try to do a fresh (that is: non-upgrade) download of [version 8.2.1](https://github.com/rmcrackan/Libation/releases/latest)? I think this fixes it.

**Comment by TsaraVandercross** [comment]
As requested, I did a fresh install of 8.2.3.  I was able to successfully run it now.  Looks good to me!

**Comment by rmcrackan** [comment]
Fwew! Thanks for following back up with me and thank you for your patience. That was a rough release.
