### ISSUE TITLE
nonstop crashing

### ISSUE THREAD

**Issue by whichy** [rmcrackan/Libation#316]
[_Log202206.log](https://github.com/rmcrackan/Libation/files/9136388/_Log202206.log)

**Comment by Mbucari** [comment]
You uploaded the wrong log file.  That one is from June.

**Comment by rmcrackan** [comment]
Sorry about the crashing. I just fixed something which was affecting some users and sounds similar to your issue. Can you try [version 8.2.1](https://github.com/rmcrackan/Libation/releases/latest) and let me know if it fixes your problem?

**Comment by whichy** [comment]
thank you for the fast response

[Log202207.log](https://github.com/rmcrackan/Libation/files/9136702/Log202207.log)
[Log202207_001.log](https://github.com/rmcrackan/Libation/files/9136703/Log202207_001.log)
[Log202207_002.log](https://github.com/rmcrackan/Libation/files/9136704/Log202207_002.log)


I installed the new one and it won't even run. 
![image](https://user-images.githubusercontent.com/838292/179644755-e72860f6-2ee2-454b-92b0-ce6bd415669e.png)

**Comment by rmcrackan** [comment]
Go into the folder where your logs are and delete `FileLocations.json` . Does the error still happen?

**Comment by whichy** [comment]
Brilliant!! I'm running 8.2.0 now and everything seems to be working.  Thank you!

**Comment by rmcrackan** [comment]
w00h00. Thank you for your reply. I'm glad it's fixed

**Comment by NoodleLover69** [comment]
deleting the file did not resolve the issue for me
