### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by adamgilli** [rmcrackan/Libation#317]
Got this error after updating libation to 8.2.1 today 
<img width="316" alt="image" src="https://user-images.githubusercontent.com/38134797/179671920-cb1b4ad9-786a-45e1-bf0d-2ac9b3c99238.png">

**Comment by Mbucari** [comment]
Same as https://github.com/rmcrackan/Libation/issues/316

Go into the folder where your logs are and delete FileLocations.json

**Comment by Jed28** [comment]
I went into C:\Users\Jed\Libation and deleted FileLocations.json. I still have the issue
[Log202207.log](https://github.com/rmcrackan/Libation/files/9138380/Log202207.log)

**Comment by ElysiumFic** [comment]
I've got this error too. I don't have a FileLocations.json file to delete. The error started after upgrading to the latest version. Have tried deleting Libation entirely and re-downloading. Still there.

**Comment by rmcrackan** [comment]
Crap. It's the new way I tried to release new versions to create smaller downloads. Fixed in [version 8.2.2]. I'm so sorry about this :(

**Comment by rmcrackan** [comment]
Thank you for testing this, opening an issue, and creating screenshots. You really took a lot of your time to address my screw up.
