### ISSUE TITLE
Add App Updater to Avalonia Builds

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#324]
Continuing our discussion in https://github.com/rmcrackan/Libation/pull/321

Problem: Add automatic app updating to Libation and LibationCli without using winforms.

I mentioned the possibility of making 2 new libation dlls devoted to updating, one for Windows and one for linux, with the windows one using Autoupdater.net. I tried this out, but it's going to be a real problem because we would have to find and load all the windows forms assemblies manually. So that's a no-go in my book.

My next thought is to just copy Autoupdater.Net's ZipExtractor.exe and ship it with Libation. We would have to do the zip file downloading, but after that we just call zipextractor like so:
```console
zipextracter.exe --input %temp%\libationupdate.zip --output C:\path\to\Libation\ --executable C:\path\to\Libation\Libation.exe
```

Then we just make the same kind of thing fox Linux using a bash script, which can double as the auto updater for libationcli on linux.

All that's left is the libationcli updater for windows. Maybe just reuse zipextractor?

**Comment by rmcrackan** [comment]
Another issue with autoupdater (I haven't tested yet so I don't know the answer) -- which zip will it grab? We're about to have 3.

**Comment by Mbucari** [comment]
Octokit.Release.Assets contains all files published as part of the release.  As you said we'll have three, so you'll need to be very strict with your file naming and hard-code which suffix each applications looks for.

**Comment by rmcrackan** [comment]
That's right. I remembered that being part of the autoupdater magic but we actually do it ourselves in appscaffolding. Once we decide on a naming convention for all 3 versions, GetLatestRelease can find the best match inside those Assets for the current version.

You were right about the current version of autoupdater. He responded. As it is now, sadly, winforms are too tightly coupled -- https://github.com/ravibpatel/AutoUpdater.NET/issues/556

**Comment by rmcrackan** [comment]
@Mbucari Do I remember right that you completed this?

**Comment by Mbucari** [comment]
> @Mbucari Do I remember right that you completed this?

Only for windows. Once we get this Deb package build Incorporated into the release workflows, I think we should just make a message box pop up for Linux and mac users that an update is available.

**Comment by rmcrackan** [comment]
Sounds good. Do you want me to keep this open for that? Or close?

**Comment by Mbucari** [comment]
Open. I'll add it after the deb build happens. What I'd like to do for linux is provide the shell commands to execute the update in a textbox the the user can just copy/paste.

**Comment by rmcrackan** [comment]
This was completed in the latest, correct?

**Comment by Mbucari** [comment]
@rmcrackan yup!
