### ISSUE TITLE
Classic Updater not working

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#328]
You zipped the classic build inside a folder, so that folder is extracted to the install location when updating. You end up with a subfolder named Classic-Libation.8.3.0-win-classic containing all the update files, and then the old Libation.exe is launched.

**Comment by rmcrackan** [comment]
Ugg. Right you are. Remember when I said I hadn't done it manually in a long time :(

I fixed that file. It should work now. I'll test in a moment.

**Comment by rmcrackan** [comment]
Success. Thanks for catching that!
