### ISSUE TITLE
Add Bug Report Templates to Libation Repo

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#330]
You can make templates for new issues by creating files in .github/ISSUE_TEMPLATE/

Check out the ones I made here: https://github.com/Mbucari/Libation/tree/master/.github/ISSUE_TEMPLATE

And to see what they look like, try making a new issue on my repo: https://github.com/Mbucari/Libation/issues

**Comment by Mbucari** [comment]
FYI, these examples I made in my repo are now live in your repo after merging my latest PR.

**Comment by rmcrackan** [comment]
Thanks -- that's really slick

**Comment by rmcrackan** [comment]
Yup, I was just checking them out
