### ISSUE TITLE
Possible to support build in chapters for M4B files?

### ISSUE THREAD

**Issue by zanymuzik** [rmcrackan/Libation#332]
I tried the linux version and loved the UI and simplicity.

The one feature I missed the most is the lack of chapters build into the output files (https://github.com/mkb79/Audible supports that).
Any possibility to add that in a future release? I believe this might also need M4B support.

**Comment by Mbucari** [comment]
It does have built-in chapters. They are the original QuickTime format (aka Apple text, timed text). Other conversion tools will strip the QuickTime chapters and replace them with Nero chapters. If you are able to see chapter markers on mp4 files generated by other tools but not in files generated by Libation, its probably because your media player supports Nero chapters but not QuickTime chapters.

**Comment by rmcrackan** [comment]
Ugg. The more things change... I remember fighting these identical metatag battles nearly 20 years ago. Evidently they're here forever.

It sounds like this feature request is to take our metadata cleanup a step further (ie Nero) and possibly look into how @mkb79 does it.

**Comment by Mbucari** [comment]
This is something FFMpeg does unless you tell it not to. see `-movflags disable_chpl` at https://ffmpeg.org/ffmpeg-all.html#Options-56

Personally, I hated the Nero format and was glad to be rid of them.

**Comment by rmcrackan** [comment]
@Mbucari Thanks for the link. I can see both sides here: on one hand it's standard ffmpeg behavior and on the other hand I see their warning about nero tags. You've more than earned my trust and I'm comfortable letting you be the tie breaker.

**Comment by Mbucari** [comment]
I could add support for them if there's a really strong outcry, but I think I've got better things to do in the meantime. I'd say anyone who can't see chapter markers in their media player needs a better media player.

But if you REALLY want to add Nero chapter markers to your books, just run the following ffmpeg command:

`ffmpeg -i source.m4b -c copy outfile.m4b`

**Comment by rmcrackan** [comment]
Fair enough. Your call. Do want me to keep this open as a 'maybe'? Or close it?

**Comment by Mbucari** [comment]
Close it. I'll add it to my internal list of possible changes/upgrades.
