### ISSUE TITLE
unexpected error

### ISSUE THREAD

**Issue by BShort16** [rmcrackan/Libation#333]
<img width="419" alt="Screenshot 2022-07-29 154717" src="https://user-images.githubusercontent.com/110264630/181854998-a358072a-0bb6-4467-b488-9ecfff5aad7f.png">

Error pop up stops me from adding anymore books. I am unable to delete the corrupted folder so I am essentially stuck with half my library downloaded and I have no clue how to fix it. 

[Log202207_001.log](https://github.com/rmcrackan/Libation/files/9223741/Log202207_001.log)

**Comment by Mbucari** [comment]
This looks like you have a corrupt directory at D:\Libation\me

Can you see that directory in file explorer? if not, open a comand prompt and run the following command:
`dir D:\Libation /A DRAHS`

**Comment by BShort16** [comment]
I was originally saving all the files to an external drive and when I got stuck I scrapped that and just downloaded them to my main computer. Did not have any issues after that. I will try and play around with the external and see if I can fix it. Thank you!
