### ISSUE TITLE
Skip importing this book? (Content License denied for asin)

### ISSUE THREAD

**Issue by Domenic080** [rmcrackan/Libation#336]
I can see my audible library on Libation and it is correctly updated with new audiobooks when I add them on Audible Android App and  when I clic on "Scan library" on Libation, but after hundreds of audiobooks downloaded and decrypted with success, now I can't do it anymore. For every audiobook I receive the classic error "Skip importing this book? An error occurred while trying to process this book etc etc.".
In log file I see the error "Content License denied for asin" but I correctly authenticate myself with audible username and password and I can correctly use Audible service via Android app.
I've attached log file. 
I use Libation version 8.3.1.1 on Windows 10.

[Log202207_003.log](https://github.com/rmcrackan/Libation/files/9227581/Log202207_003.log)

I've already tried to uninstall and reinstall Libation and other previous versions.
I've tried to delete all my Audible audiobook for my library and add again them, without success.  

Thank you in advance for your precious help!
Domenico

**Comment by rmcrackan** [comment]
This happens sometimes. I'd be very surprised if it doesn't resolve itself in the next 24 hours. I've heard this from a small number of users and they've all had it resolve itself in a day of 2. I wish I had a better explanation but the good news is that it does seem to go away on its own.

**Comment by Domenic080** [comment]
I confirm that today I can again download and decrypt Audible audiobooks, I had to remove and readd to Audible library my audiobooks. It is strange that for some specific podcast series the error remains. I can correctly listen those podcasts via Audible Android app.

**Comment by rmcrackan** [comment]
Sorry for the trouble. I wish I could figure out the pattern of when and why audible does this. I'm glad it's working for you again.

Which ones are still having issues?

**Comment by Domenic080** [comment]
Now I 've only two podcast that I can't download and decrypt, in the log the error is simply "Decrypt failed". I've attached the log. Thanks again

**Comment by Domenic080** [comment]
[Log202208.log](https://github.com/rmcrackan/Libation/files/9229812/Log202208.log)

**Comment by rmcrackan** [comment]
Thank you for the log file. This looks for all the world like a networking/proxy issue. However I assume your phone is using that same network to download the podcasts. I've got to be honest - I'm not sure what I can do about that. I'm sorry.
