### ISSUE TITLE
Linux and Mac TODO

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#339]
## Linux
- ~~Saving and restoring window size and position doesn't seem to work.~~
- ~~Make a .deb package and upload it to [Launchpad](https://launchpad.net). That will solve the install/update problem because users will just use apt-get.~~
- Add Linux arm64 native libraries. I'll need someone with an arm64 Linux machine to compile these for me.

## Mac
- ~~Mp3 is unavailable. This fix will require making an aac decoder for mac and then tracking down and adding the mac version of libmp3lame.~~
- ~~Figure out how to code sign the executables so users don't have to disable developer verification to use the app. This will [enrolling in the Apple Developer Program](https://developer.apple.com/developer-id/). TBH this seems onerous and maybe impossible without owning a mac.~~
- ~~Similar the the above point, we need to make an installer and updater for macOS. I don't know much about Linux, and I know even less about Mac.  Maybe we need to reach out to other open source devs who support macOS and see how they do it.~~
- ~Add command to open the file explorer to a folder (Go.To replacement)~ https://github.com/Mbucari/Libation/commit/d884d34c5b61c95c9341ff2524bc1b701281093f

## Both
- ~~The Expand/Collapse Process Queue symbols ( ❱❱❱ ❰❰❰ ) are Unicode and don't display properly. Replace with images.~~
- ~~Add the Illegal Character Replacement dialog.  This is a problem because Avalonia doesn't support Unicode, so the defaults don't display properly.~~

**Comment by sammcj** [comment]
Hey @Mbucari - have you had a look at some automated options for this?

The one that popped to mind is using Github Actions which has macOS runners with something like this - https://github.com/marketplace/actions/code-sign-action

Great project by the way!

**Comment by rmcrackan** [comment]
@Mbucari  is this still an active to do list? Or is it stale?

**Comment by Mbucari** [comment]
>  is this still an active to do list? Or is it stale?

Sorry I missed that. Yes, it's stale.

**Comment by timdmackey** [comment]
Thanks to those involved for your work on making this app cross-platform! I discovered Libation yesterday and was happy to be able to backup my Audible library to my mac.

_I see that this issue is closed, but my question is closely related so I didn't want to open a new issue unnecessarily._

Once it's set up, the app works great on MacOS, but the process of running the app could definitely be improved. The following issues could be solved by having the app live in an .app bundle:
- Can't add Libation to the Dock
- Need to sort through 300 files to find the executable each time
- Shortcuts to the executable don't reflect the correct icon, even if a custom icon is added to the executable
- (enhancement, unsure if this is fixable) Terminal shows up on the screen every time the app is opened

I was curious whether it would be possible for me to bundle the app myself, and found this document from Avalonia: https://docs.avaloniaui.net/docs/distribution-publishing/macos. I haven't read over it closely enough to know if I can do the app bundling myself, but I'm curious whether this is something that could be added to the build process to provide a proper .app bundle for Mac?

_Code signing_ is a separate issue, but it looks like there's a suggestion above about how that might be possible to do with Github Actions.

Libation is amazing, and I'd love for more people to be able to use it! Having a signed (or even unsigned) app bundle would make this something I could recommend to my other mac-using friends to use. Many of them are not technical at all, and wouldn't feel comfortable running terminal commands to get the program set up and running.

**Comment by rmcrackan** [comment]
@timdmackey Great find -- thanks! I understand about the terminal aspect. The platform specific bits for mac and linux are difficult. If you or anyone you know is a mac developer, we welcome improvement submissions. Github has a [walk-through](https://docs.github.com/en/get-started/quickstart/contributing-to-projects) for how to contribute.

@Mbucari In case this didn't already come up during your avalonia research, I'm tagging you here.

**Comment by Mbucari** [comment]
@timdmackey I've tried to make an app package in the past, but I've been unable to solve the issue of the icns not displaying. It's maddening. At this point the only explanation I have is that macOS won't display icons for unsigned packages, but I haven't found any documentation supporting that hypothesis.

That said, the package does work. In fact, I added a couple of permissions to the plist and now it runs without me disabling gatekeeper or adding an exception for Libation. This confuses me, because I thought that shouldn't be possible. I rolled back my VM to right after I installed guest additions (before I had ever run Libation on it), and the app package still executed without bugging me for permissions. IDK what's going.

Anyway...

[Here's my work-in-progress package](https://github.com/rmcrackan/Libation/files/10714092/Libation.app.zip). Please download and try it. You'll need to download the most recent Libation chardonnay release and extract the program files into Contents/MacOS. Then just double-click the package and let me know what happens!

**Comment by Mbucari** [comment]
@timdmackey 

OK, I've managed to put together a macos app bundle.

https://github.com/Mbucari/Libation/suites/10926896121/artifacts/552533482

You still have to --master-disable gatekeeper, but it's not a self-contained bundle. Also I noticed that mp3 conversion was never working on mac. I added new .dylib files to support that feature.

The problem I see with the app bundle is that Libation is actually 3 programs: Libation, LibationCli, and Hangover. I think Hangover could be converted to a plugin within the Libation bundle, but I don't know what to do about CLI.

Calling all mac people: @timdmackey , @hutattedonmyarm, @CryptoJones

Can you offer any suggestions for bundling Hangover and LibationCli into a single App bundle?  All three programs share >95% of the program files, so splitting them into three separate bundles would nearly 3x the distribution size.

Also, @hutattedonmyarm, you mentioned you have an M1 mac. I'd never thought about it before today, but we've only ever built Libation for macos x64. Would you care to test an arm64 version?

**Comment by hutattedonmyarm** [comment]
@Mbucari I think it's perfectly reasonable to have LibationCLI and Hangover both sit in Libation.app/Contents/MacOS/, I've seen a few apps doing this.

Libation works perfectly fine when I built it for M1. However I couldn't find a good way to create a universal binary (including both arm64 and x64). We can just mash both together using lipo, but that creates an enormous binary. So releasing them seperately is probably better.

I also tested your bundle creation with M1, works without modification if fed the appropriate build output.

> Also, do you think I could get you to compile a couple of C libraries on your machine for me?

Sure thing!

**Comment by Mbucari** [comment]
@hutattedonmyarm 
> Sure thing!

Thanks!

The first one is a lib called ffmpegaac. [Here's the source and build script](https://github.com/rmcrackan/Libation/files/10716999/ffmpegaac.zip).

To build it, you'll homebrew installed and you'll need to download [this FFmpeg source package](https://ffmpeg.org/releases/ffmpeg-5.1.2.tar.xz).

Here's the build command:
```Console
./build_ffmpegaac_homebrew.sh ffmpeg-5.1.2.tar.xz
```

The second library is libmp3lame. You'll need [the build script from my repo](https://github.com/Mbucari/NAudio.Lame_SA/blob/master/build_libmp3lame_homebrew.sh) and [this LAME source package](https://versaweb.dl.sourceforge.net/project/lame/lame/3.100/lame-3.100.tar.gz).

Here's the build command:
```Console
./build_libmp3lame_homebrew.sh lame-3.100.tar.gz arm64
```

NOTE: if you download the source packages through safari and it extracts the .tar.gz to .tar, the script won't work.

To test that the built libraries are working:
1. Rename ffmpegaac.dylib to ffmpegaac.arm64.dylib and place it into the bundle's MacOS folder.
2. Rename libmp3lame.dylib to libmp3lame.arm64.dylib and place it into the bundle's MacOS folder.
3. Run Libation and change the settings to download as MP3.
4. Try to download a book.

**Comment by hutattedonmyarm** [comment]
I had to use `arm-apple-darwin22.2.0` instead of arm64 to build LAME, because:

```
Configuring LAME
checking build system type... arm-apple-darwin22.2.0
checking host system type... Invalid configuration `arm64': machine `arm64' not recognized
configure: error: /bin/sh ./config.sub arm64 failed
```

but that fails as well:

```
libtool: link: gcc -dynamiclib  -o .libs/libmp3lame.0.dylib  .libs/VbrTag.o .libs/bitstream.o .libs/encoder.o .libs/fft.o .libs/gain_analysis.o .libs/id3tag.o .libs/lame.o .libs/newmdct.o .libs/presets.o .libs/psymodel.o .libs/quantize.o .libs/quantize_pvt.o .libs/reservoir.o .libs/set_get.o .libs/tables.o .libs/takehiro.o .libs/util.o .libs/vbrquantize.o .libs/version.o .libs/mpglib_interface.o   -lm  -O3   -install_name  /usr/local/lib/libmp3lame.0.dylib -compatibility_version 1 -current_version 1.0 -Wl,-single_module -Wl,-exported_symbols_list,.libs/libmp3lame-symbols.expsym
Undefined symbols for architecture arm64:
  "_hip_decode", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_decode1", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_decode1_headers", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_decode1_headersB", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_decode_exit", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_decode_headers", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_decode_init", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_set_debugf", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_set_errorf", referenced from:
     -exported_symbol[s_list] command line option
  "_hip_set_msgf", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode1", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode1_headers", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode1_headersB", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode_exit", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode_headers", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_decode_init", referenced from:
     -exported_symbol[s_list] command line option
  "_lame_init_old", referenced from:
     -exported_symbol[s_list] command line option
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [libmp3lame.la] Error 1
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

I'll try to get it up later today when I have more time on my hands

**Comment by hutattedonmyarm** [comment]
Can't get LAME to build. Statically linked (`--enable-static` as additional parameter to configure) is no problem, but can't figure out the magic to build dylibs

**Comment by Mbucari** [comment]
> can't figure out the magic to build dylibs

I found that I couldn't get lame to make a dynlib, but I could make it myself after it had compiled its static libmp3lame.a (located at ./libmp3lame/.libs/libmp3lame.a) by executing 
`gcc -dynamiclib -shared -fPIC -Wl,-v,-force_load libmp3lame.a -o libmp3lame.dylib`

**Comment by hutattedonmyarm** [comment]
> > can't figure out the magic to build dylibs
> 
> I found that I couldn't get lame to make a dynlib, but I could make it myself after it had compiled its static libmp3lame.a (located at ./libmp3lame/.libs/libmp3lame.a) by executing `gcc -dynamiclib -shared -fPIC -Wl,-v,-force_load libmp3lame.a -o libmp3lame.dylib`

That worked! Downloading and MP3 conversion, working as well. I've forked and created [a realease](https://github.com/hutattedonmyarm/Libation/releases/tag/9.3.0) to attach the binaries

**Comment by Mbucari** [comment]
> That worked! Downloading and MP3 conversion, working as well.

Woohoo!

> The binary is _huge_

I guess that's arm for you. Trade file size for simpler, fixed width instructions.

> I've forked and created [a realease](https://github.com/hutattedonmyarm/Libation/releases/tag/9.3.0)

FYI, this goes with my audio library project [AAXClean.Codecs](https://github.com/Mbucari/AAXClean.Codecs)

Thank you again!

**Comment by rmcrackan** [comment]
@Mbucari sounds like you've completed even more of this list! Again -- very impressed by the xplat progress

**Comment by hutattedonmyarm** [comment]
> did my `build_ffmpegaac_homebrew.sh` script work out of the box?

yep!

**Comment by Mbucari** [comment]
@hutattedonmyarm 
We just released a Mac arm644 build. Let me know what you think!

**Comment by hutattedonmyarm** [comment]
> @hutattedonmyarm
> We just released a Mac arm64 build. Let me know what you think!

```
❯ sudo spctl --master-disable && sudo spctl --add --label "Libation" /Applications/Libation.app && open /Applications/Libation.app && sudo spctl --master-enable
Password:
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x600001ff5fb0 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

```

<img width="372" alt="Screenshot 2023-02-20 at 06 25 47" src="https://user-images.githubusercontent.com/664905/220016342-7c9368cd-8b56-4147-ba6e-93bdabe5246b.png">

I'll have to look into that!

**Comment by Mbucari** [comment]
Did you move Libation.app to /Applications?

**Comment by hutattedonmyarm** [comment]
Yep. I just build it again using your current master on my machine. Everything seems fine with the exception of the Libation, LibationCli, and Hangover executables. Mine are slightly larger (148KB instead of your 129KB) for each.

Looking at the Mach-O binary headers reveals:

```
❯ otool -h /Applications/Libation.app/Contents/MacOS/Hangover
/Applications/Libation.app/Contents/MacOS/Hangover:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2    17       2056 0x00a18085

❯ otool -h ~/Dev/Libation/Source/bin/Publish/MacOS-chardonnay/Hangover
/Users/max/Dev/Libation/Source/bin/Publish/MacOS-chardonnay/Hangover:
Mach header
      magic  cputype cpusubtype  caps    filetype ncmds sizeofcmds      flags
 0xfeedfacf 16777228          0  0x00           2    18       2072 0x00a18085
```

There's an additional load command in mine. And `otool -l` reveals a nearly identical binary, except that this is present in mine and missing from the release:
```
Load command 17
      cmd LC_CODE_SIGNATURE
  cmdsize 16
  dataoff 128912
 datasize 19296
```

`codesign` confirms this:
```
❯ codesign -d /Applications/Libation.app/Contents/MacOS/Hangover
/Applications/Libation.app/Contents/MacOS/Hangover: code object is not signed at all

❯ codesign -d ~/Dev/Libation/Source/bin/Publish/MacOS-chardonnay/Hangover
Executable=/Users/max/Dev/Libation/Source/bin/Publish/MacOS-chardonnay/Hangover
```

Manually signing the executable with `codesign -s - /Applications/Libation.app/Contents/MacOS/Hangover` works.

[This Apple developer forum post](https://developer.apple.com/forums/thread/722039) is the only thing I found. Looksl ike you *need* to code sign when you want to run an ARM binary.

**Comment by Mbucari** [comment]
@hutattedonmyarm does this command work for all three apps?
```Console
codesign --force --deep -s - /Applications/Libation.app
```

Also, does macOS usually come with codesign preinstalled, or do users need to install xcode to get it?

**Comment by hutattedonmyarm** [comment]
@Mbucari The command works for all of them!

I’m not sure if it’s preinstalled. I think it is, but I’ve stumbled upon some note that it is part of the Command Line Utilities for Xcode (which needs to be installed). In any case it *does* require an Apple developer certificate (the free one is enough).

Here’s some more info: https://wiki.lazarus.freepascal.org/Code_Signing_for_macOS

I can try to get a GitHub workflow running with my own certificate, but I’m fairly short on time this week

**Comment by Mbucari** [comment]
@hutattedonmyarm

I just restored my macOS Monterey VM to a fresh installation, and the `codesign` tool __is__ installed.

I'm still a bit confused about the arm64 requirements.

- Am I correct that the `codesign -s -` command merely creates the placeholders in the executable files/package for the signature, but does not actually sign the files/package? 
- On a fresh install install of macOS on apple silicon, would is executing the `codesign --force --deep -s - /Applications/Libation.app` command sufficient for users to run Libation?
- Do apple silicon users still need to add a gatekeeper exception?

**Comment by hutattedonmyarm** [comment]
> I'm still a bit confused about the arm64 requirements.
> 
> * Am I correct that the `codesign -s -` command merely creates the placeholders in the executable files/package for the signature, but does not actually sign the files/package?

Sort of, yes. The `-` creates an ad-hoc signature (instead of using a real one), which just adds the hash and no cryptographic proof.

> * On a fresh install install of macOS on apple silicon, is executing the `codesign --force --deep -s - /Applications/Libation.app` command sufficient for users to run Libation?
> * Do apple silicon users still need to add a gatekeeper exception?

`codesign --force --deep -s - /Applications/Libation.app` in addition to the gatekeeper exception might just as well work. I tried remove the gatekeeper exception but that didn't work ("error: no matches for search or update operation" whatever) so I can't really test it.
Ideal would probaby to add the codesigning step to the workflow and have users just add the gatekeeper exception. Not sure if it works though

**Comment by Mbucari** [comment]
> Ideal would probaby to add the codesigning step to the workflow and have users just add the gatekeeper exception.

I agree, and I think the only way to do that is to build Libation on the macos runner. I tried using [zsign](https://github.com/zhlynn/zsign) on linux, but it just did not work.

So yeah, we need to port the [build-linux.yml](https://github.com/rmcrackan/Libation/blob/master/.github/workflows/build-linux.yml) workflow and [the associated scripts](https://github.com/rmcrackan/Libation/tree/master/Scripts) to macos and just build both linux and mac releases on macos runners.

**Comment by hutattedonmyarm** [comment]
@Mbucari I think I got it! I made two different versions: The first one just ports the [build-linux.yml](https://github.com/rmcrackan/Libation/blob/master/.github/workflows/build-linux.yml) to run on macOS. THe second one runs the linux build on Ubuntu and macOS buils on macOS. Mainly, because I had to wait over an hour for a macOS runner to become available during testing. I don't know if that's a common occurance or I got unlucky.

Anyways, [tag v9.3.4.a](https://github.com/hutattedonmyarm/Libation/tree/v9.3.4.a) builds everything on macOS and [tag v9.3.4.b](https://github.com/hutattedonmyarm/Libation/tree/v9.3.4.b) uses Ubuntu for the linux builds.

The difference to the original isn't big, I had to get creative without grep's `-P` flag and macOS uses zsh by default which can't to a "lowercase only the first letter". Other than that, only an install of `dpkg` was necessary to bundle the linux package.

The second one is a bit more fiddly, because I need to specify `matrix.os: [ubuntu-latest, macos-latest]` so that it matches a `runs-on` specification. I needed to update how the OS name is generated to provide the correct publishing profile

**Comment by rmcrackan** [comment]
Wow, this list looks nearly complete. Ambitious!

**Comment by Mbucari** [comment]
@rmcrackan I just got a free license for JetBrains Rider via their open source dev program, and it actually works in the macOS VM (unlike VSCode which had graphical issues due to VM drivers). The x-plat future is looking brighter than ever!

**Comment by rmcrackan** [comment]
Very cool! I didn't even know that initiative existed.

**Comment by rmcrackan** [comment]
Is Linux arm64 still a goal? Or is this list all done?

**Comment by Mbucari** [comment]
> Is Linux arm64 still a goal? Or is this list all done?

Still a goal. IDK if anyone out there uses it, but I'm sure it's rare. Frankly, most of the reason I even made the workflow to build linux arm64 is because it was pleasing to have a 2x2 workflow matrix, and I'm not ashamed to admit it!

**Comment by rmcrackan** [comment]
Supporting [ARM](https://nickdesaulniers.github.io/blog/2023/03/10/disambiguating-arm/)? :)

**Comment by medic17** [comment]
> Supporting [ARM](https://nickdesaulniers.github.io/blog/2023/03/10/disambiguating-arm/)? :)
I can volunteer my arm based linux box. Your choice of Ubuntu or Debian. I would like this so I can upload my backups to secondery backup solutions. You can even have SSH access if you want it.

I can try to help debug if needed though its been awhile since I worked on dotnet

**Comment by Mbucari** [comment]
@medic17 Cool, thank you! Whichever has the lowest libc version, please. I'll work on getting you compilation instructions.

**Comment by CryptoJones** [comment]
@Mbucari I built libation using aarm64 Rocky Linux build here: https://github.com/CryptoJones/LibationArm64Linux

This is my first time building dotnet applications without full visual studio so if I missed anything you need please let me know.

EDIT: Seeing the above comments if you give me the compile instructions I can also build on RHEL-based Rocky as well.

**Comment by JesseCSlater** [comment]
Are there any plans to support non debian based linux distribution? I am running fedora, and I would love to be able to use libation. I have tried running through wine, and was not able to make it work, although I have never used wine before so I might have done something wrong. I also tried using alien to create an rpm, but there were dependencies missing which I could not find. 
I don't know what it takes to package a .NET application for linux, but it seems to me that it would be ideal to distribute a flatpak, since that would get the widest coverage possible.

**Comment by Mbucari** [comment]
Sorry, I've kind of let this issue go. I won't be able to even begin working on it for another two weeks.

@CryptoJones Building Libation on any platform (and _for_ any platform with cross compiling) is trivial with dotnet. The problem is with the native libraries used by [AAXClean.Codecs](https://github.com/Mbucari/AAXClean.Codecs). These are only used for mp3 transcoding. Everything else in Libation with wok without them, but I don't want to deploy on a new platform without the mp3 functionality. In theory these can be cross compiled, but I have no way to test them.

@medic17 @CryptoJones

Here's the build files for ffmpegaac.so and libmp3lame.so:
https://github.com/Mbucari/AAXClean.Codecs/raw/master/native/ffmpegaac/build-libation-dependencies.tar.xz

Run `build-ffmpegaac.sh` and `build-lame.sh`

To test that they are working:

- Rename them to `ffmpegaac.arm64.so` and `libmp3lame.arm64.so`
- Build Libation using the dotnet 7 SDK.
  - `dotnet build LibationAvalonia.csproj`
- Place `ffmpegaac.arm64.so` and `libmp3lame.arm64.so` inside Libation's bin directory
- Run Libation and try down download something as an mp3.
<hr>
@JesseCSlater 

In theory Libation should already work for fedora. I'm not a *nix user, so my knowledge is pretty limited, but [according to Microsoft](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog#linux-rids) Libation should already run on most desktop distributions like CentOS, Debian, Fedora, Ubuntu, and derivatives.

I don't know how to make an rpm package, but can you try [converting the deb to rpm](https://blog.desdelinux.net/en/como-convertir-deb-a-rpm-y-viceversa/)?

**Comment by JesseCSlater** [comment]
I gave alien a try, but was not able to get it to work

I got this error:
```
[jesse@fedora Downloads]$ sudo dnf install Libation-10.2.1-2.x86_64.rpm
Last metadata expiration check: 5:26:37 ago on Sun 30 Apr 2023 03:57:39 PM CDT.
Error: 
 Problem: conflicting requests
  - nothing provides liblttng-ust.so.0()(64bit) needed by Libation-10.2.1-2.x86_64
(try to add '--skip-broken' to skip uninstallable packages)
```

I tried installing lttng-ust-devel to get the dependency but it did not provide what I needed. Based on [this](https://www.reddit.com/r/Fedora/comments/uxybsn/comment/ia0ynk5/?utm_source=reddit&utm_medium=web2x&context=3) reddit comment, I think it might not be so easy to fix. I am a bit incompetent with this sort of thing though, so I might just be missing something.

**Comment by cadric** [comment]
It have already been mentioned, but I hope that you someday will be able to make a .RPM for us fedora users.
Right now I am using  Libation.9.3.2-linux-chardonnay.tar.gz  as this is the last build for linux that you have that is not only packaged as a .deb for linux

**Comment by JesseCSlater** [comment]
Just downloaded the 9.3.2 version and it works perfectly. This is so much better than all the other things I tried. Whole library is downloaded instantly. Thank you so much!

**Comment by Mbucari** [comment]
@JesseCSlater @cadric Libation will now release rpm builds. [Check out v10.3.0](https://github.com/rmcrackan/Libation/releases/tag/v10.3.0)

**Comment by cadric** [comment]
> @JesseCSlater @cadric Libation will now release rpm builds. [Check out v10.3.0](https://github.com/rmcrackan/Libation/releases/tag/v10.3.0)

Amazing. Thank you!

**Comment by kfbest** [comment]
really (really) late to the game here, but thank you SO SO SO very much @Mbucari  for getting the native Mac App functioning. Using this is so much easier now.

**Comment by Mbucari** [comment]
@kfbest You're very welcome. It was a major PITA and cost me $400 lol.

**Comment by Mbucari** [comment]
I'm going to close this issue. If anyone needs to convert an audiobook to mp3 on an arm64 system, please open a new issue.
