### ISSUE TITLE
Project Translation

### ISSUE THREAD

**Issue by shuvashish76** [rmcrackan/Libation#342]
Integrate [Weblate](https://github.com/WeblateOrg/weblate) for translation purpose.

Features: https://weblate.org/en/features/
![Screenshot_2021-12-05-21-15-09](https://user-images.githubusercontent.com/48226312/144753433-4fc61e84-f12d-42d0-885e-1b9abd399061.jpeg)
https://weblate.org/en/hosting/

**Comment by rmcrackan** [comment]
While localization is admirable, I've been involved with enough localization projects to know what a massive undertaking this is. Unless a person volunteers to spearhead this effort, for the foreseeable future, Libation is English-only. However we will continue to support all global audible regions
