### ISSUE TITLE
Writing narrator to TCOM (COMPOSER)	tag

### ISSUE THREAD

**Issue by TheMetalCenter** [rmcrackan/Libation#346]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
The composer tag is pretty widely used as a field for the narrator, which is currently written to the file as `nrt`. It would be useful if the narrator was also written to the `TCOM` composer field. 

**Describe alternatives you've considered**
Manually writing the tag

**Additional context**
![image](https://user-images.githubusercontent.com/49706654/183272424-5246b30e-01b7-4943-acad-983c45170f9f.png)

Thank you for developing such a useful program!

**Comment by rmcrackan** [comment]
A similar bit of conversation happened [last week](https://www.reddit.com/r/audible/comments/wcjrpe/audible_backup_one_big_file_or_a_file_per_chapter/iidlbi2/) on reddit. As noted in that thread -- my recommendation for now is to use [MP3TAG](https://www.mp3tag.de/en/), especially [this feature](https://docs.mp3tag.de/getting-started/first-steps/#copying-one-field-to-another-field).

For the time being, I'll leave this enhancement request open in case we decide to incorporate it into Libation also.

**Comment by TheMetalCenter** [comment]
Thank you for the response! That feature is indeed powerful, I've found "Filename to Tag" very helpful in the past. In this case, however, I'm not sure if it works; though I may have the tag code incorrect. I tested the "Tag to Tag" option with `NRT`, `NARRATOR`, and `©NRT` (which is what MusicBee's tag inspector says the tag code is) but MP3TAG did not find a tag with those codes. The tag is also not observed by MP3TAG's extended tag feature. 

Anyway, it's not a huge deal, I just thought I'd suggest it as it would simply workflows for some whenever a new audiobook is added to collection.

**Comment by Mbucari** [comment]
I just like to pipe in and say that the tags are copied verbatim from the audible files. ©nrt is the field code used by apples QuickTime tags.

See https://exiftool.org/TagNames/QuickTime.html

(Unfortunately I couldn't find an official Apple reference)

**Comment by RandmTask** [comment]
I would love to see the Narrator in the Composer tag as well. PLEX and Prologue both use this as the Narrator field. Would be great to get it to work without having to post process the files. 

At the moment I have to use a program called TagEditor by Amvidia (not free) to update the Narrator field

FYI MP3Tag on a Mac is not a free download, it costs $21

**Comment by Mbucari** [comment]
@rmcrackan reminder that this is now done

**Comment by rmcrackan** [comment]
This will be available in the next version, courtesy of Mbucari

@Mbucari Thanks for the reminder

**Comment by rmcrackan** [comment]
Included in latest: [v8.8.1](https://github.com/rmcrackan/Libation/releases/latest)
