### ISSUE TITLE
Unexpected end when deserializing object.

### ISSUE THREAD

**Issue by anesone** [rmcrackan/Libation#348]
[Log202208_002.log](https://github.com/rmcrackan/Libation/files/9293535/Log202208_002.log)

**Comment by rmcrackan** [comment]
Sorry this is happening. Please go into that folder where your log file is and delete `FileLocations.json`. Then restart Libation and let me know if the error happens again.

**Comment by rmcrackan** [comment]
Are you sure you deleted FileLocations.json? This sounds like something happened to the QuickFilters.json file

**Comment by anesone** [comment]
I deleted the quickfilters json, and it started up fine. I tried to add my
filters back, and it gives me the same error.
I deleted the quick filters in the app, and even when I don't have any
quick filters, but try to filter using something like "-tags:pluslibrary"
or "-isliberated", it gives the same error.

**Comment by rmcrackan** [comment]
I was too hasty with my 2nd recommendation. All searches are failing. It sounds like the search engine is corrupted. Delete folder SearchEngine and do a new Scan

This points to something troubling though: potentially 2 corrupted files in the same folder. How old is your hard drive? Have you been experiencing any other data integrity issues?

**Comment by anesone** [comment]
Also, now if I try to use any kind of filter, including just partial
title/author/etc, the grid goes blank.

**Comment by rmcrackan** [comment]
After deleting that folder did you do a scan? If yes, did it recreate the SearchEngine folder?

**Comment by anesone** [comment]
Sorry, I wasn't seeing your responses on the other emails.

I deleted the SearchEngine folder and opened the app again. I told it to
manually scan, and then attempted to filter again. It worked!

I added back my quick filters and all is well again.  Thanks for your help!

(I haven't had any other data integrity issues that I am aware of, but the
laptop is getting a bit old.)

**Comment by rmcrackan** [comment]
Fortunately the search engine is fully recreated after every scan so it's easy to delete if it gets weird. And the FileLocations file is mostly a convenience. That said: keep an eye out. 2 corrupt files is suspicious.

Glad you're back in business!
