### ISSUE TITLE
An error decrypting a book.

### ISSUE THREAD

**Issue by Admin-Yukiko** [rmcrackan/Libation#349]
**Describe the bug**
Tried liberating "A History of Britain Volume 3"

**To Reproduce**

1. Try to liberate the book.
2. Get error

**Expected behavior**
The book should be decrypted :)

**Screenshots**

**Platform**
Window 10 up to date as of 2022-08-08
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
[Log202208.log](https://github.com/rmcrackan/Libation/files/9297071/Log202208.log)

**Comment by rmcrackan** [comment]
Sorry about these errors? Are you able to download "Histories" or "A History of Britain: Volume 3" on your phone? Also, does this happen for all books now or just these few?

**Comment by Admin-Yukiko** [comment]
" Are you able to download "Histories" or "A History of Britain: Volume 3" on your phone?"
No and no. I was using Libation to retrieve books for my son from his Audible library and didn't realize that some of the titles are part of, what I believe they call, Audible Plus. If you don't know, Audible Plus is a special bonus that provides extra books to listen to free with a subscription, no need to spend a credit for them. Using the official Audible apps, these cannot be downloaded. The odd thing though is some of his Plus titles Libation had no trouble downloading and liberating.

"Does this error happen for all books now? or just these few?"
There are four books that Libation cannot liberate, the two I mentioned and, I later noticed the first two volumes of "A History of Britain".

I don't know if my issue stems from the fact that these four books are Plus, books or if is an issue with Libation. An example of a Plus book that your fine program was able to download is "Bletchley Park and D-Day". So this is a puzzle to me.

Thank you for your quick response and for creating Libation.

**Comment by rmcrackan** [comment]
Libation can only download what's in your library. That is to say: those audible plus titles have to be in your library in order to download them. So if you can add them back to your library, then Libation can download them. (After you download them, you're welcome to go to audible and remove them from your library again.)
