### ISSUE TITLE
Thoughts about UI process of liberating single book

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#35]
1. The UI affordance to liberate a specific book is extremely non-obvious on first download (why would clicking a stoplight make anything "go"?). What if it depicted a red button labeled with a download icon instead? The green light could become a green checkmark. If you have a yellow icon, a yellow-triangle would be iconic.
2.  When I click the stoplight to liberate a specific book, I find it extremely jarring that I have to answer "no" in order to get the software to do what I feel like I asked it to do. Would it work to rename the buttons from "yes/no" to "liberate all/liberate one"?
3. Additionally, the fact that the default choice (if I press Enter) is to process everything would be pretty bad for my 1500-book library -- perhaps some UI code to see how many books are pending and set the default to only the current one if there are more than, say, 10 books pending. (This would only matter if the user pressed "Enter", which happens to be how I like to interact with that kind of dialogue.)

**Comment by rmcrackan** [comment]
1. The stoplight is going to get retired soon eventually because we've streamlined the app to no longer need the 'yellow' step -- so this metaphor no longer works. I like your ideas
2. Again: good idea
3. I don't want to put too much extra logic into this but I like the idea of switching the default

**Comment by wtanksleyjr** [comment]
The solution in that commit looks fantastic!
