### ISSUE TITLE
Feature Request: Create an nfo file.

### ISSUE THREAD

**Issue by Admin-Yukiko** [rmcrackan/Libation#351]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
For a while, we were using InAudible to decrypt books. It seems there was a change in the encryption algorithm used and InAudible no longer works. One of my sons discovered Libation. So, thanks to you, the developer, we have a new soution. :)

When InAudible decrypted a book it would create a *.nfo file with various information about the book in a nicely formatted text file, eg. title, author, reader, etc. The file was named, book title.nfo and placed in the folder with the the audio files.  Libation does retreive most of the info that InAudible placed in the nfo file. Your program displays the data and thanks to copy/paste I can create a nfo file in the same format but I was wondering, if at some future date, you could add this ability to Libation? Below I have provided an empty nfo file, with no actual book info, only the categories of data listed. There are other things normally listed in the file that might be important to "library-philes", eg. copyright publisher, etc, as well.

[Empty nfo file.txt](https://github.com/rmcrackan/Libation/files/9305386/Empty.nfo.file.txt)

**Comment by rmcrackan** [comment]
Funny you should say that 😄  Years ago, Libation was originally based directly off of inAudible. inAudible was a phenomenal program and I'm deeply thankful for it. As you said, it hasn't kept up with the times. (I heard the programmer has physical pain when sitting too long so he's no longer able to program. It's quite sad.) And as such, I used to create the exact same nfo file along side each audio file.

Over time Libation changed from handling one-off files into being a more cohesive library tracker and about a year ago I moved the nfo stuff into the "Export" at the top. You can export all of your library information in several formats including Excel.

**Comment by Admin-Yukiko** [comment]
Unfortunately, I don't see nfo as a backup file type in the Expot menu option. I can create them manually. So it's not that big of an issue, just a little bit more tedious.

**Comment by rmcrackan** [comment]
Apologies for being unclear. There are no more one-file-per-book nfo files. The data has been moved into exports so that people can get the info for all books at once.
