### ISSUE TITLE
Better error messages for these scenarios

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#352]
**Problem**

These 2 bug reports keep coming to me in reddit PMs

1. they don't have permission -- especially if a book expired from the Plus catalog between the time when they scanned and tried to download
2. the rare user will start getting errors on all downloads. Libation won't work with audible for some people for about a day. It always comes back on its own in less than 2 days and doesn't seem to happen again. It doesn't seem to be users who hit the api a lot. I can find no pattern. Once they tell me it's *every* download, I know this is happening.

**Solution**

In the case of common misunderstandings, it's the system's fault for not being more clear.

1. Libation should be able to detect license issues and let the user know that the most likely cause is returned book or audible removed it from plus. Ideally we'd also know it's a plus title but we don't currently track that
2. The only one of these I can find logs for right now is #336 which was logged as a networking error -- I don't know if this is the same or not. Any time there's a batch of more than 3 books with 100% failures, we should suggest waiting a day and creating an issue ticket with log file if it doesn't resolve itself.

**Comment by Mbucari** [comment]
Re 2, I suspect that inside the Audible app there is a built-in fallback to a secondary server when the primary is offline due to maintenance or an upgrade. The timing makes sense (being unreachable for ~1 day). Ideally we would debug the real audible app while the primary is down to find the secondary endpoint, but I haven't been able to do that yet.

**Comment by rmcrackan** [comment]
I assumed something like that must be the case. I originally suspected that they were punishing heavy users but there's a lot of reasons that doesn't add up. Unless we can catch it in the act and intercept the new traffic, all we can really do is inform the user.

**Comment by Mbucari** [comment]
It's funny you closed this now, because I was thinking about this problem and I think I've discovered a pattern. In both cases, `GetDownloadLicenseAsync` fails with a "Content License denied ..." message. All license denials come with license denial reasons like this:

```Json
{
   "license_denial_reasons":[
      {
         "message":"...",
         "rejectionReason":"...",
         "validationType":"Membership"
      },
      {
         "message":"...",
         "rejectionReason":"...",
         "validationType":"Ownership"
      },
      {
         "message":"...",
         "rejectionReason":"...",
         "validationType":"Client"
      },
      {
         "message":"...",
         "rejectionReason":"...",
         "validationType":"AYCL"
      }
   ]
}
```

I've looked through a lot of logs from old issues, and it seems like every time a license is denied because of reason 2 (random error that resolves itself in a few days), the "Client" validation type message is this:

```Json
{
   "message":"Since ClientId is null, skipping client rights validation.AAAClientId[ApolloEnv:AudibleApiExternalRouterService/EU/Prod], does not has access to asin[B09J1NKC2V].",
   "rejectionReason":"RequesterEligibility",
   "validationType":"Client"
}
```
and the "AYCL" validation type message is this:

```Json
{
   "message":"Customer [A78I42WYNWDFU] has rights to asin [B09J1NKC2V] for AYCL",
   "rejectionReason":null,
   "validationType":"AYCL"
}
```

If that is indeed the pattern, it's easily detectable and we can make more useful error messages.

**Comment by Mbucari** [comment]
OK, I did a deep dive and I'm feeling really good about this theory. I downloaded every attached log file for every one of Libation's past issues that contained "license_denial_reasons". Then I split them up by files that contained null and non-null values for the AYCL rejectionReason. No files had both null and non-null values. Finally, I went to each issue and tried to figure out if it was a legitimate case of license denial (reason 1), or a classic case of temporary denial (reason 2). Here are the results:

| Issue | Has null AYCL? | Summary |
| --- | --- | --- |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/215#issuecomment-1073769794) | No | Looks like titles are no longer in his audible library |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/216#issuecomment-1073484351) | No | title removed from plus catalog |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/222) | No | issue unrelated to license denial |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/224#issuecomment-1093247650) | No | Seems like some kind of account-specific authentication error |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/228) | No | issue unrelated to license denial |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/256) | No | issue unrelated to license denial |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/287#issuecomment-1162155965) | No | One title that user no longer had rights to |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/297#issuecomment-1165822336) | **YES** | Classic case |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/298) | **YES** | Classic case |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/304) | **YES** | issue unrelated to license denial, but still had many consecutive null AYCL in a short time |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/336) | **YES** | Classic case |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/349) | No | User removed titles from Audible library, but not from Libation |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/375) | **YES** | Classic case |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/375#issuecomment-1256955547) | **YES** | Classic case |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/375#issuecomment-1260087444) | **YES** | Classic case |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/389) | No | issue unrelated to license denial, though titles removed from plus catalog |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/389#issuecomment-1304665860) | No | issue unrelated to license denial, though titles removed from plus catalog |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/389#issuecomment-1306715404) | No | issue unrelated to license denial, though titles removed from plus catalog |
| [Issue Link](https://github.com/rmcrackan/Libation/issues/402) | No | Lots of license denials, but those appear to be titles that were removed from plus |


Now I feel pretty confident that a null AYCL rejectionReason indicates a temporary denial of service error.

**Comment by rmcrackan** [comment]
Holy good golly -- that's some serious log diving
