### ISSUE TITLE
Cleanup library to support new file locations

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#353]
What is the best way to clean up my Libation backups to support the newer file location features? I've got a bunch of folders from the old flatish file arrangement, mixed in with those in the newer folder arrangement that I configured ( `\<first author>\<if series-><series><-if series>\<if series->#<series#> - <-if series><title short>` ). 

I assume I could simply delete everything, reset the download status, and re-download. But that seems like rather a largish hit across 4 accounts and >3500 books. It would be useful if there were a simpler way to accomplish this??

Thanks, and thanks for creating and supporting this extremely useful program!

**Comment by rmcrackan** [comment]
Sorry, that's the best way. Unfortunately, all of the custom download processing options are kinda a one-way street.

While it may happen one day, what is required to enable this feature is not in the cards anytime in the foreseeable future. So I'm going to close this request for now.

**Comment by 2001db8** [comment]
Hi,

I've reached the point in exporting my library. Might be a stupit question, but

> reset the download status

how do I do that?  I did not find an option and simply moving the files out of the directory won't reset the status.

> Thanks, and thanks for creating and supporting this extremely useful program!

That too! :)


BR
