### ISSUE TITLE
Allow running LibationCli with switches instead of Settings.json

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#355]
**Is your feature request related to a problem? Please describe.**
I'm trying to automate a nightly job to run LibationCli and download any new books into my Plex setup. LibationCli depends on Settings.json existing and already populated with the settings you want.

**Describe the solution you'd like**
I would like to configure LibationCli with a series of command line switches, something like:
```
./LibationCli --appdata_dir="/home/user/Libation" --books_dir="/books" --folder_template="<first author>/<title short> [<id>]" --file_template="<title> [<id>]" scan
```

**Describe alternatives you've considered**
I've used the GUI on a separate computer to generate one and then edited it to be compatible with Linux and used that. It works but is much less accessible for scripting.

**Comment by wtanksleyjr** [comment]
I also would like to primarily use the CLI on Linux, but fall back to a GUI
when problems arise. (My Linux machine lacks a monitor, and I usually am
not in a situation to hook it up.)

One thought: multiplatform GUIs are getting harder. What if Libation could
serve a web page as a rudimentary GUI, allowing account setup, Audible
logins, and such? It needn't be a full web server, just run, use, and when
the program closes the server's gone.

-Wm

**Comment by rmcrackan** [comment]
> I've used the GUI on a separate computer to generate one and then edited it to be compatible with Linux and used that. It works but is much less accessible for scripting.

This is the way to do it. The centralized settings logic is far too deeply ingrained in the product; this would be a massive undertaking vs the small amount of time it takes to do this with the gui. Also, the Settings file is just a json, so creating a program to output a custom settings yourself is approachable. You wouldn't even need to create it from scratch, just edit a current Libation Settings file.

> What if Libation could serve a web page as a rudimentary GUI, allowing account setup

While not a bad idea on the surface, the details of this are ugly. I've spec'ed this out in the past and once you get past the superficial, it's death by 1,000 cuts. Monitor-less Linux workstation is too fringe of a situation to add specialized tools for. However, regarding "when problems arise": please let us know if you find bugs. We'll happily address those.
