### ISSUE TITLE
Names with accented characters end up as gibberish

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#360]
**Describe the bug**
When saving a book with an extended ascii character somewhere in it, it ends up saving it as gibberish in Linux.

This should be Emily Brontë
```
drwxr-xr-x   3 k8s k8s   3 Aug 14 12:08 'Emily Bront'$'\353'
```

This also happens with all of the fancy character replacements that Libation uses by default.

**To Reproduce**

1. Download one of Emily Brontë's books in linux.
2. View the author's name

**Expected behavior**
I'd expect it to appear as `Emily Brontë`

**Platform**
Linux docker image

**Comment by Mbucari** [comment]
The character is written properly on Ubuntu 21, so I don't know what to tell you. I'd look at your docker configuration.

![VirtualBox_Ubuntu_15_08_2022_15_18_36](https://user-images.githubusercontent.com/37587114/184720307-72354987-714c-47d4-9f55-62c09c1cd648.png)

**Comment by pixil98** [comment]
Closing this, it was the locale on the server providing persistent storage to the docker container.
