### ISSUE TITLE
Follow up from reddit user v8.4.1 pre-release bug

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#361]
Following up from [here](https://www.reddit.com/r/audible/comments/wotihu/windows_10_support_has_been_nixed_how_am_i/ikgxbob/)

If you have no tags and if all books have been downloaded, the steps are easy, but this is a pretty specific case. Let me know if this is you.

Otherwise, let's see if your logs can help. Your log file is in `C:\Users\<user name>\Libation`. Can you attach it to this issue/ticket?

**Comment by ff-o** [comment]
hey,
thanks for opening an issue. I have no tags and have downloaded not my entire library, just all the books I want.
Weird issue, I hope we will sort it out.

Here are the log files -->>

[Log202207.log](https://github.com/rmcrackan/Libation/files/9353096/Log202207.log)
[Log202207_001.log](https://github.com/rmcrackan/Libation/files/9353097/Log202207_001.log)
[Log202208.log](https://github.com/rmcrackan/Libation/files/9353098/Log202208.log)
[Log202208_001.log](https://github.com/rmcrackan/Libation/files/9353099/Log202208_001.log)
[Log202208_002.log](https://github.com/rmcrackan/Libation/files/9353100/Log202208_002.log)
[Log202208_003.log](https://github.com/rmcrackan/Libation/files/9353101/Log202208_003.log)
[_Log202112.log](https://github.com/rmcrackan/Libation/files/9353103/_Log202112.log)
[Log202112.log](https://github.com/rmcrackan/Libation/files/9353104/Log202112.log)
[Log202201.log](https://github.com/rmcrackan/Libation/files/9353105/Log202201.log)
[Log202202.log](https://github.com/rmcrackan/Libation/files/9353106/Log202202.log)
[Log202203.log](https://github.com/rmcrackan/Libation/files/9353107/Log202203.log)

**Comment by rmcrackan** [comment]
Thank you for the log files. The most recent file looks like a lot of activity on Classic today with no errors. Are you still having problems?

**Comment by Mbucari** [comment]
@rmcrackan It's a lot of activity in Classic "Version":"8.3.6.1"

No instance of 8.4.1.1 makes it past logging the startup state.

**Comment by ff-o** [comment]
@Mbucari summarized it. 

"8.4.1.1" still won't open and I don't  even get any error messages like the first time I opened it (this must have something to do with the runtime version I installed (and deinstalled later) the error message was refering to, which probably made a mess)

 No problems with"8.3.6.1"

**Comment by rmcrackan** [comment]
I can't figure this out at all and I'm terrified to do another full release until this is fixed. I'm going to try another pre-release soon - v8.4.2. Let's see if it makes any difference.

**Comment by rmcrackan** [comment]
I fear my confidence is low but I just released [v8.4.2](https://github.com/rmcrackan/Libation/releases/tag/v8.4.2). Please let me know if it works for you.

**Comment by ff-o** [comment]
Sadly, no change. Classic doesn't open and Chardonnay still exhibits the strange behaviour of just loading once after extracting the archive.

Just for the sake of it, the most recent logfile, even though there should be nothing new

[Log202208_004.log](https://github.com/rmcrackan/Libation/files/9372384/Log202208_004.log)

Thanks again for your support, especially since this seems to be a "me" problem

**Comment by Mbucari** [comment]
Rename the Libation app settings folder (C:\Users\ff\Libation) to Libation.bak, then try again. It'll ask you to do it fresh install, so do that and see if it works then.

**Comment by rmcrackan** [comment]
@Mbucari That will certainly cause no harm but I'm curious what you're hoping will happen. 8.3.x and 8.4.x are using those same settings; successfully for 8.3 and unsuccessfully for 8.4.

Here's where my brain is stuck:

The only substantial difference appears to be the new OS-specific AppConfig. This user's experience is kinda similar to what happens to me when I build in the wrong order. I would suspect that except [1] I use that build script that you're familiar with, including the `clean` [2] we've tested these built exe.s many times and we can't get the error to happen on my computer, on your no-.net VM fresh install, or on your no-.net VM as upgrade. I've even gotten verification that the latest 8.4 pre-release works for another random user.

Either I'm missing something with the AppConfig issue. Or else that's a red herring and there's something completely unexpected. In any case... I'm friggin' stumped.

**Comment by Mbucari** [comment]
@ff-o Don't do that just yet.

@rmcrackan I have another idea. I think some of the reflection code is bad. I'm working on a fix which I'll push shortly.

**Comment by ff-o** [comment]
The comment about a fresh installation was made in a hurry, before I checked 8.4.2 on another Win10 21H2 Laptop.

I must admit that I was a bit reassured that it did not work there either.
Exactly the same, I tried to make a fresh install and couldn't get past the settings pane.

**Comment by rmcrackan** [comment]
> another Win10 21H2 Laptop

That raises the stakes; the issue is not segregated to that one laptop

**Comment by Mbucari** [comment]
I hope closing this thread wasn't premature. I've never been able to replicate this problem, so IDK if my fix is a fix.

**Comment by rmcrackan** [comment]
Intentional. I have no clue either. I keep trying these builds hoping I'll see something different. They've all worked flawlessly for me

**Comment by rmcrackan** [comment]
Whoops -- no. It was intentional to accept the PR. Github "helpfully" closes referenced issue numbers when we put it in the commit comments -- which is where they damn well belong! So I have to remember to re-open the tickets. Ugg.

**Comment by rmcrackan** [comment]
@ff-o [v8.4.3](https://github.com/rmcrackan/Libation/releases/tag/v8.4.3) has a major fix in it. If you haven't run out of patience with us yet, please try Classic and Chardonnay and let us know how it goes.

Whether you continue to help us test or not, thank you very much for all you've done. I know this isn't the software experience anyone wants and you've been quite kind to help so much with this process.

**Comment by CharlieRussel** [comment]
OK, I have several that won't download with 8.4.3.1 Classic. I selected one, B002V019KM as representative and ran with full verbose logging on just that one title.  After it failed, I downloaded and decrypted it with inAudible so I know it's still available to me. 

I'll be happy to provide access to my account so you can test. 
[B002V019KM.zip](https://github.com/rmcrackan/Libation/files/9376631/B002V019KM.zip)

**Comment by Mbucari** [comment]
@CharlieRussel It looks like you've got a different, unrelated problem. I suspect removing your c[...]l pre-amazon account, saving, then re-adding it may fix your problem.

**Comment by ff-o** [comment]
v8.4.3 classic + chardonnay works flawlessly so far :) 
Tried to open and close it several times and downloaded some pdfs, no problems so far.
I'll try and download some books later.

> I know this isn't the software experience anyone wants and you've been quite kind to help so much with this process.

This immediate support is exactly the experience I want. I knew this is a personal project from the start, so don't worry:
I'm happy 

Thanks @rmcrackan @Mbucari

**Comment by rmcrackan** [comment]
@ff-o 

Whew! That's wonderful to hear 😄 

@CharlieRussel 

> I've sent the necessary json to @rmcrackan

I didn't get it. I'm also leaving on vacation very soon so I won't have time to look at it for a while.

Speaking of vacation, I'm pretty sure the latest build is ready for a full release but if I do so mere hours before I leave -- that's not just tempting fate a little bit. This was certainly a happy note to end on before I leave though. Much thanks to everyone for seeing this through. Esp MBucari who cracked the problem..

**Comment by Mbucari** [comment]
@rmcrackan Have fun! And turn off your email! (unless you work for one of those companies who expect you to be on call 24/7 🤬)

@CharlieRussel my email is mbucari1@gmail.com.  If I manage to fix this before @rmcrackan gets back, I'll post a unofficial build that you can use.

**Comment by CharlieRussel** [comment]
Sent. For real this time. :)  @rmcrackan -- Enjoy your vacation! We'll all still be here when you get back, with luck. (At my age, one needs the qualifier!)

**Comment by rmcrackan** [comment]
> Sent. For real this time. :) @rmcrackan -- Enjoy your vacation! We'll all still be here when you get back, with luck. (At my age, one needs the qualifier!)

Wow -- this email just arrived. 4 months later. Not surprisingly, the tokens are more than a little expired now so I can't use these settings for testing
