### ISSUE TITLE
Crash when there is an error downloading with setting "ask each time"

### ISSUE THREAD

**Issue by bilbags** [rmcrackan/Libation#364]
**Describe the bug**
The program crashes every time it encounters an error in downloading a book. The setting chosen for errors is "ask each time." 

UPDATE1: I now see that this is tied to formerly available Plus content that is no longer available AND when it has a PDF. This was reported in the message prior to this one & I am going to try the prelease version referenced there. 

UPDATE2: The problem persists with the prelease v8.4.2 and with any former Plus content that also includes a PDF (e.g., Count of Monte Cristo, Practical Yoga Nidra, etc.).

**To Reproduce**

1. Click the LIberate traffic light icon in the far left column to download a book
2. Download error encountered with the pop-up asking what to do (per setting)
3. In a few seconds, there is a pop-up window "Libation has stopped working...." and the program shuts down

**Expected behavior**
For the program not to crash when it unable to download a book & allow one to choose to retry, stop, or ignore. 

**Screenshots**
N/A

**Platform**
Windows 10 Professional Version 21H2 Build 19044.1889

**Log Files**
Begin processing queue
 {}2022-08-21 16:12:05.042 -05:00 [ERR] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_2(System.Object, System.ValueTuple`2[[System.Exception, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]])) Download & Decrypt
AudibleApi.ValidationErrorException: Content License denied for asin: [B0854PPSRZ]
   at AudibleApi.Api.GetDownloadLicenseAsync(String asin, DownloadQuality quality) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Download.cs:line 137
   at FileLiberator.DownloadDecryptBook.downloadAudiobookAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadDecryptBook.cs:line 136
   at FileLiberator.DownloadDecryptBook.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadDecryptBook.cs:line 94
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\Processable.cs:line 58
   at LibationAvalonia.ViewModels.ProcessBookViewModel.ProcessOneAsync() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationAvalonia\ViewModels\ProcessBookViewModel.cs:line 130
 {"ExceptionDetail":{"HResult":-2146233088,"Message":"Content License denied for asin: [B0854PPSRZ]","Source":"AudibleApi","TargetSite":"Void MoveNext()","RequestUri":null,"JsonMessage":"{\"license_denial_reasons\":[{\"message\":\"Asin [B0854PPSRZ] is not eligible for AYCL\",\"rejectionReason\":\"ContentEligibility\",\"validationType\":\"AYCL\"},{\"message\":\"Since ClientId is null, skipping client rights validation.AAAClientId[ApolloEnv:AudibleApiExternalRouterService/NA/ACLS/Prod], does not has access to asin[B0854PPSRZ].\",\"rejectionReason\":\"RequesterEligibility\",\"validationType\":\"Client\"},{\"message\":\"Ownership: User [A3A1OA237FOZFK] does not has Ownership rights for asin [B0854PPSRZ].\",\"rejectionReason\":\"RequesterEligibility\",\"validationType\":\"Ownership\"},{\"message\":\"Customer [A3A1OA237FOZFK] is not part of any plans.\",\"rejectionReason\":\"RequesterEligibility\",\"validationType\":\"Membership\"}]}","Type":"AudibleApi.ValidationErrorException"}}2022-08-21 16:12:05.053 -05:00 [ERR] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_1(System.Object, System.String)) ERROR. All books have not been processed. Most recent book: processing failed
 {}2022-08-21 16:12:05.389 -05:00 [INF] (at LibationAvalonia.ViewModels.ProcessBookViewModel+<Processable_Completed>d__76.MoveNext()) Automated backup: Download Pdf Step, Completed: [B0854PPSRZ] Practical Yoga Nidra: A 10-Step Method to Reduce Stress, Improve Sleep, and Restore Your Spirit
 {}

Begin processing queue
 {}2022-08-21 16:20:26.126 -05:00 [INF] (at LibationAvalonia.ViewModels.ProcessQueueViewModel+<QueueLoop>d__60.MoveNext()) Begin processing queued item. 5/9/2022 [B005GFQ5WQ] The Count of Monte Cristo
 {}2022-08-21 16:20:26.128 -05:00 [INF] (at FileLiberator.Processable+<ProcessSingleAsync>d__23.MoveNext()) Begin ProcessSingleAsync {"Title":"The Count of Monte Cristo","AudibleProductId":"B005GFQ5WQ","Locale":"us","Account":"a[...]e.b[...]s@a[...]t.n[...]t"}
 {}2022-08-21 16:20:26.131 -05:00 [INF] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: 
Download & Decrypt Step, Begin: [B005GFQ5WQ] The Count of Monte Cristo
 {}2022-08-21 16:20:26.139 -05:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__9.MoveNext()) {"Username":"a[...]e.b[...]s@a[...]t.n[...]t","LocaleName":"us"}
 {}2022-08-21 16:20:26.560 -05:00 [INF] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Download & Decrypt Step, Completed: [B005GFQ5WQ] The Count of Monte Cristo
 {}2022-08-21 16:20:26.568 -05:00 [INF] (at FileLiberator.Processable+<ProcessSingleAsync>d__23.MoveNext()) Begin ProcessSingleAsync {"Title":"The Count of Monte Cristo","AudibleProductId":"B005GFQ5WQ","Locale":"us","Account":"a[...]e.b[...]s@a[...]t.n[...]t"}
 {}2022-08-21 16:20:26.577 -05:00 [INF] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: 
Download Pdf Step, Begin: [B005GFQ5WQ] The Count of Monte Cristo
 {}2022-08-21 16:20:26.632 -05:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__9.MoveNext()) {"Username":"a[...]e.b[...]s@a[...]t.n[...]t","LocaleName":"us"}
 {}2022-08-21 16:20:26.661 -05:00 [ERR] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_2(System.Object, System.ValueTuple`2[[System.Exception, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[System.String, System.Private.CoreLib, Version=6.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]])) Download & Decrypt
AudibleApi.ValidationErrorException: Content License denied for asin: [B005GFQ5WQ]
   at AudibleApi.Api.GetDownloadLicenseAsync(String asin, DownloadQuality quality) in /home/runner/work/AudibleApi/AudibleApi/AudibleApi/Api.Download.cs:line 123
   at FileLiberator.DownloadDecryptBook.downloadAudiobookAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadDecryptBook.cs:line 106
   at FileLiberator.DownloadDecryptBook.ProcessAsync(LibraryBook libraryBook) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\DownloadDecryptBook.cs:line 56
   at FileLiberator.Processable.ProcessSingleAsync(LibraryBook libraryBook, Boolean validate) in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\FileLiberator\Processable.cs:line 53
   at LibationAvalonia.ViewModels.ProcessBookViewModel.ProcessOneAsync() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2022\Libation\Source\LibationAvalonia\ViewModels\ProcessBookViewModel.cs:line 130
 {"ExceptionDetail":{"HResult":-2146233088,"Message":"Content License denied for asin: [B005GFQ5WQ]","Source":"AudibleApi","TargetSite":"Void MoveNext()","RequestUri":null,"JsonMessage":"{\"license_denial_reasons\":[{\"message\":\"Asin [B005GFQ5WQ] is not eligible for AYCL\",\"rejectionReason\":\"ContentEligibility\",\"validationType\":\"AYCL\"},{\"message\":\"Ownership: User [A3A1OA237FOZFK] does not has Ownership rights for asin [B005GFQ5WQ].\",\"rejectionReason\":\"RequesterEligibility\",\"validationType\":\"Ownership\"},{\"message\":\"Since ClientId is null, skipping client rights validation.AAAClientId[ApolloEnv:AudibleApiExternalRouterService/NA/ACLS/Prod], does not has access to asin[B005GFQ5WQ].\",\"rejectionReason\":\"RequesterEligibility\",\"validationType\":\"Client\"},{\"message\":\"Customer [A3A1OA237FOZFK] is not part of any plans.\",\"rejectionReason\":\"RequesterEligibility\",\"validationType\":\"Membership\"}]}","Type":"AudibleApi.ValidationErrorException"}}2022-08-21 16:20:26.681 -05:00 [ERR] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_1(System.Object, System.String)) ERROR. All books have not been processed. Most recent book: processing failed
 {}2022-08-21 16:20:26.901 -05:00 [INF] (at LibationAvalonia.LogMe+<>c.<.ctor>b__9_0(System.Object, System.String)) Automated backup: Download Pdf Step, Completed: [B005GFQ5WQ] The Count of Monte Cristo
 {}2022-08-21 16:20:40.221 -05:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration))

**Comment by rmcrackan** [comment]
Sorry about this crash. By the way, I haven't forgotten you -- I've been out of town for almost 2 weeks. Now that I'm back I'm slowly working my way through my backlog.

You can find your log files by going to Settings and clicking 'Open log folder'. It'd be nice to see but you've given a lot of good info here so it may not be strictly necessary. I'll let you know more when I have a chance to work on this bug.

Thank you for your patience.

**Comment by rmcrackan** [comment]
Thank you again for your patience. I don't have any books which can perfectly replicate your problem but I gave it my best attempt. Please let me know whether pre-release [v8.4.4](https://github.com/rmcrackan/Libation/releases/tag/v8.4.4) solves your issue.

**Comment by rmcrackan** [comment]
8.4.4 is now a full release so I'm going to close this issue. If you are still having this problem, reply here and I can re-open it for further investigation.

**Comment by rest230** [comment]
Hi, i installed the new version, but have problem with download audiobook, i can post the image for error https://prnt.sc/xCq6ZCfbbS7t

**Comment by rmcrackan** [comment]
@rest230 Can you attach your log file?

**Comment by rest230** [comment]
Yes, the log:

08/09/2022 1:56:34	Download & Decrypt Step, Begin: [B0BCGRYDNG] Las redes de poder en España
08/09/2022 1:56:34	Download & Decrypt Step, Completed: [B0BCGRYDNG] Las redes de poder en España
08/09/2022 1:56:34	Download & Decrypt
08/09/2022 1:56:34	ERROR. All books have not been processed. Most recent book: processing failed
08/09/2022 1:56:34	ERROR: Content License denied for asin: [B0BCGRYDNG]
08/09/2022 2:09:47	Download & Decrypt Step, Begin: [B0BCGV1N6D] Recupera tu poder: Libera tu mente y tu cuerpo y vive tu propia vida
08/09/2022 2:09:47	Download & Decrypt Step, Completed: [B0BCGV1N6D] Recupera tu poder: Libera tu mente y tu cuerpo y vive tu propia vida
08/09/2022 2:09:47	Download & Decrypt
08/09/2022 2:09:47	ERROR. All books have not been processed. Most recent book: processing failed
08/09/2022 2:09:47	ERROR: Content License denied for asin: [B0BCGV1N6D]
08/09/2022 2:10:06	Download & Decrypt Step, Begin: [B0BB3FGP78] La niña que todo lo quería saber: La curiosidad: claves para una vida más inteligente y feliz
08/09/2022 2:10:06	Download & Decrypt Step, Completed: [B0BB3FGP78] La niña que todo lo quería saber: La curiosidad: claves para una vida más inteligente y feliz
08/09/2022 2:10:06	Download & Decrypt
08/09/2022 2:10:06	ERROR. All books have not been processed. Most recent book: processing failed
08/09/2022 2:10:06	ERROR: Content License denied for asin: [B0BB3FGP78]
08/09/2022 2:10:11	Download & Decrypt Step, Begin: [B08WCJF8DN] Una Vida Titán
08/09/2022 2:10:12	Download & Decrypt Step, Completed: [B08WCJF8DN] Una Vida Titán
08/09/2022 2:10:12	Download & Decrypt
08/09/2022 2:10:12	ERROR. All books have not been processed. Most recent book: processing failed
08/09/2022 2:10:12	ERROR: Content License denied for asin: [B08WCJF8DN]
08/09/2022 2:10:15	Error. Skip: [B08WCJF8DN] Una Vida Titán
08/09/2022 2:38:26	Download & Decrypt Step, Begin: [B0881Y75YZ] Estoy aprendiendo el alemán: Escucha. Repite. Habla.
08/09/2022 2:38:27	Download & Decrypt Step, Completed: [B0881Y75YZ] Estoy aprendiendo el alemán: Escucha. Repite. Habla.
08/09/2022 2:38:27	Download Pdf Step, Begin: [B0881Y75YZ] Estoy aprendiendo el alemán: Escucha. Repite. Habla.
08/09/2022 2:38:27	Download & Decrypt
08/09/2022 2:38:27	ERROR. All books have not been processed. Most recent book: processing failed
08/09/2022 2:38:27	ERROR: Content License denied for asin: [B0881Y75YZ]
08/09/2022 2:38:27	Download Pdf Step, Completed: [B0881Y75YZ] Estoy aprendiendo el alemán: Escucha. Repite. Habla.
08/09/2022 2:38:27	Error downloading PDF. See log for details. Error summary: Content License denied for asin: [B0881Y75YZ]

**Comment by mkb79** [comment]
Some users of my `audible-cli` package have the same issues. You can read [here](https://github.com/mkb79/audible-cli/issues/118) more. It seams that Audible/Amazon has a rate limit now for AYCL titles.

**Comment by rmcrackan** [comment]
@mkb79 Good catch, thank you. It looks like those limits reset after 12-24 hours. This aligns with my experience also.

@rest230 Please try this tomorrow and let me know if it's still an error. That will tell us if it is this same problem or something else.

**Comment by tdguchi** [comment]
@rmcrackan im the user that reported the limit, today, after more than 24h im not able to download or stream even with official app. stay tuned to the issue in audible-cli as im reporting there

**Comment by mkb79** [comment]
@rmcrackan 
You can implement a check for the `benefit_id`. The value is `AYCL` for items which are not purchased and be part of AYCL. So you can make a switch for users, to hide these items if they reached their limit. Purchased items should not be affected by this limit (hopefully)!
