### ISSUE TITLE
<year> tag in Settings > Download/Decrypt

### ISSUE THREAD

**Issue by RandmTask** [rmcrackan/Libation#367]
When naming the file, would be great if we could have a <year> tag also.

At the moment, I need to go in to the tag to check what year it was then manually rename the file.

**Comment by bilbags** [comment]
I was just perusing the messages to see if someone had suggested this enhancement, as I would like to be able to have a tag for year in the name. As far as original release vs. release year of an audiobook, I think we have to go with the latter; and yes, I would find that very useful.

**Comment by rmcrackan** [comment]
> Would like to have this option for folder naming as well as file naming.

Agreed. If this gets added for filename, it will also be added for folders.

**Comment by CharlieRussel** [comment]
Agreed re: Audible release year. Mostly the original book release year isn't terribly interesting wrt to what's in my audio book library. What distinguishes one audio book from another is often the Audible release date.

**Comment by rmcrackan** [comment]
Included in the new (v8.5)[https://github.com/rmcrackan/Libation/releases/tag/v8.5.0]

**Comment by bilbags** [comment]
Thanks for this update!! Working like a champ - I really appreciate it.
