### ISSUE TITLE
NFO file creator 

### ISSUE THREAD

**Issue by JustinFourie** [rmcrackan/Libation#369]
Hi the application no longer creates NFO files . I keep my files on my pc and it often easier to read the nfo and know what the book is about . Could this feature be returned please . With an option to turn it on and off so we dont impact other users .

**Comment by rmcrackan** [comment]
The previous per-book NFO files were migrated into 'exports' which has all of this info in one file. You can export in several formats incl. Excel.

Sorry, maintaining the code for individual NFO files started to get more trouble than they were worth, especially once we had full-library exports. There are some unexpected 'gotchas' that made them a pain to create.

**Comment by JustinFourie** [comment]
> The previous per-book NFO files were migrated into 'exports' which has all of this info in one file. You can export in several formats incl. Excel.
> 
> Sorry, maintaining the code for individual NFO files started to get more trouble than they were worth, especially once we had full-library exports. There are some unexpected 'gotchas' that made them a pain to create.

Ok thanks  I will check out the Export function one file might work better for me . Thank you for all your work .

**Comment by rmcrackan** [comment]
Thank you for your understanding :)
