### ISSUE TITLE
Libation appears to not run/execute

### ISSUE THREAD

**Issue by Sbackus65** [rmcrackan/Libation#371]
**Describe the bug**
When I double click on Libation, or I right click and select open, nothing happens.

**To Reproduce**
Set Libation to download all audible books in library.  When the hard drive is full, it will stop working.  After moving the downloaded books, rebooting, etc. libation will not start.

**Expected behavior**

**Screenshots**

**Platform**

Windows 10 Pro

**Log Files**
Attach your Libation log file here.
[Log202209_004.log](https://github.com/rmcrackan/Libation/files/9586754/Log202209_004.log)

**Comment by rmcrackan** [comment]
Sorry about this. Thank you for your log file. It looks like it's having trouble reading your accounts settings file. Maybe that file is corrupted. In the folder where your log file lives, delete `AccountsSettings.json` . Hopefully this will fix the issue. You'll just need to re-add your account(s). Please let me know if this helps.

**Comment by White-Fox-VA** [comment]
I seem to only have a folder called es within the main folder, is there somewhere else I should look?, I have the program in a folder on my desktop btw.

**Comment by rmcrackan** [comment]
It should be in the same folder where you found the log file.

**Comment by White-Fox-VA** [comment]
I'm a noob and also not Sbackus65, I don't know where the log file is either, sorry.

**Comment by rmcrackan** [comment]
@Sbackus65 "When the hard drive is full, it will stop working" -- somehow I missed this part. If resources are maxed out, Libation will act weird. This can also happen if you run out of memory. I'm not sure how to mitigate either situation.

@White-Fox-VA D'oh, Mea culpa. If you're on Windows, go into your `C:\Users\<user>` folder and open `Libation`. The log file is in there.

**Comment by White-Fox-VA** [comment]
Like a charm! Thank you!, I'll probably makes some hardlinks to bundle everything more closely together.

**Comment by rmcrackan** [comment]
@White-Fox-VA -- you can also go into the folder where Libation.exe lives and open appsettings.json . You can tell it to use anywhere for that directory and move the existing folder to your new location. Remember to escape back-slashes in json.

**Comment by Sbackus65** [comment]
Hi rmcrackan!  I deleted AccountSettings.json, re-logged in, and also changed to use a (much larger) external hard drive.  I have had no problems since. :-) I have just installed on Ubuntu and am going to try on there for a while.

A suggestion would be to allow converting a single file from M4B to MP3, rather than a whole library all or nothing...

Thank you for this awesome tool!

**Comment by rmcrackan** [comment]
Hooray. I'm glad it works now. Thanks for checking back in.

RE mp3: good suggestion. For now, if you just want 1 as mp3, it's probably easiest to: change your settings to mp3, set that one book to 'not downloaded' (use the details and tags button on row's right), download it (click its red stop-light), and revert your settings back to m4b. It's a mouthful but it should go pretty fast for 1-offs.
