### ISSUE TITLE
Browse the entire audible catalog

### ISSUE THREAD

**Issue by ekt-** [rmcrackan/Libation#374]
Is there a public api that allows you to browse the entire audible catalog? I'm not talking about your library, but all existing books. I find the app and the website quite useless in terms of search. 

I'm not even sure if this feature should be in libation (so feel free to close this as soon as you read it), but I'm asking here because there are experts on the subject.

**Comment by rmcrackan** [comment]
This isn't a goal for Libation. I'll be happy to direct you to some resources.

I keep all of my AudibleAPI code in a separate [github repo](https://github.com/rmcrackan/AudibleApi) and [nuget package](https://www.nuget.org/packages/AudibleApi) so people can write their own code against it if they wish. This is all C#/.NET code.

I like to think of Libation as the best program in its field, but as far as just specializing in the actual audible api, literally no one is as good as @mkb79 . You can write code directly against his [python audible api](https://github.com/mkb79/Audible) or use his [python command line interface](https://github.com/mkb79/audible-cli) without coding. He started to make a webpage interface but those efforts appear to be on hiatus.

Everything mentioned here is free and open source.

**Comment by ekt-** [comment]
hei thanks! if I understand correctly, both @mkb79 and yours audible api are what I'm searching for.  yes I agree specialized too ls (like libation) should do one thing and doit the best they can, without trying to be a "swiss army knife"
