### ISSUE TITLE
Manage previously downloaded books

### ISSUE THREAD

**Issue by sarg3nt** [rmcrackan/Libation#376]
I used Libation a while back to download most of my Audio Books from Audible but  lost the config when I rebuilt my computer.  Now, several month later I'm trying to use it again to catch up with new books and have tried to configure it several different way, starting over each time.  It's pointing at the directory my saved books are in for storage but does not seem to see them.  It says I need to download all of the books again.  Is there a way to have it scan the target folder and sync things up?  Am I missing a setting somewhere?  Is this a new feature request?

**Describe the solution you'd like**
I'd like for libation to not just download books blindly, but to also manage them.  I.e. be intelligent about matching library books to the folder.  
This should also work for audio books not downloaded by Libation and are not from Audible.  
It should be able to find any missing meta data, cover art etc. and apply it
It should be able to re-name / rearrange the target folders books if settings change 
Bonus: It should be able to match the folder structure the AudioBookshelf expects: https://www.audiobookshelf.org/docs#book-title-folder

**Describe alternatives you've considered**
I'm going to start looking for another "management" app that can help with updating and maintaining metadata and folder structure as described above

**Additional context**
My goal is to use the previously mentioned AudioBookshelf server / app to have access to my AudioBook library offline from Audible and enable sharing it with my family without having to log them into my Audible account.  One of the key features I want to get working in AudioBookshelf is the ability to view by series which the Audible app can't do (really guys?!?!)  I have 250 unread books and a lot of that is due to the difficulty in viewing easily by author / series, etc. (I know you can view by author in Audible, but the interface is terrible)

**Comment by rmcrackan** [comment]
Sorry, at present Libation does not have the goal of being a full audio file management system and does not have plans to support non-audible books. I actually try to facilitate the idea that if you want to download your audible books with Libation then move them, it's allowed and Libation will remember that you've already downloaded them. Also, you can re-set a downloaded book to 'not downloaded' so you can download again, whether or not the files are already there. This has allowed some users to download their library as single-file books, set all to not-downloaded, and download again with the option for them all to be split into files by chapter.

Regarding finding ones you've already downloaded: I don't have bandwidth to do it anytime soon but I like the idea of adding this feature.

In the short term, you can avoid re-downloading by setting all to 'downloaded' and set just the new ones to 'not downloaded'. You can change this book-by-book by pressing a row's right hand tags and details button. You can set this in bulk via the "Visible Books" menu at top.

Regarding the audiobookshelf folder format: Libation can't help you re-organize the books and directories after the fact. However, before download you can create templates to say how to download books. Settings \> Download and Decrypt tab \> Custom file naming . If this folder structure is your end goal, you may just want to edit these templates and re-download your entire audible library so as many as possible can fit this format. I recommend starting with just a book or 2 before doing the whole library -- to test that the templates are what you expect. To download just 1 book, click the book's red stoplight.
