### ISSUE TITLE
Unable to scanlibrary

### ISSUE THREAD

**Issue by SpookyXU** [rmcrackan/Libation#377]
[_Log202209.log](https://github.com/rmcrackan/Libation/files/9666916/_Log202209.log)
[Log202209.log](https://github.com/rmcrackan/Libation/files/9666917/Log202209.log)

**Comment by SpookyXU** [comment]
Just noticed something looking at the logs... would it matter that the application is not installed on the C drive? I noticed there's references to C drive in the error log...

**Comment by rmcrackan** [comment]
It doesn't appear to be hard drive related. These look like audible is actively shutting you down. Using the same wifi connection, can you download books on your phone?

```
 ---> System.Net.Http.HttpRequestException: The SSL connection could not be established, see inner exception.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
```

**Comment by SpookyXU** [comment]
Actually computer is hard wired, not using wifi. I can download books using the audiblesync application though on same connection.

**Comment by SpookyXU** [comment]
I guess it has something to do with the network connection maybe..

**Comment by rmcrackan** [comment]
It's acting that way. Is there a way to test the computer on another connection? Can you go through a vpn? Get on wifi?

**Comment by SpookyXU** [comment]
May have to try a different computer. It's weird that it will download the audiblesync stuff.

**Comment by rmcrackan** [comment]
I agree; that's super weird. I'd have thought it'd be all or nothing.

**Comment by SpookyXU** [comment]
It appears to be the connection.. I tried it on a different network connection and it went through. not sure how to resolve that, if at all. Thanks for following up so quickly.

**Comment by rmcrackan** [comment]
That sucks. I'm going to close this issue since there seems to be nothing Libation can do about the matter. If you reply here, I'll still be notified of your messages. Good luck!
