### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by Knowexactlynothing** [rmcrackan/Libation#378]
**Describe the bug**
Error message on startup

**To Reproduce**
Open Libation.exe

**Expected behavior**
Libation is amazing, so happy that my audiobooks have been liberated, but it stopped working today.

**Screenshots**

**Platform**

Windows 11

**Log Files**
Attach your Libation log file here.
[_Log202209.log](https://github.com/rmcrackan/Libation/files/9701441/_Log202209.log)
[Log202209.log](https://github.com/rmcrackan/Libation/files/9701442/Log202209.log)
[Log202210.log](https://github.com/rmcrackan/Libation/files/9701443/Log202210.log)

**Comment by Knowexactlynothing** [comment]
That did the trick.  Thank you so much!
    On Monday, October 3, 2022 at 08:06:11 PM CDT, rmcrackan ***@***.***> wrote:  
 
 


Sorry about this! Thank you for your logs. Please open the folder with your logs in it and delete the FileLocations.json -- it appears to be corrupted. Let me know if this fixes your issue.

**Comment by rmcrackan** [comment]
You're welcome
