### ISSUE TITLE
How do I mark as already downloaded in bulk? Is it possible?

### ISSUE THREAD

**Issue by ThoughtfulSenpai** [rmcrackan/Libation#379]
Excuse me. I would kindly appreciate if someone could tell m**e how I can mark in bulk books as already downloaded.** clicking them one by one is not an option. I want to select them and ignore them from now on, they have been liberated. I had them download on a previous version of Libation, then updated and moved them to my Prologue app and they all appear as not liberated. Which is not cool

Kindly excuse me for my basic question. Im sure I'm missing something in plain sight but haven't spotted it.

**Comment by rmcrackan** [comment]
No problem. Go to "Visible Books" then "Set 'Downloaded' status". This will set all books to the setting you choose.

If you used the search bar, this will apply the new status only to the books which are searched for.
