### ISSUE TITLE
Positive test cases on Libation 5.0.0

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#38]
I'm trying to put the new Libation through its paces, and sometimes ... everything just works :) . This "issue" will serve to document where I deliberately tried something that in principle COULD go wrong, and instead it all worked. Yay!

I have two Audible accounts, one currently unpaid and the other active (1-year membership). I also have an active Kindle Unlimited account and am sharing a "Partner" account with someone else (yes, I tested Audible sharing through that too).

**Comment by wtanksleyjr** [comment]
Kindle Unlimited with free narration: it works.
Audible Plus: it works.
Amazon Family Sharing (only between two adults): it works.

So, wow, GREAT start.

**Comment by wtanksleyjr** [comment]
Computer shuts down in the middle of a download: it works. (Details: it pops up an abort/retry/ignore, you click "retry", no problem.)

**Comment by rmcrackan** [comment]
Thanks! These are encouraging to read

**Comment by rmcrackan** [comment]
I'm going to close this 'issue' so I can more easily browse actual outstanding issues. Feel free to add to this post though. I'll still get notifications.
