### ISSUE TITLE
Tagging Series as part of fix metadata?

### ISSUE THREAD

**Issue by CallMeTerdFerguson** [rmcrackan/Libation#382]
**Is your feature request related to a problem? Please describe.**
First, thanks for this incredible project. It's amazing! I've started looking at it to back up my stuff and I've noticed one thing that I'm possibly just missing how to do or possibly isn't implemented. When looking at the grid view on the main page, Libation seems to have access to certain metadata, in my case specifically _series_, that it is getting from somewhere but don't end up in the id3 tags. The app I'm using will automatically sort series based on this if available, and I see that Libation has access and can use it for filtering, sorting and it can be used in the template for file naming/location. Is it currently possible or would it be possible to add the option to export certain pieces of metadata like series into the custom id3 tags as part of the metadata cleanup or some other new option? Ultimately, I'd like for an id3 _series_ tag to contain the value that is currently displayed in the _Series_ field on the grid view when I liberate.

**Describe the solution you'd like**
Is it currently possible or would it be possible to add the option to export certain pieces of metadata like series into the custom id3 tags as part of the metadata cleanup or some other new option?

**Describe alternatives you've considered**
I'm currently having to manually edit the tags, which is doable, but not ideal.

**Additional context**

**Comment by rmcrackan** [comment]
Libation gets series during the library import then it's stored in the database. "Export" will show you all of this in Excel and other formats.

I currently shy away from tag editing because that way madness lies -- the nuance of id3 tags is ugly and a half. It's becoming a popular request though. Maybe it's time to reconsider.
