### ISSUE TITLE
Exceeded Maximum Attempts error 

### ISSUE THREAD

**Issue by WanderingLizard** [rmcrackan/Libation#383]
Hello. I just downloaded the latest release of Liberation (8.4.6, win classic and win chardonay), but receive the "exceeded maximum attempts"" error message similar to an issue that was reported in August 2021 (log attached). My account is through the Canadian site audible.ca.

Thanks for your help

[Log202210.log](https://github.com/rmcrackan/Libation/files/9792754/Log202210.log)

**Comment by rmcrackan** [comment]
So sorry about this. Does it help if you delete your account on Libation, Save, Re-enter your account, then Scan? My hope is this will force you to do a fresh login. Note: removing your account will not alter or delete anything else.

**Comment by WanderingLizard** [comment]
Thanks for getting back to me so quickly. I tried what you suggested, and it got me a little further but I ended up stuck in a captcha loop. But I then tried logging in through my web browser (which I didn't realize was an option initially) and managed to connect my account. So I'm good to go! Thanks for your help.

**Comment by rmcrackan** [comment]
I have no idea why that captcha loop sometimes happens. I'm glad you found the other login and are all set. Thanks for the update
