### ISSUE TITLE
Adding Year to Template options

### ISSUE THREAD

**Issue by bilbags** [rmcrackan/Libation#384]
**Is your feature request related to a problem? Please describe.**
Not a problem 

**Describe the solution you'd like**
I love the ability to customize naming for files & folders. I would like to have a <year> option for the full release year of an audiobook (e.g., 2022).

**Describe alternatives you've considered**
None

**Additional context**
I realize Audible lists the full date of release (e.g., 10-20-22), but I would like to pull just the year in full, if possible. However, if it could only pull the date as Audible lists it, that's better than pulling nothing. :)  

If this is no possible at all, I would love for Libation to have a release date column (like the purchase date column). Thanks!

**Comment by rmcrackan** [comment]
Duplicate of #367

**Comment by bilbags** [comment]
I'm sorry for duplicating - kinda embarrassing!

**Comment by rmcrackan** [comment]
No worries. There's a lot to keep up with here. Even I thought: did I see this before or did I imagine that?

**Comment by rmcrackan** [comment]
Your duplicate was apparently the poke I needed. New version coming soon with this option :)
