### ISSUE TITLE
Captcha issues

### ISSUE THREAD

**Issue by 1andy981** [rmcrackan/Libation#387]
**Describe the bug**
No matter how many times I, correctly, input the captcha and password it just sends me back to capctha again.  driving me insane, tryinbg to dind old version before this captcha started.  cannot sync account.  any way to switch it off?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
I’m so sorry about this. I have no control over those and have no idea why this occasionally happens to users. Sometimes this fixes itself in about a day. You can side-step password and Captcha entirely by clicking the “or click here” link on the password box. It will guide you through logging in using the web site.

**Comment by 1andy981** [comment]
thank you!

**Comment by 1andy981** [comment]
thanks anyway, guess I need to leave it.  even the broswer version takes me to a cache.  no worries, it was amazing software when I was able to use it, guess they have changed something.

thanks!

**Comment by rmcrackan** [comment]
How about this: same thing with the 'or click here' link, but copy and paste that huge link into your browser's private mode. If you're on windows, right click on the browser's icon. Chrome calls this Incognito. Firefox: Private. Edge: InPrivate.

**Comment by 1andy981** [comment]
Perfect!  Worked!  Thank you!  I missed this so much!  Spend a fortune in audible but hate streaming and want to use my Walkman so it's perfect.  Thanks

**Comment by rmcrackan** [comment]
That’s so great to hear. I didn’t want to disappoint a fan over an annoying login snafu
