### ISSUE TITLE
The latest version for some reason has a captcha that doesn't work.  It is blurry and even when I enter the letters and numbers correctly it doesn't work.

### ISSUE THREAD

**Issue by celt123** [rmcrackan/Libation#388]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
I’m so sorry about this. I have no control over those -- they come from amazon/audible. Unfortunately I also have no idea why this occasionally happens to some users. Sometimes this fixes itself in about a day.

You can side-step password and Captcha entirely by clicking the “or click here” link on the password box. It will guide you through logging into Libation using the web site. If you're already logged into audible on that browser, you can copy and paste that huge link into your browser's private mode. If you're on windows, right click on the browser's icon. Chrome calls this Incognito. Firefox: Private. Edge: InPrivate.
