### ISSUE TITLE
Resume download if it gets interrupted.

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#39]
I think we should add the ability to resume downloading/decrypting the fire if it get interrupted (e.g. by unexpected restart, network error, or application error). Audible supports http Ranges so it's possible, and I actually don't think this would be too hard to do with a modified NetworkFileAbstraction.

**Comment by rmcrackan** [comment]
Cool. I didn't know they supported that.

**Comment by rmcrackan** [comment]
Wow, that was less of a code change than I thought there would be for this.
