### ISSUE TITLE
Estimate Time Remaining for Process Queue

### ISSUE THREAD

**Issue by nogwater** [rmcrackan/Libation#391]
I have over 100 audiobooks to download and process.  I'd like to know how long it will take to finish.

Libation displays an ETA for each queue item, but not for the queue as a whole.  It does show percent complete and running time.  For example, I'm currently at 14% and 30:21.  Using this information, we can estimate the time remaining at:
```
30:21 = 1821 seconds
1821 sec / 14% = 130 sec / percent
100 - 14 = 86% remaining
86% * 130 sec / percent = 10790 sec = about 180 minutes or 3 hours.
```

If possible, it would probably be better to measure the rate during the past minute or 5 minutes in case the network speed changes.  The software probably has access to more detailed information internally that could be used to make the above more accurate.  For example if the percent displayed is based on the number of books, not the total length of the books or size, it could get skewed if you've downloaded several small books and have one big one remaining.

Thanks!

**Comment by nogwater** [comment]
I noticed that clearing the finished items updates the %, but not the elapsed time.  That makes sense, but it would mess up the above example math.

**Comment by rmcrackan** [comment]
I'll be honest, time remaining is simply a tough nut to crack. Before implementing it, me, another programmer, and another user spent a ton of time exploring options. All of them have their up sides and down sides. Although your ideas do look good, I don't see us spending more time rehashing this particular issue. Thanks for the detailed input. I don't want to sound ungrateful.
