### ISSUE TITLE
Incorrect Format for Set Downloaded Status Confirmation Message

### ISSUE THREAD

**Issue by nogwater** [rmcrackan/Libation#392]
The confirmation string is rendered as: `Are you sure you want to replace downloaded status in 0?`
The `0` should be a format placeholder that says something like "this 1 book".

**To Reproduce**

1. Import one or more books into your library.
2. From the Visible Books menu, click Set 'Downloaded' Status...
3. Click Save

**Expected behavior**
The confirmation message box should include the number of books you are applying the status to.

**Screenshots**
![image](https://user-images.githubusercontent.com/350287/201548159-e93f0e00-9932-4353-96b5-9807767de535.png)

**Platform**
Tested on: Windows 10

**Log Files**
N/A

The code for this is in setDownloadedToolStripMenuItem_Click on line 105 https://github.com/rmcrackan/Libation/blob/34bad7a53dce164c33dd9ffd791dbec2b3c9593e/Source/LibationWinForms/Form1.VisibleBooks.cs#L105

```$"Are you sure you want to replace downloaded status in {0}?",```
It shouldn't have the leading `$`.  This is causing it to interpolate a `0` into the string instead of sending `{0} on to ShowConfirmationDialog to populate with the appropriate text.

With this change:
![image](https://user-images.githubusercontent.com/350287/201548290-d1d9a194-e4ff-4353-805b-9ac4a29f5dbb.png)

The confirmation is rendered correctly:
![image](https://user-images.githubusercontent.com/350287/201548317-0a20fa10-753e-4bdf-9dea-e014e81364b4.png)

It looks like the same bug is in: `removeToolStripMenuItem_Click`.

**Comment by rmcrackan** [comment]
Whoops -- great catch. Thank you!

[Fixed](https://github.com/rmcrackan/Libation/commit/bce44b6f6d81a8a7a5397f33b32303e2f2d5a36a). It will be included in the next release

Thanks again 😃
