### ISSUE TITLE
Option to choose to update version immediately instead of waiting for manual close?

### ISSUE THREAD

**Issue by badbob001** [rmcrackan/Libation#393]
Currently, if there is an update, one has wait for the app to finish starting and then manually close the app to trigger the update. But there are is often a big delay before the app is done with its startup process, even if auto-update of library is disabled. And I'm afraid if I just close the app immediately, I will corrupt something.

So why not at the update notification, offer an option to do the update immediately and skip all the app startup processes?

**Comment by rmcrackan** [comment]
That should be fine -- you won't corrupt anything.

We can't update immediately. The app has to be closed or the update can't succeed in overwriting the app's files which are currently in use.

**Comment by badbob001** [comment]
I meant that when clicking 'update now', the app will automatically close to let the update start. But if you're saying that simply closing it immediately at startup is ok, even when the library is being updated, then that's fine.

**Comment by rmcrackan** [comment]
Ah, thanks for the explanation. I think I understand now. You should be fine.

Most of what I would call "updating the library" is technically getting everything ready for updating the library. Then the one step at the end of all that which *actually* updates the library is fast and should be resilient anyway.
