### ISSUE TITLE
Set Download Status failed

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#394]
I was doing some library cleanup and trying to re-download some books that hadn't ended up where I wanted them. First batch went well, but then when I tried to change the download status of Margaret Attwood's "Alias Grace", it failed. It looks like it didn't like a symbolic link that I'd created to put an earlier book into a second series (Tanya Huff's "An Ancient Peace" which is both 6th in her Confederation series and first in her Peacekeeper series. ) I suspect I can work around the failure by using a junction rather than a symlink, but honestly, I'd prefer to avoid unnecessary junctions. 
[Log202211.log](https://github.com/rmcrackan/Libation/files/10006459/Log202211.log)

**Comment by rmcrackan** [comment]
I agree it shouldn't give you an error. I'm hesitant to follow them like normal directories though since they can cause infinite loops and then I have to check for those which is non-trivial.

Would it suffice to gracefully not follow them and also not recurse into them?

**Comment by CharlieRussel** [comment]
Yeah, I understand the issues. How about doing something like PowerShell does with: 

`Get-ChildItem "D:\AudibleBooks\Tanya Huff" -Depth 2`

This limits the amount of recursion you have to deal with. And if it's in PowerShell, it should be in .NET. However, if that's not something fairly trivial to implement, then just gracefully don't follow them.

**Comment by rmcrackan** [comment]
It's often used in *my* actual recursion. I'll get a listing, then follow each item in that listing, etc. When it's a standard file tree I can recurse infinitely and in practice I can't get myself into trouble. Once links are involved all bets are off.

**Comment by CharlieRussel** [comment]
Fair enough. Then just handle it gracefully and I'll deal with it on my end. (And yeah, I'm a PowerShell geek at heart!)

**Comment by rmcrackan** [comment]
Ideally how soon would you like to see this fix go live?

**Comment by CharlieRussel** [comment]
No rush. I worked around the current issue by the brute force solution of creating the directories and then copying the full files. Fit it in when you have the need to do a new build. Certainly don't need a build just for this. Most people don't do this sort of thing anyway. (However, you're MUCH more likely to run into it on a Linux machine. :) )

**Comment by rmcrackan** [comment]
Thanks. The code is in place so it'll definitely go out with the next version. Thanks for finding this.
