### ISSUE TITLE
Check Downloaded Files

### ISSUE THREAD

**Issue by nogwater** [rmcrackan/Libation#396]
**Is your feature request related to a problem? Please describe.**
I'd like to re-check my local file system for downloaded files.  My specific case was because I'd deleted some of the local files but Libation had them marked as downloaded in the database so it didn't offer to re-download them.  It could be useful to go the other way too -- when starting a clean database but pointing to an existing download folder, Libation should be able to recognize that at least some of the library already exists and doesn't need to be downloaded.

**Describe the solution you'd like**
Add a new menu item to the Visible Books menu called "Check downloaded..."  When clicked, this would check all of the visible books and update their status.  Here's some sample code that does for books that the database says exists.  It checks that the expected file path can be found and if it can't marks the books as not downloaded/liberated.  After running marking all of my books as downloaded and then running this menu item, I'm able to see which books need to be redownloaded, and queue them for download.

![menu item](https://user-images.githubusercontent.com/350287/201550264-8b131193-e566-4a3f-9db7-c18cd2d13831.png)

```
private void checkDownloadedToolStripMenuItem_Click(object sender, EventArgs e)
{
    var visibleLibraryBooks = productsDisplay.GetVisible();
    foreach (var libraryBook in visibleLibraryBooks)
    {
        if (libraryBook.Book.Audio_Exists())
        {
            var filePath = AudibleFileStorage.Audio.GetPath(libraryBook.Book.AudibleProductId);
            if (filePath == null)
            {
                libraryBook.Book.UserDefinedItem.BookStatus = LiberatedStatus.NotLiberated;
                LibraryCommands.UpdateUserDefinedItem(libraryBook.Book);
            }
        }
    }
}
```

The above code could be enhanced to check books that are currently marked as not downloaded and mark them as downloaded if they are, and it could (I think) update any PDF status.

My above sample code doesn't prompt the user with a confirm.  I don't know if it should.  Also, I believe it runs in the UI thread which would probably be bad for huge libraries.

pixil98 requested that this feature be available in the CLI, which makes sense to me.

**Describe alternatives you've considered**
I could imagine making this part of the scan system (it sounds like it used to work like that), or as a new menu item under Import that would check all books.

**Additional context**
https://github.com/rmcrackan/Libation/issues/130#issuecomment-1312853961

**Comment by rmcrackan** [comment]
[Per comment in # 130](https://github.com/rmcrackan/Libation/issues/130#issuecomment-1314503107) -- also add to CLI

**Comment by rmcrackan** [comment]
This will be in the next version. 

@pixil98 -- it will also be in the [CLI](https://github.com/rmcrackan/Libation/blob/master/Documentation/Advanced.md#command-line-interface)

* UI: Visible Books \> Set 'Downloaded' status automatically. Visible books. Prompts before saving changes
* CLI: Full library. No prompt

v8.6 will be live as soon as I can figure out what I'm doing wrong with the new version Release workflow.

**Comment by rmcrackan** [comment]
Edit: it's live -- https://github.com/rmcrackan/Libation/releases/tag/v8.6.0
