### ISSUE TITLE
M4B files

### ISSUE THREAD

**Issue by chieftwidgit** [rmcrackan/Libation#397]
I have begun to see an increase in the number of M4B files, created by Libation, that can not be converted using other programs.  I normally use inAudible to create chapterized MP3 files.  I always get an error saying it can't extract a good audio file, but has previously converted.  Now for an increasing number of files it will hang indefinitely.  I have tried AVS, but it gives a red 'x' and refuses to convert.  There are programs that will convert but they are horribly slow with these files.

**Comment by chieftwidgit** [comment]
Would it be possible to have an option to leave the key in the .AAX files you save.  By removing the key and replacing with zeros it makes it impossible to convert.

**Comment by rmcrackan** [comment]
> Would it be possible to have an option to leave the key in the .AAX files you save

If you select the option to save the aax file, Libation doesn't alter it at all. Regarding the top concern, I'm afraid I'm not sure what you're asking. Can you give a specific example of the audible book, how you are using Libation, and which audio software is failing to process the file that Libation created?

**Comment by rmcrackan** [comment]
This thread has been stale for a while so I'm going to close it. Reply here if more action is needed and I can re-open it
