### ISSUE TITLE
Export complete chapter titles

### ISSUE THREAD

**Issue by k-trahan** [rmcrackan/Libation#4]
Is it possible to have the .m4b and the .cue files contain the true chapter titles instead of the generic "Chapter 01" in the .cue or the book name in the .m4b itself?

Now that Audible has real chapter titles available in their players for a lot/most? audiobooks, it's a step backward to go back to generic 01, 02, etc. chapter titles that don't end up lining up with the actual chapters due to acknowledgements and prologues, for example.

Absolutely love the application! If preserving chapter titles is possible it would make it that much better.

**Comment by rmcrackan** [comment]
I plan to look into this in the future. To be honest though, my backlog is huge and there's only 1 of me so no promises even on a vague time frame. Thanks for the feedback. I'm glad it's been useful to you

**Comment by rmcrackan** [comment]
Today code was added to do this. A new download will be available by end of week.
