### ISSUE TITLE
Manual Audible sign in - only allows amazon sign in

### ISSUE THREAD

**Issue by imrobtown** [rmcrackan/Libation#400]
I get the infinite captcha loop so I used the 'log in with your browser' link.
The page brought up allows only an amazon account login.   I have an old pre-amazon username/password account.    With a normal audible loign I can select to use the username/password.  

I tried logging into my account 
![Screenshot 2022-11-18 at 16-08-58 Audible Sign In](https://user-images.githubusercontent.com/18663664/202802874-3bd9d9c3-1206-4048-9ffc-8036079a8d10.png)
using username/password,  then selecting library and copying that URL to libation,  it did not work.

**Comment by imrobtown** [comment]
![Screenshot 2022-11-18 at 16-11-01 Amazon Sign In](https://user-images.githubusercontent.com/18663664/202803145-9af40584-1c3f-4eae-bb5d-1ca50529c48c.png)

**Comment by rmcrackan** [comment]
Darn. Since I can't get a pre-amazon account, these have been very difficult to test.

When you set up that account in Libation, did you select "pre-amazon - us" for the Locale?

**Comment by CharlieRussel** [comment]
That should work.  I used the web workaround for my pre-Amazon account, given that the regular dialogue always gives me an endless captcha loop.

Charlie.
(he/him/his)

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by imrobtown** [comment]
No I didn’t, I’ll try.  I’m away for a week though.  Thanks

**Comment by rmcrackan** [comment]
This thread has been stale for a while so I'm going to close it. Reply here if more action is needed and I can re-open it
