### ISSUE TITLE
Right Click Menu for Stop-Light Icon 

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#406]
**Is your feature request related to a problem? Please describe.**
Currently, no advantage of right-click is taken in the stop-light area, and some key right-click menu options would be a big improvement.

**Describe the solution you'd like**
 I'd LOVE to have a right click on the traffic-light icon give me a menu to let me:
- Set Download status for that book
- Remove from Library
- Remove from Library and Ignore forever
- Open File Location (current behaviour of a regular click on a green light)
- Locate file (ie, let me point to the current file location)

This has come up as I've been trying to clean up my library to take advantage of some of the newer features, and it's currently a royal PITA that would be greatly simplified.

**Describe alternatives you've considered**
current Visible Books menu is  fine, but a real pain as one is working through a whole bunch of changes. 

**Additional context**
This has come up as I've been trying to clean up my library to take advantage of some of the newer features, and it's currently a royal PITA that would be greatly simplified.

**Comment by rmcrackan** [comment]
> Remove from Library and Ignore forever

This doesn't yet exist. Keeping a list of books to ignore is easy. What happens when a book accidentally gets added? Or when someone changes their mind? Now there needs to be a new interface for dealing with these. It'll start as a simple list. Then someone else will want full details. And eventually it will need to be a new way to fully view in the grid. I'm not ready for this slipper slope at the moment.

If you tag books with `hidden` they'll appear in grey. If you use `-[hidden]` in your default and saved searches, they won't be shown. It's an imperfect work-around until we decided to fully implement an ignore-forever feature.

**Comment by CharlieRussel** [comment]
@rmcrackan Yeah, OK, I get it. Though I have some ancient episodes of various podcasts before there WERE podcasts. (ie, radio broadcasts of "Click and Clack", Scientific American, and very ancient episodes of Bob MacDonald's "Quirks and Quarks", etc.) But for now, the workaround is viable, especially since those are all in my old pre-Amazon account which I don't often pull from. So I can workaround it.

**Comment by rmcrackan** [comment]
> Open File Location (current behaviour of a regular click on a green light)

I'm not sold on this one. It's already there as a left click.

**Comment by Mbucari** [comment]
@rmcrackan I found a way to detect modifier keys (ctrl/alt/shift) when opening the context menu. Want to use that?

**Comment by rmcrackan** [comment]
@Mbucari I'd rather just use normal rt-clk. I dislike the lack of discoverability when keys are required.

**Comment by CharlieRussel** [comment]
> > Open File Location (current behaviour of a regular click on a green light)
> 
> I'm not sold on this one. It's already there as a left click.

Mostly this is completeness. Right click and choose from the options. Don’t have to remember which is on the left, which is on the right.

**Comment by CharlieRussel** [comment]
@rmcracken & @Mbucari. I agree that it wouldn’t be as discoverable as is strictly desirable.

Charlie.
(he/him/his)

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by rmcrackan** [comment]
Code is complete. This will be included in the next release after I clean up part of the new publishing process.

**Comment by rmcrackan** [comment]
How would you feel if Remove simply became 'remove forever'? I can't think of too many situations where someone wants to remove something only for now

**Comment by CharlieRussel** [comment]
I'm fine with Remove Forever. What I'm trying to get away from is having it keep trying to add something back to the library that I have NO intention of ever wanting to listen to. There was a period where Audible had "free" episodes of radio shows that are all now well out of date and weren't, frankly, all that interesting in the first place as an Audible thing. And I really don't want to have to go through the annoyance of removing them again and again and again.

**Comment by rmcrackan** [comment]
Done. It will be available in the next version

**Comment by CharlieRussel** [comment]
Well, and as soon as you made that available, I tried it, and without really thinking of the consequences, removed a title I didn't actually want removed. (S.U.E.) What file do I need to edit to add the title back? Really, I shouldn't be allowed to near a computer after 10PM on a holiday.

**Comment by Mbucari** [comment]
Run the "Hangover" program (separate program in the libation program files folder), go to the deleted books tab and check the books to undelete.

**Comment by CharlieRussel** [comment]
Thanks, @Mbucari. And may your holiday season be a good one.

**Comment by CharlieRussel** [comment]
That got it back to where it is in the DB. But it (and several other books) appear to have a corruption of the account -- they show as user@domain|com rather than user@domain.com. So, of course, it won't download them. Is there a simple way to fix this? I've deleted that account and re-added it, and it now shows correctly in the Accounts dialog, but books that have the corrupted account listed will not re-download. I suspect I'm going to need to start over, but I'd rather avoid that with some 2500-3000 books in my 4 accounts. OTOH, if I must, I must.

**Comment by Mbucari** [comment]
@CharlieRussel I'm not sure what caused the problem, but it should be fixable with a query. I'm out of town for the next few days, but I'll get you sorted when I get back if @rmcrackan doesn't fix it first. So if you can wait for a few days, don't delete your db.

**Comment by CharlieRussel** [comment]
@Mbucari No sweat. I've been living with it for a while now, so it can certainly wait.

**Comment by rmcrackan** [comment]
@CharlieRussel So sorry. I can't imagine what could have possibly caused an error like that. Can you zip and email me your db? (Don't post it here where anyone can see it)

**Comment by CharlieRussel** [comment]
Sent you an email with a OneDrive link. (The file itself is >6 Mb. ) But if that's a problem, I'll zip it and resend.

**Comment by rmcrackan** [comment]
Thanks for the database. I don't see any 'removed' books . I also don't see a book titled 's.u.e.'

I do see 800 titles where the username is lower-case L before `com` (4 of which are not downloaded). I don't understand how they ever got in there in the first place. Are they supposed to be on the normal C...e@s...s.com amazon-us account?

**Comment by CharlieRussel** [comment]
S.U.E is Stupid User Error. 🙂 In other words, I shouldn't ought to have done that.

Yes, those books with the lower case "L" are the problem. On my screen, I wasn't sure WHAT character it was, I actually thought it was a bar ("|"), but I couldn't search on them so I knew it wasn't that. Didn't even think of a lowercase L.

I have no idea how they got corrupted to that. Obviously, I would never have been able to download them with that account address in the first place. So yes, that's the problem. When I realized that the account was corrupted, I deleted and re-added the proper @scribes.com us-amazon account. But now they don't match up, of course.

All this came about because I was trying to re-arrange things to take advantage of the newish custom file save abilities of Libation before moving/copying the entire library onto one of my OneDrives to make it accessible from all my various devices. And for backup, of course! But I really wanted to get it rationalized into  <first author>\<if series-><series><-if series>\<if series->#<series#> - <-if series><title short> format, which is kind of how I think of them.

Charlie.
(he, him, his)
________________________________

**Comment by CharlieRussel** [comment]
Oh, and the reason you don't see any removed ones is that @Mbucari pointed me at the hangover program, so I fixed that part.

**Comment by rmcrackan** [comment]
Yup. We're about to use it again. Open Hangover. Database tab. Paste in the command that I emailed you and hit Execute. It will be

`update LibraryBooks set Account = 'YOUR_REAL_EMAIL_HERE' where Account like '%lcom'`

**Comment by CharlieRussel** [comment]
Perfect! And I'm now able to download the book I accidentally removed (Tai-Pan, by James Clavell). And I can now go about my business of re-arranging things. A tip headed your way.
