### ISSUE TITLE
Japan service throwing errors; US working fine

### ISSUE THREAD

**Issue by lobsterbake** [rmcrackan/Libation#408]
Since yesterday, I get an error upon attempting to download any content from Japan account. I've tested using a (different) US account and that is working fine. Let me know if there's anything I can provide in the way of log files to help with troubleshooting. Super helpful application, by the way.

**Comment by lobsterbake** [comment]
Updating with a log file.

I can confirm that I am able to stream titles from my library through a browser from the official website without incident. Ditto for streaming from the standard Audible app (Android version). So in those contexts, my login credentials are recognized. I tried deleting and re-entering my credentials in Libation, and although my login credentials appear to be initially accepted and my library accurately scanned, an error is thrown whenever I try to download an item. As noted in initial post, US service working fine from same instance of Libation (different account).

Many thanks for any advice.
[Log202212_002.log](https://github.com/rmcrackan/Libation/files/10239421/Log202212_002.log)

**Comment by rmcrackan** [comment]
Sorry this is happening. Let's give this a day or 2 to resolve itself. I hope we're experiencing the following:

About 1/2 a year ago, I got a ton of reports from audible US members that stuff like this would happen. All official software would work but not Libation. This would last from a few hours to 1 day then start working again. This pattern repeated intermittently for a few months, always affecting different people and then it would fix itself. I could never reproduce it on my computer. My best guess is that when audible is making changes to their servers or is having too much traffic, then their servers are overloaded and they temporarily route some accounts to secondary servers. I have no knowledge of such servers but presumably their official software would know how to do this. This is just a guess based on the patterns we saw.

Please let me know if this is still a problem this weekend.

@Mbucari -- got a new log if you want to see if it matches your pattern

**Comment by lobsterbake** [comment]
Thanks so much. Will circle back in a few days with an update.

**Comment by lobsterbake** [comment]
@Mbucari Thank you for offering to take a look. Is there a good way for me to get you a verbose log file without posting it publicly here? If the verbose file contains my account ID or other account-specific details, I'd prefer not to post publicly.

**Comment by Mbucari** [comment]
@lobsterbake email it to me at mbucari1@gmail.com

**Comment by lobsterbake** [comment]
@Mbucari Sent. Thank you!

**Comment by Mbucari** [comment]
@lobsterbake I think @rmcrackan is right. This appears to be an outage that affects Libation, but you should be able to access your books through the Audible app and website in the meantime. Give this a day or 2 to resolve itself.

@rmcrackan His error is a new one I've never seen before. Instead of AYCL's rejectionReason being null, the reason is "GenericError" and the message is "Encountered an error. Please try again later". I think this is the same error, but now Audible gives better log information.

```Json
{
   "message":"Encountered an error. Please try again later.",
   "rejectionReason":"GenericError",
   "validationType":"AYCL"
}
```

**Comment by lobsterbake** [comment]
@Mbucari and @rmcrackan -- Thank you both for taking a look. I'll keep an eye on it over the next few days and will let you know if the issue resolves itself.

**Comment by lobsterbake** [comment]
@Mbucari and @rmcrackan -- Seems to have resolved itself, as anticipated. Let me know if it's of any use for me to send another log file, now that it's working. 

For the record, the errors persisted for around 36 hours. And FWIW, the the error messages began after a stretch where I had downloaded a lot of large files in fairly rapid succession (think "Great Courses" lecture series), so I was hitting the server pretty hard. Not sure if that was just coincidence, or if I unwittingly triggered some kind of throttle.

Thanks again for your exceptional responsiveness!

**Comment by rmcrackan** [comment]
Thanks for the follow up. I'm so glad it's working for you again. Thank you also for letting us take a look at your logs.
