### ISSUE TITLE
Login with 'approval' not working

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#41]
Per [here](https://www.reddit.com/r/audible/comments/occ16x/libation_50_harder_better_faster_stronger/h3vfh4n/), there are some audible/amazon 2FA logins which have a step requiring 'approval'. Current implementation does not handle this correctly. I might have a login that this happens to.

**Comment by shokinn** [comment]
If you need help for testing a fix.
I think that error is happening to me since i secured my Amazon account with 2FA.

\* I use Audible Germany.

**Comment by rmcrackan** [comment]
@shokinn Thanks! I was actually just working on this fix. Can you see if my latest version (v5.1.1) fixed it -- https://github.com/rmcrackan/Libation/releases/latest

**Comment by shokinn** [comment]
![grafik](https://user-images.githubusercontent.com/10045300/124830864-c5a71e00-df7a-11eb-9186-0869525e778a.png)

Hey @rmcrackan,
nope same issue as before, I don't get asked for my 2FA code instead it shows the "approval needed" button.

**Comment by rmcrackan** [comment]
Did you check your email? When this step happens, amazon is supposed to send you an email and you have to click approve. Then you press that button in Libation after you approve via the email link.

I'll also add better instructions in Libation.

**Comment by shokinn** [comment]
Nope, no emails for confirmation at all.
Is there a debug mode wich I can launch to provide you logs?

**Comment by rmcrackan** [comment]
[v5.1.3](https://github.com/rmcrackan/Libation/releases/latest) has another attempted bug fix. Try that first.

RE log files: your LibationFiles folder (to find this: Settings > Advanced Settings) contains your log files. Settings.json allows you to set logging to debug. Change LogLevel Default and MinimumLevel to "Debug".

Privacy in logging, ESPECIALLY during authentication, is tricky. I've tried hard to log useful info and also tried to redact personal info. Before you send me a log, my advice is to close Libation, move/delete your log, restart Libation, reproduce the error, and close Libation. Then look over the new log and make sure no sensitive data accidentally got in there.

You can post your log on pastebin and give me the link or email me the file directly (my email is in my [public profile](https://github.com/rmcrackan))

**Comment by shokinn** [comment]
Now I get immediatly an error after I got asked for an captcha.

![grafik](https://user-images.githubusercontent.com/10045300/124954475-672f7d80-e016-11eb-8f3b-4d918d881f88.png)

I also have sent you an email with the logs attached.

**Comment by rmcrackan** [comment]
Thank you so much for the logs. We're getting closer! Please try again with [v5.1.4](https://github.com/rmcrackan/Libation/releases/latest). If this doesn't fix it, please email me the new logs

**Comment by shokinn** [comment]
Just tried 5.1.6.
Looks Awesome.

Thanks for fixing it!

![grafik](https://user-images.githubusercontent.com/10045300/125109745-066e7680-e0e4-11eb-8a4c-1f09b1b4d855.png)

**Comment by rmcrackan** [comment]
:) You're welcome. Thanks for working with me to do so. Enjoy your books!
