### ISSUE TITLE
Pipeline: Use Linux runners

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#410]
The build pipeline is currently using Windows runners to perform the build. If we switch to Linux we gain the benefit of setting Linux and MacOS binaries as executable. They are also significantly faster to setup and run. There are a couple of problems standing in the way of fully implementing them.

* Unit tests fail when run on Linux. The couple I looked at seem to be related to newline handling. If this is the extent of the problems it should be solvable by using `Environment.NewLine`.
* Building Windows versions on Linux runs into problems detailed in https://github.com/dotnet/runtime/issues/3828. For now we can split the build pipeline in half and move the Linux and MacOS builds over to Linux runners.

Part of this change is going to be to use tar.gz files for Linux and MacOS instead of zip files. This will preserve permissions on files.

@rmcrackan - you can assign this to me, I would appreciate some of your time to look at the unit tests.

**Comment by rmcrackan** [comment]
As long as I can still use VS's "Test Explorer" to run tests locally, I have no preferences how they run in devops land. Can you tell me which ones are failing due to newline? I'd like to personally see what I did wrong

**Comment by rmcrackan** [comment]
After you deduce the best way to run these here, I'll look at how easy this is to apply to the supporting repos: [Dinah.Core](https://github.com/rmcrackan/Dinah.Core) , [AudibleApi](https://github.com/rmcrackan/AudibleApi) , [LuceneNet303r2](https://github.com/rmcrackan/LuceneNet303r2) . That's where a lot more unit tests live.

**Comment by pixil98** [comment]
You can view the output of the Unit Test step at https://github.com/pixil98/Libation/actions/runs/3701507387/jobs/6270874053. This shouldn't stop you from using the Test Explorer.

Getting the unit tests to run is pretty easy, I added the following step to the build workflows:

```
      - name: Unit test
        working-directory: ./Source
        run: dotnet test
```

**Comment by Mbucari** [comment]
@pixil98 Thanks for adding the tests!

@rmcrackan The linux tests are failing because of the drive letter colon. I'm currently working on character replacements, so I'll try to fix the tests.

**Comment by Mbucari** [comment]
@rmcrackan It looks like the removeInvalidWhitespace_regex isn't working on linux.

**Comment by pixil98** [comment]
As part of the pipeline rewrite, I'm pulling the build version from AppScaffolding.csproj. Should I add a check when tagging a release to make sure that the tagged version matches the version in the project?

**Comment by rmcrackan** [comment]
@pixil98 Sure. My new temp publish process is:

* update and push appscaffolding version
* run my old release tool to ensure git checkins are complete and collect commit comments since last publish
* manually use cmd line git to create and push a new tag which matches appscaffolding version
* after your yaml builds the draft, edit with my comments

Soon I was planning to change the 3rd step to be a push-button equivalent, driven by the appscaffolding version

**Comment by rmcrackan** [comment]
The newline tests are fixed. There are also 31 failed tests for file paths. That's going to take more time. It's not a simple slash replace. Also not sure why unix paths are getting converted to `C?`. It's trying to fix the windows `C:` but these path sanitizers should be leaving the 1st 2 characters alone as a shortcut to [1] not deal with that 1 allowable colon on windows [2] for UNC paths beginning with the one acceptable case of double slashes.

**Comment by Mbucari** [comment]
@rmcrackan I spent last night fixing all of the tests on linux. They're pushed my repo right now. I think maybe I'll just do a PR this morning with what I have so far and not worry about finishing everything else I was going to do.

**Comment by rmcrackan** [comment]
@pixil98 If we're including unit tests, I assume they should run on all master-branch checkins (CI) but not on the CD pipeline which publishes. Thoughts?

**Comment by pixil98** [comment]
I had that thought as well. If you tag a release with broken unit tests, you probably want it to build anyway (assuming it will build). Currently they run in both locations because I added them to the build pipeline that I'm reusing in both cases. I'll add a parameter to the build workflow that disables the unit tests so they can be skipped from the release process..

**Comment by pixil98** [comment]
@rmcrackan - One last question and the PR should be ready. It looks like the version in AppScaffolding.csproj is always 4 digits but the release is often 3 digits. Since I'm now pulling the version from it, how does that translate into a release version? It would be awkward if the release is tagged as v8.6.4 but the builds are v8.6.4.0.

**Comment by rmcrackan** [comment]
Release versions will always be a new 1-3 digit version. Sometimes I increment part 4 as I'm doing incremental changes. When I do releases, I ignore part 4 and omit final `.0` -- eg: v1.0.2.0 => v1.0.2 , v1.2.0.1 => v1.2 , v1.0.0.1 => v1

**Comment by pixil98** [comment]
Okay, I'm going to use the full 4 digit number for builds for pull requests and merges to main. For releases I'll override it to the version number in the tag name. That way I don't have to do some fancy regexing to try and calculate the version and you can have more flexibility. It does mean I won't be able to do any sanity checking that the version matches the tag name.

**Comment by rmcrackan** [comment]
If you look at the Settings \> About, it actually keeps all 4 parts as the official version -- as found in the appscaffolding. I think that it's more user-friendly for the zip and title displayed on the version-download page to not end in the dot-zeros. Hopefully I'll just remember to manually change them in the version download title when I turn off the draft flag

**Comment by Mbucari** [comment]
@pixil98 Really outstanding work. Thank you.

You said these build are executable on linux and macOS, so what does a user need to do to get Libation up and running? Are the instruction ([Linux](https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnLinux.md) and [macOS](https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md)) still correct except for `chmod`?

**Comment by pixil98** [comment]
This won't change anything about the instructions other than removing the need to `chmod` the executables. It shouldn't be too hard to have a special linux build workflow that would build a deb package. It looks like it be hosted out of github (I haven't tried this yet). https://assafmo.github.io/2019/05/02/ppa-repo-hosted-on-github.html

**Comment by Mbucari** [comment]
@rmcrackan When you announce v9.0 on reddit, can you add a request for help creating a .deb linux package?
