### ISSUE TITLE
MacOS error: Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.

### ISSUE THREAD

**Issue by 2600box** [rmcrackan/Libation#415]
Hello,

Apologies in advance if this is a known error, but this is what I get after allowing unsigned code to run on MacOS Ventura 13.1:

```
➜  Libation.8.6.3-macos-chardonnay ./Libation
Unhandled exception. System.BadImageFormatException: An attempt was made to load a program with an incorrect format.
 (0x8007000B)
[1]    8848 abort      ./Libation
```

**Comment by rmcrackan** [comment]
Thanks for reporting this. I'm going to close this and link to it from #327 which is where we're keeping track of the mac issues. A few other people have seen this also, search `BadImageFormatException` on that page and take a look at the subsequent replies. We have a new build process soon which we hope will address this and some other cross-platform issues.
