### ISSUE TITLE
Check for Updates with Download Link

### ISSUE THREAD

**Issue by lycannon** [rmcrackan/Libation#421]
Please add a version check on startup with a menu option (under Settings) to view the download page of the new version? Perhaps add a manual Check for Updates menu option under settings.

**Comment by rmcrackan** [comment]
Interesting, please elaborate. In what way would you like this feature to differ from the current auto-update option which runs on startup?

**Comment by lycannon** [comment]
It's easy to forget that there is an auto-update as there isn't any kind of notification / status message letting the user know they are on the latest version. Now that you mention it, I do remember getting the notification on a new release; but I imagine that people would want to wait until any current sync / conversions complete before updating.

Ha- Just started the app to look at the UI and got the notification for an update.

What I envision is updating the About dialog with additional information, see attached image.

![QR7vYyaWh4](https://user-images.githubusercontent.com/2049556/208820770-5b7a80a0-cbe0-4053-abb9-d681103f939b.png)

**Comment by lycannon** [comment]
The update link would re-run the auto-updater.
The GitHub link would open the default system browser to the repo

I also just shared the app with a friend- took me a bit to track down the repo for the download link.

**Comment by rmcrackan** [comment]
> people would want to wait until any current sync / conversions complete before updating

The updater doesn't run until you close the app

> attached image

Nice mock-up. Thanks!

> I also just shared the app with a friend- took me a bit to track down the repo for the download link

I'm open to suggestions. On the main page it has:

```
Libation: Liberate your Library
Download Libation
```

I also created [getlibation.com](https://getlibation.com). I need to do more to advertise it though. At the top, it has a tab for Download

**Comment by rmcrackan** [comment]
Included in latest: [v8.8.1](https://github.com/rmcrackan/Libation/releases/latest)
