### ISSUE TITLE
update libation on windows doesn't allow spaces.

### ISSUE THREAD

**Issue by pepijnmm** [rmcrackan/Libation#423]
**Describe the bug**
When I got the update message and tried to update it gave the error that you can see in the screenshots.
My username exists op two parts for example"user account" but it only got the user part. so it seems to me that there should be "" around the {zipFile}(and also the other paths in that command) or at least when there is a space in the path.

**To Reproduce**

1. Get the update message
that will try to run the following(only the arguments seems to be the problem so everything after zipextractor.exe):
c:\users\user account\appdata\local\temp\zipextractor.exe --input c:\users\user account\appdata\local\temp\tmp52a0.tmp --output e:\program files (x86)\libation.8.6.3-win-chardonnay --executable e:\program files (x86)\libation.8.6.3-win-chardonnay\libation.exe

**Expected behavior**
I tested to see if the " would solve it and it indeed did when I ran it manually:
"c:\users\user account\appdata\local\temp\zipextractor.exe" --input "c:\users\user account\appdata\local\temp\tmp52a0.tmp" --output "e:\program files (x86)\libation.8.6.3-win-chardonnay" --executable "e:\program files (x86)\libation.8.6.3-win-chardonnay\libation.exe"

**Screenshots**
![image](https://user-images.githubusercontent.com/3217184/209124255-4eab691f-95dc-4811-8e85-4debc08889b3.png)
![image](https://user-images.githubusercontent.com/3217184/209125342-08ab5638-80c9-4369-be8d-376e2c2a6382.png)

**Platform**
Windows 10

**Log Files**
See screenshot.

**Comment by rmcrackan** [comment]
Superlative bug tracking!! How did you manage to track down the specific calls to zipextractor.exe?

There is currently [no solution](https://github.com/ravibpatel/AutoUpdater.NET/issues/323) to this in the updater library we use. I really hope we don't have to write our own but we might. I [opened a ticket](https://github.com/ravibpatel/AutoUpdater.NET/issues/595) . I'll keep you updated as I learn more.

Thank you for your detailed work.

**Comment by pepijnmm** [comment]
@rmcrackan Thank you for the fast fix!
"How did you manage to track down the specific calls to zipextractor.exe?"
I wanted to find out what was being sent/if I could reproduce it in cmd as I indeed thought it was the quotes. I saw the files got saved in GetTempPath and when I went there I found a zipextractor.log which told me the input(that's where the screenshot is from)
