### ISSUE TITLE
Searched a book series and this happened

### ISSUE THREAD

**Issue by Priofire** [rmcrackan/Libation#424]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
[Log202212.log](https://github.com/rmcrackan/Libation/files/10290791/Log202212.log)

**Comment by Mbucari** [comment]
@rmcrackan Time to leave the wife with your racist uncle!

**Comment by rmcrackan** [comment]
@Priofire Very strange. Did this happen only once? Or more than once?

@Mbucari not helpful lol

**Comment by Priofire** [comment]
@rmcrackan I tried again today and cannot actually replicate the issue anymore, but it happened twice when I first started using Libaation yesterday. Apologies that I can't be more helpful.

From what I remember, the first time I searched 'Jim Butcher' and pressed Enter, then a mass of errors just came flooding in.

The second time, I was scrolling down (no searching/filtering). The moment my scrollwheel clicked over and the page moved, the errors came piling in.

**Comment by rmcrackan** [comment]
Jeez, that definitely should not happen. Since it's not happening anymore, it's difficult to guess. I'm going to close this bug report. If it happens again, you can reply here with a new error log. I'll get alerted and I can reopen it.

Merry Christmas!
