### ISSUE TITLE
Trying to open libation results in extreme lag and eventually full lockup of machine, resolved by reboot only

### ISSUE THREAD

**Issue by omnei** [rmcrackan/Libation#425]
Upgrading from 8.4.3 chardonnay to most recent

Now upon trying to load libation, whole computer freezes, lags terribly, and then inevitably locks up entirely and is only resolved with a reboot. Im not sure where any sort of logs for this might be stored, if any, since libation never even opens. Is this purely just due to it being on a windows 7, a very old operating system?

Upon looking, i cannot find any sort of log file for this.

**Comment by Mbucari** [comment]
By default, logs are stored in C:\Users\[you]\Libation

However, I suspect that what you're experiencing is not Libation bug but the result of upgrade Libation's runtime. Version 8.4.3 ran on .NET 6 [which supports Windows 7](https://github.com/dotnet/core/blob/main/release-notes/6.0/supported-os.md) . The most recent Libation version runs on .NET 7 [which only supports Windows 10 and above](https://github.com/dotnet/core/blob/main/release-notes/7.0/supported-os.md).

**Comment by omnei** [comment]
> 

at first i thought it was due to win 7. but, it eventually loaded and has been working fine now. So. im not sure. i think it honestly just decided to take a long time to load. I redownloaded it as well. So maybe my original download was messed up
