### ISSUE TITLE
Mac Beta version URL input tool?

### ISSUE THREAD

**Issue by lelediaz** [rmcrackan/Libation#428]
Hey,
I just wanted to say that I really love this program and it´s the only one working so far without having to pay for it.
I know you do this in your free time and I really have to thank you for this create little tool I just found out about it.
Anyway, I did not had any issues so far and everything is working fine. My only problem with other programs was that everytime it downloaded a file it was in AAX and not in aax like the ones you download from audible directly and can open them in iBooks. 
I still don´t know why this happened with OpenAudible, since its a well known tool but it was useless for me.
I really hope that you will keep this program alive for long as possible and its also working great with the newest 13.01 ventura macOS version, so I still haven´t faced any issues with your great Libation tool. 

Anyway, is there are way to like input just a URL of a audiobook from audible and then download it via the URL? 
Like meant for not purchased books and also not from the plus catalogue but for the ones you have to pay for with credits. Would be cool to know any information about that

**Comment by rmcrackan** [comment]
Thanks for the feedback.

Regarding file types, be default, Libation downloads your books as m4b files -- which is an unencrypted audiobook format you can use anywhere. If you still want to keep the original aax/aaxc files, there's a setting on the 'audio file options' tab for 'retain the aax file'.

Libation can download all books in your audible library including audible plus titles. It's not possible to download books you don't own.
