### ISSUE TITLE
MacOS Captcha Window

### ISSUE THREAD

**Issue by perrinaz** [rmcrackan/Libation#434]
When using Libation to log into the Audible/Amazon account, if a captcha window pops up, the window itself is too small to see the whole image.  This is on a Mac running Ventura (v13).  I was able to work-around by using the browser to login, and now that I'm logged in, I don't know if I could reproduce the error.

**Comment by Mbucari** [comment]
I'm going to level with you, neither I nor @rmcrackan own a mac. I had a mac VM up and running to test Libation, but I couldn't install Visual Studio on it so I couldn't even debug on macOS. That Libation works at all on Mac is something of a minor miracle. So all that is to say, I don't think I can help with that, and please temper your expectations for Libation Mac support.

**Comment by rmcrackan** [comment]
@Mbucari Very very true :( When we release version 9, I want to take mac and linux out of beta. That implies full support though which we obviously are unable to provide in the typical sense. What wording could we use to say 'it mostly works but sorry about the rough edges cause I dunno how to fix them'

**Comment by Mbucari** [comment]
>  What wording could we use to say 'it mostly works but sorry about the rough edges cause I dunno how to fix them'

Good question. I don't think even I would be able to immediately tell if a bug I was experiencing was something affecting all platforms or just mine. How can we expect users to know the difference?

**Comment by rmcrackan** [comment]
@perrinaz Sorry man. You've got a perfectly valid complaint. The truth is -- I don't know what I can do about it so I'm going to close this. I'm glad you were able to log in. Let me know if other parts of Libation are too out of whack for you to use on Mac.

We're doing our best to make this program accessible to a platform we really can't even test on. Sorry you're getting the short end of the stick.
