### ISSUE TITLE
Feature Request -- Bandwidth Caps

### ISSUE THREAD

**Issue by bigtrucker26** [rmcrackan/Libation#435]
First, Let me THANK YOU for working on this program, and continually trying to improve it.

I am running into a slight issue, and I hope you would be willing to implement a solution.

The Libation program is trying to download at the maximum internet speed, and is basically blocking everything else on my network trying to sate it's thirst for my audiobooks.  While I appreciate this thirst, it is causing me a issue as it works.
Many download and streaming programs include the ability to limit how much bandwidth it may consume, allowing those of us with limited internet connections to maintain other data flows at the same time (both on the same machine, or on multiple machines).

So, I hereby request the ability to set limits (or cap the data rate) of the downloads (and uploads), to ensure it doesn't interfere with other internet traffic.  I leave it to you, to decide if you want to implement a solution with time based limits, or just a single limit (either is fine with me, but matters to some).

Again, Thank You for creating and maintaining this program, it is allowing me to manage and properly utilize a Large library of audiobooks (I'm a trucker, and I chew through them pretty quick), especially since audible won't make the necessary tweaks to their own app to allow proper categorization and organization..., let alone, integrate other sourced books into that system....

**Comment by rmcrackan** [comment]
Flattery will get you everywhere :) I hadn't considered that people might want to throttle their downloads.

@Mbucari this sounds more like the kind of details you delve into. How big of an ask is this?

**Comment by Mbucari** [comment]
@rmcrackan Just so happens I was just looking into this. I don't think it will be too bad to just add a timer into the download loop, but I'm not sure how to wire it to the UI. The downloader is pretty far down the stack., so that's a lot of layers to pass controls through. Settings are one thing because you can just pass them down on init, but speed limits need to be updatable at any time. Part of me just wants to use a static variable that's checked on each download loop iteration and be done with it. You cool with that?

**Comment by rmcrackan** [comment]
Tell me more -- where would the static var live?

**Comment by Mbucari** [comment]
> where would the static var live?

As a member of `NetworkFileStream`. I'd set it directly from the UI code when a download is started and again any time the user changes the setting.

**Comment by rmcrackan** [comment]
Sure why not.

I once had ambitions of giving each setting a 'has changed' event. Well, wouldn't we want the before and after value? What about a 'before changed' event. I guess they each need a new shared 'setting' object and a way to compose with them and refactor all of Libation to use then and UGGG! who's got that kind of time? Screw it -- the current way has worked for over 5 years so if it ain't broke... 😄

**Comment by Mbucari** [comment]
>  Screw it

Damn right lol. This is too small of an addition to justify rethinking Libation's entire workflow.

**Comment by bigtrucker26** [comment]
If I may, oh, great programmers...
Even if it took a restart of the program to take effect, it would be useful to add a KB/MB cap...  but, what if it only took effect when the next in que initiated???
I don't think there's any reason it HAS to be on the fly changing... In my case, I would love to set a 10MB d and 2MB u limit.. but, others have different connections... or other network loads...

**Comment by rmcrackan** [comment]
@bigtrucker26 No worries -- what @Mbucari suggested will be very flexible. It involves violating a best practice among software developers but, frank-ly, that's how the sausage is made. Get it? frank... sausage... (I'll be here all week folks. Try the waitress and tip your veal. G'NIGHT!)

**Comment by bigtrucker26** [comment]
@rmcrackan I wasn't worried, I just didn't want to make you folks break something or go through massive hurdles....
I'll be happy with a single speed limit set, others, prefer to let things go more wild while they sleep, so, that's where scheduling would come in, if implemented....
And Thank You Both for being so willing to put this into effect!!!

**Comment by rmcrackan** [comment]
Scheduling is possible but infinitely more ambitious. Time, date, calendar, etc are basically a nightmare. Every user has one more example for what would work better for them. Each request is reasonable and not terribly hard to accommodate. In aggregate, it's a never ending cycle of adding yet one more thing -- it's a hole with no bottom. Then once it's really flexible and configurable for tons of nuanced options, someone says: this is too complicated. And they have a point.

I imagine that if we do this feature, it will just be a setting and it will be up to the user to update it as desired.

**Comment by bigtrucker26** [comment]
Yes, customization is a never ending rabbit hole...
I was only thinking of giving them 2 times of day x-y one speed set and y-x another speed set...
Like I said though, a single speed setting set is all I need to keep it from taking my entire connection....  (I run libation on a dedicated media server, but it was blocking my main pc while it was dl'ing...)
And I am Very greatful for the willingness to add data rate limits....  Especially since you both seemed ready and willing to do so as soon as asked, I sure wasn't expecting that...
Have Fun, Thank You,
I'll sign off the conversation now, as I don't think there's anything else I can add productive to the efforts ahead....
Best wishes, and may the New Year bring you more happiness!!

**Comment by rmcrackan** [comment]
I'm going to keep this open until the feature is officially pulled in. Which should be soon because @Mbucari is the man

**Comment by rmcrackan** [comment]
Code is complete. This feature will be available in the next version. Which will be whenever my family can stop getting sick, injured, etc. 2023 is not my favorite year so far.

**Comment by Mbucari** [comment]
> 2023 is not my favorite year so far.

2023 has some big shoes to fill if it wants to compete for The Worst Year!
