### ISSUE TITLE
Liberate audible files that are in a local folder

### ISSUE THREAD

**Issue by able58** [rmcrackan/Libation#437]
**Describe the solution you'd like**
I have many audible files, from a previous account, that were downloaded to a local folder.  It would be great if I could point Liberate to that folder and have them converted.   

thanks

**Comment by rmcrackan** [comment]
This isn't possible with the format audible has been using for the last few years ("AAXC"). The decrypt keys are tied directly to account access. Having the file isn't enough.

If they're much older files, you might have some luck with [inAudible](https://github.com/rmcrackan/inAudible). In the older style of encryption (AAX), it was possible to discover the decrypt key and unlock the file.
