### ISSUE TITLE
CAPTCHA when signing into an account has no accessible alternative

### ISSUE THREAD

**Issue by mehgcap** [rmcrackan/Libation#44]
When Libation prompts for an account password, it next asks for the user to fill in the response to a CAPTCHA. This screen's edit field and submit button are accessible to screen readers, but the test itself is not. There is no audio alternative, or way to skip this step entirely. Is it possible to proceed without completing the CAPTCHA? If not, could an accessible option be added?

**Comment by rmcrackan** [comment]
This is a great idea. I'll look into the technical details of how amazon provides this option.

**Comment by rmcrackan** [comment]
I'm still trying to figure this out. Some users are shown an option to get SMS, phone call, or something else. I'm not sure why some people get this option screen and others do not

**Comment by rmcrackan** [comment]
@mehgcap I can't make either of my amazon/audible accounts give me an audio option. If you want to explore this deeper, [email me](https://github.com/rmcrackan) and we can discuss ways for you to help
