### ISSUE TITLE
Unable to install Libation (Windows 11)

### ISSUE THREAD

**Issue by Rimmons** [rmcrackan/Libation#441]
When opening the Libation application, an error window appears with the following text:

Exception has been thrown by the target of an invocation.

   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.PropertyInfo.GetValue(Object obj)
   at LibationFileManager.Configuration.SetNonString(Object newValue, String propertyName) in D:\a\Libation\Libation\Source\LibationFileManager\Configuration.PersistentSettings.cs:line 28
   at AppScaffolding.LibationScaffolding.PopulateMissingConfigValues(Configuration config) in D:\a\Libation\Libation\Source\AppScaffolding\LibationScaffolding.cs:line 169
   at LibationWinForms.Program.RunInstaller(Configuration config) in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 147
   at LibationWinForms.Program.Main() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 41

1. Extract zip to Libation folder on desktop.
2. Run as administrator Libation application from folder
3 See error

Windows 11

**Comment by Mbucari** [comment]
@rmcrackan I'm on it.

**Comment by Mbucari** [comment]
@rmcrackan 

To fix this, you need to add a default constructor to [EquatableDictionary](https://github.com/rmcrackan/Libation/blob/master/Source/LibationFileManager/Configuration.PropertyChange.cs)

Then in Configuration, replace the Dictionary properties with this:

```C#
[Description("A Dictionary of GridView data property names and bool indicating its column's visibility in ProductsGrid")]
public Dictionary<string, bool> GridColumnsVisibilities { get => GetNonString<EquatableDictionary<string, bool>>()?.Clone() ?? new(); set => SetNonString(value); }

[Description("A Dictionary of GridView data property names and int indicating its column's display index in ProductsGrid")]
public Dictionary<string, int> GridColumnsDisplayIndices { get => GetNonString<EquatableDictionary<string, int>>()?.Clone() ?? new(); set => SetNonString(value); }

[Description("A Dictionary of GridView data property names and int indicating its column's width in ProductsGrid")]
public Dictionary<string, int> GridColumnsWidths { get => GetNonString<EquatableDictionary<string, int>>()?.Clone() ?? new(); set => SetNonString(value); }
```

Sorry, I forgot to test with an empty setting. Doh!

**Comment by Rimmons** [comment]
Wow thank you so much for the swift response and fix!

Do you happen to have a noob tutorial at all? I'm struggling to find the place to put this code in.

Thank you again!

**Comment by Mbucari** [comment]
@Rimmons Sorry for the misunderstanding. That code if for @rmcrackan (Libation's owner) to fix this bug it's a bug I introduced, but it's his project so only he can fix it and re-release it.

**Comment by Rimmons** [comment]
@Mbucari Apologies, this is my first time using GitHub, I have no idea what I'm doing, I'm just trying to download my audiobooks haha

**Comment by Mbucari** [comment]
@Rimmons No worries. In the meantime, try downloading version 8.7

https://github.com/rmcrackan/Libation/releases/tag/v8.7.0

**Comment by Rimmons** [comment]
@Mbucari Well that seemed to work! Don't ask me why or how, but I'm in now!

**Comment by rmcrackan** [comment]
Building the fixed version now

@Rimmons Thank you for your patience

@Mbucari and thank You for your quick response

**Comment by rmcrackan** [comment]
w00h00 -- New version [v8.8.2](https://github.com/rmcrackan/Libation/releases/latest) is live. @Mbucari can you verify the fix worked?

**Comment by Mbucari** [comment]
@rmcrackan I just downloaded v8.8.2 and ran it with empty Libation folder. It works.

**Comment by Rimmons** [comment]
@Mbucari @rmcrackan All good on this end. Cheers, you're both absolute legends!

**Comment by rmcrackan** [comment]
Perfect. Thanks again for the quick turn-around

**Comment by Mbucari** [comment]
@rmcrackan Really sorry about that. Such a rookie mistake. I'm honestly embarrassed I didn't do a final test with a fresh install.

**Comment by rmcrackan** [comment]
A rookie mistake to be sure, but also a rookie mistake we've all made many times. We caught it quickly though and the user was gracious so: no blood, no foul
