### ISSUE TITLE
Error Importing library

### ISSUE THREAD

**Issue by khstjohn** [rmcrackan/Libation#448]
**Describe the bug**
I am unable to scan my audible library and instead receive an error importing library notification. 
Authenticate.LoadSessionCookiesAsync exceeded maximum attempts. MaxLoadSessionCookiesTrips=6

**Platform**

[e.g. Windows 10

**Log Files**
Attach your Libation log file here.

[Log202301_001.log](https://github.com/rmcrackan/Libation/files/10421622/Log202301_001.log)
[Log202301_001.log](https://github.com/rmcrackan/Libation/files/10421632/Log202301_001.log)
[Log202301.log](https://github.com/rmcrackan/Libation/files/10421633/Log202301.log)
[Log202301.log](https://github.com/rmcrackan/Libation/files/10421623/Log202301.log)

**Comment by rmcrackan** [comment]
Sorry! Somehow this slipped past my radar. Are you still seeing this error?

**Comment by khstjohn** [comment]
Thank you for getting back to me.

 

Yes, I am still receiving those error messages, but only on selected titles, seven now in total. I confirmed that those selections were present and playable through the audible app, but Libation was unable to convert them and returned the error message I previously sent.

 

Thank you for looking into this,

 

Kevin

**Comment by rmcrackan** [comment]
Can you try again and attach your latest log file so I can see which 7 and what their errors are?

**Comment by rmcrackan** [comment]
This bug seems to have gone cold. If you're still having issues, please attach a new log and I'll reopen.
