### ISSUE TITLE
Error while trying to process this book

### ISSUE THREAD

**Issue by khstjohn** [rmcrackan/Libation#449]
**Describe the bug**
Error while trying to process this book message on all books in my audible library that have yet to be downloaded.

Scan library
Id books that have not been downloaded
Click on the book's "Red Stop Light"
I then receive the error message.

**Expected behavior**

**Screenshots**
![image](https://user-images.githubusercontent.com/122758486/212576015-72f259c6-bdeb-464a-a6ce-77a15f4d699a.png)

**Platform**
Windows 10, 

**Log Files**
[Log202301_001.log](https://github.com/rmcrackan/Libation/files/10421654/Log202301_001.log)

**Comment by Mbucari** [comment]
Both of your issues are network error. Your computer can't find www.amazon.com, so Libation can't log in and register itself as an Audible device. Are you running through a VPN?

**Comment by rmcrackan** [comment]
This ticket appears to have gone cold. I will happily re-open it if the conversation continues.
