### ISSUE TITLE
Wrong duration time on iPod/Itunes

### ISSUE THREAD

**Issue by manicspike** [rmcrackan/Libation#452]
**Describe the bug**
The wrong duration time is shown when putting an audiobook chapter onto iPod/iTunes. Each chapter is listed on iPod/Itunes as full length of audiobook. So I have a chapter that is 5 hours long for example.

**To Reproduce**
Place a chapter onto iPod. Look at duration time.

**Expected behavior**
I expect it to show the correct time.

**Comment by Mbucari** [comment]
Is this an m4b file or an mp3?

Which audiobook is it? (Audible link).

**Comment by manicspike** [comment]
M4b file. I've tried with a few books so far. 

I actually have the .cue file box checked, and there's no .cue file included with the chapters. Could that be why?

**Comment by Mbucari** [comment]
Very peculiar. I know you said it happens with a lot of books, but can you please reproduce the error on your machine and then post the log files here?

**Comment by manicspike** [comment]
Okay, here is a log file from the book I just tried out. 
[Log202301.log](https://github.com/rmcrackan/Libation/files/10442324/Log202301.log)

**Comment by Mbucari** [comment]
Aha! The problem if you're splitting your audiobook into multiple files by chapter. When you do that, no cue is created and the files don't contain chapter metadata because the files **_are_** the chapters. Try not splitting by chapter and putting a single big m4b file on your ipod. I don't own an ipod, but I'd bet good money it will recognize the chapter metadata and provide you with a nice UI for navigating by chapter.

**Comment by Mbucari** [comment]
For good measure, I installed itunes and imported split audiobooks. I see what you mean. Each file is shown as the full length of the audiobook. This is an apple thing. I'm not sure why it does it, but I can assure you there's nothing in the files that claims they're as long as itunes reports.

**Comment by manicspike** [comment]
It's something to try I suppose. It's definitely an Apple thing. Right now I could just change the Start/End time of each file in iTunes/iPod but it is time consuming

**Comment by rmcrackan** [comment]
@Mbucari hmm, I hadn't considered that. Big consideration: when you add m4b files to an iphone, it goes to the book app rather than the music app -- which to me is the correct place. I don't know where m4a goes

**Comment by manicspike** [comment]
Yes, an m4b automatically goes to the book app. An m4a automatically goes to the music section. You can switch it over to either section you want though. I switched the m4b file over to the music section in hopes that it would fix the duration problem. I guess they have to be m4a files then.

**Comment by Mbucari** [comment]
@manicspike Have you tried a single m4b file yet? I imported mine into itunes and it works great.

**Comment by manicspike** [comment]
Yes, a single m4b file works.

**Comment by rmcrackan** [comment]
This is what I suspected for m4a vs m4b. I think we should leave it as m4b since popular software makes the assumption that a = audio and b = book

**Comment by rmcrackan** [comment]
This one fell off the radar. Where does it stand?

**Comment by manicspike** [comment]
I downloaded the latest version last night, and I still had chapters coming up at 10 hours long for example. Putting an entire book on is fine, but I don't have the space sometimes. I would like to know just how much time I have left on a chapter.
     On Thursday, February 16, 2023, 04:52:08 AM PST, rmcrackan ***@***.***> wrote:  
 
 


This one fell off the radar. Where does it stand?

**Comment by Mbucari** [comment]
@rmcrackan This is an itunes issue. Like I said before, there's nothing in these m4b files to suggest to any media reader that they're longer than they are.

**Comment by manicspike** [comment]
Yeah, the files are all correct, they just don't show up properly on Apple devices. If there's nothing you can do, I understand. Thank you for all the work you're doing on the program.
     On Thursday, February 16, 2023, 05:23:23 PM PST, Mbucari ***@***.***> wrote:  
 
 


@rmcrackan This is an itunes issue. Like I said before, there's nothing in these m4b files to suggest to any media reader that they're longer than they are.

**Comment by rmcrackan** [comment]
@Mbucari That sucks. It sounds like we've followed this path as far as it can go. Much thanks for all your research into this.
