### ISSUE TITLE
One of the last two updates has disabled custom file naming

### ISSUE THREAD

**Issue by PaulBrad25** [rmcrackan/Libation#453]
**Describe the bug**
I updated Libation yesterday, after restarting it then told me to update again immediately, after doing both and restarting again I downloaded another dozen audio books and they all ended up in the same subfolder called 

(0000.00) ＜series＞ ＜series#＞꞉ ＜title short＞ [Audio] {＜year＞ ＜narrator＞} - ＜author＞

which is the folder format I defined in settings, however they aren't extracting the info from the file and inserting it into the folder name

**Screenshots**

**Platform**

Windows 10

**Log Files**
Attach your Libation log file here.

![Capture](https://user-images.githubusercontent.com/122999941/213224146-fd24ef8a-6af1-48a7-8ea3-85efc1afad95.JPG)
![Capture2](https://user-images.githubusercontent.com/122999941/213224164-ea629830-9671-418c-9741-b5b6b47861bf.JPG)
![Capture3](https://user-images.githubusercontent.com/122999941/213224170-5fe1ba19-1b62-416e-90b1-b19200b7d826.JPG)
[Log202301.log](https://github.com/rmcrackan/Libation/files/10448298/Log202301.log)

Excellent work on the program in general folks, it's greatly appreciated.

**Comment by Mbucari** [comment]
@rmcrackan I'm on it.

**Comment by Mbucari** [comment]
@PaulBrad25 Sorry about that. We added some more checks to naming templates to ensure file extensions don't get deleted. Unfortunately, your template is being incorrectly identified as a file with (0000 and everything after the dot the file extension.

I made a fix for this, but until that's released I'd suggest no periods in the templates.

**Comment by rmcrackan** [comment]
The fix is complete. I'll publish a new version in the morning. I'm tired right now and don't want to screw it up

**Comment by PaulBrad25** [comment]
> 

Ah ok, if you're developing new functionality, then now I know the cause I can work around it on my end if you prefer.

I store book files by original publication date in author folders which means I enter (0000.00) as a space holder and then manually enter the year and month from Goodreads/Wikipedia/etc. , as audible books don't have accurate publication dates. I don't *have* to have a placeholder. 

Or maybe it's possible to make it work like excel where anything inside '' '' is ignored as a function and just shows as text?

**Comment by Mbucari** [comment]
@PaulBrad25 None of that should be an issue after @rmcrackan pushes a new update tomorrow. Your (0000.00) will work again, and templates should be more resilient in general.

**Comment by rmcrackan** [comment]
Yeah, this one's on us. A dot shouldn't break the world. It's a perfectly acceptable path character.

@Mbucari Life has gotten busy again (but thankfully not covid this time). If I remember later, I'll eventually add some unit tests with dots in them unless you beat me to it

**Comment by rmcrackan** [comment]
New version [v9.0.1](https://github.com/rmcrackan/Libation/releases/latest) is published. Thank you for your patience

**Comment by Mbucari** [comment]
@rmcrackan I added only 1
https://github.com/rmcrackan/Libation/blob/f72551fa9ac6f68e152e16a1105e9921bed74953/Source/_Tests/LibationFileManager.Tests/TemplatesTests.cs#L97

I noticed there are no folder template tests besides checking for warnings and number of tags. I should probably be some folder text template tests.

**Comment by PaulBrad25** [comment]
Thanks folks. I wish backing up my comics collection was as straight forward, and kindle collection was as well orchestrated.

**Comment by PaulBrad25** [comment]
Two more questions folks, save me from my own stupidity if it's staring me in the face...

1/ Updates are by push notification or manual reinstall only? I couldn't find a 'check for updates' macro button and had to delete Libation and reinstall the newer version to get your update.

2/ If someone were to fuck up a little; right click on the liberate traffic light for an entry, and accidentally select 'Remove from Library' instead of Set Download Status to 'Not Downloaded'. How would one go about undoing that, theoretically. 
Asking for a friend.
I've <ahem> *they've* tried rescanning the library, removing the book from the Audible Library and reading it, and reading through all the 'help' and 'settings' to no avail. It's still there in Audible library, but Libation has been told to reject it and I can't find the log that would be in to undo it.

**Comment by PaulBrad25** [comment]
> Two more questions folks, save me from my own stupidity if it's staring me in the face...
> 
> 1/ Updates are by push notification or manual reinstall only? I couldn't find a 'check for updates' macro button and had to delete Libation and reinstall the newer version to get your update.
> 
> 2/ If someone were to fuck up a little; right click on the liberate traffic light for an entry, and accidentally select 'Remove from Library' instead of Set Download Status to 'Not Downloaded'. How would one go about undoing that, theoretically. Asking for a friend. I've _they've_ tried rescanning the library, removing the book from the Audible Library and reading it, and reading through all the 'help' and 'settings' to no avail. It's still there in Audible library, but Libation has been told to reject it and I can't find the log that would be in to undo it.

RE: 2/ never mind, I've found 'hangover.exe'

**Comment by Mbucari** [comment]
> 1/ Updates are by push notification or manual reinstall only? I couldn't find a 'check for updates' macro button and had to delete Libation and reinstall the newer version to get your update.

Libation checks for updates every startup. If there's an available update but you weren't being notified, then something went wrong.
