### ISSUE TITLE
Custom Fields

### ISSUE THREAD

**Issue by GeraldPape** [rmcrackan/Libation#455]
I wiould like to have additional fields in the UI that I could fill for each audiobook. 
personal notes as free text
finished bool, eventually an additional field for the Date

**Comment by Mbucari** [comment]
> I wiould like to have additional fields in the UI that I could fill for each audiobook.

Can you elaborate? Do you mean like a new "My Notes" grid column with an editable text box, or more like a 'notepad' dialog window you can open, read/edit, and close for each book?

>finished bool

I don't understand what you mean. Something different than the green stoplight indicating that the book has been liberated?

> eventually an additional field for the Date

Which date? The date a book was liberated?

**Comment by Mbucari** [comment]
@GeraldPape Ping

**Comment by rmcrackan** [comment]
I think this ticket went cold. If conversation picks up again I'll be happy to re-open it.

**Comment by rmcrackan** [comment]
For something like that I recommend tagging and filtering.

Personally, I review every audible book I've listened to as my personal way to track what I've finished but I appreciate that's not everyone's choice. I'll use that as the example though.

After I listen to a book, I review it in audible. On Libation's next scan, it retrieves my personal rating/review. This marks it as `Rated`, which is a special search word. (To see all special search words, click the [?] button to the left of the search bar.) To see only unread/unrated books, I filter by for "not rated." Searching with "not" is a minus: `-Rated`. I don't want to have to do this filter every time, so I clicked "Add to Quick Filters" and on the Quick Filters menu then select "Start Libation with 1st filter". Now every time Libation launches, my Rated books are hidden.

If you prefer, you can do this with a custom tag. In the book's far right is a button for "tags and details." Click that and type `finished` in that box. Now in the filter/search box, `-[finished]` will hide all books with that tag. (Searching with tags uses brackets: `[tag_name]`). For fun, there's 1 secret tag called `hidden`. If you use that tag, it will grey-out the row. A book can have as many tags as you want, separated by spaces.

For additional info like date finished, you're right -- we'd need a new place for notes. Do you still need a notes area or will the above solve your case?

**Comment by GeraldPape** [comment]
Thank you for the explanation. That's fine for me, don't need any more fields now.

**Comment by rmcrackan** [comment]
Sounds good. Thanks for the feedback
