### ISSUE TITLE
Help installing Libation on a Mac, please

### ISSUE THREAD

**Issue by TonyCog** [rmcrackan/Libation#457]
Hello

u/darchangel on Reddit suggested I ask this here. I have no coding knowledge. I would like to install Libation on a Mac but I don't understand the installation instructions using Terminal. Is someone able to provide a step-by-step list of instructions to install this on a Mac?

Many thanks!

**Comment by Mbucari** [comment]
1. Download [the latest Libation Mac release](https://github.com/rmcrackan/Libation/releases/download/v9.0.1/Libation.9.0.1-macos-chardonnay.tar.gz).
2. Extract the file (if it wasn't already extracted for you).
3. [Open a terminal](https://support.apple.com/guide/terminal/open-or-quit-terminal-apd5265185d-f365-44cb-8b09-71a064a42125/mac)
4. In the terminal change directory to the extracted libation files. Something like this:
  ```console
  cd /users/[Your_User_Name]/Downloads/Libation.9.0.1-macos-chardonnay
  ```
  If that worked and you're inside the libation folder, your command line will look something like this:
  ```console
  [Your_User_Name] Libation.9.0.1-macos-chardonnay%
  ```
5. Once your terminal shows that you're in the libation folder, run these commands in the terminal:
  ```console
  sudo spctl --add --label "Libation" ./Libation
  sudo spctl --master-disable
  ```
  After you enter the first command, you'll be asked to enter your computer password.
6. Then, run Libation with this command:
  ```console
  ./Libation
  ```

I'm sorry there's not currently a better way to do this.

**Comment by TonyCog** [comment]
Thank you for your help. I'm not sure what I'm doing wrong. After I enter the first command from step 5 and enter my password, I get this:

./Libation: invalid API object reference
Tonys-Mac-Studio:~ [User name]$ 

After entering the second line, I only get a prompt.

**Comment by Mbucari** [comment]
I made a video showing step-by step how to get Libation running.
https://user-images.githubusercontent.com/37587114/213933357-983d8ede-2738-4b32-9c6e-40de21ff09c2.mp4

**Comment by rmcrackan** [comment]
That's great! I haven't tried to embed videos into markdown. It should definitely go into the main documentation.

**Comment by TonyCog** [comment]
This worked! The video only shows cutting and pasting one command, the installation instructions show two lines. Maybe that is the issue. Whatever it is, this video is great and I appreciate your time. My audiobooks have been freed! Thank you!

**Comment by Mbucari** [comment]
> I haven't tried to embed videos into markdown. It should definitely go into the main documentation.

That took me a minute. Is the same pattern as hyperlinks
\[\]\(\)
With the video in the parentheses. But I'll be damned if I know what GitHub does with the text in the square brackets. You can put anything in there and it doesn't change what gets displayed.

**Comment by rmcrackan** [comment]
@Mbucari added to the [mac page](https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md). How did you upload it? I see it's listed as https://user-images.githubusercontent.com/...

**Comment by Mbucari** [comment]
> How did you upload it?

Drag drop into the text editor.

**Comment by rmcrackan** [comment]
Wow -- I wouldn't have thought to even try that with a file as big as a video
