### ISSUE TITLE
Leaving MP3s as .tmp

### ISSUE THREAD

**Issue by cschodt** [rmcrackan/Libation#459]
Hello!

I'd messaged on Reddit about this issue. Here's the log file from the day I ran Libation through my library. Thanks for any help you can provide.

[_Log202301.log](https://github.com/rmcrackan/Libation/files/10483148/_Log202301.log)

**Comment by rmcrackan** [comment]
From reddit:

> Hey, so I just tried this out, and it downloaded and decrypted great, totally amazing, but when I went to convert to MP3, it kept all the files as ".mp3.tmp"
> 
> I can just delete the .tmp and they play, but it's like 800 books, so kind of a pain. I wasn't sure if this was either something I did wrong, or a glitch you'd want to know about.

**Comment by Mbucari** [comment]
@cschodt just FYI, if you want only mp3s and don't care about m4b, you can change the setting to download and decrypt directly to mp3.

Settings > Audio File Options > Download my books as .MP# files

**Comment by rmcrackan** [comment]
Fixed. Will be included in the next release

**Comment by rmcrackan** [comment]
New version [9.1](https://github.com/rmcrackan/Libation/releases/latest) is published
