### ISSUE TITLE
Error trying to scan library

### ISSUE THREAD

**Issue by RHelmuth** [rmcrackan/Libation#461]
I've tried both login methods and keep getting an error instead of successfully scanning my library. Here are the logs (after I changed log settings to "Debug"), but please let me know if there's anything else I should do.
[Log202301.log](https://github.com/rmcrackan/Libation/files/10495673/Log202301.log)

**Comment by rmcrackan** [comment]
Thanks for the log. Is your audible account a US account?

**Comment by RHelmuth** [comment]
Yes, although I'm currently outside the US and was logging in without a VPN...

**Comment by RHelmuth** [comment]
Looks like that was the issue! After using a VPN to set my IP to a US location, the login/scan was successful. Thanks!
