### ISSUE TITLE
Different Books Location Per Account

### ISSUE THREAD

**Issue by runnylogan** [rmcrackan/Libation#465]
I would like to select a different download location for different accounts or set a custom location for a specific account, leaving all others with the default location under 'Important Settings'.

This would keep downloaded account content in a separate folder structure and allow applications such as Audiobookshelf to present that content as different libraries.

**Comment by Mbucari** [comment]
You can sort of already do that with folder naming templates. All accounts will have the same root folder, but you can place books into folders by account like so:
![2023-01-27_095623](https://user-images.githubusercontent.com/37587114/215147156-77022372-77e2-42c1-a9ee-bd19f8841e4e.png)

**Comment by runnylogan** [comment]
Exactly the outcome I was looking for, thanks.
