### ISSUE TITLE
Custom File Naming format enhancements - Sort Author by Last Name, zero-pad <series#>

### ISSUE THREAD

**Issue by bta1701** [rmcrackan/Libation#466]
I would like to save audiobooks sorted by Author, last name first.

Also, in the saving format, it would be cool if the <series#> could be zero-padded (user defined # of chars)

Ideally my custom format would be:
<first author lastfirst>\<if series -><series>\<series#,2> <-if series><title short>

which would produce (example):
Zelazny, Roger\Chronicles of Amber\01 Nine Princes in Amber\

This program is truly awesome.  Thanks muchly.

**Comment by bta1701** [comment]
somehow my format example got clipped.  Have to use parentheses () instead of angle brackets for some parts or they get clipped.  Try this (imagining the () are <>:

(first author lastfirst)\<if series ->(series)<series#,2> <-if series><title short>

**Comment by rmcrackan** [comment]
Your leading-zeros idea sounds doable.

Unfortunately, the last name one is unlikely due to the issue listed [here](https://github.com/rmcrackan/Libation/issues/420#issuecomment-1361311573).

**Comment by bta1701** [comment]
Thanks.  I searched the list for "last name" trying not to duplicate a prior, but obviously I don't search good.  Sorry.

Thanks again.

b

**Comment by rmcrackan** [comment]
No worries. github has ways to search closed tickets also but you have to know their tricks; they don't make it nearly as obvious as they should.

**Comment by rmcrackan** [comment]
[Version 9.2.1](https://github.com/rmcrackan/Libation/releases/latest) has greatly expanded templating including this request. [Documentation](https://github.com/rmcrackan/Libation/blob/master/Documentation/NamingTemplates.md)

Great work, @Mbucari !!

**Comment by rmcrackan** [comment]
FYI, this is getting some additional scrutiny. Watch #481 for progress.
