### ISSUE TITLE
podcasts wont download

### ISSUE THREAD

**Issue by CreedOfLies** [rmcrackan/Libation#467]
about a week ago I started to have an issue where podcasts will no longer download after importing

books still download though

**Comment by Mbucari** [comment]
@rmcrackan I confirmed that there's a problem downloading podcasts in 9.1, but that bug does not exist in the master branch. You can go ahead and release the master and it'll fix this.

**Comment by rmcrackan** [comment]
Ah, thanks. On it.

**Comment by rmcrackan** [comment]
Fixed in [latest](https://github.com/rmcrackan/Libation/releases/latest)
