### ISSUE TITLE
Add <language> option to file structure naming as an export setting.

### ISSUE THREAD

**Issue by ThoughtfulSenpai** [rmcrackan/Libation#469]
When downloading different books from different audible regions, if one has books in French, English, etc, one ends up with the same book in different languages. For some books this doesn't matter, since the title is also translated, but some books don't get translated titles. Think Dracula, for example. While it is possible to add locale as an argument for the name, which may help, it would be better if one could have the  language tag embedded in the folder name.  

**My idea would be to*
Grab the language of the book and treat it as a tag for naming the folders of downloaded books.
Example:
Bram Stoker - Dracula - (ITA)/
Bram Stoker - Dracula - (FRE)/
Bram Stoker - Dracula - (ENG)/
Bram Stoker - Dracula - (SPA)/

and so on.

<img width="301" alt="image" src="https://user-images.githubusercontent.com/100229664/215898800-e59de986-6e08-426d-9b75-a57d186785d5.png">

Have a great day!

**Comment by rmcrackan** [comment]
Thanks for the idea! These new options are available in [version 9.2](https://github.com/rmcrackan/Libation/releases/latest)

\<language\> - English
\<language short\> - ENG

It requires 1 re-scan to pick up languages. I didn't previously store this info
