### ISSUE TITLE
Error - Could not deserialize json

### ISSUE THREAD

**Issue by SunFox14** [rmcrackan/Libation#470]
[Log202302.log](https://github.com/rmcrackan/Libation/files/10558204/Log202302.log)

**Comment by rmcrackan** [comment]
Sorry about this. Thank you for the log file. In the same folder as the log files is `Settings.json`. Could you [email](https://github.com/rmcrackan) that to me?

**Comment by SunFox14** [comment]
Here you go!

**Comment by rmcrackan** [comment]
Weird. The file didn't seem to come through. Can you email the file directly to me? My email is on [this page](https://github.com/rmcrackan)

**Comment by SunFox14** [comment]
2nd try, here's the file to both emails.

**Comment by rmcrackan** [comment]
Gracias. The direct email worked. This file looks perfect. I believe maybe the other file is corrupted: AccountsSettings.json. *Don't send that one to me*, it has info in it which could give full access to your audible account. I think you should just delete it, and re-enter your account info (under Settings \> Accounts), and see if the problem happens again. This is similar to deleting browser cookies and it will prompt you again to login. Please let me know if this helps.

**Comment by SunFox14** [comment]
Success! Thanks a bunch!!

**Comment by rmcrackan** [comment]
You're welcome :)
