### ISSUE TITLE
Can't see library

### ISSUE THREAD

**Issue by anesone** [rmcrackan/Libation#474]
When I open the app, nothing shows in my library.  When I try to use a filter, I get the exception:
"Bad Filter String: Object reference not set to an instance of an object."
I used the export function, and it shows my recent purchases. I just can't back them up.
[Log202302_009.log](https://github.com/rmcrackan/Libation/files/10614111/Log202302_009.log)

**Comment by rmcrackan** [comment]
So sorry about this. Thank you for the log file. It was invaluable. The fix is live in the [latest version: 9.2.2](https://github.com/rmcrackan/Libation/releases/latest). Please let us know if it does not work.
