### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by dcolecpa** [rmcrackan/Libation#475]
**Describe the bug**
Can't install 

**To Reproduce**
1.  ENTER INSTALL COMMAND ON CLI 
wget -O libation.deb https://github.com/rmcrackan/Libation/releases/download/vX.X.X/Libation.X.X.X-linux-chardonnay.deb &&
sudo apt install ./libation.deb

2. RESPONSE 
--2023-02-05 19:18:15--  https://github.com/rmcrackan/Libation/releases/download/vX.X.X/Libation.X.X.X-linux-chardonnay.deb
Resolving github.com (github.com)... 140.82.112.3
Connecting to github.com (github.com)|140.82.112.3|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2023-02-05 19:18:16 ERROR 404: Not Found.

3. Click on '....'
4. Scroll down to '....'
5. See error

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by wtanksleyjr** [comment]
I think you copied that link from some general-purpose documentation; it's supposed to be replaced by a link to a specific version, not X.X.X. I'll paste the most current one in for you, you should be able to use that right away. https://github.com/rmcrackan/Libation/releases/download/v9.2.1/Libation.9.2.1-linux-chardonnay.deb

You can get the newest version of this link at any time by going to the github homepage of this project, and clicking on the latest entry in the "Releases" display to the right of the source code. [This link](https://github.com/rmcrackan/Libation/releases) is a list of all releases, and you'll see the `deb` links for all of the recent ones.

**Comment by rmcrackan** [comment]
@wtanksleyjr Much thanks, my penguin friend!!

@dcolecpa Let us know if this solution doesn't work for you.

**Comment by dcolecpa** [comment]
That resolved it, thanks!
