### ISSUE TITLE
Issue installing Libation on a Mac

### ISSUE THREAD

**Issue by FTime8** [rmcrackan/Libation#476]
Hi,

I am trying to install the Mac version of Libation. I am hoping you can help here.

I followed the step by step instructions in the embedded video regarding installing on a Mac. I was able to get to the step where I select New User, but after selecting it the terminal pops up again with the below and nothing progresses.

![Libation progress halt](https://user-images.githubusercontent.com/124659843/217201924-7665c6b7-600f-4a41-8a60-91f01f48aaa6.png)

**Comment by colossal-squid** [comment]
<img width="489" alt="image" src="https://user-images.githubusercontent.com/32293829/217513673-29085697-0eeb-4b22-863c-bb66a1b035f2.png">
same here

**Comment by Mbucari** [comment]
Hi @FTime8 Can you please post the log file? It's located in [user]/Libation (~/Libation)

**Comment by rmcrackan** [comment]
Fixed by @Mbucari in [version 9.3.1](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by FTime8** [comment]
Sorry @Mbucari, I gave up over the weekend before the update & deleted everything and backed up my audiobooks on my friends Windows based computer to an external drive.
