### ISSUE TITLE
Unable to create New User in 9.2.1 / 9.2.2 on Linux

### ISSUE THREAD

**Issue by Xelef2000** [rmcrackan/Libation#478]
**Describe the bug**
When installing libation 9.2.1 / 9.2.2 and clicking "New User", the program crashes without output. 
it works fine in 9.2 and below. 

**To Reproduce**

1. Install Libation
2. Open programs
3. Click New User

**Expected behavior**
The window to create new settings should appear.

**Platform**

Linux pop os 22.04 

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
@rmcrackan I'll check it out tomorrow

**Comment by rmcrackan** [comment]
@Mbucari Thank you, sir

**Comment by rmcrackan** [comment]
@Xelef2000 This should now be fixed in [version 9.2.3](https://github.com/rmcrackan/Libation/releases/latest)

@Mbucari Thanks again for the quick turn around!
