### ISSUE TITLE
Book which could be liberated in Libation 4 not working in v5

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#48]
https://www.reddit.com/r/audible/comments/occ16x/libation_50_harder_better_faster_stronger/h40a0f5/

here's the top of the error message i get when trying to download 11-22-63 in libation 5

> ************** Exception Text ************** System.NullReferenceException: Object reference not set to an instance of an object. at FileLiberator.DownloadDecryptBook.Cancel() in C:\Dropbox\DinahsFolder\coding_NET\Visual Studio 2019\Libation\FileLiberator\DownloadDecryptBook.cs:line 221 at LibationWinForms.BookLiberation.ProcessorAutomationController.<>cDisplayClass9_0.<wireUpEvents>b9(Object , FormClosingEventArgs _) in C:\Dropbox\DinahsFolder\coding_NET\Visual Studio 2019\Libation\LibationWinForms\BookLiberation\ProcessorAutomationController.cs:line 325 at System.Windows.Forms.Form.OnFormClosing(FormClosingEventArgs e) at System.Windows.Forms.Form.WmClose(Message& m) at System.Windows.Forms.Form.WndProc(Message& m) at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m) at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)

> ************** Loaded Assemblies **************

**Comment by Mbucari** [comment]
If you want to focus on the login issues, I'll loo at this. The downloader is kind of my baby, but you're the api and auth expert.

**Comment by rmcrackan** [comment]
Bug fixed. Fringe case allows 0-length chapters for section headers. Rarely used but evidently valid.

**Comment by rmcrackan** [comment]
@Mbucari Which login issues? The stupid "approval" issue is going to be tough because it doesn't happen for all accounts. The captcha accessibility alternative is cool but will affect far fewer people.

**Comment by Mbucari** [comment]
The approval one. Maybe you can convince some trusting soul experiencing this issue to give you their login?

**Comment by rmcrackan** [comment]
I'm not sure I'm ready for that kind of responsibility. If anything at all goes weird with that account ever, the crosshairs are on me.

**Comment by rmcrackan** [comment]
@Mbucari you're definitely the download/decrypt master right now. I've been very impressed at what you've done there.

It sounds full of myself, or maybe full of something else, but I believe my expertise is really problem solving. I'm not the expert at any of the pieces within Libation. At some of them (here's looking at you, UI) I'm really pretty terrible. But I could squeak by on reverse engineering to see how inAudible worked, look at (at the time) the only working audible api in an obscure language, etc etc etc and I now have a 1-click solution to remove drm from my entire audible library, tagging, database, and search engine.
