### ISSUE TITLE
Cannot Download Anything

### ISSUE THREAD

**Issue by OldScotsman** [rmcrackan/Libation#480]
Hello
Thank you so much for your  great program which I make donations for.
Today, I can no longer download "ANY" book.  I re-installed an older version but with the same error message.

![Libation Error](https://user-images.githubusercontent.com/102461501/217507963-706adb9c-786e-4377-bc21-bde8382b05d3.JPG)

An error occurred while trying to process this book.  I get the option to "Abort", "RETRY" "IGNORE"  "
It also says "See settings to avoid this box in future" but the error applies to all books.

Can you help.
OldScotsman

**Comment by rmcrackan** [comment]
I've seen this happen a few times in the past and it nearly always resolves itself after about 1 day. Let's wait for 24 hours, try again, and if it still doesn't work, please attach the log file to this issue.

**Comment by OldScotsman** [comment]
Hello rmcracken.
Thank you so much for getting back to me so promptly. Most appreciated
I removed the account twice and added it again using the copy and paste method of the url and the error was still there.  I have just tried it again but this time I just inserted my Audible password and Libation now works.  ?????
While I am here, last week I right clicked on a book and accidentally clicked on "Remove from library". So far I have not found a way to retrieve it.  Is there one or is it gone?   I thought about clicking "Remove library books" and start again but I am not sure of the consequences.
Thank you once again
OldScotsman

**Comment by rmcrackan** [comment]
Yay, I'm glad that worked for you.

Regarding undo a 'remove': a better way in the queue of to-do items ( #433 ). Until then:

Go to the folder where the Libation program is and find HangoverWinForms or HangoverAvalonia. It's a debug program -- in other words it's for handling weird problems (... like the problem that I haven't yet built a decent user interface for this issue). Run Hangover and go to the tab for 'deleted books'. You can un-delete books here.

**Comment by OldScotsman** [comment]
Thank you.
Is there an easier way to donate?  The last time I did it the process seemed so complicated and now I can't even find how I did it. Grin

**Comment by rmcrackan** [comment]
Thanks! The easiest way is [paypal](https://paypal.me/mcrackan?locale.x=en_us).

If that doesn't work for you, you can [email](mailto:rmcrackan@gmail.com) an [amazon card](https://www.amazon.com/gp/product/B09BZ4VF5R). Amazon defaults to a stupidly high value but there's an "enter amount" box for any custom amount.

**Comment by OldScotsman** [comment]
Done it.
Again thank you.  Love your program

**Comment by rmcrackan** [comment]
Much thanks 😄

**Comment by Mbucari** [comment]
@OldScotsman

Can you please post your log files? I've been trying to catalog cases this particular issue.

**Comment by rmcrackan** [comment]
@Mbucari my suspicion is that this occurs when audible has a redirect which the official app knows to handle but we don't. It feels like whenever this happens to a user, it affects them on Libation for a day or less and doesn't affect them on the phone app. Maybe it's a load balancer or something which happens with rolling upgrades.

I still have no explanation for why it happens to some users for a while but not others. If it were about server updates, I'd expect it to happen for all users, including me when I try to debug the issues. If it's a load balancer, I'd expect it to happen once then not happen the next time they try. Or else expect it to start hitting lots of overflow users at once and see a spike in trouble tickets -- again, including myself.

I'm not completely happy with this theory but I can't think of anything better. Let me know if you uncover anything. I'm at a loss.

**Comment by Mbucari** [comment]
@rmcrackan Yeah, that does sound about right. I don't expect to be able to fix the problem, I just hope to be able to provide users with more helpful error messages. [I thought I'd had it before](https://github.com/rmcrackan/Libation/issues/352), but I guess I didn't.
