### ISSUE TITLE
Custom Naming Fields for Author First or Last Name Only

### ISSUE THREAD

**Issue by schmads42** [rmcrackan/Libation#481]
I prefer to organize my books by the author's last name, followed by the author's first name, i.e.:  "Doyle, Arthur Conan".

I'd like two new tags, `<author first name>` and `<author last name>` which would return only the last name, and any names that are not the last name, respectively.

A single tag that returns the name in Last, First format would also work, but wouldn't be as flexible for others who may want only the last or first names.

I have already made the changes on a clone of the repo, locally.  I tried to push a branch to do a PR, but I am not permitted.  I will be happy to submit my changes for a pull-request if that's easy for you, but I'll also attach a diff.  Any whitespace changes were unintentional.

I have tested the changes on Windows 10 x64 only, but they shouldn't be platform-specific.

[SepNameFieldsDiff.txt](https://github.com/rmcrackan/Libation/files/10691576/SepNameFieldsDiff.txt)

Libation rocks!  Feel free to use or discard this as you like.

**Comment by rmcrackan** [comment]
Thanks much for your idea and for your code. I've considered this before and unfortunately the [edge cases](https://github.com/rmcrackan/Libation/issues/420#issuecomment-1361311573) are just too numerous. (I wish github made searching easier; it took me a while to find this even knowing it existed)

This has been a popular request with at least 3 tickets so far. I'll keep a look out and hope that audible improves their metadata.

@Mbucari I'm interested in your opinion. Am I over-thinking this? Or are these good reasons to not create such a feature?

**Comment by Mbucari** [comment]
> @Mbucari I'm interested in your opinion. Am I over-thinking this? Or are these good reasons to not create such a feature?

I think it's worth a try. I think the worst case scenario is they authors's name parts get jumbled and filenames will require manual correction, but the people who want this feature are probably already manually editing filenames. I recently took a look at all the author and narrator names in my library and have a couple of ideas for how to be a little clever about it and avoid some of the pitfalls you outlined. Would you mind exporting your library and sharing it with me so I could see some more examples?

And I just had a crazy idea. What if we used the OpenAI service to do the name parsing for us?

**Comment by CharlieRussel** [comment]
If you need a library or 4, I have some large ones. Including pre-Amazon and a UK one. Ping me in email and I'll share.

**Comment by rmcrackan** [comment]
> Oh! I’m sorry for the duplicate request

No worries. Github's defaults assume you're searching open tickets only. You have to trick it a bit to also search closed too.

> I didn’t realize that Amazon made such a mess of the authors

Dude, tell me about it. I keep hoping they'll fix their metadata, and eventually they might for the major authors. I've seen their half-assed approaches to other upgrades though and I can promise you that the little guys will be unchanged until the heat-death of the universe. Maybe one day they'll at least fix the big authors though and this feature will be more feasible.

> you’ve got a really clean codebase

Thank you :) Since this started as a one-man passion project, it let me indulge in any level of organization with a singular vision. @Mbucari has been fantastic in understanding my conventions.

> What if we used the OpenAI service to do the name parsing for us?

I haven't gotten into AI yet. I'm sure it's the future but I'm not convinced it's the present. I feel like we're in its AskJeeves days and won't really feel its impact until we hit the early Google years. It could be fun to play with though. And maybe I'm wrong and we'll be pleasantly surprised.

@Mbucari Sure I'll email you an export today.

@CharlieRussel If you don't have @Mbucari 's email, you can email yours [to me](https://github.com/rmcrackan) and I can forward it.

**Comment by Mbucari** [comment]
Here's a list of all unique author and narrator names between @rmcrackan's and my libraries.


[authors and narrators.txt](https://github.com/rmcrackan/Libation/files/10700164/authors.and.narrators.txt)

Name suffixes include:
-  \- introduction
-  \- adaptation
-  \- translator
-  \- contributor
-  \- illustrator
-  \- director
-  \- foreword
-  \- editor
-  \- preface
-  \- adaptor
-  \- afterword
-  \- interviewer
-  \- introductions
-  \- essay
-  \- editor/introduction

There's also a "\- Ret." suffix for "Retired"

**Comment by rmcrackan** [comment]
A few fun ones from that list:

* Bruce Bueno de Mesquita
* Ramon de Ocampo
* Ramon De Ocampo
* Jennifer Van Dyck
* Carla Naumburg PhD
* Doug Stanhope and Friends
* Tamara Lovatt-Smith
* Common
* Doug Tisdale Jr.
* Robert S. Mueller III
* Frank T Vertosick Jr. MD
* The Arabian Nights
* The Great Courses
* The Laurie Berkner Band
* Committee on Foreign Affairs
* House Permanent Select Committee on Intelligence
* Professor David K. Johnson PhD University of Oklahoma
* Festival of the Spoken Nerd
* Audible Original
* Audible Originals
* Patrick O'Brian
* Patrick O’Connell /<-- note the different apostrophe

**Comment by wtanksleyjr** [comment]
And don't forget the ones who put "Dr." and other titles in _front_ of
their names; not to mention " Jr." versus ", Jr." (I think I have a few
that just have a SEA of titles all around their names, I shouldn't make any
judgments about their egos so I'll keep my mouth mostly shut). Oy vey. And
then there's the fact that Chinese names typically have the family name
first, except of course when they don't because someone westernized them.

**Comment by rmcrackan** [comment]
Since most people seem more concerned about last name, the Dr. at the beginning will be less of an issue. The litany of titles is definitely a headache. I'm less concerned about Chinese/Japanese family name position because realistically audible probably westernized it anyway whether they like it or not.

**Comment by Mbucari** [comment]
@rmcrackan 

Would you take a look at this! 

https://github.com/aeshirey/NameParserSharp

**Comment by rmcrackan** [comment]
@Mbucari at first glance, it's better than starting from scratch. We'd need a boatload of unit tests before we made a final call. Curious what it would do with stage names like "Common", "Jewel", "The Edge". Hell, I'm curious of what *I'd* expect. I'm not crazy about how long their pending PR and simple issues have been hanging around. I guess we could just fork it though.

**Comment by Mbucari** [comment]
@rmcrackan I took our combined list, removed all "introduction", "adaptation", etc. suffixes, and passed them to NameParserSharp. [Here are the results](http://jsonblob.com/1073316304018227200).

It looks good! None of them were unparsable.

> Curious what it would do with stage names like "Common", "Jewel", "The Edge".

```JSON
{
  "IsUnparsable": false,
  "FullName": "Jewel",
  "First": "Jewel"
}
```

```JSON
{
  "IsUnparsable": false,
  "FullName": "Common",
  "First": "Common"
}
```

Also...

```JSON
{
  "IsUnparsable": false,
  "FullName": "Committee on Foreign Affairs",
  "First": "Committee",
  "Middle": "on",
  "Last": "Foreign Affairs",
  "LastBase": "Foreign Affairs"
},
{
  "IsUnparsable": false,
  "FullName": "Committee on Oversight and Reform",
  "First": "Committee",
  "Middle": "on",
  "Last": "Oversight and Reform",
  "LastBase": "Oversight and Reform"
}
```

**Comment by Mbucari** [comment]
OK, here's the list of all authors and narrators in my library, @rmcrackan's library, and @CharlieRussel's library.

[authors and narrators.txt](https://github.com/rmcrackan/Libation/files/10701830/authors.and.narrators.txt)

And [here are the parsed names](http://jsonblob.com/1073360957375528960)  that I created using [this free nuget package I found](https://www.nuget.org/packages/NameParserFree).

**Comment by CharlieRussel** [comment]
And then you're going to have ones like "L.E. Modesitt" v. "L. E. Modesitt Jr." v. "LE Modesitt, Jr.". And is Marine Le Pen a last name of Pen, or the more accurate French solution of a last name of "Le Pen"? (Not that I would even consider listening to anything from  her, but merely as an example of where there could be problems.) And what does it do with L. Sprague de Camp?

**Comment by Mbucari** [comment]
@CharlieRussel 

```JSON
[
  {
    "Rank": "Marine",
    "FirstName": "Le",
    "LastName": "Pen"
  },
  {
    "FirstName": "L",
    "LastName": "Modesitt",
    "MiddleName": "E"
  },
  {
    "FirstName": "L",
    "LastName": "Modesitt",
    "MiddleName": "E",
    "Suffix": "Jr"
  },
  {
    "FirstName": "LE",
    "LastName": "Modesitt",
    "Suffix": "Jr"
  },
  {
    "FirstName": "L",
    "LastName": "Camp",
    "MiddleName": "Sprague de"
  }
]
```

I really don't believe that this process needs to be perfect, or even 99%. It'll be correct enough most of the time, and where it's incorrect it won't cause a system failure or even be unreadable.

**Comment by CharlieRussel** [comment]
@Mbucari I suspect you're right that it won't be a major problem even where it's wrong. Though I would posit that 4 out of the 5 were wrong at least in part. However, only the Le Pen one is really wrong. (Though at least one publisher lists L. Sprague DeCamp, shifting the last name, which is, to me, the important one.) IAC, I have the same problem with eBooks and end up having to go through my Calibre to manually fix things like this where the slight variation puts them in completely different groupings. Mostly I catch it on import, but sometimes they slip through and I need to poke around to find it after the fact. As you point out, not the end of the world.

**Comment by Mbucari** [comment]
> Though I would posit that 4 out of the 5 were wrong at least in part.

True, but these were edge cases designed to probe the limits.

> the Le Pen one is really wrong

Yes, it's mistaking her first name for a military title. This kind of mistake is bound to happen. This library does have an option for adding multi-word first and last names to a list so they can be identified. "Le Pen", "de Camp", and others can be added to that list to improve matching.

**Comment by rmcrackan** [comment]
It's impossible for name parsing to be perfect. "Prince Harry" has a title. "Prince" is the stage name of "Prince Rogers Nelson" where it was his birth first name. I do think da, le, de, von and similar should be assumed to be part of the last name, a la "Leonardo da Vinci".

> Curious what it would do with stage names like "Common", "Jewel", "The Edge".

```
{
  "IsUnparsable": false,
  "FullName": "Common",
  "First": "Common"
}
```

however in your [link](https://jsonblob.com/1073320095815843840), line 6443:

```
  {
    "LastName": "Jewel"
  },
```

I don't know that we'll be able to use this as-is but maybe we could fork and improve it. We could try PRs first. The library looks like it's gone pretty stale though so who knows.

**Comment by rmcrackan** [comment]
I we do commit to a name parsing template feature, users are going to want

* full name
* last name comma the rest
* last name only
* and all of these for both author and narrator

**Comment by Mbucari** [comment]
@CharlieRussel I used a different parsing engine on your edge cases, and this is the result:

```JSON
[
  {
    "FullName": "Marine Le Pen",
    "First": "Marine",
    "Last": "Le Pen",
  },
  {
    "FullName": "L.E. Modesitt",
    "First": "L.E.",
    "Last": "Modesitt",
  },
  {
    "FullName": "L. E. Modesitt Jr.",
    "First": "L.",
    "Middle": "E.",
    "Last": "Modesitt",
    "Suffix": "Jr.",
  },
  {
    "FullName": "LE Modesitt, Jr.",
    "First": "LE",
    "Last": "Modesitt",
    "Suffix": "Jr.",
  },
  {
    "FullName": "L. Sprague de Camp",
    "First": "L.",
    "Middle": "Sprague",
    "Last": "de Camp",
  }
]
```
[And here are the results of the whole list](https://jsonblob.com/1073648645949374464).

@rmcrackan I was thinking of leveraging the new custom string formatters to do this.

The formatter would support virtual functions like

|Function|Description|
|-|-|
|Format(FML)|Format the first, middle and last name parts|
|Separator(string)|string used to join multiple names|
|Sort()|Part of the name to sort by (F, M, or L)|
|Max(\#)|Maximum number of names to add|

Using this author string as an example: 
```So this string of authors `Philip Pullman, Joanna Wyatt, Anton Lesser, Richard Pearce, Douglas Blackwell, Daniel Flynn, Nicolette McKenzie, Garrick Hagon, Liza Ross```

This tag:
`<authors[Format(L, F M) Separator(; ) Sort(L)]>`

results in this:
```Blackwell, Douglas; Flynn, Daniel; Hagon, Garrick; Lesser, Anton; McKenzie, Nicolette; Pearce, Richard; Pullman, Philip; Ross, Liza; Wyatt, Joanna```

and this tag `<authors[Format(L) Separator(, ) Sort(L) Max(4)]>`

Results in this:
```Blackwell, Flynn, Hagon, Lesser```

and this tag `<authors[Format(L, F) Separator(; ) Sort(F) Max(3)]>`

Results in this:
```Lesser, Anton; Flynn, Daniel; Blackwell, Douglas```

**Comment by CharlieRussel** [comment]
@Mbucari - It looks like this second engine handles edge cases better, and we already know that none are going to be perfect.

**Comment by rmcrackan** [comment]
This ticket brought to you by: if you want to find out the truth, confidently say a mistruth on the internet and people will swarm to correct you and call you an idiot. And if you want something done, tell a programmer it can't be done.

**Comment by rmcrackan** [comment]
The fix is [here](https://github.com/rmcrackan/Libation/pull/487#issuecomment-1426613423). Available in [latest](https://github.com/rmcrackan/Libation/releases/latest)
