### ISSUE TITLE
Missing book from the scanned list

### ISSUE THREAD

**Issue by tsarinaspades** [rmcrackan/Libation#482]
Hello
I only have two audible books on my account. One has been successfully scanned but not the other one. There's no error message or anything.
The book is still on my Audible account.

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach your log file?

**Comment by tsarinaspades** [comment]
> Sorry about this. Can you attach your log file?

Is the log file something called _Log202302.log?

I've tried using another app (BookLibConnect) and I have the same problem so I believe the problem comes from Audible. Could that book have a special token or a different protection?

**Comment by rmcrackan** [comment]
> Is the log file something called _Log202302.log?

Yup

**Comment by tsarinaspades** [comment]
> Thanks! I see you backed up 2 books and haven't backed up a third. Are you able to listen to this book on your phone app? Or on the website with their browser player?

I'm not interested in the 3rd book that's why I didn't back it up. The problem is that there should be 4 books listed and the 4th one is not showing.

**Comment by rmcrackan** [comment]
Stupid question -- you're sure it's the same account and region?

**Comment by tsarinaspades** [comment]
> Stupid question -- you're sure it's the same account and region?

I only have two accounts. One account has 2 books and the other account has 2 books. One of the accounts has 1 missing book. The settings are fine because Libation is able to backup books from both accounts. It's just that 1 is missing and I don't know why. But I'm starting to believe it comes from Audible. Maybe there's an additional protection to certain books?

**Comment by rmcrackan** [comment]
In the same folder as `Libation.exe` is `HangoverWinForms.exe` or `Hangover.exe`. Please start that program. Copy/paste this into that top box and click Execute: `select count(1) from Books`

What does it say at the bottom?

**Comment by rmcrackan** [comment]
This bug seems to have gone cold. If you're still having issues, please attach a new log and I'll reopen.
