### ISSUE TITLE
Rename and save FileLocations.json instead of deleting it.

### ISSUE THREAD

**Issue by Andytr1** [rmcrackan/Libation#485]
See issue #483 for background. It appears that the error handling deletes FileLocations.json even if it may not be corrupt. Since this file "links" the physical location of audiobooks with the UI, it would be helpful to rename it and keep it in file system, while alerting the user.

**Comment by rmcrackan** [comment]
The fix is [here](https://github.com/rmcrackan/Libation/pull/487#issuecomment-1426613423). Available in [latest](https://github.com/rmcrackan/Libation/releases/latest)
