### ISSUE TITLE
Guiding users to installation instruction

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#486]
Paraphrased suggestion from reddit regarding installing on a mac. Could also apply to the other platforms:

I think if you just added a readme or something (maybe listed as __READ ME FIRST so it's on the top of the folder when you unzip it) that says like "go to this link for detailed installation instructions" you'll solve a lot of the complaints, since you've already done the work -- it just wasn't accessible. Even if you just put it in the release notes it'll make it easier for people to find.

**Comment by Mbucari** [comment]
Here's the new mac setup video
[](https://user-images.githubusercontent.com/37587114/219270196-3d7ead58-4b6b-4692-a30b-1b9e7e257669.mp4)
