### ISSUE TITLE
Error processing Podcast

### ISSUE THREAD

**Issue by powerhousejoe** [rmcrackan/Libation#488]
**Describe the bug**
I've been able to complete many audio books and some podcasts but some podcasts are throwing an error.  Might be of no importance but i notice the individual podcasts that have an error are missing author and narrator.  Log file states it cannot find the file.  Not sure what to do.
![Capture](https://user-images.githubusercontent.com/125143554/218268957-e1d1e12a-878d-4e93-9d87-9917a244f4b9.JPG)

**Platform**

[e.g. Windows 10

**Log Files**

[Log202302_001.log](https://github.com/rmcrackan/Libation/files/10714080/Log202302_001.log)

**Comment by Mbucari** [comment]
You've trimmed your log file so I can't be positive, but I'm pretty sure you're not using the latest version of Libation. This was a bug that's been fixed.

**Comment by powerhousejoe** [comment]
Previous log file was too large to upload.  I will install update and give it another go.  Will let you know results.

**Comment by powerhousejoe** [comment]
Update did the trick.  Thank you
