### ISSUE TITLE
Cannot Download books in Linux

### ISSUE THREAD

**Issue by firstWizball** [rmcrackan/Libation#493]
**Describe the bug**
I have managed to install and set up Libation but each time I select a book to download it fails.

**To Reproduce**
Open application
click on book 
get error

**Expected behavior**
Books to download

**Screenshots**
if you need a screenshot please let me know

**Platform**
linux

**Log Files**
Attach your Libation log file here.
[Log202302.log](https://github.com/rmcrackan/Libation/files/10742415/Log202302.log)

**Comment by Mbucari** [comment]
Did you install Libation using the deb package? If so, pls run this command and paste the output here:

```
ldd -v -d -r /usr/lib/libation/ffmpegaac.so
```

If it's in a different location, pleas locate ffmpegaac.so and run the command on it.

Also, what distribution are you running?

**Comment by mverboom** [comment]
I'm seeing the same problem. As I don't have much experience with dotnet, I was tracing the problem that seems to be related to ffmpegaac.so. On my debian 11 systemen, the ldd output is:
ldd -v -d -r /usr/lib/libation/ffmpegaac.so
/usr/lib/libation/ffmpegaac.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libation/ffmpegaac.so)
/usr/lib/libation/ffmpegaac.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/libation/ffmpegaac.so)
	linux-vdso.so.1 (0x00007ffd533a7000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f6c51ab2000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f6c5196e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f6c51e88000)
undefined symbol: hypot, version GLIBC_2.35	(/usr/lib/libation/ffmpegaac.so)
undefined symbol: pthread_create, version GLIBC_2.34	(/usr/lib/libation/ffmpegaac.so)
undefined symbol: pthread_join, version GLIBC_2.34	(/usr/lib/libation/ffmpegaac.so)
undefined symbol: pthread_once, version GLIBC_2.34	(/usr/lib/libation/ffmpegaac.so)

	Version information:
	/usr/lib/libation/ffmpegaac.so:
		libm.so.6 (GLIBC_2.35) => not found
		libm.so.6 (GLIBC_2.27) => /lib/x86_64-linux-gnu/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
		libm.so.6 (GLIBC_2.29) => /lib/x86_64-linux-gnu/libm.so.6
		libc.so.6 (GLIBC_2.28) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.34) => not found
		libc.so.6 (GLIBC_2.7) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.6) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
	/lib/x86_64-linux-gnu/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6

I also have an older version (8.8.2.1) where the ffmpegaac.so doesn't have the unresolved symbols.

Was searching on how the ffmpegaac.so is built (or downloaded?) and if other versions are available to make it work again..

Regards,

Mark

**Comment by Mbucari** [comment]
@mverboom thanks for the ldd output. [here's the ffmpegaac source](https://github.com/Mbucari/AAXClean.Codecs/tree/master/native/ffmpegaac). Let me know if you successfully build and run it!

**Comment by mverboom** [comment]
Had only little time to do a test:

```
sudo apt-get install gcc make perl pkg-config yasm

wget https://ffmpeg.org/releases/ffmpeg-5.1.2.tar.xz
tar xJvf ffmpeg-5.1.2.tar.xz
cd ffmpeg-5.1.2/
./configure --disable-shared --enable-static --disable-doc --disable-symver --disable-programs --disable-debug --enable-pic --disable-everything --enable-decoder=aac --enable-decoder=pcm_f32le --enable-decoder=pcm_s16le --enable-encoder=aac --enable-encoder=pcm_f32le --enable-encoder=pcm_s16le --enable-parser=aac --enable-demuxer=aac --enable-demuxer=pcm_f32le --enable-demuxer=pcm_s16le --enable-muxer=pcm_f32le --enable-muxer=pcm_s16le --enable-filter=aresample --enable-filter=asetnsamples
make -j $(nproc)
cd ..

sudo apt-get install libavformat-dev
git clone https://github.com/Mbucari/AAXClean.Codecs
cd AAXClean.Codecs/native/ffmpegaac

gcc -fPIC -c aacDecoder.c -c aacEncoder.c -I../../../ffmpeg-5.1.2 -I/home/mbucari/ffmpegaac

gcc -shared -fPIC -Wl,-Bsymbolic -Wl,-soname,ffmpegaac.so.1  -o ffmpegaac.so aacEncoder.o aacDecoder.o -L../../../ffmpeg-5.1.2/libavutil -L../../../ffmpeg-5.1.2/libswscale -L../../../ffmpeg-5.1.2/libswresample -L../../../ffmpeg-5.1.2/libavcodec -L../.../../ffmpeg-5.1.2/libavformat -L../.../../ffmpeg-5.1.2/libavfilter -L../../../ffmpeg-5.1.2/libavdevice -lc -lswresample -lavformat -lavcodec -lavutil -lm
```

Copied the ffmpegaac.so over to the libation install. Didn't work, but strace showed that it was looking for ffmpegaac.x64.so.so (??). So symlinked it, started libation and started a download. And it is now downloading!

Regards,

Mark

**Comment by mverboom** [comment]
Oh, before I forget, the link is not required when copying the ffmpegaac.so over the one in the debian package. The ffmpegaac.x64.so.so seems to be something in the tar.gz version.. When copying over the library in the debian package libation also works fine and can download again.

Regards,

Mark

**Comment by firstWizball** [comment]
Here is the out put you asked for

/usr/lib/libation/ffmpegaac.so: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/lib/libation/ffmpegaac.so)
/usr/lib/libation/ffmpegaac.so: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/lib/libation/ffmpegaac.so)
	linux-vdso.so.1 (0x00007ffc20ff1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fc4786d7000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007fc478588000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fc478ab4000)
undefined symbol: hypot, version GLIBC_2.35	(/usr/lib/libation/ffmpegaac.so)
undefined symbol: pthread_create, version GLIBC_2.34	(/usr/lib/libation/ffmpegaac.so)
undefined symbol: pthread_join, version GLIBC_2.34	(/usr/lib/libation/ffmpegaac.so)
undefined symbol: pthread_once, version GLIBC_2.34	(/usr/lib/libation/ffmpegaac.so)

	Version information:
	/usr/lib/libation/ffmpegaac.so:
		libm.so.6 (GLIBC_2.35) => not found
		libm.so.6 (GLIBC_2.27) => /lib/x86_64-linux-gnu/libm.so.6
		libm.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libm.so.6
		libm.so.6 (GLIBC_2.29) => /lib/x86_64-linux-gnu/libm.so.6
		libc.so.6 (GLIBC_2.28) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.34) => not found
		libc.so.6 (GLIBC_2.7) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.14) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.6) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.17) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.2) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.3.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
	/lib/x86_64-linux-gnu/libc.so.6:
		ld-linux-x86-64.so.2 (GLIBC_2.3) => /lib64/ld-linux-x86-64.so.2
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
	/lib/x86_64-linux-gnu/libm.so.6:
		ld-linux-x86-64.so.2 (GLIBC_PRIVATE) => /lib64/ld-linux-x86-64.so.2
		libc.so.6 (GLIBC_2.4) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_2.2.5) => /lib/x86_64-linux-gnu/libc.so.6
		libc.so.6 (GLIBC_PRIVATE) => /lib/x86_64-linux-gnu/libc.so.6

**Comment by Mbucari** [comment]
Thanks for the info guys!

@mverboom @firstWizball 

Can you try upgrading the libc version on you machines?

```console
sudo apt-get update
sudo apt-get install libc6
```

**Comment by mverboom** [comment]
For debian 11 there are no updates on my system.

```
dpkg -l libc6
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version         Architecture Description
+++-==============-===============-============-=================================
ii  libc6:amd64    2.31-13+deb11u5 amd64        GNU C Library: Shared libraries
```
BTW, did a recompile from scratch (app and ffmpeg), combined the own build ffmpeg library, and all is fine.

Regards,

Mark

**Comment by firstWizball** [comment]
did that and got the message
libc6 is already the newest version (2.31-0ubuntu9.9).

**Comment by Mbucari** [comment]
OK, it looks like all I need recompile ffmpegaac to target an older version of libc. Unfortunately that does not appear easy on linux. Look the the "official" method is to install an older OS and build on that. And those *nix folks mocked windows for "dll hell"...

BTW, this error only affects mp3. Loccless mp4 (aac) doesn't use the native library.

**Comment by mverboom** [comment]
Agreed. I used my debian 11 build server to compile ffmpeg. Compiling on the target is easiest..

**Comment by Mbucari** [comment]
I've rebuilt the aac decoding and mp3 encoding libraries so they only require glibc 2.14. It'll be in the next Libation release.

**Comment by rmcrackan** [comment]
Fixed in [latest version](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by firstWizball** [comment]
In the latest build this seems to have come back.  As I can download acc but not mp3.
