### ISSUE TITLE
"Strip audible branding" + "Split my books" is overclipping into the starting book audio (and breaking chapter splits too)

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#494]
**Describe the bug**

This is not ocurring with every book. Publisher doesn't appear to be a factor since I've hit examples from Tantor/Recorded Books, Upfront, and Blackstone but it seems to be almost all of the books I've tried lately from publisher christianaudio.com/echristian.   

Example book(s):
https://www.audible.com/pd/Good-Faith-Audiobook/B01CUTHFKG
https://www.audible.com/pd/Conversationally-Speaking-Audiobook/B08TZGDLF7
https://www.audible.com/pd/Lad-a-Dog-Audiobook/B00B77ME6S
https://www.audible.com/pd/Curiosity-Audiobook/B00WREMLIQ
https://www.audible.com/pd/Blood-Royal-or-The-Son-of-Milady-Audiobook/1799955648
https://www.audible.com/pd/An-Occurrence-at-Owl-Creek-Bridge-and-Other-Stories-Audiobook/B002V1BI66

Aligning the 'fixed' track and the original in Audacity I get the following:
The length of the "This is Audible" audio is ~01.861 seconds. From the tracks I tested it usually starts at .090 seconds, and ends at 01.951 seconds.  

The 'fixed' track starts at 3.762 seconds relative to the full track.
The 'fixed' track is only 1.858 smaller. This was confusing until I realized that it was because I have the books being split by chapter and the first file cuts into the second chapter, leaving the next file truncated, and the next and so on.

When I disable _Split my books_, it the beginning of the audiobook plays correctly and only the audible branding it stripped.

**To Reproduce**

1. Settings > Audio File Serttings
2. Enable _Split my books into multiple files by chapter_.
3. Enable _Strip audible branding from the start and end of audiobooks_
4. Download a book or 200.
5. Play first track

**Expected behavior**
- Only Audible branding audio removed, all other audio unaffected and chapters split accurately.

**Screenshots**
Here is a screenshot of all of my Audio File settings in case another setting is contributing to the problem:

![image](https://user-images.githubusercontent.com/1682957/219086434-43d20295-d420-413f-af67-8950ec5932a9.png)

**Platform**

Windows 10 2H22

**Log Files**
Log from "good faith" processing.
[Log20230215.log](https://github.com/rmcrackan/Libation/files/10745203/Log20230215.log)

**Comment by Mbucari** [comment]
Thank you for the very detailed bug report! This was a very tricky little bug to track down, and it would have taken a lot longer without all of the information you provided. I wish all users were this meticulous!

I've fixed it and it'll be in the next Libation release.

**Comment by rmcrackan** [comment]
Fixed in [latest version](https://github.com/rmcrackan/Libation/releases/latest)
