### ISSUE TITLE
Chapter splitting sometimes produces tiny malformed files

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#495]
**Describe the bug**
I have not been able to discern a pattern other than it's usually larger books, and it's the chapters toward the end. Downloading the book without splitting, the chapters are not malformed and play correctly.

I've also tested with OpenAudible and it splits the chapters correctly.

Example book:

https://www.audible.com/pd/The-Big-Book-of-Reel-Murders-Audiobook/1684576881

**To Reproduce**

1. Settings > Audio File Serttings
2. Enable _Split my books into multiple files by chapter_.
4. Download a book or 200.
5. Check filesizes

**Screenshots**

![image](https://user-images.githubusercontent.com/1682957/219115852-4c22c123-a28a-4648-984a-c0d9440a50b5.png)

**Platform**

Windows 10 2H22

**Log Files**

[Log20230215-1.log](https://github.com/rmcrackan/Libation/files/10746107/Log20230215-1.log)

**Comment by Mbucari** [comment]
Thanks for the bug report. It's fixed and will be in the next Libation release.

**Comment by rmcrackan** [comment]
Fixed in [latest version](https://github.com/rmcrackan/Libation/releases/latest)
