### ISSUE TITLE
macOS: Avalonia Application quit unexpectedly (v.9.3.2)

### ISSUE THREAD

**Issue by srustamo** [rmcrackan/Libation#501]
**Describe the bug**
Avalonia Application quit unexpectedly.

**To Reproduce**
Unarchive, move app to Appliations folder;
Run 
"""
sudo spctl --master-disable && sudo spctl --add --label "Libation" /Applications/Libation.app && open /Applications/Libation.app && sudo spctl --master-enable
"""
Save configuation.
Click on Libation.app in Applications folder. Get the error: Avalonia Application quit unexpectedly.

**Expected behavior**
Open the app successfully.

**Platform**
macOS 10.14.6 (18G9323)

**Log Files**
[Log202302.log](https://github.com/rmcrackan/Libation/files/10765543/Log202302.log)

Attach your Libation log file here.

**Comment by Mbucari** [comment]
Dotnet doesn't support OSX 10.4. The oldest supported version is 10.5.
