### ISSUE TITLE
Strip Audible + Split Chapters Still Truncating Chapters

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#502]
**Describe the bug**
This is a followup to #494.

The beginning of the first file is no longer clipped but the chapter divisions are still off. 

I have not had time to investigate like I did with the previous but it _seems_ like the amount of time that the first file is extended, cutting into the second chapter is about the same length as the "This is Audible" intro (if I had to guess).

Example: https://www.audible.com/pd/Discussing-Design-Audiobook/B08WH2MMMF 

1. Settings > Audio File Serttings
2. Enable Split my books into multiple files by chapter.
3. Enable Strip audible branding from the start and end of audiobooks
4. Download a book or 200.
5. Play _second_ or subsequent track(s)

**Comment by Mbucari** [comment]
> or 200.

Off, I felt that.

Can you please download a [patched version from here](https://github.com/Mbucari/Libation/actions/runs/4209929268) and run it through its paces? Please report back with any other errors/bugs you find. Thanks!

**Comment by manalive** [comment]
@Mbucari 

I was going to tell you it wasn't fixed, but it turns out that the second chapter (forward) in the unsplit file (of the example audiobook I listed in the description) is off by a second or so.

I tested with two other books that had misaligned chapters, and it seems to be .splitting correctly.

**Comment by rmcrackan** [comment]
Fix will be included in the next version 9.3.3 which I'll release today.

**Comment by rmcrackan** [comment]
Fixed in latest -- [v9.3.3](https://github.com/rmcrackan/Libation/releases/latest)
