### ISSUE TITLE
Auto-Update intermittent failure

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#505]
Auto-update is occasionally failing. It appears to happen when I'm too quick to close the main window. The "waiting for main application to exit" window just sits there after I close the main window. The Zip extractor has already run, it should be ready to start the update, but it doesn't. If I kill that window, and restart Libation, it again prompts for the update, and this time it goes through. 

Windows 11, build 22621
Libation Classic 9.3.3.1

**Comment by Mbucari** [comment]
@CharlieRussel this is a known bug in the updater program. For some reason when the updater starts, libation doesn't completely close. The window closes, but the process is still running so the update or can't start. As a workaround, you can go to task manager and kill the libation process.

**Comment by CharlieRussel** [comment]
@Mbucari -- OK, so just be patient and wait a bit longer before killing the window. Or resort to Stop-Process. (Seriously, why use taskmanager for something simple like killing  a process? Especially since I always have at least two PowerShell windows open (one regular, one admin level).

**Comment by rmcrackan** [comment]
Am I correct that there's nothing more to be done on this issue?

**Comment by CharlieRussel** [comment]
The only workaround that I can see is to not start the main libation process at all if the user selects yes to update but just go ahead and do the update before the main window starts.

**Comment by Mbucari** [comment]
@CharlieRussel I wouldn't be patient at all. If you close Libation and zip extractor is hanging, kill the process. Libation doesn't need to shut down gracefully, so you can just kill it.

**Comment by rmcrackan** [comment]
Fixed in [v9.4.2](https://github.com/rmcrackan/Libation/releases/latest)
