### ISSUE TITLE
Infinite CAPCHA loop when trying to import audible library and don't have Audible logins only amazon

### ISSUE THREAD

**Issue by fractaldonut** [rmcrackan/Libation#508]
Hi, 

Thank you very much for the application!

When I try authenticate my audible account through the app when trying to import my library I get an infinite CAPCHA loop. I also can't login through the browser because I dont have an audible account - I use amazon details to log in to audible and these don't work when I try the login through the browser route. 

I actually managed to import my library before but I removed all the titles because I wanted to redownload them in mp3 after changing the default file format to this in the settings. It is after removing my audible account from Libation and reconnecting it that I am running into these problems. I have also tried on separate days  to get around the CAPCHA loop as suggested in one of the previous issues. 

Any advice would really be appreciated, thanks again!!

**Comment by Mbucari** [comment]
Hey @fractaldonut. The username/password login system isn't working at the moment. [Use the external login method instead](
https://github.com/rmcrackan/Libation/issues/507#issuecomment-1441651949).

**Comment by fractaldonut** [comment]
Hi @Mbucari, the external login method isn't working for me either. I assume its because I dont have an audible account - I use amazon details to log in to audible and these don't work when I try the login externally through the browser. Is that right and if so is there any way I can authenticate? Thanks for your help

**Comment by Mbucari** [comment]
@rmcrackan is really the expert in this area.

**Comment by Mbucari** [comment]
one thing you could try is using [audible-cli](https://github.com/mkb79/audible-cli/releases/tag/v0.2.4) to log into your account. Once you do that, you can import audible-cli's auth file into libation.

**Comment by rmcrackan** [comment]
While we're experiencing issue with the in-app login, the browser method is the only way. It really should work for everyone since it's directly on amazon. Can you detail what's going wrong?

**Comment by fractaldonut** [comment]
There are two different sets of credentials with which you can have an audible account: audible and amazon. The login menu that I reach by visiting the link you provide in the 'Login through the browser' option is titled: "Sign in to Audible using your Audible username" (see screenshot). I don't have an audible username and only have amazon details. Equally when I sign in to audible normally through the browser, there are these two different paths to login, and when I click 'sign in using audible username' and enter my details it doesnt work. I can only log in by using the 'login with amazon account' way. 

Is there any way for people who only have amazon details and not a audible username to import their library currently?


<img width="760" alt="Screenshot 2023-02-24 at 10 44 00" src="https://user-images.githubusercontent.com/50805308/221159418-04ee78ac-5fd9-4321-a396-6f999de9b22e.png">

**Comment by rmcrackan** [comment]
When you create the account entry in Libation, you have to select your region from a dropdown. Among the options are `pre-amazon - us` (also uk and germany). With that selected, the browser login should send you to the correct login place.

**Comment by rmcrackan** [comment]
The new [version 9.4](https://github.com/rmcrackan/Libation/releases/latest) fixed previous login errors. Sorry for the trouble.
