### ISSUE TITLE
Default installation is too confusing

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#510]
Initial installation should be less confusing. New users won't yet know enough about settings in order for that box to be meaningful. The 'new user' flow just needs very simple instructions for how to add their audible login(s).

**Comment by CharlieRussel** [comment]
If you want, I could probably take a crack at writing up some basic instructions. Unfortunately, they would be Windows only, given I’ve never used a Mac and I don’t currently have a Linux box.

**Comment by rmcrackan** [comment]
Sure.

This ticket is more for changing the program so it has better flow. I welcome write ups also :)

**Comment by CharlieRussel** [comment]
OK, I'm working on a detailed initial installation document, using Chardonnay on Windows. And I think it will help, but it has raised a couple of things that I think would be useful in terms of "flow":
1.) Explicit prompting for region/password as part of the initial installation -- sort of like Windows does, for example. 
2.) Prompt for filename templates as part of that initial installation. I suspect most people want a more specific file/folder layout than the default, but it's a pain if you don't do that up front. 

There are some others, but I need to think them through a bit. It's tricky to put my "new user" hat on, now that I sort of know how it all fits together, and I need to do some more thinking on that.

**Comment by Mbucari** [comment]
@rmcrackan How about we just don't show the settings window on a fresh install? Just load up the defaults. Defaults are fine for people to get their feet wet, and if they want more they can poke around in the settings menu.

**Comment by rmcrackan** [comment]
That's a good idea. I always assumed people would minimally want to choose where there books get downloaded to. This was also a choice that was made back when there were literally, like, 5 settings. These days -- yeah -- I prefer your idea.

**Comment by rmcrackan** [comment]
Fixed with style in v10
