### ISSUE TITLE
Chardonnay Memory Leak

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#511]
When the grid is reloaded in Chardonnay, (on library scan and when a book is "removed"), the DataGrid retains references to the old GridEntry objects so the GC cannot free them. This causes a pretty massive memory leak.

I'll need to do in chardonnay what classic already does: update existing GridEntry objects instead of instantiating new ones.

**Comment by rmcrackan** [comment]
Was this addressed in the latest PR? I usually don't give the Avalonia changes a lot of attention so I wouldn't have noticed.

**Comment by Mbucari** [comment]
Sorry, no. It's actually kind of involved. I took a massive shortcut when I made the main grid. I tried doing what you did in classic, calling `BindToGrid` to load the library on init and then using `UpdateGrid` to process changes, but I ran into a series of problems that are non-trivial to fix without causing the grid to flicker too much.

**Comment by rmcrackan** [comment]
No worries -- take your time. I was just going through tickets to see what I might be able to close.
