### ISSUE TITLE
Libation Mac doesn't open

### ISSUE THREAD

**Issue by sveinbjornpalsson** [rmcrackan/Libation#513]
**Describe the bug**

App won't open. App startup doesn't begin.
(sorry, describing this issue is weird)

**To Reproduce**

- right-click to open app.
- It immediately shows this message "The application “Libation” can’t be opened."
- I also get the usual open dialog, unknown developer and that. But that's it. Doesn't open.

**Expected behavior**

I expected to open the app I downloaded.

**Screenshots**
<img width="560" alt="Screenshot 2023-02-25 at 22 35 18" src="https://user-images.githubusercontent.com/7467567/221382812-5753269a-479a-43f8-92df-34834a21be01.png">

**Platform**

MacOS Ventura 13.1 - MBP M1 Max

**Log Files**
n/a
<img width="560" alt="Screenshot 2023-02-25 at 22 35 18" src="https://user-images.githubusercontent.com/7467567/221382830-8c97db16-0c08-4b17-82c7-115aeaf2aa94.png">

**Comment by Mbucari** [comment]
@sveinbjornpalsson Yeah, there's a problem with the arm64 builds right now.

Make sure you've moved Libation to your Applications folder, then run this command:

```
codesign --force --deep -s - /Applications/Libation.app && sudo spctl --master-disable && sudo spctl --add --label "Libation" /Applications/Libation.app && open /Applications/Libation.app && sudo spctl --master-enable
```

**Comment by nrogovik** [comment]
> @sveinbjornpalsson Yeah, there's a problem with the arm64 builds right now.
> 
> Make sure you've moved Libation to your Applications folder, then run this command:
> 
> ```
> codesign --force --deep -s - /Applications/Libation.app && sudo spctl --master-disable && sudo spctl --add --label "Libation" /Applications/Libation.app && open /Applications/Libation.app && sudo spctl --master-enable
> ```

This works, please update the docs which command does not work, thanks! https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md

**Comment by Gatewayy** [comment]
That command gives the following error:

codesign --force --deep -s - /Applications/Libation.app && sudo spctl --master-disable && sudo spctl --add --label "Libation" /Applications/Libation.app && open /Applications/Libation.app && sudo spctl --master-enable
The application cannot be opened for an unexpected reason, error=Error Domain=RBSRequestErrorDomain Code=5 "Launch failed." UserInfo={NSLocalizedFailureReason=Launch failed., NSUnderlyingError=0x60000079d380 {Error Domain=NSPOSIXErrorDomain Code=153 "Unknown error: 153" UserInfo={NSLocalizedDescription=Launchd job spawn failed}}}

**Comment by Gatewayy** [comment]
So I updated to the latest point release and restarted and now the command runs the app bundle without issue.

**Comment by rmcrackan** [comment]
Fixed in [v9.4.2](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by Mbucari** [comment]
@Gatewayy Pleaselet us know if the app still crashes after the latest update. It shouldn't, but...

**Comment by nrogovik** [comment]
Working good here, thanks!

**Comment by Gatewayy** [comment]
Sadly, it still crashes.

**Comment by Mbucari** [comment]
@Gatewayy dies it generate a lot ful in [user]/Libation? If so, please post it.

**Comment by Gatewayy** [comment]
the only file in that directory currently is the settings.json.

**Comment by Mbucari** [comment]
@Gatewayy there's no appsettings.jsom file?

**Comment by sveinbjornpalsson** [comment]
New version works fine on my end, thanks!

**Comment by Mbucari** [comment]
@Gatewayy can you please create a new issue with everything your experiencing? Delete that Libation folder and re-download the latest version. Run through all of the installation steps in the wiki, and post what happens. Thanks!

**Comment by Gatewayy** [comment]
Alright, I finally am able to open the app, set preferences, save an account, and import the list of audiobooks on my Audible US account.  I removed that application, re-downloaded the latest release, Nuked my Libation Folder via CLI, re-ran the CLI command and set everything back up again from scratch.  Something was obviously corrupted so the "nuclear option" seems to have worked.
