### ISSUE TITLE
No way to actually remove titles no longer in library

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#514]
When we 'remove' titles which are no longer in the user's audible library, they are now only soft deleted. Which means this sequence puts us in a weird state:

* add podcast on audible
* scan libation to import podcast
* remove podcast on audible
* 'remove books' on libation. These titles are soft deleted
* re-add podcast on audible
* scan libation
* episodes do not show up again

**Comment by fractaldonut** [comment]
I think the error is actually more general than that and that it occurs even without steps 3 & 5

[@517 ](https://github.com/rmcrackan/Libation/issues/517)

**Comment by Mbucari** [comment]
What if we change the "Save" button in Hangover's deleted books tab to "Restore" and add a "Remove from Database" button?

**Comment by rmcrackan** [comment]
I like both ideas. If I can ever get any free time (and if you don't beat me to it) my other idea was to see if the removed book was still part of the active audible library. This is easy in the mass 'remove books' feature since we've already query that. The hang up is: it has more overhead when removing a book any other way and I'm less happy about that.

Actually, 'remove from database' might be better worded as 'fully delete from Libation' or similar. Dammit -- I knew this would happen: once remove was an option, we needed an un-remove and now we are exposing Hangover to everyone which means we have to care about crap like this. I really should never have released the soft delete feature into the wild until I had an in-app way to un-soft-delete. I knew better and I let user requests make me feel pressured to be a people pleaser instead of waiting until it was ready. ::sigh:: Oh well. It is what it is and we can only move forward.

**Comment by Mbucari** [comment]
The Removal Books tab is pretty basic. If you don't like it and hangover, it wouldn't be difficult to implement the same dialogue window inside libation. You could even use the Trash metaphor. Items can either be restored or you can empty the trash.

**Comment by rmcrackan** [comment]
Good point. There's certainly precedent in mac and windows for a trash bin limbo.

**Comment by rmcrackan** [comment]
I answer this damn question almost daily on reddit. (Actually 3x yesterday.) I'm kicking myself for releasing this before having a real solution. I guess we made it too easy to accidentally remove books ☹️

**Comment by rmcrackan** [comment]
@Mbucari : 

![Who's awesome?](http://www.quickmeme.com/img/e5/e56c5591a895603b5e41c61c0f930d19aa87cfc00f6c77761e8fcd23102d709c.jpg)
