### ISSUE TITLE
Can't Download Episodes of a Series on Libation V9.4.0.1

### ISSUE THREAD

**Issue by student8271** [rmcrackan/Libation#516]
**Describe the bug**
Unable to download audiobooks that are part of a series.

**To Reproduce**

1. Go to the main window.
2. Click on the plus sign next to the name of a series.
3. Click on the stop light sign next to the name of a part of the series.
4. Get an error message.

**Expected behavior**
Libation should download the audiobooks, but it doesn't.

**Screenshots**
<img width="777" alt="Screenshot 2023-02-26 at 11 43 44 AM" src="https://user-images.githubusercontent.com/95700971/221395468-82d3e044-5fc4-458b-ab19-693cc1ec4984.png">

**Platform**

macOS 12.6.2 (21G320)

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
Please post your log file and a link to the series you're unable to download.

**Comment by rmcrackan** [comment]
This ticket seems to have gone cold so I'm closing it. If you have additional info, please reply and I'll be happy to re-open it.
