### ISSUE TITLE
Library Scan Does not find Audiobooks after they were Imported Before and then Deleted

### ISSUE THREAD

**Issue by fractaldonut** [rmcrackan/Libation#517]
Import -> Scan Library produces the 'scanning response' in the top right corner but then nothing happens. This is despite me having audiobooks on the connected account and those titles not being in the application (I have 12 audiobooks and none download)

I have in the past imported all 12 successfully but then deleted them as I wanted to import them as mp3s instead and now its not working. Is there an auxiliary file that I need to delete to reset the application so I can import the audiobooks?

Massive thanks for the application and for the support <3

**Comment by CharlieRussel** [comment]
Use the Hangover app (in the main Libation folder) to resolve this. You might have to tell it to run it despite a warning from Defender.

**Comment by CharlieRussel** [comment]
You'll need to run hangover As Administrator, and you will see something like this:
![image](https://user-images.githubusercontent.com/21000516/221714469-8ba6cdf7-a9a0-4460-bc20-100ed651c0dc.png)
Check the box next to the files you want to restore and click Save.

**Comment by fractaldonut** [comment]
That worked. Thank you!

**Comment by rmcrackan** [comment]
@CharlieRussel Thanks for the tech support! :)

@fractaldonut To download a book again, set it to 'not downloaded' and it will be downloaded again on your next attempt. There are a few places to do this: right click on the left hand stop light button, click on the right hand tags/details button, or in bulk using the top 'visible books' menu. Sorry for the confusion for how to do this. I know documentation and a clunky interface are among Libation's failings. Thanks for reaching out with your question.

**Comment by CharlieRussel** [comment]
@rmcrackan it was an easy one, since I’d had to ask the same question a couple of months ago. ;)
