### ISSUE TITLE
File.Move block UI

### ISSUE THREAD

**Issue by Mbucari** [rmcrackan/Libation#519]
Books are moved from the temp folder to the books folder after downloading. If those folders are on different drives, File.Move has to copy the files. For some reason, that operation block the UI even if it's run inside an async Task. It becomes a real problem when downloading podcasts on a fast internet connection. They download so quickly that the move operation takes up most of the time, resulting in a nearly full-blocked UI.

The only way I can see the fix this is to read/write the file asynchronously.

@rmcrackan do you have any ideas?

**Comment by rmcrackan** [comment]
I have no idea why the async should block. However instead of a move, you could do a copy then delete. The top 2 or 3 answers to [this SO question](https://stackoverflow.com/questions/882686/non-blocking-file-copy-in-c-sharp) have straight forward solutions. For the delete I'd just wrap it in a Task.Run, but again, I don't know why your file processing is blocking when in async.

**Comment by Mbucari** [comment]
You're right, Task.Run does work for the File.Move. I was mistaken about that being the problem. The true culprits all the finishing tasks running after a book has downloaded that are running synchronously.

- SetCoverAsFolderIcon
- UpdateBookStatus
- downloadCoverArt

I changed it to this, and it's a LOT smoother.

```C#
Task[] finalTasks = new[]
{
  Task.Run(() => WindowsDirectory.SetCoverAsFolderIcon(pictureId: libraryBook.Book.PictureId, directory: finalStorageDir)),
  Task.Run(() => libraryBook.Book.UpdateBookStatus(LiberatedStatus.Liberated)),
  Configuration.Instance.DownloadCoverArt ? Task.Run(() => downloadCoverArt(libraryBook)) : Task.CompletedTask
};

await Task.WhenAll(finalTasks);
```

Check out this CPU profiler chart.
![image](https://user-images.githubusercontent.com/37587114/221926507-9e617a06-3079-4d84-ba97-374dee224bd4.png)

**Comment by rmcrackan** [comment]
A fine idea. After the book is done processing, I imagine most if not all of the subsequent serialized steps could be done in parallel

**Comment by Mbucari** [comment]
I've fixed this. I also found a way to set folder icons in macOS. How cool is that?

**Comment by rmcrackan** [comment]
> I also found a way to set folder icons in macOS

Nice!! I forgot that was a thing in mac-world. I had 1 mac for a long time but that was quite a while ago. I'd completely forgotten that some programs did that, even back then. So cool that you figured it out. How hard is it in C#?

**Comment by Mbucari** [comment]
> How hard is it in C#?

I might be going too far and saying I "figured it out", because some wonderful developer built and for the last 8 years has maintained [a bash script that does it](https://github.com/mklement0/fileicon). All I had to do was add the script to the project and run it with a one-liner.

**Comment by rmcrackan** [comment]
Fair enuf. Thanks for discovering and adding it.

Really, I didn't "figure out" several of the cornerstone pieces of tech in Libation. I did a complete disassemble of inAudible which itself just leveraged ffmpeg and a few other libraries, a deep code dive into OpenAudible back when it was easy to disassemble java, a line-by-line re-write of this weird but innovative crystal-lang audible api which pre-dated mkb79, another line-by-line translation of mkb79's lib... Obviously I did a boatload of my own coding too but most of the break-through tech was someone else's work that I improved upon. Then you've improved on much of what I've written and I dearly hope there will be others in the future that will build on top of us.

**Comment by Mbucari** [comment]
> Fair enuf. Thanks for discovering and adding it.
> 
> I dearly hope there will be others in the future that will build on top of us.

Ditto. And I really hope that audible doesn't change their encryption scheme again anytime soon, because I am a piss-poor Android reverse engineer. I'm damned good on Windows, but I'm totally lost in Android and I don't own an iphone. If Audible still maintained their Windows metro app, I'd have a chance. But without that I think I'm totally out of luck.

**Comment by rmcrackan** [comment]
The people who will save our bacon when that next happens are the ones who did so last time -- ffmpeg. That app/community is fucking magic. Judging from how long audible kept with aa vs aax vs aaxc, I feel confident that they aren't going to change again anytime soon.
