### ISSUE TITLE
Error scanning library

### ISSUE THREAD

**Issue by qtrolazygo** [rmcrackan/Libation#521]
When I select the option to scan the library an error occurs

1. Open Libation (version is 9.4.2.1)
2. Select the Import menu item
3. Click on the Scan Library option
4. An "Error Importing Library" dialog shows

**Expected behavior**
The Library should be updated with the latest items 

**Screenshots**
![Error screenshot](https://user-images.githubusercontent.com/126741005/222320171-9e2501bb-cdde-4c07-83be-d5dd7322fa71.png)

**Platform**
Edition	Windows 11 Pro
Version	22H2
OS build	22623.1325
Experience	Windows Feature Experience Pack 1000.22639.1000.0

**Log Files**
[Log202303.log](https://github.com/rmcrackan/Libation/files/10867154/Log202303.log)

**Comment by Mbucari** [comment]
I'm pretty sure this is a network error. See the error message:

> The request failed due to an underlying issue such as network connectivity, DNS failure, server certificate validation or timeout.

Are you able to try on a different internet connection? If not, try waiting for a day and seeing if it resolves itself.

**Comment by rmcrackan** [comment]
This ticket seems to have gone cold so I'm closing it. If you have additional info, please reply and I'll be happy to re-open it.
