### ISSUE TITLE
VISIBLE 0 BOOKS

### ISSUE THREAD

**Issue by justofficial2023** [rmcrackan/Libation#523]
**Describe the bug**
I HAVE MANY BOOKS BUT AFTER NEW UPDATE IT SHOW VISIBLE 0 BOOK
![Screenshot 2023-03-05 165128](https://user-images.githubusercontent.com/127023362/222957428-75e5ff86-6177-457d-8984-d794af47947a.png)
![Screenshot 2023-03-05 165128](https://user-images.githubusercontent.com/127023362/222957443-578e49e7-80d2-4d02-a471-fbf69660ed95.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
Please attach your log file.

Go to Settings and click "Open log folder"

Then attach the most recent file starting with "Log" or "_Log"

**Comment by justofficial2023** [comment]
[Log202303_002.log](https://github.com/rmcrackan/Libation/files/10917008/Log202303_002.log)

**Comment by Mbucari** [comment]
It looks like at least one of the cover art images is corrupt. Try deleting the "Images" folder and restarting Libation.

**Comment by rmcrackan** [comment]
Fixed in latest :)
