### ISSUE TITLE
Please add series # to grid display

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#529]
It would be useful in trying to see where I have blanks that I might want to infill if I could see the series # in the grid display. So, currently, it shows "Series", but if the series is "Inspector Lynley", having "Well-Schooled in Murder" show as 3rd in the series would be useful. And if it showed as 3 of 21, that might be even more useful. (Not sure you currently have the total number, plus it's something that's subject to change and even interpretation, so less important.)

**Comment by chieftwidgit** [comment]
File sent.  Please verify

**Comment by CharlieRussel** [comment]
Currently, you list series, sub-series, and merged series separated by a comma in the Series column. Not ideal, but workable given the limitations of most grid systems (what a perfect grid system would look like is a rabbit hole we probably don't want to go diving down!). Given that, the simplest answer is to list the books place in each series, in the order they appear in the Series column, separated by the same comma. Giving the primary series only is probably also acceptable. 

(if it weren't too annoying, I'd prefer semicolons as separators for both, but that's just me being cranky.)

**Comment by chieftwidgit** [comment]
Sorry I was sure I replied to #528.

**Comment by wtanksleyjr** [comment]
This is something I use Audiobookshelf for all the time, its Series view
lets you see what books are included in each subseries. (You know, if you
want to see how the competition does it ;) .

-Wm

**Comment by Mbucari** [comment]
@rmcrackan @wtanksleyjr For viewing series, we could add a separate window like we did for "Records" (accessed via the book's context menu > "View Bookmarks/Clips". That window could live query the audible series ID and display all titles that are part of that/those series.

**Comment by Mbucari** [comment]
Check this out:

[](https://user-images.githubusercontent.com/37587114/225118608-b9d20c54-716a-4cfb-afe2-93ea2a34dd5f.mp4)

**Comment by Mbucari** [comment]
> So this is what people can do when they aren't stuck in meetings all day :)

One of the few perks of being overqualified for ones work.

> That's a really cool demo!

Thanks! I also figured out how to distinguish available books from unavailable books. If you query the catalog endpoint with an unauthenticated request, Audible doesn't know if you're able to purchase the item or not so the items look identical. But if you make an authenticated request, books that are unavailable to you will have a null Price.

**Comment by rmcrackan** [comment]
Nice. As in: unavailable for purchase? Cool. Sounds like the perfect time for a convenience property on the DTO for `IsAvailable => Plan is not null` or something like that.

I've been meaning to ask: since you added the way to get the json from the DTO, am I correct that it returns the original json? And this means that won't contain the duplicate properties that we created. Eg: the IsAvailable flag above

**Comment by Mbucari** [comment]
> As in: unavailable for purchase?

Yup. as an example, both these versions of "Ball Lightning" are children of the "Three-Body Problem" series: [[B07BWM5YXL]](https://www.audible.com/pd/Ball-Lightning-Audiobook/B07BWM5YXL) and [[B07F9ZD3W8]](https://www.audible.com/pd/Ball-Lightning-Audiobook/B07F9ZD3W8)

But only the second is available for purchase. If you make an authenticated request, the unavailable one's price is null.

> Sounds like the perfect time for a convenience property on the DTO

Great idea. I'll add that to my open PR.

> am I correct that it returns the original json and that it won't contain the duplicate properties that we created?

Yup. It's the verbatim response. I thought it would be nice for logging, but it's been WONDERFUL for development as well. It's so nice to have that info within Libation.

**Comment by rmcrackan** [comment]
Logs are like sex. When they're good, they're great. And when they're bad, they're still better than nothing.

**Comment by Mbucari** [comment]
check out this demo!


[](https://user-images.githubusercontent.com/37587114/225403148-0c5f6a41-f985-4c79-85cd-daba91dcc7f9.mp4)

**Comment by rmcrackan** [comment]
Oh hell yes! That's badass

Minor suggestion: 'Add to library' should say include like included/Plus/free ... basically just something to assure the user that we aren't about to use their credit.

Unrelated: After this Friday (3/17) I'm out of pocket until 2 Mondays later (3/27) so let's not release anything else major. Truly, I may not be able to do a thing about it and that could be ugly.

**Comment by Mbucari** [comment]
> Oh hell yes! That's badass

Yeah, I'm _really_ happy with how it's shaping up. 
> 'Add to library' should say include like included/Plus/free

Good idea.

> out of pocket until 2 Mondays later (3/27) so let's not release anything else major.

That's fine. This demo was relatively quick to whip up, but polishing it into a final feature will take some time. There are still a lot of design and architectural choices to make, and those always take a lot of iterations to refine.

@CharlieRussel, sorry I kind of hijacked this issue from you, but I'll add in your request ;)

**Comment by CharlieRussel** [comment]
@Mbucari That’s quite alright. I view myself as a gardener here. Planting a seed, and wondering what it will grow into.

**Comment by Mbucari** [comment]
@CharlieRussel Are you're trying to fertilize me, too? 🤣

**Comment by CharlieRussel** [comment]
@Mbucari  Absolutely. In my experience, nothing works better than well rotted bull pucky.

**Comment by Mbucari** [comment]
@wtanksleyjr can you please test out the series view feature in my preview build? I think it's pretty darn sweet, but I'd love some feedback. 
https://github.com/Mbucari/Libation/actions/runs/4474423544

**Comment by CharlieRussel** [comment]
@Mbucari & @rmcrackan  I don't see the series index column (hidden or otherwise) in 9.4.7. Is this coming in a future build? Or did I just miss something. Or did you decide against it. (Perfectly valid -- it's your baby!)

**Comment by rmcrackan** [comment]
No new column in the main grid. The main grid now has the series position in parentheses in the normal Series column. I believe Mbucari has some more work he wants to do on this feature.

There's lots more info in the new series view: Right click the image of a book which is in a series => "View all books in series".

**Comment by CharlieRussel** [comment]
@rmcrackan -- "Right click the image of a book which is in a series => "View all books in series" -- Yup, I like it. My only problem is with a couple of series where there is no meaningful series index, only "#999999999" for each episode. (@Audible -- seriously, that's the best you could do??!!)

**Comment by rmcrackan** [comment]
Completed in v10
