### ISSUE TITLE
Error Importing Library

### ISSUE THREAD

**Issue by leitourgia** [rmcrackan/Libation#533]
**Describe the bug**
Failing to import new titles

**To Reproduce**

1. Import
2. Click on 'Scan Library of All Accounts'
3. See error

**Expected behavior**
New titles should be scanned and added to list.

**Screenshots**

**Platform**
Windows 11

**Log Files**
Attach your Libation log file here.
[Log202303_003.log](https://github.com/rmcrackan/Libation/files/10981777/Log202303_003.log)
[Log202303_004.log](https://github.com/rmcrackan/Libation/files/10981778/Log202303_004.log)
[Log202303_001.log](https://github.com/rmcrackan/Libation/files/10981779/Log202303_001.log)
[Log202303_002.log](https://github.com/rmcrackan/Libation/files/10981780/Log202303_002.log)
[Log202303.log](https://github.com/rmcrackan/Libation/files/10981781/Log202303.log)

**Comment by Mbucari** [comment]
@leitourgia thank you for the logs

@rmcrackan Can you please look at this? It's all EF errors, and you're by far the most qualified to deal with those.

I'm concerned by this error message: `'duplicate column name: Language'.`

How is that even possible? Did the migration run twice???

**Comment by rmcrackan** [comment]
That *shouldn't* be possible. I'd have to take a look at the database to be sure. You can upload to https://wetransfer.com or similar and [email me](https://github.com/rmcrackan) the download link. It's this file which is next to your logs: `LibationContext.db`

**Comment by rmcrackan** [comment]
This ticket appears to have gone cold so I'll close it. If you have more info, please reply here or email me as per above and I'll be happy to re-open it.
