### ISSUE TITLE
Shortcut ALT-L conflicted with Apple-@ (ALT/Option-L)

### ISSUE THREAD

**Issue by elvquant** [rmcrackan/Libation#534]
On MacOS the @ has keystroke ALT/Option-L. Typing this in filter-field i then open up the "Liberate"-menue

ALT-I ⁄
ALT-L @
ALT-X ≈
ALT-F ƒ
ALT-V √
ALT-S ‚

**Comment by Mbucari** [comment]
This isn't actually a bug. These are shortcut keys to access menu items. If you just press the alt key, you'll see certain letters in the menu names get underlined. The underlined letter is the alt key code that opens that menu. As you've discovered, Alt+L opens the liberate menu.

**Comment by elvquant** [comment]
ALT-L is the traditional keystroke on macOS for @, like ALTGR-Q on Windows. Traditional CMD-Keys on Apple are for Menue based shortcuts. ALT opens the third level of keys on the keyboard on Apple Systems. (1st normal, 2nd shift, 3rd ALT, 4th Shift-ALT)
Its a minor-mini issue, of course and a work around is to copy'n'paste (CMD-C/CMD-V) data to the filter field.
<img width="644" alt="Apple-ALT" src="https://user-images.githubusercontent.com/14792545/225751323-bfe22fe4-e305-41b1-ae78-d5a588108b87.png">
<img width="644" alt="Apple-ShiftALT" src="https://user-images.githubusercontent.com/14792545/225751346-34ad1e42-1100-42c1-ab2d-fda85f3f0887.png">

**Comment by rmcrackan** [comment]
@elvquant On Mac, does ALT typically open up menus for the active program?

@Mbucari Is [this](https://github.com/AvaloniaUI/Avalonia/issues/5976) the same issue?

**Comment by Mbucari** [comment]
It looks like native menus are actually supported.
https://github.com/AvaloniaUI/Avalonia/issues/898#issuecomment-1025460399

I need to see what they do on Windows and Linux before I commit to using them, but it looks promising.

**Comment by Mbucari** [comment]
Let's focus on the Alt key problem in this issue. Native menus are a separate issue.

[We cannot change the alt key for menu item accelerators](https://github.com/AvaloniaUI/Avalonia/discussions/10690). It's hard-coded. @rmcrackan The issue you linked to is about swallowing the alt keypress.

The only way to not swallow the alt key and have menu shortcuts is to the Avalonia's built-in hotkeys. I'll look into it.

**Comment by Mbucari** [comment]
@elvquant I think I've fixed the hotkey problem, but I don't have a mac to test. Would you mind downloading and testing [the preview build](https://github.com/rmcrackan/Libation/actions/runs/4578834434)?

**Comment by Mbucari** [comment]
Specifically, please test if the shortcut keys actually work. Alt no longer triggers shortcuts, but I'm not sure if ⌘ _will_. Try ⌘+V to see if it opens your Visible Books menu.

**Comment by Mbucari** [comment]
Alright, I've confirmed that the mac command key now works for menu quick access.

Also, I've fixed the native menu:
![Screen Shot 2023-04-01 at 12 53 49 PM](https://user-images.githubusercontent.com/37587114/229309203-2a15041c-f8ec-4f3c-a412-5e0ba0f2d4de.png)

I _could_ use native menus for Libation's entire menu bar, but unfortunately doing that would break the new guided tour. So for now, it's staying inside the Libation window.

**Comment by Mbucari** [comment]
@rmcrackan We need a better "About" page.

**Comment by rmcrackan** [comment]
@Mbucari you say that as if it's possible to have a *worse* one

**Comment by CharlieRussel** [comment]
@Mbucari & @rmcrackan -- It would be good to have it include a link to the latest update in there. Just for those folks who have initially declined the update but now want it. And it's a fairly typical inclusion.

**Comment by Mbucari** [comment]
> @Mbucari you say that as if it's possible to have a _worse_ one

I was trying to think of something worse for a snarky reply, but I couldn't. You're right, it literally could not be any worse.

@CharlieRussel good call

**Comment by Mbucari** [comment]
@CharlieRussel @rmcrackan 
![image](https://user-images.githubusercontent.com/37587114/229370086-2cf31599-b620-4cca-82e8-8037a03e2263.png)

**Comment by CharlieRussel** [comment]
@Mbucari I like it, though I'm not 100% convinced that Loaded Assemblies makes any sense to 99% of your users. But maybe an Acknowledgements section, now that we've had more than just @rmcrackan working on this?

**Comment by Mbucari** [comment]
@elvquant it's live with version 10.0.4

**Comment by elvquant** [comment]
Fantastic. Thanks a lot, again (after pre-amazon-germany lightspeed fix)
