### ISSUE TITLE
When book is unavailable, check other accounts

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#535]
As I understand how the scanning feature works, a book is added to the grid from the first account that has it and is ignored on the other accounts/regions. 

**Describe the solution you'd like**
Now that we have the new improved hotness of availability checking, it would useful if books that are unavailable would be rechecked against the other accounts to see if they are available there and then the grid item swapped out for the first one that shows available (if any).

**Comment by Mbucari** [comment]
I was thinking about this issue yesterday, and the approach I was considering was to use the availability criteria to decide which library book gets imported into the database. Currently, first in wins and is added to the db, and all duplicates are discarded. If instead we change the criteria to first available book wins, we could ensure that all books available to the account holder are also available to be backed up within libation.

@rmcrackan sound good?

**Comment by rmcrackan** [comment]
Sure. Off the top of my head:

* Search 'checked' accounts first. ie: those accounts with 'include in library scan' checked
* If there's more than one account, the available status should say which account it's available on. Unnecessary if there's only 1 acct.

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
