### ISSUE TITLE
Action on + sign acts on all episodes

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#536]
**Is your feature request related to a problem? Please describe.**
No, it's a pure enhancement. But the current behaviour is counter-intuitive

**Describe the solution you'd like**
Currently, when a podcast or other episodic title is shown in the grid, it's hidden behind a single + sign for the entire series. Which is fine. BUT, when you want to act on all of the episodes (ie, change download status, remove, etc) you have to act on each individual item, and they don't show in "visible" items unless you first expand the group. It makes more sense, IMHO, to allow any action to act on all of the items hidden by the + sign. (And, if you insist, you could add a warning dialog, though I've been an admin for too long to expect to be warned when I do something stupid.)

**Comment by Mbucari** [comment]
At the core, it sounds like what your asking is for all book/episode entries to be counted among "visible" books if they pass the search filter. Is that right?

@rmcrackan What are your thoughts?

**Comment by CharlieRussel** [comment]
@Mbucari -- Yeah, I think basically that works. Though my first banging my head up against it was right clicking on the + sign and not being able to actually do anything with all those ancient episodes that they used to treat as a "feature" or bonus.

**Comment by rmcrackan** [comment]
I agree. "Visible" should be anything that matches the filter.

Although we can't actually see them, I think "visible" is more intuitive to the average user than "matches." I doubt many people even use or think about the search/filters. I'm open to suggestions though if you have a better idea.

**Comment by Mbucari** [comment]
@CharlieRussel It's also pretty easy to add a context menu to the plus/minus button. What sort of actions would you like to see in there?

**Comment by CharlieRussel** [comment]
It seems to me that it should include all the things you can do to the 'visible' books. If we're treating those hidden by the + sign as visible, then it should carry over to the context menu. Or am I missing something??

**Comment by Mbucari** [comment]
Setting downloaded status and removing both make sense for groups of items. Operations that don't make sense are:

- locate the audiobook
- view bookmarks and records

Operations that may make sense:
- download all children 
- convert to mp3. Nearly all podcasts are MP3s to begin with, but if you are mp4.
- view other items in series. This is the future I'm working on to view all items on Audible that are a part of the series.

Any operation that acts on a group row will necessarily be a batch action. Some operations just don't make sense when batched.

**Comment by CharlieRussel** [comment]
You are  correct about the ones that don't make sense. But download all definitely does, as does convert, I suppose. (Not something I ever do, except converting mp3 to m4b, and that's not an issue here. )

**Comment by Mbucari** [comment]
@CharlieRussel I added this feature as well as the "View Series Episodes/Books" dialog.  @rmcrackan is out of town for a week, so so in the meantime I was hoping you'd download my build and take it for a spin. I'd love your feedback!

https://github.com/Mbucari/Libation/actions/runs/4464503061

**Comment by CharlieRussel** [comment]
@Mbucari -- Downloaded, and after I bypassed the security complaints, etc, I gave it a quick run. Looks good, does what I'd expect from a right click. However, it seems that somewhere along the line, the "locate file" option has broken. It takes one to the top level directory where your saved audible books are, but doesn't take you to the folder where the file is supposed to be. (This is true for non-series books as well.) I'm pretty sure this is a regression, but I'm not at all sure when it was introduced. I honestly hadn't test that in a while.

**Comment by Mbucari** [comment]
@CharlieRussel That feature was introduced in [v8.7.0](https://github.com/rmcrackan/Libation/releases/tag/v8.7.0). I downloaded it and it seems to work the same then as it does in my preview release.

What do you think about the series numbers in the Series column. How about the Series Viewer?

**Comment by CharlieRussel** [comment]
Sorry, thought I'd left a comment. Must have forgotten to post it before I had to do a reboot. 

The series viewer is good, but it really should allow columns beyond the series # to be sortable. Agreed that most series will work sort fine with that column, but some will not. For example, the free series "[Walk to Run One Mile](https://www.audible.com/pd/Workout-1-Foundation-Walk-Audiobook/B07G8HFBQC)" has only one # for all of the series -- #999999999. This makes the sort on series # not work. If I could sort on title, however, that would fix it. 

Also, the series viewer shows the Availability column as blank. Even though it clearly is available. So something's off there. 

The series number doesn't appear to be completely reliable. For example:
![image](https://user-images.githubusercontent.com/21000516/226500105-0de8753a-9389-45e9-824c-8a149a046f26.png)


Finally, while I like having the series number in the Series column, I'd actually prefer it to be in it's own column.

**Comment by Mbucari** [comment]
> it really should allow columns beyond the series # to be sortable.

[Fixed in the latest preview](https://github.com/Mbucari/Libation/actions/runs/4474808608)

> the series viewer shows the Availability column as blank

Yup, that was a bug. It's fixed now.

> I'd actually prefer it to be in it's own column.

I'm ambivalent about this one because more columns is more screen clutter. Though I suppose people who don't want it can just hide that column. @rmcrackan What do you think?

Also, always sorting the main product grid's episodes by series index was a choice made by @rmcrackan way back when podcast grouping was added. It can be changed so all episodes are sorted by any column beneath their parents, but that's an executive decision he'll have to make.

<hr>

But please do check out the update linked above. I added wish list support, so non-free books may be added and removed from your wish list.

**Comment by CharlieRussel** [comment]
Password protected zip?

**Comment by Mbucari** [comment]
@CharlieRussel no?

**Comment by rmcrackan** [comment]
@Mbucari regarding the questions above from 5 days ago: I have opinions; no strong feels though.

Agreed that if you don't want a column, you can just hide it. I don't like how many extra columns are getting added but oh well, I too can just hide.

RE sorting: yeah, that's fine. This is yet another case of: audible screwed up and now it's our job to make it work for users because god knows they're never going to fix it.

**Comment by CharlieRussel** [comment]
@rmcrackan "This is yet another case of: audible screwed up and now it's our job to make it work for users because god knows they're never going to fix it."  

Truer words, etc.

**Comment by rmcrackan** [comment]
This will be included in the next version release :)

**Comment by Mbucari** [comment]
@rmcrackan I'm addressing episode sorting now, and I'd like your input on something.

By default, the grid is sorted by DateAdded (that is, the date the items were added to Libation's db) descending. So newest is on top. But the default episode sorting is to sort by serier order **ascending**, so the oldest is on top. That just seems wrong to me. The newest (highest episode number) should be on top, right?

**Comment by wtanksleyjr** [comment]
The whole question is what type of podcast you've got. If it's a news
podcast you only even CARE about the most recent, the rest you discard. If
it's an epic adventure, you care about all the episodes and listen from the
oldest to newest. I suspect there are positions in between.

Audible hosts a few books as serial podcasts, kind of like a Disney season
released one episode at a time. Those WANT to be packed into a single
folder.

**Comment by rmcrackan** [comment]
@wtanksleyjr Great point -- it's the problem of streaming movies vs. live events. If my internet glitches for 2 minutes in the middle of Batman, don't go forward in the movie by 2 minutes: I want to see it in order. If I'm watching the Olympics, don't make me stay 2 minutes behind on a race: I want to be current.
