### ISSUE TITLE
Multiple tag edit

### ISSUE THREAD

**Issue by dr-fluff** [rmcrackan/Libation#537]
When setting up Libation on a new computer the download state or tag changes are not save between devices although the local library is the same. 

Edit multiple book tags instead of just one to be able to change download status or any other information.

**Comment by rmcrackan** [comment]
You can either just move the database file `LibationContext.db` or check out the top 'Visible Books' menu. Without using search, it will apply these too all books. If you search first, you can get creative with how you apply these bulk changes. Overwriting the database file is probably best in this case though.

**Comment by Mbucari** [comment]
@rmcrackan @dr-fluff I think this issue is as solved as it's going to get. Libation provides several ways to batch edit book properties. Can we close this?

**Comment by rmcrackan** [comment]
@Mbucari Agreed
