### ISSUE TITLE
Show duplicated audiobooks across different account

### ISSUE THREAD

**Issue by elvquant** [rmcrackan/Libation#539]
It would be nice to show (optional) all audiobooks inside an account, also audiobooks which are found in an previous account.

Additional an import filter would by nice to have. At the beginning audible offers monthly "Hörletter" automatically to the account, don't know what's in there, many tips of future audiobooks or reviews. That are not interest to backup.

**Comment by rmcrackan** [comment]
> It would be nice to show (optional) all audiobooks inside an account

Do you mean you'd like to see duplicate entries for the same book when that book exists in multiple accounts? We're intentionally not doing this. Firstly, I can't think of any way to prevent confusion. Also, I can't think of any way to meaningfully differentiate these duplicates without adding more columns that would only be useful in this rare case.

> also audiobooks which are found in an previous account

I'm afraid I don't understand this request. Please clarify.

> import filter

I'll give this some thought. Off the top of my head though I don't see this happening. You can use the filter box to use `-Hörletter` (or try `-Horletter`, I've not yet tested search filters with `ö`) then set that as your default filter so it will always apply on launch. Alternately, you can right click and hide these episodes.

**Comment by elvquant** [comment]
I would optionally see duplicate books, that exists in multiple accounts (across accounts). I column misc i can see the account. My next work-around is to add the accounts in other order (main accounts first)

Instead of filtering the import, i can also remove audiobooks from library after imported/scanned

**Comment by Mbucari** [comment]
I was thinking about this issue yesterday, and the approach I was considering was to use the availability criteria to decide which library book gets imported into the database. Currently, first in wins and is added to the db, and all duplicates are discarded. If instead we change the criteria to first available book wins, we could ensure that all books available to the account holder are also available to be backed up within libation.

**Comment by rmcrackan** [comment]
While not a bad idea, this is not compatible with how we've chosen to handle multiple accounts.
