### ISSUE TITLE
Error occurred while trrying to process this book

### ISSUE THREAD

**Issue by myopica** [rmcrackan/Libation#540]
Am received this error with any book I try, I just downloaded the latest version which was problematic in itself as Windows Defender (which I apparently cannot turn off) kept blocking it, once I got it to install, I still met this same issue. 

![error occurred](https://user-images.githubusercontent.com/91154865/225996271-26b3deac-067a-461f-85c4-52df0d2ef476.jpg)

**Comment by rmcrackan** [comment]
Please attach your log file

**Comment by myopica** [comment]
It's working now, and I'm having a nervous breakdown over the defender issue. So can we just close the issue? Or tell me where to find the log file but as I say it's working now. Many thanks --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 17/03/2023, 19:39 rmcrackan ***@***.***> wrote:

   
  Please attach your log file

**Comment by rmcrackan** [comment]
No worries. I'll close it. Glad it's working again
