### ISSUE TITLE
wont update libary

### ISSUE THREAD

**Issue by cman2342** [rmcrackan/Libation#543]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**

[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
[Log202303.zip](https://github.com/rmcrackan/Libation/files/11018737/Log202303.zip)

**Comment by Mbucari** [comment]
Hi @cman2342 It looks like one or more of the items in your library have an invalid DateAdded property.

Can you please:
1. Go to Settings and change "Logging Level" to "Debug"
2. Scan your library again
3. Go to your Libation folder and you'll find a file called "LibraryScans.zip". Upload that here.

Thanks!

**Comment by cman2342** [comment]
[LibraryScans.zip](https://github.com/rmcrackan/Libation/files/11023949/LibraryScans.zip)

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
