### ISSUE TITLE
ID3 tag encoding issue when transcoding to mp3? (Japanese)

### ISSUE THREAD

**Issue by lobsterbake** [rmcrackan/Libation#545]
Super helpful program - thank you!

My issue: when using the Japan service and saving audio books as mp3 files with separate chapters, I find that third party apps (Plex, audiobook player apps on my phone, etc.) render the resulting Japanese language ID3 metadata tags in garbled form.

* This does not happen (i.e., the metadata tags render properly in Japanese) if I select "download my books in the original audio format (Lossless)". It only happens if I opt to transcode to mp3 ("Download my books as .MP3 format (transcode if necessary)").
* Metadata is properly rendered in the Libation interface itself 
* Metadata is rendered properly in Windows, even for the transcoded mp3 files whose metadata shows up as garbled when viewing in Plex or third-party apps. The third-party apps in question are Unicode aware so should, in principle, render Japanese just fine.
* I've found that I can "repair" the garbled metadata tags using a foobar2000 plugin called foo_chacon (see [https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components_0.9/Chacon_(foo_chacon)](https://wiki.hydrogenaud.io/index.php?title=Foobar2000:Components_0.9/Chacon_(foo_chacon)).)

I realize that this is very much an 'edge' issue that is unlikely to impact too many people... but was wondering if you had any suggestions.

Some screenshot examples of what happens:

Preferred audio settings....

![audio settings](https://user-images.githubusercontent.com/109994341/226613287-784d80d3-4a63-4531-bc9b-2b2dcc6dcc68.jpg)

Will yield metadata that renders fine in Libation...

![libation interface fine](https://user-images.githubusercontent.com/109994341/226613505-0f084eba-9d54-4605-b6e2-84efc4582c37.jpg)

Yet appears garbled in third-party applications (e.g., Plex server):
![Plex rendering example](https://user-images.githubusercontent.com/109994341/226613712-329fb1e3-f839-40bd-972f-aaf6bc775a02.jpg)

If, in Libation, I forego transcoding and download the audiobook in its native format (in this case, a single .m4b file), the metadata rendering is fine in Plex and other third-party apps:
![Plex rendering example 2](https://user-images.githubusercontent.com/109994341/226613912-57797b20-2bff-4e76-a1b9-827dda19512f.jpg)

I've found that I can use the foo_chacon plugin/component for foobar2000 to repair the garbled mp3 metadata tag encodings:

![foo_chacon](https://user-images.githubusercontent.com/109994341/226615428-7fd04302-9aed-4e46-bf24-73f5b1b414a3.jpg)

Plex server rendering AFTER foo_chacon cleanup of tag encodings:

![Plex rendering example 3](https://user-images.githubusercontent.com/109994341/226615635-961f5bc4-2d06-4027-897a-002bac2fe8ad.jpg)

**Comment by Mbucari** [comment]
@lobsterbake Thank you for the report! Can you please pick one of the bad mp3 file chapters here?

**Comment by Mbucari** [comment]
Thanks for the files. LAME doesn't write some unicode tags correctly. I changed they way those tags are written and the Japanese characters display properly. This fix will be released after @rmcrackan gets back next week.

**Comment by lobsterbake** [comment]
Thanks so much. I suspected that it must have been a LAME issue, but glad to have that confirmed.

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
