### ISSUE TITLE
Error removing PodCast

### ISSUE THREAD

**Issue by Tb3986** [rmcrackan/Libation#546]
**Describe the bug**
Hello,
when i try to remove a podcast, i get this error:
![Immagine](https://user-images.githubusercontent.com/45364981/226893020-6bfa37bc-0b63-4d42-ac56-5accfd592180.png)

**Platform**

Windows Server 2019

**Log Files**
[Log202303.log](https://github.com/rmcrackan/Libation/files/11039514/Log202303.log)

**Comment by Mbucari** [comment]
This is a known bug and will be fix in the next patch next week.

**Comment by elvquant** [comment]
Got this error today :-) (macOS)

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
