### ISSUE TITLE
login issue

### ISSUE THREAD

**Issue by ronstampler** [rmcrackan/Libation#548]
wont login to audible.co.uk

Windows 10

[Log202303.log](https://github.com/rmcrackan/Libation/files/11070268/Log202303.log)
ate distribution)]

**Log Files**
Attach your Libation log file here.
[Log202303.log](https://github.com/rmcrackan/Libation/files/11070277/Log202303.log)

**Comment by Mbucari** [comment]
Looks like you're being prompted for a captcha repeatedly. After the first failed captcha, you're required to re-enter your password. The black password is causing the error. It's a bug, but now you know how to work around it.

**Comment by rmcrackan** [comment]
This will be included in the next version release :)
