### ISSUE TITLE
Download Update freezes program

### ISSUE THREAD

**Issue by JakobTischler** [rmcrackan/Libation#55]
I was on v5.1.5 and got the prompt to download v5.1.9. Pressed okay → Select target folder → Downloading popup opens → nothing happens, no progress bar, I can't move the popup (frozen). The zip never gets downloaded.

The "close window" X is in some weird state when I hover it, flickering as if being stuck in a while loop or something. I can't click it though. 

I'm not sure where the logs are, so I have nothing to attach as of yet.

**Comment by rmcrackan** [comment]
I can reproduce your issue on my computer so logs may not be necessary. I think github changed something. I'm testing now. fyi -- logs are in the "LibationFiles" folder.

**Comment by rmcrackan** [comment]
Damn. I have no idea when or how I broke this and it's going to make it a lot more confusing for all users to upgrade :(

Thank you very much for bringing this to my attention

Fixed in [v5.1.10](https://github.com/rmcrackan/Libation/releases/tag/v5.1.10)

**Comment by JakobTischler** [comment]
Awesome, thank you.
