### ISSUE TITLE
Permissions test

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#550]
@Mbucari : please close this issue then delete it

**Comment by Mbucari** [comment]
Cloosing!

**Comment by Mbucari** [comment]
Doesn't appear that I can delete it.

**Comment by rmcrackan** [comment]
w00h00. Do you [feel powerful?](https://www.youtube.com/watch?v=b3c1RORu_Bs)

**Comment by Mbucari** [comment]
I am mod. Hear me roar!

**Comment by rmcrackan** [comment]
Bitch, I have 3 young daughters. I can do this all day -- -https://www.youtube.com/watch?v=CevxZvSJLk8

**Comment by Mbucari** [comment]
Just how many times have you listened to "Let It Go" and "Baby Shark"?

**Comment by rmcrackan** [comment]
Baby Shark: less than you might think. I've heard it but my little home school dorks were never inundated with it as others were.

RE Frozen -- yeah, that was 1 or 2 rough years. The upshot is that I've weaponized it. If kids are engaged in some extended stupid fight (which is often), I just say: "ok Elsa." (i.e.: Let it go)

On the flip side, there are some great media moments that I get to revel in with kids. A few years ago I got to introduce them to ghibli studios and especially My Neighbor Totoro. I was lucky enough to see it on big screen a few years pre-pandemic at a theater which shows old movies on their low attendance nights. Tonight we got to all go see it in-theater courtesy of [Studio Ghibli fest](https://www.fathomevents.com/series/studio-ghibli-fest). I will never tire of seeing this big screen. Magical way to end our vacation.

**Comment by Mbucari** [comment]
Sounds lovely :)

My sister and I try to get my nieces to watch movies that were meaningful to use as kids. The one that really annoys me is that they don't like Jurassic Park but love Jurassic World. smh... No accounting for taste!

**Comment by rmcrackan** [comment]
My kids mostly enjoyed JP; they haven't yet seen any sequels. Jurassic World wasn't bad. However: [JP](https://www.youtube.com/watch?v=nnun8y7r8_U) \+ [JW](https://longawkwardpause.files.wordpress.com/2015/06/jurassicworld-superbowl-trailer-02.jpg) = [Ew](https://longawkwardpause.files.wordpress.com/2015/06/jurassic-poop-e1434305747874.jpg
)
