### ISSUE TITLE
Blank book reported, causing error at download

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#551]
**Describe the bug**
When I ran the new build (9.4.7.1) against one of my accounts, it reported one title to liberate, but didn't show any titles that weren't downloaded. I attempted to download anyway and got a failed error. From the log, it appears to be a title that is no longer available, but if so it's not one I have any knowledge of, given that I was fully downloaded before this build. 

**To Reproduce**

Scan some libraries, find one item to liberate, click "Liberate Visible Books: 1", return error (see screen shot)

**Expected behavior**
Didn't really expect there to BE any to liberate, given that everything in my library has already been liberated. And it can't be pre-orders because I have two on that account, not one.

**Screenshots**
![image](https://user-images.githubusercontent.com/21000516/228018876-bc5968ed-07a3-4ded-ae83-15bb3581a922.png)
![image](https://user-images.githubusercontent.com/21000516/228018518-3a29e4f0-d380-4e6d-98a2-97dbc83fbeec.png)

**Platform**

Windows 11, Libation Classic 

**Log Files**
2023-03-27 10:18:02 AM	Download & Decrypt Step, Begin: [B0B4W5J4R7] [blank title]
2023-03-27 10:18:02 AM	Download & Decrypt Step, Completed: [B0B4W5J4R7] [blank title]
2023-03-27 10:18:02 AM	Download & Decrypt
2023-03-27 10:18:02 AM	ERROR. All books have not been processed. Most recent book: processing failed
2023-03-27 10:18:02 AM	ERROR: License response not "OK" for asin: [B0B4W5J4R7]

**Comment by rmcrackan** [comment]
This is really weird. I just used Classic v9.4.7.1 to scan for and download my new books without issue. That blank entry has an ID so it's not a completely blank entry, but it's not an ID I can find on their website. Even google can't find it.

Does it have an entry in the grid? If so, what other details does it have when you click the 'tags and details' button?

**Comment by Mbucari** [comment]
It's an episode of https://www.audible.com/pd/Quirks-and-Quarks-from-CBC-Radio-Podcast/B08JJP3RCY

It looks like that episode is no longer available for download. Some podcasts prune their catalog and older episodes become unavailable. If you re-scan your library, Libation should detect that that episode is no longer available and will mark it as unavailable.

**Comment by CharlieRussel** [comment]
Ok. But then why did it not detect that in this scan?

Charlie.
(he/him/his)

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________

**Comment by Mbucari** [comment]
@CharlieRussel Can you please enable Debug level logging, do a scan, then post your LibraryScans.zip file here? (It'll be in your Libation settings folder).

**Comment by Mbucari** [comment]
@CharlieRussel Actually, can I have your LibationContext.db too? With both of those I can simulate a scan of your account and figure out what's going on.

**Comment by CharlieRussel** [comment]
@Mbucari  & @rmcrackan -- Files zipped and sent in email to both of you.

**Comment by Mbucari** [comment]
Thanks @CharlieRussel! This one turned out to be easy, but only because out your logs and db. :)

**Comment by CharlieRussel** [comment]
@Mbucari  -- When logs are good, they're great. And even when they're bad, they're good. And I'm all in favour of easy!

**Comment by rmcrackan** [comment]
Fixed in v10
