### ISSUE TITLE
Crash when adding new Audible account

### ISSUE THREAD

**Issue by JakeShirley** [rmcrackan/Libation#552]
**Describe the bug**
I just downloaded Libation for the first time on MacOS Ventura and I cannot add an Audible account.  The app crashes when clicking on "Audible email/login".

**To Reproduce**

1. Click on "No accounts yet, add account"
2. Double click on "Audible email/login"
3. Crash

**Expected behavior**
No crash, let me log in.

**Screenshots**
<img width="912" alt="Screenshot 2023-03-27 at 12 46 37 PM" src="https://user-images.githubusercontent.com/1000311/228050313-3032f2c2-bb02-47f6-86e2-06d59d42ae12.png">

**Platform**

MacOS Ventura, using Libation 9.4.7.

**Log Files**
[crash.txt](https://github.com/rmcrackan/Libation/files/11082466/crash.txt)

**Comment by Mbucari** [comment]
Please upload the Libation log file. It'll be in your user folder/Libation/Log_[date].log

**Comment by JakeShirley** [comment]
[_Log202303.log](https://github.com/rmcrackan/Libation/files/11083759/_Log202303.log)

Here you go!

**Comment by Mbucari** [comment]
@JakeShirley would you please do us a favor and [try this pre-release ](https://github.com/rmcrackan/Libation/actions/runs/4538595319) to see if the problem is fixed? I don't own a mac and after the latest UI framework update I've been unable to run libation on a virtual machine, so I can't debug anything on a Mac right now.

Thanks!

**Comment by self-absorbed** [comment]
@Mbucari I tried the pre-release and I can confirm that the issue is fixed.

Thanks!

**Comment by JakeShirley** [comment]
Glad to here, sorry I didn't get to test this.  The quick turn around is really appreciated, this tool rocks!

**Comment by Mbucari** [comment]
@self-absorbed Thank you so much. This fix was incorporated into v10.

**Comment by rmcrackan** [comment]
Fixed in v10. Released today
