### ISSUE TITLE
Can't get past CAPTCHA

### ISSUE THREAD

**Issue by TrevorMacklin** [rmcrackan/Libation#555]
**Describe the bug**
When attempting to log in, I enter my password and I'm shown a CAPTCHA which is never accepted. I've tried about 15 times. I've checked to verify that my password is being entered correctly, and most of the CAPTCHAs have been easy to read. Additionally, when I instead chose to log in with my browser, nothing happens. the login window simply closes.

**To Reproduce**
Click "Import"
Click "Scan Library"
Enter password
Click "Submit"
Enter CAPTCHA
Click "Submit"

or alternatively

Click "Import"
Click "Scan Library"
Click "Click here"

**Expected behavior**
Login and library scan

**Screenshots**

**Platform**

[e.g. Windows 10]

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
@TrevorMacklin Please post your log file. You can find it by going to Settings and clicking "Open log folder"

**Comment by Mbucari** [comment]
@TrevorMacklin If you open your log file, you will see the exact error message that resulted in you being given another captcha. They include:

"Your password is incorrect"
"Enter the characters as they are given in the challenge."

Note that these will differ with the region.

**Comment by rmcrackan** [comment]
[Latest version 10.0.4](https://github.com/rmcrackan/Libation/releases/latest) released just now addresses a few login issues. Please give it a try and let us know if it solves your issue.

**Comment by Mbucari** [comment]
@TrevorMacklin I'm closing this issue. If you're still unable to log in using the latest update, please open a new issue.
