### ISSUE TITLE
An item with the same key has already been added

### ISSUE THREAD

**Issue by Sbackus65** [rmcrackan/Libation#556]
**Describe the bug**
Dialog box states duplicate key

**To Reproduce**
Libation automatically updated to the latest version earlier today.  I made a purchase on Audible.  I opened the new Libation executable, which automatically scanned the library but did not show the new books.  I clicked Import-->Scan library, and a dialog box appeared stating the above.  

**Expected behavior**
I expected the new books to show up in library so I could download.

**Screenshots**
![image](https://user-images.githubusercontent.com/113722306/228168622-34f3f951-e75c-4a5e-9448-c9eb5d7c5fba.png)

**Platform**
Windows 10

**Log Files**
[Log202303_001.log](https://github.com/rmcrackan/Libation/files/11086812/Log202303_001.log)

**Comment by Sbackus65** [comment]
Don't know if it helps, but I have several books that I purchased different versions of.  They have the same kindle file but different Audible files.  I am attaching screen shots here.
![image](https://user-images.githubusercontent.com/113722306/228336185-4eb968c0-4fdd-46b9-a226-8062a2bbf6ab.png)
![image](https://user-images.githubusercontent.com/113722306/228336324-8b5aa2c9-85f0-494c-9d03-b73cb3ac7a18.png)
![image](https://user-images.githubusercontent.com/113722306/228336573-efc92436-dfe6-40e9-832c-e0fe32a3b160.png)

**Comment by Mbucari** [comment]
that is extremely helpful, thank you!

Can you do me a favor and post the Audible product IDs for both versions of Ender's Game and The Martian?  You can find them by clicking the "Edit Tags" button (left-most column) and reading it from the Book Info.

**Comment by Sbackus65** [comment]
Title: The Martian
Audible ID: B082BHJMFF

Title: The Martian
Audible ID: B00B5HZGUG

Title: Ender's Game Alive: The Full Cast Audioplay
Audible ID: B00E3U3IB6

Title: Ender's Game: Special 20th Anniversary Edition
Audible ID: B002V5A12Y

**Comment by Sbackus65** [comment]
I posted the audible IDs but am emailing you the full tag info in case it helps.

Title: The Martian
Author(s): Andy Weir
Narrator(s): Wil Wheaton
Length: 10 hr 59 min
Audio Bitrate: 128 Kbps, 44.1 kHz, Stereo
Category: Science Fiction & Fantasy > Science Fiction
Purchase Date: 6/21/2021
Language: English
Audible ID: B082BHJMFF

Title: The Martian
Author(s): Andy Weir
Narrator(s): R. C. Bray
Length: 10 hr 53 min
Audio Bitrate: 64 Kbps, 22.1 kHz, Stereo
Category: Science Fiction & Fantasy > Science Fiction
Purchase Date: 6/5/2015
Language: English
Audible ID: B00B5HZGUG

Title: Ender's Game Alive: The Full Cast Audioplay
Author(s): Orson Scott Card
Narrator(s): Full Cast Recording
Length: 7 hr 24 min
Audio Bitrate: 64 Kbps, 22.1 kHz, Stereo
Category: Science Fiction & Fantasy > Fantasy
Purchase Date: 10/13/2020
Language: English
Audible ID: B00E3U3IB6
Series: The Ender Saga, The Enderverse

Title: Ender's Game: Special 20th Anniversary Edition
Author(s): Orson Scott Card
Narrator(s): Stefan Rudnicki, Harlan Ellison, Gabrielle de Cuir
Length: 11 hr 57 min
Audio Bitrate: 64 Kbps, 22.1 kHz, Stereo
Category: Science Fiction & Fantasy > Fantasy
Purchase Date: 3/15/2021
Language: English
Audible ID: B002V5A12Y
Series: The Ender Saga, The Enderverse

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Mbucari** [comment]
Thank you. Can you do one more thing for me please? In Libation go to Settings and change "Log Level" to "Debug". Then re-scan your library.  This will create a file called 'LibraryScans.zip in your Libation settings folder. Can you email that to me? mbucari1@gmail.com

There's no personally identifying info in those.

**Comment by rmcrackan** [comment]
Fixed in v10

**Comment by Sbackus65** [comment]
Thank you!  You guys are awesome  :-)

-Sam

Sent from my iPhone

On Mar 29, 2023, at 1:57 PM, rmcrackan ***@***.***> wrote:

﻿

Fixed in v10
