### ISSUE TITLE
OPF file creation

### ISSUE THREAD

**Issue by joshaconnor** [rmcrackan/Libation#568]
**Is your feature request related to a problem? Please describe.**
I have other apps that use the audiobooks I download here, and they have trouble importing the metadata correctly and understanding what book to connect each file to. 

**Describe the solution you'd like**
Creating an OPF file, along with the CUE file, which contains the metadata of the file, would solve the issue. As an open file format, most apps built with a self-hosted mindset are somewhat compatible with the format. 

**Describe alternatives you've considered**
An alternative helpful, but niche, addition to this fix would be the ability to export an OPF file for a single book in case working in bulk isn't the current mode I am working in. 

**Additional context**
The specific app I am currently having trouble with is audiobookshelf. I have seen the issues [445](https://github.com/rmcrackan/Libation/issues/445) and [557](https://github.com/rmcrackan/Libation/issues/557), and both address the problem partially, but don't solve the problem in the most future oriented way. These both require additional scripts or a solution from the other app rather than creating a generalized solutions that interconnects the apps in an ecosystem. 

[opf file format](https://docs.fileformat.com/ebook/opf/)
[further info about opf](https://en.wikipedia.org/wiki/EPUB#Open_Packaging_Format_2.0.1)
[audiobookshelf importing opf](https://www.audiobookshelf.org/docs#book-additional-metadata)

**Comment by wtanksleyjr** [comment]
Seconded.  Like the original requestor, I use OPF also to pass the book
info on to Audiobookshelf. Unfortunately OPF can only have one series, but
I like the portability of the info. On the other hand, the ABS format
(native to Audiobookshelf, similar to INI format) can accept multiple
series, making it a better match to the metadata provided by Audible.

I would also like to have Libation dump each book's full known metadata
(including things like series ASIN) in the folder with the book in a
more complete format than OPF. I personally run a script that splits up the
Libation library dump and puts each book's JSON info into its own folder,
as a first step -- but it would be really nice to have this be automatic.

**Comment by Mbucari** [comment]
@wtanksleyjr I just tried audiobookshelf for the first time, and its mp3 chapters are all screwed up. The total audio length is correct, the chapter timestamps are correct, but the audio that plays at those timestamps is not what it's supposed to be. It's off anywhere from +/- 2 minutes from the timestamp. Have you noticed this?

**Comment by wtanksleyjr** [comment]
No, I've not seen that! That's very strange. This happens with multiple
books, or just one? My MP3s don't have chapters, but my m4bs are almost all
from Libation and definitely use the same chaptering ... unless you have
files from some experimental version you ran :) . But that can't be the
case, this is OLD functionality.

-Wm

**Comment by Mbucari** [comment]
@wtanksleyjr I've only checked with one mp3 file. Chapter tagging in mp3s is totally different than MP4's, and they are incredibly rare in the wild. I wrote the ID3 chapter tag module myself (because they're so rare I couldn't find any existing projects that already do it), and it they're perfect on my desktop media player (PotPlayer). But Audiobookshelf seems to screw them up. Hmmm.

**Comment by wtanksleyjr** [comment]
Ah, then I haven't used those; like you I looked into chapter-tagging MP3s
(because I wanted to use the zip-0 trick on podcast audiobooks), but unlike
you I gave up on it.

However, it looks to me like something ABS might be getting wrong, and a
bug report feels like a good idea.

-Wm

**Comment by joshaconnor** [comment]
ABS uses Tone as their tagging tool, for all metadata I believe. I have not looked into the software, but it seems to support tagging chapters, among other things, in mp3, among other things. I do not know if all features are supported in all formats. It would be a good thing to look into, if you want more details on ABS chapters. [Repo](https://github.com/sandreas/tone)

**Comment by Mbucari** [comment]
@joshaconnor @wtanksleyjr 

I've been ignoring this request since it's been made, and @wtanksleyjr's [recent comment](https://github.com/rmcrackan/Libation/issues/652#issuecomment-1621105037) encapsulates my lack of enthusiasm for this feature. OPF is a poor metadata interchange format. It supports too few fields to be terribly useful, and I don't want to expend the effort to make what i consider a crappy feature.

With the recent changes made at the request of that issue, audiobookshelf can now read ASIN, Series name and number, publisher, and language from all m4b and mp3 audiobooks created by Libation. Is that good enough? Can I close this issue?

**Comment by wtanksleyjr** [comment]
I no longer want OPF. I now want json ;) ;) . But it's OK, you can close
this feature.

-Wm

**Comment by rmcrackan** [comment]
I agree with the above. We're not trying to be all things to all people. Given the structured output and the CLI program, someone else should be able engineer a good solution to this. If you do create one to share, let me know and I'll be glad to add it to [AudiobookHub](https://github.com/rmcrackan/AudiobookHub).
