### ISSUE TITLE
Wrong INF when decrypting multiple books simultaneously

### ISSUE THREAD

**Issue by JakobTischler** [rmcrackan/Libation#57]
Using v5.1.10:

When two or more books are being decrypted simultaneously, the progress information from one book swaps over to another:

![image](https://user-images.githubusercontent.com/748857/126157619-890860ea-92c3-43f1-8bfe-b065e9c05ffa.png)

![image](https://user-images.githubusercontent.com/748857/126157630-1cbb82c2-8d95-43cd-87c5-34fc40cdca51.png)

It seems though as if this is only a log problem - the decrypted files all seem to be in order.

**Comment by Mbucari** [comment]
This is related to issue #58. Simultaneous backups are not supported, but the user isn't prohibited from trying.

**Comment by rmcrackan** [comment]
@Mbucari 

I'm in the process of cutting the Gordian Knot on this one. I pondered lots of different potential solutions for this and none of them panned out. The answer I'm going with is: log it all but don't bother re-routing logs to this UI box. No one cares anyway except for debugging. This will still be preserved in logs. I'm going to just delete this box. Will be available in next release.

**Comment by rmcrackan** [comment]
Fix available in [v5.3.2](https://github.com/rmcrackan/Libation/releases/tag/v5.3.2)
