### ISSUE TITLE
Blank Screens after 2FA

### ISSUE THREAD

**Issue by cwcampagna** [rmcrackan/Libation#573]
Thanks for the help, This program will help with my ADHD and allow me to send an MP3 file to a transcription program for better focus!

**Describe the bug**

Probably user error ;)

Blank Screens after 2FA
Also, when I try to sign in from the browser, no, screens or options to do so come up.

**To Reproduce**
Scan Library
Enter Password (I can't use the "Or click here" option; nothing happens
2FA entered
Nothing happens :(

**Expected behavior**
I would expect all my audible books to be imported, but nothing happens.

**Screenshots**
See Attached Files

**Platform**
Windows 10
Classic-Libation.10.0.2-windows-classic

**Log Files**
No log files nothing in any of the windows show up, just blank windows.

![audible login 1](https://user-images.githubusercontent.com/24554367/230094098-1e12152b-3c7a-4c44-81fa-47280078ab2a.png)
![Captcha](https://user-images.githubusercontent.com/24554367/230090541-71145ee9-87d3-483e-b8f2-3cda05ea6925.png)
![2FA](https://user-images.githubusercontent.com/24554367/230091036-8e60a1ec-c9b8-4c8f-bbae-dd5c1ea589e6.png)
![Nothing Shows](https://user-images.githubusercontent.com/24554367/230091175-fb408425-38e4-4958-b964-14dabbd740dd.png)

**Comment by rmcrackan** [comment]
@Mbucari is this related to your fixes that I haven't yet released? Or unrelated?

**Comment by Mbucari** [comment]
@rmcrackan the external login not working has been fixed, but the blank screen after 2fa is a mystery. If you want to hold off for another hour or so, I'll test logging in with classic to see if I can reproduce. I have 2fa enabled.

**Comment by Mbucari** [comment]
@rmcrackan I Can't reproduce this error. Logins is working on classic.

@cwcampagna I think this may be a glitch on your system The 2fa dialog is supposed to look like this:
![image](https://user-images.githubusercontent.com/37587114/230111822-322235e2-8786-48f4-8353-90f7e6d3d853.png)

Notice all that text that's missing on your window. That text not rendering suggests something is wrong at a pretty deep level. Can you restart your computer and try again?

**Comment by ralphtrickey** [comment]
I have a similar problem with Classic 10.0.2. When I click her (sic) to login, nothing happens. When I go through the integrated process to log in, it completes the steps but nothing happens and it doesn't seem to save whatever token comes back and running scan again prompts for a login.

**Comment by Mbucari** [comment]
@cwcampagna and @ralphtrickey

Can you please try this:

1. In Libation's Settings, change the Logging level to "Verbose"
2. Go to %temp\Libation and create a new folder there named "Verbose"
3. Try logging in again. Some files will be created in %temp\Libation\Verbose
4. email those files to me at mbucari1@gmail.com

**Comment by cwcampagna** [comment]
@rmcrackan @Mbucari  So at work,  I downloaded and ran Libation program on my laptop running windows 11.

No issues! I will keep working on my desktop that does not seem to cooperate. Since it is at home, could it be a security issue with by ATT internet modem blocking traffic?

Thanks for creating this program. Paypal $ coming to  you. Enjoy!

**Comment by Mbucari** [comment]
@cwcampagna I'm glad you got it working! You can copy the AccountSettings.json file from your work computer to your home computer to share the credentials, so there's no need to log in again.

**Comment by cwcampagna** [comment]
Great where do I find the AccountSettings.json file and where do I place the AccountSettings.json file once I copy it?

Also, my PayPal account is acting up, can I send my thanks to your Venmo account or similar?

**Comment by cwcampagna** [comment]
I was able to copy my account setting from the laptop to the PC, and everything is working!
Thanks again!
