### ISSUE TITLE
Account log in issue

### ISSUE THREAD

**Issue by jopadget24** [rmcrackan/Libation#576]
I cannot get Libation to import my library.  Every time I type my password, I go through the CAPTCHA and two factor auth, then nothing happens.  I have done this several times with not success.  

I have also tried the 'Or click here' link to log in that way, but when I click the link, nothing opens.

Below is my file log.

[_Log202304.log](https://github.com/rmcrackan/Libation/files/11181584/_Log202304.log)

**Comment by rmcrackan** [comment]
[Latest version 10.0.4](https://github.com/rmcrackan/Libation/releases/latest) released just now addresses a few login issues. Please give it a try and let us know if it solves your issue.

**Comment by jopadget24** [comment]
That fixed the log in issue.  Thanks!
