### ISSUE TITLE
Cannot fetch library details

### ISSUE THREAD

**Issue by AndrewHows** [rmcrackan/Libation#580]
**Describe the bug**
As a new user, setting up an account and performing the initial library fetch fails. Primary account is in the US, and predates Amazon, while I also have an automatically-created (but empty) Australian account. Have tried with us, us-pre-amazon, and au locales.

**To Reproduce**
Enter account details
Enter password when prompted
Enter captcha when prompted
Enter 2FA when prompted
Nothing happens
Log file indicates failure to fetch library (404 not found)

**Expected behavior**
Books from my library appear in app

**Platform**
Linux Mint 20.1 Ulyssa

**Log Files**
[_Log202304.log](https://github.com/rmcrackan/Libation/files/11196904/_Log202304.log)

**Comment by Mbucari** [comment]
@AndrewHows Sorry about this. It looks like Audible is trying to send to an email to approve the sign-in, but Libation isn't processing it correctly. Can you try again, but when Libation prompts you for your password, click on the "Or click here to log in with your web browser" link and follow those instructions

@rmcrackan Looks like the approval needed result runner isn't working. Do you know how to trigger amazon to require an email approval, short of trying to log in from another country??

**Comment by rmcrackan** [comment]
> Do you know how to trigger amazon to require an email approval, short of trying to log in from another country??

Nope. As you know, login is complicated and specific across many use cases, several of which I can't reproduce, and all of which I have no control over. If this is too far outside of what can reasonably be debugged, this is definitely what the alternate login is for. (ie: the "Or click here" link).

I wonder if a simple UI change would help people here. Instead of the easy-to-miss link, we might add a button like 'having login issues? click here to log in through the browser instead' or something like that. More advanced would be to show a more obvious prompt after we detect a login failure. That's likely overkill though.

**Comment by CharlieRussel** [comment]
@rmcrackan You know, I think that would be a useful change. We see a LOT of issues with logins, and it seems that folks just don't SEE the alternate login option. We need to make it easier to do the right thing.

**Comment by Mbucari** [comment]
Or, if we have one method that works all the time (as far as we know) and another method that works only some of the time, use the method that work all of the time as the primary

**Comment by wtanksleyjr** [comment]
Are you saying to use the web page method as primary? If you do that, would
it make sense to make it available to the CLI as well, and would that make
the CLI capable of operating completely headless?

-Wm

**Comment by CharlieRussel** [comment]
@wtanksleyjr -- I doubt it would allow for completely headless, plus it requires one to copy and paste a <i>really long URL</i> into your browser. 
@Mbucari  -- the catch is that the web method is rather counter-intuitive. It works, and I've not had it fail ever, but it feels fairly clunky and kludgy. OTOH, I've never had the "standard" method work for me, so...

**Comment by rmcrackan** [comment]
> the catch is that the web method is rather counter-intuitive. It works, and I've not had it fail ever, but it feels fairly clunky and kludgy

Bingo. This is psychology, not technology.

Everyone here is a power user. If I told my dad to do the copy and paste method, he'd say it's too complicated and delete the app without ever giving it a chance. A login box (when it works) is frictionless. Everyone accepts this as part of the app paradigm and uses it just like they always do -- no thinking required.

The login process is part of first impressions for new users. We haven't yet built up any trust or credibility and every point of confusion or discomfort increases the chance that they'll leave. I can think of 4 apps I tried **this week** where that's what happened when I tried to use them. Once users have gotten some use out of Libation, then they're willing to invest in some learning or slight discomfort. Until then, the burden of proof is on us that the app will make their lives better. Starting hard and saying "trust us, it's worth it" is a psychological dead-end.

**Comment by Mbucari** [comment]
But what if we added a web view control that Opens the webpage within Libation to have users log in?

https://learn.microsoft.com/en-us/dotnet/api/microsoft.web.webview2.winforms.webview2?view=webview2-dotnet-1.0.1722.32
https://github.com/OutSystems/WebView

**Comment by rmcrackan** [comment]
I haven't use one of those in a long time. In the early days of .net winforms, there was a similar control which was bloated disaster and I've avoided them since.

You're welcome to try. Surely they've come a long way since then. I'm not married to the current implementation. I'm married to making this step as easy as possible for the user.

**Comment by rmcrackan** [comment]
We seem to have taken over OP's bug. My apologies.

@AndrewHows , does the 'or click here' link solve your problem?

**Comment by AndrewHows** [comment]
> @AndrewHows Sorry about this. It looks like Audible is trying to send to an email to approve the sign-in, but Libation isn't processing it correctly. Can you try again, but when Libation prompts you for your password, click on the "Or click here to log in with your web browser" link and follow those instructions

Yes, logging in via that method solved it. Thanks.
