### ISSUE TITLE
Some duplicate titles in library

### ISSUE THREAD

**Issue by Sbackus65** [rmcrackan/Libation#583]
**Describe the bug**
Newly scanned titles in library have duplicate entries.  Titles scanned in previous version only have one entry (existing titles are not duplicated.)

**To Reproduce**
1.  Open Libation.
2. Libation automatically scans library. 
3. Duplicates show up.  Duplicate files are not necessarily next to each other.

**Expected behavior**
I expect one title for each audiobook

**Screenshots**
![image](https://user-images.githubusercontent.com/113722306/231671922-3981b3ca-2317-4f1c-bdd4-a0cc6f8ee92b.png)

**Platform**
Windows 10

**Log Files**
[Log202304_002.log](https://github.com/rmcrackan/Libation/files/11218887/Log202304_002.log)
[Log202304_001.log](https://github.com/rmcrackan/Libation/files/11218888/Log202304_001.log)

**Comment by Mbucari** [comment]
@Sbackus65 That's weird, and it shouldn't be possible. Can you please go to your Libation settings folder and email me your LibationContext.db file?

mbucari1@gmail.com

**Comment by Sbackus65** [comment]
Hi Mbucari1,

I have emailed to your gmail account.

Thanks!
________________________________

**Comment by Mbucari** [comment]
I've emailed you back your DB with duplicates removed. If this ever happens again, do the following:

1. Launch the Hangover app (you can get to it through the Settings menu)
2. Paste this command in the SQL box and click "Execute"
    ```SQL
    DELETE FROM LibraryBooks
    WHERE BookId IN
      (SELECT BookId From
        (SELECT AudibleProductId, BookId, Title, COUNT(*)
        FROM Books 
        GROUP BY AudibleProductId
        HAVING count(*) > 1))
    ```
    then paste and run this command
    ```SQL
    DELETE FROM Books
    WHERE BookId IN
      (SELECT BookId From
        (SELECT AudibleProductId, BookId, Title, COUNT(*)
        FROM Books 
        GROUP BY AudibleProductId
        HAVING count(*) > 1))
    ```
3. Repeat step 2, pasting both commands in that order, until the bottom readout shows `0 records affected`
