### ISSUE TITLE
Happened twice since update

### ISSUE THREAD

**Issue by cerinawithasea** [rmcrackan/Libation#585]
**Describe the bug**
This is the first time i have tried to help by sharing my logs I hope i did. The computer was  untouched and just downloading

**To Reproduce**

**Expected behavior**

**Screenshots**

**Platform**
Edition	Windows 10 Pro
Version	22H2
Installed on	‎1/‎15/‎2023
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Log Files**
[Log202304.log](https://github.com/rmcrackan/Libation/files/11240174/Log202304.log)

Attach your Libation log file here.

**Comment by Mbucari** [comment]
You've set your Books folder to the same folder as your Libation settings. This will cause the problems you're seeing. I suggest you make a sub folder inside D:\Liberation for keeping your books.
