### ISSUE TITLE
Fails to download book (Error getting download license)

### ISSUE THREAD

**Issue by PutinTheGreat** [rmcrackan/Libation#586]
**Describe the bug**
Fails to download book and brings up skip importing this book message box.

**To Reproduce**

1. Purchase `Get In Get Out: An Amish, Sci-fi, Gender Bender Adventure (https://www.audible.com/pd/Get-In-Get-Out-An-Amish-Sci-fi-Gender-Bender-Adventure-Audiobook/B07CNKWG68)` from audible
2. Open Libation Classic v10.1.0.1 (also happened on older versions)
3. Click Scan Library to get book to show in list 
4. Click Liberate
5. Click Begin Book and PDF Backups: 1 remaining
6. See error

**Expected behavior**
It downloads/decrypts book into m4b file.

**Screenshots**
https://i.imgur.com/H8c2gmt.png

**Platform**
OS Name:	Microsoft Windows 10 Pro
Version:	10.0.19045 Build 19045
Other OS Description: 	Not Available
OS Manufacturer:	Microsoft Corporation
System Name:	DOUGS
System Manufacturer:	To Be Filled By O.E.M.
System Model:	To Be Filled By O.E.M.
System Type:	x64-based PC
System SKU:	To Be Filled By O.E.M.
Processor:	Intel(R) Core(TM) i9-9900K CPU @ 3.60GHz, 3601 Mhz, 8 Core(s), 16 Logical Processor(s)
BIOS Version/Date:	American Megatrends Inc. P1.90, 12/26/2018

**Log Files**
[Log202304.log](https://github.com/rmcrackan/Libation/files/11240276/Log202304.log)

**Extra Notes**
Error appears to be `Error getting download license` this is the only file it's happened on.

**Comment by Mbucari** [comment]
Are you able to listen to that book from the Audible website?

**Comment by PutinTheGreat** [comment]
ah my bad didnt think of sharing that part.  havent verified the entire book but have checked out first 2 chapters on website and mobile and they play fine.  on mobile app it downloaded whole book without issue as well.

https://i.imgur.com/aHkNud7.png

**Comment by Mbucari** [comment]
This error message has the smell of a temporary API outage. I can't say for sure, but I suspect if you try downloading again in a couple of days it will have resolved itself.

**Comment by PutinTheGreat** [comment]
i dont think thats the case as its been giving an error for weeks now.  and other books worked fine at same time as that purchase and 4-5 after.  it still erroring, thankful for ignore option for it, though skip this time would be nice.

this particular book isnt that important but figure this might not be only one to have the issue.  but ill try getting this book every so often and see if its temporary api issue

**Comment by Mbucari** [comment]
OK, I've look more into this and I've discovered that that particular title can only be downloaded with widevine DRM, not the standard ADRM used by the vast majority of books. So for now there is nothing we can do.

**Comment by Mbucari** [comment]
Actually, I there's something else going on here. Not sure what yet.

In the meantime, you can use the "ignore" option so Libation no longer attempts to download this book. Or you can just delete it through the right-click menu on the stoplight button.

**Comment by Mbucari** [comment]
@PutinTheGreat I figured it out. This book cannot be downloaded using the new "aaxc" file format but can be downloaded as the old aax format. This is the first and only example of a book that can't be downloaded in the new format that I've seen in the nearly 2 years I've been working on this. Thanks for the report!

**Comment by rmcrackan** [comment]
Fixed in recently released `Libation 10.2.1`

@Mbucari Thank you so much!
