### ISSUE TITLE
Missing at least one book

### ISSUE THREAD

**Issue by dcolecpa** [rmcrackan/Libation#589]
**Describe the bug**
I have Krakatoa by Simon Winchester in my audible Library.  Unfortunately, it is not downloaded in the Libation library.  I have a lot of books ~300 or more and assume others are missing also. 

**To Reproduce**
1. Go to 'Home Page'
2. Click on 'Scan Library '
3. No error noted

**Expected behavior**
All of my books downloaded.

**Screenshots**

**Platform**
Edition	Windows 10 Home
Version	22H2
Installed on	‎8/‎18/‎2020
OS build	19045.2846
Experience	Windows Feature Experience Pack 120.2212.4190.0

**Log Files**
[Log202304.zip](https://github.com/rmcrackan/Libation/files/11290612/Log202304.zip)
[Log202304_001.zip](https://github.com/rmcrackan/Libation/files/11290617/Log202304_001.zip)

**Comment by dcolecpa** [comment]
Sorry, forget to mention I am using Libation 10.2.1.1

**Comment by dcolecpa** [comment]
Thanks, happy to help.  The log is attached
[Log202304_001.zip](https://github.com/rmcrackan/Libation/files/11297968/Log202304_001.zip)
[LibraryScans.zip](https://github.com/rmcrackan/Libation/files/11297973/LibraryScans.zip)

FYI, I have 38 errors reported by Libation and most of those have downloaded but not as mp3.  Based on my work this morning it looks like I am missing 3 books Krakatoa (Winchester), Hunchback of Notre Dame (Hugo) and Oliver Twist(Dickens).  FYI, I am also getting errors (and don't care) on Car Talk, Science Friday and subscription stuff from long ago

**Comment by Mbucari** [comment]
I've run your Library scans through Libation, and it successfully imports Hunchback of Notre Dame and Oliver Twist. When you say they're missing, how are you determining that? Are you searching and not finding them, or are you scrolling through the grid looking for them?  If you're searching and not finding, might I suggest deleting the SearchEngine folder and restarting Libation. Or maybe you accidentally deleted them and they're sitting in Libation's Trash Bin? Look at Settings > Trash Bin.

As for Krakatoa, it's just not being returned by Audible during the library scan. I don't know why that's happening, and I don't know that there's anything we can do about it :/

**Comment by dcolecpa** [comment]
Alright, thanks for looking into it.  These three are odd, I am looking in the "Books" folder where all the down loads are and Hunchback and Oliver aren't there.  Oh well, I did look in the Trash bin just now and found 2297 'subscriptions' Car Talk, Forbes, etc.  I am restoring them and perhaps they are buried in there.  I also check the Windows trash bin just in case.  I'll see what shakes out.  

I'll close this ticket out, meanwhile.

Cheers!
