### ISSUE TITLE
Hi Libation was working fine for me but now it says that books cannot be imported if it happends 2 or 3 times plaese contact administrator, I tried 4 times. Please help.

### ISSUE THREAD

**Issue by docbha** [rmcrackan/Libation#59]

**Comment by docbha** [comment]
[
[Issue.docx](https://github.com/rmcrackan/Libation/files/6847196/Issue.docx)
](url)

**Comment by rmcrackan** [comment]
I'll be glad to take a look. Please attach your log file

**Comment by docbha** [comment]
Thanks so much, unfortunately I am not so IT savy, could you guide me from where i can find the log file.

**Comment by rmcrackan** [comment]
No problem. In Libation, go to Settings > Advanced Settings. This will open a box that shows you a location of a folder on your computer. Go to the folder indicated. Inside that folder will be files that start with "Log." These are what I need.

I also just made a personal note for a future feature to make these easier to find and share.

**Comment by docbha** [comment]
Hi Please find attached the log files, thanks a lot for your guidance.
[Log202107_009.log](https://github.com/rmcrackan/Libation/files/6850042/Log202107_009.log)

**Comment by rmcrackan** [comment]
Thanks! Fixed in v5.2.1

**Comment by docbha** [comment]
Thanks a lot !!!!
