### ISSUE TITLE
First time trying to import

### ISSUE THREAD

**Issue by Pezhistory7** [rmcrackan/Libation#590]
**Describe the bug**
First time user. Account added. Password and Catpha completed. Told Libation to scan.  This occurred 3 times.

![image](https://user-images.githubusercontent.com/131560032/233808988-a5ed30d9-fb62-4817-8963-f4f2312f1ef2.png)

**Comment by Mbucari** [comment]
Holy smokes! Sorry for the bad first impression.

Can you please upload your log file? If you open the settings window in libation, there will be a button you can click to open the folder containing logs. Just drag drop that log.zip file here. Thank you!

**Comment by PaulBrad25** [comment]
Regular user here, it's something in the last update, I logged in today to back up my new purchases, they synced, then I updated, then I made new purchases, then I got the same error as above and kept getting asked for a new login.

**Comment by PaulBrad25** [comment]
Regular user here, it's something in the last update, I logged in today to back up my new purchases, they synced, then I updated, then I made new purchases, then I got the same error as above and kept getting asked for a new login.

**Comment by PaulBrad25** [comment]
Seems to have been fixed by rebooting the laptop, will let you know if anything else goes awry.

**Comment by Pezhistory7** [comment]
> Holy smokes! Sorry for the bad first impression.
> 
> Can you please upload your log file? If you open the settings window in libation, there will be a button you can click to open the folder containing logs. Just drag drop that log.zip file here. Thank you!

[_Log202304.log](https://github.com/rmcrackan/Libation/files/11302586/_Log202304.log)

**Comment by Pezhistory7** [comment]
[_Log202304_001.zip](https://github.com/rmcrackan/Libation/files/11302587/_Log202304_001.zip)
[_Log202304_002.zip](https://github.com/rmcrackan/Libation/files/11302588/_Log202304_002.zip)

**Comment by Mbucari** [comment]
@Pezhistory7 This _looks_ like a network error. The audible request is timing out.  Is it possible for you to try on a different internet connection?

**Comment by Pezhistory7** [comment]
Winner Winner.  Personal hotspot to phone.  Library connected.  I assume now I can go back to my  home wifi for the downloads.  Kill my data plan otherwise

**Comment by Mbucari** [comment]
> Winner Winner.

Woot! At least we found the error.

> 15 min update- no joy when I connected back to my wifi. Download errors.

Dang. Maybe reach out to your ISP?
