### ISSUE TITLE
Error importing library

### ISSUE THREAD

**Issue by oswallt** [rmcrackan/Libation#594]
**Describe the bug**
Clicking scan library produces an error.

**To Reproduce**

1. Scan library.
4. See error.

**Expected behavior**
The library scan completes successfully.

**Platform**
Windows 10

**Log Files**
[Log202304.log](https://github.com/rmcrackan/Libation/files/11315360/Log202304.log)
[Log202304.zip](https://github.com/rmcrackan/Libation/files/11315361/Log202304.zip)
[Log202304_001.zip](https://github.com/rmcrackan/Libation/files/11315362/Log202304_001.zip)

**Comment by Mbucari** [comment]
@oswallt This is another http timeout error.  This has been happening a lot recently, and makes me think there's something going on with the Audible servers.

@mkb79 Have you been seeing an increase in http timeouts?

**Comment by rmcrackan** [comment]
> This has been happening a lot recently, and makes me think there's something going on with the Audible servers.

This happened a year or so ago and we were getting these on and off for weeks. Where people had no issue with the official methods but Libation would get these errors for a day or 2 then resolve itself.

My best guess is there are errors and/or upgrades happening on audible's side and that the official apps know a secondary path that we don't know about which, under the covers, the apps try silently. We couldn't find a rhyme or reason regarding which users were affected -- so this guess could be wrong.

**Comment by rmcrackan** [comment]
@oswallt Is this still an issue?

**Comment by oswallt** [comment]
@rmcrackan Yep, and I'm able to download from openAudible, so now I'm not sure what the problem is.

**Comment by oswallt** [comment]
It's working again!

**Comment by rmcrackan** [comment]
Thanks for the update. Sucks that it took so long but I'm glad you're back in business :)
