### ISSUE TITLE
Spatial Audio?

### ISSUE THREAD

**Issue by mslmn** [rmcrackan/Libation#597]
**Is your feature request related to a problem? Please describe.**
No. 

**Describe the solution you'd like**
Is there a difference between the files from standard Audible books and Spatial Audio ones? If so, can they be fetched by Libation?

**Additional context**
Example link:
https://www.audible.co.uk/pd/Zero-G-Audiobook/B07K3XYXFC

**Comment by rmcrackan** [comment]
Yes. The only caveat is: make sure this item is **disabled** -- Settings, Audio File Options tab, Downsample stereo to mono. It will still download, but will sound wrong.

**Comment by Mbucari** [comment]
>  Is there a difference between the files from standard Audible books and Spatial Audio ones?

Yes, but please don't ask me what they are.

> If so, can they be fetched by Libation?

Nope. Libation only downloads the standard stereo (actually duplicated mono) AAC audio files. In theory it _could_, but I don't own a device that supports Dolby Atmos so I can't reverse engineer what we'd need to do to get those files.

**Comment by rmcrackan** [comment]
> Nope. Libation only downloads the standard stereo (actually duplicated mono) AAC audio files.

@Mbucari Why wouldn't Libation be able to support anything, as long as it's just a file wrapped in encryption?

**Comment by Mbucari** [comment]
> @Mbucari Why wouldn't Libation be able to support anything, as long as it's just a file wrapped in encryption?

It probably could, but I don't know how to request a Dolby Atmos file. We can get High and Low quality, but those are your standard stereo audio.

![Screenshot_20230510-064118~2](https://github.com/rmcrackan/Libation/assets/37587114/543972e1-8b5e-4ae9-994a-75a26fe282c2)


[See the supported devices](https://help.audible.com/s/article/does-my-device-support-dolby-atmos-playback?language=en_US)

**Comment by gilesfun** [comment]
> > @Mbucari Why wouldn't Libation be able to support anything, as long as it's just a file wrapped in encryption?
> 
> It probably could, but I don't know how to request a Dolby Atmos file. We can get High and Low quality, but those are your standard stereo audio.
> 
> 
> [See the supported devices](https://help.audible.com/s/article/does-my-device-support-dolby-atmos-playback?language=en_US)

I have a compatible device and could supply a pcap if you know of a way to disable certificate pinning for Audible Android.

**Comment by CLHatch** [comment]
Seems my phone also supports it. Let me know if there's anything I can do to help you.

**Comment by mkb79** [comment]
The `spatial` audio files have a different encryption than aax or aaxc files. I was able to download these files. But I can’t get any further with the decryption part! [Here](https://github.com/mkb79/audible-cli/issues/155) you can read a little bit more.

**Comment by rmcrackan** [comment]
Fixed in #1223
