### ISSUE TITLE
Failed install of 10.2.1 in MacOS High Sierra

### ISSUE THREAD

**Issue by John4736** [rmcrackan/Libation#598]
**Describe the bug**
I download the 10.2...x64 for MacOS. The tar extract throws lots of errors "Ignoring malformed pax extended attribute", mostly for ...dll files, and some for  ._Info.plist-e files. I'm running High Sierra. A subsequent attempt to run the spctl & open command fails with "error -10825". 

**To Reproduce**
1. Download Libation.10.2.1-macOS-chardonnay-x64.tgz
2. CD to a Libation install directory
3. Extract using command line tar -xvf Libation.10.2.1-macOS-chardonnay-x64.tgz
4. Provide password
5. (errors appear throughout tar -xvf listing)
6. Run ... spctl ... open ... command string
7. (error -10825)

**Expected behavior**
I expected the install to complete

**Screenshots**

**Platform**
Mac 10.13.6

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
Hi @John4736

Sorry for the long delay in replying. Unfortunately, Libation is only supported macOS 10.15 (Catalina) or newer.
