### ISSUE TITLE
Docs don't say what metadata gets "fixed"

### ISSUE THREAD

**Issue by CLHatch** [rmcrackan/Libation#599]
I don't see anywhere where it's spelled out exactly what metadata gets "fixed" when you allow Libation to fix the metadata.  I see the options that you can check, but what will be the exact difference in the files with the between "fix metadata" being checked and unchecked with no other options selected?

**Comment by Mbucari** [comment]
In addition to the options that are enabled if you allow Libation to "fix up" the audiobook, it does the following:

- Adds the `TCOM` metadata tag for the narrators.
- Sets the `©gen` metadata tag for the genres.
- Unescapes the copyright symbol (replace `&#169;` with `©`)
- Replaces the recodring copyright `(P)` string with `℗`
- Replaces the embedded chapter markers embedded in the aax file with the chapter markers retrieved from Audible's API.
- Replaces the embedded cover art image with the 500x500 px cover art retrieved from Audible
