### ISSUE TITLE
2 factor Authentication

### ISSUE THREAD

**Issue by Asok76** [rmcrackan/Libation#6]
I was going to give Libation a shot as the OpenAudible has limited their features.  I cannot get logged in to my library via Libation.  I am assuming it is because I have 2 factor authentication turned on for my Amazon accounts.  Any chance you can allow log in with 2 factor Authentication?

**Comment by rmcrackan** [comment]
I use 2FA also. Just in case, I just did a fresh login, 2FA and all, and it worked for me for audible.com -- the US site

I hate that github has no way to do private messages. PM me on reddit and I'll give you my personal email so you can send me your error log. Error logs are in the Libation Files folder. Look in "Settings > Advanced Settings" to see where that is on your computer

**Comment by Asok76** [comment]
Well, bad assumption on my part.  I humbly apologize.  I have played with it some more and apparently it was my VPN that was stopping it from working.   Turned the VPN off and Viola!!  Thanks for your prompt response and for creating this software.  Keep up the great work!!!
