### ISSUE TITLE
Support mouse wheel scrolling?

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#60]
Version
* 5.2.0

Issue
* The mouse wheel does not seem to be able to scroll the main grid with all the books.

**Comment by Mulchman** [comment]
There seems to be some nuance with it. If you click in the grid then mouse scrolling will work but if you just focus the application, move the mouse into the grid area and then try to scroll it won't scroll.

Programs typically let you scroll with the mouse even if you haven't specifically focused on the control that allows scrolling. Take Chrome, for example - you can focus the main window and then still scroll the page content w/o actually selecting or manually focusing/clicking on the page content.

**Comment by rmcrackan** [comment]
Weird. Mine works exactly how you say you wish yours would. I even downloaded it from github to make sure I'm using the same build. I'd love to help look into this but I'm not even sure where to start. I'll be happy to reopen this if you have ideas

**Comment by Mulchman** [comment]
Try this: open libation.exe and then immediately try to scroll the grid w/o clicking anywhere first.

What I see is that the filter box has focus (and so no scrolling events make it to the grid).

**Comment by rmcrackan** [comment]
Sorry, boss. That works perfectly for me. At worst there's a slight delay the first time. I can even click on another window, hover over Libation and get it to scroll with the mouse wheel

**Comment by Mulchman** [comment]
What about if you type something in the filter box so that the caret and focus is definitely there and not the grid then mouse wheel over the grid and it still scrolls for you?

**Comment by rmcrackan** [comment]
Yep. Still works for me :(

**Comment by Mulchman** [comment]
Well, shoot. Maybe it's some oddity based on Windows version and/or accessibility settings or something.
