### ISSUE TITLE
Add AbsentFromLastScan or Available/Unavailable searchable

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#601]
**Is your feature request related to a problem? Please describe.**
I'm sure there are lots of scenarios where users would find this useful, but in my case, sorting by "liberated" take about ~3 minutes to complete, whereas searches are fairly fast.

**Describe the solution you'd like**
Simple boolean search would be fine. Something like one of the following:
- isAbsentFromLastScan or -wasAbsentFromLastScan
- isAvailable
- isUnavailable

**Comment by rmcrackan** [comment]
Absent from last scan would be a pretty major departure for how we do things so that's not a simple ask. Tell me more about how you envision 'is available'.

**Comment by Mbucari** [comment]
So yes, there is a property in the database that tracks whether a book was available to be download during your last library scan. And I agree it would be nice to be able to have that in search. Unfortunately, due to the way the db is structured and the way search indexing is done, this would be a pretty damn big task.

**Comment by Mbucari** [comment]
This feature has been added to [the latest release](https://github.com/rmcrackan/Libation/releases/tag/v10.3.0).

**Comment by Mbucari** [comment]
To make sure your search index is updated, please go into Libations settings folder and delete the SearchEngine folder.

**Comment by rmcrackan** [comment]
> To make sure your search index is updated, please go into Libations settings folder and delete the SearchEngine folder.

Then do a new scan to rebuild it
