### ISSUE TITLE
Make Last Download Date and (downloaded with) Libation Version Searchable

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#602]
**Is your feature request related to a problem? Please describe.**
Example use case:
You download a book with libation, but the files are corrupted. You want to find all the other books you downloaded on that date or with that version to see if they were corrupted.

**Describe the solution you'd like**
Preferably users can search for blank/non-blank entries as well as use greater-than-less-than operators or range searches.

**Comment by Mbucari** [comment]
This feature has been added to [the latest release](https://github.com/rmcrackan/Libation/releases/tag/v10.3.0).

**Comment by Mbucari** [comment]
To make sure your search index is updated, please go into Libations settings folder and delete the SearchEngine folder.

**Comment by rmcrackan** [comment]
> To make sure your search index is updated, please go into Libations settings folder and delete the SearchEngine folder.

Then do a new scan to rebuild it.

**Comment by Mbucari** [comment]
> Then do a new scan to rebuild it.

No need. Just doing a search will build it if it's absent.

**Comment by manalive** [comment]
@Mbucari 

Many thanks for this feature!
The request included making Libation Version searchable. Feasible? Should I make a new issue?
