### ISSUE TITLE
File Not Found

### ISSUE THREAD

**Issue by ElderHallow** [rmcrackan/Libation#607]
Hello,

After an update to Libation which I've downloaded today. I've just tried to download/backup three of my titles from my Audible library.

Usually I just click on the green traffic light and it starts downloading straight away.

However, since the update whenever I click on the traffic light I get the message 'File Not Found'. Is there something that I am missing? Can't seem to get it to work with any of my books.

I can't seem to remove the books to try re-adding them either. Any help would be much appreciated!

Thanks.

**Comment by Mbucari** [comment]
It sounds like Libation thinks the book has already been downloaded, and when you're clicking the icon it's trying to open the folder containing that book but is unable to find it.  Is the stoplight you're clicking green? If so, right-click it and click "Set Download Status to 'Not Downloaded'".

**Comment by ElderHallow** [comment]
That's it! Thanks so much for your help. Got the books I wanted downloaded now.
________________________________
