### ISSUE TITLE
Integrate with syncabook

### ISSUE THREAD

**Issue by marknefedov** [rmcrackan/Libation#608]
**Is your feature request related to a problem? Please describe.**
I often switch between audiobook and ebook, but always searching through pages where I ended listening is not cool. Amazon book have a read-along feature whispersync, and epub3 does too.

**Describe the solution you'd like**
Add step to align text book with audiobook via https://github.com/r4victor/syncabook
Or https://www.readbeyond.it/aeneas/

I'm sorry to bother you. But I haven't found any other place to share with idea with you. This is probably a huge task, so I'll understand if you reject it.
Tank you for your work!

**Comment by Mbucari** [comment]
I've looked into this, and I'm sorry to say it's just not something Libation is set up to do. It's a cool idea, but unfortunately we can't implement it. Sorry!
