### ISSUE TITLE
Remember window position/dimensions?

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#61]
Version
* 5.2.0

Suggestion
* Can the application window position/dimensions be remembered between each run? Might also need a test to ensure it's within the desktop dimension bounds on startup to ensure the window is visible (in the case that a monitor has been disconnected since last run).

**Comment by rmcrackan** [comment]
This is a good and long overdue idea

**Comment by rmcrackan** [comment]
I'd really only want it for the main form. I've written these before and the edge cases are slightly more complex. Multiscreen is an issue, esp if it changes. When my laptop is docked its physical screen isn't used at all and I have multiple monitors.

It's been a while, but I think when you're maximized or minimized you don't have immediate access to size and location. Closing from max is common. Closing from min is uncommon but possible. When closed from max, when you load you'd want to return to max and have 'restore' go back to your saved location and size. When closed from min, you'd just want to load to your last saved location and size. You probably just have to persist on every move and resize with a little state logic for min and max

**Comment by rmcrackan** [comment]
Resolved. Will be available in next release
