### ISSUE TITLE
"Reset library" action?

### ISSUE THREAD

**Issue by evan** [rmcrackan/Libation#613]
I'm getting set up with Libation. It's taking me a while to figure out the right settings for what I'm trying to accomplish. It would be handy to have an option to reset all library data and start over, but preserve account and settings data. I think this would be the equivalent of deleting the Books, Images, LibationContext.db, SearchEngine, and FileLocations.json folders/files, and restarting.

I initially tried to do this by removing all books from my Libation library and rescanning, but that did not work.

**Comment by rmcrackan** [comment]
Like you said, this is the equivalent of just deleting everything other than your AccountsSettings. I don't think we need a new feature for that.

To reset your books, you can either remove the books and go to Settings > Trash Bin to permanent remove, then re-scan. You can also use the Visible Books menu to set all books to 'not downloaded'. This will also let you re-download them. (It will not delete the book files.)
