### ISSUE TITLE
I think this is a bug

### ISSUE THREAD

**Issue by bungles411** [rmcrackan/Libation#614]
**Describe the bug**
When I download a book everything seems to function as intended.  When I go to play an audiobook in it's original downloaded folder it seems to also function as intended.  When I move the audiobook folder to a new location this is where things get weird.  Most of the audiobooks still work fine but I have several that now have a strange VLC error and they won't allow me to copy them into my phone to play either.  When I move the files back to the original downloaded location they begin to function again as expected.

There also seems to be some connection/dependency between the folder name and the mp4 audiobook name.  Some names when the file name is verbose (tends to happen with multiple authors or narrators) causes the file to have the same error and the file cannot be moved because the new destination wont accept a file that long.  In order to fix this you have to 1. edit the folder name 2. edit the audiobook file name to match the shortened folder name.

I am not sure if the naming piece is related to the first bug.

**To Reproduce**
1. Download Audiobook.
2. Test that it is functional in VLC
3. Move the Audiobook folder to a new location on your hard drive
4. Test for "your input can't be opened error.

This does not present on all books so I recommend downloading several to reproduce the error.

1. Go to audiobook
2. Click to open
7. See error Your input can't be opened 

**Expected behavior**
The error not only keeps the file from playing on any player but it also keeps the file from transferring to your phone to try it on mobile.

**Screenshots**
![Screenshot 2023-05-30 235913](https://github.com/rmcrackan/Libation/assets/135101529/1bafa7c6-39d6-4a56-aacd-cf927ef5ddf5)

**Platform**

[Windows 11]

**Log Files**
Attach your Libation log file here.
[_Log202305.zip](https://github.com/rmcrackan/Libation/files/11609818/_Log202305.zip)
[_Log202305_001.zip](https://github.com/rmcrackan/Libation/files/11609819/_Log202305_001.zip)

![settings4](https://github.com/rmcrackan/Libation/assets/135101529/1a025da1-19ec-47f6-b8cf-948926c390c7)
![settings3](https://github.com/rmcrackan/Libation/assets/135101529/99dcebf9-07dc-48ba-9498-d978f3fd59ca)
![settings2](https://github.com/rmcrackan/Libation/assets/135101529/ad72a2a7-1924-435e-864b-47ee0746a9fc)
![settings1](https://github.com/rmcrackan/Libation/assets/135101529/b2a7662e-4417-47fd-957b-0c3604dfa7b5)

**Comment by bungles411** [comment]
One other comment is the error looks a lot like a vlc fingerprint.  Some books have them and many do not.

**Comment by Mbucari** [comment]
Hi @bungles411. Your problem is that the saved file path is too long. It was hard to count the number of file path characters from your screenshot, but it looks to be about 284 characters long. Windows' MAX_PATH length is 260 characters. There's a way to extend that limit which Libation uses, but it looks like [VLC does not support it](https://forum.videolan.org/viewtopic.php?t=150542).

To fix this, either use a different media player that does support long paths, or move/rename some combination of folders and/or the file so that the total path length does not exceed 260 characters.

**Comment by rmcrackan** [comment]
Unfortunately, having the author and narrator in every folder name and every file name will always be quite long.

We've actually put a lot of effort into supporting long file names in windows but I can see your point. Maybe we could benefit from a setting to always limit filename to ~255. @Mbucari thoughts?

**Comment by bungles411** [comment]
That isn't the issue im trying to raise.  I understand the file name
length.  It is what it is and knowing that is really all I needed on that
side.  The issue I believe is still outstanding is as follows:

1. If I download an audiobook with libation it goes into a destination
folder.

2. If I move the audiobook to a different destination sometimea the book
will have an error.  And the book will not play or be able to be copied
into my phone.

3.  If I move the audiobook back to the original destination folder the
audiobook works again , will play on my PC and can be copied into my phone.

4.  I was not expecting a dependency between the destination folder where
the files are stored and the file functioning.  It prohibits me from
organizing my files the way I want and instead having to leave them where
they download.

Does that make sense?

**Comment by rmcrackan** [comment]
Gotcha. That is very strange and very undesirable. I had the explicit goal from day-1, back when it was just for me, to be able to re-org book files. To be clear: this is only a problem for you when the file path is excessively long, correct? That is: over ~255 characters

**Comment by bungles411** [comment]
I believe this is when the file path is short or long.  I don't believe
they are connected.

**Comment by rmcrackan** [comment]
If this is happening when your paths are short, then I don't see how Libation could be responsible nor am I sure how Libation could help. That's wacky. I honestly don't know what in the world could cause this.

**Comment by bungles411** [comment]
ok.  I will continue to investigate

**Comment by Mbucari** [comment]
@rmcrackan 
> We've actually put a lot of effort into supporting long file names in windows but I can see your point. Maybe we could benefit from a setting to always limit filename to ~255.

This is more complicated that it sounds. Supporting long paths makes some things easier. By default, windows MAX_PATH is 260 characters, and the max component length (length of any directory or file name) is 255 characters. If you have a really long file name, you'll need to shorten the directory name length to stay under the 260 character MAX_PATH, and vice versa. You have 260 characters to play with, and truncating directory and file names to fit that involves many choices. If Libation makes those choices for users, many people will be unhappy.

When you use long paths you still have a max component length of 255 characters, but MAX_PATH is 32,767 characters.

@bungles411 I'll try to reproduce your error when I get home, but since you're able to download books and play them (albeit only from their original location) this is almost certainly not a bug in Libation.

**Comment by rmcrackan** [comment]
> If Libation makes those choices for users, many people will be unhappy

Agreed. I did used to do this and people were indeed unhappy. When I thought this issue was about path length, I believed maybe it could help to have short length enforcement as an option. I'm less sold on it now.

**Comment by Mbucari** [comment]
> > If Libation makes those choices for users, many people will be unhappy
> 
> Agreed. I did used to do this and people were indeed unhappy. When I thought this issue was about path length, I believed maybe it could help to have short length enforcement as an option. I'm less sold on it now.

The downside of >1k stars. Congratulations on that, btw!

**Comment by rmcrackan** [comment]
> \>1k stars. Congratulations on that, btw!

Thanks! I've honestly never thought to look at that. I assume that's a relatively high number. It used to bring me incredible thrills when someone other than me mentioned Libation in r/audible or r/audiobooks . It still pleases me but I'm honestly surprised when someone doesn't mention it on relevant threads. I never dreamed I'd create something with this kind of popularity. It's surreal being that guy.

When I started what became Libation, inAudible worked on all titles and OpenAudible was free. I didn't think there was a market hole or anything like that. It was just something I made for me.

**Comment by Mbucari** [comment]
I can't reproduce this error. It's definitely an environment issue and not Libation's issue.

**Comment by bungles411** [comment]
Thank you for looking at it again.  Much appreciated.

**Comment by rmcrackan** [comment]
So sorry we were unable to help.

Curious: does this happen only when moving things from one folder on E drive to another E drive folder? Does it happen when moving from E to C? There's got to be something I'm not thinking of.

**Comment by bungles411** [comment]
Not a worry.  The issue im speaking of is within the same drive.  I will
try it moving to an alternate drive.
