### ISSUE TITLE
Error 1

### ISSUE THREAD

**Issue by SadAdQuirkliy** [rmcrackan/Libation#615]
my plotter has stopped working because of error 1

I don´t know if its just me or someone else but if i got to my Plots and press on the 3 dots then go to view log: there are multiple reports of "Only wrote 4022 of 1048554 bytes at offset 386916426 to "D:\\%chia coins\\plot-k32-2023-05-30-16-16-daccd45b070d20a884b0ff5a18efcdc25a9a60df3a2db8fa0b76ee0d83e01df8.plot.p1.t4.sort_bucket_066.tmp" with length 386920448. Error 1. Retrying in five minutes."

I work with Windows 10 on an Macbook
with 16gb of ram
about 1TB of storage 
and an Intel core
on chia 1.8.1

**Comment by SadAdQuirkliy** [comment]
yes I have already checked my hdd is not dead

**Comment by Mbucari** [comment]
@SadAdQuirkliy are you sure you're in the right repository? The error you're describing doesn't sound anything like this program Libation.
