### ISSUE TITLE
Feature Request/Enhancement: Add narrator to "composer" tag

### ISSUE THREAD

**Issue by bilbags** [rmcrackan/Libation#617]
This request is not related to a problem, it is an enhancement request. Many programs use the "composer" tag for the narrator for audiobooks. I would love if Libation could automatically update the "composer" tag with the narrator. Thanks for the consideration!

**Comment by CharlieRussel** [comment]
+1 -- it's one of the things I now do manually. Would be a nice enhancement.

**Comment by rmcrackan** [comment]
@Mbucari wasn't this already done in #346 ?

**Comment by Mbucari** [comment]
@rmcrackan @CharlieRussel @bilbags 

Yes, this has already been done. It's the `TCOM` tag in both the m4b and mp3 files, but it's only added to m4b files if you've selected "Allow Libation to fix up audiobook metadata"

**Comment by CharlieRussel** [comment]
@Mbucari -- Ah, critical requirement, I see. Makes total sense. Sadly, I did NOT have that box checked.

**Comment by Mbucari** [comment]
@CharlieRussel You should. There's some [good stuff in there](https://github.com/rmcrackan/Libation/issues/599#issuecomment-1540468092).
