### ISSUE TITLE
Searches on ID field are not working (10.3.3)

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#618]
**Describe the bug**
None of these fields are producing results:
![image](https://github.com/rmcrackan/Libation/assets/1682957/9715c71f-7fad-4f4a-90f5-220170280fa9)
If I just search the ID number without the including the field it _usually_ works but not always. I am not sure the pattern but I suspect books with all numeric IDs (no B0 prefix) are the most problematic.

**Comment by rmcrackan** [comment]
@Mbucari The fix now appears to be case specific. `id:B06WLMWF2S` shows only Sherlock Holmes, `id:b06WLMWF2S` shows nothing

**Comment by manalive** [comment]
This is now working for some IDs but not all numeric IDs where there are leading zeroes.

For example: https://www.audible.com/pd/Unfinished-Tales-Audiobook/0008371113

(Sorry I can't find any examples that are PLUS/Free for testing)

**Comment by rmcrackan** [comment]
Reopening because of

> The fix now appears to be case specific

...

> This is now working for some IDs but not all numeric IDs where there are leading zeroes.

**Comment by rmcrackan** [comment]
Let's try this again -- fixed in [v10.3.7](https://github.com/rmcrackan/Libation/releases/latest)
