### ISSUE TITLE
Updated Docker Image

### ISSUE THREAD

**Issue by cyndane31** [rmcrackan/Libation#619]
**Is your feature request related to a problem? Please describe.**
Love the UI, wanted to run Libation in docker on my UnRaid server. 

**Describe the solution you'd like**
I took the LinuxServer Calibre image as a template (which utilizes KasmVNC) and modified it to run Libation, creating a psuedo-webui.

**Describe alternatives you've considered**

**Additional context**
I'm new to github and not sure how to do pull requests and all that, but I've got the Dockerfile I'd be happy to provide for the image I created. Just let me know if this is something that interests you in combining with your project. Keep being awesome!

**Comment by Mbucari** [comment]
@rmcrackan IDK. I don't know anything about docker. We could try it.

@cyndane31 Did you make your script from scratch, or did you base it off of [the existing one](https://github.com/rmcrackan/Libation/commits/master/Docker/liberate.sh)? Can you post it here?

**Comment by cyndane31** [comment]
@Mbucari @rmcrackan here is a link to my fork where I uploaded the new Dockerfile. https://github.com/cyndane31/Libation/blob/master/Dockerfile

I started with the LinuxServer Calibre docker image, which itself is built on top of KasmVNC. Very new to docker myself, so its probably doing quite a few unnecessary things, but I just wanted to get to something functional. Happy to assist with streamlining it.

**Comment by pixil98** [comment]
I've never seen KasmVNC before, that's kind of neat.

If you want to include this as an official image, I think we'd want to streamline it a bit more with the existing docker image. Ideally we'd only have to build it once and use the single build to generate two images. We could add a new tag (FROM statement) to the existing Dockerfile and then update the build scripts to specify the target(s) to build in the pipeline, see https://stackoverflow.com/questions/49754286/multiple-images-one-dockerfile.

I get wary when starting to own all narrow use case builds like this on projects I'm in charge of.  I guess I'd caution against it and that there's nothing wrong with @cyndane31 owning the image until there is a greater demand for something like this. That said, it's not my project and I need to do a little tweaking of the docker image to enhance debugging soon so I can probably help review an MR if you want to go in this direction.

**Comment by rmcrackan** [comment]
I'm happy to include anything that either of you want to update in those docker files; just submit a PR. (I know exactly nothing about Docker and we don't officially support it. We run those docker builds that @pixil98 made you made as a convenience.)

**Comment by cyndane31** [comment]
@pixil98 you're mostly speaking Greek to me 😂 I'm happy to help in whatever capacity I can, but definitely don't have the dev knowledge to truly own the alternate image. 

I just missed having the UI available when I spun up my new media server, but wanted everything to be more self contained. Honestly, I could probably replace my UI container with your CLI image now that I've got my collection setup and baseline. I think the setup steps are what benefit most from having the UI available.

**Comment by pixil98** [comment]
I would agree with that. Libation is definitely designed to have a UI and while I really like using the CLI to automate it, it's always overly complicated when I need to make changes to it's config. Some of the ease of setup could be fixed in the docker image's run script and some could probably be changed in how Libation interacts with it's config. Ideally you'd be able to run the cli docker image from scratch and have it just work instead of needing to pre-seed it with a fully configured setup.

I won't have time in the near future to take on making a new docker image and integrating it with the existing one. I could find some time if you wanted to talk, maybe on discord, about how to do it and try your hand at it. I can probably also review the MR.

**Comment by rmcrackan** [comment]
The docker image is not an officially supported feature; it is a convenience which @pixil98 kindly facilitated. Since pixil98 doesn't have the time and/or inclination to fulfill this request, I'm going to close out this ticket unless you'd like to create a Pull Request.
