### ISSUE TITLE
not receiving email on "Audible is sending you an email, clip approve" screen

### ISSUE THREAD

**Issue by bennybnyhc** [rmcrackan/Libation#62]
See subject. When I try clicking "approved" anyway I got the bug screen and the link to the logs, so I am reporting it here

Thanks in advance!
[Libation-logs-07212021.zip](https://github.com/rmcrackan/Libation/files/6853150/Libation-logs-07212021.zip)

**Comment by rmcrackan** [comment]
Man this "Approved" login step has been insidious. Please follow these steps:

* close Libation
* Open your settings.json and change MinimumLevel to Verbose. This will create large detailed logs and save the source code of the login screens
* try again to login with Libation
* close Libation and change MinimumLevel back to Information -- you don't want to accidentally leave it on Verbose
* zip your logs and Verbose_ResponseBody_*.tmp files
* Please email me directly -- my address is under the picture on [this page](https://github.com/rmcrackan)

I've tried to hide personal info within logs but when logging all of this it's possible I missed something. And we'd rather it not be on a public website

**Comment by Mbucari** [comment]
Have you ever tried copying the login credentials from the installed Audible app? It's just an idea and I haven't looked into it, but if I could figure out how to do that then it would be a workaround for all login issues. Just use audible's own software to log in and register, then steal the credentials.

**Comment by Mbucari** [comment]
You wouldn't need to do it on an iPhone. Libation is windows-only, so I'd just need to figure it out for the windows audible app installed through the Windows app store. It doesn't matter if you don't plan on using that app if you're just installing it so it can handle login for Libation.

**Comment by rmcrackan** [comment]
Interesting work around. I'm not up for that at the moment but I dig the idea

**Comment by rmcrackan** [comment]
This thread seems to have gone cold. I'm going to close for now and I can reopen it again later if there's more debug info
