### ISSUE TITLE
Fatal Error?

### ISSUE THREAD

**Issue by SylvanScape** [rmcrackan/Libation#620]
**Describe the bug**
-When I try to open Libation by double-clicking the shortcut icon on my desktop, a window titled "Fatal error, pre-logging" pops up. It says "An unrecoverable error occurred. Since this error happened before logging could be initialized,"

**Screenshots**
![Libation Popup screenshot](https://github.com/rmcrackan/Libation/assets/136011069/013e41ef-a747-42cd-8724-29fca02b9474)

**Platform**
-Windows 10

**Log Files**
[Log202306.zip](https://github.com/rmcrackan/Libation/files/11691820/Log202306.zip)

**Comment by Mbucari** [comment]
Ass that window says, this error happened before logging was initialized, so no info about that error was written to the log file. However, you log file does contain what looks like a related error where Libation was unable to access the folder "C:\Users\Vivian\AppData".

Did you by chance copy your libation settings from another computer or do anything to cause "C:\Users\Vivian" to no longer be available to Libation on your system?

**Comment by SylvanScape** [comment]
Ah, so that's what that meant.  Sorry, obviously I'm not very savvy.  I can't imagine what caused it - everything's where I initially downloaded it, it was working fine for quite some time, & I haven't made any changes except for the app updates when they popup.  Is there something I can do to re-point it to the correct location?

**Comment by Mbucari** [comment]
@SylvanScape Go to "C:\Users\Vivian\Libation" and delete Settings.json, then try restarting Libation. I hope that helps.

**Comment by SylvanScape** [comment]
Sorry for the delay - I finally was able to try it, & it's working properly again! Thank you, Mbucari!
