### ISSUE TITLE
Composer/Narrator [TCOM] tag not applying except in specific situations

### ISSUE THREAD

**Issue by bilbags** [rmcrackan/Libation#621]
**Describe the bug**
This is a follow up to #617. I already had the metadata setting checked, but none of the m4b files are getting the composer [TCOM] tag. I did some tests with the audiobook fix-up settings, and the results are below.

**To Reproduce**
1. My default settings: strip "unabridged" and download in original audio format settings chosen (secondary option not chosen), which results in the [TCOM] tag **not being applied**.
2. Making one change from my default - enabled split my books - [TCOM] tag is **not** applied. 
3. Making one change from my default - download as mp3 - [TCOM] tag is **not** applied.
4. Making two changes from my default - download as mp3 & split by chapter - [TCOM] tag **is** applied. 

**Expected behavior**
For the [TCOM] tag to apply in all cases listed above, particularly when split by chapter is not enabled and download original lossless setting is enabled. 

**Platform**
Windows 10, running latest version of Libation v10.3.1.1

**Log Files**
I have 2 log files (logging was set to verbose) - one with my default settings & the other with the chaptered & MP3 settings. I did not attach them at this time, as I am uncertain if it is safe to do so with verbose logging.

**Comment by Mbucari** [comment]
@bilbags I can't reproduce what you're describing. Every single combination of options results in the TCOM tag being written.

May I ask how you're verifying whether the tag is written? The fact you're seeing them when you're splitting by chapters suggests to me that your metadata reader is struggling with large files.

**Comment by bilbags** [comment]
@Mbucari I have checked the tags with Windows Explorer, MP3Tag, Foobar, and several other programs. The issue persists when I choose to split by chapters (as m4b), so the size of the files does not seem to be a factor. All other tags are written/saved as expected (or at least I think they are - I'm not sure how many tags Libation is applying). 

I have attached screenshots of my settings, so that you can attempt to reproduce the issue with the exact same settings across the board. 

![3](https://github.com/rmcrackan/Libation/assets/109483059/850d9309-d63a-4581-909c-def871f591fd)
![2](https://github.com/rmcrackan/Libation/assets/109483059/cfcbcd0c-bb3d-42eb-abc5-90661381e710)
![1](https://github.com/rmcrackan/Libation/assets/109483059/a1ad8fb3-1a71-4c84-b4d7-8d30909c3124)

**Comment by Mbucari** [comment]
OK, there were two separate things going on here.

For the m4b files, I was literally writing a tag called "TCOM". The problem is that name isn't recognized as a composer tag for mp4 files. The correct composer tag for mp4 files is "©wrt".

For mp3 files, there was a bug in ID3 tag writer that's used for writing chapter markers. When you split the mp3 by chapters, that id3 writer isn't used so the tags were intact.

I've got fixes coming.

**Comment by bilbags** [comment]
@rmcrackan @Mbucari  Thank you - Works great now!
