### ISSUE TITLE
In addition to the options that are enabled if you allow Libation to "fix up" the audiobook, it does the following:

### ISSUE THREAD

**Issue by CLHatch** [rmcrackan/Libation#622]
In addition to the options that are enabled if you allow Libation to "fix up" the audiobook, it does the following:

- Adds the `TCOM` metadata tag for the narrators.
- Sets the `©gen` metadata tag for the genres.
- Unescapes the copyright symbol (replace `&#169;` with `©`)
- Replaces the recording copyright `(P)` string with `℗`
- Replaces the chapter markers embedded in the aax file with the chapter markers retrieved from Audible's API.
- Sets the embedded cover art image with the 500x500 px cover art retrieved from Audible

_Originally posted by @Mbucari in https://github.com/rmcrackan/Libation/issues/599#issuecomment-1540468092_

**Comment by rmcrackan** [comment]
Thanks, friend! Updated: https://github.com/rmcrackan/Libation/blob/master/Documentation/Advanced.md#settings

**Comment by CLHatch** [comment]
> Thanks, friend! Updated: https://github.com/rmcrackan/Libation/blob/master/Documentation/Advanced.md#settings

This was actually an accidental click creating a new issue when I was getting the link to your comment in another repo. :-D
