### ISSUE TITLE
Option to overwrite existing files when saving books

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#627]
**Is your feature request related to a problem? Please describe.**
When Libation moves a book's files to the books folder, it will append a number to the end if the files already exist. I'd like an option to overwrite existing files if they already exist. This came up with the problem I'm having there it's occasionally writing 10MB files out. I'd like to have it just redownload those and overwrite the existing bad ones. Additionally, it would allow for a somewhat heavy handed way to in place update the files if something like the moov atom changes again.

**Describe the solution you'd like**
I'd like an option to have the files overwrite existing files when saving books.

**Describe alternatives you've considered**
I have to clean things up manually more than I'd like.

**Comment by rmcrackan** [comment]
Included in [Libation v10.4](https://github.com/rmcrackan/Libation/releases/latest)
