### ISSUE TITLE
Output file validation

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#628]
**Is your feature request related to a problem? Please describe.**
I'm running into a problem where book being liberated are encountering errors, and it results in writing out partial m4b files. I'm still tracking down the cause of that, but it would be nice if there was the ability to validate the file was written correctly and not mark the book as liberated if it wasn't.

**Describe the solution you'd like**
I'd like the the ability to have Libation validate that the file was written correctly. This is more of a vague enhancement request. There are a couple points in the process that feel like they could be validated, when the book is initially downloaded and when the book is moved to the final destination. For the first one, it would largely depend on what kind of metadata you can get from audible. For the second one it could check that the file has the same checksum as the one in the temp folder.

**Describe alternatives you've considered**
I've considered writing a script to run periodically and flag books that are suspiciously small files.

**Comment by Mbucari** [comment]
Do you have any log files that include one or more of these silent download failures?

**Comment by pixil98** [comment]
I haven't had time to look into it yet, I just got back from a vacation and found that it had failed to download a handful of books while I was gone. I'll need to test with log config change that was mentioned and see if that writes to stdout so i can capture the logs easier. I wrote up these issues as I was trying to figure out how I could troubleshoot the issue and help mitigate and recover from it. Once I get logs I'll create a new bug report issue for it.

**Comment by Mbucari** [comment]
@pixil98 let me make sure I understand this. Your "Books" folder is set to a location on your NAS. It's downloading fine to the temp folder, but Libation's copying operation fails silently when it tries to move the book from the temp folder to the Books folder?

**Comment by pixil98** [comment]
Let me give you a bit more detail about my setup. I have the Libation docker image setup as a cron job in a kubernetes cluster. Once a week it runs Libation and downloads all new books. The in process directory is set to /tmp which is local to the node it is running on. The "Books" folder is on a NAS shared using NFS. What I was noticed is that books were periodically showing up on the NAS as partial m4b files. Because this happens automatically I don't generally see the output of Libation and the jobs are ephemeral, so I can't pull the logs off them once they stop. I can go back later tonight and see if I can pull the libation cli output from last weekend's run, it should still exist. I believe it said that the copy failed and it would try again, but the partial file still existed so if/when it tries again it won't overwrite the partial file and I'll end up with both.

I don't think the above problem is Libation's, but it could be enhanced to make it more resilient. It seems like a PostgreSQL instance that was also using the NFS server was doing something that the server didn't like and it was becoming increasingly unstable. Once I shutdown the PostgreSQL instance everything started working fine and I was just left with a mess of partial files to clean up. For now I've reset Libation's database and I'm having it redownload everything into a new folder and I'll reconcile them by hand. @rmcrackan I think the ability to overwrite existing files would still be nice as it would allow me to clean up from this much easier and in place rather than moving my existing library, downloading everything, and copying back the ones Libation can't get anymore by hand.

I don't think file validation would have helped in my situation since it would have just run into the instability of the NFS server and probably not validated meaningfully. If it did exist I would use it since I'm running it as an scheduled background process and there are probably some cases it would catch.

**Comment by rmcrackan** [comment]
Included in [Libation v10.4](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by Mbucari** [comment]
@pixil98 To clarity, Libation was erroneously marking books as liberated even if the file moving operation failed. This has been corrected.
