### ISSUE TITLE
Store Different Libraries in Different Locations

### ISSUE THREAD

**Issue by CaptainLexington** [rmcrackan/Libation#629]
I like helping my less-technical friends liberate their media, and for some of them this means using my own computer to download their libraries. Right now, their library will save to the same location as my library. I could set each library to manual updates only, and then manually switch the output dir each time I update, but it would be nicer if each account had a separately-configured output directory.

**Comment by CLHatch** [comment]
> I like helping my less-technical friends liberate their media, and for some of them this means using my own computer to download their libraries. Right now, their library will save to the same location as my library. I could set each library to manual updates only, and then manually switch the output dir each time I update, but it would be nicer if each account had a separately-configured output directory.

I know you are looking for a way to set up a new library, with a new location, but you can  SORT OF do what you want already with the renaming patterns.  This is my folder naming pattern currently:

`<account>\<if podcast->Podcasts\<if series-><series>\<-if series>(<pub date>) - <title> [<id>] {<narrator[separator(; )]>}<-if podcast><!if podcast->AudioBooks\<author[separator(; )]>\<if series-><series>\<series#[2]> - <-if series>(<year>) - <title> [<id>] {<narrator[separator(; )]>}<-if podcast>`

Notice the first part is `<account>`, so the books from each person's account gets put into their own folder (the folder name ends up being the owner's email address).

**Comment by CaptainLexington** [comment]
Actually, that's pretty much exactly what I wanted! Probably I would only request to be able to use the account nickname instead of the email address, but I can use this indefinitely

**Comment by CharlieRussel** [comment]
@CLHatch -- That's actually a quite slick solution. I like it. Thanks.

**Comment by CLHatch** [comment]
> Actually, that's pretty much exactly what I wanted! Probably I would only request to be able to use the account nickname instead of the email address, but I can use this indefinitely

I had the same idea, about an option to use the account nickname.  Would be nice.

**Comment by rmcrackan** [comment]
For an easy fix, the `<account>` idea above is great! If you want more control:

Libation isn't made to be multi-user. However, it **is** made with extreme flexibility around how to manage files. If you're comfortable mucking around in the settings files, you can set up completely separate installations of Libation for each user.

I'll detail this for Windows although it's very similar for Mac and Linux. Before you manually edit or move settings files, please **back up everything first**.

In the folder where Libation.exe lives there's appsettings.json. The sole purpose of this text file is to tell Libation where all the settings live. (Note: if the folder has the `\` character in it, as windows paths do, it uses `\\` for technical reasons.) You can edit it with Notepad or similar. With Libation closed, you can edit this setting and move all of your settings from the old location to the new one.

Now you can move your Libation where ever you want and install it again for the next friend. Download the installation zip, unzip, run it, choose New User (which will create the needed appsettings.json file) etc. and relocate these settings also. Rinse, repeat

**Comment by Mbucari** [comment]
> I would only request to be able to use the account nickname instead of the email address

This is doable and would be a good addition.

**Comment by rmcrackan** [comment]
> I would only request to be able to use the account nickname instead of the email address

Included in [Libation v10.4](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by filviu** [comment]
Not sure if I should post here or open a new issue - but for me on Libation Classic v10.6.3.1 I always get the same value for `<account nickname>`

I have one on audible.com which has the nickname `com` and one on audible.co.uk that has the nickname `co_uk` - yet all my books get the `com` value even if under the Misc column I can see the book belonging to the uk account.

**Comment by Mbucari** [comment]
@filviu Just a hunch, but do both your US and UK accounts have the same username?

**Comment by rmcrackan** [comment]
Fixed in [version 10.6.4](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by filviu** [comment]
> @filviu Just a hunch, but do both your US and UK accounts have the same username?

yes, same email for both.
