### ISSUE TITLE
Series# truncates decimal places

### ISSUE THREAD

**Issue by pixil98** [rmcrackan/Libation#632]
**Describe the bug**
When using the <Series#> tag in the path formatting, Libation will use just the integer portion of the number and drop the decimal part.

**To Reproduce**
* Configure the folder name to include <Series#> I used `<first author>/<if series-><series>/<series#> - <-if series><title short> [<id>]`
* Download a book that is numbered between two integers. I tested with the [Skyward ](https://www.audible.com/series/Skyward-Audiobooks/B07JZCTPDR) series.

**Expected behavior**
I would expect it to use the full decimal number (e.g. 2.1 for Sunreach) when creating the folder.

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/46978190/784f4a9a-be81-463c-8074-478d1ea48d43)

**Platform**
I've tested using Windows 10 and the Docker image

**Log Files**
Attach your Libation log file here.

**Comment by Mbucari** [comment]
@pixil98 Can you please enable Debug-level logging, do a library scan, then upload the LibraryScans.zip file found in your Libation settings folder?

**Comment by CLHatch** [comment]
Ideally, we should be able to have one string that will allow us to see either `01` or `01.5` as the book number, depending on if there is a decimal point or not.  Not `01.`f or `01.0` for the first case.

**Comment by CLHatch** [comment]
There might also be books with something like `01.15` or the like, not sure.  Wouldn't want those rounded, would want as many digits displayed as there are to the right of the decimal point.

**Comment by Mbucari** [comment]
@pixil98 @CLHatch There a fix for this incoming. There's a new optional [number formatter](https://github.com/Mbucari/Libation/blob/master/Documentation/NamingTemplates.md) that lets you specify a mask like `000.##` which will format `1` to `001` and `1.5` to `001.50`
