### ISSUE TITLE
HiDPI Support

### ISSUE THREAD

**Issue by dlime** [rmcrackan/Libation#634]
Would be great if the app could support HiDPI resolutions in the future (e.g. 4k displays). 

For now I'm using `run_scaled` as workaround.

To set it up on Ubuntu 22.04:
```
sudo apt -y install xvfb xpra
wget https://raw.githubusercontent.com/kaueraal/run_scaled/master/run_scaled
sudo chmod a+x run_scaled
sudo mv run_scaled /usr/local/bin
```

To run with scale factor x2:
```
run_scaled libation
```

**Comment by Mbucari** [comment]
Hmmm, I'll have to check this out. I have a laptop with a 4k display that runs Windows but I don't have any other 4k displays . The "classic" version of Libation has scaling problems, but Chardonnay (the version that runs on linux and macOS) scales correctly.

**Comment by Mbucari** [comment]
@dlime I've looked into this, and there's currently no universal DPI detection on linux with our UI framework. [It's an open issue](https://github.com/AvaloniaUI/Avalonia/issues/9390) and it may get better in the future.

However, you can set [an environment variable](https://github.com/AvaloniaUI/Avalonia/wiki/Configuring-X11-per-monitor-DPI) to override the scaling. I wasn't able to make that work inside a VM, but you may have better luck.

**Comment by rmcrackan** [comment]
Try [the latest version](https://github.com/rmcrackan/Libation/releases/latest). New changes have addressed this issue.

**Comment by Mbucari** [comment]
> New changes have addressed this issue.

Only on classic. He's on Ubuntu and using chardonnay. Chardonnay has problems on Linux High DPI displays, and that Avalonia wiki link above is the best solution currently available.

**Comment by rmcrackan** [comment]
Oops. Do I need to re-open this?

**Comment by Mbucari** [comment]
> Oops. Do I need to re-open this?

no, I closed it because there's nothing we can do about it.

**Comment by hellerblake** [comment]
for anyone else coming across this, as it is still an issue for me. Pop!_OS 24.04 normal 1080p monitors and all normal scaling. I installed the deb version, the app was so tiny I couldn't even read anything.

adding this environment variable is my current work around, and it looks normal now
`AVALONIA_GLOBAL_SCALE_FACTOR=2 libation`

**Comment by rmcrackan** [comment]
Much thanks for following up on your solution. I added it to my docs -- https://getlibation.com/docs/advanced/troubleshoot#ui-too-small
