### ISSUE TITLE
Libation Crashing While Downloading Podcast Episodes

### ISSUE THREAD

**Issue by lbhdan** [rmcrackan/Libation#635]
**Describe the bug**
While downloading podcast episodes, Libation has started crashing, with the message "Libation has crashed due to an unhandled error." The notice goes on to say:

Exception of type 'Lucene.Net.Index.MergePolicy+MergeException' was thrown.

   at Lucene.Net.Index.ConcurrentMergeScheduler.HandleMergeException(Exception exc)
   at Lucene.Net.Index.ConcurrentMergeScheduler.MergeThread.Run()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)

If I acknowledge the notice, the whole program shuts down. If I leave the notice on the screen it continues downloading, throwing a new notice after every episode is downloaded.

**Expected behavior**
The first couple of podcasts I downloaded seemed to work fine, but then this problem started. I've updated to the latest Libation version, rebooted and restarted the computer, all to no avail.

**Screenshots**

![Libation Crash Notice 061923](https://github.com/rmcrackan/Libation/assets/129123451/e5c12914-756e-4ee6-8308-e678b69f8429)

**Platform**
Windows 10

**Log Files**

[Log202306_001.zip](https://github.com/rmcrackan/Libation/files/11788028/Log202306_001.zip)

**Comment by Mbucari** [comment]
> Could this be related to the recent search engine refactor?

I'm not a betting man, but I'd put money on this being my fault ;)

**Comment by Mbucari** [comment]
@rmcrackan I may have spoken too soon. I don't know what's going on exactly, but I suspect @lbhdan's search index is corrupted, but I have no idea how that could have happened.

@lbhdan can you please delete the "SearchEngine" folder inside your Libation settings folder and try again?

**Comment by lbhdan** [comment]
@Mbucari @rmcrackan @lbhdan Looks like you diagnosed the problem. After deleting the "SearchEngine" folder, the downloads appear to be proceeding without issue. I'll let you know if it completes with no further problems.

**Comment by rmcrackan** [comment]
Nice! Thanks for following up with us.
