### ISSUE TITLE
Not auto-downloading books on Ubuntu 22.04

### ISSUE THREAD

**Issue by NeeWii** [rmcrackan/Libation#636]
**Bug description / how to reproduce**

"Import Library" settings are set to automatically run scans in background, and to auto download books. Relevant accounts are "checked" in Settings --> Accounts. Purchased a book on audible. Automatic scan picks it up and shows the title in my library list, however it will sit there indefinitely with a "red traffic light" and does not automatically download/liberate.

**Expected behavior**
That the title would be automatically liberated (i.e. downloaded locally)

**Screenshots**
n/a

**Platform**

Ubuntu 22.04
Libation Chardonnay v10.4.1.1

**Log Files**
I've attached the end of the Libation log when set to "Verbose" logging (I've pasted from roughly the point at which the scan has identified there's a new book for import). Can share more if needed.
[_Log202306-verbose_extract.log](https://github.com/rmcrackan/Libation/files/11790636/_Log202306-verbose_extract.log)

**Comment by rmcrackan** [comment]
Included in [Libation 10.4.2](https://github.com/rmcrackan/Libation/releases/latest)
