### ISSUE TITLE
Handling of multiple spaces in the file/directory naming templates

### ISSUE THREAD

**Issue by uffefl** [rmcrackan/Libation#637]
**Handling multiple spaces/other replacement chars in file/directory names**
In the illegal character replacement dialog I have several rules that replace illegal characters with spaces, or with strings that contain spaces. This sometimes lead to a replaced character space next to a natural space, which creates unsightly double-spaces in the final name.

The best example I can give is the typical `Book title: Book subtitle` pattern that most of my books follow. I would like to replace `:` with ` - `, to ensure spacing on both sides of the (now no longer present) colon. However this turns into `Book title -  Book subtitle` which looks dumb. My workaround for now is to replace with ` -`, but obviously this would fail if the colon doesn't have a trailing space. It would also look dumb if there was a space before the colon (eg. French language maybe? I don't have any books with this issue, so this is speculative).

(I'm assuming this also applies to other characters than spaces. Eg. the default underscore replacement could have the same issue, but I have not tried this.)

**Possible solution?**
I think the simplest solution would be to have an option (checkbox?) to simply trim the whitespace in the final string. This obviously wouldn't work with other replacement characters than spaces.

Making a general solution that handles any replacement text is a bit trickier though. What if the replacement text is more than one character, eg. the colon example above.

**Comment by rmcrackan** [comment]
Included in [Libation 10.4.2](https://github.com/rmcrackan/Libation/releases/latest)
