### ISSUE TITLE
Option to set timestamps for created directories and files

### ISSUE THREAD

**Issue by uffefl** [rmcrackan/Libation#638]
**Sorting by "Date Modified" doesn't make much sense on an initial download**
After liberating my entire Audible library in one go, I'm sad to see that all the directories have creation and modification timestamps equal to the time they were downloaded and not the time that I purchased them. This makes it harder to find recent purchases than it should be. Especially on the initial download since a lot of books were downloaded in a semi-random order.

I'm sure that after using the program for a while the dates will make a little more sense since I will probably download new titles immediately after buying them. Even more so with the ease of Libation compared to my previous inAudible process.

However some times I know there will be a lag where I will just use the Audible app for whatever reason and then come back to downloading multiple books in a single sitting. In this case it would be nice if the timestamps on the files and folders created reflected the purchase history.

**Suggestion: Make an option to set timestamps on created files and folders**
Make an option to set the timestamps on created files and folders (checkbox in Download/Decrypt settings?) to reflect purchase date would be nice.

Maybe an option to reflect the publication date as an alternative as well? I don't think I would be using this though.

**Comment by rmcrackan** [comment]
Included in [Libation 10.4.2](https://github.com/rmcrackan/Libation/releases/latest)
