### ISSUE TITLE
One book not appearing in export JSON

### ISSUE THREAD

**Issue by wtanksleyjr** [rmcrackan/Libation#64]
"The Void of Muirwood [B01723B9N4]" is present in my output folder, appears in the app's main list, and so on... but it doesn't appear in the JSON export.

I tried to capture a log, but apparently exports aren't logged at all, so I can't show you anything from the log.

I have this as a Kindle Unlimited With Free Narration, so it might be related to that -- but I tested, and none of the other Free Narration books fail to show up in the exports (although they disappear as soon as I remove the loan).

The only thing I can see that's unusual is that this is the very most recent book in my library.

**Comment by rmcrackan** [comment]
That's just strange. Libation doesn't care where you got it from. Either it can import it or it can't. Do the other export formats work for you?

Off the top of my head, that shouldn't be possible so obviously I'm wrong. I'll poke around at the json export and see if I can find what I'm wrong about. If nothing else, I can whip up some better debug logging until we can find the cause.

**Comment by rmcrackan** [comment]
I verified: anywhere that gets the full list of books pulls from near identical code with only slight variations depending on whether it's read-only vs needs to write back to the database. If your other export attempts reveal the same omission, is there a way for you to get me access to your database? I'd recommend something like zipping the LibationContext.db files and emailing me a dropbox link

**Comment by wtanksleyjr** [comment]
Hold on, it just showed up.

I can't think of any reason for this ... at all. It's been in the app for _days_, the m4b file fetched, but repeated exports and grep didn't show a match for "Void" (except in other books with that in their title, of course). Now grep has no problem seeing the book. Dang. Now I wish I'd saved the old json file, because I think I'm going crazy.
