### ISSUE TITLE
How to build from source?

### ISSUE THREAD

**Issue by Erudition** [rmcrackan/Libation#640]
**Is your feature request related to a problem? Please describe.**
Yeah, I want to try Libation, which compiles to gnu/linux platforms, but my daily driver is Guix and there are no premade packages for that!

**Describe the solution you'd like**
I don't expect a premade package for something as niche as Guix currently is. I could build it from source instead if build instructions were provided. That said, I may be able to take a swing at making the package myself if that works. So far I have not had much luck trying to copy the github runners, and I don't know dotnet very well.

**Describe alternatives you've considered**
I tried running the windows version in Wine, but it doesn't make it past the setup screen

**Additional context**
I don't see a makefile or anything resembling a build script, otherwise I normally can figure out how to build from source on my own...

**Comment by rmcrackan** [comment]
On my desktop, I just use Visual Studio (not the same as VS Code). For releases, you can see the `dotnet` commands in our yaml files. This is the step doing the heavy lifting:

https://github.com/rmcrackan/Libation/blob/master/.github/workflows/build-linux.yml#L88-L99

**Comment by Mbucari** [comment]
@Erudition You'll need to install the .NET SDK to build Libation.

[See these instructions](https://learn.microsoft.com/en-us/dotnet/core/install/linux)

Run these build commands within the `Source` directory. You may execute them in any order. Set variables `$OUTPUT` to the build directory and `$RUNTIME_ID` to the appropriate [runtime identifier](https://learn.microsoft.com/en-us/dotnet/core/rid-catalog) for your system.
```Shell
# The Primary Libation Program
dotnet publish \
  LibationAvalonia/LibationAvalonia.csproj \
  --runtime $RUNTIME_ID \
  --configuration Release \
  --output $OUTPUT \
  -p:PublishProfile=LibationAvalonia/Properties/PublishProfiles/LinuxProfile.pubxml

# OS-Specific utilities required by Libation
dotnet publish \
  LoadByOS/LinuxConfigApp/LinuxConfigApp.csproj \
  --runtime $RUNTIME_ID \
  --configuration Release \
  --output $OUTPUT \
  -p:PublishProfile=LoadByOS/Properties/LinuxConfigApp/PublishProfiles/LinuxProfile.pubxml

# The "Hangover" utility app
dotnet publish \
  LibationCli/LibationCli.csproj \
  --runtime $RUNTIME_ID \
  --configuration Release \
  --output $OUTPUT \
  -p:PublishProfile=LibationCli/Properties/PublishProfiles/LinuxProfile.pubxml

# Command-line interface for Libation
dotnet publish \
  HangoverAvalonia/HangoverAvalonia.csproj \
  --runtime $RUNTIME_ID \
  --configuration Release \
  --output $OUTPUT \
  -p:PublishProfile=HangoverAvalonia/Properties/PublishProfiles/LinuxProfile.pubxml

```

**Comment by rmcrackan** [comment]
I'm closing this since the question has been answered. However, feel free to continue the conversation here; we'll still get notifications of new messages and can respond.
