### ISSUE TITLE
Libation keeps crashing and continuously asks for credentials/2FA

### ISSUE THREAD

**Issue by sicahjes** [rmcrackan/Libation#647]
**When I try to download files, the system shits down. Constantly asks for login details.**
Whenever I queue more than one item, Libation freezes and shuts down. I've also had to force freeze it quitting. it also continuously asks for login information for two accounts (one AU one US, but using same email). I removed these two accounts as figured the same email was creating an issue with that, but the crashing continues. 

I have checked for an update and it says I'm updated, but when I open Libation it says an update is available. I choose 'yes' to download it and the window closes but nothing happens. 

To Reproduce
Steps to reproduce the behavior: add items to the question to be downloaded

Platform
Mac Big Sur 11.7.4 (cannot upgrade beyond this). 
[June 25 Log File.docx](https://github.com/rmcrackan/Libation/files/11877776/June.25.Log.File.docx)

**Comment by Mbucari** [comment]
@sicahjes I'm sorry this is happening for you. I just tested Libation on Monteray (the only macOS version I have available to me), and everything works as expected.

If you're getting prompted for login then that means Libation was never able to log in to your amazon account properly. Here's what I recommend doing.

1. Go to your Libation settings folder (inside your user folder) and delete AccountSettings.json file
2. Restart Libation and add only one of your accounts.
3. From the menu, select Import > Scan Library
4. You'll be prompted to log in to your Audible account. I'd recommend not even entering your password but instead clicking _Trouble logging in? Click here to log in with your browser._
5. Complete the login processes and then try downloading books from your account.

If that still doesn't work, please let me know and also post your **Libation** log file (found in the same folder as AccountSettings.json. Name startes with "Log" or "_Log" and is a zip file.

**Comment by yassinsameh** [comment]
Just downloading a fresh install ([Libation.10.4.2-macOS-chardonnay-arm64.tgz), crashes on opening as well. 
MacOs Ventura: 13.4 @Mbucari

**Comment by Mbucari** [comment]
@sicahjes @yassinsameh I'm leaving town like right now and won't be back until Sunday, so I can't look into this any more until then.

In the meantime can you try downgrading to [v10.3.2](https://github.com/rmcrackan/Libation/releases/tag/v10.3.2) and see if that works for you?

**Comment by Mbucari** [comment]
@yassinsameh Did downgrading work? If not, what do yo mean by "fresh install"? Is that the first time Libation was installed on that machine, or do you mean that you removed a previous install and then downloaded a new one?

**Comment by Accudio** [comment]
@Mbucari I'm also seeing this issue, for a first time installation on an Apple Macbook Pro M1 with Ventura 13.4.
It crashes on startup consistently, and behaves the same with 10.4.2, 10.3.2 and arm64 and x86 versions.

I've included the details provided by the Apple crash report window in a pastebin, for the 10.3.2/arm64 combo: https://pastebin.com/82S6BazJ

**Comment by Mbucari** [comment]
@Accudio I just don't get it. I have an M1 mac running ventura and for the life of me I cannot get it to crash. I'm sorry but I really have no idea what you guy's problem is.

**Comment by rmcrackan** [comment]
We released a [new version](https://github.com/rmcrackan/Libation/releases/latest) which will hopefully shed some light on this issue. Please give it a try and attach your new log if it's still an issue.

**Comment by Mbucari** [comment]
@Accudio @sicahjes @yassinsameh 

If/when Libation crashes, it should create a file named "LibationCrash.log" in your user folder. Please upload that. I'm very curious to see them.

**Comment by rmcrackan** [comment]
This ticket seems to have gone stale so I'll close it. If you have an update though, I'll be glad to re-open it.

**Comment by Accudio** [comment]
@Mbucari @rmcrackan I've tried again with Libation 10.6.1 and I'm still getting the crash. Additionally I'm not seeing a `LibationCrash.log` in my user folder. That would be the directory that includes the directories Desktop, Downloads etc right?

**Comment by rmcrackan** [comment]
I'm reopening this since @Accudio is able to reproduce the bug.

**Comment by Mbucari** [comment]
@Accudio I made a slight change in 10.6.1. If Libation crashed _after_ it's logging system was set up, then the error message is logged to `Log202307.zip` in the Libation settings directory. THAT should be in your user profile folder ~/Libation/Log202307.zip

Can you please check for that and upload it if it exists?

**Comment by Accudio** [comment]
I don't have a Libation settings directory I'm afraid, I can't find anything named Libation in ~ except for the .app itself

**Comment by Mbucari** [comment]
@Accudio I really want to help but I'm not not very familiar with mac, so please bear with me.

Can you please try a few things for me?

Open a terminal in Libation.app/Contents/MacOS
1. Disable gatekeeper and try running LibationCli. Does it print the usage help text?
2. If Yes, try running Hangover from the command line. What happens?

**Comment by rmcrackan** [comment]
@Accudio Are you still seeing this issue?

**Comment by rmcrackan** [comment]
This issue seems to has gone cold. If anyone has an update, reply here and I'll re-open.

**Comment by Accudio** [comment]
@Mbucari Sorry for the delay here.

1. Yes, help text is printed
2. A window is spawned titled "Hangover: Libation debug and recovery tool".

So Libation wasn't working before, but now I've done those steps it's working absolutely fine with Gatekeeper re-enabled and by double-clicking `Libation.app`! Even if I delete `~/Libation` and the app and re-download it works fine.

I'm not very familiar with mac development either so I don't know if there's anything I can do to 'reset' my system to help test why it wasn't working initially.

**Comment by rmcrackan** [comment]
@Accudio Much thanks for following back up with those details. Mbucari and I can see replies here but I'm still going to keep this ticket closed for now since the issue was resolved.
