### ISSUE TITLE
Selection of 64kbps or 128kbps instead of default 128kbps

### ISSUE THREAD

**Issue by Malaya2100** [rmcrackan/Libation#648]
Hi,

I would like to thank you for the little incredible software.

Is it possible to integrate a setting of selecting 64kbps or 128kbps instead of default 128kbps while downloading?

Regards,
Malay

**Comment by rmcrackan** [comment]
Off the top of my head: instead of storing the single value, it could be an array of all options. You could just shove it into a json string and into a field, it wouldn't need to be searchable or performant. The judgement call is: what about when you don't have a match? Would a user want that as their maximum value, or minimum? My guess is, if they don't want 'best available', this that would be their max. If no value less than or equal to that exists, then use the lowest available.

**Comment by Malaya2100** [comment]
I hope to welcome this feature in future update.

Thank you guys,
Malay

**Comment by rmcrackan** [comment]
Will be available in version 10.5. Coming very soon.

**Comment by Malaya2100** [comment]
Hi Guys,

If I'm not mistaken, I think the "Normal" downloads at 32kbps and "High"
Downloads at 128kbps.

But, the question is about how to download at 64kbps which may be termed as
"Medium" or whatever.

Hope, you will integrate this too.

Thank you,
Malay

**Comment by Malaya2100** [comment]
Hi Guys,

If I'm not mistaken, I think the "Normal" downloads at 32kbps and "High" Downloads at 128kbps.

But, the question is about how to download at 64kbps which may be termed as "Medium" or whatever.

Hope, you will integrate this too.

Thank you,
Malay

**Comment by Mbucari** [comment]
@Malaya2100 There are only 2 quality options for audio quality on Audible: Normal and High. Depending on the book, Normal may be 32 kbps 22kHz or 64kbps 22kHz and High may be 64kbps 44.1kHz or 128kbps 44.1kHz. It varies title to title.

Try it on your phone app. Download a book in Normal quality and again in High. Look at the bireate and sample rate.

**Comment by Malaya2100** [comment]
Hi Michael,

As a longtime user of Audible/inaudible, I know Audible offers three
qualities in audio files.

1. AA (32kbps) (Normal)
2. AAX_6 (64kbps) (Medium)
3. AAX_7 (128kbps) (High)

I have checked again today. Mobile app Offers only 128kbps and website
offers only 64kbps as well as 128kbps. Libation normal mode only downloads
at 32kbps.

Please note that, 32kbps is not being offered now.

E.g. Blue Ocean Strategy has three qualities, but it downloads only two
(32kbps and 128kbps).

It would be a Great help if these three qualities are implemented.

Regards,
Malay
