### ISSUE TITLE
"Skip importing" popup: add the book title / filename

### ISSUE THREAD

**Issue by JakobTischler** [rmcrackan/Libation#65]
As mentioned in #58: when the "Skip importing" popup … pops … up, the user doesn't necessarily know which book is meant (because he forgot, or has multiple decryptions running, or…). 
Could you please add some info (title, filename) concerning the book that has the problem?

**Comment by rmcrackan** [comment]
Sure, I can do this. This skip feature was a band-aid from back when the decrypter was far less mature. At this point I'm concerned why it's unable to decrypt any book we throw at it.

**Comment by rmcrackan** [comment]
Fixed. It will be included in the next release

**Comment by rmcrackan** [comment]
Try [v5.3.8](https://github.com/rmcrackan/Libation/releases/tag/v5.3.8)

**Comment by JakobTischler** [comment]
I haven't managed to produce the error that results in the Skip importing modal. If (when) I do, I'll leave some feedback, if necessary.

**Comment by rmcrackan** [comment]
Perfect. Thanks!
