### ISSUE TITLE
Duplicate `CDEK` tag into `AUDIBLE_ASIN` tag

### ISSUE THREAD

**Issue by CLHatch** [rmcrackan/Libation#652]
**Is your feature request related to a problem? Please describe.**
It appears that ffprobe has problems trying to read the `CDEK` tag from `.m4b` files. Because of this, the audiobookshelf app isn't able to pull the ASIN from files created by Libation.  Audiobookshelf will attempt to read the tag  `AUDIBLE_ASIN`, however.

**Describe the solution you'd like**
Duplicate the ASIN from the `CDEK` tag into the `AUDIBLE_ASIN` tag.

**Describe alternatives you've considered**
A fix in ffprobe to allow it to read all tags.  Oh, life would be so much simpler...

**Additional context**
There was discussion in the audiobookshelf repo regarding this, the dev of the Tone app got involved as well.  He mentioned that he chose `AUDIBLE_ASIN` instead of `ASIN` for a metadata tag because the Amazon and Audible ASIN don't always match. https://github.com/advplyr/audiobookshelf/issues/1794

**Comment by rmcrackan** [comment]
Will be available in version 10.5. Coming very soon.

**Comment by charltonstanley** [comment]
This is absolutely killer!! I just started using Libation and AudioBookShelf and was about to hack myself a script together when i happened to stumble upon this. Thank you so much!!!

**Comment by wtanksleyjr** [comment]
I'm still really excited to write a script to translate the Libation .json
export into the new ABS "metadata.json" files. It'll be incredible to have
all of the complex details that Libation gives us directly imported into
AudioBookShelf instead of only being able to squeeze in the minor subset
that the old .abs or .opf formats support.

**Comment by CLHatch** [comment]
> This is absolutely killer!! I just started using Libation and AudioBookShelf and was about to hack myself a script together when i happened to stumble upon this. Thank you so much!!!

The truly awesome thing is that @Mbucari started working on this literally MINUTES after I did this feature request. :-D

**Comment by charltonstanley** [comment]
> I'm still really excited to write a script to translate the Libation .json export into the new ABS "metadata.json" files. It'll be incredible to have all of the complex details that Libation gives us directly imported into AudioBookShelf instead of only being able to squeeze in the minor subset that the old .abs or .opf formats support.

That is a really ingenious idea. Please share how it goes!

**Comment by Mbucari** [comment]
@wtanksleyjr I forgot to mention in the 10.6 release notes, but there is a new setting to export the book's metadata in a json. look at the bottom-right of the Download\Decrypt tab.

**Comment by CLHatch** [comment]
> @wtanksleyjr I forgot to mention in the 10.6 release notes, but there is a new setting to export the book's metadata in a json. look at the bottom-right of the Download\Decrypt tab.

I saw that myself.  Was worried at first, when it said it would export to `metadata.json`, but then when I tried it it actually exported to `book filename.metadata.json`. :)

Suggestion for the metadata though... could we have an option to "sanitize" it by removing the account and date added info?
