### ISSUE TITLE
Renaming/Reorganizing Books downloaded with wrong directory structure. 

### ISSUE THREAD

**Issue by KatCountryGirl** [rmcrackan/Libation#653]
Rename/Reorganize books already downloaded. 

When I first started using Libation I just used the preset settings.
Now Im using audiobooks/author/book/book.m4b(etc)

But I have a bunch just in the book name folder Id love to reorganize them using the previously mentioned setup.

I can use readarr to move/reorganize them like this but it does not move the cue, jpg or ico files. I added those in the "Import Extra Files" but its not working. Id love them all to be organized better. And I can click on any book even ones moved and it know where they were so I dont see why we cant have a "rename" option. Thanks for consider it.

**Comment by KatCountryGirl** [comment]
also a way to check for missing (already downloaded) books, and put them back in the download queue. Maybe like a check files and give the option to redownload missing.

**Comment by CLHatch** [comment]
> also a way to check for missing (already downloaded) books, and put them back in the download queue. Maybe like a check files and give the option to redownload missing.

That part you can already do....

![image](https://github.com/rmcrackan/Libation/assets/13066223/c13a0aef-bf76-41d4-8604-106c8b367b80)
![image](https://github.com/rmcrackan/Libation/assets/13066223/cf00b359-f734-47e6-a335-81a28e85bb5c)

**Comment by KatCountryGirl** [comment]
> > also a way to check for missing (already downloaded) books, and put them back in the download queue. Maybe like a check files and give the option to redownload missing.
> 
> That part you can already do, with `Set 'Downloaded' status automatically....`
> 
> ![image](https://user-images.githubusercontent.com/13066223/251058150-c13a0aef-bf76-41d4-8604-106c8b367b80.png) ![image](https://user-images.githubusercontent.com/13066223/251058304-cf00b359-f734-47e6-a335-81a28e85bb5c.png)

THANK YOU SO MUCH! I never noticed that. 

Now another question you might know. In the "Replace Download Status" How do I select certain books maybe by folder location? Its only giving me the option to do all or click each book and do one at a time. I can select a number of them but how do I only set those books to not downloaded? And If I set them all to not downloaded would it detect them and not redownload or replace the existing ones?

**Comment by rmcrackan** [comment]
> If I set them all to not downloaded would it detect them and not redownload or replace the existing ones?

If a book is set to not downloaded, then on its next download attempt it will download a new copy, possibly with a file name like "whatever (1).m4b"

**Comment by CLHatch** [comment]
> > If I set them all to not downloaded would it detect them and not redownload or replace the existing ones?
> 
> If a book is set to not downloaded, then on its next download attempt it will download a new copy, possibly with a file name like "whatever (1).m4b"

I believe you fairly recently made an update where it will replace an existing file instead of making a new `(1)` file.

**Comment by rmcrackan** [comment]
@CLHatch Sorry, you're correct. What I described is the default behavior. There is also a new setting on the 'Import settings' tab for "Overwrite existing files is they already exist"

**Comment by CLHatch** [comment]
> @CLHatch Sorry, you're correct. What I described is the default behavior. There is also a new setting on the 'Import settings' tab for "Overwrite existing files is they already exist"

Oh, I forgot that was a setting.  Was thinking it was just "new behavior".  I must have immediately gone in there and turned that on when I saw it was there. :)

**Comment by Mbucari** [comment]
@maaximal You've got an answer for one part of your issue. The other part [has been proposed before](https://github.com/rmcrackan/Libation/issues/426) but is just not feasible, so we're not going to do it.

Does that answer all your questions?

**Comment by rmcrackan** [comment]
@Mbucari Right answer, wrong "@". I believe you intended to address @KatCountryGirl 

@KatCountryGirl One part was answered by @CLHatch and the other part is not a feature we intend to pursue. See @Mbucari 's link above. Sorry.
