### ISSUE TITLE
Settings won't stick

### ISSUE THREAD

**Issue by kwhopson** [rmcrackan/Libation#657]
I tell Libation where I want to extract the files and to convert to .mp3 in Settings but as soon as I close Settings, it reverts back to default, spitting out .m4b files with an accompanying .cue files, and in the wrong location.

![Settings Won't Stick](https://github.com/rmcrackan/Libation/assets/621620/674696ac-bbe5-4d61-8360-1a21184e712f)

Windows 10, I get no error so not attaching log file.

**Comment by Mbucari** [comment]
@kwhopson There should be a "Save" button at the bottom of your settings form like this:
![image](https://github.com/rmcrackan/Libation/assets/37587114/fadad87c-6b37-4e4a-b3d1-d0cffe80dd98)

I don't see that in your screenshot, and that is DAMN weird.

@rmcrackan You got any ideas?

**Comment by CLHatch** [comment]
> @kwhopson There should be a "Save" button at the bottom of your settings form like this: ![image](https://user-images.githubusercontent.com/37587114/251331706-fadad87c-6b37-4e4a-b3d1-d0cffe80dd98.png)
> 
> I don't see that in your screenshot, and that is DAMN weird.
> 
> @rmcrackan You got any ideas?

It wouldn't explain why the save button isn't there, but he might be able to get the "Save" button by switching to the other variant?  I'm thinking he's using the "Classic", since there is no "Dark" theme option, so maybe if he installs Chardonnay over it, it will show up?

**Comment by Mbucari** [comment]
> It wouldn't explain why the save button isn't there, but he might be able to get the "Save" button by switching to the other variant?

Good idea. @kwhopson Can you try downloading the windows "chardonnay" variant and trying again?

**Comment by rmcrackan** [comment]
Sorry about this!

Bug fixed: The "Settings" dialog size was recently changed. Save and Cancel buttons were pushed outside of the dialog's bounds.

This will be fixed in v10.5.1 which will be available within the hour.

**Comment by Mbucari** [comment]
> Sorry about this!
> 
> Bug fixed: The "Settings" dialog size was recently changed. Save and Cancel buttons were pushed outside of the dialog's bounds.

I made those changes on the high DPI display of my laptop instead of the normal DPI display of my desktop. Everything looked fine and continues to look fine on my laptop, but I guess I broke it on low DPI monitors.

**Comment by rmcrackan** [comment]
[New version is now available](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by rmcrackan** [comment]
> I made those changes on the high DPI display of my laptop instead of the normal DPI display of my desktop. Everything looked fine and continues to look fine on my laptop, but I guess I broke it on low DPI monitors.

I feel ya. The DPI on my work laptop is a nightmare and I have to accept that everything is hot garbage on it. Thankfully I have normal DPI on the monitors on my docking station. I got it looking right in my normal DPI monitors.

Can you verify that my change looks right in your environments?

**Comment by Mbucari** [comment]
> Can you verify that my change looks right in your environments?

I will when I get home this evening

> The DPI on my work laptop is a nightmare

Same for me, but Libation classic is particularly bad. I was looking into this the other day, and I think I may have found the problem and the correct solution.

All forms use `System.Windows.Forms.AutoScaleMode.Font`. Changing that to `System.Windows.Forms.AutoScaleMode.Dpi` and setting `AutoScaleDimensions = new System.Drawing.SizeF(96F, 96F)` should make the forms look identicall across all dpi settings. I'll test that out when I get home and we may fix Libation classic on High DPI once and for all.

**Comment by kwhopson** [comment]
I can verify the buttons now show on a 1920x1080 screen, settings are saving, everything functions properly. Great work! Thank you for the speedy attention.
