### ISSUE TITLE
Library will now load -- import scan library no results

### ISSUE THREAD

**Issue by dwj7738** [rmcrackan/Libation#658]
**Describe the bug**

Will ask for credentials for Audible but no results when scanning libary

**To Reproduce**
removed libation entirely -- in  c:\users\username and in %appdata% and also searched %programdata%.. 
unzipped libation into a new folder.. started as a new user.. went through the welcome
audible sent sms text.. everything ok.. audible asked for login credentials when trying to scan library   0 results

**Expected behavior**

**Screenshots**

**Platform**

windows 11 
![2023-07-05_22-49-13](https://github.com/rmcrackan/Libation/assets/972436/a292f572-7dfc-43d7-a52d-6b7031f27a1f)

**Log Files**
[Log Files](https://drive.google.com/file/d/1rc7mT8MA1yr6gWTos28gKc50BtxHSxg4/view?usp=sharing) 
[Scans Log](https://drive.google.com/file/d/1jGsqL7cPhMrSvX5pp1YkIs1kt9lHojBK/view?usp=sharing)

**Comment by Mbucari** [comment]
@dwj7738 This appears to be a networking error. Something is preventing Libation from establishing an HTTPS connection.

**Comment by rmcrackan** [comment]
This ticket seems to have gone stale so I'll close it. If you have an update though, I'll be glad to re-open it.
