### ISSUE TITLE
Use full size cover art

### ISSUE THREAD

**Issue by jlnbxn** [rmcrackan/Libation#661]
**Is your feature request related to a problem? Please describe.**
The code appears to only request the default cover art provided by audible. For example, requesting [https://api.audible.com/1.0/catalog/products/B01D24NLWO?response_groups=contributors,media,price,product_attrs,product_desc,product_details,product_extended_attrs,product_plan_details,product_plans,rating,sample,sku,series,reviews,ws4v,relationships,review_attrs,categories,category_ladders,claim_code_url,periodicals,provided_review](https://api.audible.com/1.0/catalog/products/B01D24NLWO?response_groups=contributors,media,price,product_attrs,product_desc,product_details,product_extended_attrs,product_plan_details,product_plans,rating,sample,sku,series,reviews,ws4v,relationships,review_attrs,categories,category_ladders,claim_code_url,periodicals,provided_review) provides a field called "product_images", which, depending on the query parameters, gives an array of different sizes of images, the default one being 500x500, which is relatively low resolution. It looks like [this](https://m.media-amazon.com/images/I/51HiU+5mTwL._SL500_.jpg).

**Describe the solution you'd like**
Adding "&image_sizes=1215" delivers a higher resolution, which would be preferrable. It looks like [this](https://m.media-amazon.com/images/I/81WKzuPInFL._SL1215_.jpg). Additionally, the link returned by the "product_images" field is structured like this "https://m.media-amazon.com/images/I/81WKzuPInFL._SL1215_.jpg". Removing the part between the end of the filename and the file extension seemingly returns an even less compressed version of the image, see [here](https://m.media-amazon.com/images/I/81WKzuPInFL.jpg). A fallback solution to the default image would be also reasonable.

**Describe alternatives you've considered**
Embedding the images afterwards myself.

**Additional context**
This software is absolutely great, thank you for your time :) I'd do the work myself, but I'm not at all familiar with the language. I might try to do it myself anyway, but since it's a rather trivial problem, I thought I'd post it here first.

**Comment by Mbucari** [comment]
@jlnbxn Libation makes use of both image sizes. The base image IDs for both the 500x500 and the full-size native covers are stored in the DB. The cover is reduced to 80x80 for the grid and queue displays, but you can see the full-size image by clicking on the cover art in the grid. Also, the full-size image is what's downloaded and saved if you select the "Save cover art image alongside audiobook" option.

**Comment by rmcrackan** [comment]
I thought that option was for creating an additional image file and that the default behavior of fixing metadata also embedded the large cover. Either I don't understand this ticket or I misunderstand how we're embedding images.

**Comment by Mbucari** [comment]
@rmcrackan It was I who misunderstood the request.

That's a perfectly reasonable request, and I think it makes sense to embed the large image when the "High" quality option is selected and the 500x500 px image when "Normal" is selected.

**Comment by rmcrackan** [comment]
Added in [version 10.6](https://github.com/rmcrackan/Libation/releases/latest)
