### ISSUE TITLE
Split Existing into Chapters

### ISSUE THREAD

**Issue by phoenix1589** [rmcrackan/Libation#662]
I've got a Liberated audiobook, as a single file. I've now changed some settings including splitting into chapters. Is there any way to force Libation to split already liberated books? It works fine for a new book being liberated, but I can't find a way to re-download or split what it has in a single file.

**Comment by rmcrackan** [comment]
You can't split the existing file; you can re-download it as split. Check the box in Settings \> Audio File Options tab \> Split my books into multiple files by chapter. Save. Right click the green stop light for your book and set download status to 'not downloaded'. The light will turn red and your next liberate/backup will do this for you.

**Comment by rmcrackan** [comment]
@Mbucari This is a really common question. I think I chose the wrong wording for 'set to not downloaded'. Do you have any ideas to make this more intuitive to users?

**Comment by CLHatch** [comment]
> @Mbucari This is a really common question. I think I chose the wrong wording for 'set to not downloaded'. Do you have any ideas to make this more intuitive to users?

It may not be the wording... possibly it's the menu it's in.  Looking at it "## Visible Books" doesn't even look like a menu, it looks like information, so I'm thinking many don't know there are options in there.  Perhaps moving the "Set  downloads status" options to the "Liberate" menu, where everyone will see it when they are going to download books?

**Comment by phoenix1589** [comment]
I'd even tried setting the status to not-downloaded - but then missed the option under the Liberate menu (I did try sync, which didn't do anything). Now that I've seen this option under the menu, it's all working.

**Comment by Mbucari** [comment]
>  Do you have any ideas to make this more intuitive to users?

I have no better words, but I like @CLHatch's idea of enabling the full context menu on every cell. That may help clear up some of the confusion.

**Comment by rmcrackan** [comment]
I also like that. If we can think of something sensical for "copy" on the stop light, then all cells could use the same context menu: copy, then the stuff currently only on stoplight.

Regarding the wording: download again? download again on next scan? There's an answer here; I just can't find it.

**Comment by CLHatch** [comment]
> I also like that. If we can think of something sensical for "copy" on the stop light, then all cells could use the same context menu: copy, then the stuff currently only on stoplight.
> 
> Regarding the wording: download again? download again on next scan? There's an answer here; I just can't find it.

You know,  maybe there should just be a "Force Download" option that will "Liberate" even if it's a "green light"? Speaking of "green light" how about a "yellow light" if it sees there's been an update to the book online, or if the user has changed settings since the book was downloaded?

**Comment by CLHatch** [comment]
> I also like that. If we can think of something sensical for "copy" on the stop light, then all cells could use the same context menu: copy, then the stuff currently only on stoplight.
> 
> Regarding the wording: download again? download again on next scan? There's an answer here; I just can't find it.

As to what for "copy" on the "stoplight", I was thinking that might not even be needed... Would it be difficult to have a "global" set of options for all cells, then tag onto the bottom of the list for each cell whatever other options would apply to each cell?

**Comment by Mbucari** [comment]
> If we can think of something sensical for "copy" on the stop light, then all cells could use the same context menu:

I already made these changes in my repo. I chose to add "copy" to every column except the cover art and liberate columns.

> maybe there should just be a "Force Download" option that will "Liberate" even if it's a "green light"?

I like that. It's easy to implement and gives people what the really want: a way to download the same book again.

> how about a "yellow light" if it sees there's been an update to the book online, or if the user has changed settings since the book was downloaded

That sound like a lot of work that I don't want to do right now lol

**Comment by CLHatch** [comment]
> > how about a "yellow light" if it sees there's been an update to the book online, or if the user has changed settings since the book was downloaded
> 
> That sound like a lot of work that I don't want to do right now lol

Yeah, it does sound like a lot of work, keeping track of what settings would cause a "yellow light", and keeping more in the database I'm guessing from imports, comparing to the old.  Maybe next time you get real bored. :-D

**Comment by rmcrackan** [comment]
RE yellow light: agreed. Also yellow does technically have a use. In the olden days: red would be no progress and when you clicked liberate, the following would happen: download the encrypted file, change the light to yellow, decrypt, change to green. These days the steps are different and the intermediate/yellow stuff happens really fast so it gets used but isn't very useful.

**Comment by rmcrackan** [comment]
Added in [version 10.6](https://github.com/rmcrackan/Libation/releases/latest)
