### ISSUE TITLE
New Image Size

### ISSUE THREAD

**Issue by OldScotsman** [rmcrackan/Libation#666]
Firefox on Windows 10

I downloaded the new version (???) today on  Firefox on Windows 10 and there are 9 book images viewable.  Has this been reduced?  I feel there used to be more.  Is there a way to try the previous version like I used to be able to by looking for them under "Classic-Libation.?.?.?-windows-classic.zip" references which I can't find any more.  I suppose what I am saying is there a way to undo an upgrade.
All the best.
Bill

[Log202307_004.zip](https://github.com/rmcrackan/Libation/files/12000498/Log202307_004.zip)

**Comment by OldScotsman** [comment]
I can no longer log in and get this message

[Log202307_005.zip](https://github.com/rmcrackan/Libation/files/12000616/Log202307_005.zip)


SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.

   at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
   at System.Windows.Forms.SplitContainer.ApplyPanel2MinSize(Int32 value)
   at LibationWinForms.Form1.Configure_ProcessQueue() in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ProcessQueue.cs:line 19
   at LibationWinForms.Form1..ctor() in D:\a\Libation\Libation\Source\LibationWinForms\Form1.cs:line 52
   at LibationWinForms.Program.Main() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 74


Thank you.
Hope you can help
Bill

**Comment by Mbucari** [comment]
@OldScotsman 
> there are 9 book images viewable. Has this been reduced

If I understand you correctly, you're saying that when you open libation you can only see 9 rows of books where before you could see many more? And let me guess, you have a 4K monitor?

If so, this was a recent "fix" (fix in quotes because one man's fix is another man's new bug). You can still scroll down to see the rest of your books, right?

>  is there a way to undo an upgrade.

Yes, you can download old releases [here](https://github.com/rmcrackan/Libation/releases). Not that, if I correctly understand your problem, this behavior will not be reverted in future releases and older versions of Libation may stop working at any time when Audible makes changes to their service.

If you want everything to be "smaller", you can change your computer's display scaling. [See these instructions](https://support.microsoft.com/en-us/windows/view-display-settings-in-windows-37f0e05e-98a9-474c-317a-e85422daa8bb).

<hr>
> I can no longer log in and get this message...

This is a bug caused by the aforementioned "fix". This will be corrected today.

**Comment by OldScotsman** [comment]
Hello again,
Sorry to be a bother.  If there is a new version due out soon, how will I be able to load it if I can't open the old one? Is there a way to load an older version as a zip file like they used to be?
Regards.

**Comment by CLHatch** [comment]
> Hello again, Sorry to be a bother. If there is a new version due out soon, how will I be able to load it if I can't open the old one? Is there a way to load an older version as a zip file like they used to be? Regards.

You can download the release from the "releases" page here, and unzip it over your current copy.

**Comment by Mbucari** [comment]
@OldScotsman 

Here's a link to the version before that bug was introduced:

https://github.com/rmcrackan/Libation/releases/download/v10.5.1/Classic-Libation.10.5.1-windows-classic.zip

**Comment by OldScotsman** [comment]
Thank you for your patience. The version 10.5.1 is back and running. I will wait another day to update because it still wants to upload the new version which is causing my problem.
Thank you once again for a your patient with a non expert. 
I love your Program and continue to recommend.
Regards.

**Comment by CharlieRussel** [comment]
The HighDPI "fix" is not an improvement here. Two screen shots should make that clear. (And yes, I'm on a 4k monitor.) For now,  I'm reverting to 10.5.1. (And no, changing my scaling for the entire desktop is NOT an acceptable solution.)
![Libation Scaling 01](https://github.com/rmcrackan/Libation/assets/21000516/160353e1-141c-42bd-8749-88dfbcbb8449)
![Libation Scaling 02](https://github.com/rmcrackan/Libation/assets/21000516/dce29687-a016-4f14-acd1-d56c226c4ab2)

**Comment by Darktide764** [comment]
Same issue as @CharlieRussel with a 4k monitor. It's unbearable and had to downgrade.

**Comment by Mbucari** [comment]
@CharlieRussel @Darktide764 

You know you can drag that slider separator to resize the queue, right?

As far as the column widths go, that must be caused by old, unscaled column widths in the settings. I'm going to add a migration to help fix this.

@rmcrackan Hold off a little while longer.

**Comment by CharlieRussel** [comment]
@Mbucari: Of course I know. But even after I slid it over, you'll notice that the rest of it is oversize. The number of books per screen is down substantially. And seriously? I have an old man's eyes and the 10.5.1 scaling is just fine.

**Comment by OldScotsman** [comment]
I can't help but agree with that.

**Comment by Mbucari** [comment]
@rmcrackan You want to weigh in on this? Aside from @CharlieRussel's problem of tiny columns resulting from old, invalid settings, the 10.5.2 fix shows Libation the way it was intended to be displayed. It looks the same on a 1080p monitor with 100% scaling as it does on a 4k monitor with 200% scaling, and that's a good thing.

My position is that if users want everything to look smaller, then they should achieve that by adjusting their system's display scaling.

**Comment by rmcrackan** [comment]
* Option 1: keep as-is. Scaling works. In practice it doesn't work for users unless they scale their entire desktop
* Option 2: go back to old version. Scaling sucks. In practice it works for users
* Option 3: keep new (working) scaling. Create in-app scaling solution such as this [poor-man's scaling](https://stackoverflow.com/a/45431194)

3 is optimal. 2 sounds like it would please the users chiming in here and might be faster.

> `ctrl` while using the mouse scroll wheel

I like that the current implementation of ctrl+scrollwheel is horizontal scroll

**Comment by CLHatch** [comment]
> > `ctrl` while using the mouse scroll wheel
> 
> I like that the current implementation of ctrl+scrollwheel is horizontal scroll

I wasn't aware of that.  That must be specific to Classic, because it seems to just do vertical scrolling in Chardonnay.

**Comment by rmcrackan** [comment]
\#thisiswhyidrink

**Comment by CharlieRussel** [comment]
@rmcrackan -- It is indeed. :)  But on the options -- honestly, I can live with any of them. What I personally prefer is option #3, but I have zero idea how difficult it would be to implement, and how many bugs it would create/surface. I suspect it would have edge cases that could be ugly.

**Comment by rmcrackan** [comment]
Yeah, this is a no-win situation. Mbucari took a lot of effort to create the "correct" solution. But (since software development can't stop punching me in the teeth) the "correct" solution is actually less usable. A custom solution could potentially be much more work and will definitely have unintended consequences which themselves will require more work to fix. Maybe the cheapest solution is [to mail these](https://www.amazon.com/dp/B07QS6TVQM) to all of you fancy-pants users who can afford 4k monitors.

**Comment by CLHatch** [comment]
> Yeah, this is a no-win situation. Mbucari took a lot of effort to create the "correct" solution. But (since software development can't stop punching me in the teeth) the "correct" solution is actually less usable. A custom solution could potentially be much more work and will definitely have unintended consequences which themselves will require more work to fix. Maybe the cheapest solution is [to mail these](https://www.amazon.com/dp/B07QS6TVQM) to all of you fancy-pants users who can afford 4k monitors.

I'm curious if the scaling issue exists in the Chardonnay variant?  I'm running that on my dual 1080p  system.  I've not tried installing either on my wife's 4K system.

**Comment by CharlieRussel** [comment]
@rmcrackan -- Well, if you really want ugly, try running inAudible on a 4k monitor, and try converting an MP3 to M4B with chapters. Now for that, I'd definitely want [those](https://www.amazon.com/dp/B07QS6TVQM). The dialog is perfectly sized at about 720p, small at 1080p, and impossible at 4k.

Seriously, I can live with the "correct" solution, even though it takes up more real estate than I'd prefer when I'm on my laptop. (On the desktop, I have dual 4k so I've got a bit more room to work with.)

**Comment by Mbucari** [comment]
I'm going to try for option 3. It _may_ not be too difficult.

Unfortunately work stuff just got in the way and I won't be able to do anything until tomorrow.

@rmcrackan I suggest deleting the classic zip file from the 10.5.2 release in the meantime. It's a bit broken.

**Comment by CharlieRussel** [comment]
@Mbucari -- Work first, play later. ;)  And if you want someone to try it on 4k or other HighDPI monitor (I've got a Surface Book that has a 'squarer' screen, using both the built in and a connected 4k), ping me and I'll give it a try.

**Comment by rmcrackan** [comment]
I just deleted 10.5.2 altogether. I don't trust our current logic to act right for classic users in need of an upgrade if the latest release doesn't actually contain a classic zip. I'll release a new version for all varieties per normal when we get this all worked out.

**Comment by OldScotsman** [comment]
I shouldn't say this but I was happy the way things were on Windows 10 using Firefox. If the truth be told, I have no idea what Chardonnay is, well apart from the lovely wine. Grinning.

**Comment by CLHatch** [comment]
> I shouldn't say this but I was happy the way things were on Windows 10 using Firefox. If the truth be told, I have no idea what Chardonnay is, well apart from the lovely wine. Grinning.

It's an alternate release they have.  "Classic" and "Chardonnay" are described [here]https://github.com/rmcrackan/Libation/blob/master/Documentation/GettingStarted.md#download-libation-1.

**Comment by rmcrackan** [comment]
> I have no idea what Chardonnay is, well apart from the lovely wine. Grinning.

In the beginning there was just one Libation. It's what I made in an old familiar technology stack that I was familiar with and was Windows only. (Actually for its first few years it didn't have a name at all -- it was just this thing I made for myself.) Later Mbucari re-implemented the UI in a newer tech stack which was cross platform. So I retroactively called the first one Classic. The newer UI had a clean white feel. Keeping with the wine/libation/alcohol theme, I chose a white wine with the broadest name recognition. I considered Champagne but that implies superior quality and that wasn't my intent. Similarly, the debugging tool that we bundle with Libation is called "Hangover". Clearly, I like sticking to a theme.

**Comment by CLHatch** [comment]
> > I have no idea what Chardonnay is, well apart from the lovely wine. Grinning.
> 
>  Clearly, I like sticking to a theme.

So the obvious question here is why the CLI isn't called Tequila.

**Comment by Mbucari** [comment]
> I'm curious if the scaling issue exists in the Chardonnay variant?

@CLHatch 
Chardonnay scales correctly on Windows and mac, but not on Linux (due to the absence of a uniform API for determining display DPI across all the different Linux desktop environments). When I say it scales correctly I mean that on any given screen size it will look the same regardless of the display's DPI. 10.5.2 changed classic to do the same thing, and that's what people seem to be upset about. So if you're them, then yes the issue does exist on Chardonnay Windows and Mac.

**Comment by rmcrackan** [comment]
> Tequila

or maybe TOM `C`O`L`L`I`NS. (I've been messing with formatting for 20 minutes and can't get the CLI to stand out without it looking like a ransom note)

**Comment by Mbucari** [comment]
@CharlieRussel All right, I'm ready for you to take it for a test drive!

https://github.com/Mbucari/Libation/actions/runs/5527209448

**Comment by CharlieRussel** [comment]
Uh, maybe I'm feeling particularly stupid tonight, but I'm not quite sure where in that are the file(s) I need.

Charlie.
(he/him/his)

________________________________

**Comment by Mbucari** [comment]
@CharlieRussel Scroll to the bottom. Zips are in the "Artifacts" section.

**Comment by CharlieRussel** [comment]
Duh. OK, I was stupid. Got it. Downloaded classic. 

Took me a moment to find it (would be nice to have a hot key combination but I'm assuming that creates cross-platform issues if you have it for other platforms). It works, and the result is what I'd expect. However, the actual behaviour is S L O W. It feels like it isn't reacting to the clicks or the attempt to drag the bar across. Then it suddenly jumps too far, of course, because I kept trying to drag it further. 

Good news is, even the smallest setting is perfectly useable on my 27 inch 4K monitor. And when I drag it over to the 3240x2160 built in laptop screen, it's a bit small, but then I can move it back. Note that the smallness is mostly because the fonts are too small for over there and they don't change -- just the graphics and the grid itself. 

Given that it's trying to redraw in the background, and I suspect that's why the slowness, how about adding an apply button and you don't actually do the changing until either apply or save is clicked?

**Comment by Mbucari** [comment]
@CharlieRussel OK, thanks for the feedback. I've added an "Apply" button and also a second slider to control font size independently of the grid/image size.

Please let me know what you think.
https://github.com/Mbucari/Libation/actions/runs/5535206894
Also there's a little something extra in there for you ;)

**Comment by CharlieRussel** [comment]
Much better! (And a nice extra!)  The only caveat I would offer is that it's an odd place for the Apply button. I'm guessing there are other requirements that argue against putting it down with the Save button, but it's not intuitive that the new Apply button applies to both font and grid size. There's a couple of ways around that -- one is to use two Apply buttons, another might be to make that Apply button an Apply Display Settings button?  Or do a bit of line art to draw both of the sliders as going into the apply button. 

Grid size —͏–\\
͏͏͏͏͏͏͏͏͏͏͏͏ ͏ ͏ ͏ ͏ ͏ ͏/—→Apply
Font size —͏/

(OK, that's really ugly, but hopefully you see what I'm getting at. )

**Comment by rmcrackan** [comment]
Added in [version 10.6](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by CLHatch** [comment]
> @CharlieRussel OK, thanks for the feedback. I've added an "Apply" button and also a second slider to control font size independently of the grid/image size.
> 
> Please let me know what you think. https://github.com/Mbucari/Libation/actions/runs/5535206894 Also there's a little something extra in there for you ;)

> Added in [version 10.6](https://github.com/rmcrackan/Libation/releases/latest)

I'm glad to see this feature works in Chardonnay also.  One suggestion, though, it was mentioned that the scale is between 0.5 and 2.  How about showing that scale in an input box to the right of the sliders, so we can both see the exact scale, and just input the scale we want.

**Comment by CharlieRussel** [comment]
@Mbucari -- Well, that's a way to solve it that I didn't think of. And way better -- well done. 

![image](https://github.com/rmcrackan/Libation/assets/21000516/c2af09e4-4400-4846-805e-ba1046914a3c)

**Comment by CLHatch** [comment]
> @Mbucari -- Well, that's a way to solve it that I didn't think of. And way better -- well done.
> 
> ![image](https://user-images.githubusercontent.com/21000516/253157714-c2af09e4-4400-4846-805e-ba1046914a3c.png)

Looks SLIGHTLY different in Chardonnay, but definitely works.  BTW, @Mbucari , I just noticed you missed labeling the "group box", it has the generic title there.

![image](https://github.com/rmcrackan/Libation/assets/13066223/e23754ff-c883-426f-be04-0e5cc1ccc76f)

**Comment by OldScotsman** [comment]
Thank you all for your efforts.  It is most appreciated.  I am very pleased with the results on Windows 10 using Firefox.

**Comment by Mbucari** [comment]
> I just noticed you missed labeling the "group box", it has the generic title there.

Doh!
