### ISSUE TITLE
Cannot load the Program and comes up with submiited errors.

### ISSUE THREAD

**Issue by OldScotsman** [rmcrackan/Libation#668]
I reported this earlier but it now says the matter is closed.  The problem is still there.  I can't log in and get the message below.

> I can no longer log in and get this message
> 
> [Log202307_005.zip](https://github.com/rmcrackan/Libation/files/12000616/Log202307_005.zip)
> 
> SplitterDistance must be between Panel1MinSize and Width - Panel2MinSize.
> 
> at System.Windows.Forms.SplitContainer.set_SplitterDistance(Int32 value)
> at System.Windows.Forms.SplitContainer.ApplyPanel2MinSize(Int32 value)
> at LibationWinForms.Form1.Configure_ProcessQueue() in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ProcessQueue.cs:line 19
> at LibationWinForms.Form1..ctor() in D:\a\Libation\Libation\Source\LibationWinForms\Form1.cs:line 52
> at LibationWinForms.Program.Main() in D:\a\Libation\Libation\Source\LibationWinForms\Program.cs:line 74

Is it possible to load an earlier version of 10.5.2 which I think is causing me the issue?

Regards
Bill

**Comment by rmcrackan** [comment]
Your previous bug ( #666 ) shows that you closed it. Fortunately we saw it and a fix for that bug is actually coming as early as today. To keep our notes clean, I'm going to close this and re-open the original bug.
