### ISSUE TITLE
You named it 5.3.x (again)

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#67]
I don't know how to get in contact with you any other way, but the latest release is 5.3.x. instead of 5.2.5. :)

**Comment by rmcrackan** [comment]
D'oh. Fuck it -- now it's 5.3 :)

Contacting me here is fine. You can also email me directly. Email is on [this page](https://github.com/rmcrackan)

**Comment by rmcrackan** [comment]
I checked my version history. Surprisingly, this wasn't a mistake. I don't release all versions since I don't want to flood users with upgrade notifications. I did a ton of work recently and some minor features added up into a lot of incrementing version counters. Thanks for the heads up though.
