### ISSUE TITLE
Download set to MP3?

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#671]
**Describe the bug**
Somehow, in the running of two betas and then manually overwriting with the 10.6.0 zip contents, Libation was set to download MP3. This was not something I would do or did. 
**To Reproduce**

1. Copy zip contents to Libation folder (autoupdate didn't work because of previous 'beta' builds run there. 

**Expected behavior**
This should never be force-set to anything for an existing installation. 

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/21000516/832b0390-7502-492f-8ad3-5e35f5aa9933)
**Platform**
Windows 11, Libation Classic 10.6.0
**Log Files**
Attach your Libation log file here.
No log file created.

**Comment by Mbucari** [comment]
I have no idea how this happened, but it's a fluke. I just downloaded 10.5.1, ensured that "m4b" was selected, upgraded to 10.6, and verified that "m4b" was still selected.

**Comment by CharlieRussel** [comment]
I’m willing to let it go as a fluke. Goodness knows I was mucking around in the settings with the beta builds but I can’t imagine changing that setting. If someone else complains, we can always reopen it.

Charlie.
(he/him/his)

Sent from Outlook<https://aka.ms/qtex0l> on my phone. Please excuse any terseness or Autocorrect typos.
________________________________
