### ISSUE TITLE
10.6.1 Windows Chardonnay freeze

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#676]
From reddit: https://www.reddit.com/r/audible/comments/14z36j2/libation_issue_version_1061/

> I’m new to Libation and am attempting to back up my library. I’m running it on Windows 11. As I’m trying to do the initial download, Libation keeps freezing. I thought perhaps I was over taxing it because I just set it to download everything (books and podcasts - over 6000 items). So, I started downloading things individually by choosing 6 files at a time to download. But even then, it freezes. It will download maybe one or two, but then it gets to the next book, it looks as if it finishes it but it sticks and I have to end task to force a shut down. Then I have to fight with it to reopen and download one or two more books and it freezes again. I admit, I’m not a programmer and so I don’t entirely understand how everything works. My thought is to delete and reinstall and try to start over but I thought I’d ask first and maybe I wouldn’t have to start from square one. Thanks for any help.

**Comment by rmcrackan** [comment]
More details are in that thread. I'll redirect attention to this github ticket.

**Comment by Mbucari** [comment]
I'm over 200 books into downloading my whole Library on the 10.6.1 release version of chardonnay, and no problems so far. Both this and #675 seem to be environmental, and #675 is particularly perplexing. They may even be related as #675 appears to be a cross thread synchronization bug, and there's a lot of UI invoked updates in the process queue. My hunch is it's a bug in the 11.0.0 release version of Avalonia.

**Comment by rmcrackan** [comment]
Fixed (hopefully) in (version 10.6.2)[https://github.com/rmcrackan/Libation/releases/latest]
