### ISSUE TITLE
ONE SINGLE Mp3 File - with an Embedded CueSheet 

### ISSUE THREAD

**Issue by OldScotsman** [rmcrackan/Libation#677]
I was wondering if sometime in the future when you are not so busy 🤣  it would be possible to enable the downloading of Mp3 chaptered files into **ONE SINGLE FILE** with an Embedded CueSheet included.  At the moment there is an option in "Settings/Audio File Options/Download my books as .MP3 files (Transcode if necessary)".  This present option gives me a choice of a single M4b file or multiple Mp3 files.    I prefer a single M4b file with embedded chapters but some of my friends prefer Mp3 without all the clutter of dozens of files.  An embedded CueSheet in a single Mp3 file makes it easy to convert back to multiple files if required.  This I do but takes a great deal of time.

I hope this makes sense.

Thank you once again

OldScotsman

**Comment by wtanksleyjr** [comment]
The easy part of this answer: to get a single MP3 file from multiple ones,
just use a compression utility like infoZIP to combine the MP3 files into a
single ZIP file with no compression, and rename it to .mp3. It seems like
cheating but it absolutely works.

The problem is that the resulting file will have no tags; you have to
attach the tags onto the zipfile (making it no longer legal as a zipfile).
There are utilities that copy the tags from the first mp3 onto the combined
file, but I've only ever used Linux ones.

But I don't know how you're going to add the CUE into the MP3, I think it's
too big to fit into an MP3 tag. Do your friends have a utility that does
this for them?

**Comment by Mbucari** [comment]
I've actually been thinking about doing this for a while. I first learned this was a thing by looking at foobar2000's metadata fields. I'm not sure how common it is for media players to support it, but it definitely exists I've tried it and it works.

**Comment by Mbucari** [comment]
@wtanksleyjr that zipped mp3 trick is a new one on me! Do most media players recognize that as a valid format?

**Comment by wtanksleyjr** [comment]
Yeah, 0-zipped MP3 with tags appended has worked on all the players I've
thrown at it (including Smart Audiobook Player, Listen, and
Audiobookshelf). My one uncertainty is whether they're supporting it as a
gimmick or as something the engineers expected.

When I asked ChatGPT it was too polite to call me a liar, but it thought it
might just be a coincidence, and it warned me not to use my powers for
piracy. Hilarious.

I also found mp3cat and mp3merge, both of which seem to just binary append
MP3 files together -- reading their documentation, apparently players scan
only for valid MP3 frames, which might explain why uncompressed MP3 zip
files just work.

-Wm

**Comment by OldScotsman** [comment]
I use in inAudible. It has a feature which converts your single m4b to either a single or multiple Mp3 files with the option of an embedded CueSheet. It is relatively simple to set up but  take 15 minutes and longer for the process to complete. I'm not sure if it is the embedded CueSheet that takes the time.  I have never tried it without it.

**Comment by rmcrackan** [comment]
@Mbucari inAudible was C#/.net. If you reflect/decompile it you might see some awfully familiar bits of old code :) It's pretty easy to reflect although the reflectors somehow mess up the using directives here. It's been a few years but if I recall correctly, he has a custom `Action` that the reflectors wrongly assume is the `System.Action` delegate.

**Comment by OldScotsman** [comment]
I'm afraid it takes all my skill in figuring out how to get a program to do what it claims in can do, never mind how it does it.  That's where clever chappies like you come in, to help me, hopefully.  😉

**Comment by Mbucari** [comment]
@rmcrackan Thanks, but this one was pretty darned simple. I also found and fixed a bug in ConvertToMp3 that has been there since god-knows how long.

@OldScotsman We've got you covered!

**Comment by OldScotsman** [comment]
You mean there is hope in sight?  😎

**Comment by Mbucari** [comment]
> You mean there is hope in sight? 😎

Yup! It'll be in the next release, and you won't have to do anything special. Just download as mp3.

**Comment by OldScotsman** [comment]
What a man.  You are great, My hero, snivel, snivel.  😁  
Well worth another donation to keep Libation what it is.  👏 👍 👌

**Comment by rmcrackan** [comment]
> Yup! It'll be in the next release, and you won't have to do anything special. Just download as mp3.

Version 10.6.3 [will be available here](https://github.com/rmcrackan/Libation/releases/latest) within the hour
