### ISSUE TITLE
Import non-Audible files

### ISSUE THREAD

**Issue by DannyBeanz** [rmcrackan/Libation#681]
Hey,

I've succesffuly downloaded and decrypted my Audible library, but have a number of non-Audible books.  Is it possible to add these to Libation for central management, or is this not possible.

If it's not possible, can you recommend a Windows app that might work well for managing both the Audible and non-Audible files?

Thanks

**Comment by rmcrackan** [comment]
I like this idea in principle. However a lot of how Libation does things behind the scenes is extremely audible-centric. Changing this would be an overhaul I'm not prepared to make.

Some people recommend audiobookshelf or plex. I've personally never used either one myself.

**Comment by DannyBeanz** [comment]
Thanks for coming back to me so promptly.
