### ISSUE TITLE
Minor display/layout issue

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#686]
Libation Classic. Settings \> Important settings tab. Top setting has text above it which is almost entirely covered by 'My Users folder' box.

**Comment by Mbucari** [comment]
I'll try to get to this this weekend. I've had jury duty this week and it sucked!

**Comment by rmcrackan** [comment]
Ugg. A single day of jury duty is a lot. I'm so sorry you got stuck with an even longer case. Those are brutal. Only Joe Pecci/Marisa Tomei and Tom Cruise/Jack Nicholson could make a jury trial interesting.

**Comment by Mbucari** [comment]
Deliberation was the worst part. There is a frustratingly large number of morons in the world.

**Comment by rmcrackan** [comment]
The foundation of the American legal system is 12 people too stupid (sorry) to get out of jury duty

**Comment by Mbucari** [comment]
This is my first time and I wanted the experience. Now that I've had it I guarantee you I will never sit on another jury for the rest of my life.

**Comment by CLHatch** [comment]
> The foundation of the American legal system is 12 people too stupid (sorry) to get out of jury duty

I imagine all you need to do to get out of jury duty is say "Well, if he were innocent he wouldn't have been charged, right?" :-D

**Comment by Mbucari** [comment]
The number of possibilities is limited only by your imagination!

You could try doing the whole "sovereign citizen" thing. Tell the court that you do not recognize it's authority to punish anyone.

Or you could just try making overtly racist or sexist comments, depending on what the situation calls for 🤣

**Comment by rmcrackan** [comment]
After all this jury duty talk, guess what letter my wife got in the mail yesterday. D'oh!

**Comment by CLHatch** [comment]
> After all this jury duty talk, guess what letter my wife got in the mail yesterday. D'oh!

Something from Publisher's Clearing House?

**Comment by rmcrackan** [comment]
Fixed in [version 10.6.4](https://github.com/rmcrackan/Libation/releases/latest)
