### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by KatCountryGirl** [rmcrackan/Libation#687]
**Describe the bug**
It wont connect to my account when opening

**To Reproduce**
Open the program and I get error 

Could not deserialize json: 

```
   at Dinah.Core.JsonHelper.FromJson[T](String json, String jsonPath, JsonSerializerSettings jsonSerializerSettings)
   at Dinah.Core.IO.JsonFilePersister`1.loadFromFile()
   at Dinah.Core.IO.JsonFilePersister`1..ctor(String path, String jsonPath)
   at AudibleUtilities.AudibleApiStorage.GetAccountsSettingsPersister() in D:\a\Libation\Libation\Source\AudibleUtilities\AudibleApiStorage.cs:line 20
   at LibationWinForms.Dialogs.AccountsDialog.populateGridValues() in D:\a\Libation\Libation\Source\LibationWinForms\Dialogs\AccountsDialog.cs:line 43
   at LibationWinForms.Dialogs.AccountsDialog..ctor() in D:\a\Libation\Libation\Source\LibationWinForms\Dialogs\AccountsDialog.cs:line 28
   at LibationWinForms.Form1.accountsToolStripMenuItem_Click(Object sender, EventArgs e) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.Settings.cs:line 11
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ScrollableControl.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
```

**Expected behavior**
the program to start correctly

**Screenshots**
https://www.dropbox.com/s/wx0w7u2cr7ndoil/capture-20230727-213217.png?dl=0

**Platform**

Windows Server 2021 64bit

**Log Files**
https://www.dropbox.com/s/x88oyk2hsgx2rcc/_Log202307_004.zip?dl=0

(edited by @rmcrackan to fix formatting links. Github auto-formatting strikes again)

**Comment by rmcrackan** [comment]
Sorry about this error. It looks like Libation can't read the file which has your `AccountsSettings.json` file. Unfortunately this is the one which has your account access. Easy fix is to close Libation, rename the file, start Libation, and re-add your account(s).

Another thing to try. First back up the file. Then see if you can open it in Notepad. If not, it's truly corrupted. If yes, open it in Notepad. Type a space, save the file, delete the space, save. (Basically, let's force it to re-save from notepad in a way that should be valid.) After this, do you still get the error?

@Mbucari Any of the json stuff could be moved into the db. I could go into the reasons why there were originally all these json files if you care. (The short version is that the db used to be unreliable so I made it contain only data directly from audible. This way it could be deleted and rebuilt without losing anything else.) If you ever go down this road, don't make account id be a true foreign key in the library book table; it's valid to delete accounts without deleting the associated books. (Of course these could be hidden/soft-deleted but my experience with soft-deletes is a headache and a half. They show up again when you forget to filter for a visibility flag or you end up with duplicates when the user re-adds an account that they can't see is actually present and hidden.)

**Comment by Mbucari** [comment]
> > @Mbucari Any of the json stuff could be moved into the db. I could go into the reasons why there were originally all these json files if you care.
> 
> I actually rather like the account info is an editable text file, separate from the rest of the DB. I keep it backed up, and can just drop it into a fresh install.

I actually do the same thing, and I find it pretty valuable. Then again I'm constantly deleting the DB during development.

**Comment by CLHatch** [comment]
> > > @Mbucari Any of the json stuff could be moved into the db. I could go into the reasons why there were originally all these json files if you care.
> > 
> > 
> > I actually rather like the account info is an editable text file, separate from the rest of the DB. I keep it backed up, and can just drop it into a fresh install.
> 
> I actually do the same thing, and I find it pretty valuable. Then again I'm constantly deleting the DB during development.

Yep.  If I want to do a "clean install", I'll just delete everything but `appsettings.json` in the app folder (telling it where my config folder is), and `Settings.json` and `AccountSettings.json` in the config folder.  Extract the latest copy into the app folder, and run it.  Honestly, those are config settings, they don't really "belong" in the database.

**Comment by CharlieRussel** [comment]
> Yep. If I want to do a "clean install", I'll just delete everything but `appsettings.json` in the app folder (telling it where my config folder is), and `Settings.json` and `AccountSettings.json` in the config folder. Extract the latest copy into the app folder, and run it. Honestly, those are config settings, they don't really "belong" in the database.
I agree. It also makes it super easy to drop a copies onto a new machine or new VM and not have to start over.

**Comment by CLHatch** [comment]
> I agree. It also makes it super easy to drop a copies onto a new machine or new VM and not have to start over.

Good to know.  That is what I was hoping would happen, but I hadn't tested it yet.

**Comment by rmcrackan** [comment]
Thanks all for the feedback. 'Leave as is' is the clear crowd favorite.

**Comment by Mbucari** [comment]
@KatCountryGirl were you able to follow @rmcrackan's suggestion and re-add your accounts? You up and running again?

**Comment by Mbucari** [comment]
@rmcrackan I think we could reduce the chances of corrupting JSON files if [JsonFilePersister](https://github.com/rmcrackan/Dinah.Core/blob/3b019851556fbe423833f9b692f96e9383488dd2/Dinah.Core/_IO/JsonFilePersister.cs#L39C1-L52C4) didn't save the file immediately after opening it.

**Comment by rmcrackan** [comment]
@Mbucari The ctor you linked to is for when the file doesn't yet exist. Saving right away seems like the right choice. The ctor below it is for when the file already exists; no saving needed.

**Comment by Mbucari** [comment]
This issue has gone col, but please feel free to reopen it if you continue experiencing this problem.
