### ISSUE TITLE
x86 version possible?

### ISSUE THREAD

**Issue by rmcrackan** [rmcrackan/Libation#690]
There's a [reddit request](https://www.reddit.com/r/audible/comments/eenfi0/new_audible_library_manager_libation/ju0d5dw/) for an x86 build. I don't know what the dependency limitations are, esp regarding AAXClean.

**Comment by Mbucari** [comment]
AAXClean has x86 libs, so all we should need to do is modify the build scripts. 

Do you want to do it for both classic and chardonnay, or just one or the other?

**Comment by Mbucari** [comment]
Never mind, they say they're on Windows Vista and that's not supported by dotnet core.

**Comment by rmcrackan** [comment]
Normally I'd say both. Since this is currently just a Windows request and since in however many years I've never gotten this request, Classic seems sufficient.

nvm -- your .net core edit came in literally as I was typing. Oh well.
