### ISSUE TITLE
macOS Catalina: Uncaught exception 'NSInternalInconsistencyException

### ISSUE THREAD

**Issue by robster7674** [rmcrackan/Libation#693]
**Describe the bug**

When starting Libation after upgrading to v10.6.3.1, it crashed with:
```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
terminating with uncaught exception of type NSException
abort() called
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'NSWindow drag regions should only be invalidated on the Main Thread!'
```
**To Reproduce**

This was a one-off.

**Expected behavior**

Be able to start Libation correctly.

**Screenshots**

n/a

**Platform**

macOS 10.15.7 (Catalina)

**Log Files**
Attach your Libation log file here.

[_Log202304.log](https://github.com/rmcrackan/Libation/files/12225983/_Log202304.log)

Crash log:
[Libation_2023-07-31-201202_BorBook.crash.txt](https://github.com/rmcrackan/Libation/files/12225945/Libation_2023-07-31-201202_BorBook.crash.txt)

**Comment by Mbucari** [comment]
Interesting! So this happens every time you start Libation?

Can you please try something?

1. Go to your libation settings folder (same place you found the log file)
2. Open Settings.json in a text editor
3. Find and delete the `MainWindow` object. I don't know if you're familiar with JSON, but you'll need to delete the entire block that looks like this (including the trailing comma)
```JSON
  "MainWindow": {
    "X": 224,
    "Y": 33,
    "Height": 720,
    "Width": 1424,
    "IsMaximized": true
  },
```
4. Save and start Libation.

**Comment by robster7674** [comment]
@Mbucari this only happened once, unfortunately. However, thanks for the hint, I will try this if I experience a similar crash in the future.

**Comment by Mbucari** [comment]
@robster7674 thanks for the bug report. I'm glad it's only happened once because I can't find the source. Please let us know if this happens again.
