### ISSUE TITLE
License Denied - To the Best of Our Knowledge

### ISSUE THREAD

**Issue by kg2187** [rmcrackan/Libation#697]
**Describe the bug**
At some point in the past, I had a subscription for "To the Best of Our Knowledge". Now every time Libation starts up, it tries to get the newest episodes. I've tried to Remove from Library in Libation, but it comes back when a new episode is out. Is it possible to remove the series from Libation, or make it not try to check for new episodes for a series that I don't have a license to?

**To Reproduce**

1. Go to the year 2009 and subscribe to the show and let the subscription run out after a year
2. Start Libation now, it will try to get the episode from this week.

**Expected behavior**
Allow users to not download a series ever, or remove a series perminitly from the library

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/63173010/ea89a004-a24c-48b0-b0ac-273d4e9cbd3b)

**Platform**
Windows 11 22H2

**Log**
3.8.2023 09:14:32	Download & Decrypt Step, Begin: [B0BRLGN5T4] To the Best of Our Knowledge: Taking Pop Seriously
3.8.2023 09:14:33	Download & Decrypt Step, Completed: [B0BRLGN5T4] To the Best of Our Knowledge: Taking Pop Seriously
3.8.2023 09:14:33	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0BRLGN5T4] To the Best of Our Knowledge: Taking Pop Seriously

**Comment by Mbucari** [comment]
Right-click on that item in the grid and click "Remove from library"
![image](https://github.com/rmcrackan/Libation/assets/37587114/106d50f7-3bac-431d-9b9c-bd630663870f)
All episodes will be moved to the "Trash Bin", which you can access from the settings menu
![image](https://github.com/rmcrackan/Libation/assets/37587114/4d2afe2a-1f93-43cd-a172-b345d67294da)
Anything in the trash bin will not be added back to Libation after a library scan, but if you delete those items from the trash bin and they're still in your Audible Library, then they will be added back to Libation after the next scan.

**Comment by Mbucari** [comment]
@kg2187 I think I may have misunderstood your situation.

Am I correct that you have already done the "Remove from library" trick, but when new episodes of that series are released the new ones are added to your library?

**Comment by kg2187** [comment]
I'll try this again, maybe I did it wrong the first time. I've removed it from my library now and it is not listed after a restart of libation. I'll let you know if it appears again when the next episode is published.

**Comment by kg2187** [comment]
I've tried to remove it twice, and it always comes back when a new episode is released. 
![image](https://github.com/rmcrackan/Libation/assets/63173010/7abad767-d7ca-4923-a1e8-ec80bb0a6730)
This maybe isn't a problem, I don't want these episodes. It's just a mild annoyance :)

**Comment by Mbucari** [comment]
@kg2187 You have these titles in your audible library, but you no longer have access to listen to them. If you go to the audible website and browse your library, you'll see that these are listed as "unavailable". Since they're still in your audible library, they are imported by libation. If you never want to see them again, you can remove them from your audible library. You could also remove them from libation by either right clicking each one and selecting "Remove from Library", or  from the "visible books" menu.
