### ISSUE TITLE
Unable to log in after entering captcha 

### ISSUE THREAD

**Issue by mitabird** [rmcrackan/Libation#70]
[_Log202107.log](https://github.com/rmcrackan/Libation/files/6873182/_Log202107.log)

**Comment by rmcrackan** [comment]
Thank you for the log file. I see where the error is happening but I need more info. Could you please go to Libation > Settings and change the log level to "Verbose", then try to log in again. Now when the error occurs, it will log a whole lot more info and will also save the login pages so I can examine them. Please zip your logs and these .tmp files for me.

Thanks!

**Comment by rmcrackan** [comment]
I found one place where a bug is likely. I'm fixing it now and the next release should fix your issue. If it does not, place reply back here and I'll look deeper into it.

Thanks again for the log. It helped a lot.

**Comment by rmcrackan** [comment]
Try [v5.3.8](https://github.com/rmcrackan/Libation/releases/tag/v5.3.8)
