### ISSUE TITLE
Add Audiobook description/content metadata

### ISSUE THREAD

**Issue by 3lB4rto** [rmcrackan/Libation#704]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
When extracting the audio and metadata also bring the description of the audiobook in NFO file (like inAudible) or also have the chance to save as TXT

**Describe alternatives you've considered**
Use Libation to bring the AAX and then use inAudible to split the process 

**Additional context**

**Comment by CLHatch** [comment]
> **Is your feature request related to a problem? Please describe.** No
> 
> **Describe the solution you'd like** When extracting the audio and metadata also bring the description of the audiobook in NFO file (like inAudible) or also have the chance to save as TXT
> 
> **Describe alternatives you've considered** Use Libation to bring the AAX and then use inAudible to split the process
> 
> **Additional context** Add any other context or screenshots about the feature request here.

They recently added an option to save the FULL metadata into a `.json` file alongside the audio files.

**Comment by Mbucari** [comment]
@3lB4rto

@CLHatch is right, this feature already exists. See the "Download/Decrypt" tab in settings:
![image](https://github.com/rmcrackan/Libation/assets/37587114/098a0e8c-6f78-4999-aa62-d471b6382210)
