### ISSUE TITLE
Show sample custom naming for both books and podcasts

### ISSUE THREAD

**Issue by CLHatch** [rmcrackan/Libation#705]
**Is your feature request related to a problem? Please describe.**
When you are editing custom paths, we can't actually see what that path will be when the item is a podcast, it only shows what will be output for an audiobook.

**Describe the solution you'd like**
Either show the example custom path for both books and podcasts, or have a toggle to show one or the other.  Or maybe even have fields we can set (Podcast: Yes/No, Series: Yes/No, etc), and have the example update itself based on that.

**Comment by Mbucari** [comment]
Seems like this relates to #700. Whatever solution we come up with there will solve this issue.

**Comment by CLHatch** [comment]
> Seems like this relates to #700. Whatever solution we come up with there will solve this issue.

Ah, I'd completely forgotten about that FR.  Definitely related.  Although it would still be nice to see the example paths for both as you edit, so we don't have to edit, go the the table, go back and edit to fix the errors, etc...

**Comment by rmcrackan** [comment]
I think this is close enough to be considered a duplicate. Let's track ideas on that other earlier request.
