### ISSUE TITLE
[Feature Request] Force rescan to detect book length changes.

### ISSUE THREAD

**Issue by tehguitarist** [rmcrackan/Libation#707]
**Is your feature request related to a problem? Please describe.**
I saw that this had been requested previously, but as occasionally a book gets updated - sometimes the length will change (recently three books by Will Wight had extra content added). I couldn't re-scan these books in, so the solution was to remove my audible account, delete the books from my database, add my audible account, and scan them in. They now have the new lengths.

**Describe the solution you'd like**
A way to check for length differences, either by a forced database update, or preferably, a notification that an audiobook has had its length changed.

**Describe alternatives you've considered**
I've mentioned a workaround above.

**Additional context**
This won't find every updated book file, but it will find some, and comparing lengths seems easy enough, but even a forced database update with fresh information would do the trick. Thanks so much for making such an incredible tool.

**Comment by Mbucari** [comment]
Fixed in version [11.0.0](https://github.com/rmcrackan/Libation/releases/tag/v11.0.0)
