### ISSUE TITLE
Newer Books Unable to Be Downloaded and Listed as [Blank Title]

### ISSUE THREAD

**Issue by Adam-kunn** [rmcrackan/Libation#709]
**Describe the bug**
Books added to library after a certain day come up as [Blank Title] when library is scanned. They are still in my Audible library, and removing and adding again does not change this. [Blank Title] books are mostly unable to be downloaded. When looked at with the edit tags, the link to audible brings up the proper page. Removing all old files and starting fresh does not change anything.

**To Reproduce**

1. Input account information
2. Import books
3. Certain books come up as [Blank Title]
4. 
**Expected behavior**
All books were expected to load property

**Screenshots**
![Screenshot 2023-08-11 002306](https://github.com/rmcrackan/Libation/assets/141990026/cff145d9-1b6d-4b4f-85cd-f714fb4b067b)

**Platform**
Windows 11

**Log Files**
Attach your Libation log file here.
[_Log202308.zip](https://github.com/rmcrackan/Libation/files/12318794/_Log202308.zip)

**Comment by JoB4031** [comment]
I was able to download a new book yesterday morning.  Today a new book or scan shows the above.  I deleted my account and resetup my account and all my books show as in the screenshot above.

**Comment by JoB4031** [comment]
I was able to download a new book yesterday morning.  Today a new book or scan shows the above.  I deleted my account and resetup my account and all my books show as in the screenshot above.  

I was able to download if I mark as downloaded and then select redownload.

Platform: Windows 10


[_Log202308.zip](https://github.com/rmcrackan/Libation/files/12319886/_Log202308.zip)

**Comment by Mbucari** [comment]
@JoB4031 Can you please email me your LibationContext.db file? It's in the same folder as your logs.

mbucari1@gmail.com

**Comment by Adam-kunn** [comment]
Certainly, but it might not be necessary. I went to bed shortly after I submitted the ticket. When I woke up, the data was correct on libation. I think it was just some sort of... temporary hiccup. So as far as I know, the issue is solved. Sorry to have been a bother.
