### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by Colonel39** [rmcrackan/Libation#714]
[_Log202210.log](https://github.com/rmcrackan/Libation/files/12367182/_Log202210.log)
[Log202210.log](https://github.com/rmcrackan/Libation/files/12367187/Log202210.log)
[Log202210_001.log](https://github.com/rmcrackan/Libation/files/12367189/Log202210_001.log)
[Log202210_002.log](https://github.com/rmcrackan/Libation/files/12367190/Log202210_002.log)
[Log202211.log](https://github.com/rmcrackan/Libation/files/12367192/Log202211.log)
[Log202301.log](https://github.com/rmcrackan/Libation/files/12367193/Log202301.log)
[Log202307.log](https://github.com/rmcrackan/Libation/files/12367194/Log202307.log)
[Log202308.log](https://github.com/rmcrackan/Libation/files/12367195/Log202308.log)

**Comment by Mbucari** [comment]
@Colonel39 We need more than that to help you.

For starters, please update to [the latest version of Libation](https://github.com/rmcrackan/Libation/releases/tag/v11.0.0) and try again. If you're still experiencing your problem, please _explain_ the problem and attach the log.**zip** file.

**Comment by Mbucari** [comment]
@Colonel39 This issue has gone stale. Please feel free to re-open it if you need further help.
