### ISSUE TITLE
PortableApp.com Packaging

### ISSUE THREAD

**Issue by kucksdorfs** [rmcrackan/Libation#723]
**Is your feature request related to a problem? Please describe.**
No, just a packaging format.

**Describe the solution you'd like**
I would like either a easy way to install and use Libation from the PortableApp platform (including update handling).

**Describe alternatives you've considered**
I believe I can manually move files around, but would prefer an installer and possibly a way to update from the PortableApps platform

**Additional context**
[Link](https://portableapps.com/development/portableapps.com_format) to the filesystem layout, ini files, etc...
Would be a bonus if Libation could be installed from the platform as well as having a paf.exe installer.

**Comment by Mbucari** [comment]
I experimented with this last year and it still works. It's windows-only, though.

1. Download and extract the [portable app launcher](https://github.com/Mbucari/Libation/releases/download/v8.3.3/LibationPortable.zip)
2. Download a copy of the [latest windows release](https://github.com/rmcrackan/Libation/releases/latest) (both classic and chardonnay will work).
3. Extract Libation program files into the portable app `\bin` directory.
4. Run `LibationLauncher.exe`
