### ISSUE TITLE
Could not locate or create appsettings.json

### ISSUE THREAD

**Issue by sg-qwt** [rmcrackan/Libation#725]
Hi there,

I'm trying to package Libation for NixOS and I almost get it working. But it seems the app has some particularity preference when first initialize appsettings.json?

When I tried to run on first startup, it failed with:
```
> ./result/bin/Libation
Unhandled exception. System.TypeInitializationException: The type initializer for 'LibationFileManager.Configuration' threw an exception.
 ---> System.ApplicationException: Could not locate or create appsettings.json
   at LibationFileManager.Configuration.getOrCreateAppsettingsFile()
   at LibationFileManager.Configuration..cctor()
   --- End of inner exception stack trace ---
   at LibationFileManager.Configuration.get_IsMacOs()
   at LibationAvalonia.Program.Main(String[] args)
Aborted (core dumped)

```

I do notice there's touch appsettings.json in Bundle_Debian.sh srcipt, 
```
touch /usr/lib/libation/appsettings.json
chmod 666 /usr/lib/libation/appsettings.json
```
but since the Nix store is immutable, I can touch an empty appsettings.json in the immutable Nix store $out/lib/libation/appsettings.json, then I don't think the app will be able to modify it anyway.

Is there any workaround for this issue? Or maybe I can simply pass in flag --config with some default appsettings.json this case?

Also normally the app will just skip the check and create a default  appsettings.json in my $HOME/.config/libation/appsettings.json anyway, is that possible this case?

Thanks!

**Comment by Mbucari** [comment]
The only purpose of `appsettings.json` if to tell Libation where its settings directory is.

Libation looks for it in four possible places. They are (in order)
1. The Libation program files directory
2. `[LocalApplicationData]/Libation/appsettings.json`
3. `[UserProfile]/Libation/appsettings.json`
4. `[TEMP]/Libation/appsettings.json`

If Libation cannot find `appsettings.json`in any of those places it will attempt to create it in each places until it succeeds. If successful, the new `appsettings.json` will point to `[UserProfile]/Libation`. If Libation is unable to find or create `appsettings.json` it will exit.

`LocalApplicationData` and `UserProfile` are special directories that have per-environment meanings.

On *nix systems, `UserProfile` should always be `$HOME`, and `LocalApplicationData` should be `~/.local/share`

`[TEMP]` is the system's temporary files directory, usually `/tmp`.

NOTE:  The `LibationFiles` directory in `appsettings.json` **must be an absolute path**, so you can't use `~/Libation`.

**Comment by Mbucari** [comment]
@sg-qwt I made some changes to the appsettings.json handling.

- `LibationFiles` can now handle unix veriables. Tested and working with `~/Libation` and `$HOME/Libation`. Basically, if `echo $LibationFiles` evaluates to the correct path then it will work.
- As I mentioned in the other thread, Libation will attempt to create the `Libation` subdirectory before trying to create `appsettings.json`
