### ISSUE TITLE
It seems like the pdf downloader has been removed on 11.0.2?

### ISSUE THREAD

**Issue by Viel0320** [rmcrackan/Libation#729]
**Describe the bug**
It seems like the pdf downloader has been removed on 11.0.2

as Screenshots below, the first book was added after update, and the second was added before, both with pdf attached.

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/12400928/c78533ba-f05b-4d35-8ff2-690a7a1e79c1)
![image](https://github.com/rmcrackan/Libation/assets/12400928/84333e49-3e86-4311-bc28-410fcfa22bf7)

**Platform**

win 11 insider canary ver. 25936.1000

**Log Files**
[_Log202309.zip](https://github.com/rmcrackan/Libation/files/12490454/_Log202309.zip)
Ignore the license ban plz,  it's unrelated with this issue.

**Comment by Mbucari** [comment]
@Viel0320 Fixed. Thank you for the report.

**Comment by CLHatch** [comment]
> @Viel0320 Fixed. Thank you for the report.

I think you forgot to bump the version in the app when you did this release.  It keeps saying there's an update right after I update, and "About" still says Chardonnay 11.02.1.

**Comment by Mbucari** [comment]
> I think you forgot to bump the version in the app when you did this release. It keeps saying there's an update right after I update, and "About" still says Chardonnay 11.02.1.

God damn it.

**Comment by OldScotsman** [comment]
The new version "Classic-Libation.-windows-classic.zip" when download and installed is 11.0.2.1 which tells you to download 11.0.3.

**Comment by CLHatch** [comment]
> The new version "Classic-Libation.-windows-classic.zip" when download and installed is 11.0.2.1 which tells you to download 11.0.3.

Allow me, @Mbucari:

God damn it.

**Comment by Mbucari** [comment]
Fixed
