### ISSUE TITLE
AbsentFromLastScan no longer working in filter since update

### ISSUE THREAD

**Issue by manalive** [rmcrackan/Libation#734]
**Describe the bug**
After updating to 11.0.3.1 neither Absent nor AbsentFromLastScan returned any results.

**Comment by rmcrackan** [comment]
Fixed in [v11.0.4](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by manalive** [comment]
Just a tip in case anyone else ends up with this problem: It still didn't work for me until I performed a Scan, then filtering on Absent started working again
