### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by cyrilgowtham** [rmcrackan/Libation#737]
im unable to sync and import by library
 Im using windows 10

**Comment by Mbucari** [comment]
Please attach your log file. It should be in `c:\users\[you]\Libation\Log####.zip`

**Comment by cyrilgowtham** [comment]
> 

[Log202309.log](https://github.com/rmcrackan/Libation/files/12568586/Log202309.log)

**Comment by cyrilgowtham** [comment]
[_Log202309.zip](https://github.com/rmcrackan/Libation/files/12568593/_Log202309.zip)
[_Log202309_001.zip](https://github.com/rmcrackan/Libation/files/12568594/_Log202309_001.zip)

**Comment by Mbucari** [comment]
@cyrilgowtham This is a truly bizarre error you're experiencing. I don't think I've seen anything like it before.

Can you please provide your library scan logs? In Libation go to Settings and change "Logging level" to "Debug"
![image](https://github.com/rmcrackan/Libation/assets/37587114/5c94f676-aace-4c0b-b6fd-2939244e747b)

Scan your accounts again. You'll find a new file named `LibraryScans.zip` in the same folder as your log files. Please upload that here.

**Comment by rmcrackan** [comment]
This ticket has gone cold. I'll be happy to re-open it if you have more info later
