### ISSUE TITLE
Add "Read" or "Finished" flag

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#742]
**Is your feature request related to a problem? Please describe.**
Nope, just something that would make it easier to sort and work with my existing library
**Describe the solution you'd like**
Audible knows whether a book is read or not read. (heck, it even knows if I've started reading, but haven't finished.) I'm not sure if they expose that in their API, but if they do, adding a tag for it would let one sort or filter on it

**Describe alternatives you've considered**
The Audible app, but I'm avoiding that

**Additional context**
![image](https://github.com/rmcrackan/Libation/assets/21000516/396b799d-6366-4ca2-a78f-4a16c5a66603)

**Comment by CharlieRussel** [comment]
@rmcrackan -- did this go stale and get lost in the shuffle? Or just not something you can easily do? I'm OK either way, but just checking since it's a year old.

**Comment by rmcrackan** [comment]
Audible has a metadata field for `is_finished`, but it's null for all of my books. Which means this is only returned to us via some search option we don't currently use. Which means trudging through the different combinations of possible search flags until I find the right one. And modifying the code, database, and search engine to store the new field(s). Then going through all the testing to see how performant it is with possibly more data being returned with the expanded search parameters. Then tweaking the download settings to make sure that lower bandwidth users don't get too many timeouts (by changing the requested page size limit). But more lower page sizes means more pages which takes longer -- and higher bandwidth users don't want the increased time in waiting for larger pagination. Which means ugg fuck it I'll put it off another year. Sorry.

**Comment by CharlieRussel** [comment]
@rmcrackan — oh, yuck!  Definitely put it off for _at least_ another year, if not forever. It’s not that big a deal.

**Comment by CharlieRussel** [comment]
Thanks @rmcrackan!

**Comment by CharlieRussel** [comment]
Downloaded and 'installed'. Works as expected, with the expected number of Audible screwups. Thanks, @rmcrackan!
