### ISSUE TITLE
Download the books from different accounts to different folders

### ISSUE THREAD

**Issue by Sir-Jeffrey-Q** [rmcrackan/Libation#745]
**Is your feature request related to a problem? Please describe.**
A challenge I have run into a few times now is that I have a few different audible accounts in my Libation setup, but I would like to be able to keep the books in those libraries separated. 

**Describe the solution you'd like**
A setting that allows me to choose the download folder based on the account the book belongs to, if I care to separate them.

**Describe alternatives you've considered**
For a while I tried running multiple instances of Libation, each with their own account and download destination, but this was very clunky and did not always work. Sometimes when I would try to open the instance tied to account A, the one tied to account B would open instead, and I could not get a third instance tied to account C to work at all, even when the downloaded file structures were fully copied and kept in separate places.

**Comment by CLHatch** [comment]
> **Is your feature request related to a problem? Please describe.** A challenge I have run into a few times now is that I have a few different audible accounts in my Libation setup, but I would like to be able to keep the books in those libraries separated.
> 
> **Describe the solution you'd like** A setting that allows me to choose the download folder based on the account the book belongs to, if I care to separate them.
> 
> **Describe alternatives you've considered** For a while I tried running multiple instances of Libation, each with their own account and download destination, but this was very clunky and did not always work. Sometimes when I would try to open the instance tied to account A, the one tied to account B would open instead, and I could not get a third instance tied to account C to work at all, even when the downloaded file structures were fully copied and kept in separate places.

You can already do this by using either the `<account>` or `<account nickname>` tag in the folder naming template.  This is the folder template I'm currently using:

`<if podcast->Podcasts\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<pub date>) - <series> - <title> [<id>]<-if podcast><!if podcast->AudioBooks\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<year>) - <title> [<id>]<-if podcast>`

And it places books as follows:

`AudioBooks\Audible\Chris\Arthur C. Clarke\Space Odyssey Series\01 - (2008) - 2001꞉ A Space Odyssey [B002UZJGYY]\2001 [B002UZJGYY].m4b`

**Comment by Sir-Jeffrey-Q** [comment]
Wow. Ok, yeah, did not realize those were so powerful. Thanks! I'll have to figure out how to use those.
