### ISSUE TITLE
Possible Interruption of service. You were denied a content license for...

### ISSUE THREAD

**Issue by KeeperOfTheFort** [rmcrackan/Libation#746]
Hi. Just started using Liberate yesterday and have encountered the same error as Issue:#592 OP "Possible Interruption of service. You were denied a content license for...".

Previously discussed here:

Possible Interruption of service. You were denied a content license for... #592
https://github.com/rmcrackan/Libation/issues/592

I have an active Audible.co.uk subscription with 803 visible audiobooks (mix of purchased and plus catalogue).

After successfully backing up 167 audiobooks the error hit and one by one all the remaining 636 audiobooks turned red in Process Queue with the words: "Possible Interruption of service" repeated at the foot of each.

Fired up to try again today and the same error persists. Tried logging out of account and logging back in and tried running through VPN but no joy.

Hope there is a remedy - happy to provide any further info :) Thx

**Comment by CLHatch** [comment]
This usually Audible "rate limiting" you, and it should fix itself in a day or two.  I think it usually happens when downloading from the "Plus Catalog", but I'm not certain.  It's happened to me twice, and it did fix itself.

**Comment by KeeperOfTheFort** [comment]
That is good news - well kinda :)

Ahh, I'll keep an eye on it over the next few days then. 

If this is a common issue, perhaps a way of limiting the connections/download requests per period to mitigate being thrown into Audible jail could be a solution - slow down to speed up maybe? Not sure how this is triggered but just thinking out loud :)

Thanks CLHatch - it's reassuring to know that downloads did resume for you!

**Comment by KeeperOfTheFort** [comment]
Great news today ... 

Downloads have resumed - whoo! :)

Thinking of stopping downloads at 100 and repeating batches of 100 daily. Hopefully, this will mitigate any firewall/algo triggers.

So, Audible "rate limiting" seems to trigger at around ~150 downloads and lasts for around 48 hours.

Would there be any chance of adding an optional "safety" daily cap to Libation settings and a warning/reminder to mitigate other peeps unknowingly landing up in Audible jail?

Incredibly impressed with Libation - it's a work of genius - and deserves a place in every audiobook lovers arsenal of tools!!

**Comment by rmcrackan** [comment]
I haven't tested large batches in a while. Last time I did though, I could download as many owned books as I wanted and limiting only kicked in if I tried to download ~100 Plus titles in a day.

A daily cap or batch cap is a good idea. We don't currently have an automated way for a new user with a small hard drive to download their whole library.

**Comment by LoisGNS** [comment]
I put in a "feature request" on this same topic before I saw this posting. I, too,  spent some time in Audible Jail when I was trying to download from my Plus catalog.
