### ISSUE TITLE
Book Stuck At 1% In Process Queue

### ISSUE THREAD

**Issue by jwoolum** [rmcrackan/Libation#748]
**Describe the bug**
I've run into an issue where a single book gets stuck at 1% download. I've tried uninstalling, updating to the latest version, and removing it from the library (then adding it back). The drive I am saving the books to still has more than half a terabyte. I can delete other books and redownload them just fine. It's just this particular book and I don't get it.

**To Reproduce**
1) Open Libation
2) Liberate->Visible Books
3) Book: Deadline by Domino Finn is stuck at 1% in the Process Queue
4) Process Queue timer continues ad infinitum.

**Expected behavior**
The book should process within several minutes.

**Screenshots**
![452t3grttrsd](https://github.com/rmcrackan/Libation/assets/143609970/50eb362c-aa58-4d2a-9c03-1367d6e92b3d)

**Platform**
Windows 10

**Log Files**
[_Log202309.zip](https://github.com/rmcrackan/Libation/files/12639725/_Log202309.zip)
[_Log202309_001.zip](https://github.com/rmcrackan/Libation/files/12639726/_Log202309_001.zip)
[_Log202308.zip](https://github.com/rmcrackan/Libation/files/12639727/_Log202308.zip)
[_Log202308_001.zip](https://github.com/rmcrackan/Libation/files/12639728/_Log202308_001.zip)
[_Log202308_002.zip](https://github.com/rmcrackan/Libation/files/12639729/_Log202308_002.zip)
[_Log202308_003.zip](https://github.com/rmcrackan/Libation/files/12639730/_Log202308_003.zip)

**Comment by rmcrackan** [comment]
Fixed in [v11.0.4](https://github.com/rmcrackan/Libation/releases/latest)
