### ISSUE TITLE
Remove from library for all books selected

### ISSUE THREAD

**Issue by TJM** [rmcrackan/Libation#752]
**Is your feature request related to a problem? Please describe.**
I have a large number of books that I added because they were free, but I don't want them. I can right click and "remove from library" on each one, but I would prefer to search, select all and remove them all. Even when a large number are selected it only seems to remove one.

**Describe the solution you'd like**
Remove all books selected from library

**Describe alternatives you've considered**
* Import -> Remove Library Books .... but then the "search" field goes away, sorting by series makes them line up nicely, but still need to check each checkbox. They highlight like they are selected, but no way to apply the remove action to the selection. It is, however a LOT faster than using the right click -> remove from library option on each title :)

**Additional context**

**Comment by rmcrackan** [comment]
No problem. After you search and you're sure that the grid is only the stuff you want to remove (including the titles scrolled off screen), go to the top menu: Visible Books \> Remove from library

**Comment by TJM** [comment]
Yep, sorry, I meant to come back and confirm that I found that option after clicking like 50 checkboxes ;)
