### ISSUE TITLE
The search bar produces zero results no matter what

### ISSUE THREAD

**Issue by boomschtick** [rmcrackan/Libation#753]
**Describe the bug**
No matter what I put in the search bar, I get zero results.  Even a simple search of the word 'the' returns no results.

**To Reproduce**

Put literally anything in the search bar and zero results are returned.  This is true whether I use Lucene syntax or not.

**Expected behavior**
See results that are relevant to the search term

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/1853797/ca9c4a75-4ad9-4bb0-98e1-06713db74974)
![image](https://github.com/rmcrackan/Libation/assets/1853797/274cb4ed-8b3b-462c-9d5b-740348f63e92)

**Platform**

Windows 11

**Log Files**
Attach your Libation log file here.

**Comment by rmcrackan** [comment]
Thanks for your log file. I'm seeing bugs related to the search engine -- I think a file got corrupted. With Libation closed, go to that folder where your log files live. Delete the folder `SearchEngine`. Open Libation. The grid will be empty. Do a scan. This will re-build your search engine. Search should now work as normal.

Try to search for something that isn't a word like `the`. That gives me blank results also. I think Lucene ignores stuff like: the, of, a, an.

**Comment by boomschtick** [comment]
Yep... that did it.  Soooo nice to have that working.

**Comment by rmcrackan** [comment]
w00h00 -- thanks for following up. I was hoping this would be an easy one. Cheers!
