### ISSUE TITLE
Art covers missing

### ISSUE THREAD

**Issue by fsafq41** [rmcrackan/Libation#757]
**Describe the bug**
Art covers are not always downloaded and therefore not embedded in the m4b liberated files

**To Reproduce**
Just check process queue for Finished liberated file with no art cover
Or
"Click to see full size" on Cover shows no art cover

Re-scanning the library does not seem to address the problem

**Screenshots**
For book with no art cover, this default grey cover is shown
![a](https://github.com/rmcrackan/Libation/assets/129561979/be3b9ae7-e3ed-494a-bcf8-ab40c24244a9)

**Platform**
Mac

**Comment by Mbucari** [comment]
@fsafq41 Can you please provide links to some of the books that have this problem?

**Comment by fsafq41** [comment]
For example:
https://www.audible.com/pd/B08S91CGBY

it doesn’t not seem to be book specific as it is impacting almost 50% of my library.
The download of each cover seemed to have often timed out when I download my library initially on a slow internet connection.
Request: when rescanning/refreshing the library, is it possible to add a check on the missing covers and download them. Alternatively, add a cover check function.

**Comment by Mbucari** [comment]
> For example: https://www.audible.com/pd/B08S91CGBY

Request: when rescanning/refreshing the library, is it possible to add a check on the missing covers and download them. Alternatively, add a cover check function? Thanks

That _should_ already be happening. Every time you launch Libation it tries to load the cover art from the `Images` folder, and if it isn't found then Libation downloads it.

Can you please share your LibationContext.db with me? mbucari1@gmail.com

**Comment by fsafq41** [comment]
Thank you. Re-scanned my library on a fiber connection and confirmed that all my missing covers have been updated.

Note: you will need need to re-liberate or edit manually the tags of all the books which had been liberated with missing covers.
