### ISSUE TITLE
Stall during liberate

### ISSUE THREAD

**Issue by CMuser28** [rmcrackan/Libation#758]
Libation v11.0.4.1
Cannot choose more than 1 book to liberate at a time because that causes the liberation to stall

**Platform**
Windows 11 Home

**Log Files**

[Log202309_004.zip](https://github.com/rmcrackan/Libation/files/12709942/Log202309_004.zip)

**Comment by CMuser28** [comment]
I apparently had 0 storage space on my computer oops!

**Comment by wtanksleyjr** [comment]
I absolutely have done that before.
