### ISSUE TITLE
Characters replacement

### ISSUE THREAD

**Issue by dbecerravela** [rmcrackan/Libation#776]
**Describe the bug**
Problem with text replacement. Does not generate the files.

**To Reproduce**

1. Go to 'Settings'
2. Click on 'Setting'
3. Go to 'Download/Decrypt' tab.
4. Click on 'Edit how filename characters are replace'
5. Set this configuration:
![image](https://github.com/rmcrackan/Libation/assets/97953249/ed442c8a-a755-4bac-994a-07685d8e59e6)

**Expected behavior**
Replace the characters properly in the folder and filenames.

**Platform**
Linux Mint 21.2 Cinnamon

**Log Files**
[_Log202309.log](https://github.com/rmcrackan/Libation/files/12847617/_Log202309.log)
[_Log202309.zip](https://github.com/rmcrackan/Libation/files/12847618/_Log202309.zip)

**Comment by Mbucari** [comment]
@dbecerravela I don't understand your problem. Are your audiobooks still downloading, but the folder/file names still contain those "characters to replace"?

**Comment by wieland-s** [comment]
@dbecerravela I installed Libation today and have the same issue. 
@Mbucari exactly! 

I've tried several replacement-characters, does not work. 

<img width="500" alt="image" src="https://github.com/user-attachments/assets/41a6a6fe-5812-41fa-a601-d11d7fdcda7a">
<img width="500" alt="image" src="https://github.com/user-attachments/assets/96be4e4c-f2fc-4944-925b-e422ee9a9cd2">

**Comment by rmcrackan** [comment]
If you're having trouble with character replacements, I recommend using completely safe characters like `_` until you can pin-point the one giving you issues.
