### ISSUE TITLE
Autoscan Selected Account(s)

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#778]
**Is your feature request related to a problem? Please describe.**
Enabling autoscan has it scan all accounts. I really only have new books on one account. So having it scan all four accounts doesn't make sense. 
*
**Describe the solution you'd like**
Add an option for Autoscan to only scan selected accounts. 

**Describe alternatives you've considered**
I now do it manually, but I'd really like it to autoscan my active account on startup. 

**Additional context**

**Comment by rmcrackan** [comment]
Go to settings > Accounts and use the checkboxes.

To verify this: when a scan occurs (including auto scan), in the upper right of the main view it will say "Scanning" if only 1 account and "Scanning 4 accounts..." if 4 accounts.

**Comment by CharlieRussel** [comment]
Well, DUH. I should have known -- you almost always have it in there already. Thanks @rmcrackan!
