### ISSUE TITLE
Add locale BR - Brazil

### ISSUE THREAD

**Issue by maptan** [rmcrackan/Libation#782]
Audible is now available in Brazil. www.audible.com.br
Could you please add this locale to the options?

Thank you.

**Comment by rmcrackan** [comment]
[No problem](https://github.com/rmcrackan/Libation/releases/latest) :)

**Comment by mkb79** [comment]
@rmcrackan 
Login to Brazil marketplace is difficult using an external browser. At the end you will not get a `ap/maplanding` url. The browser will redirect the user to another page. So the user must search in the browser history, to find the needed url. [Here](https://github.com/mkb79/Audible/issues/194#issuecomment-1737683369) you can read about my findings.

**Comment by rmcrackan** [comment]
@mkb79 Thanks so much! I doubt I'll get to that anytime soon so I'll create a bug for later with this info.
