### ISSUE TITLE
More a question than an enhancement - file organization

### ISSUE THREAD

**Issue by landreaus** [rmcrackan/Libation#783]
I'd like to organize my downloads into different folders on my drive instead of them all being in the same folder. Reallly, all in the same folder but in sub folders. So I might have a subfolder for Paid and another for Free. And within each of those I might have Fiction and NonFiction. Will this confuse Libation and make it believe it still needs to download those files?

**Comment by rmcrackan** [comment]
short answer: no problem

long answer 1: contrary to what it resembles, Libation goal isn't to be an iTunes-like program. Its goal is to give you full control over your audio files, including if you want to move them. When you download a book, libation marks it as 'downloaded' and won't try to download it again. (You can even right-click a book in Libation and set this downloaded status yourself to prevent it from downloading a book or to make it download again.) Lots of users download their books then move them to external and/or cloud drives.

long answer 2: as long as you keep audible's unique id as part of the folder or file, then libation can potentially find the audio files again. This should happen automatically if it's within the 'books location' (from the first setting in Settings) folder or subfolders. There's also Import > locate audiobooks.

**Comment by landreaus** [comment]
Excellent. Thank you!
