### ISSUE TITLE
File download fails

### ISSUE THREAD

**Issue by chieftwidgit** [rmcrackan/Libation#79]
As far as I can tell Audible must have made some change.  The library scan works fine, but trying to download any book gives an error.  The log file gives the following:

2021-08-02 12:15:55.978 -04:00 [ERR] (at Dinah.Core.StepRunner.BaseStep.logEnd(System.Boolean, System.TimeSpan, System.Exception)) End step 'Step 1: Get Aaxc Metadata'. FAILED. Completed in 00:00:00
System.Net.WebException: The remote server returned an error: (403) Forbidden.
   at System.Net.HttpWebRequest.GetResponse()
   at AaxDecrypter.NetworkFileStream.BeginDownloading() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\AaxDecrypter\NetworkFileStream.cs:line 191
   at AaxDecrypter.AaxcDownloadConverter.Step1_GetMetadata() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Libation\AaxDecrypter\AaxcDownloadConverter.cs:line 116
   at Dinah.Core.StepRunner.BasicStep.RunRaw() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Dinah.Core\Dinah.Core\StepRunner\BasicStep.cs:line 10
   at Dinah.Core.StepRunner.BaseStep.Run() in C:\Dropbox\DinahsFolder\coding\_NET\Visual Studio 2019\Dinah.Core\Dinah.Core\StepRunner\Abstract_BaseStep.cs:line 22

Hope this helps.  I get the error regardless of version and on multiple systems.  An associate also reported this to me this morning.

**Comment by rmcrackan** [comment]
Thank you for letting me know and thank you very much for the log file. I will be unavailable for about two weeks but I will look into this when I return. Please post here if the issue changes or (hopefully) resolves itself.

Thanks again

**Comment by wtanksleyjr** [comment]
Just confirming same thing here, and this is with a slightly older version.

**Comment by docbha** [comment]
Yes even I am unable to downlaod too.
[Log202108_004.log](https://github.com/rmcrackan/Libation/files/6918945/Log202108_004.log)

**Comment by Mbucari** [comment]
This appears to be caused by an interruption in the Audible service. Here's the error message:

>403 ERROR
>The request could not be satisfied.
>Request blocked. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
>If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.

>Generated by cloudfront (CloudFront)

My Android Audible app is also unable to download at this time, so I'm pretty sure this is an Audible issue that they'll resolve soon.

**Comment by Mbucari** [comment]
EDIT: I actually am able to download on my Android app. I'm going to investigate this further to make sure it's not a Libation problem.

**Comment by docbha** [comment]
Yes still not working thanks for looking into this .

**Comment by mkb79** [comment]
Maybe [this](https://github.com/mkb79/audible-cli/issues/24#issuecomment-891753958) is the issue for the download problems. Have someone of you time for testing?

**Comment by Mbucari** [comment]
> Maybe [this](https://github.com/mkb79/audible-cli/issues/24#issuecomment-891753958) is the reason for the download problems. Have someone of you time for testing?
> 
> Edit:
> Found the real reason for the issue. The "User-Agent" have to be set correctly.

Are you sure that's the only reason? AudibleApi has been setting user agent ever since changing to the new download method, but it just stopped working yesterday.

**Comment by mkb79** [comment]
> > Maybe [this](https://github.com/mkb79/audible-cli/issues/24#issuecomment-891753958) is the reason for the download problems. Have someone of you time for testing?
> > Edit:
> > Found the real reason for the issue. The "User-Agent" have to be set correctly.
> 
> @mkb79 Are you sure that's the only reason? AudibleApi has been setting user agent ever since changing to the new download method, but it just stopped working yesterday.

@Mbucari I've changed this in my last version of `audible-cli` and I can download any audio book in aaxc format now!

**Comment by mkb79** [comment]
To be clear. Before I add the user agent, I had the same trouble downloading aaxc files with the same error message in file!

**Comment by Mbucari** [comment]
@mkb79 You were right. AudibleApi was using the following user-agent:
"Mozilla/5.0 (iPhone; CPU iPhone OS 12_3_1 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148"

Changing to the one in your repo fixed it.

**Comment by mkb79** [comment]
@Mbucari Great to hear that!

**Comment by Mbucari** [comment]
Fixed it here:
https://github.com/Mbucari/Libation/releases/tag/5.4.9

**Comment by rmcrackan** [comment]
Fixed here https://github.com/rmcrackan/Libation/releases/tag/v5.4.9

Thank you, thank you, thank you to @Mbucari  and @mkb79 !!!

**Comment by chr1xm** [comment]
Thank you so much!!! Working again just had to do a new setup and working again
