### ISSUE TITLE
Adding <series# 0> to the options when formating folder structure

### ISSUE THREAD

**Issue by gitcrook** [rmcrackan/Libation#790]
**Is your feature request related to a problem? Please describe.**
No real problem here, just a minor annoyance at worst.

**Describe the solution you'd like**
You have the option for <ch# 0> when formatting audio files split by chapters. I would just like the same for the folder structure since I have formatted my whole library as follows "authors's name\series name\ 01 book name\don't care naming the specific files". I have found this to be the most stable/ universal method of formatting since many audiobooks go past 10 books, they are named the same thing with a number before or after, or something their original structure don't allow for simple distinction of its order. 

**Describe alternatives you've considered**
Up to now I have just been using "0<series#>". Works the same if the series is below 10 books.

**Additional context**
Nothing to add, keep up the great work. Nothing beats this + audiobookshelf.

**Comment by CLHatch** [comment]
> **Is your feature request related to a problem? Please describe.** No real problem here, just a minor annoyance at worst.
> 
> **Describe the solution you'd like** You have the option for <ch# 0> when formatting audio files split by chapters. I would just like the same for the folder structure since I have formatted my whole library as follows "authors's name\series name\ 01 book name\don't care naming the specific files". I have found this to be the most stable/ universal method of formatting since many audiobooks go past 10 books, they are named the same thing with a number before or after, or something their original structure don't allow for simple distinction of its order.
> 
> **Describe alternatives you've considered** Up to now I have just been using "0<series#>". Works the same if the series is below 10 books.
> 
> **Additional context** Nothing to add, keep up the great work. Nothing beats this + audiobookshelf.

This is already possible.  You can do a LOT with the naming pattern.  This is mine:

`<if podcast->Podcasts\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<pub date>) - <series> - <title> [<id>]<-if podcast><!if podcast->AudioBooks\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<year>) - <title> [<id>]<-if podcast>`

This places the Podcasts in:

`Podcasts\Audible\Chris\Tim Lebbon; Dirk Maggs\Alien꞉ Out of the Shadows\01 - (2018-12-07) - Alien꞉ Out of the Shadows - Episode 9 [B08GC7FF93]`

And books in:

`AudioBooks\Audible\Chris\Rachel Higginson\Star-Crossed\06.5 - (2017) - Breathless Magic [B06X9DFVYL]`

**Comment by ex-nerd** [comment]
Thanks! Would be nice if that was in the help docs for the format.  Looks like just `<series#[00]>` also works.

**Comment by CLHatch** [comment]
> Thanks! Would be nice if that was in the help docs for the format. Looks like just `<series#[00]>` also works.

It does, but by adding the `.##` it also supports "decimal" book numbers, such as book "1.5" in a series.
