### ISSUE TITLE
Docker Documentation refers to "InProgress " which does not exist

### ISSUE THREAD

**Issue by MarcoMue** [rmcrackan/Libation#792]
**Describe the bug**
This Document https://github.com/rmcrackan/Libation/blob/master/Documentation/Docker.md#setup wants me to change
"Change InProgress to /tmp"
but the InProgress variable does not exist in the Settings.json

**Screenshots**
My Settings File:
[Settings.json](https://github.com/rmcrackan/Libation/files/13290164/Settings.json)

**Platform**
Docker

**Comment by patienttruth** [comment]
@MarcoMue, I noticed the same thing. I'm trying to set this up right now while my audio books are downloading.  Did you create the variable or just leave it out?

(Thank you @rmcrackan for this awesome piece of software!!!)

**Comment by patienttruth** [comment]
@MarcoMue If you select a location in Edit settings > Download/Decrypt > Temporary Files Location, it will populate the variable into the settings.json file. 

![image](https://github.com/rmcrackan/Libation/assets/105557996/36542d85-240c-4738-bfab-b3769bdd9876)

So, I'm sure you could just put it in following the format at the end of the file.

![image](https://github.com/rmcrackan/Libation/assets/105557996/844145d3-4ed7-423d-b172-4ad15e4cc78c)
