### ISSUE TITLE
Problem downloading Audible Plus audiobooks

### ISSUE THREAD

**Issue by jewangyu** [rmcrackan/Libation#794]
**Describe the bug**
I can't seem to download audible plus books. I have no issue downloading the books I've purchased. 

**To Reproduce**
1. Scan Library
2. Liberate
3. License Denied

**Expected behavior**
I expect the audible plus books to download like my other books. 

**Screenshots**
![Libation_UQDk4mxQPx](https://github.com/rmcrackan/Libation/assets/49538725/6aa1f6cf-547d-4032-aa8a-b0d99e15df85)

**Platform**
Windows 10

**Log Files**
11/26/2023 8:21 PM	Download & Decrypt Step, Begin: [1980000174] Dark Age
11/26/2023 8:21 PM	Download & Decrypt Step, Completed: [1980000174] Dark Age
11/26/2023 8:21 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1980000174] Dark Age

**Comment by MarcoMue** [comment]
I just tried the same Audiobook with Libation 11.1 and it worked.

**Comment by rmcrackan** [comment]
Fantastic! Thanks for the follow up
