### ISSUE TITLE
Access to the path 'C:\Program Files\libation\.;LibationFiles\Books' is denied.

### ISSUE THREAD

**Issue by isahbellah** [rmcrackan/Libation#795]
[_Log202311.zip](https://github.com/rmcrackan/Libation/files/13481772/_Log202311.zip)

**Comment by rmcrackan** [comment]
Sorry, Windows has gotten very picky about what it will allow to write in Program Files. There's likely nothing we can do about this. I recommend keeping Libation somewhere else.

**Comment by isahbellah** [comment]
I tried that and it got solved, but now I can't scan my library. It keeps asking me to login, even though I already logged in.

**Comment by rmcrackan** [comment]
Ouch -- that's not good. Let's delete the file that holds your login stuff and see if that helps.

Go to settings and click the button for 'open log folder'. In that folder is the file `AccountsSettings.json` -- this is what remembers your login tokens (think: browser cookies). Delete that file, close/re-open Libation, then try to log in again. Let me know if that fixes it.

**Comment by isahbellah** [comment]
oh, nevermind! I just reset my audible password and used a new one and that seemed to fix the issue lmao
thanks for the help, though!! :) I'll keep you posted in case I get any other problems.

**Comment by isahbellah** [comment]
Wow, I guess it is NOT my day today...
just tried to liberate one book and got this error
![image](https://github.com/rmcrackan/Libation/assets/76537931/cdeec0b9-658d-4fcc-be0d-74a8b7a70c3d)

**Comment by isahbellah** [comment]
Deleted the entire folder, downloaded libation again and redid every single step. seems to be working now!! :) just... I can't change any of the settings lol but it's okay, as long as I can download the books.
