### ISSUE TITLE
libation unexpectedly quit (over and over)

### ISSUE THREAD

**Issue by myexbff** [rmcrackan/Libation#799]
Hi.  got about halfway thru liberating my audible books yesterday and had to leave (so I turned off the computer) about halfway thru (480 gigs downloaded). Today when I restarted my laptop and libation, it attempts to pick up where the scan left off but immediately closes after the first book.  I've restarted both the app and my laptop several times.  Same error each time.

I've also cleared the queue of books waiting to download and restarted, but when I reopen the app it picks right up on my library and crashes again.  I've slicked to skip the first book on the list and it starts the second, then crashes.

Each time it presents the "Libation unexpected quit" error.  I attempted to paste the full error below but it exceeds the character limit. Attempting to attach a word doc.

I'm on a 2021 MacBook Pro 14 inch 64 gig with 8 tb HD.  Sonoma 14.1.1.  Appreciate any suggestions.

David
[libation error.docx](https://github.com/rmcrackan/Libation/files/13501534/libation.error.docx)

**Comment by rmcrackan** [comment]
Sorry this is happening. Can you attach your log file to this ticket? In settings there a button for 'open log folder'

**Comment by myexbff** [comment]
[_Log202311.zip](https://github.com/rmcrackan/Libation/files/13503527/_Log202311.zip)
here you go.  holler if you need anything at all.

**Comment by myexbff** [comment]
Decided to try something basic.  Deleted the app (left all the downloaded content in the folder).  Went to redownload.  Tried both Mac OS versions.  Neither will install. They both say "Cannot be opened because Apple cannot check for malicious software.  Contact the developer for more info."

Just a heads up in case others start contacting you.

David

**Comment by rmcrackan** [comment]
Thank you for the log. I'm seeing a simple 'license denied' for `B005GFQ5WQ` The Count of Monte Cristo. And a lot of very odd errors at the end. If you can get it running again I have some ideas to try. Until then though it's moot. If you're able to get Libation running again let me know and I'll bounce some ideas off of you.

Unfortunately the Mac person kinda dropped out of this project and I have no experience on Mac. We have [info here](https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md) including a video. Crossing my fingers that there something there to unblock you.

The way "the developer" is supposed to get around the malicious software thing is by paying Apple an annual ~~extortion~~ fee for which I have neither the money nor inclination.

**Comment by myexbff** [comment]
Thank you for looking at it. Sorry to have wasted your time.
David

**Comment by rmcrackan** [comment]
☹️  Sorry I don't know Mac. If you can figure out the Mac side of the permissions, I'll be happy to help work through the Libation and audible side of things with you.

**Comment by ifican** [comment]
Having the exact same problem on mac and basically the same as *800. My issue has been going on about 1 week now but strangely enough started on the same title as the author of this one. I have pause that title to let it try others and still no joy. You had some ideas, im happy to test those. Im not home right now so cant look at the logs to see if its the same error. 

A side question if i install Libation on a different host, can i point it at the same library location and have it know not to re-download the same titles?

**Comment by rmcrackan** [comment]
Like I said, unfortunately I'm not a mac person. You can try going back to [v11.1](https://github.com/rmcrackan/Libation/releases/tag/v11.1.0) and see if that helps.

You can definitely move Libation anywhere. I explicitly made it with no install or uninstall -- it's just files. To 'install' it, copy files. 'Uninstall'? Just delete the files.

There are 2 types of files: the files you download from me (which makes the app work), and the files Libation generates (which make it *your* library). There's nothing special about the first type of files, just download a fresh copy from [here](https://github.com/rmcrackan/Libation/releases). The 2nd type is what you'll copy.

In settings of the Libation already installed, click the 'open log folder' button. The folder this takes you to is your 'libation files'. Copy this folder to the new computer. On the very first launch on a new computer it asks if you're a new or returning user. Pick 'returning' and use the next box to point to the folder with your libation files.

**Comment by ifican** [comment]
good news for others with mac, 11.1 is working perfectly. Ill stick with it for now in hopes that future updates clear everything else up. Thanks for the suggestion and also clarifying the moving of files. Ill play with moving it to a linux distro soon.

**Comment by rmcrackan** [comment]
Would you mind trying the new v11.3 and see if it works for you?
