### ISSUE TITLE
Add South African Locale

### ISSUE THREAD

**Issue by RokumanZA** [rmcrackan/Libation#806]
**Is your feature request related to a problem? Please describe.**
Can't add my account as there is no South African Locale.

**Describe the solution you'd like**
Add South African Locale settings and option to Locale list.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by rmcrackan** [comment]
@RokumanZA Thanks for the heads up; this is the first I've heard of this locale. What's the main url for audible South Africa?

@mkb79 Are you aware of any of the settings needed for South Africa? [It looks like](https://github.com/mkb79/Audible/blob/master/src/audible/localization.py) you don't have it yet either.

**Comment by mkb79** [comment]
@RokumanZA @rmcrackan 

There are no Audible marketplace for South Africa. Take look [here](https://www.audible.com/ep/country-selector). It's not listed.

**Comment by rmcrackan** [comment]
@mkb79 Nice! I never knew about that page.

**Comment by RokumanZA** [comment]
Thank you for looking into this, thanks to this I found out that my account is actually in us Locale, which is surprising sincce they showed nothing about not having audible in ZA when I signed up years ago :) appreciate you guys looking into this!

**Comment by rmcrackan** [comment]
No worries. Glad the mystery is solved :)
