### ISSUE TITLE
fail to import library

### ISSUE THREAD

**Issue by cylindricpanda** [rmcrackan/Libation#811]
[_Log202312.zip](https://github.com/rmcrackan/Libation/files/13706878/_Log202312.zip)

**Comment by popey** [comment]
The log shows a timeout. If you try again, does it work? 
Did you have a poor network connection at the time?
Do you have a very large library of books? 

Perhaps try the option in Settings -> Settings -> Download/Decrypt -> "When liberating books and there is an error, Libation should:" "Retry book later. Skip for now. Continue processing books" ?

**Comment by cylindricpanda** [comment]
My library is not small but it's not humongous either. My two audiobooks did eventually show up, but none of my kindle books have. I did change that setting but when I retry to import the little progress text in the corner flashes but nothing starts importing. I don't get an error message or anything.

**Comment by rmcrackan** [comment]
Sorry, Libation only downloads audible audiobooks, not kindle
