### ISSUE TITLE
Trouble accessing audible account

### ISSUE THREAD

**Issue by BettyBookish** [rmcrackan/Libation#812]
**Describe the bug**
I previously downloaded most of my audible when I installed Libation a few weeks ago. I started getting errors at that time. I think because I used all the space in the 1TB external HD. I ordered a 2TB drive and wanted to download to that one, but now I can't get libation to work. When I go to settings I get an error when I click on Accounts. 

**To Reproduce**
Steps to reproduce the behavior: Go to settings click on accounts.

**Expected behavior**

**Screenshots**

**Platform**
Windows 11
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
[_Log202312.zip](https://github.com/rmcrackan/Libation/files/13767392/_Log202312.zip)

**Comment by rmcrackan** [comment]
Sorry you're getting errors.

Does your new external HD have the same drive letter as your old one?

Regarding accounts, it's possible it's a corrupt file. I've had that happen in the past and I don't have a good answer about why. When you go to the folder with your log file, there's the file `AccountsSettings.json` which allows libation to talk to your audible library. You can rename that file and restart Libation. Then in Libation go to accounts and set yours up again. On your next scan, Libation will guide you through a new login.

**Comment by BettyBookish** [comment]
Thank you so much! I appreciate the support!
