### ISSUE TITLE
Libation appears to download audiobooks, but files are not on machine

### ISSUE THREAD

**Issue by sicahjes** [rmcrackan/Libation#816]
**Describe the bug**
I have 22 books that are marked as 'Liberated' with a green traffic light icon. However, when I navigate to the storage folder the files are not there. I have also tried the following, without success:

- Right click on item in library and select 'locate file'. It takes me to the folder I checked above, but does not display the book. 
- Searched for book titles in Spotlight. No luck. 

These books were all set to download yesterday, however I only noticed the issue today when I went to organise the files. 

When I click on the file in the library, it takes me to the correct folder with a folder and audio files showing, but transparent. If I try to do this with other items in the library, this folder is replaced by the new book I click on. I need to individually change the name of these folders in order for them to save.

Note: Libation has saved all of these folders with a fullstops/period at the beginning, which may be part of the issue. This is because the books are not part of a series, so I'll change the nomenclature in the hope this prevents the issue from occurring again.

**To Reproduce**
This was spontaneous, no idea how to reproduced.

When I first noticed the issue today, I tried to download four more books. 

Book 1: resulted in a 'ghost file', like the above.
Book 2:  resulted in a 'ghost file', like the above.
Book 3: downloaded and could be located. 
Book 4: resulted in an error and has been set aside to retry later.
Book 5: downloaded and could be located. 

It seems to be ok now, but I thought I'd report the bug just in case others have experienced it. I did not do anything to fix this, the fix was also spontaneous.

**Expected behavior**
Items in library marked as 'Liberated' to be downloaded and locatable. 

**Platform**
Mac Ventura 13.6.1 

**Log Files**
Attached
[_Log202312.zip](https://github.com/rmcrackan/Libation/files/13802459/_Log202312.zip)
[_Log202401.zip](https://github.com/rmcrackan/Libation/files/13802462/_Log202401.zip)

**Comment by rmcrackan** [comment]
Thank you for all of these details. I'll take a look.

Since it's working though and we can't currently reliably reproduce it, I'm going to close the bug for now.
