### ISSUE TITLE
crashes on setting downloaded status

### ISSUE THREAD

**Issue by andirapandi** [rmcrackan/Libation#820]
**Describe the bug**
Didn't use the program for a few months. It has quite a large amount of books and a few accounts.
On recently added books, download and decrypt works after selecting "liberate"/begin. It crashes afterwards.
Trying to manually set to "downloaded" after the successfull decrypt (it crashed for many times so I assume it sill not recover), it also crashed. Also, updating (setting to downloaded) takes some time before the app crashes (vanishes). After restart, the book still is set to not downloaded.

**To Reproduce**

quickest: right click book in list, set to downloaded -> crash
same with liberate/begin (then after some time)
same with entering tags/details of book, and setting to downloaded, crashes after hitting ok and some seconds.

same behaviour with setting "not downloaded" on downloaded file

**Expected behavior**
set to downloaded, do not crash

**Screenshots**

**Platform**
win10 64, enough free disk + ram
**I used 11.2 and reverted to 11.1 also tried 11.3.1 (classic)**

**Log Files**
I set to verbose logging, nothing new in the log folder though!!

**Comment by rmcrackan** [comment]
Are you saying that none worked: 11.1, 11.2, or 11.3.1 ?

**Comment by andirapandi** [comment]
Yes.
Just downloaded VS2022 and latest code and get an exception in line 528 LibraryCommands.cs - StackOverflow.

`                foreach (var book in libraryBooks)
                {
                    context.Attach(book.Book.UserDefinedItem).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    context.Attach(book.Book.UserDefinedItem.Rating).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                }`

Actually I am not very familiar with EntityFramework. I am googling right now. Maybe this helps you?

**Comment by andirapandi** [comment]
I managed to get EntityFramework to log.
There is just one book in libraryBooks - since I am setting a single item to "not downloaded" (in my test now).
I get an endless output from EF before the stackoverflow. Also again I know little about EF, it certainly seems wrong that this uses internal recursive calls - and seems to effet the whole dataset.
This is only a small part of the output - for a single book context.Attach.
How can it track so much?

> Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2588, CategoryLadderId: 762}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2588, CategoryLadderId: 770}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2588, CategoryLadderId: 927}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'CategoryLadder' entity with key '{CategoryLadderId: 927}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2591, CategoryLadderId: 927}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'Book' entity with key '{BookId: 2591}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2591, CategoryLadderId: 732}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'CategoryLadder' entity with key '{CategoryLadderId: 732}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2569, CategoryLadderId: 732}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2571, CategoryLadderId: 732}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'Book' entity with key '{BookId: 2571}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2571, CategoryLadderId: 844}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2571, CategoryLadderId: 865}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'CategoryLadder' entity with key '{CategoryLadderId: 865}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2567, CategoryLadderId: 865}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'Book' entity with key '{BookId: 2567}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'BookCategory' entity with key '{BookId: 2567, CategoryLadderId: 920}'.
Microsoft.EntityFrameworkCore.ChangeTracking: Debug: Context 'LibationContext' started tracking 'CategoryLadder' entity with key '{CategoryLadderId: 920}'.

**Comment by andirapandi** [comment]
Again, I know little of EF..

it seems like there are insane tracking-cascades.

I have a reasonable amount of books in there as well.

With this here, it does not crash, though.. it certainly seems like something else completely is wrong.

`                using var context = DbContexts.GetContext();

                var attached = new List<Book>();

                // Attach() NoTracking entities before SaveChanges()
                foreach (var book in libraryBooks)
                {
                    var stateBefore = context.Entry(book.Book.UserDefinedItem).State;
                    // Log this state or inspect it in the debugger
                    //var item = context.Books.AsNoTracking().FirstOrDefault(x => x.UserDefinedItem. == id);
                    var _book = BookQueries.GetBook_Flat_NoTracking(context, book.Book.AudibleProductId);
                    action?.Invoke(_book.UserDefinedItem);
                    context.Attach(_book.UserDefinedItem).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    attached.Add(_book);

                    //context.Attach(book.Book.UserDefinedItem).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                    //context.Attach(book.Book.UserDefinedItem.Rating).State = Microsoft.EntityFrameworkCore.EntityState.Modified;
                }

                var qtyChanges = context.SaveChanges();
                if (qtyChanges > 0)
                    BookUserDefinedItemCommitted?.Invoke(null, libraryBooks);

                attached.ForEach(b => context.Entry(b.UserDefinedItem).State = EntityState.Detached);
`

I just chatted up this "solution".

Perhaps I have hit a point where a totally unoptimized (wrong?) DB access is hitting a limit? Updating 1 book should not result in such a cascade of changetrackings?

I could provide the EF debugging/tracing code if you need that. I had to google/chat all of it too. I even have some logic to turn the logging on and off during runtime. Yeah, so clever.

**Comment by rmcrackan** [comment]
This is wacky. Something is definitely caught in a spiral. Those trackers shouldn't keep trying to track the same 2 entities over and over. There's something very wrong here. And by the way: great debugging so far. You know the directory with your logs and db file et al.? I'd back that up, delete the db and search engine dir, do a fresh scan from audible, then try changing the download status. If it works, then we know it's something wrong with your old database and I can help you apply any changes you want from your old db to your new db. If it doesn't work, then we've found an exceptionally strange bug that has never come up for any other user.

**Comment by andirapandi** [comment]
It's not the same 2 entities. I assume it marks all entities for change. I also assumes that nothing is wrong with the DB but with the EF structure. (But see later..)
Also, are you **missing unhandled exception handlers** to at least log the error before exiting? Not certain about SO exception (as well as out of memory) though becuase they could seriously break the program structure. Still, they most likely should still get logged.

As for recreating DB:
I deleted SerarchEngine dir as well as LibationContext.db.
I used 11.3.11 - and had 0 audioooks as expected.
I scan all. Takes a few secs. :) Ttoal processed and new are not equal.
Order seems to be same as before.
**Hmm.. strangely, setting to "downloaded" works. It does take a sec though which seems long.**

**So it seems like the DB was actually broken in my case.. and also it could be recreated.**

I could even set all to "downloaded" using the "Visible Books" menu option in the WinForms app.

So I assume all is good and well again.

Thanks for the terrific app too! It greatly improves my hearing experience next to some good podcasts. And the audible offers are insanely good, with all the knowledge available there.

**Comment by psychowood** [comment]
This is happening to me too, came here to post the same issue.

If I'm not wrong. it all started when I had to kill an instance (bad idea) of Libation UI, because it was kind of stuck. Since that moment, when updating the status of a book (either from liberating it or by just setting it manually from the UI, it crashes, so it somehow looks connected with some sort of DB corruption.

Here is the log from just running and setting a book as downloaded (both Verbose and Debug show the same logs), cleaned from personal data:

```
2024-01-07 12:56:16.889 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) 

 {}2024-01-07 12:56:17.264 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Microsoft.EntityFrameworkCore.Relational.resources, Version=7.0.12.0, Culture=en-GB, PublicKeyToken=xxx
 {}2024-01-07 12:56:17.277 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Microsoft.EntityFrameworkCore.Relational.resources, Version=7.0.12.0, Culture=en, PublicKeyToken=xxx
 {}2024-01-07 12:57:13.344 +01:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"Libation","Version":"11.1.0.1","ReleaseIdentifier":"WindowsClassic","OS":"Windows","InteropFunctionsType":"WindowsConfigApp.WinInterop","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":true,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":false,"LibationFiles":"C:\\Users\\me\\Libation","BooksDirectory":"\\\\?\\UNC\\truenas\\audiobooks","InProgress":"C:\\Users\\me\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDirectory":"\\\\?\\C:\\Users\\me\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":2,"DecryptInProgressDirectory":"\\\\?\\C:\\Users\\me\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
 {}2024-01-07 12:57:13.406 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module System.Windows.Forms.resources, Version=7.0.0.0, Culture=en-GB, PublicKeyToken=yyy
 {}2024-01-07 12:57:13.418 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module System.Windows.Forms.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=yyy
 {}2024-01-07 12:57:13.459 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Libation.resources, Version=1.0.0.0, Culture=en-GB, PublicKeyToken=null
 {}2024-01-07 12:57:13.472 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Libation.resources, Version=1.0.0.0, Culture=en, PublicKeyToken=null
 {}2024-01-07 12:58:20.043 +01:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":21429,"booksFullyBackedUp":18960,"booksDownloadedOnly":1,"booksNoProgress":2467,"booksError":0,"booksUnavailable":1}
 {}2024-01-07 12:58:20.069 +01:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":288,"pdfsDownloaded":268,"pdfsNotDownloaded":18,"pdfsUnavailable":2}
 {}
```

If I delete the Context DB, is there a way to make it set the status to "downloaded" without doing it manually, perhaps just checking for the existence of a specific folder/file?

**Comment by andirapandi** [comment]
You can set all visible to downloaded at once - that is what I did.

**Comment by rmcrackan** [comment]
Sounds like the issue here was a corrupt database. Don't get me wrong -- it's still my fault and I'm not passing the blame to someone else. But I'm not sure what to do about it so I'm going to close this ticket.

I have something to (supposedly) catch unhandled exceptions which I'll look into. You're right though that SO, out of memory, and disk full errors are exceptional cases for logging. I actually have another logging bug right now so I'll think about those together in that ticket.

Thank you for your great debugging on this one.

Also thanks for replying to @psychowood . I was in the process of typing this and was about to answer them next and I saw your reply pop up :)

**Comment by andirapandi** [comment]
BTW, I had disk full several times, though the last time was well before the issue arose.

Thanks again!
