### ISSUE TITLE
Respect xdg directory specifiction

### ISSUE THREAD

**Issue by nadir-ishiguro** [rmcrackan/Libation#821]
This is a wonderful application. Thank you very much!

I'm also very grateful that you support Linux. The one issue I have is that Libation creates its own "Libation" directory in the home directory even if the library is located somewhere else.

The typical and I think ideal solution is to divide media and config files according to the xdg standard. So config files would go into `~/.config/libation` while the library can be located wherever the user wants, just like now.

**Comment by madsamjp** [comment]
I would LOVE to be able to use this app! However, I can't tolerate additional directories added to my home directory (I keep a very minimal and tidy home folder). I've never understood why developers like to clutter people's home directories with config files. If there's a work-around, please let me know!

**Comment by wtanksleyjr** [comment]
That would be a good feature for the Debian installer. For now, the fix is to edit `/usr/lib/libation/appsettings.json` - or wherever it is, you'll find by running `which libation`, and that'll be a link to wherever Libation (the executable and its dlls, and the appsettings.json file) is.

**Comment by rmcrackan** [comment]
Thank you @wtanksleyjr !! I came back from vacation to a million emails and it's really helpful when others can help out like this. I really appreciate it.
