### ISSUE TITLE
Libation no longer syncs with my library, and keeps crashing

### ISSUE THREAD

**Issue by reader234** [rmcrackan/Libation#823]
Hello,

I haven't used Libation since November. When I try to sync (import) my library, it shows that it scans, but nothing is added.

I've re-installed Libation as well as deleted and re-added my account info. Now, Libation keeps crashing.

I'm on a Macbook Pro M1Max, MacOS Monterey, Libation 11.1.0.1. 

I appreciate your help; thank you!

**Log Files**

[Libation Crash Report 24-1-10.zip](https://github.com/rmcrackan/Libation/files/13893713/Libation.Crash.Report.24-1-10.zip)

**Comment by rmcrackan** [comment]
Sorry about this. Unfortunately that zip doesn't contain anything I recognize. If Libation starts up at all, please go to settings and click the button which opens the log folder. That folder should have a log zip.

**Comment by reader234** [comment]
Thanks for your quick reply. Here is the log file that I found.

[_Log202401.zip](https://github.com/rmcrackan/Libation/files/13897686/_Log202401.zip)

Thank you.

**Comment by rmcrackan** [comment]
Much thanks for the file. This log looks to me like your scan was successful. When did it crash?

**Comment by reader234** [comment]
It crashed soon after the scan. I just tried syncing again. It synced but no new books/podcasts were downloaded. It hasn't crashed since the last time, but still unsuccessful in syncing.

Thanks!

**Comment by reader234** [comment]
Is there a limit to how many books Libation can download and keep? Do I need to remove some of the backed-up books?

**Comment by reader234** [comment]
I think I figured it out. I did not have the correct settings for Podcasts. It is downloading now. Thank you so much for your help and quick responses!

**Comment by rmcrackan** [comment]
Glad you figured it out :)

> Is there a limit to how many books Libation can download and keep? Do I need to remove some of the backed-up books?

In general: no. Technically you may have trouble around 10,000. I have 1,300 titles. A few users have at least 6k. Years ago a user with 10k+ had issues; I honestly don't recall the solution.
