### ISSUE TITLE
Repeated error when importing library

### ISSUE THREAD

**Issue by extuary** [rmcrackan/Libation#824]
**Describe the bug**
I have Libation set to auto-scan, and I do see the <scanning...> message in the top right right when I first open the program, but that scan isn't picking up any recent additions to my Audible library. When I manually selected Import -> Scan Library, though, I immediately get an error. I've tried ~10 times, including after closing and re-opening Libation.

**To Reproduce**
I'm using version 11.2.0.1. (is that version deprecated? is that the problem? I don't see it in the Releases anymore.)
Import -> Scan Library

**Expected behavior**
A scan

**Screenshots**
![Capture](https://github.com/rmcrackan/Libation/assets/156373900/07648feb-d936-442b-ae26-7a825cc924d9)
^ That's what the error message looks like.

**Platform**
Windows 10

**Log Files**
Sorry, I'm not totally sure which files are needed -- esp. since the `Log202401` file appears to be empty. 
Here are all of the files named 'log' from my libation folder. I can grab a diff file, if what you need isn't in there.
[AllLogs01-11-2024.zip](https://github.com/rmcrackan/Libation/files/13908806/AllLogs01-11-2024.zip)

**Comment by rmcrackan** [comment]
Wow, thank you for all of those files. Yeah, I totally borked something up with 11.2. For now I recommend [v11.1](https://github.com/rmcrackan/Libation/releases/tag/v11.1.0) and I hope to have another attempt available soon. Sorry about this.

I'm going to close this ticket with the assumption that this is part of my 11.2 f-up. If you need help with 11.1, you can reply here and I'll still get the notification.

Sorry again.

**Comment by extuary** [comment]
Thanks for your help! I'll update you, if the problem persists.

**Comment by extuary** [comment]
Yeah, totally!

Just downloaded. I received the same error on the first attempt to manually scan, but the second attempt worked normally. 

Further testing has been... confusing. At first, it seemed like I was getting that error maybe 1 time in 4. Then I closed and re-started Libation, and since then, I got the same error every time for ~12 attempts over 4-5 minutes. And now it's working again, for the most recent 3 attempts. (At this point, my library is correctly synced and I've been asking Libation to query Amazon over-and-over for minutes. Idk if that's causing issues; just thought I'd mention it.)

[Here's](https://github.com/rmcrackan/Libation/files/13921632/Log202401_002.zip) the log file with today's date.


On my end, my present difficulty is solved since my library has now re-synced. So, thanks!
I'm happy to do other testing, if that would be helpful.

**Comment by rmcrackan** [comment]
Thanks for the follow up and for the new log

`The request failed due to an underlying issue such as network connectivity, DNS failure, server certificate validation or timeout.`

This could mean lots of stuff. I'm guessing you're not having actual network issues or you'd notice it much more in your other day to day stuff. The other things here are also bullshit low effort troubleshooting stuff which are unlikely. In any case though, especially since it's intermittent, this is the kind of bug which we could put a ton of time into for little reward, so I'm happy to leave this alone if you are. Although I greatly appreciate your offer to help.
