### ISSUE TITLE
Captcha Not working

### ISSUE THREAD

**Issue by Grinim** [rmcrackan/Libation#83]
Version : 5.4.9
US Audible Account, using Username Not email

Hello,

  There appears to be an issue with the captcha login.  When I attempt to load my library it request my password, then moves to requesting a CAPTCHA.  It doesn't matter what I  give as a responds it fails.  Have tried multiple times and the result is the same each time.

Tried everything I can think of, and don't believe its a 'me' issue.

[Log202108_001.log](https://github.com/rmcrackan/Libation/files/6932677/Log202108_001.log)

**Comment by Grinim** [comment]
Just to add, account is setup as US, My account is from before amazon took over. But if I choose Pre-Amazon I get 404 error.

**Comment by rmcrackan** [comment]
It’s not just you. I’ve yet to figure out why it works for most then not work for a few people. I’m out of town but the captcha bug is on my (s)hit list when I return.

**Comment by rmcrackan** [comment]
Ps. Thanks for the logs!

**Comment by dfuk** [comment]
Also cant get the captcha to work

[Log202108.log](https://github.com/rmcrackan/Libation/files/6933030/Log202108.log)

**Comment by Grinim** [comment]
Not sure if it will provide any new info, But I'm attaching a log file from a 2nd machine, having the same issues

[_Log202108.log](https://github.com/rmcrackan/Libation/files/6934885/_Log202108.log)

**Comment by rmcrackan** [comment]
Could you set logging to Verbose and try again? Please zip and attach the new logs and tmp pages

**Comment by Grinim** [comment]
[grinimLibationLogs.zip](https://github.com/rmcrackan/Libation/files/7010604/grinimLibationLogs.zip)

Here you go, This is with the settings for Pre-amazon and using just a user name

**Comment by Grinim** [comment]
[grinimLibationLogPreamazon.zip](https://github.com/rmcrackan/Libation/files/7010701/grinimLibationLogPreamazon.zip)
I made a mistake on the previous log files, they are US account in settings. the one attached here is set to pre-amazon and give a 404 error

**Comment by Mbucari** [comment]
> 
> 
> [grinimLibationLogPreamazon.zip](https://github.com/rmcrackan/Libation/files/7010701/grinimLibationLogPreamazon.zip)
> I made a mistake on the previous log files, they are US account in settings. the one attached here is set to pre-amazon and give a 404 error

It looks like you are being prompted to reset your password. If you go to Audible.com, are you able to log in?

**Comment by Grinim** [comment]
Yep, Logged in without issue, only thing it did was I logged in the first time, then it made me log in again with a captcha. This is the normal procedure I face with a different computer.

**Comment by Grinim** [comment]
Just for the record, When I go to audible.com, I press log in with username. I don't log in using a email as I am still on the old system.

**Comment by rmcrackan** [comment]
Were you ever able to complete the login? Or are you still stuck?

I only recently realized that I still have work to do on the username/pre-amazon login stuff. I'm so angry with amazon/audible for making us reverse engineer their whole damned process instead of just giving us a basic api

**Comment by Grinim** [comment]
Afrim, I can log in no problem,

**Comment by rmcrackan** [comment]
@Grinim : Since you're able to log in I'm going to close this issue. Mbucari and I have a side conversation about the login stuff, incl username logins, which is its own headache

**Comment by Grinim** [comment]
Okay, Just to be clear. I can log in to the website not the app.  But I understand the issue is bigger then me and wait patiently for a full fix.

**Comment by rmcrackan** [comment]
> I can log in to the website not the app

Whoops! I misunderstood. I'll reopen this.

**Comment by Mbucari** [comment]
Looking at https://github.com/rmcrackan/AudibleApi and https://github.com/mkb79/Audible, looks they are building logings differently.

For OAuth parameters, Audible uses "pageId"="amzn_audible_ios" for both amazon and audible acounts, but mkb79 uses "pageId"="amzn_audible_ios_privatepool" for audible logins.
Audible uses "openid.assoc_handle" = "amzn_audible_ios_[CountryCode]" for both, but mkb79 uses "openid.assoc_handle" = "amzn_audible_ios_lap_ [CountryCode]" for audible logins.
AudibleApi uses a constant "openid.oa2.client_id" instead of generating one from the device ID.

The last difference I noticed is that Libation's "pre-amazon" locale is only for the US, but mkb79 claims it was also used in Germany and the UK.

**Comment by Mbucari** [comment]
> [grinimLibationLogPreamazon.zip](https://github.com/rmcrackan/Libation/files/7010701/grinimLibationLogPreamazon.zip)
> I made a mistake on the previous log files, they are US account in settings. the one attached here is set to pre-amazon and give a 404 error

Best on the log files, my patient is trying to log in using the 
https://www.amazon.com/ap/signin endpoint. For pre-Amazon Audible accounts, it should be using https://www.audible.com/ap/signin

**Comment by KnechtNoobrecht** [comment]
I am using 5.5.0 and i can't log in too.
Amazon/Audbile web login works perfectly fine for me.
I am prompted to enter a 2FA code but i don't receive one.

**Comment by rmcrackan** [comment]
Can you attach your log?

> I am prompted to enter a 2FA code but i don't receive one.

Did you get an error? Or no error but also no code sent?

**Comment by KnechtNoobrecht** [comment]
> 
> 
> Can you attach your log?
> 
> > I am prompted to enter a 2FA code but i don't receive one.
> 
> Did you get an error? Or no error but also no code sent?

No error, no code from Amazon.
[Log202108.log](https://github.com/rmcrackan/Libation/files/7022650/Log202108.log)
Here you go.
I disabled 2FA and was able to login, just to let you know.

**Comment by rmcrackan** [comment]
> I disabled 2FA and was able to login, just to let you know.

Good idea. Glad you were able to work around it for now. I'll look into this

**Comment by Grinim** [comment]
I downloaded and tried the new version 5.5.2, I am now able to get the books to populate.  However when downloading a book I get an error saying it couldn't be processed, But the files appear in the directory and appear so far to work fine.

[https://ibb.co/rMKXq2n](url)
[https://ibb.co/ZKV44pJ](url)

**Comment by rmcrackan** [comment]
@Grinim That definitely should not happen. Can you please attach your log file? I'll take a look

**Comment by rmcrackan** [comment]
@Grinim found the bug. New fixed version coming very soon. Sorry!

**Comment by Grinim** [comment]
All good, Thanks for the App and your efforts to fix issue.  I just downloaded the new version 5.5.3 and it worked perfectly.
