### ISSUE TITLE
Migration from Windows to Linux

### ISSUE THREAD

**Issue by dethorpe** [rmcrackan/Libation#830]
**Is your feature request related to a problem? Please describe.**
My storage is on an Ubuntu server, since there is a Linux version of Libation now I want to move the application there.

**Describe the solution you'd like**
Documentation or functionality in migration between platforms.

**Describe alternatives you've considered**
Doing it myself and seeing what breaks.

**Comment by rmcrackan** [comment]
You should be able to copy most the files from your main folder (the folder with logs, database, etc) from one place to another. Don't bother copying FileLocations.json -- the old one will be all windows paths. If you're feeling ambitious you could edit this yourself, but it's not a necessary file.

For Settings, I'd just a fresh install then edit this via the UI. If you really want to do it manually though: delete all the entries with "X" and "Y" -- those are remembering the window's previous location on your screen on your prev computer. The trickier part is the 3 paths: Books, InProgress and WriteTo.Args.path

**Comment by dethorpe** [comment]
Easy, thank you. I'd be happy to write a commit for the docs if you'd approve.

**Comment by wtanksleyjr** [comment]
This is also vital for Docker use - it's necessary to do all these
machine-specific changes in order to use Docker, since it's not possible
(to the best of my knowledge) to configure Docker using its own GUI, you
have to install on Windows and copy config/DB to the docker, editing first.

**Comment by rmcrackan** [comment]
@dethorpe Sure, much thanks!!

@wtanksleyjr Speaking of docker, I know nothing about it but something about the upgrade to .net8 broke the docker build step. So new versions are *no mas* unless someone who knows more than me wants to take a whack at it.

**Comment by wtanksleyjr** [comment]
Hmm, ironically enough (yeah I know that's not irony it's coincidence) I've
been Dockering around for a while. The hard part is the config files, I've
got the rest almost done by reading other people's Docker files. It
actually might work, but I'm a little busy tonight. I'll make a PR ASAP
even if I'm not sure it's perfect.

The main part, running the app, is preposterously simple. If I've got the
permissions right and someone does the work of setting the folders up it'll
just work. What I want to do is provide an install script that'll set
everything up once, and then you can just run and so on.

-Wm
