### ISSUE TITLE
Libation Crashes On Start Up

### ISSUE THREAD

**Issue by AnnieB82** [rmcrackan/Libation#836]
[_Log202401_001.zip](https://github.com/rmcrackan/Libation/files/14087481/_Log202401_001.zip)
[_Log202401_002.zip](https://github.com/rmcrackan/Libation/files/14087482/_Log202401_002.zip)
[_Log202401_003.zip](https://github.com/rmcrackan/Libation/files/14087483/_Log202401_003.zip)
[_Log202401_004.zip](https://github.com/rmcrackan/Libation/files/14087484/_Log202401_004.zip)
[_Log202401.zip](https://github.com/rmcrackan/Libation/files/14087485/_Log202401.zip)

**Comment by rmcrackan** [comment]
Sorry about this! Much thanks for the log files. It looks like the file holding your login tokens (think: like browser cookies) got corrupted. Go to the folder where these log files were, delete the file `AccountsSettings.json`, and restart Libation. You'll need to re-add your account and log in again then you should be good to go.

Sorry again.

**Comment by AnnieB82** [comment]
Great, thanks - I'll give it a try :)
