### ISSUE TITLE
5.4.9 not downloading books

### ISSUE THREAD

**Issue by docbha** [rmcrackan/Libation#84]
It was working fine but is giving an error now in downloading books.Please find attached the log
[Log202108_004.log](https://github.com/rmcrackan/Libation/files/6940276/Log202108_004.log)

**Comment by Mbucari** [comment]
Looks like you're being denied a download license for the following titles.

- Live and Let Grow
- Marriage of Inconvenience: Knitting in the City, Book 7
- Kissing Tolstoy: Dear Professor, Volume 1

These are all Audible Plus books, which makes me think you let your subscription lapse.

**Comment by docbha** [comment]
Actually my membership is still active for few days though I cancelled it to renew. I will check with my husband's account which is on active subscription and let you know. 
Thanks for looking into this.

**Comment by docbha** [comment]
Hi I checked and you are right it seems that even though my account is still active for another 10 days because i cancelled it to renew next month,  somehow i am not able to downlad books, even gave same error for my bought book once, tried again and it worked.

The same books work on my husband's account. I just had one query when I try and import same books from my husband's account into Libation, the books dont show up as they are already in Libation from my account though not downloaded. They still show after i have removed them from my audible library and after i deleted this account from libation seettings. is there a way to delete these non-downloaded books from Libation so they show up as new from my husband's account and i can download them.
Thanks

**Comment by Mbucari** [comment]
Right now there isn't a way to remove books once they've been imported, but that's a feature we're looking to add.

**Comment by docbha** [comment]
Thanks how do I delete the database

**Comment by rmcrackan** [comment]
The database file is LibationContext.db. Look in settings to see where to find it. Delete this and reimport your library. Then everything will be like it was except for the newly deleted books. As the person above said, a better feature for this is coming soon-ish

**Comment by docbha** [comment]
Thanks a lot
