### ISSUE TITLE
misspelling of a word

### ISSUE THREAD

**Issue by whocrazy** [rmcrackan/Libation#850]
Hi.
Collapse is spelled c o l l a p s e, not C o l l p a s e.  I first encountered this when downloading my audible podcasts, was not sure at first, it meant, until I clicked the button and then it said press to Expand.
Thanks, this is a fantastic program BTW.

**Comment by rmcrackan** [comment]
lol how long has that been there? Good find. [I just fixed it in my code.](https://github.com/rmcrackan/Libation/commit/5a86a1a27bad9a44c5d5dd745ef98e703c2bee57)

Now if I can ever figure out what's the deal with the new mystery bugs in version 11.3, I can finally release this fix to the world.
