### ISSUE TITLE
Can't access library

### ISSUE THREAD

**Issue by Ragtime001** [rmcrackan/Libation#857]
![audible lib issue](https://github.com/rmcrackan/Libation/assets/161757220/78019962-ee4f-4bf3-9438-e77b7c6f89b5)
The above jpg shows what the Library page looks like on my Win 11 Edge browser.  The pages showing only audiobooks, podcasts, or collections are populated normally.  I get the same results in another browser, and in private mode, both when cookies from earlier are present and when they've all been deleted and I've freshly signed in. (And I did call Audible and they just said to clear cookies). It's been like this a couple of days.

Here is the message I got when I tried to scan manually in Libation:
One or more errors occurred. (Collection contains Series with null SeriesName (Parameter 'items'))

   at ApplicationServices.LibraryCommands.scanAccountAsync(ApiExtended apiExtended, Account account, LibraryOptions libraryOptions, LogArchiver archiver) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 293
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 263
   at ApplicationServices.LibraryCommands.scanAccountsAsync(Func`2 apiExtendedfunc, Account[] accounts, LibraryOptions libraryOptions) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 265
   at ApplicationServices.LibraryCommands.ImportAccountAsync(Func`2 apiExtendedfunc, Account[] accounts) in D:\a\Libation\Libation\Source\ApplicationServices\LibraryCommands.cs:line 132
   at LibationWinForms.Form1.scanLibrariesAsync(Account[] accounts) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.ScanManual.cs:line 77

Log files are attached:
[_Log202402.zip](https://github.com/rmcrackan/Libation/files/14452061/_Log202402.zip)
[_Log202402_001.zip](https://github.com/rmcrackan/Libation/files/14452062/_Log202402_001.zip)

FYI, I can access the overall Library on my mobile phone, but I'm trying to use Libation to sort through the large amount of items I've got in the library.

Please advise and thanks for your work.

**Comment by rmcrackan** [comment]
Much thanks for the logs. Well that's certainly a new one: `Collection contains Series with null SeriesName`. Somewhere in your audible library is a series with no name. Thank you audible, that's super helpful /s

I'll work on a fix later today.

**Comment by rmcrackan** [comment]
I'm releasing this as a pre-release for now. It should fix your problem: https://github.com/rmcrackan/Libation/releases/tag/v11.3.5

**Comment by CLHatch** [comment]
> Much thanks for the logs. Well that's certainly a new one: `Collection contains Series with null SeriesName`. Somewhere in your audible library is a series with no name. Thank you audible, that's super helpful /s
> 
> I'll work on a fix later today.

I wonder if it's a case of a book that isn't in a series, and they accidentally put some whitespace in the "SeriesName" field?

**Comment by CLHatch** [comment]
Or maybe I'm misunderstanding.  Definitely an error on their end though. :-D

**Comment by rmcrackan** [comment]
> I wonder if it's a case of a book that isn't in a series, and they accidentally put some whitespace in the "SeriesName" field?

It's possible. Sometimes their metadata management is trash.

**Comment by CLHatch** [comment]
> > I wonder if it's a case of a book that isn't in a series, and they accidentally put some whitespace in the "SeriesName" field?
> 
> It's possible. Sometimes their metadata management is trash.

I see you have mastered the art of the understatement.

**Comment by Ragtime001** [comment]
Thanks for your quick response.
I don't remember having any trouble installing 11.1.0.1 but I am not clear how to update with the prelease.  I dl'd, unzipped, looked in the folder, and double clicked the zip extractor.  and a small pop up box says "installing update" and also "extracting..."

It that right or should I cancel?  

Pardon the ignorance.

**Comment by rmcrackan** [comment]
:) You're welcome

**Comment by Ragtime001** [comment]
I have an unverified theory as to what cause the bug, now that's I'm looking at the library.  I added one episode of a podcast to my library without adding the podcast overall.  Just a guess.
