### ISSUE TITLE
String '2016-02-29' was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by infomata** [rmcrackan/Libation#858]
Describe the bug
When attempting to scan the library after setting up the login information for the Audible account, the following error is encountered multiple times: "String '2016-02-29' was not recognized as a valid DateTime."

To Reproduce

Install the software for the first time.
Follow the directions up to the library scan part.
Set up the login information for the Audible account with the username and password.
Attempt to scan the library.
Encounter the error message mentioned above.
Expected behavior
The library should scan without any errors and display the audiobooks available in the Audible account.

Platform
Mac mini M2

Log Files
file attached here
It seems there might be an issue with parsing date information in the library scan process.
[_Log202403.zip](https://github.com/rmcrackan/Libation/files/14468561/_Log202403.zip)
![Screenshot 2024-03-02 at 3 17 18 PM](https://github.com/rmcrackan/Libation/assets/161927158/4416c457-8e5e-404d-883d-a27b2371f0a2)

**Comment by rmcrackan** [comment]
Thank you very much for the logs. I have no idea why that leap year isn't working on mac. I created this pre-release to address your issue. Let me know if it helps: https://github.com/rmcrackan/Libation/releases/tag/v11.3.6

**Comment by infomata** [comment]
Dear rmcrackan,

I wanted to extend my heartfelt thanks for your swift and adept assistance with Libation, which has significantly liberated my Audible library experience. Your approach not only solved my issue but also has the potential to benefit others in the community, reflecting the true spirit of open-source software.

I am inspired by your dedication and am sending a small donation as a token of my appreciation. Your work has added a valuable layer of freedom to my digital life, and for that, I am truly grateful.

Warmest regards,

infomata

**Comment by infomata** [comment]
I sent over $40 via Friends & Family with Paypal from a separate email some moments ago, thank you rmcrackan you are doing a great service to internet patrons that discover your software - i've already shared and helped some of my buddies through tutorials this past week to feature some of the freedom in their lives as well... thank you!

**Comment by rmcrackan** [comment]
Wow -- thank you *so* much for your kind words and very generous tip!

I've been the beneficiary of many, many, many (god I'm old) years of software, tutorials, and information on the web, all freely given. I told myself that if I ever had the chance to contribute, I'd try to live up to the same. In particular I was a young adult in those early days of corporations putting restrictive drm on all their content and hackers breaking it just as fast, then giving away the solutions to the rest of us.

Until the day that Lord Bezos inevitably slaps me with a 'cease and desist', I'm glad to do my small part for keeping information free and letting people own what they purchase.
