### ISSUE TITLE
Decrypt Failed - every book imported

### ISSUE THREAD

**Issue by cece-nz** [rmcrackan/Libation#866]
**Describe the bug**
All books being imported return the same error Download & Decrypt: Decrypt failed.

**To Reproduce**
Imported from library.

**Expected behavior**
Download to successfully be added to library

<img width="1192" alt="Screenshot 2024-03-15 at 12 49 13 PM" src="https://github.com/rmcrackan/Libation/assets/67735299/67c93101-3e92-4a0d-9db1-c2da616c0cb1">

**Platform**
Mac Sanoma 14.0
Libation Chardonnay v11.1.0.1

**Log Files**
15/03/2024 12:45PM	Download & Decrypt Step, Begin: [B0784XW7PM] Octonauts: The Monster Map and Other Stories
15/03/2024 12:45PM	Download & Decrypt Step, Completed: [B0784XW7PM] Octonauts: The Monster Map and Other Stories
15/03/2024 12:45PM	Download & Decrypt:  Decrypt failed
15/03/2024 12:45PM	ERROR. All books have not been processed. Most recent book: processing failed
15/03/2024 12:48PM	Download & Decrypt Step, Begin: [B017WOQT6A] Harry Potter and the Half-Blood Prince, Book 6
15/03/2024 12:48PM	Download & Decrypt Step, Completed: [B017WOQT6A] Harry Potter and the Half-Blood Prince, Book 6
15/03/2024 12:48PM	Download & Decrypt:  Decrypt failed
15/03/2024 12:48PM	ERROR. All books have not been processed. Most recent book: processing failed

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach your log file to this ticket? If you open Libation and go to Settings, there's a button for 'open log folder'

**Comment by cece-nz** [comment]
Cheers for your quick response!

Is this what you are after?
[_Log202403.zip](https://github.com/rmcrackan/Libation/files/14609434/_Log202403.zip)

I have also tried uninstalling and reinstalling with the same issues

**Comment by rmcrackan** [comment]
Perfect, thanks! I see errors relating to 'arm64'. Is it possible that you're using the arm64 version of Libation on a non-arm64 Mac? (Full disclosure: I'm not the Mac person so part of this is me grasping at straws.)

[Details are here](https://github.com/rmcrackan/Libation/blob/master/Documentation/InstallOnMac.md) but the tl;dr is that there are 2 versions of Libation for Mac depending on if you have Intel or the newer arm64: M1, M2, etc.

**Comment by cece-nz** [comment]
Ahhh the damn M1 chip saga strikes again!
I have uninstalled all relation to the old one followed the instructions you posted, which I didn't do originally (my bad).

It's no working perfectly. Thanks again for your quick and helpful response

I missed the details you posted and had gone straight to:
https://github.com/rmcrackan/Libation/releases/tag/v11.1.0

Would you like me to close this? Otherwise happy if you want to, as resolved

**Comment by rmcrackan** [comment]
WooHoo -- I'm so glad it's working for you. Thanks for following up :) Cheers!
