### ISSUE TITLE
Error Downloading/Processing Books

### ISSUE THREAD

**Issue by ysmorid** [rmcrackan/Libation#869]
**Describe the bug**
When clicking on a book to download, I get a popup saying error in processing book.  I'm given the option to abort, cancel, or ignore.
I've tried clicking them all and re-clicking on the title to download, with no luck.  They will not download.

**To Reproduce**
Click on the red traffic light to start a download of a book.
Error will immediately pop up

**Expected behavior**
The book should start to download

**Screenshots**
![Screenshot 2024-03-20 115909](https://github.com/rmcrackan/Libation/assets/6166756/c6d3ef64-94ee-4246-ab4a-36d5cbe80699)

**Platform**
Windows 11 Home

**Log Files**
Unable to access log files.  Says compressed folder is empty.

**Comment by rmcrackan** [comment]
Let's put this bug on hold in case it's related to the other one.

**Comment by rmcrackan** [comment]
Did the other ticket fix this problem as well?

**Comment by ysmorid** [comment]
It did! You were right that they were related.

**Comment by crfcontact** [comment]
Hello, Sorry did I miss something..I'm Still having same problem "an error occurred while processing....."   On Mac  Thanks!

**Comment by Nicholas-Aung** [comment]
Hello, I am having the same problem stilll What do I need to do?

**Comment by rmcrackan** [comment]
@Nicholas-Aung Please attach your latest log file?

**Comment by Nicholas-Aung** [comment]
![image](https://github.com/rmcrackan/Libation/assets/174967901/5cc7e21a-9e7e-49c7-bab0-6dd5127bf008)

**Comment by rmcrackan** [comment]
Thanks for the screenshot. If you go into your settings, in the lower right is a button which will open the folder to your log files. Please attach the latest log zip to this ticket. It will contain some other details which can help me diagnose this.

**Comment by Nicholas-Aung** [comment]
[_Log202407.zip](https://github.com/user-attachments/files/16136294/_Log202407.zip)

**Comment by rmcrackan** [comment]
Perfect -- thank you for the log.

I added one of the books to my library that failed for you ('The Observer Effect꞉ The Joseph Bridgeman Series, Book 3'). Then I ran the same version of Libation that you're using. I can't see your settings so I downloaded both m4b and mp3 just in case. They worked for me. There must be something specifically going on at your computer.

Some things to try:

* Your 'books location' (that is: the first box in settings, where your books are downloaded to) is set to drive F: -- if this is an external drive, maybe try an internal one and see if that gets us past this error.
* Maybe there's something in this book's database entry that went weird.
  * Right click the book
  * Remove from Library
  * Settings > Trash Bin
  * Check this book
  * Permanently Remove from Libation
  * Close Trash Bin
  * Do a new Libation scan. It will import this book as though for the first time
  * Try again to download

**Comment by MakD** [comment]
@rmcrackan i am also facing a similar issue where a particular book fails to download. i can download others without any issues. can you please check my logs
[_Log202409_001.zip](https://github.com/user-attachments/files/17174367/_Log202409_001.zip)

**Comment by rmcrackan** [comment]
@MakD Are you able to download it on the official app?

**Comment by MakD** [comment]
> @MakD Are you able to download it on the official app?

Oh damn. Just tested.  Cannot even on the official app.

**Comment by Hauk-Lykke** [comment]
I have the same issue. I tried downloading in the Android Audible app, which works. I tried following the recipe above, removing from Libation library and scanning to re-add. No luck. Here is my log.

[_Log202504.zip](https://github.com/user-attachments/files/19948419/_Log202504.zip)

**Comment by Hauk-Lykke** [comment]
Update: The issue appears to affect all of my longer audiobooks. Anything longer than about 36 hours gets errors.

**Comment by rmcrackan** [comment]
I just released v12.3 (with a bug, d'oh!) then 12.3.1 with the fix. See if it helps you
