### ISSUE TITLE
Can not log in to Audible account (edit: while on VPN)

### ISSUE THREAD

**Issue by ZeroNamesLeft** [rmcrackan/Libation#871]
**Describe the bug**
I can not log in to my Audible account. I tired my other account and it was the same issue. I get the prompts fill them out. Prompt goes away. I click "Scan Library" and I get prompted to enter my password again. I tried to use all methods of sign in available through Libation.

I deleted the Libation temp folder and tried to set up from scratch. Same issue.  

OS used

Windows 11

Libation Versions tired:
Libation.11.1.0-windows-chardonnay
Libation.11.3.5-windows-chardonnay
EDIT: Libation.11.3.6-windows-chardonnay

**Log Files**

[_Log202403.zip](https://github.com/rmcrackan/Libation/files/14792875/_Log202403.zip)

**Comment by ZeroNamesLeft** [comment]
Forgot to mention that I changed my Amazon account log in to require Two-Step Verification during the troubleshooting and the next time i tried to log in though Libation it did request the code. I took this to mean that the connection to amazon is working.

**Comment by ZeroNamesLeft** [comment]
Issue Resolved.

It was a VPN issue.

**Comment by rmcrackan** [comment]
Thanks for the update

fyi v11.3.5 and v11.3.6 *should* work, but they're marked as pre-release just in case. v11.1 the most reliable.

**Comment by ZeroNamesLeft** [comment]
i just tried Libation.11.3.5-windows-chardonnay and it does not work on VPN either.

**Comment by ZeroNamesLeft** [comment]
i just updated to 11.3.13 and Libation is accessing my audible account while on VPN. Problem might be fixed.

**Comment by rmcrackan** [comment]
Hooray! I took a gamble on some ipv4 vs ipv6 ~~fuckery~~ internal configuration in hopes that it might get around the issue. Thank you for following up to confirm.
