### ISSUE TITLE
Some titles unavailable 

### ISSUE THREAD

**Issue by Inkspit** [rmcrackan/Libation#872]
I downloaded all of my library - took a while and we had many hiccups along the way but I got there. however, I am left with 11 books that cannot be downloaded as they’re not available. Most of them are audible plus so I assumed they’re just not free anymore. But one of them is a book I paid for and no matter what I do it will not recognise. I haven’t done anything special just imported my libraries and other files downloaded around it. I had issues with older titles but weirdly this is now the only one that refuses to work. In order to get it to work before I restarted etc. but this didn’t help at all. The file is still available on audible so I’m confused. 

I’m using a MacBook on the most up to date iOS. 
I’m not sure how to find the log files sorry, I’m newer to coding and to this specifically.

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach your log file to this bug? I'll take a closer look.

**Comment by stickystyle** [comment]
I have the same issue, attached are my logs.
The book in question is "Mr. Hook-up: Hooked, Book 1"
[Log202405.log](https://github.com/rmcrackan/Libation/files/15355462/Log202405.log)

**Comment by rmcrackan** [comment]
@stickystyle The log looks like audible is actively blocking you from this title. When you look on the audible website or in your phone app, is this book there?

**Comment by stickystyle** [comment]
That's a good question. it was a book that came from my wife's account via the family sharing. When I go to it in my account (which is the one I'm using with libation), it shows as something I need to purchase, where other books shared like this show the option to start playing.
On her device it shows as purchased and allows her to play it.

**Comment by rmcrackan** [comment]
It sounds like this is a book from their 'plus' catalog which is free with an active subscription. These are not sharable with family plans like purchased books are. You likely added this to your audible library when you had an active subscription.

Libation has a 2-tiered deletion, like windows or mac recycle/trash can. You can right-click and delete the problem book and it won't bother you again, even when re-scanning.

You can also go into settings > trash bin and fully delete it. If you do this, it will appear again on re-scan if it's in your audible library. It doesn't sound like this is the case for you though.
