### ISSUE TITLE
Windows 11 - Can't get passed Windows Defender

### ISSUE THREAD

**Issue by MTinkerer** [rmcrackan/Libation#873]
Hi,

I've been trying to run Libation but am having all kinds of difficulties getting past windows defender.  I've created exceptions, moved to a different folder outside of program files, and everything else I can find on the internet to install it.  Still to no avail.  
Is there a thread you can't point me towards with specific instructions on getting past this step?
Or if I can provide further info, please let me know.

Thank you!

**Comment by CLHatch** [comment]
> Hi,
> 
> I've been trying to run Libation but am having all kinds of difficulties getting past windows defender. I've created exceptions, moved to a different folder outside of program files, and everything else I can find on the internet to install it. Still to no avail. Is there a thread you can't point me towards with specific instructions on getting past this step? Or if I can provide further info, please let me know.
> 
> Thank you!

I don't remember having to do anything with Windows Defender myself.  What exact errors are you getting from Windows Defender?  "Getting past Windows Defender" doesn't actually tell us what you're seeing.

**Comment by rmcrackan** [comment]
Can you post a screenshot of the issue you're having?

**Comment by wtanksleyjr** [comment]
1. Is it possible that you're trying to unzip the executable file into your
"Program Files" folder? If you're doing that, probably Windows Defender
will stop you. We recommend unzipping/copying the executables to a
different folder. I keep mine in C:\dev\Libation, for example.

2. Is it possible that your Windows is running in "S mode", where it will
only run apps from the Windows Store? Have you installed apps downloaded
from the Internet? See
https://support.microsoft.com/en-us/windows/switching-out-of-s-mode-in-windows-4f56d9be-99ec-6983-119f-031bfb28a307
for more info on that.

-Wm

**Comment by MTinkerer** [comment]
[image: image.png]

**Comment by MTinkerer** [comment]
Oh wait, I think I've got it figured out now.  Took a restart (?)
Sorry for the false alarm and thank you for the speedy response.

**Comment by rmcrackan** [comment]
@MTinkerer thanks for the update. I'm glad it's figured out

@CLHatch , @wtanksleyjr Thanks for stepping in. Y'all are fast :)
