### ISSUE TITLE
CUDA

### ISSUE THREAD

**Issue by x-FBi** [rmcrackan/Libation#877]
**Is your feature request related to a problem? Please describe.**
To speed up conversion time with ffmpeg

**Describe the solution you'd like**
added -hwaccel to ffmpeg

**Describe alternatives you've considered**
I wait a little bit longer. 
You could add a custom command line to ffmpeg, if there's other commands I'm missing for people to add custom commands.

**Comment by rmcrackan** [comment]
Thanks. Libation actually doesn't use ffmpeg anymore. It's great to discover other features in it though. It's such an incredibly rich app.
