### ISSUE TITLE
Redownload book using only docker client.

### ISSUE THREAD

**Issue by mattheys** [rmcrackan/Libation#881]
Sorry this isn't a bug or anything but my own fault, I just can't find anywhere else to ask the question.

I made a mistake with unionfs and have accidentally deleted 1 book from my libation folder, I thought libation might notice and redownload but it hasn't.

I'm just using the docker image and not the desktop app, how can I mark the title as needing to be redownloaded?

I'm a developer too and I don't mind running a sql command to update the database if needs be, just let me know which table and column and I can work that the update statement, or is it a case of just removing all the entries from the FileLocations.json file?

Thanks.

**Comment by mattheys** [comment]
Will this do it?

```sql
UPDATE UserDefinedItem
SET LastDownloaded = NULL, LastDownloadedVersion = NULL, BookStatus = 0
WHERE BookId = @BookId
```

**Comment by mattheys** [comment]
Decided to yolo it, backed up the config folder and my download folder.

Ran the above SQL and removed all entries in the FileLocations.json, then restarted the container. 

Redownloaded, phew :-)

**Comment by rmcrackan** [comment]
I've been out of town. I'm glad you found a way that works. If you accidentally delete a book from the Libation grid, you can go into Settings > Trash can to restore it. If you want to re-download an audio file, you can right click the book and select re-download.

**Comment by wtanksleyjr** [comment]
He's talking about the CLI, though - although the CLI offers an option to
download a specific AZIN, it doesn't work if the book's already been marked
downloaded, it prints a non-obvious error message.

-Wm
