### ISSUE TITLE
error importing library

### ISSUE THREAD

**Issue by alonglifestrail** [rmcrackan/Libation#882]
2024-04-20 20:09:36.504 -04:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) 

 {}2024-04-20 20:09:45.162 -04:00 [INF] (at AppScaffolding.LibationScaffolding.logStartupState(LibationFileManager.Configuration)) Begin. {"AppName":"Libation","Version":"11.1.0.1","ReleaseIdentifier":"WindowsClassic","OS":"Windows","InteropFunctionsType":"WindowsConfigApp.WinInterop","Mode":"Release","LogLevel_Verbose_Enabled":false,"LogLevel_Debug_Enabled":false,"LogLevel_Information_Enabled":true,"LogLevel_Warning_Enabled":true,"LogLevel_Error_Enabled":true,"LogLevel_Fatal_Enabled":true,"BetaOptIn":false,"UseCoverAsFolderIcon":false,"LibationFiles":"C:\\Users\\Nicole\\Libation","BooksDirectory":"\\\\?\\C:\\Users\\Nicole\\Libation\\Books","InProgress":"C:\\Users\\Nicole\\AppData\\Local\\Temp\\Libation","DownloadsInProgressDirectory":"\\\\?\\C:\\Users\\Nicole\\AppData\\Local\\Temp\\Libation\\DownloadsInProgress","DownloadsInProgressFiles":0,"DecryptInProgressDirectory":"\\\\?\\C:\\Users\\Nicole\\AppData\\Local\\Temp\\Libation\\DecryptInProgress","DecryptInProgressFiles":0}
 {}2024-04-20 20:09:50.580 -04:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Windows, Culture=neutral, PublicKeyToken=null, ContentType=WindowsRuntime
 {}2024-04-20 20:09:51.666 -04:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Microsoft.Windows.SDK.NET, Culture=neutral, PublicKeyToken=null
 {}2024-04-20 20:10:03.333 -04:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Libation.resources, Version=1.0.0.0, Culture=en-US, PublicKeyToken=null
 {}2024-04-20 20:10:03.479 -04:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module Libation.resources, Version=1.0.0.0, Culture=en, PublicKeyToken=null
 {}2024-04-20 20:10:22.851 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":2,"booksFullyBackedUp":2,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0,"booksUnavailable":0}
 {}2024-04-20 20:10:22.999 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2024-04-20 20:10:25.674 -04:00 [INF] (at AudibleUtilities.ApiExtended+<CreateAsync>d__7.MoveNext()) {"LoginType":"ILoginChoiceEager","Account":"AccountId=f[...]1@g[...]l.c[...]m|AccountName=f[...]1@g[...]l.c[...]s|Locale=us","LocaleName":"us"}
 {}2024-04-20 20:10:32.186 -04:00 [ERR] (at LibationWinForms.MessageBoxLib.ShowAdminAlert(System.ComponentModel.ISynchronizeInvoke, System.String, System.String, System.Exception)) Alert admin error: {"text":"Libation has encountered an unexpected error.","caption":"Unexpected error"}
System.InvalidOperationException: Invoke or BeginInvoke cannot be called on a control until the window handle has been created.
   at System.Windows.Forms.Control.MarshaledInvoke(Control caller, Delegate method, Object[] args, Boolean synchronous)
   at System.Windows.Forms.Control.Invoke(Delegate method, Object[] args)
   at System.Windows.Forms.Control.Invoke[T](Func`1 method)
   at LibationWinForms.Form1.exportMenuEnable(Object _, RunWorkerCompletedEventArgs e) in D:\a\Libation\Libation\Source\LibationWinForms\Form1.BackupCounts.cs:line 55
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
 {"ExceptionDetail":{"Type":"System.InvalidOperationException","HResult":-2146233079,"Message":"Invoke or BeginInvoke cannot be called on a control until the window handle has been created.","Source":"System.Windows.Forms","TargetSite":"System.Object MarshaledInvoke(System.Windows.Forms.Control, System.Delegate, System.Object[], Boolean)"}}2024-04-20 20:10:40.135 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":2,"booksFullyBackedUp":2,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0,"booksUnavailable":0}
 {}2024-04-20 20:10:40.167 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) PDF counts. {"total":0,"pdfsDownloaded":0,"pdfsNotDownloaded":0,"pdfsUnavailable":0}
 {}2024-04-20 20:10:45.893 -04:00 [INF] (at AppScaffolding.LibationScaffolding.getLatestRelease(System.TimeSpan)) Timed out
 {}2024-04-20 20:10:52.695 -04:00 [INF] (at ApplicationServices.LibraryCommands+<scanAccountAsync>d__18.MoveNext()) ImportLibraryAsync. {"Account":"AccountId=f[...]1@g[...]l.c[...]m|AccountName=f[...]1@g[...]l.c[...]s|Locale=us"}
 {}2024-04-20 20:10:54.735 -04:00 [INF] (at ApplicationServices.LibraryCommands.GetCounts(System.Collections.Generic.IEnumerable`1[[DataLayer.LibraryBook, DataLayer, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]])) Book counts. {"total":0,"booksFullyBackedUp":0,"booksDownloadedOnly":0,"booksNoProgress":0,"booksError":0,"booksUnavailable":0}
 {}

**Comment by alonglifestrail** [comment]
I'm not tech savvy at all but used libation fine 2 days ago. Now it wont import my new library books.

**Comment by rmcrackan** [comment]
Sorry about this. Can you attach the actual log zip file here?

**Comment by alonglifestrail** [comment]
I went back and tried a couple hours later and it worked fine. No idea what happened. Thanks anyway.
