### ISSUE TITLE
Libation has notified to me that "License Denied" with a couple of books

### ISSUE THREAD

**Issue by Hagakui90** [rmcrackan/Libation#887]
**Not download a couple of books and notify that  "License Denied"

**To Reproduce**

1. Go to Libation app. I am using version Chardonnay v11.1.0.1
2. Click expected book such as Just Add Magic Series, Book 1 with Audible ID: 1705205526
4. See error: License Denied 

**Expected behavior**
I am wondering what if I do not buy this book and this book is displayed Unavailable when I checked Audible website's Library, so Libation can not get this book. Could you explain this situation such as error with my account or Libation issue?

**Screenshots**
![2024-04-24 09_47_00-Window](https://github.com/rmcrackan/Libation/assets/109181861/11afb262-1e43-41fe-b1ef-732ad9b50b0a)
![2024-04-24 09_44_35-My Library _ Audible com](https://github.com/rmcrackan/Libation/assets/109181861/478eb077-0e4e-4ff2-a91d-212502bc5ca0)

**Platform**
Windows 10 Pro

**Log Files**
[_Log202404.zip](https://github.com/rmcrackan/Libation/files/15087108/_Log202404.zip)

**Comment by rmcrackan** [comment]
This appears to be a book that used to be part of the audible 'plus' catalog and no longer is. This is what your 2nd screenshot shows with the buttons for 'unavailable' and 'remove'. Sorry, Libation can only download books currently available in your library. However, if you download a 'plus' book (while it is available) and then audible later removes it from that catalog, then the book will still be available to you locally.
