### ISSUE TITLE
How do we use !IsLiberated en masse now?

### ISSUE THREAD

**Issue by Mulchman** [rmcrackan/Libation#89]
With previous versions I just used !IsLiberated to see new stuff. Now everything is showing as new.

How do I mark all 345 books as "downloaded"? It looks like the workflow is to now mark that an item is downloaded via the tags, but surely I don't have to individually mark all 349 books as downloaded?!

**Comment by Mulchman** [comment]
Huh, a couple "Scan Library"'s later and it's noticed that they're all downloaded and now !IsLiberated is working correctly...

**Comment by rmcrackan** [comment]
Weird. Glad it worked out. I was getting worried. I just changed a lot with that part and I was just typing out a "crap -- now what did I do" reply. Oh well. All's well that ends well
