### ISSUE TITLE
Mb4 from other sources?

### ISSUE THREAD

**Issue by wilderwests** [rmcrackan/Libation#890]
Hi, I have started using libation to backup my library. I wanted to back up my purchased titles from apple books.
I have the mb4 files but libation shows them as greyed out when I try processing them using "locate files". Is it just not possible to do back them up along with everything else? Thanks!

**Comment by CharlieRussel** [comment]
Libation is strictly for Audible books. The good news is, you can easily, if manually, add those m4b files to the same library structure as your Libation backup - just copy and paste. But no, you can't use Libation to backup Apple purchases. Only Audible purchases.

**Comment by rmcrackan** [comment]
@wilderwests What he said ^^^ 😄 

@CharlieRussel Much thanks for the assist. It's been a helluva day.

**Comment by CharlieRussel** [comment]
@rmcrackan - least I could do for what you’ve given us! 
And really sorry it’s been that kind of day!
