### ISSUE TITLE
Unable to login with legacy audible account

### ISSUE THREAD

**Issue by DizzyPilot** [rmcrackan/Libation#901]
I have a legacy audible account I never linked to amazon.  The only option I see is to login using my amazon account.  I've read the docs / faqs / searched issues for this and found nothing.  Instructions seem to indicate this is possible - maybe I'm a bonehead and can't figure it out.

I go to accounts, input my audible login , and I get the amazon signin without the option to switch to audible username.

If anyone can shed some light on this I would appreciate it!

**Comment by rmcrackan** [comment]
Sorry about this. In Settings > Accounts, there's a Locale column. Are you able to login if you select `pre-amazon - us` (or uk or germany)?

**Comment by DizzyPilot** [comment]
Yep that works, I somehow missed pre-amazon-us and only selected us.  I appreciate your help - sorry to bother you with this.

**Comment by rmcrackan** [comment]
No worries. I like easy fixes :)
