### ISSUE TITLE
Unable to open the Application on Mac

### ISSUE THREAD

**Issue by subratrout** [rmcrackan/Libation#902]
**Describe the bug**
Unable to open the app on Mac OS (Sonoma 14.4.1)

**To Reproduce**
Tried opening the app using various ways several times as below: 
1. double clicking the app.
2. Using both scripts as described on GitHub including Hangover.

**Expected behavior**
The app should be able to open.

**Platform**
Mac OS (Sonoma 14.4.1)

**Log Files**
Log file attached
[LibationCrash.log](https://github.com/rmcrackan/Libation/files/15283015/LibationCrash.log)

**Comment by rmcrackan** [comment]
Thank you for this log file. You might be able to fix this by changing your downloads directory from `/Users/subratrout/Downloads` to a folder inside of it. eg: `/Users/subratrout/Downloads/books`.

Something about our bit of code which scans for audible books in that folder is choking on the excessive number of files elsewhere in Downloads, specifically in `/Users/subratrout/Downloads/rails_projects/dslbd-toolkit-uat/node_modules`. I don't know why this should be the case but it should be resolved by using a different/deeper directory.

Please let me know whether this helps.

**Comment by subratrout** [comment]
It worked. Thank you.

**Comment by rmcrackan** [comment]
Awesome. Thanks for following up. Glad it's solved
