### ISSUE TITLE
libationcli: mark book as ignored

### ISSUE THREAD

**Issue by praeluceo** [rmcrackan/Libation#909]
**Is your feature request related to a problem? Please describe.**
libationcli lacks clear functionality for library management, which makes library management challenging.

**Describe the solution you'd like**
When a book is offered temporarily for instance, it can be added to your library, but after that book has "rotated out" it still shows up in your library as an unlicensed item, permanently unable to download without spending a credit to buy the book.

**Describe alternatives you've considered**
I attempted to use " libationcli set-status -d ASIN" however the book is still attempted on subsequent runs of "liberate".

**Additional context**
An example of the failure:
```
$ libationcli set-status -d B002UZJGYY
$ libationcli scan && libationcli liberate 
...
DownloadDecryptBook Begin: 9/13/2020 [B002UZJGYY] 2001: A Space Odyssey
Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
````

**Comment by CLHatch** [comment]
> **Is your feature request related to a problem? Please describe.** libationcli lacks clear functionality for library management, which makes library management challenging.
> 
> **Describe the solution you'd like** When a book is offered temporarily for instance, it can be added to your library, but after that book has "rotated out" it still shows up in your library as an unlicensed item, permanently unable to download without spending a credit to buy the book.
> 
> **Describe alternatives you've considered** I attempted to use " libationcli set-status -d ASIN" however the book is still attempted on subsequent runs of "liberate".
> 
> **Additional context** An example of the failure:
> 
> ```
> $ libationcli set-status -d B002UZJGYY
> $ libationcli scan && libationcli liberate 
> ...
> DownloadDecryptBook Begin: 9/13/2020 [B002UZJGYY] 2001: A Space Odyssey
> Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
> ```

It's not obvious, but the existing option for this you are looking for is "Remove from library".  It will place that book in the "Trash Can" where it will then be ignored.

**Comment by rmcrackan** [comment]
@praeluceo Sorry the management of 'plus' books is confusing. I'll take some blame: Libation could be more clear in how I manage this. To be frank though, I'm laying some blame on audible. It's really confusing to leave items in your library when they aren't yours anymore.

Thanks again @CLHatch for beating me to this one.

**Comment by CLHatch** [comment]
> @praeluceo Sorry the management of 'plus' books is confusing. I'll take some blame: Libation could be more clear in how I manage this. To be frank though, I'm laying some blame on audible. It's really confusing to leave items in your library when they aren't yours anymore.
> 
> Thanks again @CLHatch for beating me to this one.

Yeah, I place the blame mostly on Audible.  The only possible reason to have it "in your library" would be maybe to keep track of listening progress, and they could have done that in a way that it doesn't show as "in" your library still.

**Comment by CLHatch** [comment]
So, it appears that if a book is or was included in "Audible Plus", the start end end dates of it's inclusion is in the "plans" section in the json. Skyward is currently in the Audible Plus catalog until 5/29/2024, and I see this in the json:

```json
  "plans": [
    {
      "end_date": "2024-05-29T12:00:00Z",
      "plan_name": "US Minerva",
      "start_date": "2023-11-29T08:00:00Z"
    }
  ],
```

Not sure if that can be used to determine if a person owns rights to a book or not though, because what if they've purchased it since then?

**Comment by recklessnode** [comment]
> > **Is your feature request related to a problem? Please describe.** libationcli lacks clear functionality for library management, which makes library management challenging.
> > **Describe the solution you'd like** When a book is offered temporarily for instance, it can be added to your library, but after that book has "rotated out" it still shows up in your library as an unlicensed item, permanently unable to download without spending a credit to buy the book.
> > **Describe alternatives you've considered** I attempted to use " libationcli set-status -d ASIN" however the book is still attempted on subsequent runs of "liberate".
> > **Additional context** An example of the failure:
> > ```
> > $ libationcli set-status -d B002UZJGYY
> > $ libationcli scan && libationcli liberate 
> > ...
> > DownloadDecryptBook Begin: 9/13/2020 [B002UZJGYY] 2001: A Space Odyssey
> > Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
> > ```
> 
> It's not obvious, but the existing option for this you are looking for is "Remove from library". It will place that book in the "Trash Bin" where it will then be ignored.

Is there a "remove from library" parameter to libationcli or did you mean to remove from library on the Audible side? Thanks for the replies!

**Comment by CLHatch** [comment]
> > > **Is your feature request related to a problem? Please describe.** libationcli lacks clear functionality for library management, which makes library management challenging.
> > > **Describe the solution you'd like** When a book is offered temporarily for instance, it can be added to your library, but after that book has "rotated out" it still shows up in your library as an unlicensed item, permanently unable to download without spending a credit to buy the book.
> > > **Describe alternatives you've considered** I attempted to use " libationcli set-status -d ASIN" however the book is still attempted on subsequent runs of "liberate".
> > > **Additional context** An example of the failure:
> > > ```
> > > $ libationcli set-status -d B002UZJGYY
> > > $ libationcli scan && libationcli liberate 
> > > ...
> > > DownloadDecryptBook Begin: 9/13/2020 [B002UZJGYY] 2001: A Space Odyssey
> > > Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.
> > > ```
> > 
> > 
> > It's not obvious, but the existing option for this you are looking for is "Remove from library". It will place that book in the "Trash Bin" where it will then be ignored.
> 
> Is there a "remove from library" parameter to libationcli or did you mean to remove from library on the Audible side? Thanks for the replies!

It would be a command in Libation, yes.  But I'm not sure what the matching CLI command it, personally.  I use the Windows GUI version myself.
