### ISSUE TITLE
FeatureRequest: set m4b as default format for converted audiobooks

### ISSUE THREAD

**Issue by robster7674** [rmcrackan/Libation#913]
**Is your feature request related to a problem? Please describe.**
The option to convert downloaded audiobooks to m4b by default, is missing.

**Describe the solution you'd like**
Introduce a setting for choosing between mp3 and m4b formats as default option.

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by CLHatch** [comment]
> **Is your feature request related to a problem? Please describe.** The option to convert downloaded audiobooks to m4b by default, is missing.
> 
> **Describe the solution you'd like** Introduce a setting for choosing between mp3 and m4b formats as default option.
> 
> **Describe alternatives you've considered** n/a
> 
> **Additional context** n/a

Already there.  It's this option here, if it's checked, it will be `.mp3`, if it's unchecked, it will be `.m4b`.  I had mentioned at some point that that option should probably be moved to the top of the right hand side along with the other `.mp3` options to make it more obvious. All those options on the right hand side only apply if that checkbox is checked.
![image](https://github.com/rmcrackan/Libation/assets/13066223/7289deff-ab2d-47e6-83f1-ed42a6a790b7)

**Comment by rmcrackan** [comment]
Sorry for the confusion. @CLHatch is correct: lossless/m4b is currently the default.
