### ISSUE TITLE
Nothing happening after entering my password

### ISSUE THREAD

**Issue by Itsmeraymon** [rmcrackan/Libation#916]
**Describe the bug**
New user having downloaded Libation on Mac.

When I put in my Audible password nothing happens. I've tried the other way by opening in the browser and copying the URL but nothing happens.

**Expected behavior**
For my Audible library to be imported upon putting in my password.

**Platform**
MacBook Air M2 2022 
Sonoma Version 14.5 (23F79)

Thanks a lot!

**Comment by rmcrackan** [comment]
That's strange. Can you attach your latest log? In Settings, you can click the `Open log folder` button to find them.

**Comment by Itsmeraymon** [comment]
[_Log202406.zip](https://github.com/user-attachments/files/15754044/_Log202406.zip)

**Comment by rmcrackan** [comment]
Much thanks for your log file.

For security reasons I don't log full emails; I replace most of it with `...` for your privacy. However I can see pieces. It looks like you are using an email (`d[...]n@o[...]k.c[...]m`) with a `pre-amazon - uk` account. Old audible accounts (which predate the 2008 acquisition by amazon) use usernames. Typical post-amazon accounts use emails. I suspect this is our problem here.

Try this: in Settings > Accounts, either use a username with a pre-amazon locale, or use an email with a non-pre-amazon locale. In the spirit of 'turn it off and back on again', I'd delete the current account entry, save and close that box, re-open it, and make a new account entry.

**Comment by Itsmeraymon** [comment]
I'm in!! Thanks so much

**Comment by rmcrackan** [comment]
W00h00. Thanks for the update :)
