### ISSUE TITLE
Libation is not downloading longer books.

### ISSUE THREAD

**Issue by AKAKnick** [rmcrackan/Libation#920]
**Describe the bug**
Libation is not downloading longer books, I have space on my device, it downloads shorter books just fine but not longer books. Seems like anything over 24 Hours.

**To Reproduce**

1. Download a book that is long (e.g. IT by Stephen King, The Stand by Stephen King)
2. Click on downloaded book. 
3. File shows that book should be 45 hours
4. Open book
5. Book is only 20 hours 

**Expected behavior**
I expected the whole book to be downloaded

**Screenshots**
![Screenshot 2024-06-16 162544](https://github.com/rmcrackan/Libation/assets/172877694/e1a8d3f9-ef6f-400e-9af8-9544734bbbd5)

![Screenshot 2024-06-16 162446](https://github.com/rmcrackan/Libation/assets/172877694/50aed682-79e8-49f5-bd78-a6f740b44d9f)

![Screenshot 2024-06-16 162600](https://github.com/rmcrackan/Libation/assets/172877694/c4bc7a2b-2aa8-4196-a036-a1c33d26f9e2)

**Platform**

Windows 11

**Log Files**
![Screenshot 2024-06-16 163519](https://github.com/rmcrackan/Libation/assets/172877694/f71594c2-c570-4bf3-aad7-4603eca9a527)

**Comment by rmcrackan** [comment]
Thank you so much for all of these screenshots. I happen to also have IT in my library so it super made it easy to compare results.

I tested mine as both mp3 and non-mp3 and both work for me in VLC and windows media player as 45 hours. I suspect it has something to do with the media player you're using. The biggest reason for my hunch is that my mp3 version is *exactly* the same number of bytes as yours.

**Comment by AKAKnick** [comment]
That fixed it! Thank you so much! You are awesome! Love Libation so much! Thank you for your hard work! You Rock!

**Comment by rmcrackan** [comment]
:) You're welcome
