### ISSUE TITLE
Can Libation download a book from Audible if it has previously downloaded it?

### ISSUE THREAD

**Issue by cvahr2** [rmcrackan/Libation#922]
First of all thanks very much for Libation!

I downloaded it and was then able to download my audible library. Then I realized that I hadn't had the books divided by chapter...and did what is probably a stupid thing. I deleted the books out of Libation and also from my hard drive. Now when I click "Import" and then "Scan Library" to download them again, the word "Scanning" appears and disappears very quickly. And that's it, nothing else happens. I reinstalled Libation, but that didn't make a difference.

I think that Libation doesn't see the books that I already downloaded because after I deleted the books and reinstalled Libation, I purchased two new books in Audible - and Libation does see and download them. 

Any advice would be welcome.
Thanks! Chris

**Comment by rmcrackan** [comment]
Sorry for the confusion. I'm a professional at making powerful software. Intuitive user interface? Not so much.

Libation remembers each book's "download status"; that is: whether or not the book needs to be downloaded. When you do your first scan, it gets your library from audible and every book has the download status "not downloaded" (ie: red light). Then you downloaded a book and its status is changed to "downloaded" (green light).

To download the book again, set its status back to "not downloaded" -- it will get downloaded again next time you Liberate/download. You can do this for a single book with right-click or do this for every book by using the Visible Books menu.

Regarding deleting Libation: as you've seen, there's no installer/uninstaller. Libation is just a bunch of files. Install = unzip. Uninstall = delete. The only detail is, there's actually 2 folders: the files that came from the original zip, and the files that make it *your* Libation. These files are in your Users folder (`C:\Users\[username]\Libation` on Windows, similar folder for mac and linux). This is for your settings, logs, the database which tracks download status, etc.
