### ISSUE TITLE
Colons are allowed in filenames, but they fail on Android

### ISSUE THREAD

**Issue by skorokithakis** [rmcrackan/Libation#928]
I just spent half an hour trying to figure out why Syncthing wouldn't sync one of the books I downloaded with Libation. It turns out that a colon (`:`) is an invalid character on Android.

Could the set of Android disallowed characters be added to the default set? It would probably save people some hassle:

`?:"*|/\<>`

Thank you!

**Comment by rmcrackan** [comment]
Sorry for the headache. You can specify character replacements in Settings, "Download/Decrypt" tab, "Edit how filename characters are replaced". For instance you could replace `:` with `_`

**Comment by skorokithakis** [comment]
No problem, it wasn't your fault. I know I can do this, but it would be good to add that to the default set, so other people don't waste time trying to copy such files to Android devices.

**Comment by CLHatch** [comment]
> No problem, it wasn't your fault. I know I can do this, but it would be good to add that to the default set, so other people don't waste time trying to copy such files to Android devices.

Not sure if you're aware, but you can also have it replace it with the Unicode equiv of a colon (as well as unicode equiv of most the other chars).  I do this myself.
