### ISSUE TITLE
More Logging-Options / Serilog-Sinks

### ISSUE THREAD

**Issue by silelmot** [rmcrackan/Libation#930]
I tried to get the logfiles outside of an zipfile, and learned about serilog this way.
i found that only the ZipFile Sink is added to Libation.
Would it be possible to add a the Serilog.Sinks.File and the Serilog.Sinks.Console.
Best would be a switch in the gui to select it but have it and be able to change it manual in Settings would be great already.

**Comment by silelmot** [comment]
wow. you are fast. thanks!

**Comment by rmcrackan** [comment]
Don't thank me yet. I can't get the damn pre-release to build

**Comment by rmcrackan** [comment]
So this was going to be my reply, before the build gave me such grief. Still working through the build errors:

Here's my compromise. I created a pre-release version [v11.3.14](https://github.com/rmcrackan/Libation/releases/tag/v11.3.14) which includes Serilog.Sinks.Console and Serilog.Sinks.File. The compromise is that you're on your own; I'm not supporting it. I recommend backing up your Settings.json before making any changes.

I *think* you can add things like `"Name": "Console",` at the same level as `"Name": "ZipFile",` -- left as an exercise for the reader :)

Technically, I've written upgrade scripts in Libation to edit the Serilog settings. In practice though I haven't touched it in years and I don't anticipate doing so again. So any edits you make shouldn't ever get overwritten by me. To be safe, a backup of your new settings wouldn't hurt.

**Comment by rmcrackan** [comment]
Fixed! See above, except the correct version for your pre-release is https://github.com/rmcrackan/Libation/releases/tag/v11.3.14.2

Enjoy!

**Comment by silelmot** [comment]
wow. i just finished my docker-file for usage on a headless server (xvfb, x11vnc, websockify all running). great. will import it in my image tomorrow to have this software run on my docker-traefik-system

**Comment by rmcrackan** [comment]
So that's what my code looks like to non-programmers -- as a non-docker person, that looks like Greek to me. It sounds like you're happy tho so I am too lol

**Comment by wtanksleyjr** [comment]
Could you share some ideas or code with us? I think Docker would be a great
way to get a command line version, but I lack the knowledge, so I've been
using the dpkg.

-Wm

**Comment by silelmot** [comment]
i have to fix it first, but will share it afterwards.
@rmcrackan  the new deb doesnt work for the new sinks. i will fork it and try myself when i have some spare time. when i get it work i'll tell
