### ISSUE TITLE
Adding titles 

### ISSUE THREAD

**Issue by beth9900** [rmcrackan/Libation#933]
**Describe the bug** - A selection of books (170) will not liberate. 

**To Reproduce** Steps to reproduce the behavior:
Starting the program and letting it auto scan, starting a scan, and clicking on Librate does not let these download. They are send an error message of "License Denied".

**Expected behavior** - I would like these books to complete. 

**Screenshots**
![image](https://github.com/rmcrackan/Libation/assets/174663508/81c2025c-cc4e-4e83-be3d-c1dc3a1c9a25)

![image](https://github.com/rmcrackan/Libation/assets/174663508/a26b8e3d-9449-422c-ba85-72a123424348) In log this book says completed but it shows the red light.

Per Audible site I have access and it is currently in the library
![image](https://github.com/rmcrackan/Libation/assets/174663508/401b3743-ec3a-4724-a8a9-5668772e3bb2)

**Platform**
Windows 10 Pro

**Log Files** 
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B00IGHD5EC] The Storied Life of A. J. Fikry
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B00IGHD5EC] The Storied Life of A. J. Fikry
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00IGHD5EC] The Storied Life of A. J. Fikry
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B002UZDX98] Heart of Darkness
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B002UZDX98] Heart of Darkness
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B002UZDX98] Heart of Darkness
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B002V8MQCY] The White Plague
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B002V8MQCY] The White Plague
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B002V8MQCY] The White Plague
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [1094092657] The Poet
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1094092657] The Poet
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [1094092657] The Poet
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B004AFXAZS] Heart of Darkness: A Signature Performance by Kenneth Branagh
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B004AFXAZS] Heart of Darkness: A Signature Performance by Kenneth Branagh
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B004AFXAZS] Heart of Darkness: A Signature Performance by Kenneth Branagh
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B009K8UBV6] Return of the Thin Man
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B009K8UBV6] Return of the Thin Man
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B009K8UBV6] Return of the Thin Man
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B0B432RZ21] White Gold Wielder: The Second Chronicles of Thomas Covenant, Book 3
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B0B432RZ21] White Gold Wielder: The Second Chronicles of Thomas Covenant, Book 3
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0B432RZ21] White Gold Wielder: The Second Chronicles of Thomas Covenant, Book 3
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B0B3G876N9] The One Tree: The Second Chronicles of Thomas Covenant, Book 2
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B0B3G876N9] The One Tree: The Second Chronicles of Thomas Covenant, Book 2
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0B3G876N9] The One Tree: The Second Chronicles of Thomas Covenant, Book 2
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B0B2JK6ZSX] The Wounded Land: The Second Chronicles of Thomas Covenant, Book 1
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B0B2JK6ZSX] The Wounded Land: The Second Chronicles of Thomas Covenant, Book 1
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0B2JK6ZSX] The Wounded Land: The Second Chronicles of Thomas Covenant, Book 1
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B00H7J7HVC] The Toymaker
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B00H7J7HVC] The Toymaker
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00H7J7HVC] The Toymaker
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B00H57T912] The Savannah Project: Jake Pendleton Series, Book 1
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B00H57T912] The Savannah Project: Jake Pendleton Series, Book 1
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00H57T912] The Savannah Project: Jake Pendleton Series, Book 1
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B00GUP8QS2] Breach of Power
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B00GUP8QS2] Breach of Power
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00GUP8QS2] Breach of Power
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B002UZN1Z4] The Dragon in the Sea
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B002UZN1Z4] The Dragon in the Sea
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B002UZN1Z4] The Dragon in the Sea
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B076L2C45F] The Illustrated Man
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B076L2C45F] The Illustrated Man
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B076L2C45F] The Illustrated Man
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [1501903403] This Tender Land
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [1501903403] This Tender Land
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1501903403] This Tender Land
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B085LRBBXJ] The Holy Bible: King James Version: The Old and New Testaments
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B085LRBBXJ] The Holy Bible: King James Version: The Old and New Testaments
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B085LRBBXJ] The Holy Bible: King James Version: The Old and New Testaments
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B003TTWDFY] The Book of Five Rings
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B003TTWDFY] The Book of Five Rings
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B003TTWDFY] The Book of Five Rings
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [B0B8P6VX1G] The Guardian
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [B0B8P6VX1G] The Guardian
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0B8P6VX1G] The Guardian
7/3/2024 6:47 PM	Download & Decrypt Step, Begin: [1980035601] Mosaic: Breakthrough, Book 5
7/3/2024 6:47 PM	Download & Decrypt Step, Completed: [1980035601] Mosaic: Breakthrough, Book 5
7/3/2024 6:47 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1980035601] Mosaic: Breakthrough, Book 5
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [1980035644] Ripple
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [1980035644] Ripple
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1980035644] Ripple
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [1980035660] Catalyst
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [1980035660] Catalyst
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1980035660] Catalyst
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [1980035652] Leap
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [1980035652] Leap
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1980035652] Leap
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [1980035679] Breakthrough
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [1980035679] Breakthrough
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1980035679] Breakthrough
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B002UZL9G2] Atlas Shrugged
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B002UZL9G2] Atlas Shrugged
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B002UZL9G2] Atlas Shrugged
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B01GQO53QE] Fingerprints of the Gods: The Quest Continues
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B01GQO53QE] Fingerprints of the Gods: The Quest Continues
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B01GQO53QE] Fingerprints of the Gods: The Quest Continues
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [1982689714] And Then She Vanished: Joseph Bridgeman, Book 1
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [1982689714] And Then She Vanished: Joseph Bridgeman, Book 1
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1982689714] And Then She Vanished: Joseph Bridgeman, Book 1
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B09FM4KXBL] The Locked Door
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B09FM4KXBL] The Locked Door
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B09FM4KXBL] The Locked Door
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [1705246125] Claw: A Canadian Thriller: Claw, Book 1
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [1705246125] Claw: A Canadian Thriller: Claw, Book 1
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [1705246125] Claw: A Canadian Thriller: Claw, Book 1
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B076X5ZPPD] Unacknowledged: An Exposé of the World’s Greatest Secret
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B076X5ZPPD] Unacknowledged: An Exposé of the World’s Greatest Secret
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B076X5ZPPD] Unacknowledged: An Exposé of the World’s Greatest Secret
7/3/2024 6:48 PM	Download Pdf Step, Begin: [B076X5ZPPD] Unacknowledged: An Exposé of the World’s Greatest Secret
7/3/2024 6:48 PM	Download Pdf Step, Completed: [B076X5ZPPD] Unacknowledged: An Exposé of the World’s Greatest Secret
7/3/2024 6:48 PM	Error downloading PDF. See log for details. Error summary: Content License denied for asin: [B076X5ZPPD]
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0D2NRT7TF] The Long Way Home (Long Night Book 2): A Cyber Thriller: Survival and Sacrifice in a Digital Apocalypse
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0D2NRT7TF] The Long Way Home (Long Night Book 2): A Cyber Thriller: Survival and Sacrifice in a Digital Apocalypse
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0D2NRT7TF] The Long Way Home (Long Night Book 2): A Cyber Thriller: Survival and Sacrifice in a Digital Apocalypse
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY8X3HQW] The Long Night (Book 1): A Post-Apocalyptic Cyber Thriller
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY8X3HQW] The Long Night (Book 1): A Post-Apocalyptic Cyber Thriller
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY8X3HQW] The Long Night (Book 1): A Post-Apocalyptic Cyber Thriller
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY99RLG9] Stories to Curl Your Toes: Five creepy and grotesque stories including a mysterious illness, dystopian society, and blood thirsty monster
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY99RLG9] Stories to Curl Your Toes: Five creepy and grotesque stories including a mysterious illness, dystopian society, and blood thirsty monster
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY99RLG9] Stories to Curl Your Toes: Five creepy and grotesque stories including a mysterious illness, dystopian society, and blood thirsty monster
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY8QB44T] Left Alive: An End Times Novel
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY8QB44T] Left Alive: An End Times Novel
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY8QB44T] Left Alive: An End Times Novel
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY5SJFR7] Sea of Red
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY5SJFR7] Sea of Red
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY5SJFR7] Sea of Red
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY978WMY] The Code Hunters: A Nicholas Foxe Adventure
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY978WMY] The Code Hunters: A Nicholas Foxe Adventure
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY978WMY] The Code Hunters: A Nicholas Foxe Adventure
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY9NCRMS] Confrontation: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY9NCRMS] Confrontation: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY9NCRMS] Confrontation: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY38ZH3Z] Endurance: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY38ZH3Z] Endurance: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY38ZH3Z] Endurance: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY9NZFZZ] Survival: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY9NZFZZ] Survival: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY9NZFZZ] Survival: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY4LNH62] Impact: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY4LNH62] Impact: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY4LNH62] Impact: A Post-Apocalyptic EMP Survival series
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CYD1XL77] Father, Son, Stone
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CYD1XL77] Father, Son, Stone
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CYD1XL77] Father, Son, Stone
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0D1NVW6F1] Carbon-14: The Shroud of Turin
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0D1NVW6F1] Carbon-14: The Shroud of Turin
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0D1NVW6F1] Carbon-14: The Shroud of Turin
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0D2JWWXQ4] A Changing World
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0D2JWWXQ4] A Changing World
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0D2JWWXQ4] A Changing World
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY884PXK] The Hard Years
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY884PXK] The Hard Years
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY884PXK] The Hard Years
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0D1PCQQQL] Boom And Bust
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0D1PCQQQL] Boom And Bust
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0D1PCQQQL] Boom And Bust
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0D1NS322M] The Good Years: Book Two In The Tinder Street Saga
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0D1NS322M] The Good Years: Book Two In The Tinder Street Saga
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0D1NS322M] The Good Years: Book Two In The Tinder Street Saga
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CY46DBW1] Tinder Street: Tinder Street Saga Book One
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CY46DBW1] Tinder Street: Tinder Street Saga Book One
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CY46DBW1] Tinder Street: Tinder Street Saga Book One
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CW8M3H6T] Dead America - Kansas Box Set Parts 1-5
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CW8M3H6T] Dead America - Kansas Box Set Parts 1-5
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CW8M3H6T] Dead America - Kansas Box Set Parts 1-5
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0D2NT7L36] Dead America - Gun Runners Box Set - Books 1-6
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0D2NT7L36] Dead America - Gun Runners Box Set - Books 1-6
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0D2NT7L36] Dead America - Gun Runners Box Set - Books 1-6
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B07DPT63W6] The Secret of the Stones: Lost Chambers Series, Book 1
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B07DPT63W6] The Secret of the Stones: Lost Chambers Series, Book 1
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B07DPT63W6] The Secret of the Stones: Lost Chambers Series, Book 1
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0CRRP4WW7] George Orwell’s 1984: An Audible Original adaptation
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0CRRP4WW7] George Orwell’s 1984: An Audible Original adaptation
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0CRRP4WW7] George Orwell’s 1984: An Audible Original adaptation
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B00HAKIBSQ] The Ash Tree
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B00HAKIBSQ] The Ash Tree
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00HAKIBSQ] The Ash Tree
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B00CLSQRZG] The Land of Mist
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B00CLSQRZG] The Land of Mist
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00CLSQRZG] The Land of Mist
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B085RHYBV9] Beowulf
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B085RHYBV9] Beowulf
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B085RHYBV9] Beowulf
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B003JNJ6SC] Madame Bovary
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B003JNJ6SC] Madame Bovary
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B003JNJ6SC] Madame Bovary
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B00CLSQA2Q] The Last Man
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B00CLSQA2Q] The Last Man
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B00CLSQA2Q] The Last Man
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B085F3BNKD] Crime and Punishment
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B085F3BNKD] Crime and Punishment
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B085F3BNKD] Crime and Punishment
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B075VF1R27] The Picture of Dorian Gray
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B075VF1R27] The Picture of Dorian Gray
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B075VF1R27] The Picture of Dorian Gray
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B0773Z4GB6] A Tale of Two Cities: The Audible Dickens Collection
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B0773Z4GB6] A Tale of Two Cities: The Audible Dickens Collection
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B0773Z4GB6] A Tale of Two Cities: The Audible Dickens Collection
7/3/2024 6:48 PM	Download & Decrypt Step, Begin: [B095TS6LLR] War and Peace
7/3/2024 6:48 PM	Download & Decrypt Step, Completed: [B095TS6LLR] War and Peace
7/3/2024 6:48 PM	Download & Decrypt:  Content license denied. Check your Audible account to see if you have access to this title. - [B095TS6LLR] War and Peace

**Comment by rmcrackan** [comment]
Thank you very much for these details and screenshots!

I'm about to be out of town for a bit and I'll take a look when I return. In the mean time, would you mind also attaching a log file to this ticket? They have a bit more detail for me to see. If you go into Libation's Settings, on the first tab there's a button for Open Log Folder. Just the latest log file is fine. Please drag and drop it into the reply box on this page.

**Comment by beth9900** [comment]
Hi there, 

I am not in a hurry. Please enjoy your vacation. 

I hope this is the correct log file. 

Katherine Sockwell

    On Wednesday, July 3, 2024 at 07:56:00 PM CDT, rmcrackan ***@***.***> wrote:  
 
 


Thank you very much for these details and screenshots!

I'm about to be out of town for a bit and I'll take a look when I return. In the mean time, would you mind also attaching a log file to this ticket? They have a bit more detail for me to see. If you go into Libation's Settings, on the first tab there's a button for Open Log Folder. Just the latest log file is fine. Please drag and drop it into the reply box on this page.

**Comment by rmcrackan** [comment]
> I am not in a hurry. Please enjoy your vacation.

Thank you!

> I hope this is the correct log file.

No file was attached. Maybe that's not allowed via email; only directly on this page. I've never tried by email. I assumed that would have worked. Weird. Oh well, here's the page. You can drag and drop the file into the 'add a comment' box at bottom -- https://github.com/rmcrackan/Libation/issues/933

**Comment by beth9900** [comment]
Hi there, 

I tried again today and everything completed. I don't know why it took multiple sessions but I am all good now. 

Thanks for everything. 
Katherine Sockwell



   On Thursday, July 4, 2024 at 05:48:16 AM CDT, rmcrackan ***@***.***> wrote:  
 
 



I am not in a hurry. Please enjoy your vacation.


Thank you!


I hope this is the correct log file.


No file was attached. Maybe that's not allowed via email; only directly on this page. I've never tried by email. I assumed that would have worked. Weird. Oh well, here's the page. You can drag and drop the file into the 'add a comment' box at bottom -- #933

**Comment by rmcrackan** [comment]
Thank you for the update. I'm so glad it works now.
