### ISSUE TITLE
Would love to include kindle ebooks

### ISSUE THREAD

**Issue by michaelsmolka** [rmcrackan/Libation#935]
I really love Libation. Together with Audiobookshelf, both running on our NAS, I found the perfect solution for our audiobooks.
Over the years we (me, my wife and the kids) were collecting a continously growing collection of digital assets (mainly ebooks and audiobooks). Now as we have already "freed" the audiobooks, we are eager to find a similar solution for the ebooks.

**Describe the solution you'd like**
The idea is simple: We'd like to have an app like libation that, once configured, monitors the kindle account, downloads every new book and after "de-DRMing" it, loads it to our NAS. From there we could access it with any free ebook reader without having amazon tracking every user action.
(Or maybe just a extension within Libation but for the ebooks)

**Describe alternatives you've considered**
I already searched the web and found some calibre plugins that are more or less able to do the DRM part. But you still have first to manually donwload the books and bring them into calibre. And you rely on an outdated version of kindle for Mac/PC as it is no longer developed by Amazon. Additionally this unfortunately didn't work with every kindle book. And although calibre is nice, it is far away from being user friendly in terms of intuitive use.
Would really, really love to see an automated solution like Libation for Kindle ebooks.

**Comment by rexpark** [comment]
This would be a much appreciated enhancement.

**Comment by darrenoc3** [comment]
+1 Libation is fantastic, would be great to have an all-in-one solution for Audible+Kindle without having to use Calibre

**Comment by darrenoc3** [comment]
Would love to see this one day, but it's already been asked for and isn't likely to happen, see: https://github.com/rmcrackan/Libation/issues/813

**Comment by rmcrackan** [comment]
This is a great idea, but I'm going to close it for the same rationale as linked above. I'm limiting open feature requests to things which fit the current vibe of the app. That said: if another developer wants to come along to help and they really want to do this, I'd be down for that conversation. Until then though, sorry.
