### ISSUE TITLE
Queue processing fails - Suspected System.Net.Sockets.resources problem

### ISSUE THREAD

**Issue by Pantechniconsole** [rmcrackan/Libation#937]
Libation 11.1.0.1

When processing the queue, it runs for a few seconds and then the processing time jumps to an hour and processing appears to stop. Eventually an Abort/Retry/Ignore request appears.

It happens every time Libation is restarted.

Platform
Windows 11 Enterprise (23H2 Version 10.0.22631 Build 22631), fully patched including .Net updates (2024-07 Cumulative Update for .NET Framework 3.5 and 4.8.1 for Windows 11, version 23H2 for x64 (KB5039895))

Seeing this message in the logs
```
{}2024-07-10 10:51:37.065 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module System.Net.Sockets.resources, Version=7.0.0.0, Culture=en-GB, PublicKeyToken=b03f5f7f11d50a3a
 {}2024-07-10 10:51:37.075 +01:00 [ERR] (at LibationFileManager.InteropFactory.CurrentDomain_AssemblyResolve(System.Object, System.ResolveEventArgs)) Unable to load module System.Net.Sockets.resources, Version=7.0.0.0, Culture=en, PublicKeyToken=b03f5f7f11d50a3a
```

**Comment by Pantechniconsole** [comment]
[Log202407.zip](https://github.com/user-attachments/files/16159201/Log202407.zip)

**Comment by rmcrackan** [comment]
Thank you for the log, all of your details, and for the update. I'm glad everything resolved itself. I guess I'm glad. I hate unexplained bugs.
