### ISSUE TITLE
Filter podcasts with LibationCli?

### ISSUE THREAD

**Issue by stickystyle** [rmcrackan/Libation#938]
I have three accounts setup in Libation (one for each family member), running in a docker container that is dropping the audiobooks into user specific libraries within audiobookshelf. 
Recently, one of the family members has subscribed to a podcast in audible, and that's all well and good for them, but I don't care about backing that podcast on my server. I've marked all previous episodes as downloaded so the server doesn't try to download them, but what can I do about _new_ episodes? LibationCli has a flag for pdfs only, could it also get a flag for audiobooks only? Or perhaps is there a flag in the DB schema that we can mark a series as ignored?

**Comment by rmcrackan** [comment]
There's no cli flag but there are settings

* Import library settings tab: Import episodes?
* Import library settings tab: Download episodes?

Other podcast related features

* Important settings tab: Save all podcast episodes in a series to the series parent folder
* You can also filter using the `Podcast` flags. Or `-Podcast` to omit podcasts. Note: these are all identical but me and/or other users couldn't remember which one worked: Podcast, Podcasts, IsPodcast, Episode, Episodes, IsEpisode
