### ISSUE TITLE
Startup fails without Feedback

### ISSUE THREAD

**Issue by lufixSch** [rmcrackan/Libation#939]
**Describe the bug**
When I try to start libation either from the terminal or my application launcher nothing happens. In the terminal the Process just completes without any output.

**To Reproduce**

1. Install Libation
2. Run `libation` in the terminal

**Expected behavior**
I expect a window to pop up.

**Platform**
```
OS: Arch Linux x86_64 
Kernel: 6.9.7-arch1-1 
DE: hyprland 
WM: sway 
```

**Log Files**
I was unable to locate them.

**Comment by lufixSch** [comment]
Found the logs:

```
 OS                    Linux
 Version               11.3.14.2
 ReleaseIdentifier     None
 InteropFunctionsType  LinuxConfigApp.LinuxInterop
 LibationFiles         /home/lukas/Libation
 Books Folder          
 === EXCEPTION ===
 System.InvalidOperationException: Default font family name can't be null or empty.
   at Avalonia.Media.FontManager..ctor(IFontManagerImpl platformImpl)
   at Avalonia.Media.FontManager.get_Current()
   at Avalonia.Media.Typeface.get_GlyphTypeface()
   at Avalonia.Rendering.Composition.Compositor.get_DiagnosticTextRenderer()
   at Avalonia.Rendering.Composition.Compositor.CreateCompositionTarget(Func`1 surfaces)
   at Avalonia.Rendering.Composition.CompositingRenderer..ctor(IRenderRoot root, Compositor compositor, Func`1 surfaces)
   at Avalonia.Controls.TopLevel..ctor(ITopLevelImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.WindowBase..ctor(IWindowBaseImpl impl, IAvaloniaDependencyResolver dependencyResolver)
   at Avalonia.Controls.Window..ctor(IWindowImpl impl)
   at LibationAvalonia.Dialogs.SetupDialog..ctor() in /home/lukas/.cache/yay/libation/src/Libation-11.3.14.2/Source/LibationAvalonia/Dialogs/SetupDialog.axaml.cs:line 12
   at LibationAvalonia.App.OnFrameworkInitializationCompleted() in /home/lukas/.cache/yay/libation/src/Libation-11.3.14.2/Source/LibationAvalonia/App.axaml.cs:line 64
   at Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   at LibationAvalonia.Program.Main(String[] args) in /home/lukas/.cache/yay/libation/src/Libation-11.3.14.2/Source/LibationAvalonia/Program.cs:line 65
```

As I installed Libation using the [AUR](https://aur.archlinux.org/packages/libation), this might not be directly related to Libation but rather the package build process or dependencies.

**Comment by lufixSch** [comment]
The logs helped a lot. I was able to solve it by installing the [ttf-ms-win10](https://aur.archlinux.org/packages/ttf-ms-win10-auto) package. Nevertheless, it would be nice to know which specific fonts are needed.

It would also nice to put the log file location somewhere into the documentation or the issue template.

**Comment by royal-k506** [comment]
Just faced the same issue. Could you get Libation to run? Using Ubuntu 24.04 and already installed ttf-mscorefonts-installer but still getting the same crash. Wonder where to define that standard font.

**Comment by lufixSch** [comment]
For me installing `ttf-ms-win10` solved the issue. Is the `ttf-mscorefonts-installer` on Ubuntu equivalent to the `ttf-ms-win10` on arch? Did you check in a font manager if all fonts are installed?
I also tried looking up the font definition and changing that to another font. I found different locations where such a variable is defined but I either wasn't able to locate the all definitions or was just missing the right one.
I'm surprised, that Ubuntu is even missing those fonts. I installed Libation on Manjaro before and had no issue with missing fonts.

Below is the list of fonts from the Arch AUR Package description maybe you can compare and check which one is missing.

    [file://arial.ttf](file:///)
    [file://arialbd.ttf](file:///)
    [file://arialbi.ttf](file:///)
    [file://ariali.ttf](file:///)
    [file://ariblk.ttf](file:///)
    [file://bahnschrift.ttf](file:///)
    [file://calibri.ttf](file:///)
    [file://calibrib.ttf](file:///)
    [file://calibrii.ttf](file:///)
    [file://calibril.ttf](file:///)
    [file://calibrili.ttf](file:///)
    [file://calibriz.ttf](file:///)
    [file://cambria.ttc](file:///)
    [file://cambriab.ttf](file:///)
    [file://cambriai.ttf](file:///)
    [file://cambriaz.ttf](file:///)
    [file://Candara.ttf](file:///)
    [file://Candarab.ttf](file:///)
    [file://Candarai.ttf](file:///)
    [file://Candaral.ttf](file:///)
    [file://Candarali.ttf](file:///)
    [file://Candaraz.ttf](file:///)
    [file://comic.ttf](file:///)
    [file://comicbd.ttf](file:///)
    [file://comici.ttf](file:///)
    [file://comicz.ttf](file:///)
    [file://consola.ttf](file:///)
    [file://consolab.ttf](file:///)
    [file://consolai.ttf](file:///)
    [file://consolaz.ttf](file:///)
    [file://constan.ttf](file:///)
    [file://constanb.ttf](file:///)
    [file://constani.ttf](file:///)
    [file://constanz.ttf](file:///)
    [file://corbel.ttf](file:///)
    [file://corbelb.ttf](file:///)
    [file://corbeli.ttf](file:///)
    [file://corbell.ttf](file:///)
    [file://corbelli.ttf](file:///)
    [file://corbelz.ttf](file:///)
    [file://cour.ttf](file:///)
    [file://courbd.ttf](file:///)
    [file://courbi.ttf](file:///)
    [file://couri.ttf](file:///)
    [file://ebrima.ttf](file:///)
    [file://ebrimabd.ttf](file:///)
    [file://framd.ttf](file:///)
    [file://framdit.ttf](file:///)
    [file://Gabriola.ttf](file:///)
    [file://gadugi.ttf](file:///)
    [file://gadugib.ttf](file:///)
    [file://georgia.ttf](file:///)
    [file://georgiab.ttf](file:///)
    [file://georgiai.ttf](file:///)
    [file://georgiaz.ttf](file:///)
    [file://himalaya.ttf](file:///)
    [file://impact.ttf](file:///)
    [file://Inkfree.ttf](file:///)
    [file://javatext.ttf](file:///)
    [file://LeelaUIb.ttf](file:///)
    [file://LeelawUI.ttf](file:///)
    [file://LeelUIsl.ttf](file:///)
    [file://license.rtf](file:///)
    [file://lucon.ttf](file:///)
    [file://l_10646.ttf](file:///)
    [file://malgun.ttf](file:///)
    [file://malgunbd.ttf](file:///)
    [file://malgunsl.ttf](file:///)
    [file://marlett.ttf](file:///)
    [file://micross.ttf](file:///)
    [file://mingliub.ttc](file:///)
    [file://mmrtext.ttf](file:///)
    [file://mmrtextb.ttf](file:///)
    [file://monbaiti.ttf](file:///)
    [file://msgothic.ttc](file:///)
    [file://msjh.ttc](file:///)
    [file://msjhbd.ttc](file:///)
    [file://msjhl.ttc](file:///)
    [file://msyh.ttc](file:///)
    [file://msyhbd.ttc](file:///)
    [file://msyhl.ttc](file:///)
    [file://msyi.ttf](file:///)
    [file://mvboli.ttf](file:///)
    [file://Nirmala.ttf](file:///)
    [file://NirmalaB.ttf](file:///)
    [file://NirmalaS.ttf](file:///)
    [file://ntailu.ttf](file:///)
    [file://ntailub.ttf](file:///)
    [file://pala.ttf](file:///)
    [file://palab.ttf](file:///)
    [file://palabi.ttf](file:///)
    [file://palai.ttf](file:///)
    [file://phagspa.ttf](file:///)
    [file://phagspab.ttf](file:///)
    [file://segmdl2.ttf](file:///)
    [file://segoepr.ttf](file:///)
    [file://segoeprb.ttf](file:///)
    [file://segoesc.ttf](file:///)
    [file://segoescb.ttf](file:///)
    [file://segoeui.ttf](file:///)
    [file://segoeuib.ttf](file:///)
    [file://segoeuii.ttf](file:///)
    [file://segoeuil.ttf](file:///)
    [file://segoeuisl.ttf](file:///)
    [file://segoeuiz.ttf](file:///)
    [file://seguibl.ttf](file:///)
    [file://seguibli.ttf](file:///)
    [file://seguiemj.ttf](file:///)
    [file://seguihis.ttf](file:///)
    [file://seguili.ttf](file:///)
    [file://seguisb.ttf](file:///)
    [file://seguisbi.ttf](file:///)
    [file://seguisli.ttf](file:///)
    [file://seguisym.ttf](file:///)
    [file://simsun.ttc](file:///)
    [file://simsunb.ttf](file:///)
    [file://Sitka.ttc](file:///)
    [file://SitkaB.ttc](file:///)
    [file://SitkaI.ttc](file:///)
    [file://SitkaZ.ttc](file:///)
    [file://sylfaen.ttf](file:///)
    [file://symbol.ttf](file:///)
    [file://tahoma.ttf](file:///)
    [file://tahomabd.ttf](file:///)
    [file://taile.ttf](file:///)
    [file://taileb.ttf](file:///)
    [file://times.ttf](file:///)
    [file://timesbd.ttf](file:///)
    [file://timesbi.ttf](file:///)
    [file://timesi.ttf](file:///)
    [file://trebuc.ttf](file:///)
    [file://trebucbd.ttf](file:///)
    [file://trebucbi.ttf](file:///)
    [file://trebucit.ttf](file:///)
    [file://verdana.ttf](file:///)
    [file://verdanab.ttf](file:///)
    [file://verdanai.ttf](file:///)
    [file://verdanaz.ttf](file:///)
    [file://webdings.ttf](file:///)
    [file://wingding.ttf](file:///)
    [file://YuGothB.ttc](file:///)
    [file://YuGothL.ttc](file:///)
    [file://YuGothM.ttc](file:///)
    [file://YuGothR.ttc](file:///)

**Comment by DeltaR9A2** [comment]
Solved this issue in Arch linux by installing ttf-ms-fonts from AUR, which includes 

```
ttf-ms-fonts /usr/
ttf-ms-fonts /usr/share/
ttf-ms-fonts /usr/share/fonts/
ttf-ms-fonts /usr/share/fonts/TTF/
ttf-ms-fonts /usr/share/fonts/TTF/AndaleMo.TTF
ttf-ms-fonts /usr/share/fonts/TTF/AriBlk.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Arial.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Arialbd.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Arialbi.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Ariali.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Comic.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Comicbd.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Georgia.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Georgiab.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Georgiai.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Georgiaz.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Impact.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Times.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Timesbd.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Timesbi.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Timesi.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Trebucbd.ttf
ttf-ms-fonts /usr/share/fonts/TTF/Verdana.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Verdanab.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Verdanai.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Verdanaz.TTF
ttf-ms-fonts /usr/share/fonts/TTF/Webdings.TTF
ttf-ms-fonts /usr/share/fonts/TTF/cour.ttf
ttf-ms-fonts /usr/share/fonts/TTF/courbd.ttf
ttf-ms-fonts /usr/share/fonts/TTF/courbi.ttf
ttf-ms-fonts /usr/share/fonts/TTF/couri.ttf
ttf-ms-fonts /usr/share/fonts/TTF/trebuc.ttf
ttf-ms-fonts /usr/share/fonts/TTF/trebucbi.ttf
ttf-ms-fonts /usr/share/fonts/TTF/trebucit.ttf
ttf-ms-fonts /usr/share/licenses/
ttf-ms-fonts /usr/share/licenses/ttf-ms-fonts/
ttf-ms-fonts /usr/share/licenses/ttf-ms-fonts/Licen.TXT
```

**Comment by countbytedown** [comment]
@rmcrackan can you provide the names of the fonts used by the program?
Running on Ubuntu and I can't get past the crash detailed in this issue.
@royal-k506  did you find a solution?
