### ISSUE TITLE
crashes after login when attempting to import library

### ISSUE THREAD

**Issue by Furak** [rmcrackan/Libation#94]
[Log202108.log](https://github.com/rmcrackan/Libation/files/7036892/Log202108.log)
[_Log202108.log](https://github.com/rmcrackan/Libation/files/7036893/_Log202108.log)

**Comment by Furak** [comment]
FYI i tested with version 5.5.0 which my friend was using too and after i deleted the config folder and reconfigured it for the 5.5.0 it works fine, i didnt try to rerun 5.5.4

**Comment by rmcrackan** [comment]
> reconfigured it for the 5.5.0 it works fine

I'm confused. Did this fix your issue?

**Comment by Furak** [comment]
well, yes, if you consider running older version a fix for issue in higher version

**Comment by rmcrackan** [comment]
Ah -- It did work in 5.5.0 and did not work in 5.5.4. Now I understand my confusion.

I found where I fixed one bug in 5.5.4 and introduced a different bug. My apologies. Please try 5.5.5. If you're still seeing this bug, please attach the new log. I think 5.5.5 will fix your issue though. Sorry again for the mistake.

**Comment by Furak** [comment]
[Log202108.log](https://github.com/rmcrackan/Libation/files/7042181/Log202108.log)

thanks 5.5.5 works for me
