### ISSUE TITLE
Can't find latest Audible purchase/Error importing library

### ISSUE THREAD

**Issue by Hooey** [rmcrackan/Libation#942]
**Describe the bug**
Libation isn't finding my latest Audible purchase, although it's in my Downloads folder.

**To Reproduce**

1. Click Import/Locate Audiobooks (This after a scan failed to find the book)
2. The new book isn't listed.

**Expected behavior**
The new book would be found.

I then tried to scan my library and got the following: Error importing library.
See attached files.

**Platform**
Windows 10

**Log Files**
Attach your Libation log file here.
[_Log202407_003.zip](https://github.com/user-attachments/files/16274195/_Log202407_003.zip)

**Comment by rmcrackan** [comment]
Thank you very much for your logs. First thing to try: [upgrade to the latest version](https://github.com/rmcrackan/Libation/releases/latest). I'm not sure if it will help but it couldn't hurt. version 11.1 has been pretty reliable.

The error in your files is that Libation can't authenticate. Possibly just expired tokens (which are like browser cookies). I'd go to Settings > Accounts, delete your accounts, save, and re-add your accounts. On next scan you'll have to put in your pw again. Let me know if it still won't get your new book.

**Comment by Hooey** [comment]
Back in business, thank you very much!

**Comment by rmcrackan** [comment]
You're welcome :)
