### ISSUE TITLE
Audiobook list incomplete

### ISSUE THREAD

**Issue by Porkechebure** [rmcrackan/Libation#943]
**Describe the bug**
Audiobook list incomplete. Lists 407 books, shows only a few. no paging, no way to navigate.
filters sucks and don't work.
(Advice from a dev, LUCENE IS SHIT, eradicate it)
I.E. I put the lucene (SHIT!!!!) syntax author:"name" and if finds only 1 book, while i listened a ton of them from this author.
And no, it doesn't take only books i borrowed or that I recently listened, because there are books i even remotely searched or listened for 1 minute months ago.
Tried to export the full list in excel and search what's in that and doesn't work.

Moreover, some of the books I listened or podcast aren't even searchable at all and not even pop up in the excel export.

WTF?

**To Reproduce**

Just install and link the account and scan for books

**Expected behavior**
see the complete list or at least a paged version of it so i can navigate all the books

**Screenshots**
![image](https://github.com/user-attachments/assets/de1403bb-30a0-4740-9aef-b93246454c92)

**Platform**

Win 11 latest

**Comment by rmcrackan** [comment]
Lots to unpack here.

> 407 books

If you expand the `+` buttons for series/podcast, does it show all titles?

> LUCENE IS SHIT, eradicate it

Sorry, Lucene is the best offline engine I could find which could easily work with this framework. It also allows me to further customize it so I could make it more audiobook-centric, with searchable narrator, podcast, etc. which I love. I'm not a fan of its odd syntax but I do like its versatility.

I admit there are much better online engines but online is not an option. As a core design, Libation doesn't do anything online except query audible for necessary information or check for version updates. Users are already very wary of what Libation does and possible privacy implications, so having an offline search is non-negotiable.

> it doesn't take only books i borrowed or that I recently listened, because there are books i even remotely searched or listened for 1 minute months ago.

The grid should match https://www.audible.com/library (or whatever the url is if you're in a region other than the US). If it doesn't match, then it's a bug and I'd like to take a look at your log file if you're willing to attach it.

> Tried to export the full list in excel and search what's in that and doesn't work.

The excel export is pretty naive. It's essentially what's in the unfiltered grid, so if there's a bug in the excel export it will really be about what's in the grid.

**Comment by Porkechebure** [comment]
> Lots to unpack here.
> 
> > 407 books
> 
> If you expand the `+` buttons for series/podcast, does it show all titles?
> 
> > LUCENE IS SHIT, eradicate it
> 
> Sorry, Lucene is the best offline engine I could find which could easily work with this framework. It also allows me to further customize it so I could make it more audiobook-centric, with searchable narrator, podcast, etc. which I love. I'm not a fan of its odd syntax but I do like its versatility.
> 
> I admit there are much better online engines but online is not an option. As a core design, Libation doesn't do anything online except query audible for necessary information or check for version updates. Users are already very wary of what Libation does and possible privacy implications, so having an offline search is non-negotiable.
> 
> > it doesn't take only books i borrowed or that I recently listened, because there are books i even remotely searched or listened for 1 minute months ago.
> 
> The grid should match https://www.audible.com/library (or whatever the url is if you're in a region other than the US). If it doesn't match, then it's a bug and I'd like to take a look at your log file if you're willing to attach it.
> 
> > Tried to export the full list in excel and search what's in that and doesn't work.
> 
> The excel export is pretty naive. It's essentially what's in the unfiltered grid, so if there's a bug in the excel export it will really be about what's in the grid.

They weren't added to my library. However Adding a podcast now starts the download process but never produce files and opening with Locate files doesn't find anything
