### ISSUE TITLE
Libation login crash

### ISSUE THREAD

**Issue by elmo6973** [rmcrackan/Libation#949]
**Describe the bug**
When I leave libaition downloading over night sometimes i wake up to an unexpected error.

**To Reproduce**
I just leave the program running since I have about 2k audiobooks and podcasts in my audible account.
![Screenshot 2024-07-27 172651](https://github.com/user-attachments/assets/85fc9385-f1cd-4dbb-8830-c4d815dbc106)

**Expected behavior**
The expected behavior is a smoothing running program while it downloads over night

**Screenshots**
![Screenshot 2024-07-27 172651](https://github.com/user-attachments/assets/85fc9385-f1cd-4dbb-8830-c4d815dbc106)

**Platform**

Windows 11

**Log Files**

[_Log202407_008.zip](https://github.com/user-attachments/files/16401827/_Log202407_008.zip)
[_Log202407_009.zip](https://github.com/user-attachments/files/16401828/_Log202407_009.zip)
[AccountsSettings.json](https://github.com/user-attachments/files/16401829/AccountsSettings.json)

**Comment by rmcrackan** [comment]
Thank you for attaching these files. Strange, it looks like something bad happened to your AccountSettings.json file. If you delete that file and restart Libation, it will create a new one and the problem will go away. Unfortunately you'll need to go through Libations Settings again.
