### ISSUE TITLE
setup

### ISSUE THREAD

**Issue by relbell83** [rmcrackan/Libation#950]
[_Log202408.zip](https://github.com/user-attachments/files/16553737/_Log202408.zip)

**Comment by rmcrackan** [comment]
I'm not actually sure how this could happen. Was the settings file manually edited?

`Access to the path 'C:\\WINDOWS\\system32\\.;LibationFiles\\Books' is denied.`

**Comment by relbell83** [comment]
I'm not sure to be honest. I was following the setup instructions and then it gave me this error.
I ended up closing out of the settings entirely and moved on to the next step and everything seems to be okay now.

**Comment by rmcrackan** [comment]
That's just strange. I'll poke around and see if I can recreate it. Thanks much for the log file. I'll close this bug since the bug itself somehow fixed itself though.
