### ISSUE TITLE
Error processing book with libationcli on Raspberry pi 5

### ISSUE THREAD

**Issue by jcarletto27** [rmcrackan/Libation#951]
**Describe the bug**
DownloadDecryptBook fails for some books when using libationcli on Raspberry Pi using arm64 linux versions 11.1, 11.3.13 and latest 11.3.14.2

Error is `Error processing book. Skipping. This book will be tried again on next attempt. For options of skipping or marking as error, retry with main Libation app.. See log for more details.`

**To Reproduce**

libationcli liberate

**Expected behavior**
running this on my desktop running the arch amd64 version processes without issue

**Screenshots**
no screenshots

**Platform**
Raspbian inchworm on raspberry pi 5 arm64

**Log Files**
[_Log202408.zip](https://github.com/user-attachments/files/16566935/_Log202408.zip)

**Comment by jcarletto27** [comment]
sorry, wrong log file, this is the correct one
[_Log202408.zip](https://github.com/user-attachments/files/16567032/_Log202408.zip)

**Comment by jcarletto27** [comment]
After some digging it seems like it has to do with some of the file names so I adjust my regex and that seems to have helped. seems it didn't like anything with colons in the name. 

thanks

**Comment by rmcrackan** [comment]
Thanks for the follow up. In case it helps: Libation has settings for file path character replacements

**Comment by rmcrackan** [comment]
Much thanks for your paypal tip :D I really appreciate it
