### ISSUE TITLE
Split Folders based on Audible account

### ISSUE THREAD

**Issue by jcarletto27** [rmcrackan/Libation#952]
**Is your feature request related to a problem? Please describe.**
I would love to be able to have a different save folder for different audible accounts, this way it's easier to make different libraries in Audiobookshelf.

**Describe the solution you'd like**
the ability to assign a folder structure for different accounts on either the accounts page or in the settings page or at runtime in the cli

**Describe alternatives you've considered**
spinning up multiple docker containers to handle different accounts, but that's not very resource efficient/

**Additional context**
none at this time.

thanks so much for such a wonderful app!

**Comment by CLHatch** [comment]
> **Is your feature request related to a problem? Please describe.** I would love to be able to have a different save folder for different audible accounts, this way it's easier to make different libraries in Audiobookshelf.
> 
> **Describe the solution you'd like** the ability to assign a folder structure for different accounts on either the accounts page or in the settings page or at runtime in the cli
> 
> **Describe alternatives you've considered** spinning up multiple docker containers to handle different accounts, but that's not very resource efficient/
> 
> **Additional context** none at this time.
> 
> thanks so much for such a wonderful app!

Already possible to do (I do it myself).  Here's my current naming format that I use that works out very well for Audiobookshelf:

Folder Template: `<if podcast->Podcasts\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<pub date>) - <series> - <title> [<id>]<-if podcast><!if podcast->AudioBooks\Audible\<account nickname>\<author[separator(; )]>\<if series-><series>\<series#[00.##]> - <-if series>(<year>) - <title> [<id>]<-if podcast>`

File Template: `<audible title> [<id>]`

This sepeates things into `AudioBooks/Audible/Account Nickname/...` and `Podcasts/Audible/Account Nickname/...`.  It also puts the books into Series folders if it is a series.

![image](https://github.com/user-attachments/assets/1b9330a2-4043-4b3a-9791-02fe7e09f737)

**Comment by rmcrackan** [comment]
@CLHatch Thanks for keeping an eye on these questions. You have such good practical examples.

**Comment by CLHatch** [comment]
> @CLHatch Thanks for keeping an eye on these questions. You have such good practical examples.

You're welcome.  It helps in this example that the OP had the EXACT same use case as me (easily adding multiple sets of Audible accounts to Audiobookshelf).  Well, slightly different in my case... I have them in the same Audiobookshelf library.  I just point multiple folders to that library.

![image](https://github.com/user-attachments/assets/461c962f-5e1b-416b-acb0-0e06c6276d1a)

**Comment by jcarletto27** [comment]
This was fantastic and I missed the notification for it. I ended up writing some scripts to handle it after the fact, but this is miles better! I'll be updating my settings to match yours when I upgrade my hard drive tomorrow!

**Comment by CLHatch** [comment]
> This was fantastic and I missed the notification for it. I ended up writing some scripts to handle it after the fact, but this is miles better! I'll be updating my settings to match yours when I upgrade my hard drive tomorrow!

@rmcrackan and @Mbucari have been very accommodating where it comes to us Audiobookshelf users. :-D  They both have added some renaming tags and metadata tags that make it work very well for us. :-)

**Comment by CLHatch** [comment]
> This was fantastic and I missed the notification for it. I ended up writing some scripts to handle it after the fact, but this is miles better! I'll be updating my settings to match yours when I upgrade my hard drive tomorrow!

@rmcrackan and @Mbucari have been very accommodating where it comes to us Audiobookshelf users. :-D  They've both added some renaming tags and metadata tags that make Libation work very well for us. :-)

Incidentally, the naming pattern I use also handles "decimal" book numbers, say if you have a book that is listed as "Book 1.5" in a series.  That's what the `<series#[00.##]>` is for... it zero fills to two digits (`00`), plus allows decimal after (`.##`).

![image](https://github.com/user-attachments/assets/189f7475-c196-428d-a29f-5e7c8148ad24)
