### ISSUE TITLE
Error: Successful backups (264 titles) then instant license denial for remaining 356 titles

### ISSUE THREAD

**Issue by ziggytipper** [rmcrackan/Libation#953]
**Describe the bug**
Fully backed up 264 books in one session (mix of Canadian and Australian audible account). Attempted to resume backups of remaining 356 books (Canadian audible account). Error appeared "License denied" for every title. I verified that the affected titles were active in Audible Library (Canada) and working in the web player (Canada). Affected titles _seem_ to be only free titles + titles from plus catalogue. Titles paid with credits (also from Canadian store) did not deny and successfully downloaded and decrypted from what I observed.

I attempted various troubleshooting tips for this error though it doesn't seem to be as well documented as others, not recently at least. I tried to use a different recent Libation build (v11.3.14 and v11.1.0), I tried deleting "AccountsSettings.json" and re-entering account data, I tried logging in and out Amazon and Audible, and I tried disabling VPN. Next tip I will try is waiting as I've seen some users mention that works. I am open to other interventions in the meantime if possible.

**To Reproduce**

1. Go to Liberate>Begin Book and PDF backups
2. Downloads begin and then immediately fail.
3. See error

**Expected behavior**
I expected the books to download like the previous ones.

**Screenshots**
![image](https://github.com/user-attachments/assets/1c8f8d04-f277-4d95-b8a7-a87091d1cc91)

**Platform**

Windows 10

**Log Files**
Attach your Libation log file here.
[_Log202408_001.log](https://github.com/user-attachments/files/16570133/_Log202408_001.log)

**Comment by rmcrackan** [comment]
Sorry about this! Thank you for all of your diligence in troubleshooting. Something must have gone wrong during the log file upload so I can't dig into that.

With this particular error, I'd stop using Libation for 24-48 hours then try again to see if it resolved itself. I feel like there's a good chance that it will. If it doesn't, let's look at the new log in a few days and see if there are more details there.

**Comment by ziggytipper** [comment]
Cheers for the quick response! Sounds good :) I'll report back after that time then with the results. Amazon might not like me downloading too many books at a time haha

**Comment by rmcrackan** [comment]
Several users have reported this when downloading a ton of 'plus catalog' titles, and then it goes back to normal for them in a day or 2. I haven't seen it with purchased titles, but it makes sense that audible might always tweaking stuff behind the scenes. They're extremely not transparent with such things.

**Comment by ziggytipper** [comment]
Just checking in to note that it did indeed fix itself! And then promptly broke after exactly 200 more decrypts. I think it's clear it's an Amazon based restriction/bug in place, no fault to your tool whatsoever!

Or I guess since it's been going on long it's more of an Audible feature than a bug! haha

Here's my most recent log in case. Otherwise I guess it's safe to close this. :)
[_Log202408_001.log](https://github.com/user-attachments/files/16594847/_Log202408_001.log)
[_Log202408_001.zip](https://github.com/user-attachments/files/16594863/_Log202408_001.zip)

**Comment by rmcrackan** [comment]
Thanks for checking in. This is good info to have. I gathered from past users that it's "a lot". Nice to actually have a real number for it.
