### ISSUE TITLE
App not launching on windows 11

### ISSUE THREAD

**Issue by Eilaran** [rmcrackan/Libation#958]
**Describe the bug**
The Libation app does not launch at all, fresh download with not anterior versions/installs.
I tried with both Classic and Chardonnay versions 11.1.0
App files are on drive D: ; no special characters in any folder names, no spaces.
I did not find any logs in any user folder.
No instance of libation app in the task manager

**To Reproduce**
No idea, I simply tried to start using the Libation.exe app. Maybe an error due to my Documents folder being on D: ? 

**Expected behavior**
I was expecting the app to start

**Screenshots**
Not applicable here

**Platform**
Windows 11
Build 22631.3880

**Log Files**
No log file found

**Comment by rmcrackan** [comment]
Sorry about this. Did anything happen at all when you double-clicked the exe? Also, does it work if on C: ?

Btw, I'm about to be away from computers for a while so it may be a bit before I can get back to this.

**Comment by Eilaran** [comment]
There was a slight "blinking" like the app did start something, but nothing more

As for trying to have the install on C:, it did nothing more, same behaviour - both with classic and chardonnay

**Comment by rmcrackan** [comment]
Is anything displayed when you do this?

* Open the Windows folder containing Libation.exe
* In the folder's address bar, type `cmd` and press Enter
* In the command window which opens, type `Libation` and press Enter

![Screenshot 2024-08-16 10 14 06](https://github.com/user-attachments/assets/9c88a4b9-c3c4-404a-b728-30be5ec86bc8)

![Screenshot 2024-08-16 10 14 21](https://github.com/user-attachments/assets/b0c57900-3194-4ca8-8e7e-395294afcb54)

**Comment by Eilaran** [comment]
By launching from the command console, it did start the Welcome to Libation window
Thanks for the help
