### ISSUE TITLE
AudibleUK: Not seeing "Audible Collection" book

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#96]
In my Audible UK account, I have the Kobna Holdbrook-Smith narration of Nicholas Nickleby: The Audible Collection by Charles Dickens. This is not shown as part of my Libation list of books, and therefor not downloaded. (I can manually download all 19 parts of it, btw. )

This is an unusual book in that it was divided up into 19 separate downloaded parts.

![AudibleUK_01](https://user-images.githubusercontent.com/21000516/131368687-283378ce-848d-446a-bfed-bdd36cd8ecb8.jpg)

**Comment by rmcrackan** [comment]
You caught me -- episodic stuff is the only thing not supported in Libation. The files are easy enough to decrypt, but behind the scenes, audible does parent-and-episode relationships for episodes and podcasts differently than it does for normal titles. Generally these are things people just listen to once or twice and don't care about retaining/backing-up, so it never became a priority to add this feature. It sounds like I should add this feature back into the work queue.

**Comment by CharlieRussel** [comment]
Most times I wouldn't care, but this was one that is huge, and I will end up 'reading' it in chunks. Don't want it to disappear in the middle. Thanks for adding it to the queue.

**Comment by rmcrackan** [comment]
Added to [Libation v5.6.3](https://github.com/rmcrackan/Libation/releases/latest)

**Comment by CharlieRussel** [comment]
Thanks for fixing this!
