### ISSUE TITLE
Folder Images Are skipping on some downloads.

### ISSUE THREAD

**Issue by Dynamistic** [rmcrackan/Libation#964]
![image](https://github.com/user-attachments/assets/d40f54e6-40c6-40de-aba8-c396b63467cc)

Some of the folder images dont appear during download. I try redownloading the books and the folders still dont appear. 

Windows 10

**Comment by Dynamistic** [comment]
I figured out why its happening. When the folder name is too long it doesnt apply the folder icon. There also seems to be an issue with this and not downloading the PDF for it (if its available) on subsequent downloads.

**Comment by rmcrackan** [comment]
Interesting. Thank you for the follow up
