### ISSUE TITLE
PDF Downloaded, but showing not downloaded

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#97]
Libation is downloading the PDFs associated with my books, but the display shows the audio book downloaded, but not the PDF (has down arrow). When I check the book's folder, the PDF is there. Here's a screen shot from "In Pieces".

![AudibleUK_02](https://user-images.githubusercontent.com/21000516/131371800-6b143bb7-c116-4178-9e03-efc8b592fac3.jpg)

**Comment by rmcrackan** [comment]
Damn, I found this bug last week, fixed the code, then forgot to release the new version. Sorry about that. I'll have this out within the hour.

**Comment by rmcrackan** [comment]
[v5.5.9](https://github.com/rmcrackan/Libation/releases/latest) is released. Thanks for pointing this out.
