### ISSUE TITLE
Libation Chardonnay not opening, classic crashing.

### ISSUE THREAD

**Issue by Gorlock66** [rmcrackan/Libation#970]
**Describe the bug**
Libation Chardonnay not opening, classic crashing.
**To Reproduce**
Try to open Libation
[_Log202409.zip](https://github.com/user-attachments/files/16880679/_Log202409.zip)

**Expected behavior**
I expected Libation to open
**Screenshots**

**Platform**
Windows 11
[e.g. Windows 10, Windows 11, Mac, Linux (State distribution)]

**Log Files**
Attach your Libation log file here.
[_Log202409.zip](https://github.com/user-attachments/files/16880681/_Log202409.zip)

**Comment by rmcrackan** [comment]
Thank you very much for your log file.

Sorry about this bug. I've heard of something like this happening when the books directory has a ton of stuff from other programs in it. Your is just `Y:\\libation\\libationfiles` which looks pretty targeted to only audiobooks. How large is this folder?

**Comment by Gorlock66** [comment]
Thanks for the reply. The libationfiles folder is 5.85 TB. I did re-install yesterday with a fresh C:\Users\dwh_m\Libation folder. I ran through the registration and configuration, manually told 2 new books to download, then marked all the others as already downloaded. Closed Libation and neither Chardonnay or Classic open. Libation shows in task manager temporarily for both. Chardonnay doesn't open, Classic gives the popup error about submitting an issue. The logfile is after doing this. Thank you

**Comment by rmcrackan** [comment]
What's the total number of files in that folder?

**Comment by Gorlock66** [comment]
64,521 Files, 16,317 Folders

**Comment by rmcrackan** [comment]
Hmm, that doesn't feel excessive to me. I'm working on what I hope will be a fix for you. In the meantime, some things to check.

* Delete this folder: `C:\Users\dwh_m\AppData\Local\Temp\Libation`
* Open your Settings.json file (but please do not manually edit or save). Verify that `Books` and `InProgress` point to valid folders. Don't worry that some paths have the `\\\\?\\` or `\\?\` prefix.

**Comment by rmcrackan** [comment]
I created this pre-release version for you. Please let me know if it fixes your issue. If you're still getting bugs, please attach the new log file:

https://github.com/rmcrackan/Libation/releases/tag/v11.3.15

**Comment by Gorlock66** [comment]
I am at work, but will test later today and let you know. Thank you

**Comment by Gorlock66** [comment]
I deleted: C:\Users\dwh_m\AppData\Local\Temp\Libation
The Books path was correct. The InProgress entry did not exist in the Settings.json with Chardonnay 11.1.0 or 11.3.15.
Libation.11.3.15-windows-chardonnay seems to have resolved the issue. I have opened and closed Libation multiple times and downloaded one new book.

I appreciate your quick response and help with resolving my issue.

**Comment by rmcrackan** [comment]
w00h00 -- thank you much for your follow up. I'm glad I was able to resolve it. Thanks for helping me debug this issue
