### ISSUE TITLE
Please add Series as a Boolean for filtering

### ISSUE THREAD

**Issue by CharlieRussel** [rmcrackan/Libation#973]
**Is your feature request related to a problem? Please describe.**
I'm trying to clean up my library and it doesn't appear possible to filter by those books that are NOT in a series. 

**Describe the solution you'd like**
Add a simple Boolean field of Series or NotSeries (equivalent to what you do with Podcasts)

**Describe alternatives you've considered**
I tried to figure out a string filter that would work but failed miserably. 

**Additional context**
I've got a bunch of books (hundreds!) that were downloaded to folders that did NOT include Author because I set up my file naming wrong. I've fixed that, but now I have a bunch of books that need re-downloading to get things right. And I really, really don't want to do this one by one. 
Thank you!

**Comment by rmcrackan** [comment]
Shouldn't be too hard. One warning though: search filters evaluate each book distinctly. This means I can add the ability to say that it is or isn't in a series. What cannot easily be added is whether you have more than one book from that series in your own library. This means that if audible says it's in a series for any reason, it's going to show up with such a filter. And if audible does not correctly put it in a series, it won't. (I have both of these obnoxious errors in my library.)

**Comment by CharlieRussel** [comment]
Well, @rmcrackan, I wouldn't expect anything different from Audible. And I suspect it will give me at least a couple of errors, but they will just have to be dealt with on an individual basis. Better than my current situation. And frankly, unless it's a series I've completely abandoned, chances are even if I only have a single book, I'll likely have more later. ;)

**Comment by rmcrackan** [comment]
Here ya go: https://github.com/rmcrackan/Libation/releases/tag/v11.3.17

"Series" is already used for something else. `IsInSeries` and `InSeries` are now synonyms for having an empty series field. Or filter by with-series with a minus. ie: `-InSeries`

**Comment by CharlieRussel** [comment]
-InSeries makes the most sense for me, so perfect. Thanks!

Charlie Russel (he/him/his)
________________________________

**Comment by CharlieRussel** [comment]
@rmcrackan -- Well, it's there, but doesn't appear to be working. Undoubtedly something isn't right with what Audible is doing...
-InSeries comes up blank, while InSeries includes every book.

**Comment by rmcrackan** [comment]
Sorry, forgot to mention: you need to do a scan to re-populate the search index

**Comment by CharlieRussel** [comment]
@rmcrackan -- Duh, of course one does. And now it works as expected. Thanks!!
