### ISSUE TITLE
Accidentally deleted books from folder, can I "Re Liberate" books that I have accidentally deleted?

### ISSUE THREAD

**Issue by GrumpyMonk7973** [rmcrackan/Libation#981]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by rmcrackan** [comment]
Sorry about the confusion. Go to settings > trash bin. It’s kinda a limbo. You can un-delete or fully delete books from there. (Fully deleted books which are still in your audible library will return during your next scan)

**Comment by rmcrackan** [comment]
To re-liberate a not deleted book (or un deleted book), it’s in the right-click options

**Comment by GrumpyMonk7973** [comment]
Thanks! I had figured it out a little last night. I did it the hard way, but I got it to work. Thanks for the quick response thought!
