### ISSUE TITLE
Libation not decrypting m4b

### ISSUE THREAD

**Issue by kilowhiskey202** [rmcrackan/Libation#982]
Libation works beautifully on my MacBook except for one thing - the m4b files I download still say "Protected mpeg 4 audiobook." I've set everything up according to the instructions and gone through each option in Settings. If I convert to mp3, everything's fine, but m4b always shows as protected. I also noticed that it never actually ran an initial decryption process after setup. I'm running Libation Chardonnay v11.1.0.1 on macOS Ventura 13.7.

Is there something simple that I'm missing?

<img width="895" alt="Libation_Protected-m4b" src="https://github.com/user-attachments/assets/135f0f77-77de-4477-a1d7-3e40dab77ada">

**Comment by rmcrackan** [comment]
You're good. That description is the operating system's description of this file type. For whatever reason, this OS thinks all "m4b" files are "protected mpeg 4 audiobook". Windows says the same for m4b files even though these are not "protected" in any way.

I suspect historical reasons. Some quick googling shows that m4b is a format which apple once used to copy protect their m4a audiofiles. Who knows why the same file type is now used for unprotected audiobooks.

Pontificating aside, you'll know if these are truly unprotected if you can play them on apps which have no access to the decryption keys. For example: VLC is free and plays this file type. If it can play your audiobook, then it's not actually encrypted/protected.
