### ISSUE TITLE
Libation cannot open

### ISSUE THREAD

**Issue by VaHiX** [rmcrackan/Libation#988]
**Describe the bug**
After upgrade to Version 15.1 Beta (24B5055e) it cannot open, I reinstall it but no different.
The app was authorized in the security setting.

**To Reproduce**
Upgrade to Version 15.1 Beta (24B5055e)
Run the app.

**Platform**
Mac OS X Sequoia Version 15.1 Beta (24B5055e)

**Comment by tothemoonsands** [comment]
I created issue that notes several problems with Mac 15.0 (inability to hide, always crashes after a period of time, etc.)
That's too bad to hear about worse issues with 15.1
I'm hoping these issues gain the attention of the devs, this is such a fantastic app and I hate the prospect of losing it now in MacOS Sequoia.

**Comment by rmcrackan** [comment]
Does this help? https://support.apple.com/guide/mac-help/apple-cant-check-app-for-malicious-software-mchleab3a043/mac

**Comment by rmcrackan** [comment]
Duplicate of #983
