### ISSUE TITLE
Won't accept correct email and password

### ISSUE THREAD

**Issue by scottsab** [rmcrackan/Libation#990]
Please help. When I log in through Libation, in either the simple method or the copy-the-long-URL method, Audible gives me an error saying "There was a problem. Your email or password was incorrect. Please try again." I am definitely typing in the correct email and password. I tried at least 8 times. I tried it in both Opera and Google Chrome browsers. I even tested the email and password by going to a different computer and logging directly into Audible using that email and password, and the login was successful. Please help, I very much want to use Libation. I am using Windows 10 , 64 bit. Please email me.
Thank you so much, 
Scott
teamdba@yahoo.com

**Comment by rmcrackan** [comment]
Sorry about this. If you're absolutely sure that the user/email and pw are correct, make sure the correct region/country is selected.

**Comment by rmcrackan** [comment]
I'll also copy this to an email to you soon.

**Comment by rmcrackan** [comment]
Closing. Solved via email.
