### ISSUE TITLE
Unable to import library

### ISSUE THREAD

**Issue by Brent-Metalhead** [rmcrackan/Libation#991]
**Describe the bug**
I get an error when trying to import my Audible, stating something about an API error being thrown

**To Reproduce**

Just added my associated email to my audible account and attempted a library scan

1. Go to 'Import'
2. Click on 'Add Account'
3. Added my audible account
4. See error "Error importing library. Please try again. If this still happens after 2 or 3 tries, please contact support"

**Expected behavior**

**Screenshots**

![2024-10-05 22 18 14](https://github.com/user-attachments/assets/38c27a0d-0c3c-4c74-9b32-c822e23ad2bb)

**Platform**

Windows 10

**Log Files**
Attach your Libation log file here.
[_Log202410.zip](https://github.com/user-attachments/files/17267895/_Log202410.zip)

**Comment by rmcrackan** [comment]
Sorry about this. Thank you very much for attaching the log -- it was helpful. All errors seem to be `The request failed due to timeout.` Please try again after 24-48 hours and see if this error solves itself. If it does not, please post your new log here and I'll dig a bit deeper.

**Comment by Brent-Metalhead** [comment]
Understood

**Comment by rmcrackan** [comment]
Any change?

**Comment by Brent-Metalhead** [comment]
Yeah it worked after a day. Forgot to update, my bad
 
 
  On Tue, Oct 8, 2024 at 10:25 AM, ***@***.***> wrote:   


Any change?

**Comment by rmcrackan** [comment]
No worries. Thanks for the update. Glad it's back.
