### ISSUE TITLE
Disable annoying shrink/expanding scrollbars

### ISSUE THREAD

**Issue by cbordeman** [rmcrackan/Libation#993]
I've fixed this, submitting a small PR to do it.

Scrollbars everywhere (particulary on the main product list) are so freaking tiny, it's really hard to locate them and click and start to scroll.  When you mouse over scrollbars, they grow to a normal size, but I think it would be so much better if they were a normal size all the time.

This does _not_ refer to autohide, where scrollbars are not present when the contents are small.

**Comment by cbordeman** [comment]
The PR is #994

**Comment by cbordeman** [comment]
Nice!  Although I'm technically just over the border in Fort Mill, SC now.

**Comment by rmcrackan** [comment]
Fair enough. I have family in Rock Hill and we still say they're in Charlotte.
